### ISSUE TITLE
Restrict individual live streams to specific user Groups

### ISSUE THREAD

**Issue by eliataylor** [LuatixHQ/opencti#1569]
## Use case

Currently the "Connect and consume the platform stream" permission expose ALL streams.

## Current Workaround

We can only allow access to all or no streams currently.

## Proposed Solution

Add a User Group field to the Live Stream form.

## If the feature request is approved, would you be willing to submit a PR?

Sure

**Comment by SamuelHassine** [comment]
Hello @eliataylor,

That's an interesting feature request thanks. Just to let you know, Stream only contain the allowed marking definitions of the group of the user consuming the stream.

So if the user does not have access to TLP:RED for instance, the stream will filter TLP:RED content.

Kind regards,
Samuel
