### ISSUE TITLE
Populate x_opencti_additional_names field of File observable when merging multiple file names

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1570]
## Use case

Often, artifacts have different names, and these names are parsed as separate objects by a collector. The merge feature works best with hash(es) and a single file name. If multiple file names are selected to be merged, it would be useful if the secondary names (underlined in red in the screenshot below) were added to the x_opencti_additional_names field.

In this vein, it would be useful to have some guidance on the best way to delimit multiple file names in the x_opencti_additional_names field. We currently use pipes :)

Finally, it appears that no more than four observables can be merged a time - which is just a minor inconvenience.

## Current Workaround

Manually add additional file names to the x_opencti_additional_names field

## Proposed Solution

If merging multiple file names, add the secondary names to the x_opencti_additional_names field

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/133860326-8869f7b0-903f-4e0c-993b-55028b5732cc.png)

## If the feature request is approved, would you be willing to submit a PR?

No, no dev experience :(

**Comment by richard-julien** [comment]
Linked to https://github.com/OpenCTI-Platform/opencti/issues/1564 as a global merge retention improvment
