### ISSUE TITLE
Implement missing STIX relationships

### ISSUE THREAD

**Issue by nor3th** [LuatixHQ/opencti#1573]
## Use case

Implement missing STIX 2.1 relationships.

## Current Workaround

Relationships are not available

## Proposed Solution

Implement relationships

## Additional Information

I wrote this script (https://github.com/nor3th/furry-chainsaw/blob/main/opencti/relationships_test.py) to scrap all relationships from the STIX 2 documentation and verify (in a bit of an ugly way) against the OpenCTI implementation.

**Precondition: Merging the list items from here https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-front/src/utils/Relation.js#L85-L90 into one line (otherwise the regex won't work... I was too lazy to fix that)**

This is the result:
```
$ python3 relationships_test.py  ../opencti/opencti-platform/opencti-front/src/utils/Relation.js
---- Parsing entire page ---- 
Course-of-action_Malware(.*) needs relationship remediates
Course-of-action_Vulnerability(.*) needs relationship remediates
Didn't find Infrastructure_<all stix cyber-observable objects>(.*) <--- ignore
Intrusion-set_Infrastructure(.*) needs relationship owns
Malware_Infrastructure(.*) needs relationship exfiltrates-to
Threat-actor_Sector(.*) needs relationship attributed-to
Threat-actor_Sector(.*) needs relationship impersonates
Didn't find Tool_Infrastructure(.*)
Didn't find Tool_Infrastructure(.*)
Didn't find Domain-name_Domain-name(.*)
== Result ==
Object to Object found/not found 172/4
Object relationships found/not found 166/6

[...]
```
Meaning:
- CoA - Malware is missing the relationship `remediates`
- CoA - Vulnerbility is missing the relationship `remediates`
- Intrusion-Set - Infrastructure is missing the relationship `owns`
- Malware - Infrastructure is missing the relationship `exfiltrates-to` (in fact this is a typo which is also present in the summary table here https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_6n2czpjuie3v where `exfiltrate-to` is implemented (w/o the `s`))
- Threat-Actor - Sector is missing the relationship `attributed-to` and `impersonates` (I am not sure if this is intended or not, since the other identity SDOs do have this relationship. I understand as well if this was left out on purpose)
- Tool - Infrastructure relationships are missing at all
- Domain-Name - Domain-Name relationships are missing at all

I am leaving out the Malware-Analysis relationships, since that SDO isn't implemented yet in OpenCTI.

## If the feature request is approved, would you be willing to submit a PR?

Yes, if it only consists of modifying the `Relationship.js` (from opencti-front) and the `stix.js` (from opencti-graphql) files.

**Comment by SamuelHassine** [comment]
Very nice work @nor3th. This script is quiet useful! You can propose modification by modifying the 2 files. But please take a look at `Localization.js` in `opencti-front` as well :)

**Comment by nor3th** [comment]
Hey @SamuelHassine 

Thanks for the feedback. Should I maybe extract the relationships into a json file to be included in an opencti test case?
What should I look for in the `Localization.js` file? Misspelled relationship names or anything else as well?

Regards

**Comment by securitiz** [comment]
+1 for this feature :) thanks for the work on this @nor3th @SamuelHassine
