### ISSUE TITLE
Self-signed Certificate Error

### ISSUE THREAD

**Issue by r0sier** [LuatixHQ/opencti#1574]
## Description

I'm trying to install a self-signed certificate onto my OCTI instance. I have specified APP__HTTPS_CERT__CA, APP__HTTPS_CERT__KEY, and APP__HTTPS_CERT__CRT from a local mounted volume. However, OCTI platform throws the following error:
```
TypeError: CA_CERTS.map is not a function
    at /opt/opencti/build/src/http/httpServer.js:25:25
```

## Environment

1. OS: Ubuntu 18/ Docker
2. OpenCTI version: 5.0.0
3. OpenCTI client: Platform

**Comment by SamuelHassine** [comment]
Hello @r0sier,

Can you please use this envvar:

```
- "APP__HTTPS_CERT__CA=[\"/path/to/ca.cert\"]"
```

With a list and not just a string.

**Comment by r0sier** [comment]
Many thanks @SamuelHassine. I should have read the documentation better!
