### ISSUE TITLE
Implement more complex exports forms

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1576]
## Use case

The following issue suggest to establish a more complex and whole filtering system for exports, in order to make sure that no data is exported when it should not.
In addition, this issue aims at taking into account the increasing possibilities of exports with the different fields in OpenCTI and allowing for a finer tuning of the content of the export.
This issue deals only with the existing "Files & History" tab in the "exported files section". For other exports, see #1374 
What is suggested is to add filtering menus and step-by-step options to the current menu while generating the export.

The following filters are would be necessary :

-taking into account the fact that there are different types of markings which can be cumulated (such as TLP + classification + commercial + specific sharing community). It is necessary to be able to have filters cumulating several of these types. For instance, in the dialog menu, we could have a menu asking for the marking type and then offering to set the level desired for this type ;

-for each marking type, it could be possible to choose a minimum level, a maximum level, both or a finite list of marking values included in the export. The specific case of "no marking of this type" should be an option of this finite list to be able to export all data with no TLP specified for example.

- additional filters on authors, tags, date of creation (relative and absolute) should be possible and useful for complex exports, to filter the exported neighbors of the entity. The filters could be similar to those of the research field, except for the global keyword, which is not necessary.

## Current Workaround
Export a JSON and clean it by hand (not satisfactory), or not using OpenCTI.

**Comment by SamuelHassine** [comment]
Filters are now taken into account in exports.
