### ISSUE TITLE
Upload of an encrypted artifact

### ISSUE THREAD

**Issue by 2xyo** [LuatixHQ/opencti#1579]
## Use case

Upload of an encrypted artifact in one step.

## Current Workaround

- initial situation : an analyst had a password protected zip file with the artifact inside
- on OpenCTI, click create an artifact
  - Select the artifact to upload then click [create]
- open the  artifact
  - set the `decryption_key`
  - set the  `encryption_algorithm` to `mime-type-indicated`
  - update the `has_md5`, `hash_sha-1`, `hash_sha-256` with the hash of the artifact (because the actual hashes are the hashes of the zip archive)

## Proposed Solution

- initial situation : an analyst had a password protected zip file with the artifact inside
- on OpenCTI, click create an artifact
  - Select the artifact to upload
  - set the password (optional field) 
  - click [create]
 
 
## Additional Information

- It doesn't work well if the zip archive has multiples  files insides.
- if the mime type is `application/zip`, it would be nice to try common password like `infected`, `malware`, so the analyst doesn't even need to enter the password as he usually does in other products that test these passwords.
- For zip files, the filed `encryption_algorithm` should be set to `mime-type-indicated`
- would be great to also update the value of `SSDEEP` and `TLSH` (from `hash-algorithm-ov`)

## If the feature request is approved, would you be willing to submit a PR?

No, I don't speak React properly, you will spend more time understanding / correcting my PR than doing it.

**Comment by SamuelHassine** [comment]
Duplicate #1580.
