### ISSUE TITLE
Download artifact as a zip password protected archive

### ISSUE THREAD

**Issue by 2xyo** [LuatixHQ/opencti#1580]
## Use case

- A raw artifact (malware) is uploaded to OpenCTI by analyst A. 
- Analyst B would like to download the artifact without triggering the antivirus/EDR/XDR on his workstation. 

## Current Workaround

None.

## Proposed Solution

- On the artifact view, add a button [Download  with a password]
- Open a dialog box with the proposed `infected` password and a button [Download]
 - Then the artifact is downloaded as a zip password protected archive and everyone is happy

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by leetn00b** [comment]
@2xyo Can we amend the proposed solution to additionally include the ability to download multiple files at once via the Observations page? For example, if I filtered down a list of Artifacts or Files I wanted to download, then clicked the checkboxes or the Select All checkbox, I should be able to download all of those files at once, and be able to specify whether or not to auto-paginate for all pages remaining or just the current page.

**Comment by YungBinary** [comment]
@SamuelHassine Can we have another look at this? This issue wasn't for uploading as password protected, but for downloading.

**Comment by GraemeMeyerGT** [comment]
@YungBinary it's very imperfect, but it seems you can just delete the files from the Artifact directory and OpenCTI simply removes the Download button and it all seems to work well. Obviously this won't be useful if _some_ people need to access the files, but if nobody needs to download the files then to prevent people from accidentally downloading them, it might be enough.

@SamuelHassine I see you've added a P1 tag to this - is this an indicator of the roadmap/development priority? I can't find the current OpenCTI roadmap anywhere.
