### ISSUE TITLE
Multiple Groups in SAML response are seen as a single string

### ISSUE THREAD

**Issue by elouieibm** [LuatixHQ/opencti#1603]
## Description

When authenticating using SAML, authentication fails if the user is a member of multiple groups.  

In our environment, if a user is a member of multiple groups the groups are returned as "Group1","Group2".  It seems that OpenCTI sees this as a single string.

## Environment

1. OS (where OpenCTI server runs): RHEL 7.9
2. OpenCTI version: 5.0.0
3. OpenCTI client: frontend
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Environment is configured with the following:
     - "PROVIDERS__SAML__CONFIG__ROLES_MANAGEMENT__ROLE_ATTRIBUTES=[\"Groups\"]"
      - "PROVIDERS__SAML__CONFIG__ROLES_MANAGEMENT__ROLES_MAPPING=[\"OCTIGroup:Default\"]"

2. Login to OpenCTI by clicking on SAML button
3. Get redirected to SAML authentication page and authenticate as a user
4.  Authentication succeeds, but get redirected to OpenCTI login page if the authenticated user belongs to multiple groups.  The OpenCTI dashboard displays if the user is a member of a single group.

## Expected Output

User is redirected to the OpenCTI dashboard even if they are a member of multiple groups.

## Actual Output

Users with membership to multiple groups are redirected to the login page
 
## Additional information
I am not sure if this is a quirk of how our servers are returning multiple groups.  I resolved the issue by updating providers.js with a check to determine if the group list contained "commas".  If so create an array of the group entries and store the array into the profile["<ROLE_ATTRIBUTES>"] value

Thank you

## Screenshots (optional)

**Comment by richard-julien** [comment]
Hi @elouieibm , in all our users use case for now the SAML response reply an array of groups. It is impossible for you to configure your saml providers to respond with an array instead of the string with comma?

**Comment by elouieibm** [comment]
Hi @SamuelHassine 
Thank you for your assistance.  I worked with our SAML team and they were able to change the response to an array and the issue is resolved.  Thank you again for you help.
