### ISSUE TITLE
Search OpenCTI based on an STIX indicator patter

### ISSUE THREAD

**Issue by Fran992** [LuatixHQ/opencti#1604]
Hello,
I'm new in this community and I just installed OpenCTI few days ago, but I have a couple of questions about indicators.

After reading some articles (about stix and opencti) and did some tests on opencti demo, I'm still wondering how to have all observables that have a common charateristic wrote in indicator stix pattern.
For example, if I have an indicator like this: [email-message:subject = 'Hello'], can I get all the observables (type email messages) that contain the word "Hello"? If yes how?

Thanks for your help, I know that is a basic question but I really want to start with this tool.

Best regards,

**Comment by nor3th** [comment]
Hey @Fran992 

Under Analysis -> Observations, select E-Mail Message and then search for "Hello".
Does this answer your question?

![screen4](https://user-images.githubusercontent.com/73965465/135680426-ba8360f1-d00d-464e-b5a1-b145c101a3f7.png)
https://demo.opencti.io/dashboard/observations/observables?sortBy=created_at&orderAsc=false&searchTerm=Hello&filters=%7B%7D&observableTypes=Email-Mime-Part-Type%2CEmail-Message

Please also use the question issue template for future questions.

Regards,

**Comment by Fran992** [comment]
Hi @nor3th thanks for the reply, but no it was not what I was looking for.

Let me clarify.

Reading the stix docs: "_Indicators contain a pattern that can be used to detect suspicious or malicious cyber activity. For example, an Indicator may be used to represent a set of malicious domains and use the STIX Patterning Language to specify these domains._" and also "_in general an Indicator is considered to have "matched" (or been "sighted") when the conditions specified in the structured pattern are satisfied..._"

So Stix Pattern can also be used for "complex" pattern like this: e.g. "_([ipv4-addr:value = '198.51.100.1/32' OR ipv4-addr:value = '203.0.113.33/32' OR ipv6-addr:value = '2001:0db8:dead:beef:dead:beef:dead:0001/128'] FOLLOWEDBY [domain-name:value = 'example.com']) WITHIN 600 SECONDS_"

Considering that Opencti is based on the STIX standard and Opencti create a relationship between observables and indicators (for example, as shown in the following figure)
![image](https://user-images.githubusercontent.com/91552512/135994105-874c5fa7-24fa-4ad4-9914-8c587803823e.png)

I was wondering if it is possible to get all the observables that match the expression specified in an indicator (using the stix pattern)? If yes, how?

Regards,

**Comment by nor3th** [comment]
Hey @Fran992 

No this feature is not available. 
@SamuelHassine a feasible feature request to search simply providing a STIX indicator?

Regards

**Comment by Fran992** [comment]
Thanks again @nor3th 
Just the last question. 

If I create an indicator (for example: [ipv4-addr:value='192.168.1.2'] ) with " detection = yes " and then (at a later time) I add the observable (with value  '192.168.1.2'), is opencti able to link the observable to the indicator?

Because I tried the following scenario on opencti, but it seems that no relationship (or detection) was created between the indicator and observable. Is it correct? or a bug? (or I missed something)?

Thank you in advance

**Comment by nor3th** [comment]
Hey

No OpenCTI won't link the observables after changing the indicator. You have to manually create the relationship between the indicator and the new observable.

Regards,

**Comment by Fran992** [comment]
Thanks for your time!

**Comment by nor3th** [comment]
I'm reopening this as a feature request, since Samuel said it might be a feasible addition.

**Comment by Fran992** [comment]
That sounds great! Have you got a roadmap about this feature? In which version will be included?
Thanks!

**Comment by nino-filigran** [comment]
@Fran992 considering that you can now filter on pattern (indicator pattern), and use the operator contains or start with, you should be able to achieve your request.
As a result, I'm closing this feature request. If it does not meet your needs though, please feel free to reopen this ticket and drop a comment. 

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/978bd7b5-bd4a-4de6-8321-a632ce989979)
