### ISSUE TITLE
Ability to control merging of entities

### ISSUE THREAD

**Issue by samjackson200** [LuatixHQ/opencti#1610]
## Use case

OpenCTI currently seems to merge Intrusion Sets together whenever there is a match of aliases. This sometimes works well when there is merging of data from two sources that use different names for the intrusion set (i.e. APT29 from ATT&CK and Cozy Bear from Crowdstrike are merged into a single entity). At other times this correlation actually causes issues when a particular vendor has two discrete intrusion sets but are suspected to be linked and therefore have similar aliases; but due to this overlap in aliases the two intrusion sets are merged by OpenCTI but this merging would actually be incorrect in this instance. 

## Current Workaround

There is no effective work around for this, Intrusion sets have to be manually recreated and this usually causes data management issues later on as data later added does not get linked to these additional entities.

## Proposed Solution

To be able to manually define the criteria in which Threat Actors/Intrusion Sets are merged together. For example, you could control the number of aliases that have to match before intrusion sets are merged. In cases where there is a alias correlation, but it is below the defined threshold then a link could be defined between the two but not merged, and then OpenCTI alerts the administrator/data manager to allow or deny the merge. In cases where there may be a entity imported that is related to a particular intrusion set, but there are two intrusion sets with that alias, then the entity would be linked to both entites and again the data manager informed. 

## If the feature request is approved, would you be willing to submit a PR?

Can't do a PR, but happy to help in another way if I can.

**Comment by manonviallet** [comment]
Tell me if this should be a distinct issue, but it would be highly useful to have a similar feature for the merge of relations: meaning that auto-merge of similar relations should be approved (or maybe manual approbation of merges could be a feature that can be activated or disabled by the the administrator of the platform).
The identified problem is the automatic merge of relations which have different marking levels but similar dates.

**Comment by manonviallet** [comment]
In addition (should have started with this one first), we also identified this issue of "abusive" merge of entities, especially for intrusion sets, and also for actors and for campaigns, and are definitely having the same ideas as the ones suggested above !

**Comment by SamuelHassine** [comment]
Merging of entities is now more guided:

* UPDATE_EXISTING_DATA=true will merge
* In all cases, upsert is leaded by the confidence level
* Confidence level is also taken into account into the merge process (target entity is always the highest).
