### ISSUE TITLE
Mass Modification or filtering over OpenCTI

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#1613]
I want to do mass modification over entities in OpenCTI, however I end up doing them manually one by one.
Is there is any feature or a way that can allow me to do mass modification and filtering over the tool?

**Comment by SamuelHassine** [comment]
Hello @Sarah-Elnagdy,

It's available in the platform. Please use the `data/entities` section for SDOs and `observations/observables` for SCOs. Then you have filters, select all capabilities. With massive operations possible:

![image](https://user-images.githubusercontent.com/1334279/135766011-a717956b-3cc4-4a28-b85d-7cc6d56bf8c0.png)

Kind regards,
Samuel

**Comment by ghost** [comment]
Thank you Samuel; however when I select a field I don't get the toast that should enable me to modify or delete entities.
I used to get that toast but now can't seem to appear any longer.
![image](https://user-images.githubusercontent.com/8087967/135816029-f62a403d-601a-4a88-a97f-1937541b7a3a.png)

**Comment by richard-julien** [comment]
The panel on the right allow you to filter the list.
Then you have to select the entities (check box) on the left to be able to apply actions

**Comment by ghost** [comment]
Thanks Richard.

**Comment by ghost** [comment]
One more question @SamuelHassine @richard-julien, is there is any way we can modify data via script instead doing it via the GUI?

**Comment by richard-julien** [comment]
Yes. Your script can directly use the graphQL Api to execute some actions. You can also use the python lib that will give you direct methods
