### ISSUE TITLE
Platform trying to re-initialise after environment crash

### ISSUE THREAD

**Issue by kanniget** [LuatixHQ/opencti#1614]
## Description

My infrastructure suffered a complete power outage overnight and now the platform will not start.

I have had an instance of Opencti running in a docker containers for the last 4 weeks, last week I successfully upgraded from 4.5.5 to 5.0.1 and the environment was running very well.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Alpine Linux 3.14.2
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
5.0.1
3. OpenCTI client: { e.g. frontend or python }
frontend
4. Other environment details:
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS

09d9c07fc53d   opencti/platform:5.0.1                                 "/sbin/tini -- node …"   28 minutes ago   Restarting (1) 26 seconds ago                                                                                                                
38b57cd06194   opencti/worker:5.0.1                                   "python3 worker.py"      2 days ago       Restarting (1) 21 seconds ago                                                                                                               
994ffeade00b   opencti/worker:5.0.1                                   "python3 worker.py"      2 days ago       Restarting (1) 20 seconds ago  
7a330e6796e0   opencti/worker:5.0.1                                   "python3 worker.py"      2 days ago       Up Less than a second                                                                                                                        
108f5dbe8b6c   opencti/worker:5.0.1                                   "python3 worker.py"      2 days ago       Restarting (1) 34 seconds ago                                                                                                                
cb8a47af15d5   opencti/connector-export-file-stix:5.0.1               "/entrypoint.sh"         2 days ago       Up Less than a second                                                                                                                        
53efd51c507b   opencti/connector-ipinfo:5.0.1                         "/entrypoint.sh"         2 days ago       Restarting (1) 32 seconds ago                                                                                                                
3a5c6c530239   opencti/connector-export-file-csv:5.0.1                "/entrypoint.sh"         2 days ago       Up 1 second                                                                                                                                  
1e95ce9044c6   opencti/connector-import-report:5.0.1                  "/entrypoint.sh"         2 days ago       Restarting (1) 12 seconds ago

fa923045e24e   opencti/connector-import-file-stix:5.0.1               "/entrypoint.sh"         2 days ago       Up 2 seconds                                                                                                                                 
d885343ef37a   opencti/connector-opencti:5.0.1                        "/entrypoint.sh"         2 days ago       Up Less than a second                                                                                                                        
b87a28002d99   opencti/connector-history:5.0.1                        "/entrypoint.sh"         2 days ago       Restarting (1) 32 seconds ago

d0b55f609c2c   opencti/connector-virustotal:5.0.1                     "/entrypoint.sh"         2 days ago       Restarting (1) 40 seconds ago

82ddb4fd9492   docker.elastic.co/elasticsearch/elasticsearch:7.15.0   "/bin/tini -- /usr/l…"   2 days ago       Up 47 minutes                   9200/tcp, 9300/tcp

f4966d26480a   minio/minio:RELEASE.2021-09-15T04-54-25Z               "/usr/bin/docker-ent…"   2 days ago       Up 11 hours (healthy)

80b86be2de78   rabbitmq:3.9-management                                "docker-entrypoint.s…"   2 days ago       Up 11 hours                     4369/tcp, 5671/tcp, 15671-15672/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp   

841034c0000f   redis:6.2.5                                            "docker-entrypoint.s…"   2 days ago       Up 11 hours                     6379/tcp                                                                                                    

## Reproducible Steps

Lose power to your environment unexpectedly  ;-)

## Actual Output
{"category":"APP","version":"5.0.1","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-10-04T01:09:35.512Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-10-04T01:09:35.561Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-10-04T01:09:35.580Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-10-04T01:09:35.611Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client base' client ready","timestamp":"2021-10-04T01:09:35.625Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-10-04T01:09:35.626Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] SMTP is alive","timestamp":"2021-10-04T01:09:35.642Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-10-04T01:09:36.144Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2021-10-04T01:09:36.152Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2021-10-04T01:09:36.156Z"}
{"query":{"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"ignore_throttled":false,"track_total_hits":true,"body":{"size":200,"sort":[{"standard_id.keyword":"asc"}],"query":{"bool":{"must":[{"bool":{"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}],"minimum_should_match":1}}],"must_not":[]}},"runtime_mappings":{}}},"category":"APP","version":"5.0.1","level":"debug","message":"[ELASTICSEARCH] paginate","timestamp":"2021-10-04T01:09:36.159Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2021-10-04T01:09:36.173Z"}
{"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-10-04T01:09:36.178Z","data":{"reason":"[INIT] Fail initialize schema, index already exists","http_status":500,"category":"technical"},"internalData":{}},"category":"APP","version":"5.0.1","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-10-04T01:09:36.178Z"}
{"category":"APP","version":"5.0.1","level":"info","message":"[INIT] Platform initialization done","timestamp":"2021-10-04T01:09:36.180Z"}

/opt/opencti/build/src/config/errors.js:8
  return new Exception();
         ^
ConfigurationError: A configuration error has occurred
    at error (/opt/opencti/build/src/config/errors.js:8:10)
    at ConfigurationError (/opt/opencti/build/src/config/errors.js:53:3)
    at /opt/opencti/build/src/initialization.js:142:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at initialization (/opt/opencti/build/src/initialization.js:379:20)
    at /opt/opencti/build/src/boot.js:7:16

**Comment by richard-julien** [comment]
This error occurred when you have the indices available in elasticsearch but without any data created when opencti do its initialization. This is for opencti and inconsistent state that prevent the platform to start.

As your data are empty after your crash (dont know why) you have to 2 solutions
1. Restore a correct backup and restart
2. Delete your indices and so restart from fresh

**Comment by kanniget** [comment]
This doesnt make sense, How can there be no data created at initialisation yet there be data in the indices?  surely the system has to have been initialised previously to have data in the indices.  It looks to me that the system sometimes tries to initialise itself on startup despite already previously been operating fine and as a result corrupts itself.

Has a proper backup strategy been developed yet? I have seen discussions where the backups were discussed but no satisfactory solution has been presented as far as I can see.

If a complete reload from the beginning is the only option for a failure like this then I have serious concerns recommending this tool to customers of mine.

**Comment by richard-julien** [comment]
Trying to explains a bit more.
When platform starts, different steps occurred:

SECTION 01
1. Platform check if the indices exists
2. If YES -> Move to SECTION 02
3. If NO -> Create the indices
4. Then creates the migration structure, base data, admin user, ...
5. Finally start

SECTION 02
1. Check if basic data exists (Migration structure)
2. IF NOT -> Platform error -> [INIT] Fail initialize schema, index already (Its your current state)
3. IF YES -> Reinit the admin user then start

This error can happens if for any reason a crash occurred after indices creation but before data init when initializing the platform. Its uncommon but it can happen. The solution of that is to reset the elastic to restart from 0. I should be acceptable because its a start fresh in both case.

This kind of situation should not happen in case of big crash like yours the data are not lost. Have you configured the docker volume to be resilient?

For the backup strategy, today we recommend to use the backup strategy of elasticsearch. https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html
We currently developing some other strategy to export/backup data in files but an elasticbackup works very well and its already use by a lot of opencti customers.

Hope this explanation helps :)

**Comment by kanniget** [comment]
Thanks for going into more detail, and thankyou for sharing the backup strategy, I will look at this.

Yeah, my volumes are resilient, mapped to external storage.  

I am trying to understand how this can occur in order to prevent it, So far it has occurred twice for me. First time I assumed it was my own fault. As It is only a dev lab so not critical but for me but knowing how to prevent it or recover quickly from it is critical for production use cases. 

From your explanation, in my recent case  I had over  300K of 'documents' in the system when the crash occurred. From Section 2, step 2 it would indicate the 'basic' data was lost. How does this occur and is it possible to create a backup of the basic data to attempt an automated recovery in this instance?

**Comment by richard-julien** [comment]
Can you check in your elasticsearch if you still have your 300k documents? If yes do you think it could be possible to do a snapshot and share it with us to debug the problem?

**Comment by kanniget** [comment]
I will take a look

**Comment by kanniget** [comment]
Ok,  I had already wiped the data from this instance and restarted it. I do have some backups and the only ones i have were from before the crash that caused it. 

I will try and reproduce it and when I do I will come back with a snapshot for you.

**Comment by kanniget** [comment]
Ok, I have had it happen again.  How do I provide the snapshot?

**Comment by richard-julien** [comment]
You can put that where you want. Dropbox, drive, ... If you dont wont to everyone get your backup you can send me the link through a PM in slack
