### ISSUE TITLE
Ability to download files as password protected zip archives

### ISSUE THREAD

**Issue by leetn00b** [LuatixHQ/opencti#1616]
## Proposal

It would be beneficial for users of OpenCTI to have the ability to download files via the UI. As some users may be using the OpenCTI UI in a protected environment, it should be possible for the file to be placed in a password protected zip archive before download.

**Comment by richard-julien** [comment]
Hi @leetn00b , duplicate of https://github.com/OpenCTI-Platform/opencti/issues/1580?

**Comment by leetn00b** [comment]
> Hi @leetn00b , duplicate of #1580?

Yes
