### ISSUE TITLE
Threat Actors Feed

### ISSUE THREAD

**Issue by pagosasia** [LuatixHQ/opencti#1622]
## Prerequisites

- [Yes ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [Yes ] I went through old GitHub issues and couldn't find anything relevant
- [Yes ] I googled the issue and didn't find anything relevant

## Description

Threat-actors are all imported into intrusion-sets instead of Threat-actors.  Is there any connector or code samples that can be used to import threat-actors from MISP or other feeds? Thanks.

## Environment

1. OS Ubuntu 18.04
2. OpenCTI version: 5.0.1
3. OpenCTI client:  frontend 
4. Other environment details: VM

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Have enabled connectors with AlienVault, MISP, OpenCTI and more

## Additional information
![image](https://user-images.githubusercontent.com/35626152/136757223-8b631804-cb4a-4b4d-8e32-5b1b882cca40.png)

![image](https://user-images.githubusercontent.com/35626152/136757264-ce3e89c2-0c85-450d-a80d-5e2ca3cd6b8a.png)

**Comment by nor3th** [comment]
Hey @pagosasia 

The import is correct. The STIX standard defines an intrusion set as an APT/FIN/malware group while the threat actor itself is the organization behind it. As an example: APT28 is an intrusion set while the Russian GRU subunit is the threat actor behind the intrusion set.

Here an example: https://oasis-open.github.io/cti-documentation/examples/defining-campaign-ta-is

I am not sure if MISP even covers threat actors. I am currently thinking about improving the existing SDO dataset and I could add a few threat actors. Would this addition be of use to you?

Regards,

**Comment by sukesh-ak** [comment]
You can see threat actor types in the drop down as well

![image](https://user-images.githubusercontent.com/53081362/136916405-e4809e16-2992-4a32-abab-a48804d432b3.png)
