### ISSUE TITLE
Inferences in V5 : multiple same case displayed

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1627]
## Description
The explanatory display of inferences in a relation regularly shows the same inference over again. Although it is not the same source every time, it would be interesting to have a merge of identical inferences paths, at least in the display 

## Environment

2. OpenCTI version 5.0.1
3. OpenCTI frontend

**Comment by richard-julien** [comment]
Can you be more explicit about the situation and the expectation with a document example? Thanks

**Comment by manonviallet** [comment]
Yes ! First, I dont think it is a bug, but this issue is about finding a way of displaying the inferences that could be more efficient to the eye and better understandable.

A good example is this case on the demo (https://demo.opencti.io/dashboard/threats/intrusion_sets/4aea8e17-49c3-4b26-86f9-2a527590432b/knowledge/relations/d60e6a31-4473-40ed-acca-7754cd6f8ff1) with APT28 targeting the civil society sector.


There are 3 inferences displayed and explained (I created one for the purpose, so not sure it will hold with updates of the demo) (I could not capture them in one shot, so has to do 2 screen shots).
 
![Capture d’écran du 2021-10-18 15-02-03](https://user-images.githubusercontent.com/49722941/137741331-cdba512a-0517-4288-bd6d-6b1fd151f2a2.png)

![Capture d’écran du 2021-10-18 15-36-40](https://user-images.githubusercontent.com/49722941/137742238-9bcd7eab-6e1c-47c5-9d57-007afc23b8b9.png)

The issue I was trying to point out is that it seems there will be as much inferences explained as there are individuals relations made. In this example, there are 2 "part-of" with exactly the same path : APT28 targets the "political parties" sub-sector which is part of the civil society sector, The two problems identified are:
- the risk of having tens or hundreds of same inferred relations (which may risk slow down the display of the page ?) and in any case make it unreadable;
- the fact that even today with only three displayed inferred relations, it is not clear why several are displayed. Maybe it would be useful either to display them all in one (for instance, have something similar to sectors, with a collapsible view ?) , or have more explanations directly on this display, so we can see with only one look that the inferences are based on different initial relations.

So my three suggestions would be:
- drop it and display each scenario only once, and not all the "repetitions" ;
-  keep this but:
          - regroup the same under a collaspible view
          - add more information directly on the first view, so that it is visible that it is different without having to click on the relation : maybe with displaying the dates and the authors ?
