### ISSUE TITLE
Indicator : "valid until" not correctly filled

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [LuatixHQ/opencti#1634]
## Description

Inserting any indicator, the valid until field is every time set at 365 days
## Environment

1. OS: Ubuntu 20.04 (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version:  OpenCTI 5.0.1 
3. OpenCTI client: frontend and connectors
## Reproducible Steps

Steps to create the smallest reproducible scenario:
Create a new indicator, fill the various fields leaving "valid until" empty. After the creation, the "valid until" field contains "valid from" + 365 days
Looking at the code, I notice an initial check on "kill-chain-phase" equals to delivery. I obtain the wrong result using this value during creation.

## Expected Output
Different dates dependent on TLP and class (as in https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/domain/indicator.js)

## Actual Output
Everytime "valid until" is equal to "valid from" plus 365 days 
## Additional information
The problem happens both inserting manually the indicator and using AlienVault and Crowdstrike connector

**Comment by SamuelHassine** [comment]
Hello @GiuseppeLaurenza,

365 days is the default behaviour if there is no matching with the main observable type of the indicator. What is the main observable type of your indicator?

Kind regards,
Samuel

**Comment by GiuseppeLaurenza** [comment]
Thanks for the reply
I tried different indicator type, included, for example, ipv4 addresses

**Comment by SamuelHassine** [comment]
Ok, thanks @GiuseppeLaurenza I've successfully reproduced the bug. It will be fixed in the next version.

**Comment by GiuseppeLaurenza** [comment]
thanks for your fast reply
just to better understand, updating to the new version, when it will be available, will update also the old indicators or only the new one added after the upgrade?

**Comment by SamuelHassine** [comment]
What do you prefer?

**Comment by GiuseppeLaurenza** [comment]
For me it will be better if the update also "fix" the old "valid until" fields
Regards

**Comment by GiuseppeLaurenza** [comment]
Continuing the testing, I found that for IPv4 it consider all TLP as White, if I choose TLP-RED or TLP-Amber for example, it assing always the TLP-White number of days.
For URL type instead, it continuously to put 365 days
