### ISSUE TITLE
Customize filters for observations

### ISSUE THREAD

**Issue by leetn00b** [LuatixHQ/opencti#1635]
## Use case

We are seeking a solution where we can filter on custom keys, values, and specify the operator to use, i.e. gt, lt, eq. The goal here is to filter data applied to Artifacts by custom Connectors.

## Current Workaround

None

**Comment by nor3th** [comment]
Hey @leetn00b 

You can either do that in the GraphQL UI (available under https://my_opencti.com/graphql) or you can issue your own graphql queries via the API. Initiate an OpenCTIApiClient instance and then you can issue graphql commands like this `api_client.query(<my query>, {})`

Have a look at the pycti implementations on how to execute graphql queries.

Is this sufficient or do you need to execute graphql queries within the OpenCTI UI?

Regards,

**Comment by leetn00b** [comment]
> Hey @leetn00b
> 
> You can either do that in the GraphQL UI (available under https://my_opencti.com/graphql) or you can issue your own graphql queries via the API. Initiate an OpenCTIApiClient instance and then you can issue graphql commands like this `api_client.query(<my query>, {})`
> 
> Have a look at the pycti implementations on how to execute graphql queries.
> 
> Is this sufficient or do you need to execute graphql queries within the OpenCTI UI?
> 
> Regards,

Many thanks for the information.

We are in fact seeking the ability to run graphql queries within the OpenCTI UI. Ideally within the observations page, to filter down on any custom fields (lists, booleans, etc.) we apply via new Connectors.

**Comment by leetn00b** [comment]
After further research, it appears that we are seeking to customize the filter keys, operators, and values via the UI, not the entire GraphQL query itself.

**Comment by SamuelHassine** [comment]
For the moment, for user experience purposes, we have no plan to be able to fully customize key/values/operator from the UI. That being said, we will be glad to introduce new filters capabilities. So if you can precise which keys are valuable for you or your teams, we can easily implement them. Please open an issue with more precise requests.
