### ISSUE TITLE
Background tasks

### ISSUE THREAD

**Issue by Bella-chris** [LuatixHQ/opencti#1636]
I want to create a background task so I can monitor some events and notify me when they occur.
Is there is any way we can do this in OpenCTI?

**Comment by richard-julien** [comment]
Take a look to Subscriptions & digests in the user profile (https://demo.opencti.io/dashboard/profile). This way you can have some email notification on specific content.
If you need more than email we have to open a bit this feature to webhook and more :)

**Comment by Bella-chris** [comment]
@richard-julien the attached link is not working

**Comment by richard-julien** [comment]
Demo is down for now you can check directly on your personal opencti instance

**Comment by Bella-chris** [comment]
@richard-julien Somehow I don't have have that view in my portal:
![image](https://user-images.githubusercontent.com/92671957/137899142-42b62109-a621-4a31-bc02-23a4c08c43b4.png)

**Comment by richard-julien** [comment]
Looks like you need to upgrade your opencti to the latest version.

**Comment by Bella-chris** [comment]
@richard-julien I installed the docker version available, how can I upgrade it?

**Comment by richard-julien** [comment]
Update your docker compose to opencti 5.0.1 and restart.
By the way 5.0.1 require elastisearch 12 at minimum. It will be back to 10+ in the next version to support opensearch.

**Comment by sc0ttes** [comment]
Hey @Bella-chris , I created a Webhook connector that was just merged into master in the connectors branch (link above). I think it may solve your monitoring and notification of background tasks problem.
