### ISSUE TITLE
OVA import error with VMware ESX 6.7

### ISSUE THREAD

**Issue by CRAI-Ruzila** [LuatixHQ/opencti#1642]
When importing the v5.0.0 OVA file (found at https://www.notion.so/Virtual-machine-template-1789b4442b414dbf87f748db51c85aa5) I get the following error in my ESX console:

"Failed to deploy OVF package. ThrowableProxy.cause A specified parameter was not correct: The provided manifest file is invalid: Invalid OVF checksum algorithm: SHA1."

**Comment by nor3th** [comment]
Hey @CRAI-Ruzila 

Try converting the OVA signature to SHA256 and then give it another try:
https://support.secureauth.com/hc/en-us/articles/360050877072-OVA-file-not-deploying-properly-after-downloading-from-SecureAuth

Regards
