### ISSUE TITLE
Chinese translation 

### ISSUE THREAD

**Issue by smaillong001** [LuatixHQ/opencti#1651]
Hello, 
when will you add a Chinese translation
https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-front/src/utils/Localization.js   

The file cannot be found in the running demo path

**Comment by richard-julien** [comment]
Hi @smaillong001, it will be a nice addition to OpenCTI! 
Do you think you can translate the file in chinese (through a pull request or directly if you are not familiar with git)? 
We will be very happy to provides a chinese translation in openCTI.

**Comment by richard-julien** [comment]
@smaillong001 , any possibility for you to help with this translation? Thanks

**Comment by richard-julien** [comment]
@smaillong001 any news on your possible help on the translation? Thanks

**Comment by little-roach** [comment]
Hi, @richard-julien , I can provide some help on the translation if needed,  and please provide all files/documents to be translated, including Localization.js and others.

**Comment by richard-julien** [comment]
Hi @little-roach , that's a great news! Thanks
All translation are defined in only one file : https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-front/src/utils/Localization.js

You can copy the complete fr:{} section, rename fr to cn and then modify all french stuff to chinese.

Thanks in advance!

**Comment by little-roach** [comment]
Hi @richard-julien , Chinese translation had been added in Localization.js and the request had been submitted.

https://github.com/OpenCTI-Platform/opencti/pull/1827
