### ISSUE TITLE
When hovering over observable in Report, show related objects

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1667]
## Use case

Reports only show the relationships that were created in the context of that report itself. It would be useful to hover over an objects and see the following: 

- additional information about the object, such as the hash (already implemented)
- objects related to the original object
  - this includes relationships created outside of the context of the current report
  - these objects should be links, and clickable, so a user can quickly jump to the related object

## Current Workaround

From the knowledge graph, select an observable. At this point, its unclear if the object has any relationships (outside of those created within the context of the report). Select the observable, go to Knowledge, and view if the the object has any relationships

OR

After creating a report, add the contents of the report to an Investigation, then use the "Expand" functionality, to see all relationships. 

## Proposed Solution

When hovering over an observable, show related objects, included those related outside of the context of the report. Make the "hover bubble" clickable, and with links so an analyst can easily view the relationship. This is difficult, because if a report is updated, then the investigation needs to be updated as well, and the user has to track if other analysts have updated the report

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
This can be implemented for all entities and all graphs in the platform: be able to display more context about an entity directly in the graph view.

Having all those information in tooltip can be very resource aggressive, but we have to look for a solution to dynamically load tooltip when hovering. If not possible, this means opening a right panel when clicking on the information icon with a lot of information, including a "mini-graph" view.
