### ISSUE TITLE
When expanding an object in Investigations view, allow analyst to filter by Relationship Confidence Level and / or Observable Score

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1668]
## Use case

If an object has many relationships, including those of low confidence, or if those objects have low scores, an analyst may not wish to see them.

Therefore the analyst may want to be able to choose to not add those objects to the Investigation

## Current Workaround

n/a

## Proposed Solution

Allow (at the below screen) an analyst to filter which objects are added to the Investigation by Observable Score and / or Relationship Confidence level

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/138573028-e7d32c8a-b2ac-4996-bde4-53f9f6b7a9a9.png)

## If the feature request is approved, would you be willing to submit a PR?

no, not a dev :/

**Comment by SamuelHassine** [comment]
Duplicate #7105.
