### ISSUE TITLE
Error on history connector

### ISSUE THREAD

**Issue by M-J-LIN** [LuatixHQ/opencti#1669]
## Description
The history connector hangs after running for a while. The error messages are as the following image.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } AWS
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } OpenCTI 4.5.5
3. OpenCTI client: { e.g. frontend or python } python
4. Other environment details:

## Screenshots (optional)
![截圖 2021-10-25 上午9 12 14](https://user-images.githubusercontent.com/21030410/138620829-403da954-55e1-4f8c-b5fb-3e6523207a34.png)

**Comment by SamuelHassine** [comment]
Hello @M-J-LIN,

Can you please provide us with the log on the API side when you have the error "Pinging the API"?

Thanks!

Kind regards,
Samuel

**Comment by M-J-LIN** [comment]
Hi @SamuelHassine ,

These log is from API side 
![截圖 2021-10-28 上午11 27 59](https://user-images.githubusercontent.com/21030410/139181604-9b14d68d-11b9-4e42-b0ba-46b427e1078c.png)
![截圖 2021-10-28 上午11 28 43](https://user-images.githubusercontent.com/21030410/139182077-5d66463a-f399-4f5b-aadb-695fd22d9cfc.png)


And I got another error message from history connector.
![截圖 2021-10-28 上午11 08 25](https://user-images.githubusercontent.com/21030410/139181757-f532d899-4634-482d-a52f-4c9c5302e70b.png)
![截圖 2021-10-28 上午11 08 43](https://user-images.githubusercontent.com/21030410/139181763-3f23e546-4889-4378-ad37-a2b8ecd8ccf1.png)
![截圖 2021-10-28 上午11 25 36](https://user-images.githubusercontent.com/21030410/139181667-d5cb07df-b94f-40f9-8f9c-398c0d553617.png)

Thanks.
Jim

**Comment by richard-julien** [comment]
History is no more a connector, its directly a built manager. Please upgrade and try the new manager.
