### ISSUE TITLE
Add boolean selection in research parameters

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1679]
## Use case

When setting parameters for which there can be several choices (most common case are labels), by default it is a "OR" boolean which is implemented and it cannot be changed.

When setting the parameters of a research, the booleans should be also parameters. The choice should be possible between OR, AND and NOT.

![Capture d’écran du 2021-10-25 19-27-10](https://user-images.githubusercontent.com/49722941/138742516-77019ea8-60e6-401f-838a-1e6389f36396.png)

**Comment by SamuelHassine** [comment]
Linked to #1528.

**Comment by SamuelHassine** [comment]
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2686
