### ISSUE TITLE
Make lists manageable from the UI for some attributes

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1682]
## Use case
It would be useful to deal with some attributes differently than it is done today: 
- for Threat actors and Intrusion sets --> goals, resource levels, motivations (primary, secondary)
- for campaign and incident --> objectives
- for malware --> malware type, operating_system_refs, architecture_execution
_envs, implementation_languages, capabilities 

For all these attributes, in most cases, lists are implemented, or in some cases it is a free field. When lists are implemented, they are from the list set up by stix and cannot be changed from the UI.

Two things would be desirable:
- for the fields which are free today (string expected), it would be useful to have lists instead. However, this is different from what is written in STIX so it might be impossible if we do not want to diverge.
- the lists should be manageable from the UI, just as it is possible to do so for type of reports today: in the parameters, in the lables and attributes tab, there could also be a menu to manage these attributes lists. By default, the list which are implemented today and given by STIX could be implemented, but could be changed. Or they could be a dataset as well.

## Current Workaround

No use of these fields because the information is not adequate.

**Comment by SamuelHassine** [comment]
Linked to #1244.

**Comment by SamuelHassine** [comment]
All work around custom ontology will be followed in #1602.
