### ISSUE TITLE
Improve "location" and the location form

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1683]
## Use case

This is related to https://github.com/OpenCTI-Platform/opencti/issues/1663
The form and informations for locations (cities, countries and regions) is lacking some features:

- add the fields region/country/administrative area/city in the "basic information" window of the location object (the STIX 2.1 format account for this, there are fields for "region" and "country" which are existing.);
- implement the 'administrative region' type as defined in STIX 2.1;
- have no level of confidence for Location, or have it "strong" by default (the confidence level is optionnal for Location)

**Comment by 8hur** [comment]
I would like to draw attention to this issue. Sometimes the targetting of a specific region is very informative. This is especially true in the case of region with separatist movements (Tibet, Xinjiang, Kurdistan, Catalonia ...) when the legal status is unclear (Crimea, Abkhazia...) or regions with specific features (Antarctic bases, Kaliningrad ...).

**Comment by Astral-Reaper** [comment]
I too would also like to add on to this issue. (Though i could be testing it the wrong way. )
The openCTI platform doesn't seem to register states within the United States. They aren't regions, countries, or cities. If I wanted to narrow it even more, counties either, which are smaller than states but bigger than cities.
