### ISSUE TITLE
Impossible to display Info about Reports in frontend

### ISSUE THREAD

**Issue by jtamparulo** [LuatixHQ/opencti#1685]
All reports ingested since the last update (5.0.3) cannot be displayed in frontend. Once it is made (manualy), when we click on it, it appears that:
![isuue1](https://user-images.githubusercontent.com/37297427/138869470-92db9a18-182b-4980-9ee8-ef6a6e4ab0cf.PNG)

And then for all other pages of that report, that
![issue2](https://user-images.githubusercontent.com/37297427/138869566-2bfb9c2d-eca7-4bb8-b215-bf063cdaf211.PNG)

What is interersting is that we can still access the info of those report by modifying the url, in place of "undefined" in  the url "http://opencti.cymon/dashboard/analysis/reports/undefined/knowledge", when we give the ID of the report, it works:

![issue3](https://user-images.githubusercontent.com/37297427/138869893-6985162b-e7d2-4980-9ab8-0d5e6dfeb5eb.PNG)

By querying in the graphQL playground, the results are here...what could it be??

In the `docker logs openCTI`, following message could maybe explain something:

`
{"user":{"ip":"::ffff:172.22.0.16","user_id":"bcc817a4-398a-4551-8165-38f3af238aee","referer":"http://opencti.cymon/dashboard/analysis/reports/a886279d-b308-4784-b890-3570a893555f"},"type":"READ_ERROR","operation_query":"query StixCoreObjectHistoryLinesQuery($first:Int$orderBy:LogsOrdering$orderMode:OrderingMode$filters:[LogsFiltering]$filterMode:FilterMode$search:String){...StixCoreObjectHistoryLines_data}fragment StixCoreObjectHistoryLine_node on Log{id event_type timestamp user{name id}context_data{message commit references{id source_name external_id url created description}}}fragment StixCoreObjectHistoryLines_data on Query{logs(first:$first orderBy:$orderBy orderMode:$orderMode filters:$filters filterMode:$filterMode search:$search){edges{node{id ...StixCoreObjectHistoryLine_node}}}}","inner_relation_creation":0,"operation":"StixCoreObjectHistoryLinesQuery","time":17,"variables":{"first":6,"orderBy":"timestamp","orderMode":"desc","filters":[{"key":"entity_id","values":["a886279d-b308-4784-b890-3570a893555f"]},{"key":"event_type","values":["create","update","merge"]}],"filterMode":null,"search":null},"size":224,"error":{"stacktrace":["GraphQLError: String cannot represent value: { message: null, references: [] }","at GraphQLScalarType.serializeString [as serialize] (/opt/opencti/node_modules/graphql/type/scalars.js:173:9)","at completeLeafValue (/opt/opencti/node_modules/graphql/execution/execute.js:653:37)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:578:12)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:556:21)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)"]},"category":"APP","version":"5.0.3","level":"error","message":"API Call","timestamp":"2021-10-26T11:38:42.342Z"}
`

Thank you all very much!

**Comment by richard-julien** [comment]
Hi @jtamparulo,

Looks like the history connector inject something that is not readable for the UI...

At this point the only solution to resolve this problem is to clear the history index to remove this incorrect data. 
Can you check in the history index if you have some context_data.message with complex object like { message: null, references: [] }?

Please also check that the history connector have also been upgraded to the latest version,

Dont hesitate to come to the slack channel to talk directly if you need more help
