### ISSUE TITLE
Implement ordering on every column (and drop the "entity type" column)

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1688]
## Use case
In many knowledge tables, it is not possible to order the list by all column, which does not make sense as it is implemented in some other types, and would really be useful (in most cases, it is actually the "name" column that is the only one which cannot be ordered).

Example (tested in the demo) are:
- Intrusion sets - knowledge - malware --> the table cannot be ordered by the name column. Idem for Tools, incidents, campaigns, attribution.
- Intrusion sets - knowledge - observables : the "type" column cannot be ordered
- Sectors - knowledge - intrusion sets : also the name column and the entity type

Side note : in most cases, except for observables, indicators, and the "related entities" menus, the column "entity type" in the tables is not really relevant, as it is always the same type AND the user knows which since it navigated as far as this precise menu. However, this is more cosmetic than really a need.

**Comment by SamuelHassine** [comment]
Implement the "entities" view everywhere as we have for observables in the knowledge section. So all the list will be sortable by entity attributes and not relationship.

**Comment by SamuelHassine** [comment]
Related to #2553.
