### ISSUE TITLE
Worker python script in OpenCTI v5.0.3 has unexpected keyword argument 'json_logging'

### ISSUE THREAD

**Issue by faustus25** [LuatixHQ/opencti#1698]
## Description

Worker python script in OpenCTI v5.0.3 has unexpected keyword argument 'json_logging'

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 20.04
2. OpenCTI version: v.5.0.3
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

sudo python3 worker.py &

## Expected Output

INFO:root:getting connectors...

## Actual Output

/opt/opencti/worker$ sudo python3 worker.py &
[1] 11268
user@server:/opt/opencti/worker$ Traceback (most recent call last):
  File "worker.py", line 382, in <module>
    worker = Worker()
  File "<string>", line 6, in __init__
  File "worker.py", line 291, in __post_init__
    self.api = OpenCTIApiClient(
TypeError: __init__() got an unexpected keyword argument 'json_logging'
 
## Additional information

I got the worker python script to run by using an older worker python script from v5.0.0
The config for worker python script in v5.0.0 has no json_logging setting unlike v5.0.3

**Comment by axelfahy** [comment]
The option `json_logging` was added in pycti==5.03. If you are deploying OpenCTI v5.03, you should use a worker of the same version. Make sure that the platform, the worker and the connectors use the same version.

**Comment by faustus25** [comment]
I initially used the v5.0.3 worker python script and this is what generated the issue for me.
Hence why I reverted back to using v5.0.0 worker python script.

**Comment by axelfahy** [comment]
What version of pycti are you using? My guess is that you are running the last version of the worker, but with old dependencies. How did you deploy the worker and how did you install the dependencies?

**Comment by faustus25** [comment]
Yes, I updated there as the pycti library was not updated:
Successfully installed pycti-5.0.3 python-json-logger-2.0.2

The worker python script for v5.0.3 runs now.

As it is a manual install, will I have to update every OpenCTI component per requirements.txt each time?
Is there a better way to update workers, connectors etc per each new update?

**Comment by axelfahy** [comment]
IMHO, the best way to run OpenCTI is using docker, you would only have to update the version of the images in the docker-compose file when there is a new release.
