### ISSUE TITLE
Add feature to copy data to an incident or report from an investigation

### ISSUE THREAD

**Issue by dcode** [LuatixHQ/opencti#1700]
## Use case

The investigation feature is awesome, especially with the "expand" feature to quickly go through relationships to determine the scope of a given _thing_. Unfortunately, it doesn't go anywhere after that except perhaps as an exported photo. After I find some insightful information during an investigation, I'd like to write a report about it, or escalate my findings to an incident.

## Current Workaround

Start over. Manually add each of the entities and their relationships to my report.

## Proposed Solution

Add a button or menu item on an investigation page (or the investigation list) that allows a user to "Copy to Report" or "Copy to Incident". This could feasibly give a filter-able/search-able list like the "Add Entity" slide out interface. If the user doesn't have an existing report to copy the entities and relationships to, the user would click on the red `+` icon to create a new report or incident.

## Additional Information

None

## If the feature request is approved, would you be willing to submit a PR?

Maybe? Seems relatively straightforward enough if I can copy-paste code. UI/UX isn't my strong suit.

**Comment by Jipegien** [comment]
Done in 5.9 with the export as report button. Will be completed with #3799
