### ISSUE TITLE
Demo Page seems to be down

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#1713]
## Description

Dear maintainers, I just wanted to let you know that the beta page results in a 502 Bad Gateway error.

## Environment

Chrome, Mac OSX

## Reproducible Steps

Open https://demo.opencti.io/ in your favourite browser

## Expected Output

Getting the demo page

## Actual Output

502 Bad Gateway

## Screenshots
<img width="901" alt="Screenshot 2021-11-03 at 15 37 30" src="https://user-images.githubusercontent.com/60434260/140081196-7da21f1b-c05f-4cf3-a323-24928d07a005.png">

**Comment by richard-julien** [comment]
Demo is often reset and redeploy. During this the demo is not available, so its a "normal" situation.
Do you think it could be a quick win to have a kind of maintenance page instead of a 502 bad gateway @SamuelHassine ?
