### ISSUE TITLE
Add a copy button to the toolbar in Observations page

### ISSUE THREAD

**Issue by leetn00b** [LuatixHQ/opencti#1724]
## Use case

We are in need of a button in the toolbar where we can bulk copy observable values, such as: hashes, IP addresses, and URLs for import into other interfaces like Virustotal Intelligence.

## Current Workaround

Through an exporter connector, create a CSV and parse the observable values out.

## Proposed Solution

Add a copy button to the toolbar in the Observations page to allow copying to the clipboard all of the observable values separated by a new line, with the provided query and filter. The select all checkbox should allow pagination/copying all observables values whereas individual checkboxes copy individual observable values.

**Comment by SamuelHassine** [comment]
So good idea :)

**Comment by RomuDeuxfois** [comment]
[ALREADY PRESENT ON THE MASTER]

The toolbar and the add button overlap

![image](https://user-images.githubusercontent.com/53513584/205596145-6185bd19-2107-4154-9533-08f71fd1a2be.png)
