### ISSUE TITLE
PDF Viewer doesn't render Markdown tables correctly

### ISSUE THREAD

**Issue by jocelynjyl** [LuatixHQ/opencti#1729]
## Prerequisites
- [ x ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ x ] I went through old GitHub issues and couldn't find anything relevant
- [ x ] I googled the issue and didn't find anything relevant

## Description
(Not sure if this should be a question or a bug.) 
On the 'Content' tab, tables in Markdown aren't generated correctly in the PDF viewer. Does OpenCTI support extended markdown syntax? 

## Environment
1. OS (where OpenCTI server runs): Ubuntu 20.04 (focal)
2. OpenCTI version: 5.0.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps
N/A

## Additional information
Raw .md source
![Screenshot 2021-11-15 at 14 30 03](https://user-images.githubusercontent.com/8165187/141790397-40d94538-11f4-41f2-bb0e-0fb8f7d1595f.png)
PDF viewer of same 
![Screenshot 2021-11-15 at 14 30 33](https://user-images.githubusercontent.com/8165187/141790402-e46e0b13-3c9a-450f-90b4-4a3a8a0205ba.png)
Rich Editor displays table correctly
![Screenshot 2021-11-15 at 14 30 39](https://user-images.githubusercontent.com/8165187/141790403-ee3b7f9c-bfde-4088-8d02-47d3c34e2ab1.png)

**Comment by SamuelHassine** [comment]
Hello @jocelynjyl,

This has been fixed in latest versions.

Kind regards,
Samuel
