### ISSUE TITLE
Detail Viewer Bug

### ISSUE THREAD

**Issue by jcandiat** [LuatixHQ/opencti#1731]
## Environment

1. OS: ubuntu 18.04.6 LTS
2. OpenCTI version: Opencti 5.0.3
3. OpenCTI client: frontend
4. Other environment details: docker-compose

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enter to the system
2. Analysis Tab
3. Create a report

## Expected Output

When I save the report, it should show me the entered details, allowing to navigate through the details tabs.

## Actual Output

When I save the report with the create button, the site refreshes the page and shows the error when trying to show the details. It happens to me when I try to visualize a report, when I try to visualize the details of the observations,

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/5710026/142046401-330dbdd3-88d1-4086-afa4-3e8c4d473353.png)

![image](https://user-images.githubusercontent.com/5710026/142046412-8bdae059-a6aa-4b87-83a0-05e8ed5c400e.png)

**Comment by richard-julien** [comment]
Hi @jcandiat ,

Any platform logs?

**Comment by jcandiat** [comment]
> Hi @jcandiat ,
> 
> Any platform logs?

hello!

I tell you that reviewing the platform logs, I noticed 1 error in the opencti container, which I think may refer to my error.

![prueba_opencti](https://user-images.githubusercontent.com/5710026/142638198-23d83129-d1af-4358-8cc6-cc8d7ded549c.png)

**Comment by richard-julien** [comment]
Thanks for the log.
This explains your problem. Looks like the history connector write something wrong in the database. 
Exactly the same problem as https://github.com/OpenCTI-Platform/opencti/issues/1685
Can you take a look on this ticket? Thanks

**Comment by jcandiat** [comment]
> Thanks for the log. This explains your problem. Looks like the history connector write something wrong in the database. Exactly the same problem as #1685 Can you take a look on this ticket? Thanks

Thank you very much for the reply!!

I fixed that the error is in the history connector, now how can I clear the history index to solve the error? In addition to that, I have the latest version of the connector.

**Comment by SamuelHassine** [comment]
Hello @jcandiat,

2 steps here:

1. Delete all entries in the history indexes:
```
curl -X POST "localhost:9200/opencti_history-*/_delete_by_query?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "entity_type.keyword": "history"
    }
  }
}
'
``` 

2. Reset the state of your history connector using the top right button:

![image](https://user-images.githubusercontent.com/1334279/142728484-29b858a3-60b9-4ef1-8504-aebb2c5a926a.png)

3. Restart your history connector and it will recreate everything.
