### ISSUE TITLE
Data Retention period and Clearing of all data after a period of time

### ISSUE THREAD

**Issue by AAAbou** [LuatixHQ/opencti#1734]
## Prerequisites

- [ X ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ X ] I went through old GitHub issues and couldn't find anything relevant
- [ X ] I googled the issue and didn't find anything relevant

## Description

Is there a data retention period/policy for the data on OpenCTI? Is it possible to create a rule to clear observations after a certain period of time for all/single connectors? example clearing the data they are older than 7 days without affecting already ongoing operations?

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: 5.0.3
3. OpenCTI client: frontend
4. Other environment details: docker based

## Reproducible Steps

N/A

## Additional information

![image](https://user-images.githubusercontent.com/30905852/142611829-c91bdef1-0b44-40f6-9e95-42bbcc33a105.png)

![image](https://user-images.githubusercontent.com/30905852/142611906-929fedab-8b55-4e09-9e38-55c03dcc37ca.png)

![image](https://user-images.githubusercontent.com/30905852/142611995-9196e599-2b55-4ed5-9def-d7738e44ce9f.png)

**Comment by richard-julien** [comment]
Hi @AAAbou.
Data retention policy is planned in https://github.com/OpenCTI-Platform/opencti/issues/1228
Will work on it very soon,
Closing this ticket to only talk about this feature in https://github.com/OpenCTI-Platform/opencti/issues/1228

**Comment by AAAbou** [comment]
Thank you! @richard-julien
