### ISSUE TITLE
External reference of entities could not be updated

### ISSUE THREAD

**Issue by M-J-LIN** [LuatixHQ/opencti#1736]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve
When I use the _stix2.import_bundle_from_json_ to import bundle and there is external reference property in objects. If the objects have already exist in platform, the external reference would not be updated even with _update=True_.

## Current Workaround
Need an extra api call like _stix_domain_object.add_external_reference_ to update external reference to exist object.

## Proposed Solution
External reference should be updated if set _update=True_.

## Additional Information
My pycti version is 4.5.5.

**Comment by richard-julien** [comment]
Fixed in latest available version of OpenCTI 5.0.3.
Please upgrade.
