### ISSUE TITLE
Add tag to source of indicator/observable/report

### ISSUE THREAD

**Issue by AAAbou** [LuatixHQ/opencti#1738]
## Use case

Add tag/label to state the source of data of where it came from or its origin

## Current Workaround

Pushing Indicators to MISP with Tags saying "source:XXXX" using pymisp. Importing data from MISP  to OpenCTI with tags "source:XXXX" thus the observable on OpenCTI gets labeled wirh "XXXX"

## Proposed Solution

add tags to connectors

## Additional Information

Pushing Indicators to MISP with Tags saying "source:XXXX" using pymisp

![image](https://user-images.githubusercontent.com/30905852/142759267-53c03a3b-919c-4d46-8d7e-bb28672670e6.png)

Importing data from MISP  to OpenCTI with tags "source:XXXX"

![image](https://user-images.githubusercontent.com/30905852/142759221-5fcc800f-ba8e-4534-9bc0-637e8c33435c.png)

the observable on OpenCTI gets labeled wirh "XXXX"

![image](https://user-images.githubusercontent.com/30905852/142759321-a65e27d7-b4ce-4070-a4b6-35183b8edaff.png)

Adding Label that its from MITRE

![image](https://user-images.githubusercontent.com/30905852/142759454-a53a9496-60f6-42b6-ac5e-bf3f684313b9.png)

**Comment by SamuelHassine** [comment]
Report tags are taken from event tags.
Indicators/Observables tags are taken from attribute tags.

Solution is to add the source in the event itself.
