### ISSUE TITLE
Bug in victimology graph in dashboard section

### ISSUE THREAD

**Issue by nicolasleguillou** [LuatixHQ/opencti#1740]
## Description

Victimology widgets in the dashboard sections has a default value setup on 1 that gives a false idea on the actual victomology of a given threat entity.

## Environment

2. OpenCTI version: 5.0.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to custom dashboard
2. Look for a threat or arsenal item that has a complete victimology (for example an intrusion set with X targeted organizations part of X sectors and located at X countries)
3. Select victimology - countries or victimology - sectors and then pick up list, horizontal bar, donut, vertical bar widgets

## Expected Output

Analysts expect a graph with different values by country or sectors depending on the location of the compromised organisations or the different sectors listed in the threat entity's victimology. 

## Actual Output

The actual output is a graph with a non-exhaustive list of targeted countries or sectors and a value setup at 1.

**Comment by SamuelHassine** [comment]
This is linked to the absence of inference rule for `part-of` relationships. A new rule has been introduced in 5.1.0:

![image](https://user-images.githubusercontent.com/1334279/143538464-1eca5836-0be6-4881-a7d3-0c4f15de9665.png)

**Comment by SamuelHassine** [comment]
Linked to #1627.
