### ISSUE TITLE
Export only selected entities

### ISSUE THREAD

**Issue by r0sier** [LuatixHQ/opencti#1741]
## Description

This may not be the correct repository for this issue as it may be an API issue! Both the export connectors (Stix and CSV) when exporting a list scope all entities are returned. It does not return the entities selected in the UI. 

I think this may be due to the list parameters being set to `{'search': '', 'orderBy': 'created', 'orderMode': 'asc', 'filters': []}` by the process_message data which is therefore returning all. 

## Environment

Ubuntu Docker, v 5.0.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
(Tested in demo.opencti)
1. Select multiple observables / indicators via the check boxes
2. Open the export panels and export to CSV or JSON
3. Returned format includes all observables or indicators, not the entities selected

## Expected Output
Only the selected entities should be returned

**Comment by SamuelHassine** [comment]
This issue is about the core platform. By default, only filters and search keyword are taken into account during the export. But selecting individual entities is not taken into account by the export functions.
