### ISSUE TITLE
I am getting the below while running the opencti

### ISSUE THREAD

**Issue by seccodingwizard** [LuatixHQ/opencti#1745]
Hi Team ,

Need help in addressing the issue of opencti.

![image](https://user-images.githubusercontent.com/32640439/143482338-e5a74022-21e3-402b-851e-ad38e4df20e0.png)

kindly help to resolve the issue.

Regards,
Raghunandan

**Comment by seccodingwizard** [comment]
Hi Team,

Any one help on the issue what i am facing.

Regards,
Raghunandan

**Comment by richard-julien** [comment]
Hi @seccodingwizard. First time i see this.
What version of nodejs do you have?

**Comment by seccodingwizard** [comment]
Hi Richard,

I am using v17.0.1, Please help.

**Comment by richard-julien** [comment]
Do you have the same problem with just "yarn --version" ?

**Comment by seccodingwizard** [comment]
Hi Richard, i am using yarn 
![image](https://user-images.githubusercontent.com/32640439/144013021-720c3217-50d4-4088-b14c-45854f476019.png)

and getting below error now.


![image](https://user-images.githubusercontent.com/32640439/144013161-8ce39399-4bbb-45ff-9662-393d4b42cbd8.png)


Please help

**Comment by seccodingwizard** [comment]
Hi Richard,

We have resolved the issue by changing the ports of Minio and Radis. it's working now.

Thanks for the your help.

Regards,
Raghunandan
