### ISSUE TITLE
Add capability to support multiple OpenID Connect strategy providers

### ISSUE THREAD

**Issue by CyberDaedalus00** [LuatixHQ/opencti#1754]
## Description

When trying to register multiple OIC providers only the second provider is used.  This appears to be because they are both registered with PassportJS with the same name.

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 16.4
2. OpenCTI version: { e.g. OpenCTI 5.0 }
3. OpenCTI client: frontend 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

I need the ability to support multiple OpenID Connect providers.  So, I attempted to configure two different instances, each with a different issuer, client_id, client_secret, and redirect_uris values in default.json.  But it appears only the second one registered is used.  A search of the source code shows that each OIC provider is registered with PassportJS with the same name: 'oic'.  A review of the PassportJS code shows that the registration of the second provider is overwritten since both use the hardcoded name 'oic'.

Is there support for multiple OpenID Connector providers?

## Screenshots (optional)

**Comment by richard-julien** [comment]
Hi @CyberDaedalus00, this is not possible for now, changing this ticket to a feature request

**Comment by richard-julien** [comment]
Add an option to specify and expected identifier. This identifier must be correctly setup in the callback URI.
If not specified the default identifier is used.

Example for openid

```
    "myopenid": {
      "strategy": "OpenIDConnectStrategy",
      "config": {
        "label": "Login with OPEN1",
        "issuer": "xxxx",
        "client_id": "xxxx",
        "client_secret": "xxxx",
        "redirect_uris": ["http://localhost:4000/auth/oic/callback"]
      }
    },
    "openidsecond": {
      "identifier": "otheroic",
      "strategy": "OpenIDConnectStrategy",
      "config": {
        "label": "Login with OPEN2",
        "issuer": "xxxx",
        "client_id": "xxxx",
        "client_secret": "xxxx",
        "redirect_uris": ["http://localhost:4000/auth/otheroic/callback"]
      }
    }
```
