### ISSUE TITLE
Be able to select labels to import

### ISSUE THREAD

**Issue by nicolasleguillou** [LuatixHQ/opencti#1755]
## Use case

As an analyst, I want to able to select the labels I want and do not want in my opencti instance.

## Current Workaround

Delete the unwanted labels.

## Proposed Solution

Remove the right attributed to a connector to import labels.

**Comment by SamuelHassine** [comment]
Implement a global parameter at the platform level:

* Only import / create already existing labels (no creation allowed)
* In this mode: create new labels will do nothing and not raise errors
* In this mode: missing labels dependencies for an entity should not raise errors

On the Python side, this is already supported in the import mecanism, if create label return None, the label ID will not be passed as a dependency.

```
if "labels" in stix_object:
            for label in stix_object["labels"]:
                if "label_" + label in self.mapping_cache:
                    label_data = self.mapping_cache["label_" + label]
                else:
                    label_data = self.opencti.label.create(value=label)
                if label_data is not None and "id" in label_data:
                    self.mapping_cache["label_" + label] = label_data
                    object_label_ids.append(label_data["id"])
```
