### ISSUE TITLE
Export observables (and other objects) from and SDO's Knowledge page

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1756]
## Use case

Allows user to export observables, vulnerabilities, attack patterns, etc related to an SDO such as a Threat Actor

## Current Workaround

n/a

## Proposed Solution

Add the Export functionality to the SDO knowledge page

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/144320699-035b352a-c80c-4b11-bc6f-8e3b0539f31c.png)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
It has been implemented in previous versions.
