### ISSUE TITLE
Add Indicator to Report when Observable+Indicator created within the context of a Report

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1757]
## Use case

When Indicators are created via the context of a Report by creating an observable and toggling the "Create an indicator from this observable", the observable is added to the Report, but the Indicator is not. This creates additional steps to add the Indicator to the Report, and create relationships between the Indicators and other SDOs in the Report

## Current Workaround

After creating the observable + indicator, separately add the indicator to the report

## Proposed Solution

Add Indicators to the same Report as the Observable when creating an Indicator using the toggle feature "Create an indicator from this observable"

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
This is part of the new rules we are taking care about. It is almost impossible to do this at creation, because entities are created before the report itself.

@richard-julien 2 new rules to be implemented along the victimology:

```
If Report X => object => Indicator A
and Indicator A => based-on => Observable B
Then Report X => object => Observable B and Based-On Relationship

If Report X => object => Observable B
and Indicator A => based-on => Observable B
Then Report X => object => Indicator A and Based-On Relationship
```
