### ISSUE TITLE
Any solutions for cancelling an import

### ISSUE THREAD

**Issue by calamityz** [LuatixHQ/opencti#1758]
Hi, 

As I was using OpenCTI , I imported the wrong STIX file and I didn't found how to cancel the import.

I've tried to delete it with the delete button with but my datas are still in my OpenCTI Dashboard.

Dis I missed something or is the functionnality is simply not implemented ?

Thank you for your help

**Comment by richard-julien** [comment]
Hi @Fjottis ,

Cancelling an import is not possible today. When a file is imported, its through a connector that will analyze the file and push the actions into a QUEUE that will be consume by a WORKER that really inject data into OpenCTI. What you can delete is "only" a tracking job to help your understand when it will be finished.

It could be very complex to implement. Imagine cancelling the import in the middle. Do you expect OpenCTI to rollback every changes done by the import? Considering that the platform could have merge element, update (and maybe delete stuff depending of the connector). 

In the last release you introduce a new option in the connector: CONNECTOR_VALIDATE_BEFORE_IMPORT
With this option the connector will create a import bundle that will need to be validated before creating the job. After this validation it will still not be possible to cancel the operation but it could be a first step to prevent any error.

**Comment by calamityz** [comment]
Thank you for your answer.The new option connector validate before import is a really good options implemented. And it will do the job to fix misclick a file
