### ISSUE TITLE
MITRE implemented non-standard STIX relationship `detects`

### ISSUE THREAD

**Issue by dark6naw** [LuatixHQ/opencti#1766]
OS (where OpenCTI server runs): Ubuntu 20.04.3
OpenCTI version: 5.1.1
OpenCTI client: Frontend
Other environment details: NA

## Reproducible Steps
Steps to create the smallest reproducible scenario:

1. Enabled MITRE connector from Github

## Actual Output

1. Previous iterations of MITRE connector used to import without error

Screenshots (optional
![Screenshot 2021-12-07 at 11 53 45 AM](https://user-images.githubusercontent.com/34785594/144963284-a21a5093-3747-4f01-aa97-efa9eb16d18a.png)
)
![Screenshot 2021-12-07 at 11 53 57 AM](https://user-images.githubusercontent.com/34785594/144963300-8c0b9d24-a661-4127-9d32-bba7f5a005fe.png)

**Comment by SamuelHassine** [comment]
Hello @dark6naw,

`detects` is not a valid STIX relationship and has been added in the MITRE dataset. These errors do not prevent MITRE to be ingested, just these relationships are ignored. I will take a look to add this type of relationship in the future.

Kind regards,
Samuel

**Comment by dark6naw** [comment]
Thank you Samuel for the update.

**Comment by SamuelHassine** [comment]
The `detects` relationship has been added in previous versions (starting 5.3.5).
