### ISSUE TITLE
SDO enrichment is unable to initiate automatically

### ISSUE THREAD

**Issue by jieyu-lin** [LuatixHQ/opencti#1774]
## Description

As far as I know, https://github.com/OpenCTI-Platform/opencti/releases/tag/4.5.4 indicates stix domain entity can use INTERNAL_ENRICHMENT connector functionality to auto enrich data from external sources. '

<img width="605" alt="截圖 2021-12-14 11 57 08" src="https://user-images.githubusercontent.com/51392682/145931587-7e213349-30f3-4d87-bfa4-8200d94d8b6f.png">

We suppose those domain entity can share as the same auto enrich with observable: https://github.com/OpenCTI-Platform/opencti/blob/4.5.5/opencti-platform/opencti-graphql/src/schema/stixDomainObject.js#L21-L42

However, I try to establish a connector to auto enrich new import object of Vulnerability and it is not working. You can see picture underneath. New imported CVE won't trigger this connector to do enrichment

<img width="1249" alt="截圖 2021-12-14 11 57 41" src="https://user-images.githubusercontent.com/51392682/145931600-db0de069-6012-41f9-a022-25a26a6b5ccd.png">

Our team try to trace why those  enrich process were not triggered and find:
1. those auto trigger process are only for external-reference, cyber observable object
2. the other trigger point is: stixCoreObject mutation, is the button that trigger enrich process above

We suppose enrich functionality should be the same as observables.

## Environment

Linux

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Picture above

## Expected Output
<img width="1251" alt="截圖 2021-12-14 12 12 28" src="https://user-images.githubusercontent.com/51392682/145931836-038a646a-bc83-4f36-89fb-0e842725de57.png">
Just an example of observable we created, should auto-trigger enrich connector for observable

## Actual Output
<img width="1249" alt="截圖 2021-12-14 11 57 41" src="https://user-images.githubusercontent.com/51392682/145931600-db0de069-6012-41f9-a022-25a26a6b5ccd.png">

**Comment by nor3th** [comment]
Hey @jieyu-lin 

OpenCTI itself at least registers your connector correctly, otherwise it wouldn't show up. What does your connector do with the `event_id` value? https://www.notion.so/Connector-Development-06b2690697404b5ebc6e3556a1385940#0c25262374974679b648a11318685408

Regards

**Comment by jieyu-lin** [comment]
Hi @nor3th , I cannot find any attributes of `event_id`. We followed those enrichment connector of Observable (ex. `Stixfile`, `IPv4`) and we can trigger automatically.

what you said about `event_id` is `entity_id`?

**Comment by nor3th** [comment]
Hey

I was referring to the content of the `event_id` attribute of the `data` dictionary. (have a look at the `OpenCTI triggered` code layout from here https://www.notion.so/Connector-Development-06b2690697404b5ebc6e3556a1385940#b5ba1e7e077448af91aad3180e7e1f06 )

The `event_id` attribute should contain the OpenCTI ID of the your vulnerability. With that ID you can do further lookups or add additional information to it. 

What happens if you manually trigger the connector from the opencti UI (the arrow in the screenshot)? Any relevant log entries in the opencti or the connector log?

Regards

**Comment by jieyu-lin** [comment]
I had my screen shot of those requests when I trigger opencti vulnerability enrichment connector:
<img width="1254" alt="截圖 2021-12-16 14 48 20" src="https://user-images.githubusercontent.com/51392682/146343996-5351ba42-22f0-47e6-94d5-b9f0dd9f070b.png">
<img width="1255" alt="截圖 2021-12-16 14 48 34" src="https://user-images.githubusercontent.com/51392682/146344027-c1551e0a-0be1-4b0f-a134-d944dae21f4b.png">
<img width="1255" alt="截圖 2021-12-16 14 48 46" src="https://user-images.githubusercontent.com/51392682/146344058-ce4f98fb-1a53-4d7e-888c-983dc515d461.png">
<img width="1254" alt="截圖 2021-12-16 14 58 20" src="https://user-images.githubusercontent.com/51392682/146344067-093ae3b2-8996-4a36-aa48-c44c3076d766.png">

There are mainly two requests after I click enrich button. 
Here is the log in my enrichment connector which received trigger message:
<img width="1156" alt="截圖 2021-12-16 14 46 37" src="https://user-images.githubusercontent.com/51392682/146344186-8d603780-d710-4e95-894a-a044496704e6.png">

**Comment by nor3th** [comment]
Hey @jieyu-lin 

So if I understand you correctly, the connector and hence the vulnerability enrichment then works flawlessly, it's just the `auto` triggering which doesn't automatically trigger the enrichment?

Regards

**Comment by jieyu-lin** [comment]
Hi @nor3th , like what you said. I can manually trigger by platform UI but it cannot `auto-trigger` by `INTERNAL_ENRICHMENT` type connector when new vulnerabilities imported. This is also what I find in other `STIX domain entity` also.

**Comment by nor3th** [comment]
Hey @jieyu-lin 

Ok, I'll put in the bug fixes for the upcoming release. Thanks a lot for raising this issue!

Regards,
