### ISSUE TITLE
When using an External Reference on a Relationship/SRO, the Linked Objects shows "None - None"

### ISSUE THREAD

**Issue by Lost-In-Omega-Mart** [LuatixHQ/opencti#1776]
## Description

After specifying an External Reference when creating a Relationship between two entities/SDOs, the Linked Object(s) in the External Reference in the OpenCTI frontend (under "Analysis -> External references") show "None - None".

This behavior does not happen if the External Reference is linked directly to a non-Relationship entity, such as a Report or a Tool.

## Environment

1. OS (where OpenCTI server runs): AWS Linux 2
2. OpenCTI version: 5.0.2
3. OpenCTI client: frontend
4. Other environment details: None

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an "External Reference"
2. Begin creating a Relationship between two SDOs, such as a Tool and a Vulnerability
3. The Relationship creation options include External Reference(s) - select the previously created External Reference
4. Complete the creation of the Relationship between the Tool and Vulnerability
5. Navigate to the External Reference created in Step 1
6. The Linked Objects section should show an item, but instead of any details it shows "None - None"

## Expected Output

It seems that the frontend should show similar details as it does when the External Reference is linked to a Report or other SDO entity.

## Actual Output

Instead, the "Linked Objects" section of the External Reference shows:
"None - None"
"None"
 
## Screenshots (optional)
![image](https://user-images.githubusercontent.com/89865318/146415465-fb0b3098-42b6-4304-81ec-92999f838d9a.png)

**Comment by SamuelHassine** [comment]
Hello @Lost-In-Omega-Mart,

Can you please update your platform in latest version (5.1.2) and tell me if the problem persists? It should be fixed.

Kind regards,
Samuel

**Comment by Lost-In-Omega-Mart** [comment]
> Hello @Lost-In-Omega-Mart,
> 
> Can you please update your platform in latest version (5.1.2) and tell me if the problem persists? It should be fixed.
> 
> Kind regards, Samuel

Hello @SamuelHassine,

Tested this behavior within 5.1.2, and the problem does not appear to persist. Thank you for the recommendation!

Much appreciation,
@Lost-In-Omega-Mart
