### ISSUE TITLE
Vertical ultra vires attack

### ISSUE THREAD

**Issue by Snowty** [LuatixHQ/opencti#1777]
## Description

If I am a user with Default Role，I can access the Administrator's Setting menu which indicates the system has Vertical ultra vires attack defect.

## Environment

1. OS (where OpenCTI server runs): Centos 7.9
2. OpenCTI version: OpenCTI 5.1.2
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
http://domain/dashboard/settings/attributes/lebels
http://domain/dashboard/settings/attributes/kill_chain_phases
http://domain/dashboard/settings/attributes/report_types

## Expected Output

None.

## Actual Output

Default user can access the Setting menu.
 
## Screenshots (optional)
![lebels](https://user-images.githubusercontent.com/10307930/146510589-a7914c6d-0997-4a92-a23b-5130b60d7f2c.PNG)
![report_types](https://user-images.githubusercontent.com/10307930/146510603-37f8931c-da87-460c-80e6-0dfbe5a2bd30.PNG)
![killchain](https://user-images.githubusercontent.com/10307930/146510625-45546ef4-75af-4562-89c7-3511d393137b.PNG)

**Comment by richard-julien** [comment]
Thanks for reporting this, will look into it quickly

**Comment by richard-julien** [comment]
Ok looking into it this cannot be considered as an attack.
All information you can access through this method are available to standard users and correctly protected in the API.
So there is no data leak at this point.

We will add more front control to prevent direct access to this kind of URL but there is no security issue here.
