### ISSUE TITLE
When viewing the targetting of a sector by a threat actor, the intrusion sets used should be more visible

### ISSUE THREAD

**Issue by 8hur** [LuatixHQ/opencti#1783]
## Use case

https://demo.opencti.io/dashboard/threats/threat_actors/7164f189-c56e-4d53-bd96-c21b20d5297d/knowledge/relations/4a00bb58-0949-432e-bd3f-0fabd1dc346b

In this example, I try to get an overview of the targetting of civil society that have been attributed to the russian threat actor. However the visible link (Targetting of NGO henceforth targetting of civil society isn't the most relevant information. Multiple intrusion sets can be seen by unrolling the links but we have duplicates entries for some of the intrusion sets (with insufficient information to understand how they differ). No list of the intrusion sets deployed is visible.

## Current Workaround

Scroll and try to remember the duplicates

## Proposed Solution

Show a list of the entities (Intrusion set, campaigns, incidents) involved in this targetting. Probably one line per incident type with a button to uncover the full list if it doesn't fit on the screen.

## Additional Information

This could make it very useful to get relevant informations at a glance.

Additionally, even the inferred relation are labelled as "direct targetting of the sector" in the victimology page (Should a open a distinct issue ?)

**Comment by SamuelHassine** [comment]
Victimology screen has been fully rewritten and now corresponds to what is requested in this issue. Please re-open a new if needed.
