### ISSUE TITLE
How marking definitions restrictions are taken into account?

### ISSUE THREAD

**Issue by jcandiat** [LuatixHQ/opencti#1786]
## Use case

When more than one marking definition is integrated to each report, the group assigned to the user must have both marking definitions to access the report. Currently, if I have only one, I can access it, without considering the other marking definitions.

## Current Workaround

![image](https://user-images.githubusercontent.com/5710026/146989995-8062c611-a7fd-4830-a1ff-4cfd25b744db.png)

It is only necessary to have a marking definition to access the report.

## Proposed Solution

that all marking definitions are considered, to access the report.

**Comment by SamuelHassine** [comment]
Hello @jcandiat,

This behavior is already implemented. But you have to be sure the marking definition has a different "type".

Granted to TLP:AMBER (type TLP, order 3):

- TLP:WHITE => allowed (order 1)
- TLP:GREEN => allowed (order 2)
- TLP:AMBER => allowed (order 3)
- TLP:RED => denied (order 4)

But if you create a new marking TOP SECRET (type CLASSIFICATION, order 1).

A document TLP:RED and TOP SECRET will be accessible only if the group have both markings. But if the marking TOP SECRET has a type "marking", only the "order" will be taken into account (so all groups >= TLP:WHITE will access it).

I've just tested on the demo and it works fine.

Kind regards,
Samuel
