### ISSUE TITLE
URLs are rewritten with an additional `/` when using a reverse proxy

### ISSUE THREAD

**Issue by h1lll0ck** [LuatixHQ/opencti#1793]
## Description

When using a reverse proxy (e.g. for TLS connections) many of the web UI endpoints rewrite the URL/address of the page with an additional `/` between the reverse proxy base path and the OpenCTI path.

The links in the page are correct, so browsing via clicking on links works properly. However, Back or Forward, or a page refresh, in the browser results in an error being displayed as the client tries to request the endpoint with an additional `/`.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
1. OpenCTI version: `5.1.2`
1. OpenCTI client: Web UI using Chromium 96
1. Other environment details:
    1. Nginx reverse proxy using TLS
    1. OpenCTI platform running inside container

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up reverse proxy in front of OpenCTI server/platform
1. Run OpenCTI platorm with environment variable `APP__BASE_PATH=/opencti`
1. In the web UI go to "Settings" -> "Parameters", under "Configuration" change the "Base URL" to (e.g.) `https://XXXX:1234/opencti`
1. Go to one of the problematic endpoints: (e.g.) "Analysis" (the hyperlink has the correct path: `https://XXXX:1234/opencti/dashboard/analysis/reports`)
1. Page content loads correctly, but observe that the client browser page address has an additional `/`:  (e.g.) `https://XXXX:1234/opencti//dashboard/analysis/reports`
1. Refresh the page, or browse somewhere else and use the browser Back feature

## Expected Output

Upon reloading of a page (e.g. "Analysis"), the relevant content is displayed and client browser page address (and `document.location.href`) is correct: (e.g.) `https://XXXX:1234/opencti/dashboard/analysis/reports`

## Actual Output

Upon reloading of a page (e.g. "Analysis"), no page content is displayed (an error message is shown instead) and the client browser page address (and `document.location.href`) continues to be incorrectly rewritten.

The page shows this error:
```
Error
This page is not found on this OpenCTI application.
```

## Additional information

Some examples of endpoints exhibiting the incorrect rewriting:
- Dashboard:	/dashboard
- Analysis:	/dashboard/analysis
- Events:	/dashboard/events
- Observations:	/dashboard/observations
- Threats:	/dashboard/threats
- Arsenal:	/dashboard/arsenal
- Entities:	/dashboard/entities
- Search:	/dashboard/search
- Custom dashboards:	/dashboard/workspaces/dashboards
- Investigations:	/dashboard/workspaces/investigations
- Data - Entities:	/dashboard/data/entities
- Data - Synchronization:	/dashboard/data/sync
- Data - Data sharing:	/dashboard/data/sync
- Data - TAXII collections:	/dashboard/data/taxii
- Settings - Accesses:	/dashboard/settings/accesses
- Settings - Workflows:	/dashboard/settings/workflow
- Settings - Retention policies:	/dashboard/settings/retention	
- Settings - Rules Engine:	/dashboard/settings/rules
- Settings - Labels & Attributes:	/dashboard/settings/attributes/labels

Some examples of endpoints that seem to work correctly:
- Entities:	e.g. /dashboard/observations/indicators or /dashboard/analysis/notes
- Search:	/dashboard/search/XXXX
- Data Import:	/dashboard/import
- Data - Background tasks:	/dashboard/data/tasks
- Data - Connectors:	/dashboard/data/connectors
- Settings:	/dashboard/settings
- Profile:	/dashboard/profile

**Comment by h1lll0ck** [comment]
This might be related to or caused by the changes made to fix issue 1552: https://github.com/OpenCTI-Platform/opencti/issues/1552

**Comment by richard-julien** [comment]
Thanks for the report. Will be release in the next version.
Even if its not useful for your use case, be aware that the "Settings" > "Parameters" > "Base URL" has been removed in favor of APP__BASE_URL.
For information APP__BASE_URL is used only for:
* Generate correct URL when sending email with the subscription manager
* Generate correct URL for TAXII2 server links
