### ISSUE TITLE
Duplicates when filtering reports status

### ISSUE THREAD

**Issue by 2xyo** [LuatixHQ/opencti#1796]
## Environment

Demo : https://demo.opencti.io/dashboard/analysis/reports

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. open https://demo.opencti.io/dashboard/analysis/reports
2. Click filter button
3. Click status drop down buttun

## Expected Output

no duplicates status 

## Actual Output

duplicates status

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/31675/147420310-e3ab7f07-8a42-4f5c-b98c-28fde0a1b958.png)

**Comment by SamuelHassine** [comment]
This is a bug only related to the demo environment. Do you have the same in your own instance?

**Comment by 2xyo** [comment]
I confirm that I can't reproduce the issue on my instance :grin:
