### ISSUE TITLE
Bulk creation of knowledge around a threat entity

### ISSUE THREAD

**Issue by nicolasleguillou** [LuatixHQ/opencti#1799]
## Use case

As an analyst, I want to be able to import the knowledge (TTP, IOCs, victimology, arsenal used) I have around a given threat entity (intrusion set, campaign, threat actor, malware in particular) in bulk mode in order to save time and avoid repetitive tasks. 

## Current Workaround

Clicking on multiple sections and creating several relationships with the same metadata.

## Proposed Solution

This could be great to have for example a form to complete by the analyst so that on one single page, all the knowledge can be filled up, like this:

![image](https://user-images.githubusercontent.com/80690825/147663606-847c7748-f3e3-4a10-87d4-4259494a08c7.png)

This is just a suggestion, I would be glad to discuss about it if needed @SamuelHassine.

**Comment by AAA10CR7** [comment]
Was this implemented?
