### ISSUE TITLE
Descriptions modifications are sometimes not taken into account

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1807]
## Description

Sometimes, the modification of a description is not taken into account, and the analyst have to click on another field of the form to make the description modification effective.
This can be frustrating as an analyst who does not know this 'tip' on how to have the description modification effective may try several times to change it without success. 

There is a seemingly random occurrence (it is not clear to me if this happens to a specific type of object or in specific circumstances). What I observed so far in the V5 was:
- it seems to be the case only for objects descriptions, not relations;
- I was able to reproduce it for a malware in the demo, but not for any other type. It happens when adding new words to the description, but also when suppressing.
- it happened at least 1 out of 5 modification

## Environment

Reproduced on demo with V5.1.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. {Go to a malware
2. Click on the button to modify it
3. Add something to the description and sees what happens

**Comment by manonviallet** [comment]
Also happened today for a note description

**Comment by SamuelHassine** [comment]
Hello @manonviallet,

I'm not able to reproduce this bug. We need more information like:

- Browser web console log when this happens
- Browser network information when this happens

Any way to easily reproduce? Is this only concerns description (ie. Enriched markdown field) or any other fields?
