### ISSUE TITLE
Issues with the label&attributes tab parameter : cannot create label from the parameters, cannot manage attributes and cannot scroll

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1816]
## Description

In the parameters, there is a tab for managing labels and attributes. However, there are three issues with this tab:

- when clicking on the "+" button, you cannot create a label, only an attribute. To create new labels, you have to go to any page in the plateform and create them from here, but you cannot from the parameters page. It would be expected to be able to create a label directly from this page, and when using the "+" button, to be able to choose between creating a label or an attribute.
![Capture d’écran du 2022-01-12 16-37-17](https://user-images.githubusercontent.com/49722941/149172470-a186c64b-1c2a-4344-9680-6899b856aaf1.png)

- when there are a lot of labels, the list cannot be collapse, and you can never /very difficultly access to the attributes list to manage them, as they are at the very bottom. Labels and attributes should have the entire list which could be collapsed to access the other (as for victims, with list of orgs collapsing in sectors for example)

- in the two OpenCTI that we have, I encountered a bug with the scrolling menu in this tab (and only this one) : the list would not scroll down and will always send back to the beginning. However I could not reproduce it on the demo.

## Environment

V5.1.3 / demo environnement for the two first issues.

The last one was observed on 2 different OpenCTI, which are both V5.1.3, one running in docker swarm and the other in docker-compose (both on a Ubuntu OS)

**Comment by securitiz** [comment]
The same scrolling bug applies to the "Kill Chain phases" page under "Labels & Attributes"
