### ISSUE TITLE
Plateform considerably slowed down while trying to display big reports

### ISSUE THREAD

**Issue by manonviallet** [LuatixHQ/opencti#1822]
## Description

This was reproduced on the demo (v5.1.3)
When trying to access some reports with a lot of entities (~500), the platform slowed down considerably / almost froze. 
It took each time several minutes for the page to finally load.
Below is the page loading with an alert by firefox of a script slowing down the navigator. This was seen with this report https://demo.opencti.io/dashboard/analysis/reports/2d3e21cf-a9be-43e9-9724-5f9f49e91b2f/knowledge/graph?

![Capture d’écran du 2022-01-13 17-19-06](https://user-images.githubusercontent.com/49722941/149502023-963364b6-5a94-4496-be07-0c2c60810c39.png)

**Comment by SamuelHassine** [comment]
@richard-julien : https://demo.opencti.io/dashboard/analysis/reports/7b9d07c1-8a9e-44d6-aff7-4ac89312c03b

utils/Graph.js : methods `applyNodeFilters`, `applyLinkFilters` and `applyFilters`.
