### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1825]
## Description

Memory leak caused OpenCTI instance to crash. We're running with 2 GB memory (as recommended). I'm not sure what other information to share, or what would be useful, so please let me know.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: frontend
4. Other environment details: 2GB memory

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. ... use the platform and wait?
Not sure if something specific caused the crash

## Additional information

![image](https://user-images.githubusercontent.com/78382789/149594796-c2186991-3085-41da-bd86-a48464570538.png)

**Comment by nor3th** [comment]
Hey  @securitiz 

For which process or container is the graph for?

Regards

**Comment by richard-julien** [comment]
Hi @securitiz ,

By default on the docker size your provide 8G (NODE_OPTIONS=--max-old-space-size=8096)
Not sure where you find the recommendation for the 2 Go.

Can you try to profile your application for 8G to see how the platform behave?

Thanks

**Comment by securitiz** [comment]
@richard-julien I believe we were following the hardware requirements [listed here](https://www.notion.so/Infrastructure-requirements-674c810109ff42cb83002a3766592589#:~:text=512MB%20by%20default.-,Hardware%20requirements,-Search). We can adjust it, but are afraid that may just delay the problem

**Comment by richard-julien** [comment]
For now its not something we observe in our demo or prod environment. Depending of the activity of your OCTI (number of connectors/workers/clients) it could require more memory before reaching stability and so garbage that currently really clean some memory. If you still have the same memory shape with 8Go we will do more investigation to understand the problem. 
Thanks

**Comment by richard-julien** [comment]
Just to be sure you really observe a OutOfMemory in your logs? In your graphic it looks like the platform shutdown a 85% of memory usage

**Comment by securitiz** [comment]
We'll up it to 8GB and report back. The platform shut down at 85% due to ECS killing the container due to OOM. so there's no app logs available
