### ISSUE TITLE
Error Updating Author

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [LuatixHQ/opencti#1828]
Hi
Trying to change author of some observable, we receive error ‘Variable “$toId” of non-null type “String!” must not be null’
anyone knows why did it happens?
We can put the same author on other observables without any problems

Version is 5.1.3

**Comment by nor3th** [comment]
You experienced this issue using the UI, right? What page in specific?

Regards

**Comment by GiuseppeLaurenza** [comment]
Observations/Observable page

**Comment by SamuelHassine** [comment]
Hello @GiuseppeLaurenza,

I'm not able to reproduce the problem on the demo instance. You @nor3th?

Please can you send us a screenshot or the exact page where you have the problem?

Kind regaards,
Samuel
