### ISSUE TITLE
Be able to enrich in the analyst workbench

### ISSUE THREAD

**Issue by Snowty** [LuatixHQ/opencti#1830]
## Use case

When I search some ioc which is not in database, I want the enrichment connector can automatically enriched ioc.
eg, hash ioc can trigger the virustotal connector to search virustotal's database, and return the result to OpenCTI.

## If the feature request is approved, would you be willing to submit a PR?

Yes.

**Comment by SamuelHassine** [comment]
The feature is:

* Be able to bulk search SCOs / SDO: #2336 
* Be able to turn a search into a analyst workbench: #2408 
* Be able to enrich data from the analyst workbench

**Comment by nino-filigran** [comment]
Closing the issue since it will be done through Draft
