### ISSUE TITLE
Adding External Reference to File object (possibly other SCOs), while creating that object, results in Error

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1834]
## Description

When I create a File object, OpenCTI gives me the option to include an External Reference, at the bottom

When I go to add a new External Reference (adding the Source Name and URL), I get an error, and neither the File nor External Reference is Created

Current workaround is to create the External Reference separately, then link the two. 

## Environment

1. OS (where OpenCTI server runs): Ubunto 18.04
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: frontend
4. Other environment details: Was able to replicate this issue on the demo instance

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Observables
2. Create new File
3. Create a new External Reference to add to the File object
4. Add Source Name, URL
5. Select Create

## Expected Output

External Reference is created, attached to File, and I can carry on creating the File

## Actual Output

![image](https://user-images.githubusercontent.com/78382789/150585385-8aa5c049-3397-4b7e-9431-1d0b9580f178.png)

**Comment by nor3th** [comment]
Hey @securitiz 

What do the opencti platform logs say?

Regards

**Comment by securitiz** [comment]
This event doesn't generate an event in our opencti logs :/
