### ISSUE TITLE
View of countries

### ISSUE THREAD

**Issue by namnori72** [LuatixHQ/opencti#1836]
1. OS (where OpenCTI server runs): Ubuntu 16.4,,
2. OpenCTI version: OpenCTI 5.1.3

Hey, I created new Entities -> Country. Country has been added but view of all countries is still empty.

**Comment by namnori72** [comment]
![image](https://user-images.githubusercontent.com/87009374/150988402-32ec3d52-749e-4942-a9f8-daeb5adb0c33.png)

**Comment by namnori72** [comment]
![image](https://user-images.githubusercontent.com/87009374/150988513-0a362eb1-0e70-4596-8ade-ab75b7ac4a61.png)

**Comment by SamuelHassine** [comment]
Hello @namnori72,

We advise you to use the "OpenCTI datasets" connector to create countries / regions. In the mean time, this is a bug from the interface which does not show the countries that are not linked to a region (if you connect your country to a parent region, it will appear). It will be solve in the next major milestone.

Kind regards,
Samuel

**Comment by namnori72** [comment]
Yes, you right. I tried this way and it's work. Thank you for your help!
