### ISSUE TITLE
Date at timeline

### ISSUE THREAD

**Issue by namnori72** [LuatixHQ/opencti#1837]
1. OS (where OpenCTI server runs): Ubuntu 16.4,,
2. OpenCTI version: OpenCTI 5.1.3

When creating entities, the date next to the timeline is the date the entities were created, not the actual start/stop date.

![image](https://user-images.githubusercontent.com/87009374/150990692-bd0d5f73-fd62-40c1-9891-0688cd725e8e.png)
![image](https://user-images.githubusercontent.com/87009374/150990883-7fef6d4d-6fd9-44e4-968c-0d3d8d24411e.png)

**Comment by SamuelHassine** [comment]
Hello,

Please use the settings "Functional date" on timelines to see the actual dates and not the technical ones:

![image](https://user-images.githubusercontent.com/1334279/151898930-9b1a5f6d-9448-462c-a214-b4dec9233419.png)

Kind regards,
Samuel

**Comment by namnori72** [comment]
Great!!! 
Thank you so much for your reply.
