### ISSUE TITLE
Code scanning alert - Missing CSRF middleware

### ISSUE THREAD

**Issue by nor3th** [LuatixHQ/opencti#1839]
Tracking issue for:
- [ ] https://github.com/OpenCTI-Platform/opencti/security/code-scanning/17

**Comment by nor3th** [comment]
Shouldn't we change this to True by default?

https://github.com/OpenCTI-Platform/opencti/blob/63eb836d30b0f4764b805f25dcbe48e5d58b98dd/opencti-platform/opencti-graphql/src/database/session.js#L23

https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/default.json#L12

Or at least define it in the docker compose settings here
https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml

**Comment by SamuelHassine** [comment]
We will take a look at this @nor3th with @richard-julien. Thanks for raising this issue.
