### ISSUE TITLE
Removing report

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#1867]
## Problem to Solve
 
When removing a report/entity from a report, the tool should propose the removal of all or part of the relationships contained in the report/associated with the entity  we whish to remove in the report.

## Current Workaround

None

## Additional Information

**Comment by SYNchroACK** [comment]
**Proposal:**

When removing a report, it should ask to select one of the following options:
1. Remove only the report entity and all relationship objects associated to it;
2. Remove the report entity and all other entities (like observables) that were created during the ingestion of the report and which DO NOT have any relationships pointing to any other entity that will not be deleted (example: a threat actor that is being now used/linked by another report);

**Comment by SamuelHassine** [comment]
Linked to #1428, #1468
