### ISSUE TITLE
Error Message when installing with Portainer

### ISSUE THREAD

**Issue by caseyagil** [LuatixHQ/opencti#1872]
Attempting to setup OpenCTI with Portainer, shows everything is "running" however the it looks like when looking at the logs the main OpenCTI keeps erring out. Bit confused as to why and googling the error message is not finding possible solutions.

Worth noting, one moment Portainer shows an assigned IP and the 8080 port number and within 2 mins removed it, screenshot attached showing no IP assigned.

![Screen Shot 2022-02-01 at 9 26 44 PM](https://user-images.githubusercontent.com/3718778/152084058-7bb68838-b402-4fe9-a3de-a66d28e58658.png)

See below for the error message:

return new Exception();

         ^

ConfigurationError: A configuration error has occurred

    at error (/opt/opencti/build/src/config/errors.js:8:10)

    at ConfigurationError (/opt/opencti/build/src/config/errors.js:53:3)

    at /opt/opencti/build/src/database/elasticSearch.js:197:15

    at process.async (node:internal/process/task_queues:96:5)

    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:119:40)

    at initialization (/opt/opencti/build/src/initialization.js:378:3)

    at /opt/opencti/build/src/boot.js:7:16

{"category":"APP","error":{"data":{"_stack":"Error: getaddrinfo ENOTFOUND minio\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","message":"getaddrinfo ENOTFOUND minio"},"name":"UnknownError"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-02-02T01:58:38.954Z","version":"5.1.3"}

Error: getaddrinfo ENOTFOUND minio

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

{"category":"APP","error":{"data":{"_stack":"Error: getaddrinfo ENOTFOUND minio\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)","message":"getaddrinfo ENOTFOUND minio"},"name":"UnknownError"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-02-02T01:58:54.500Z","version":"5.1.3"}

[_openctitest2_opencti_1_logs.txt](https://github.com/OpenCTI-Platform/opencti/files/7983168/_openctitest2_opencti_1_logs.txt)

**Comment by nor3th** [comment]
Hey @caseyagil 

It looks to me like a few connectors aren't running due to the missing IP addresses. Maybe check minio, as it is the only required backend service which isn't running and is also mentioned in the error logs.
```
... Error: getaddrinfo ENOTFOUND minio...
```

Regards

**Comment by caseyagil** [comment]
Ok thank you for the assist, I will go tinker

**Comment by caseyagil** [comment]
Closing this, I did not realize there was a password min length. fixed and working.
