### ISSUE TITLE
Code scanning alerts - Type confusion through parameter tampering + others

### ISSUE THREAD

**Issue by nor3th** [LuatixHQ/opencti#1873]
Tracking security issues for:
- [ ] https://github.com/OpenCTI-Platform/opencti/security/code-scanning/16
- [ ] https://github.com/OpenCTI-Platform/opencti/security/code-scanning/15
- [ ] https://github.com/OpenCTI-Platform/opencti/security/code-scanning/14

**Comment by SamuelHassine** [comment]
Will be tracked individually and fixed as we improve the product security.
