### ISSUE TITLE
Creating multiples `resolves-to` between a domain and an ip raises a cyclic relationship error

### ISSUE THREAD

**Issue by axelfahy** [LuatixHQ/opencti#1884]
## Description

Issue #1818, which is not resolved. 

## Environment

1. OS (where OpenCTI server runs): MacOS, docker
2. OpenCTI version: 5.1.4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Domain name (e.g. `mydomain.com`)
2. Create an IPv4 address (e.g. `1.1.1.1`)
3. Under `Knowledge`, `Linked Observables`, add a `resolves-to` relationship between the domain and the ip with start time 2022.02.01 and end time 2022.02.02.
4. Add another `resolves-to` relationship between the same domain and the same ip, with start time 2022.02.07 and end time 2022.02.08.

## Expected Output

Both `resolves-to` relationships are present, one from 2022.02.01 to 2022.02.02 and the second one from 2022.02.07 to 2022.02.08.

## Actual Output

An error is raised, and the second relationship is not added. 

![image](https://user-images.githubusercontent.com/7095119/152945499-09210787-0985-4da0-ad6e-c65018d69976.png)

## Additional information

Additional information is available in the original issue.

**Comment by SamuelHassine** [comment]
Hello @axelfahy,

It seems that your observables have the same IDs (in other STIX IDs). I think this is a thing that is not expected. Can you please check your 2 observables (standard ID + other STIX IDs)?

![image](https://user-images.githubusercontent.com/1334279/152946482-6d04ae57-bf19-4ccc-9dda-a875fccf878c.png)

Thanks.

**Comment by SamuelHassine** [comment]
Sorry, I've just reproduced the bug. I will deep dive as soon as possible to solve it definitely.
