### ISSUE TITLE
OpenCTI shows blank views and it does not work

### ISSUE THREAD

**Issue by Tyrell20** [LuatixHQ/opencti#1885]
## Description

After a period of activity OpenCTI stops working by showing a white screen

## Environment

1. OS (where OpenCTI server runs): Red Hat Enterprise Linux Server release 7.9 (Maipo)
2. OpenCTI version: 1.5.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Execute docker-compose up
2. Login to OpenCTI dashboard with success
3. After a while the system does not load any views and show a blank screen
 
## Additional information
 docker logs docker_opencti_1 shows the error below:

`639a999c0055","querystring":"retry_on_conflict=5&timeout=5m&refresh=true","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"http_status":500,"reason":"Error updating elastic"},"stacktrace":["DatabaseError: A database error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at DatabaseError (/opt/opencti/build/src/config/errors.js:45:3)","at /opt/opencti/build/src/database/engine.js:1744:13","at runMicrotasks (<anonymous>)","at process.error (node:internal/process/task_queues:96:5)","at reportActionImport (/opt/opencti/build/src/domain/work.js:242:22)"]},"inner_relation_creation":0,"level":"warn","message":"API Call","operation":"reportExpectation","operation_query":"mutation reportExpectati^Con($id:ID!$error:WorkErrorInput){workEdit(id:$id){reportExpectation(error:$error)}}","size":789,"time":12,"timestamp":"2022-02-08T02:23:13.160Z","type":"WRITE_ERROR","user":{"applicant_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","call_retry_number":"1","ip":"::ffff:172.19.0.34","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"version":"5.1.4"}`

In addition docker_elasticsearch_1 containers is in restart status and logs show the message below:

`{"type": "server", "timestamp": "2022-02-08T06:22:29,996Z", "level": "ERROR", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "a604009a86e7", "message": "exception during geoip databases update", "cluster.uuid": "82-v51qrTFOuUrxQTCuYqg", "node.id": "k3GkKsCRRICsHVMulrTR9w" ,
"stacktrace": ["java.net.SocketTimeoutException: Connect timed out",`

`{"type": "server", "timestamp": "2022-02-08T06:22:48,155Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "docker-cluster", "node.name": "a604009a86e7", "message": "path: /opencti_history*/_search, params: {ignore_throttled=false, index=opencti_history*}", "cluster.uuid": "82-v51qrTFOuUrxQTCuYqg", "node.id": "k3GkKsCRRICsHVMulrTR9w" ,
"stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",` 

Many thanks for your help.

**Comment by richard-julien** [comment]
Looks like not related to openCTI directly, but an elasticsearch problem > "exception during geoip databases update".
Im not an expert on that i think stackoverflow will be a better help :)

**Comment by Tyrell20** [comment]
Hi @richard-julien thanks for suggestion.
I disabled the geoip update adding in docker-compose file the string below:
`ingest.geoip.downloader.enabled=false`

Restarting docker still show the same behavior. OpenCTI stop to work showing the error below:

`Error An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.`  

before the blank screen.

Checking the logs of elasticsearch's container (continuosly restart) shows error below:

`2022-02-08T16:49:21.243456000Z "stacktrace": ["org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];",`

**Comment by Tyrell20** [comment]
Hello,
could you please help us? 
We have the same errors with 5.3.1 version also.
