### ISSUE TITLE
listEntitiesByHashes should not look for fuzzy algorithm to prevent unwanted merging

### ISSUE THREAD

**Issue by debelyoo** [LuatixHQ/opencti#1899]
## Description

When merging Stix files with multiple hashes (including SSDEEP), hashes collision errors are generated. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Ingest a number of files (Stix file objects) with multiple hashes defined (e.g. MD5, SHA-1, SSDEEP). At least two files have the same SSDEEP hash.

## Expected Output

The files should be inserted without trying to merge the observables.

## Actual Output

When the second file with the common SSDEEP value is ingested in OpenCTI, a "hashes collision error" is thrown.

**Comment by richard-julien** [comment]
Updated ticket name and definition to be more accurate

**Comment by debelyoo** [comment]
Great. Thanks !
