### ISSUE TITLE
From a Report, view what other Reports have IOCs in common

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1903]
## Use case

When viewing a Report (specifically, the Overview section), it would be very helpful to see a list of Reports that share Observables with the current Report.

The request is for Reports that share Observables and not SDOs, because there are likely to be very many reports that share Attack Patterns, Countries etc. Perhaps the user could decide, but I think displaying reports with shared Observables would be most helpful. 

## Current Workaround

Go to Investigation workspace, add a report. Expand the report (all objects), remove the SDOs, then expand all the remaining objects (reports only)

## Proposed Solution

A section in the Overview of a Report that displays which reports share Observables with the current report. Preferably sorted by which report shares the most observables. I'm imagining a toggle button which would display the observables shared below the report, or clicking on the name of the Report would take the user to the Report. See screenshot for a mockup. 

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/154611259-e23ca5d0-dd1c-4b35-b4eb-e5bf060b48fc.png)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Already implemented.
