### ISSUE TITLE
Add "Rust" to Malware programming languages + allow Admins to add custom languages

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1905]
## Use case

The list of programming languages for Malware is limited

## Current Workaround

n/a

## Proposed Solution

Add rust + allow admins to add programming languages as necessary

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by guys1444** [comment]
**Link or Image to this case ?, Thanks**

do you mean as a new entity ?

**Comment by securitiz** [comment]
Not as a new entity. I've attached a screenshot below. When updating a malware, you can specify what language it is written in, and rust is not in that list:

![image](https://user-images.githubusercontent.com/78382789/155755846-b52c2d57-0c62-47e7-9521-3fd670e20b36.png)

![image](https://user-images.githubusercontent.com/78382789/155756778-4695f0f8-1cbd-47b4-887d-0aca9f043008.png)

**Comment by securitiz** [comment]
This may be fixed by #1886 if it is applied to other parameters such as Threat Actor's "Resource Level", Malware's "Malware Types", and in this case Malware's "Architecture Execution Environment"
