### ISSUE TITLE
Errors when sending email subscription but no information of the problem are provided

### ISSUE THREAD

**Issue by RomainGUIGNARD** [LuatixHQ/opencti#1910]
## Description

Some errors occurred while sending subscription email but no information are provided in the logs.
{"category":"APP","error":{},"level":"error","message":"[OPENCTI] Subscription manager failed to send","timestamp":"xxxxxxxxxx","version":"5.1.3"}

Moreover, the code seems to try continuously to send the email and enter in an infinite loop. 

## Environment

2. OpenCTI version: 5.1.3

**Comment by richard-julien** [comment]
Do you know if the mail is received or not sent at all?

**Comment by SamuelHassine** [comment]
Closing this issue as we have fixed the subscription manager so a failure during the sending process will not block the manager anymore.
