### ISSUE TITLE
OpenID Configuration not applying

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#1911]
## Description

While trying to integrate Okta/OpenID Connect with OpenCTI to accommodate role mapping between groups in Okta to roles in OpenCTI, environmental configuration settings are not applying as expected. 

I have Okta/OpenID sending the groups/roles in the auth response, but the mapping within OpenCTI is failing.  I have tried different env variables like changing the reference token, however it has no effect.

## Environment

1. OS (where OpenCTI server runs): Amazon Linux 2
3. OpenCTI client: OpenCTI 5.1.2
4. Other environment details:
     Running on AWS ECS/Farget
     Environment variables are passed from AWS Secrets manager to AWS ECS

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Okta/OpenID Connect application (Okta) including a Groups Claim:
https://developer.okta.com/docs/guides/customize-tokens-groups-claim/main/
2. Create configuration settings for OpenCTI
3. try to login via OpenID provider

## Expected Output

Successful login with mapped roles

## Actual Output

I get the following logs:
![image](https://user-images.githubusercontent.com/30411037/155180671-b822f733-80ee-48de-b6cb-dfd7334b8fb5.png)

Env Config for mapping:
![Screen Shot 2022-02-22 at 10 58 20 AM](https://user-images.githubusercontent.com/30411037/155180932-7d2e066c-0df1-4a43-aedd-a9da1bd78e66.png)

**Comment by richard-julien** [comment]
The configuration is apply on the jwt token, not on userinfo.
OpenCTI doesnt log the token so its not possible to know with your ticket if you have something to do.
In order to help you you need to check that okta reply in the access token.
The only thing we can do to help you is to log token content in opencti in the next release.

**Comment by SamuelHassine** [comment]
I'm closing this issue for the moment. We have added new logging information (content of the tokens received) so it should now be easier to understand what's going on.
