### ISSUE TITLE
Creation of an indicator without name

### ISSUE THREAD

**Issue by 2xyo** [LuatixHQ/opencti#1912]
## Description

Creation of an indicator without name is not possible as required in STIX™ Version 2.1 and in the STIX™ 2.1 Interoperability Test Document Version 1.0.

## Environment

https://demo.opencti.io/dashboard/observations/indicators?

## Reproducible Steps

1. Create an Indicator with just a `pattern` and a `pattern_type` on https://demo.opencti.io/dashboard/observations/indicators?

## Expected Output

Indicator is created.

## Actual Output

Error "This field is required"  for the `name` field.

## Additional information

- [STIX™ Version 2.1](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_wfiae74706sw)
 
`name` field is optional  for the Indicator  SDO.

- [STIX™ 2.1 Interoperability Test Document Version 1.0](https://www.oasis-open.org/committees/download.php/69153/STIX%202.1%20Interoperability%20Test%20Document-FINAL%20Version.docx  )
   - 3.1.4.1 Add Context to Indicator
  

3.1.4.1 Add Context to Indicator
```json
{
    "type": "identity",
    "id": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff",
    "spec_version": "2.1",
    "identity_class": "organization",
    "name": "ACME Corp, Inc.",
    "created": "2018-01-17T11:11:13.000Z",
    "modified": "2018-01-17T11:11:13.000Z",
    "created_by_ref": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff"
},
{
    "type": "indicator",
    "spec_version": "2.1",
    "id": "indicator--0c7e22ad-b099-4dc3-b0df-2ea3f49ae2e6",
    "created_by_ref": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff",
    "created": "2019-05-12T08:17:27.000Z",
    "modified": "2019-05-12T08:17:27.000Z",
    "indicator_types": ["malicious-activity"],
    "pattern": "[url:value = 'http://badsite.com/foo' OR url:value = 'http://badsite.com/bar']"
    "pattern_type": "stix",
    "valid_from": "2019-01-01T00:00:00Z"
},
{
    "type": "attack-pattern",
    "spec_version": "2.1",
    "id": "attack-pattern--7e33a43e-e34b-40ec-89da-36c9bb2cacd5",
    "created_by_ref": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff",
    "created": "2019-05-12T08:17:27.000Z",
    "modified": "2019-05-12T08:17:27.000Z",
    "name": "Spear Phishing as Practiced by Adversary X",
    "description": "Spear phishing where the attacker includes personal details in the email and claims that the target had won a contest.",
    "external_references": [
        {
            "source_name": "capec",
            "external_id": "CAPEC-163"
        }
    ]
},
{
    "type": "relationship",
    "spec_version": "2.1",
    "id": "relationship--57b56a43-b8b0-4cba-9deb-34e3e1faed9e",
    "created_by_ref": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff",
    "created": "2019-05-12T08:17:27.000Z",
    "modified": "2019-05-12T08:17:27.000Z",
    "relationship_type": "indicates",
    "source_ref": "indicator--0c7e22ad-b099-4dc3-b0df-2ea3f49ae2e6",
    "target_ref": "attack-pattern--7e33a43e-e34b-40ec-89da-36c9bb2cacd5"
}

```

It's not possible to validate this test case as no description is provided in the attack pattern SDO.

**Comment by SamuelHassine** [comment]
Automatically generate the name if not given from the indicator pattern.

**Comment by SamuelHassine** [comment]
Fixed this as name is automatically set to pattern if not provided.
