### ISSUE TITLE
Add option wantAssertionsSigned in the SAML configuration

### ISSUE THREAD

**Issue by yoan-arley** [LuatixHQ/opencti#1916]
## Description

we want to authenticate OpentCTI with SALM.
During authentication with SAML, authentication fails and returns error 'Invalid Signature'

## Environment

1. OS CentOS 7 
2. OpenCTI version: 5.1.4
3. OpenCTI client: frontend
4. Other environment details: Virtual environment with Docker Swarm and Portainer

## Reproducible Steps
Steps to create the smallest reproducible scenario:
1. container configuration :
    - PROVIDERS__SAML__STRATEGY=SamlStrategy
    - "PROVIDERS__SAML__CONFIG__LABEL=Login with SAML"
    - PROVIDERS__SAML__CONFIG__ISSUER=opencti
    - PROVIDERS__SAML__CONFIG__ENTRY_POINT=https://authrsx.xxxxxxx.lan/saml/singleSignOn
    - PROVIDERS__SAML__CONFIG__SAML_CALLBACK_URL=https://xxxxxxx.xxxxxxx.lan:4443/auth/saml/callback
    - PROVIDERS__SAML__CONFIG__CERT=MIIGOj--SAMl_Certificate--EOiYfqew=
    - PROVIDERS__SAML__CONFIG__PRIVATE__KEY=MIIJKQIBAA--OpenCTI_Cerificate_Key--wmk13g5   
    - PROVIDERS__SAML__CONFIG__wantAssertionsSigned=false
2. The SAML login button is present.
3. authentication fails and returns error 'Invalide Signature'

## Expected Output

User authenticates and accesses dashboards

## Actual Output

OpenCTI return 'Invalid signature'

during authentication with SAML, OpenCTI connects well to the authentication server but does not recover the session (see the logs):
    Required urldc : https://xxxxxx.xxxxxxx.lan:4443/auth/saml/callback
    Set CSP form-action with urldc : https://xxxxxxx.xxxxxxx.lan:4443
    Required Params URL : https://xxxxxxxx.xxxxxxx.lan:4443/auth/saml/callback
    Set CSP form-action with Params URL : https://xxxxxxx.xxxxxxxx.lan:4443
    Apply following CSP : default-src 'self';img-src 'self' data:;style-src 'self';font-src 'self';connect-src 'self';script-src 'self';form-action * https://xxxxxxxx.xxxxxxx.lan:4443 https://xxxxxxxx.xxxxxxxx.lan:4443;frame-ancestors 'none';
    VH authrsx.xxxxxxxx.lan is HTTPS
    Get session dddddddddddddddddddddddddddddddddddddddddddd from Handler internal cache
    No URL authentication level found...
    authrsx.retraite.lan: Apply default rule
    removing cookie
    Cookies -> llxglanguage=fr; lemonldap=dddddddddddddddddddddddddddddddddddddddddddd
    CookieName -> lemonldap
    newCookies -> llxglanguage=fr;
    User yyyyyyy was granted to access to /portal.css
    Start routing portal.css
 
## Additional informations

The SAML authentication server is managed from LemonLDAP.
The OpenCTI logs do not give us details.
The certificates are signed by our PKI.

**Comment by richard-julien** [comment]
Hi @yoan-arley , it will be complex to help without a way to reproduce the problem.
I can add the support of want_assertions_signed but not sure it will solve your problem.

**Comment by richard-julien** [comment]
PROVIDERS__SAML__CONFIG__WANT_ASSERTIONS_SIGNED=false

**Comment by richard-julien** [comment]
Hum, looking deeper into your configuration @yoan-arley  looks like you have a problem

PROVIDERS__SAML__CONFIG__PRIVATE__KEY=MIIJKQIBAA--OpenCTI_Cerificate_Key--wmk13g5

Should be:
PROVIDERS__SAML__CONFIG__PRIVATE_KEY=MIIJKQIBAA--OpenCTI_Cerificate_Key--wmk13g5

You double the __ for PRIVATE__KEY but it should be only one

**Comment by SamuelHassine** [comment]
I'm closing this issue since we have added the configuration `PROVIDERS__SAML__CONFIG__WANT_ASSERTIONS_SIGNED`. Please re-open a question or reach us on Slack if you still have some issues configuring SAML.
