### ISSUE TITLE
User access information mssing

### ISSUE THREAD

**Issue by remydewa** [LuatixHQ/opencti#1919]
## Description

Actually in a user account page (ie: dashboard/settings/accesses/users/88ec0c6a-13ce-5e39-b486-354fe4a7084f) we don't have the sessions history for users other than our admin account. Maybe an issue with role permissions?

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI 5.1.4
3. OpenCTI client: frontend

## Reproducible Steps
our admin account with default role
![Screenshot from 2022-02-25 19-10-55](https://user-images.githubusercontent.com/53039170/155766405-b419f4e9-94ed-4342-a71f-6931a4dedf37.png)

another account with analyst role
![Screenshot from 2022-02-25 19-12-47](https://user-images.githubusercontent.com/53039170/155766460-ab6f0639-326d-4ab0-9c9e-a65e2654e320.png)
We know that this account is connected  everyday.

## Expected Output

We want to have the history session for all kind of users as our admin account.

**Comment by SamuelHassine** [comment]
Hello @remydewa,

This screen is just listing the current sessions and not the session history. If you want to have a proper logging of all successful logins, you can use the audit log feature.

Kind regards,
Samuel
