### ISSUE TITLE
Example TypeScript with React memoization for components + README

### ISSUE THREAD

**Issue by mschreib28** [LuatixHQ/opencti#1928]
## Use case

Provide some example TypeScript with React memoization for components as well as a basic README on conversion.

## Current Workaround

Use existing JavaScript.

## Proposed Solution

Create an example or two of some TypeScript implementations for React to enable others within the community to leverage and contribute.

## Additional Information

Spoke with @SamuelHassine about this already.

## If the feature request is approved, would you be willing to submit a PR?

Yes.

**Comment by SamuelHassine** [comment]
Typescript in both backend and frontend will be an on-going effort along the next months.
