### ISSUE TITLE
Is Native S3 Support Possible?

### ISSUE THREAD

**Issue by eternalyperplxed** [LuatixHQ/opencti#1929]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

If running the containers in AWS EKS, is there a way to not use Minio and use the native EBS/EFS CSI providers for persistent storage? It seems it's been discussed as a roadmap item but I haven't seen any configuration options or documentation for it. More generally, is there guidance for running OpenCTI in a Kubernetes environment?

## Environment

1. OS - AWS EKS on latest AL2 image

**Comment by nor3th** [comment]
Hey

We don't officially support EBS/EFS CSI, but I know that quite a few users are deploying OpenCTI in the cloud. I'd recommend to ask in our slack channel if anybody has any experiences with a setup like yours.

Concerning Kubernetes: https://github.com/OpenCTI-Platform/docker/issues/50

Regards

**Comment by TechBurn0ut** [comment]
@eternalyperplxed - Yes native S3 is supported.  On your opencti-platform container/service you need to use the following configuration.  This is just a simple JSON representation of the settings (export from AWS Secrets), you will need to adjust accordingly for your platform.

As far as running on AWS EKS, I suggest reaching out to the community in the OpenCTI Slack channel.   There are multiple members that have the platform deployed on either AWS EKS, or AWS ECS.

```
{
  "MINIO__ACCESS_KEY": "<IAM User Access Key>",
  "MINIO__BUCKET_NAME": "<AWS S3 bucket name>",
  "MINIO__ENDPOINT": "s3.amazonaws.com",
  "MINIO__PORT": "443",
  "MINIO__SECRET_KEY": "<IAM User Secret Key",
  "MINIO__USE_SSL": "true",
  "MINIO__BUCKET_REGION": "<AWS Region>"
}
```

**Comment by eternalyperplxed** [comment]
> @eternalyperplxed - Yes native S3 is supported. On your opencti-platform container/service you need to use the following configuration. This is just a simple JSON representation of the settings (export from AWS Secrets), you will need to adjust accordingly for your platform.
> 
> As far as running on AWS EKS, I suggest reaching out to the community in the OpenCTI Slack channel. There are multiple members that have the platform deployed on either AWS EKS, or AWS ECS.
> 
> ```
> {
>   "MINIO__ACCESS_KEY": "<IAM User Access Key>",
>   "MINIO__BUCKET_NAME": "<AWS S3 bucket name>",
>   "MINIO__ENDPOINT": "s3.amazonaws.com",
>   "MINIO__PORT": "443",
>   "MINIO__SECRET_KEY": "<IAM User Secret Key",
>   "MINIO__USE_SSL": "true",
>   "MINIO__BUCKET_REGION": "<AWS Region>"
> }
> ```

Perfect, thank you for this, I'll give it a shot!
