### ISSUE TITLE
Error when rendering PDF in the content section of Analysis in version 5.1.4

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#1937]
## Description

In version 5.1.4 of OpenCTI, the pdf files are not rendered in the content section of Analysis. "Failed to load PDF file." is showed instead of the pdf viewer.

The same seems to happen in version 5.1.3 when a base_path is specified.

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: 5.1.4
3. OpenCTI client: frontend
4. Other environment details: docker-compose stack

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new analysis
2. upload a pdf file in the data section
3. select the uploaded pdf in the content section

## Expected Output

The pdf viewer should run showing the content of the file

## Actual Output

The error "Failed to load PDF file." is showed instead of the pdf viewer

## Screenshots

![screenshot-opencti](https://user-images.githubusercontent.com/14950949/156549830-b33c6c11-e261-4166-b69f-40ba3e9b36df.png)

**Comment by SamuelHassine** [comment]
PDF render is now ok, but the full feature o
