### ISSUE TITLE
Error when update from 5.1.4 to 5.2.0

### ISSUE THREAD

**Issue by InnerFireZ** [LuatixHQ/opencti#1938]
## Description

When update opencti/platform from version 5.1.4 to 5.2.0 web service on port 8080(default web port) goes down (not reachable)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 21.10
2. OpenCTI version: 5.2.0
4. Other environment details:
running on portainer

## Expected Output

Web service must run on port 8080

## Actual Output

Error log from container:

{"category":"APP","error":{"data":{"_stack":"TypeError: Invalid Version: undefined\n    at new B2 (/opt/opencti/build/node_modules/semver/classes/semver.js:19:13)\n    at Iri (/opt/opencti/build/node_modules/semver/functions/compare.js:3:3)\n    at Object.Xri [as lt] (/opt/opencti/build/node_modules/semver/functions/lt.js:2:29)\n    at K2r (/opt/opencti/build/src/initialization.js:359:14)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at W2r (/opt/opencti/build/src/initialization.js:383:7)\n    at yjn (/opt/opencti/build/src/boot.js:9:3)","message":"Invalid Version: undefined"},"name":"UnknownError"},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2022-03-04T09:11:44.788Z"}
    at new B2 (/opt/opencti/build/node_modules/semver/classes/semver.js:19:13)
TypeError: Invalid Version: undefined
    at Iri (/opt/opencti/build/node_modules/semver/functions/compare.js:3:3)
    at K2r (/opt/opencti/build/src/initialization.js:359:14)
    at Object.Xri [as lt] (/opt/opencti/build/node_modules/semver/functions/lt.js:2:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at W2r (/opt/opencti/build/src/initialization.js:383:7)
    at yjn (/opt/opencti/build/src/boot.js:9:3)

## Additional information

When I revert to 5.1.4 eventing is back to normal.

**Comment by SamuelHassine** [comment]
Hello @innerfirebg,

You've been too quick to pull the new image.  You can re-pull it (it's now solved) or wait for the 5.2.1.

Kind regards,
Samuel

**Comment by InnerFireZ** [comment]
Hello,
Thanks so much! Next time I will wait.
