### ISSUE TITLE
[FR] Request for the knowledge graph for reports to have the ability to be multiselected (via drag box/ window)

### ISSUE THREAD

**Issue by kudrew** [LuatixHQ/opencti#1941]
## Use case

We would like the ability for analysts to multiselect entities in the knowledge graph using draggable windows using their mouse,

**Comment by ckane** [comment]
Was discussing with some colleagues today, and there's already a "selection" section in the toolbar at the bottom of the screen. It would be great to add a "rectangular select tool" for this feature, as well as a "lasso select tool" (for #1466) in the toolbar that would change the mouse-click behavior while it is active. When active, the left-mouse behavior would allow you to draw a rectangle that selects a new set of entities, which are inside the rectangle. If there is already a selection, and the analyst holds down shift while clicking+dragging for a rectangle selection, any unselected entities within that selection rectangle would be added to the existing selection. If the analyst were to shift-drag a rectangle across a group of entities that were ALL already a part of the current selection, they could be removed from the selection that way. Alternately, the ALT modifier key could be used to "unselect" which I think would sort-of mirror the convention used for "exclusions" in the search query parameters.
![image](https://user-images.githubusercontent.com/3454769/218337308-50e07452-7508-4838-913b-2c341228db95.png)
