### ISSUE TITLE
Ability to create additional custom workflow status names straight from the UI if possible.

### ISSUE THREAD

**Issue by kudrew** [LuatixHQ/opencti#1943]
## Use case
Ability to create additional custom workflow status names straight from the UI if possible. 
<img width="998" alt="Screen Shot 2022-03-04 at 11 46 12 AM" src="https://user-images.githubusercontent.com/51339113/156804386-0346460b-aca6-4a94-9eaa-fab6043ad05a.png">

**Comment by rabbipigeon** [comment]
Any Idea when this feature is coming? @SamuelHassine

**Comment by SamuelHassine** [comment]
Please use the AutocompleteFreeSolo field.
