### ISSUE TITLE
[FEATURE] HTTP list feeds

### ISSUE THREAD

**Issue by mwatermolen** [LuatixHQ/opencti#1945]
## Use case

Many firewalls can pull IOCs from a newline seperated HTTP feed

## Current Workaround

Using an external codebase to covert taxii to feed

## Proposed Solution

API EP like the Taxii config that provides the IOC's alone on new lines, in a rolling format
example:
```
1.1.1.1
google.com
email@mail.mail
```
## Additional Information

SEE https://luatix.slack.com/archives/CHZC2D38C/p1646255556608159
EDIT: adding @TechBurn0ut

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by richard-julien** [comment]
Can we see that as a HTTP CSV rolling feed?
First ideas.

###  User define a HTTP Feed
User create a feed using filters AND decide for each type, the data he wants to expose.
Example:
- Name: Http Feed 1, for Domain and Email.
- Filters: Domain & EmailAddr
- Columns: 
ID = Domain -> id, EmailAddr -> id
VALUE = Domain -> value, EmailAddr -> value
- Periodicity: Created or updated in the last 60 minutes

### Behavior
User access /feed/http/feed1
Data will be published like this
> #Feed 1 from XX/XX/XXXXTXX:XX:XXZ to XX/XX/XXXXTXX:XX:XXZ
> ID, VALUE
> domain-name--faa5b705-cf44-4e50-8472-29e5fec43c2c,1.1.1.1
> domain-name--faa5b705-cf44-4e50-8472-29e5fec43c1c,google.com
> email-addr--faa5b705-cf44-4e50-8472-29e5fec43c3c,email@mail.mail

Obviously if the firwall doesnt ping for 60 minutes it could lost some information.

Feel free to discuss this approach :)

**Comment by mwatermolen** [comment]
So @richard-julien I do like this approach, but our ultimate goal is to be able to use [Fortinet Threat Feeds](https://docs.fortinet.com/document/fortigate/6.2.0/cookbook/9463/threat-feeds)... Im not sure it will work with this approach

**Comment by mwatermolen** [comment]
Maybe, making ID's toggleable on/off

**Comment by richard-julien** [comment]
In my proposal the user decide the column, so if you doesnt want the id, you can just select one value.

- Name: Fortinet Feed
- Filters: Domain & EmailAddr
- Columns:
- VALUE = Domain -> value, EmailAddr -> value
- Periodicity: Created or updated in the last 60 minutes

Will produce

> #Fortinet Feed from XX/XX/XXXXTXX:XX:XXZ to XX/XX/XXXXTXX:XX:XXZ
> VALUE
> 1.1.1.1
> google.com
> email@mail.mail

**Comment by mwatermolen** [comment]
Oh, my bad... that would be excllent!

**Comment by hiran1239** [comment]
Hi,

Is this feature released yet or not?

Thanks
