### ISSUE TITLE
map.opencti.io tiles don't load because of cross-origin-resource-policy

### ISSUE THREAD

**Issue by rantebi** [LuatixHQ/opencti#1948]
## Description

Suddenly my map tiles won't load. Supposedly due to "cross-origin-resource-policy" not set in the response header of the tiles.

## Environment

1. OS: Ubuntu
2. OpenCTI version: 5.1.4
3. OpenCTI client: frontend
4. Other environment details: **chrome browser (Version 98.0.4758.109 (Official Build) (x86_64)) on mac.** (BTW on Safari there's no problem for now).

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to a page with an embedded map (tiles server set to: map.opencti.io)
2. The Polygons are loaded, but the tiles underneath are blank
3. Go to developer tools > network tab and stand on one of the image files, and you will see the following error.

## Expected Output

See the map with the tiles

## Actual Output

I don't see the tile in the map (in Chrome browser)
In the developer tools I see the following error:

## Additional information
Chrome documentation says you need to either add 'cross-origin-resource-policy' to the response header of the tiles. or add a Cross-Origin-Embedder-Policy: credentialless header to your document but I am still not sure how to do it with helmet.
Also, this issue is not to be confused with https://github.com/OpenCTI-Platform/opencti/issues/1055 

## Screenshots (optional)
<img width="1238" alt="Screen Shot 2022-03-06 at 15 25 43" src="https://user-images.githubusercontent.com/1233686/156925334-4e8f2a5a-1951-42aa-b98a-30b4f925d3c2.png">
<img width="1276" alt="Screen Shot 2022-03-06 at 15 26 18" src="https://user-images.githubusercontent.com/1233686/156925339-84bd6d10-5060-4c23-bbfe-f6c705585212.png">

**Comment by SamuelHassine** [comment]
Hello @rantebi,

We have been aware of such problem but we have fixed them in 5.2+. Can you please tell us if you still have a problem after upgrading in 5.2+?

Thanks a lot.

Kind regards,
Samuel

**Comment by rantebi** [comment]
It looks good now, but I must say it also works with an older version of OpenCTI platform. Did you happen to make the change on the tile server? In that case, it explains why it also works with older OCTI.

**Comment by SamuelHassine** [comment]
No change on our side, but one specific version was bugged :)
