### ISSUE TITLE
Dashboard distributions widget doesn't handle correctly TLP restrictions

### ISSUE THREAD

**Issue by fitz003** [LuatixHQ/opencti#1955]
## Description

After upgrading to 5.2.1, users who only have access to all of the marking definitions are not able to load the dashboard.

## Environment

1. OS: Docker
2. OpenCTI version: 5.2.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a user that doesn't have access to all marking definitions
2. Ensure there is data in the platform that is marked with a marking definition that this user does not have access to (e.g. TLP: Red)
3. Login as the user, and try viewing the default dashboard

## Expected Output

User should be able to load all of the default widgets in the dashboard

## Actual Output

Dashboard loads for a few seconds and then will crash.

## Additional information

Error log from OpenCTI:

`{
   "category":"APP",
   "error":{
      "stacktrace":[
         "Error: Cannot return null for non-nullable field Malware.id.",
         "at OW (/opt/opencti/build/node_modules/graphql/execution/execute.js:592:13)",
         "at jsn (/opt/opencti/build/node_modules/graphql/execution/execute.js:487:19)",
         "at epe (/opt/opencti/build/node_modules/graphql/execution/execute.js:411:20)",
         "at _Le (/opt/opencti/build/node_modules/graphql/execution/execute.js:906:10)",
         "at p_r (/opt/opencti/build/node_modules/graphql/execution/execute.js:793:10)",
         "at OW (/opt/opencti/build/node_modules/graphql/execution/execute.js:622:12)",
         "at jsn (/opt/opencti/build/node_modules/graphql/execution/execute.js:487:19)",
         "at epe (/opt/opencti/build/node_modules/graphql/execution/execute.js:411:20)",
         "at _Le (/opt/opencti/build/node_modules/graphql/execution/execute.js:906:10)",
         "at OW (/opt/opencti/build/node_modules/graphql/execution/execute.js:633:12)",
         "at /opt/opencti/build/node_modules/graphql/execution/execute.js:694:25",
         "at Function.from (<anonymous>)",
         "at l_r (/opt/opencti/build/node_modules/graphql/execution/execute.js:674:34)",
         "at OW (/opt/opencti/build/node_modules/graphql/execution/execute.js:605:12)",
         "at /opt/opencti/build/node_modules/graphql/execution/execute.js:484:9",
         "at runMicrotasks (<anonymous>)"
      ]
   },
   "inner_relation_creation":0,
   "level":"error",
   "message":"API Call",
   "operation":"StixCoreRelationshipsHorizontalBarsDistributionQuery",
   "operation_query":"query StixCoreRelationshipsHorizontalBarsDistributionQuery($relationship_type:String!$toTypes:[String]$field:String!$operation:StatsOperation!$startDate:DateTime$endDate:DateTime$dateAttribute:String$limit:Int){stixCoreRelationshipsDistribution(relationship_type:$relationship_type toTypes:$toTypes field:$field operation:$operation startDate:$startDate endDate:$endDate dateAttribute:$dateAttribute limit:$limit){label value entity{__typename ...on BasicObject{__isBasicObject:__typename entity_type}...on BasicRelationship{__isBasicRelationship:__typename entity_type}...on AttackPattern{name description id}...on Campaign{name description id}...on CourseOfAction{name description id}...on Individual{name description id}...on Organization{name description id}...on Sector{name description id}...on System{name description id}...on Indicator{name description id}...on Infrastructure{name description id}...on IntrusionSet{name description id}...on Position{name description id}...on City{name description id}...on Country{name description id}...on Region{name description id}...on Malware{name description id}...on ThreatActor{name description id}...on Tool{name description id}...on Vulnerability{name description id}...on Incident{name description id}...on Artifact{id}...on AutonomousSystem{id}...on Directory{id}...on DomainName{id}...on EmailAddr{id}...on EmailMessage{id}...on EmailMimePartType{id}...on ExternalReference{id}...on IPv4Addr{id}...on IPv6Addr{id}...on KillChainPhase{id}...on Label{id}...on MacAddr{id}...on MarkingDefinition{id}...on Mutex{id}...on NetworkTraffic{id}...on Note{id}...on ObservedData{id}...on Opinion{id}...on Process{id}...on Report{id}...on Software{id}...on StixCoreRelationship{id}...on StixCyberObservableRelationship{id}...on StixFile{id}...on StixMetaRelationship{id}...on StixSightingRelationship{id}...on Url{id}...on UserAccount{id}...on WindowsRegistryKey{id}...on WindowsRegistryValueType{id}...on X509Certificate{id}...on X509V3ExtensionsType{id}...on XOpenCTICryptocurrencyWallet{id}...on XOpenCTICryptographicKey{id}...on XOpenCTIHostname{id}...on XOpenCTIText{id}...on XOpenCTIUserAgent{id}}}}",
   "size":270,
   "time":3229,
   "timestamp":"2022-03-07T19:59:49.244Z",
   "type":"READ_ERROR",
   "user":{
      "ip":"::ffff:10.0.3.100",
      "referer":"https://<DOMAIN>/dashboard?",
      "user_id":"bc212fc2-2339-458e-8a8f-471ad06c048c"
   },
   "variables":{
      "dateAttribute":"created_at",
      "endDate":null,
      "field":"internal_id",
      "limit":10,
      "operation":"count",
      "relationship_type":"stix-core-relationship",
      "startDate":"2021-12-07T00:00:00-05:00",
      "toTypes":[
         "Threat-Actor",
         "Intrusion-Set",
         "Campaign",
         "Malware",
         "Tool",
         "Vulnerability"
      ]
   },
   "version":"5.2.1"
}`

## Screenshots (optional)

![screenshot](https://user-images.githubusercontent.com/13635567/157116325-1971fc57-c51c-452b-8bf2-51ddefd20552.png)

**Comment by richard-julien** [comment]
Thanks for the bug report. Fixed will be available in the next release
