### ISSUE TITLE
Error when creating an external reference in events

### ISSUE THREAD

**Issue by fitz003** [LuatixHQ/opencti#1959]
## Description

When adding an external reference to an event, the OpenCTI platform is not able to make the request and errors out. The log says "you must be logged in to do this" but multiple users have tried to do this and users are still able to add external references manually by going into Analysis --> External References

## Environment

1. OS: Docker
2. OpenCTI version: OpenCTI 5.2.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on events
2. Open an event
3. Add an external reference
4. Click on '+' to create an external reference
5. Error appear

## Expected Output

Should be able to create an external reference from within an event

## Actual Output

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information

`{
   "category":"APP",
   "error":{
      "data":{
         "category":"technical",
         "http_status":401
      },
      "stacktrace":[
         "AuthRequired: You must be logged in to do this.",
         "at Q0 (/opt/opencti/build/src/config/errors.js:8:10)",
         "at Zee (/opt/opencti/build/src/config/errors.js:20:39)",
         "at i.resolve (/opt/opencti/build/src/graphql/authDirective.js:34:23)",
         "at t.resolve (/opt/opencti/build/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)",
         "at jsn (/opt/opencti/build/node_modules/graphql/execution/execute.js:479:20)",
         "at epe (/opt/opencti/build/node_modules/graphql/execution/execute.js:411:20)",
         "at u_r (/opt/opencti/build/node_modules/graphql/execution/execute.js:342:14)",
         "at Vsn (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)",
         "at k (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:497:20)",
         "at S7r (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:403:28)",
         "at runMicrotasks (<anonymous>)",
         "at processTicksAndRejections (node:internal/process/task_queues:96:5)",
         "at adn (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:346:24)"
      ]
   },
   "inner_relation_creation":0,
   "level":"warn",
   "message":"API Call",
   "operation":"StixCoreObjectExternalReferencesLinesQuery",
   "operation_query":"query StixCoreObjectExternalReferencesLinesQuery($count:Int!$id:String!){...StixCoreObjectExternalReferencesLines_data_44vElo}fragment FileLine_file on File{id name uploadStatus lastModified lastModifiedSinceMin metaData{mimetype list_filters messages{timestamp message}errors{timestamp message}}...FileWork_file}fragment FileWork_file on File{id works{id connector{name id}user{name id}received_time tracking{import_expected_number import_processed_number}messages{timestamp message}errors{timestamp message}status timestamp}}fragment StixCoreObjectExternalReferencesLines_data_44vElo on Query{stixCoreObject(id:$id){__typename id externalReferences(first:$count){edges{node{id source_name description url hash external_id jobs(first:100){id timestamp connector{id name}messages{timestamp message}errors{timestamp message}status}connectors(onlyAlive:false){id connector_type name active updated_at}importFiles(first:1000){edges{node{id lastModified ...FileLine_file metaData{mimetype}}}}__typename}cursor}pageInfo{endCursor hasNextPage}}}}",
   "size":57,
   "time":2,
   "timestamp":"2022-03-08T22:09:04.140Z",
   "type":"READ_ERROR",
   "version":"5.2.1"
}`

## Screenshots

![Screen Shot 2022-03-09 at 9 59 45 AM](https://user-images.githubusercontent.com/13635567/157467872-d9f2655d-80cf-426e-9ca7-0450fa112c07.png)

**Comment by richard-julien** [comment]
Reproduced on demo, thanks for the report
