### ISSUE TITLE
Error creating a report where confidence is changed from the default value

### ISSUE THREAD

**Issue by 00willo** [LuatixHQ/opencti#1960]
## Description

On attempting to create a new report, if the confidence is left as the default (low in my case) a report is added upon clicking Create, however if the confidence value is adjusted to anything it fails with the following appear in th UI:

`Variable "$input" got invalid value "85" at "input.confidence"; Int cannot represent non-interger value: "85"`

## Environment

1. OS: Docker
2. OpenCTI version: OpenCTI 15.2.1
3. OpenCTI client: frontend 
4. Other environment details:
  Built from docker-compose in https://github.com/OpenCTI-Platform/docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Analysis under Activities
2. On the Reports tab, click the plus icon in bottom right
3. Enter some text for the name and description
4. Click the confidence and change the value to anything other than what is the default low.
5. Click Create

## Expected Output

The modal closes and a report is successfully created visible in the list.

## Actual Output

The UI displays an error:
`Variable "$input" got invalid value "85" at "input.confidence"; Int cannot represent non-interger value: "85"`

If a different confidence value is chosen the integer value in the error reflects that as well.

Also on setting the confidence value back to low after it errors, it will then also error on that value and not create a report as well.

## Additional information

I should note, that this does not occur on updating an existing report to change it's confidence level.

**Comment by OpenSecureCo** [comment]
I also get the same error: 
![image](https://user-images.githubusercontent.com/74164997/157769558-f6364098-256a-4709-8db3-0ae062d4ab39.png)

I am also on 5.2.1
