### ISSUE TITLE
How to assign data access permissions by marking

### ISSUE THREAD

**Issue by xF4t3** [LuatixHQ/opencti#1984]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I have 5 different user groups. I created new markings (with different order numbers) similar to each group name. I assign permissions for each group with created marking. I noticed that users in groups that are marked with a higher marking order number will be able to see the data of the group that is marked with a lower marking order number.
I think OpenCTI marking is based on order number.
**How can I assign data access permissions to each group? Make sure a group will not be able to see the data of another group.**

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.2.2
3. OpenCTI client: { e.g. frontend or python }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create 5 groups
2. Create a user with a Default role in each group
3. Create markings corresponding with each group
4. Assign permissions for groups with defined marking (only one marking with the same group name)

**Comment by richard-julien** [comment]
I think you need to create a marking with a different marking type for each group. The priority order is used for marking inside the same type.

**Comment by xF4t3** [comment]
@richard-julien thank you for your support. I tried following your instructions and it worked.
