### ISSUE TITLE
OpenCTI frontend test suite

### ISSUE THREAD

**Issue by nor3th** [LuatixHQ/opencti#1989]
## Use case

New additions to the frontend should be tested using a test suite (like for the backend)

## Current Workaround

No testing or testing in the backend + manually coping code to the frontend after the test runs.

## Proposed Solution

jest?

## Additional Information

We would be really happy if this addition could come from the community, as we are currently struggling in finding time for this feature.
:relaxed: :relaxed:

**Comment by richard-julien** [comment]
We change the testing framework, now we still need to improve the test base

**Comment by jpkha** [comment]
We add playwright for the e2e testing : https://github.com/OpenCTI-Platform/opencti/pull/5555
