### ISSUE TITLE
Exporting Report details, Malware or Intrusion Sets is hard to do

### ISSUE THREAD

**Issue by tanyawang1218** [LuatixHQ/opencti#1991]
## Use case

Exporting Report details, Malware or Intrusion Sets is hard to do. For example if you want a simple list of TTP associated to an Intrusion Set: - Data Tab -> Exported Files -> Click the little Blue File Icon with the Arrow - JSON /CSV option - But ... Now I look at the JSON , we are only getting the relationship ID for the TTP, not the content ☹.
Is there some easier way to Export content from Entities in an easy to digest format ?

## Current Workaround

No workaround.

## Proposed Solution

Not only show the Relationship ID, but also the content in the exported file.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Exporting button in Threat => Knowledge => Attack Patterns is missing (only images). I will implement it asap.
