### ISSUE TITLE
Ability to export only selected observables

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#1996]
## Use case

From the observables page, it would be helpful to export only selected objects. Currently, when multiple observables are selected, every observable is exported, regardless of what is selected

## Current Workaround

n/a

## Proposed Solution

When clicking "Export", only selected observables should be exported. If none are selected, then all observables should be exported (accounting for filters)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by securitiz** [comment]
When exporting selected observables, the export appears to hang. Creating a bug issue for this. 

![image](https://user-images.githubusercontent.com/78382789/174649014-1881f7ea-f74b-4660-8fba-f661f314c58e.png)

**Comment by SamuelHassine** [comment]
Duplicate #1741.
