### ISSUE TITLE
Knowledge tab bypass all capabilities permissions unknown error

### ISSUE THREAD

**Issue by louisgls** [LuatixHQ/opencti#2006]
## Environment

1. OS (where OpenCTI server runs): Debian 10
2. OpenCTI version: 5.2.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a role without "bypass all capabilities permissions" (check screenshot below)
2. Affect this role to an user
3. Log in with this user
4. Go to knowledge (left menu) > threats > campaigns > click on any campaign > knowledge tab

## Expected Output

The knowledge view is displayed.

## Actual Output

We can sometimes see the knowledge view for a quick seconds then this message appears :

![image](https://user-images.githubusercontent.com/11679637/161248786-63430c25-9eaf-4a46-a950-bb40e003c93a.png)

## Additional information

- We have the exact same issue when go to knowledge (left menu) > threats > intrusion sets > click on any intrusion set > knowledge tab
- When we use add the "bypass all capabilities" permission to the role, we have no issues at all
- We have no issue when go to knowledge (left menu) > threats > threat actors > click on any threat actor > knowledge tab
- A part from "knowledge" other tabs look OK for campaigns and intrusion sets
- Nothing special has been seen in the logs...

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/11679637/161263882-9020a3dc-740d-4465-bb82-8f6d66c2633e.png)

**Comment by Tonnulus** [comment]
Same issue with OpenCTI 5.3.1

**Comment by SamuelHassine** [comment]
Hello @Tonnulus,

Can you please provide me with the error log of your browser console when the error occured please?

Kind regards,
Samuel

**Comment by Tonnulus** [comment]
The problem doesn't recur. My bad.
