### ISSUE TITLE
Be able to extract a first scope of observables from created indicators

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2010]
Be able to extract a first scope of observables from created indicators

**Comment by SYNchroACK** [comment]
@SamuelHassine from this [line](https://github.com/OpenCTI-Platform/opencti/blob/8b460dfe2e20b98bd87e0068a12198c8ef8df46e/opencti-platform/opencti-graphql/src/domain/indicator.js#L192), it seems that is does not create observable(s) from the indicator in case of that indicator is associated, for example, to a malware entity, right? Is that the correct behavior?

In my scenario, I imported this [STIX bundle](https://gist.github.com/rjsmitre/79775df68b0d1c7c0985b4fe7f115586) and I can't see any observables being created from the indicators.

**Comment by SamuelHassine** [comment]
Hello @SYNchroACK,

No, it's just checking that `createObservables` is `true`. For your bundle, you should add `x_opencti_create_observables: true` in the indicators you would like to have also as observables.

Kind regards,
Samuel

**Comment by SYNchroACK** [comment]
@SamuelHassine Ok, fair enough. Should the `x_opencti_create_observables` feature be available as a button in data import panel? Or at least, is that option documented somewhere? How can a normal user can know about it?

**Comment by SamuelHassine** [comment]
Hello @SYNchroACK,

This option is proposed in the configuration of some connectors which are known to not generating observables when sending indicators to the platform. This option is not available yet in the Import STIX connector because you're right, it should not be a global config of the connector but an option you may select in the data import process of the UI.

It's something we are working on (as well as x_opencti_create_indicator=true/false in observables,  reversed option which has a broader usage).
