### ISSUE TITLE
Allow the ability to change the entity type of any entity that gets ingested from the prevalidation screen. 

### ISSUE THREAD

**Issue by kudrew** [LuatixHQ/opencti#2015]
## Use case

Some sources define entities as of one type (intrusion sets vs threat actors) and this leads to potential duplication of entities in the platform. We would like the option in the prevalidation screen to change the entity type for every entity not just observables. 

This FR is dependent on this FR: https://github.com/OpenCTI-Platform/opencti/issues/2014 

https://demo.opencti.io/dashboard/import/pending/aW1wb3J0L3BlbmRpbmcvY3Jvd2RzdHJpa2UgcmVwb3J0LnBkZi5qc29u

If the user changes the entity's type in the prevalidation menu, have the platform do a check to make sure the entity with its new type does not already exist. If it does, use the stix id that already exists on the platform. If not, generate a new id.

**Comment by SamuelHassine** [comment]
For the moment, the entity type is linked to existing data in the platform, except for observable. There is no possible mismatch.

Feature #2014 has been implemented.
