### ISSUE TITLE
no update event in Events streaming 

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#2020]
## Description

I created a data stream (Data Sharing) with the following filters `Marking definition: TLP:WHITE OR TLP:GREEN
AND
Revoked: No
AND
Entity type: Indicator`

When I update an indicator with the web interface (adding a description for exemple), I see in my stream `event: create` instead of `event: update` 

## Environment

1. OS debian 
2. OpenCTI version: 5.2.3
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Stream (Data Sharing)
2. Update one indicator (Change the description)
3. Check you stream. You will find `event: create` and not `event: update`

## Expected Output

When a object is update with the OpenCTI web interface, I expect a `event: update` in the stream.

## Actual Output

I found only `event: create`  and `event: delete` but never  `event: update` in the stream.

**Comment by richard-julien** [comment]
Hi @Tonnulus, this is an expected behavior.
In live stream every update will republish the entire object as a creation event.

**Comment by Tonnulus** [comment]
Okay thank you
