### ISSUE TITLE
How to change logo on login screen and dashboard. 

### ISSUE THREAD

**Issue by A-Wild-Ston3** [LuatixHQ/opencti#2027]
I've added URLs for logos, but all that happens is that the logo changes from the OpenCTI logo to "logo" (in plaintext)

**Comment by nor3th** [comment]
Is OpenCTI able to fetch the logo from the given URL (from a network perspective)?

Works for me:
![img](https://user-images.githubusercontent.com/73965465/163464829-52a7ceb5-cea0-4c49-a18f-50daccf8af14.png)

**Comment by A-Wild-Ston3** [comment]
Yes, I managed to fix by hosting the images locally in /vat/www/html/ and pointing the URL to there. It doesn't work for image hosting sites (such as Imgur) though.

Thanks
________________________________

**Comment by nor3th** [comment]
Hey

Then it is most likely due to some user agent filtering on Imgur's side (probably to make scraping a bit more difficult).

Regards
