### ISSUE TITLE
Improve Graph Visualization

### ISSUE THREAD

**Issue by bachvu-michael** [LuatixHQ/opencti#2040]
## Use case

- upgrade Graph Visualization: node selection, lookup node, highlight, auto layout...
- Graph Analysis: find the shortest path between 2 node...

## Current Workaround

Now is hardly to visualization graph by react-force-graph. What do you think about keylines lib. https://cambridge-intelligence.com

## Proposed Solution

https://cambridge-intelligence.com

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nor3th** [comment]
Hey @bachvu-michael 

Thanks for the suggestion. The cambridge-intelligence libraries look very interesting indeed, but it seems to me that they are only available for commercial purchase and thereby it won't be possible to integrate them into the platform for the entire opencti community to use.

Regards

**Comment by SamuelHassine** [comment]
We know we have a lot of remaining efforts to make our graphs better. But we need to stay on open source libraries / 3d parties. Please re-open an issue if you have another suggestion of a better library.

Thanks for your contribution!
