### ISSUE TITLE
Report Context Rich Text Editor

### ISSUE THREAD

**Issue by r0sier** [LuatixHQ/opencti#2063]
## Use case

In previous versions, OpenCTI allowed us to use a rich text editor to produce a HTML file which we used as the main context behind our reports. It seems in the latest updates that this functionality has been removed which means we are stuck on old versions of OpenCTI and cannot update as we depend on the rich text editor. 

## Current Workaround
Run the platform from v5.1.4

## Proposed Solution
Activate the rich text editor. 

## Additional Information
I know the OCTI team are aware of the issues with the previous text editor, but some things I found which may help:
- Issues around multiple users editing the rich text editor at the same time means that changes are not always saved
- UI issues with the text editor (IE cannot see image captions)

I've created this issue just so I can understand when this functionality will be reintroduced, and at what release.

**Comment by securitiz** [comment]
@SamuelHassine does this apply only to Entities/SDOs or Observables/hashes as well?
