### ISSUE TITLE
Sample configuration for HTTPS/SSL

### ISSUE THREAD

**Issue by lnfernux** [LuatixHQ/opencti#2068]
Hey, referencing a post I made to another issue about support for HTTPS in OpenCTI.
I've looked at the configuration guide and tried to get it to work;

## Original post

Tried changing `app.port` to `443` and added the `https_certs` node with `key`, `crt` and `reject_unauthorized` filled out (two first pointing to key + signed cert). Then updated worker url (`/worker/config.yml`) to `http://localhost:443`. 

This didn't work, so tried changing the worker url around (https, added domain A record and pointed to https://example.com, https://example.com:443). Also tried changing the port in the configuration file back to 8080 or 4000, and played around with a bunch of settings.

Setting the app.port to 8080 and the worker url to https://example.com with the app.base_url to "https://example.com" actually redirects you to a https site, but it just doesn't forward you to the correct destination.

## Question

Any chance for an example config or guide to set up working https/ssl setup?

_Originally posted by @infernuxmonster in https://github.com/OpenCTI-Platform/opencti/issues/550#issuecomment-1122340786_

**Comment by EmSi14** [comment]
@infernuxmonster did you get working setup or guide or did you work it out yourself?

**Comment by lnfernux** [comment]
> @infernuxmonster did you get working setup or guide or did you work it out yourself?

Hey - figured out our issue.

The terraform code that is linked to in the configuration documentation has an old version of OpenCTI without TLS integrated. Upgrading it solved it for me. If you have any issues with 5.0.0 I'd be happy to help.

**Comment by gritty-Kitty** [comment]
Need to implement the same, but cannot find any direct references on how to natively update Docker-Compose.yml to get SSL working from within default OpenCTI implementation. Any guidance is appreciated.
