### ISSUE TITLE
Incompatible versions 5.2.4 and 5.2.5 while explicit 5.2.4 is used

### ISSUE THREAD

**Issue by ogomozov-godaddy** [LuatixHQ/opencti#2071]
## Description

Hi,

My platform docker instance returns following error
> Your platform data (5.2.4) are too old to start on version 5.2.5

It comes from opengraph ql code
But thing is I explicitly use 5.2.4 code only, no mention of 5.2.5 anywhere. I use 5.2.4 cause 5.2.5(or latest right now) use node 18, and we do not support node 18, but only node 16 yet. See screenshots

Here is the script:

git clone -b 5.2.4 https://github.com/OpenCTI-Platform/opencti.git
cd opencti/opencti-platform
docker build -t platform -f Dockerfile .

## Environment

1. OS : docker alpine (node:16.6.0-alpine3.14)
2. OpenCTI version: 5.2.4
3. OpenCTI client: frontend
4. Other environment details:

## Additional information

![image](https://user-images.githubusercontent.com/74936027/167915401-a25e0886-aabc-49bb-837a-f5c84dfe4550.png)
![image](https://user-images.githubusercontent.com/74936027/167915454-6354d657-fd01-4859-836c-f2da892fdac6.png)
![image](https://user-images.githubusercontent.com/74936027/167915508-6aadd008-b0e7-4f0c-abd3-f4b14a94ccac.png)

**Comment by ogomozov-godaddy** [comment]
after checking source code it seems like OpenCTI makes query to find if Elastic contains existing migration records. I see it in format of GraphQL, but couldn't confirm with Kibana query if such records exist. Kibana returns 0 records with "MigrationStatus" . But seems like server may respond with something that indicates existing migration happened to latest 5.2.5 sometime in past. Can you help identify those records that are returned and cause to throw this error? I want to try to change records, so it will not cause it. I know it was for reason, but I wanna test if just this change can allow platform to run, and my few records are ok to run on 5.2.4. My data is not so much important , it's not production one

`{
  "category": "APP",
  "level": "debug",
  "message": "[SEARCH ENGINE] paginate",
  "query": {
    "body": {
      "query": {
        "bool": {
          "must": [
            {
              "bool": {
                "minimum_should_match": 1,
                "should": [
                  {
                    "match_phrase": { "entity_type.keyword": "MigrationStatus" }
                  },
                  {
                    "match_phrase": {
                      "parent_types.keyword": "MigrationStatus"
                    }
                  }
                ]
              }
            }
          ],
          "must_not": []
        }
      },
      "size": 200,
      "sort": [{ "standard_id.keyword": "asc" }]
    },
    "ignore_throttled": false,
    "index": [
      "opencti_internal_objects*",
      "opencti_stix_meta_objects*",
      "opencti_stix_domain_objects*",
      "opencti_stix_cyber_observables*",
      "opencti_inferred_entities*"
    ],
    "track_total_hits": true
  },
  "timestamp": "2022-05-11T17:45:17.314Z",
  "version": "5.2.4"
}
`

**Comment by SamuelHassine** [comment]
As you've started in the master branch, version number has been migrated. So please continue to use master until the next stable release, or wait the next 5.3.0.

Sorry for that!

**Comment by ogomozov-godaddy** [comment]
yes, thanks
I wish we could proceed with master, but master is based of Node 18, which is yet new and our security concerns don't allow to use it before thorough hardening and audit, which will take time
