### ISSUE TITLE
Docker build fails for Platform service in latest master (5.2.5? ). Yarn Install

### ISSUE THREAD

**Issue by ogomozov-godaddy** [LuatixHQ/opencti#2075]
## Description

Docker build fails for Platform service in latest master (5.2.5? ) (not related to other error reported before)

## Environment

1. OS : Mac OS 11.16.1. and Ubuntu 20.4
2. OpenCTI version: master, 5.2.5
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  git clone -b master https://github.com/OpenCTI-Platform/opencti.git
2. cd opencti/opencti-platform/
3. docker build -f Dockerfile .
4. Error during docker build

## Expected Output

Docker builds successfully

## Actual Output

123.0 ➤ YN0000: └ Completed in 1m 58s
26 123.2 ➤ YN0000: ┌ Link step
26 174.3 ➤ YN0007: │ esbuild@npm:0.14.38 must be built because it never has been before or the last one failed
26 174.3 ➤ YN0007: │ core-js@npm:3.22.5 must be built because it never has been before or the last one failed
26 174.3 ➤ YN0007: │ node-sass@npm:7.0.1 must be built because it never has been before or the last one failed
26 174.3 ➤ YN0007: │ core-js-pure@npm:3.22.5 must be built because it never has been before or the last one failed
26 174.3 ➤ YN0007: │ es5-ext@npm:0.10.61 must be built because it never has been before or the last one failed
26 177.5 ➤ YN0009: │ node-sass@npm:7.0.1 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-7715a69c/build.log)
26 177.5 ➤ YN0000: └ Completed in 54s 274ms
26 177.7 ➤ YN0000: Failed with errors in 2m 54s
executor failed running [/bin/sh -c yarn install]: exit code: 1

## Additional information

Detected on two OS (MacOS and Ubuntu)

## Screenshots (optional)

Actual error:
![image](https://user-images.githubusercontent.com/74936027/168151439-dc9389a7-f4df-4d62-bdb9-6946e73b7c2d.png)

Start of docker build:

![image](https://user-images.githubusercontent.com/74936027/168151618-78437557-28f7-4cda-8b03-4d2b988f7e49.png)

**Comment by ogomozov-godaddy** [comment]
so further investigation:
1) node-sass fails to build as part of front project. It depends on node-gyp, which requires pyhon and gcc. While  opencti-platform/Dockerfile has RUN to install them due to multiple FROM commands making installs in parallel it appears python and gcc are not installed before front project runs yarn install, so race condition. Moving below command to the top fixes issue
```
RUN set -ex \
    ; apk add --no-cache git tini gcc musl-dev python3 python3-dev postfix postfix-pcre \
    && python3 -m ensurepip \
    && rm -rv /usr/lib/python*/ensurepip \
    && pip3 install --no-cache-dir --upgrade pip setuptools wheel \
    && ln -sf python3 /usr/bin/python
```

Other issue not easy to fix without thorough testing of front

2) react-leaflet 4.x depends on react 18 (as peer), while react 17 is still enforced to install, so requirement is not met and react-leaflet fails to install

**Comment by richard-julien** [comment]
Hi @ogomozov-godaddy , looks like you try the master when we have done some test around node18. We revert this change since. Can you retry when the latest code base?

**Comment by SamuelHassine** [comment]
Yes I confirm that our rollback should solve the problem of local build.

**Comment by ogomozov-godaddy** [comment]
yes, current Node 16 version works well
