### ISSUE TITLE
Show no dat found if there is no result in global search

### ISSUE THREAD

**Issue by tanyawang1218** [LuatixHQ/opencti#2081]
## Use case

When trying to search for something and there is no result, there should be at least a notice. 

## Current Workaround

N/A. It just show nothing now.

## Proposed Solution

Show no dat found if there is no result in global search

## Additional Information
N/A

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

It displays:

![image](https://user-images.githubusercontent.com/1334279/168533086-976eaf84-24e9-40f8-808a-725dcae37e67.png)

"No entities were found for this search.".

What do you mean in this ticket?

**Comment by tanyawang1218** [comment]
It works now, thank you.
