### ISSUE TITLE
Update Docker Deployment Documentation/Compose File to Include Exposing RabbitMQ Ports

### ISSUE THREAD

**Issue by skrumzy** [LuatixHQ/opencti#2085]
I'm new to OpenCTI and Docker.  As I'm teaching myself both, I discovered that the docker compose file for the production rollout is missing the ports to expose RabbitMQ.  I couldn't get connectors to work until I did expose 5672 and 15672.  Correct me if I'm wrong please.

**Comment by SamuelHassine** [comment]
Hello,

In a Docker Compose deployment, the dependencies ports doin't need to be exposed in the Docker host, as components are interacting with each others on the private network. You need to expose 15672 or 5672 only if you need to access them from outside of the docker compose stack.

Kind regards,
Samuel

**Comment by skrumzy** [comment]
@SamuelHassine, thank you so much for explaining that to me.  Again, teaching myself both at the same time.  I think where my issue was, with your explaination, my connectors weren't on the same vlan as my opencti stack.
