### ISSUE TITLE
URL Shareable public dashboards

### ISSUE THREAD

**Issue by mwatermolen** [LuatixHQ/opencti#2101]
## Use case
Make dashboards shareable at a url like `/dashboards/public/<UUID/long string>`. This allows for embeding / iframeing dashboards for display software or other iframe cases.

We want to embed dashboards in [piSignage](https://github.com/colloqi/piSignage) for our SOC

## Current Workaround

None ATM, we have to use a separate VM to stream the screen of a logged-in browser

## Proposed Solution

Make dashboards shareable at a url like `/dashboards/public/<UUID/long string>`. 

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

YES

**Comment by richard-julien** [comment]
In this case i imagine you want an iFrame with only the dasbhoard in ready only mode without any left bar/top menu etc right?

**Comment by mwatermolen** [comment]
Yep! Thats what I was thinking @richard-julien
