### ISSUE TITLE
Access exploration permission in roles

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2107]
## Description

![image](https://user-images.githubusercontent.com/4184292/170186961-4d0fb589-fdfe-468d-98dd-aa0e0307908a.png)

First time I saw this "Exploration" term after some days testing opencti. It is not clear to me what it means but if I can guess, it means Activities Panel permissions. I think it needs a better term in order to be clear. My suggestion is to use the current panel name "Activities".

**Comment by SYNchroACK** [comment]
After some test, I got confused... what is "Access Knowledge" and what is "Access Exploration"?

![image](https://user-images.githubusercontent.com/4184292/170190719-92689058-37d4-40af-96a4-9d2095d6f950.png)

**Comment by richard-julien** [comment]
Knowledge is all Stix data in the platform (Activities / Knowledge).
Exploration represents the custom dashboard (top right menu). Agree that could be a bit confusing :)
