### ISSUE TITLE
Add missing relation kill chains in Stix 2.1 format

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#2117]
## Description

Kill chains are available in relation but its not part of the STIX specification.
We need to add kill_chain_phases in OCTI relation extensions.

```
"extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "property-extension",
        ...
        "kill_chain_phases": [
          {
            "kill_chain_name": "mitre-attack",
            "phase_name": "command-and-control"
          },
          {
            "kill_chain_name": "mitre-attack",
            "phase_name": "privilege-escalation"
          }
        ]
      }
    },
```

Then ensure that kill chains are correctly backup/restore and synchronized

**Comment by SamuelHassine** [comment]
Done for Python client: https://github.com/OpenCTI-Platform/client-python/commit/418238c5742632376e34bee04855435c1d3ecf0a.
