### ISSUE TITLE
[FEATURE] Allow removing quotes on the HTTP Feed

### ISSUE THREAD

**Issue by mwatermolen** [LuatixHQ/opencti#2118]
## Use case

For adding the HTTP feed to Fortigates we cant have quotes surrounding the IOCs

## Current Workaround

None at this time

## Proposed Solution

Add a checkbox to disable quoting

## Additional Information

![image](https://user-images.githubusercontent.com/73605619/170783098-345fc44f-c5c5-4b66-af9d-022567a380c6.png)

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
@richard-julien: allow custom separator or "no separator" (empty field).

**Comment by richard-julien** [comment]
Following the norm, now the data will not be quoted if its not needed.
So basically data will be quoted only if data contains the separator or a double quote.
Examples (with comma as separator):
- 192.168.0.1 =>192.168.0.1
- TEST_NAME => TEST_NAME
- My"Name => "My""Name"
- a,b,c,d => "a,b,c,d"
