### ISSUE TITLE
`Manage credentials` capability equals to `Bypass all capabilities`

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2122]
## Description

A user with a role that only has `Manage credentials` capability can:
1. login
2. access to `Settings > Accesses`
3. add `Bypass all capabilities` to any role.
 
In practice, `Manage credentials` capability is equal to full admin.

## Environment

OpenCTI version: 5.3.1

**Comment by richard-julien** [comment]
Yes, if a user can manage access he can grant capabilities and so the bypass that is a practical capability in a lot of circumstances. We have no plan to change that.
