### ISSUE TITLE
Is full text search possible?

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2123]
## Question

It seems that the current elasticsearch mapping has `observable_value` as `keyword` which (if I'm correct) limits the possibility to find on a search like `*ple.com*` the following domain `example.com`. Assuming that I'm correct on my analysis (based on [this link](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/keyword.html)), what was the reason to pick `keyword`? Is it possible to still find the domain using a search like the one I mentioned?

## Environment

2. OpenCTI version: 5.3.1
3. OpenCTI client: frontend

**Comment by richard-julien** [comment]
Hi @SYNchroACK ,

observable_value doesn't really exists in the database, is a dynamic field that represents the most valuable information of each observable type.  I dont really know where you find that in the elastic mapping.

Now for your search, starting wilcard is extremely expensive so we decide to not support it. End wildcard are automatically added in your search.

So example.com could be finded when you search for
- example
- example.c
- example.co
- example.com

**Comment by SYNchroACK** [comment]
@richard-julien 

> observable_value doesn't really exists in the database, is a dynamic field that represents the most valuable information of each observable type. I dont really know where you find that in the elastic mapping.

Misunderstood the code.

> Now for your search, starting wilcard is extremely expensive so we decide to not support it. End wildcard are automatically added in your search.

Fair enough. ;)
