### ISSUE TITLE
Can't upgrade from 5.2.4 to 5.3.1

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#2126]
## Description

The migration is impossible from 5.2.4 to 5.3.1

## Environment

1. OS (where OpenCTI server runs): Mac OS 12.4
2. OpenCTI version: OpenCTI 5.2.4 -> OpenCTI 5.3.1
3. OpenCTI client: frontend
4. Other environment details: Firefox

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. tar xvfz OpenCTI-release-5.3.1.tar.gz
2. pip3 install -r src/python/requirements.txt
3. yarn serv

## Actual Output

Cf. attachment

## Screenshots (optional)

`{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-05-31T05:29:29.806Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2022-05-31T05:29:29.809Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[SEARCH ENGINE] Elasticsearch (7.17.0) client selected / runtime sorting enabled","timestamp":"2022-05-31T05:29:29.966Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2022-05-31T05:29:29.966Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2022-05-31T05:29:29.976Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2022-05-31T05:29:29.991Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2022-05-31T05:29:29.998Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2022-05-31T05:29:30.357Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Pubsub subscriber' client ready","timestamp":"2022-05-31T05:29:30.450Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager initialized","timestamp":"2022-05-31T05:29:30.452Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2022-05-31T05:29:30.457Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2022-05-31T05:29:30.460Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2022-05-31T05:29:30.472Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2022-05-31T05:29:30.679Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 107 migrations from the database","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] 5 migrations will be executed","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1650287551439-remove_sector_locations.js","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Cleaning located-at relationships between Sectors and Locations","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Cleaning located-at relationships between Sectors and Locations done in 5 ms","timestamp":"2022-05-31T05:29:30.757Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1650287551439-remove_sector_locations.js","timestamp":"2022-05-31T05:29:30.959Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Starting 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:30.959Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] 1651939301056-workflow_rename.js finished","timestamp":"2022-05-31T05:29:31.044Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Starting 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Cryptographic-Key","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Cryptocurrency-Wallet","timestamp":"2022-05-31T05:29:31.311Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Hostname","timestamp":"2022-05-31T05:29:31.314Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Text","timestamp":"2022-05-31T05:29:31.317Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-User-Agent","timestamp":"2022-05-31T05:29:31.319Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] 1652114181368-entities_rename.js finished","timestamp":"2022-05-31T05:29:31.322Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:31.503Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[MIGRATION] Starting 1652125339035-files_database.js","timestamp":"2022-05-31T05:29:31.504Z","version":"5.3.1"}
{"category":"APP","level":"error","message":"[MIGRATION] Error during migration","timestamp":"2022-05-31T05:29:31.549Z","version":"5.3.1"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2022-05-31T05:29:31.554Z","version":"5.3.1"}
{"_error":{},"_showLocations":false,"_showPath":false,"category":"APP","data":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","filename":"export/.DS_Store","http_status":500,"reason":"File not found","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},"internalData":{},"name":"DatabaseError","time_thrown":"2022-05-31T05:29:31.549Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"internalData":{},"level":"error","message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2022-05-31T05:29:31.550Z","timestamp":"2022-05-31T05:29:31.554Z","version":"5.3.1"}`

**Comment by JeromeSRT** [comment]
> ## Description
> 
> The migration is impossible from 5.2.4 to 5.3.1
> 
> ## Environment
> 
> 1. OS (where OpenCTI server runs): Mac OS 12.4
> 2. OpenCTI version: OpenCTI 5.2.4 -> OpenCTI 5.3.1
> 3. OpenCTI client: frontend
> 4. Other environment details: Firefox
> 
> ## Reproducible Steps
> 
> Steps to create the smallest reproducible scenario:
> 1. tar xvfz OpenCTI-release-5.3.1.tar.gz
> 2. pip3 install -r src/python/requirements.txt
> 3. yarn serv
> 
> ## Expected Output
> 
> ## Actual Output
> 
> Cf. attachment
> 
> ## Additional information
> 
> 
> 
> ## Screenshots (optional)
> 
> `{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-05-31T05:29:29.806Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2022-05-31T05:29:29.809Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[SEARCH ENGINE] Elasticsearch (7.17.0) client selected / runtime sorting enabled","timestamp":"2022-05-31T05:29:29.966Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2022-05-31T05:29:29.966Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2022-05-31T05:29:29.976Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2022-05-31T05:29:29.991Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2022-05-31T05:29:29.998Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2022-05-31T05:29:30.357Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[REDIS] Redis 'Pubsub subscriber' client ready","timestamp":"2022-05-31T05:29:30.450Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager initialized","timestamp":"2022-05-31T05:29:30.452Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[REDIS] Redis 'Client context' client ready","timestamp":"2022-05-31T05:29:30.457Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2022-05-31T05:29:30.460Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2022-05-31T05:29:30.472Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2022-05-31T05:29:30.679Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Read 107 migrations from the database","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] 5 migrations will be executed","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1650287551439-remove_sector_locations.js","timestamp":"2022-05-31T05:29:30.751Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Replaying migration 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Cleaning located-at relationships between Sectors and Locations","timestamp":"2022-05-31T05:29:30.752Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Cleaning located-at relationships between Sectors and Locations done in 5 ms","timestamp":"2022-05-31T05:29:30.757Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1650287551439-remove_sector_locations.js","timestamp":"2022-05-31T05:29:30.959Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Starting 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:30.959Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] 1651939301056-workflow_rename.js finished","timestamp":"2022-05-31T05:29:31.044Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1651939301056-workflow_rename.js","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Starting 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Cryptographic-Key","timestamp":"2022-05-31T05:29:31.308Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Cryptocurrency-Wallet","timestamp":"2022-05-31T05:29:31.311Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Hostname","timestamp":"2022-05-31T05:29:31.314Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-Text","timestamp":"2022-05-31T05:29:31.317Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Renaming entity X-OpenCTI-User-Agent","timestamp":"2022-05-31T05:29:31.319Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] 1652114181368-entities_rename.js finished","timestamp":"2022-05-31T05:29:31.322Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Saving current configuration, 1652114181368-entities_rename.js","timestamp":"2022-05-31T05:29:31.503Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[MIGRATION] Starting 1652125339035-files_database.js","timestamp":"2022-05-31T05:29:31.504Z","version":"5.3.1"}
> {"category":"APP","level":"error","message":"[MIGRATION] Error during migration","timestamp":"2022-05-31T05:29:31.549Z","version":"5.3.1"}
> {"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2022-05-31T05:29:31.554Z","version":"5.3.1"}
> {"_error":{},"_showLocations":false,"_showPath":false,"category":"APP","data":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","filename":"export/.DS_Store","http_status":500,"reason":"File not found","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},"internalData":{},"name":"DatabaseError","time_thrown":"2022-05-31T05:29:31.549Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"internalData":{},"level":"error","message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2022-05-31T05:29:31.550Z","timestamp":"2022-05-31T05:29:31.554Z","version":"5.3.1"}`

**Comment by richard-julien** [comment]
Hi @JeromeSRT, the error is not directly related to the migration and can occurs directly in the user interface.

Any chance for you to delete directly this file (export/.DS_Store) in minio console? 
And do you know how it could be possible to have a file .DS_Store stored in minio?

Thanks

**Comment by richard-julien** [comment]
After some digin looks like a specific MAC problem. Will look into filtering the famous .DS_Store file

**Comment by JeromeSRT** [comment]
> After some digin looks like a specific MAC problem. Will look into filtering the famous .DS_Store file

Hi @richard-julien sorry for this late answer, thank you for your advices I could update my OpenCTI from 5.2.4 to 5.3.1.
