### ISSUE TITLE
Analysis ownership or accountability 

### ISSUE THREAD

**Issue by AAA10CR7** [LuatixHQ/opencti#2138]
## Use case

Imagine we are a team working on analyzing different intelligence reports. We need to know who is working on which report.

There is a field for status, author and creator, but it would help to add the current owner of the analysis. This will help actively collaboration and saving each member efforts

## Current Workaround

Writing in the comments who is handle each analysis/case

## Proposed Solution

Adding a field showing who is the owner of each report.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Linked to #243

**Comment by SamuelHassine** [comment]
Solution: add "assignment/owner" field to all SDOs as: `assignee_refs` to the entity type users in the platform.
