### ISSUE TITLE
GraphQL Issue when visualising Connectors in data section

### ISSUE THREAD

**Issue by ReadyElbow** [LuatixHQ/opencti#2146]
## Description

When looking to understand the current state of connectors that are live and running, the Platform displays the message:

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

When digging a bit deeper, the console states:
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

The Network Request and Response are detailed below but it appears that the query being run against GraphQL fails.

## Environment

1. OS (where OpenCTI server runs): AMD64 AWS Fargate (docker)
2. OpenCTI version: 5.3.2
3. OpenCTI client: Frontend
4. Other environment details: 

## Reproducible Steps

Access the connector dashboard in the Data section. Error is thrown 

## Expected Output

For a list of registered connectors to be shown.

## Actual Output

Error is raised and details below highlight the request and response issues.

#### Request 1
POST /graphql HTTP/1.1
Accept: */*
Content-Type: application/json

HTTP/1.1 200 OK
ETag: W/"c88-ELhyY6ANMQ6SluFuwPxDlABBgSE"
Content-Type: application/json; charset=utf-8
Set-Cookie: opencti_session=s%3<>Y_xMLW.WKL<>o0gUE5u<>BPROaG<>Bk; Path=/; Expires=Thu, 09 Jun 2022 10:56:54 GMT; HttpOnly; SameSite=Lax
Access-Control-Allow-Origin: *
Date: Thu, 09 Jun 2022 10:36:54 GMT
Content-Length: 3208
Connection: keep-alive
X-Powered-By: Express

#### Request 2
POST /graphql HTTP/1.1
Accept: */*
Content-Type: application/json
Payload:
{"id":"ConnectorsStatusQuery","query":"query ConnectorsStatusQuery {\n  ...ConnectorsStatus_data\n}\n\nfragment ConnectorsStatus_data on Query {\n  connectors {\n    id\n    name\n    active\n    auto\n    connector_type\n    connector_scope\n    updated_at\n    config {\n      listen\n      listen_exchange\n      push\n      push_exchange\n    }\n  }\n  rabbitMQMetrics {\n    queues {\n      name\n      messages\n      messages_ready\n      messages_unacknowledged\n      consumers\n      idle_since\n      message_stats {\n        ack\n        ack_details {\n          rate\n        }\n      }\n    }\n  }\n}\n","variables":{}}

Response:
HTTP/1.1 500 Internal Server Error
{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'split')",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}

**Comment by richard-julien** [comment]
Hi @ReadyElbow , can you write the complete error log of the API ? Thanks

**Comment by ReadyElbow** [comment]
Hi @richard-julien , when you say the complete error log of the API, where would I find this information? 
Are you asking me to recreate the request the platform performs by myself in the /graphql 'test' section.

**Comment by ReadyElbow** [comment]
@richard-julien Web Console logs:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (graphql, line 0)
[Error] Error — opencti-NGCH3KCA.js:313320:108219
	y7n (opencti-NGCH3KCA.js:7:100491)
	(anonymous function) (opencti-NGCH3KCA.js:7:101054)
	set (opencti-NGCH3KCA.js:5:63904)
	bEa (opencti-NGCH3KCA.js:7:102301)
	CEa (opencti-NGCH3KCA.js:9:119151)
	CEa
	(anonymous function) (opencti-NGCH3KCA.js:1:12872)
	fQ (opencti-NGCH3KCA.js:9:115846)
	F7n (opencti-NGCH3KCA.js:7:111732)
	F7n
	(anonymous function) (opencti-NGCH3KCA.js:5:60365)
	(anonymous function) (opencti-NGCH3KCA.js:1:12872)
	Mnt (opencti-NGCH3KCA.js:5:60312)
	DP (opencti-NGCH3KCA.js:5:60244)
	rz (opencti-NGCH3KCA.js:7:109009)
	enqueueSetState (opencti-NGCH3KCA.js:5:64274)
	(anonymous function) (opencti-NGCH3KCA.js:1:3923)
	(anonymous function) (opencti-NGCH3KCA.js:41:399903)
	(anonymous function) (opencti-NGCH3KCA.js:41:389667)
	forEach
	error (opencti-NGCH3KCA.js:41:389653)
	error (opencti-NGCH3KCA.js:11:168584)
	error (opencti-NGCH3KCA.js:11:168584)
	(anonymous function) (opencti-NGCH3KCA.js:11:166145)
	error (opencti-NGCH3KCA.js:11:168584)
	error (opencti-NGCH3KCA.js:11:168584)
	error (opencti-NGCH3KCA.js:11:168584)
	forEach
	(anonymous function) (opencti-NGCH3KCA.js:11:172169)
	error (opencti-NGCH3KCA.js:11:173306)
	error (opencti-NGCH3KCA.js:11:168584)
	error (opencti-NGCH3KCA.js:11:168584)
	(anonymous function) (opencti-NGCH3KCA.js:11:206434)
	error (opencti-NGCH3KCA.js:11:168584)
	(anonymous function) (opencti-NGCH3KCA.js:11:166145)
	error (opencti-NGCH3KCA.js:11:168584)
	(anonymous function) (opencti-NGCH3KCA.js:54:416633)
	promiseReactionJob

**Comment by richard-julien** [comment]
In the error logs of the opencti graphql server API.
You put the error seen by the browser. Its better to have the full error generated by the server that should contains the stack trace

**Comment by ReadyElbow** [comment]
If the above log does not suffice, I can try and get the logs from the docker container that I have running but would need to be rebooted with the debug logging environment variable set I presume?

**Comment by richard-julien** [comment]
No need to restart in debug, its an error log it should be directly accessible

**Comment by ReadyElbow** [comment]
What is the path of the GraphQL logs? I have been monitoring my AWS Fargate Logs and nothing has been raised with regards to the issue (despite trying again and again). Might need to add another path.

**Comment by ReadyElbow** [comment]
Hi @richard-julien,

This is the only error that I have found that references graphql in the /opt/opencti/log error path:

`{"category":"APP","error":{"data":{"category":"technical","http_status":401},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (/opt/opencti/build/src/config/errors.js:8:10)","at AuthRequired (/opt/opencti/build/src/config/errors.js:20:39)","at i.resolve (/opt/opencti/build/src/graphql/authDirective.js:34:23)","at t.resolve (/opt/opencti/build/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:481:20)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:344:14)","at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at b (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:497:20)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:403:28)","at runMicrotasks (<anonymous>)","at processTicksAndRejections (node:internal/process/task_queues:96:5)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:433:24)"]},"inner_relation_creation":0,"level":"warn","message":"API Call","operation":"DashboardStixCyberObservablesNumberQuery","operation_query":"query DashboardStixCyberObservablesNumberQuery($types:[String]$endDate:DateTime){stixCyberObservablesNumber(types:$types endDate:$endDate){total count}}","size":52,"time":2,"timestamp":"2022-06-09T14:10:40.544Z","type":"READ_ERROR","version":"5.3.2"}`

This might not be the correct error log trace but its the only one in that log path that referenced it. 
If there is another log path I should look at please do say.

**Comment by ReadyElbow** [comment]
Hi @richard-julien,

Following on from yesterday, I have identified some additional information and have done a second test where only a single instance of RabbitMQ is used (please refer to ticket #2148).

Firstly, on the OpenCTI Platform itself, I noticed that it states that RabbitMQ is currently disconnected.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/53292976/173028858-c050d886-c533-4095-8b38-7fba9a92add8.png">

This does not make sense as it is currently connected to RabbitMQ and this is evidenced by connectors successfully executing + in the RabbitMQ Console it lists the current session:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/53292976/173029064-37689071-25ea-40aa-951e-c03a68c10518.png">

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/53292976/173030206-d263fd4c-6b52-496a-a6b0-af4617b6290c.png">


Bit unsure why there is a miscommunication of sorts on the frontend system?

**Comment by ReadyElbow** [comment]
@SamuelHassine Would you not classify this instead as bug?

**Comment by ReadyElbow** [comment]
Resolved: the issue was regarding the RabbitMQ user that OpenCTI was using did not have the administrator tag set so it could not perform the metric analysis it requires.
