### ISSUE TITLE
Allow ENV Variable to enable RabbitMQ Quorum Queues for increased fault tolerance

### ISSUE THREAD

**Issue by ReadyElbow** [LuatixHQ/opencti#2148]
## Use case

With building a fault tolerant deployment of OpenCTI, it is important to have replication of data enabled to ensure that if an instance fails it does not affect the surrounding platform.

My current deployment resides on AWS and I have a RabbitMQ **Cluster** deployment with autoscaling on AWS EC2. The goal of this is so that if one RabbitMQ node fails, messages are replicated so no information is lost and a new RabbitMQ instance will rejoin the cluster without RabbitMQ having any downtime to the services that depend on it.

To enable the replication of a RabbitMQ Queue, this must be setup by the client when creating the queue, through the option:
`x-queue-type:"quorum"`. This will then be handled by the RabbitMQ cluster to perform this replication. 

## Current Workaround

Use a single RabbitMQ Node deployment that will introduce a period of downtime until RabbitMQ reboots.

## Proposed Solution

Add an additional environment variable titled 'RABBITMQ__CLUSTER_REPLICATION' that when set as true will result in all queues created by OpenCTI to make use of the header as described above. 

Once set, OpenCTI no longer needs to worry about the management of queues as RabbitMQ will then handle the distribution of messages.

More information on Quorum Queues can be found here:
https://www.rabbitmq.com/quorum-queues.html#usage

## Additional Information

AWS can force an EC2 instance to reboot if the underlying hardware requires maintenance. This occurred to me last night and resulted in important streams being lost that essentially broke the OpenCTI platform as the stream it was looking for had been lost and was not replicated. This can be fixed by adding an EBS volume of course but there is till downtime.

## If the feature request is approved, would you be willing to submit a PR?

Potentially, would require a conversation to understand the current implementation of creating queues.

**Comment by ReadyElbow** [comment]
To mention as well, the Classic Queue that RabbitMQ currently provides is meant to be deprecated in the future and Quorum is to become one of the main standards.

**Comment by ReadyElbow** [comment]
For others thinking about this situation as well, as it stands with OpenCTI from reading source code, any messages published to RabbitMQ are written to the disk so they persist.
This means that there is already a level of data redundancy in the case of AWS as you can attach an EBS volume to the instance running.

However, if the RabbitMQ fails over OpenCTI will detect this if it can't publish a message and then also fail over causing an outage. If you have autoscaling setup on both, RabbitMQ will boot back up and should make use of messages stored on the EBS volume. 

However, it does an introduce an outage but its minor. I am still interested in making use of Quorum queues for RabbitMQ but until this question gets some further commentary from others I will make use of an EFS volume. 

For those wondering about an autoscaling RabbitMQ Cluster
1) Use AWS EC2 plugin to initially create the cluster,
2) When a client creates a queue it should specify its configuration as quorum
3) If a node in the cluster fails, then the following should occur when the new node rejoins the cluster

```
rabbitmq-queues shrink # to remove the previous failed node from all quorum queues
rabbitmq-queues grow "all" --vhost-pattern "a-vhost" --queue-pattern ".*" # Add the new node to all quorum queues
rabbitmq-queues rebalance quorum # redistribute queues across cluster nodes
```

**Comment by SamuelHassine** [comment]
![image](https://user-images.githubusercontent.com/1334279/173795247-4d2f6fce-9b1d-47cb-a08d-8d2cbba652fc.png)

**Comment by SamuelHassine** [comment]
Documentation updated: https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a.

**Comment by ReadyElbow** [comment]
@SamuelHassine Thanks for completing this, I'll look to do some testing in a clustered configuration when its released I presume in the next minor version
