### ISSUE TITLE
Error: read ECONNRESET - TCP.onStreamRead

### ISSUE THREAD

**Issue by mattseymour** [LuatixHQ/opencti#2156]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Periodically my opencti/platform container is crashing with the following log message:

```
Error: read ECONNRESET 
 at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

I have noticed this happening from 5.3.2 -> 5.3.5

## Environment

Kubernetes running the Opencti docker image Opencti/platform
Platform instance: has 8GB of ram running on ubuntu 20 host.
Version: 5.3.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Running the opencti platform instance.

## Additional information

Debug option does not appear to give any extra context to the error.

**Comment by richard-julien** [comment]
Do you have a full error log to copy/paste here ?

**Comment by mattseymour** [comment]
So thats part of the issue i am facing, that is all i get back before the container dies, there is no full error log, stack trace or anything more useful. Got any suggestions?

I have also dropped the log level to debug but that does not help.

**Comment by richard-julien** [comment]
Ok. Can you describe every features you used? Sync? Data sharing? Activated connectors, etc. Could help to identify the source.
In debug level can you past the last 10 logs just before the crash?

**Comment by richard-julien** [comment]
Hi @mattseymour , we identify the problem. When opencti have some issue to connect/execute command to rabbitmq it could fail fast the platform. We will fix that quickly.

**Comment by mattseymour** [comment]
Thanks, sorry I haven't got back to sooner with the logs. I was able to get some additional log entries and what you are saying does make sense and matches what I see in the logs. 

I will post my error log entries here shortly so to help others going forwards.

**Comment by mattseymour** [comment]
```
opencti-web {"category":"APP","error":{"stacktrace":["Error: read ECONNRESET","at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"]},
"inner_relation_creation":0,"level":"error","message":"API Call","operation":"GetConnectors",
"operation_query":"query GetConnectors{connectors{id name config{connection{host use_ssl port user pass}listen push}}}",
"size":2,"time":1839,"timestamp":"2022-06-13T19:45:56.718Z","type":"READ_ERROR",
"user":{"ip":"::ffff:127.0.0.6","user_id":"<<UUID>>"},"variables":{},"version":"5.3.5"}


opencti-web {"category":"APP","error":{"stacktrace":["Error: read ECONNRESET","at TCP.onStreamRead (node:internal/stream_base_commons:217:20)"]},
"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ConnectorsStatusQuery",
"operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}",
"size":2,"time":402,"timestamp":"2022-06-13T19:46:07.146Z","type":"READ_ERROR",
"user":{"ip":"::ffff:127.0.0.6","referer":"https://opencti.localhost/dashboard/data/connectors",
"user_id":"<<UUID>>"},"variables":{},"version":"5.3.5"}
```

**Comment by richard-julien** [comment]
Closing in favor of https://github.com/OpenCTI-Platform/opencti/issues/2157
