### ISSUE TITLE
Prevent platform crash or incorrect error when ELK/OpenSearch or RabbitMQ have connectivity problem

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#2157]
## Description
Prevent platform crash or incorrect error when ELK/Redis or RabbitMQ have connectivity problem

### ELK
> Error parsing when ELK is not responding correctly

### RabbitMQ
> Platform crash when command is failing on specific conditions
See https://github.com/OpenCTI-Platform/opencti/issues/2156

**Comment by mattseymour** [comment]
💯
