### ISSUE TITLE
View entity details on graph panel

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2159]
## Use case

I would like to see the entity details (like an observable) on the graph panel without the need to exit the Graph or open a new page/tab in order to check fast and easily specific information about that entity.

## Current Workaround

Select an entity (ex: observable), then click on the following button that will open a new page/tab to see the details that I need.
![image](https://user-images.githubusercontent.com/4184292/173658713-e7274f0d-993e-4a38-9c7c-5fc8b3bfa91c.png)

## Proposed Solution

Add a new button that will open a side panel on the graph view with the entity details, similarly to the update side panel when we need to update an observable or any other entity.

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
Related to #1667

**Comment by richard-julien** [comment]
Reopen for:
- Add creation date
- Add list of external references
- Empty values must be displayed to be aligned with overview
- Add list of reports that have the element (+count if possible)
- Add more information in the combobox about the relations (from - type - to) (maybe use a larger panel)

**Comment by SamuelHassine** [comment]
+ Name empty for observables
