### ISSUE TITLE
Undo option in graph visualization (actions history)

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2161]
## Use case

I would like to undo some action performed in the graph visualization, like a node Expand that pollute the graph with data that I was not interested.

## Current Workaround

None

## Proposed Solution

Record at the least the nodes added to the graph in the last action, like Expand, and provide a button to remove those nodes added from the nodes list.

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
The ability to rollback/cancel an expand will be achieved in this release, tracked in the follwing ticket: https://github.com/OpenCTI-Platform/opencti/issues/3167

I'm closing your ticket in this regards since it seems to be a duplicate. Feel free to re-open it if you disagree.
