### ISSUE TITLE
Entity details edition during data import

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#2163]
## Use case

I would like to edit all the information/details of each entity that I'm importing through the Data Import panel.

## Current Workaround

Add the details afterwards.

## Proposed Solution

A button that will open a side panel to edit the entity that is about to be ingested.

![image](https://user-images.githubusercontent.com/4184292/173720871-63588cfa-b7f8-4522-9631-c050c464a9fe.png)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
Related to #2408.
