### ISSUE TITLE
Database error when start the containers

### ISSUE THREAD

**Issue by InnerFireZ** [LuatixHQ/opencti#2170]
## Description
Hello,
i can't start opencti in docker because of this error:

The container named opencti_opencti_1 keep making errors:

{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"_stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:40:48)\n    at loadFile (/opt/opencti/build/src/database/minio.js:119:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Promise.all (index 28231)\n    at hmr.up (/opt/opencti/build/src/migrations/1652125339035-files_database.js:11:17)","data":{"category":"technical","filename":"import/Artifact/fca39b22-94f3-44d8-85db-cedefc029481/f30422f7f2110f6a7263cc7d767df6eab537d787fad5a73b43a88f22392616bb","http_status":500,"reason":"File not found","user_id":"6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"},"internalData":{},"name":"DatabaseError","time_thrown":"2022-06-16T07:59:43.901Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:54:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:335:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at boot (/opt/opencti/build/src/boot.js:14:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-06-16T07:59:47.474Z","version":"5.3.6"}

## Environment

1. OS (where OpenCTI server runs): Ubuntu 21.10
2. OpenCTI version: 5.3.6
I am using portainer for docker management

Can anyone help me to fix this?

**Comment by SamuelHassine** [comment]
Hello,

Please remove `import/Artifact/fca39b22-94f3-44d8-85db-cedefc029481/f30422f7f2110f6a7263cc7d767df6eab537d787fad5a73b43a88f22392616bb` before upgrading.

Kind regards,
Samuel

**Comment by innerfirebg** [comment]
Hey Samuel,
I really don't know how to do that… Can you help me?

Regards

**Comment by InnerFireZ** [comment]
Hey,
I try to delete some files, but each time is different file name and error continues…

Regards.

**Comment by InnerFireZ** [comment]
OK, i delete all files from specific day, and it's ok, thanks.
