### ISSUE TITLE
Can't sort based on Status

### ISSUE THREAD

**Issue by Anotherc03der** [LuatixHQ/opencti#2176]
## Description

When I click on Analysis section and sort by status I get this error 
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

The only way to fix this, is be removing the cookies, and log-in again 
## Environment

1. OS (where OpenCTI server runs): Redhat
2. OpenCTI version: 5.3.3
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. on the side menu click on Activities 
2. then click on Analysis 
3.  click on the status to sort by status 

## Expected Output

To be sorted based on the report status 

## Actual Output
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

And the The URL is :reports?sortBy=status_id&orderAsc=true&searchTerm=&filters=%7B%7D&deSelectedElements=null

## Additional information

I was able to temporarily fix the issue by removing the cookies, log in again, and making sure the URL is: dashboard/analysis/reports?

![image](https://user-images.githubusercontent.com/6181167/174200200-c2e7b28e-1677-4d84-832a-dfe92b6a0855.png)

**Comment by SamuelHassine** [comment]
Hello @alfwazi,

This issue has been resolved in the latest version (5.3.6).

Kind regards,
Samuel
