### ISSUE TITLE
Exporting selected observables causes export to hang

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2177]
## Description

Exporting selected observables causes export to hang, making it impossible to export the observables

## Environment

1. OS (where OpenCTI server runs): Demo Instance
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to observables page
2. Select several observables (in my case, I filtered on "file" objects, then selected several of them
3. Hit the export button at the top right to open the exports panel
4. Hit the "generate an export button", which is the plus sign
5. Select CSV, and not TLP limitations

## Expected Output

The export begins to generate, but is very slow, hanging at the spinning circle

## Actual Output

A CSV export is generated for download

## Additional information

Feature was originally included in #1996 

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/78382789/174649570-83f5b96e-dfb8-421d-9669-d745569e448d.png)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Unfortunately, the export feature takes into account all filters and search keyword but NOT the checkboxes. I know this can be confusing, but you have to target the list of observables you would like to export in the view before exporting them. 

In this case, you are exporting  680K observables, which obviously can take a few hours :)

In the future, we plan to take checkboxes into account for export but for now, you should use filters before export.

Kind regards,
Samuel

**Comment by securitiz** [comment]
Understood, thank you! Should I leave this issue open as a future feature request, or is there already an issue for including checkboxes?

**Comment by SamuelHassine** [comment]
Feature here: https://github.com/OpenCTI-Platform/opencti/issues/1996 is still open. You can close this one, we will move forward in the next major milestone.
