### ISSUE TITLE
When exporting observables, include all information about them (including file name(s), hashes, etc)

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2178]
## Use case

When exporting observables, it's useful to have all the information available about them. In particular, for file objects, it would be useful to have all file names, sizes, all hashes, etc. This feature should be included for all objects, however. 

## Current Workaround

Export feature doesn't provide a workaround. A user must select the object and copy/paste the information out. 

## Proposed Solution

Allow the user to export all parameters for a given objects when exporting

## Additional Information

Currently only the following columns are exported:

confidence, created, createdBy, createdById, created_at, description, entity_type, externalReferences, externalReferencesIds, from, id, lang, modified, objectLabel, objectLabelIds, objectMarking, objectMarkingIds, parent_types, relationship_type, revoked, spec_version, standard_id, start_time, stop_time, to, updated_at

Where the "from" column contains the only value that contains an actionable "IOC". Typically this is one of the hashes or a file name. 

## If the feature request is approved, would you be willing to submit a PR?

n/a

**Comment by SamuelHassine** [comment]
Hello @securitiz,

When exporting observables from an Intrusion Set or a Threat Actor, the platform is actually exporting the relationships `related-to` so we don't have all the data (only the value).

If you would like to have everything, please use the export feature on the "entities" view:

![image](https://user-images.githubusercontent.com/1334279/174650534-f47dc858-bdfc-4bcd-8e05-a323a480eb7e.png)

It will allow you to search in observables and export the list of observables instead of the list of relationships.

Kind regards,
Samuel

**Comment by securitiz** [comment]
Thank you Samuel! I tested this in our instance (which is running 5.3.6), and it doesn't appear to include the hashes. See my output CSV attached, as well as the screenshot of one of the files showing hashes (and other missing fields). 

Several other fields appear to be missing: external references, x_opencti_description, x_opencti_score, size

Additionally, is it possible to create a separate column for each hash version (MD5, SHA1, SHA256) in the resulting export CSV?

[2022-06-20T16_43_13.733Z_TLP_ALL_(ExportFileCsv)_stix-core-relationship_full.csv](https://github.com/OpenCTI-Platform/opencti/files/8942645/2022-06-20T16_43_13.733Z_TLP_ALL_.ExportFileCsv._stix-core-relationship_full.csv)

![image](https://user-images.githubusercontent.com/78382789/174653578-e0d731fd-2b06-4cb4-af46-b19bd33df319.png)

**Comment by SamuelHassine** [comment]
Will be fixed in the next release
