### ISSUE TITLE
Customisable banner for user notifications 

### ISSUE THREAD

**Issue by ReadyElbow** [LuatixHQ/opencti#2180]
## Use case

It would be useful to be able to have a customisable message that could be displayed to all users that is statically placed on the OpenCTI Platform front-end.
This is not an urgent usecase but would be a nice to have; allowing communication to all users such as when patching/migrations are taking place and when they are completed.

## Current Workaround

Work around would be emailing.

## Proposed Solution

Introduce an administrator restricted privilege to write a set of text in the settings that is then reflected across all user views of the platform front end.

## Additional Information

An example of this would be GitLab's Broadcast Messages feature: https://docs.gitlab.com/ee/user/admin_area/broadcast_messages.html

## If the feature request is approved, would you be willing to submit a PR?

Potentially.

**Comment by SamuelHassine** [comment]
Linked to #2413. Be able to mark notifications as "important" and display them as a message.

**Comment by Jipegien** [comment]
solved by #2508
