### ISSUE TITLE
Can't see mitigates relationships data in relationship tab

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#2184]
## Description

I can't see mitigates relationships data from the tab of data/relationships when I select a mitigates relationship to see information.

## Environment

1. OS (where OpenCTI server runs): Monterey 12.4
2. OpenCTI version: OpenCTI 5.3.7
3. OpenCTI client: frontend
4. Other environment details: Firefox 101.0.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data/Relationships
2. Select a mitigates relationship
3. Click on selected mitigates relationship

## Expected Output

The information tab of selected mitigates relationship but there is no data in the tab.

See screenshot 01

## Actual Output

See screenshot 02

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/68632445/175484152-b9f24817-9549-49a5-98f9-877aec5c1565.png)

![image](https://user-images.githubusercontent.com/68632445/175484178-1e83b774-2b3a-4d5c-ad38-b235bd65cc2d.png)

**Comment by sandeshkumart** [comment]
There is a bug at 
opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.js

line# 60

there should b a constraint on it like if entity type is mitigates then url should not contain knowledge as coarse of action entity doesn't have Knowledge in top bar

**Comment by JeromeSRT** [comment]
> There is a bug at 
> opencti-platform/opencti-front/src/private/components/data/relationships/RelationshipsStixCoreRelationshipLine.js
> 
> line# 60
> 
> there should b a constraint on it like if entity type is mitigates then url should not contain knowledge as coarse of action entity doesn't have Knowledge in top bar

Will the bug be solved in a next version ?

**Comment by SamuelHassine** [comment]
Hello @JeromeSRT,

This bug will be solve in the next version.

Kind regards,
Samuel
