### ISSUE TITLE
Cannot modify External ID on Courses of Action

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2186]
## Description

When updating a Course of Action entity, there is no option to update the external ID.

## Environment

1. OS (where OpenCTI server runs): AWS Linux
2. OpenCTI version: 5.2.4
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a Course of Action Entity
2. No option to edit external ID

## Expected Output

The ability to update the external ID field

## Actual Output

No option

**Comment by fayedintoyou** [comment]
I believe this issue also exists when ingesting course of actions through a connector with `update=true` and attempting to update the `x_mitre_id` field - the query made by the worker will have the new or updated `x_mitre_id` listed as part of the mutation, but that mutation will not actually occur (as in, the value will not change for that object in the database, even if other parts of that mutation on other attributes succeeded). These could be related issues.

**Comment by sandeshkumart** [comment]
Hi this might be of some help as a workaround for a bit

mutation CourseOfActionEditionOverviewFieldPatchMutation($id:ID, $input:[EditInput]!) {
 courseOfActionEdit(id: $id){
   fieldPatch(input: $input){
     id
     x_mitre_id
   }
  }
}

Variables:

{
  "id": "coa_id",
  "input": {
    "key": "x_mitre_id",
    "value": "M1010"
  }
}
