### ISSUE TITLE
OpenCTI graphql playground asks for auth.

### ISSUE THREAD

**Issue by 0x7fff9** [LuatixHQ/opencti#2195]
## Prerequisites

- [*] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [*] I went through old GitHub issues and couldn't find anything relevant
- [*] I googled the issue and didn't find anything relevant

## Description

OpenCTI graphQL playground returns an error related to authentication when test queries are performed.
Query Example:
`query issue {
  stixCoreRelationships {
    edges {
      node {
        x_opencti_stix_ids
        to {
          __typename
          ... on AttackPattern {
            id
            name
          }
        }
      }
    }
  }
}`

Expected output:
`{"data":{"stixCoreRelationships":{"edges":[{"node":{"x_opencti_stix_ids":["relationship--9f88a6ee-aacc-474c-a9eb-ec9a869140b3"],"to":{"__typename":"Malware"}}},{"node":{"x_opencti_stix_ids":["relationship--762a7fe4-f570-54d0-b899-e0b7ec08cc7d"],"to":{"__typename":"DomainName"}}},{"node":{"x_opencti_stix_ids":["relationship--46b5f22d-a89f-4014-8ccb-8e2f9223b6f5","relationship--67151978-839e-4e6f-98da-3303a038231c"],"to":{"__typename":"IntrusionSet"}}},{"node":{"x_opencti_stix_ids":["relationship--c7d246ef-071d-518e-96e5-aa10c62b06db"]` ... [more data...]

Actual output:
`{
  "errors": [
    {
      "message": "You must be logged in to do this.",
      "name": "AuthRequired",
      "time_thrown": "2022-07-06T07:54:26.825Z",
      "data": {
        "http_status": 401,
        "category": "technical"
      }
    }
  ],
  "data": {
    "stixCoreRelationships": null
  }
}`

## Environment

1. OS Debian 11
2. OpenCTI version: 5.3.7
3. OpenCTI client: Frontend
4. Other environment details: Docker install.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. authenticate on the platform ui
2. go to platformURL/graphql
3. paste query
4. error is returned after pressing "play"

I am also experiencing this on "demo.opencti.io" initially I assumes this was because we setup an nginx reverse proxy but after exposing the port 8080 on the server and communicating directly with opencti (no https or proxies) this issues persists.

Thanks in advance for any help or guidance that can be provided here.

cheers,
Guido.

**Comment by JeromeSRT** [comment]
Hello, maybe you forgot the "Authorization Bearer" with your user ID of OpenCTI in the "HTTP HEADERS" tab of the GraphQL Playground.

**Comment by 0x7fff9** [comment]
Hi Jerome, thanks.
I was not using any headers.
But this was working before with any extra header on the tab below the query maker.

Ok thanks,
regards!!
