### ISSUE TITLE
Finer access controls for Reports for feedback   - Separate "Opinions" as a knowledge creation access control under roles.

### ISSUE THREAD

**Issue by kudrew** [LuatixHQ/opencti#2196]
1) We would like the ability to use the "opinions" to give non-analyst users a way to give feedback. But allowing them to give an opinion on a report also allows them to create knowledge. Separating this access out gives the platform more flexibility in terms of user interaction
![image](https://user-images.githubusercontent.com/51339113/177585233-92d3c6c4-0260-4afd-985b-5230750e3885.png)
.

2) We would like to have the Opinion values and range (Agree, Disagree) to be configurable, so that we could define our own user/analyst feedback spectrum.
![image (1)](https://user-images.githubusercontent.com/51339113/177585372-cd95262e-64ea-4ed5-841b-d0dc17d870d5.png)

**Comment by SamuelHassine** [comment]
Always the same about opinion capability.
