### ISSUE TITLE
Add vhost configuration for RabbitMQ

### ISSUE THREAD

**Issue by rlynch-ironnet** [LuatixHQ/opencti#2199]
## Use case

I want to share a rabbitmq host between multiple environments. The easiest way to do this would be to use a vhost per environment.

## Current Workaround

There is no current workaround, at best we would have to fork and run our own image temporarily due to how the URI is built in platform, and it being hardcoded in the worker.

## Proposed Solution

Add a configuration option `rabbitmq:vhost` and pass the value to the worker config.

## Additional Information

👍 

## If the feature request is approved, would you be willing to submit a PR?

`Yes` / ~~No~~ (Help can be provided if you need assistance submitting a PR)

**Comment by richard-julien** [comment]
Thanks again @rlynch-ironnet for the contribution
