### ISSUE TITLE
Migrate synchronizer to use workers absorption. Improve speed and prevent hung up

### ISSUE THREAD

**Issue by mbixler-var** [LuatixHQ/opencti#2208]
## Description

I have 2 separate instances of OpenCTI running on VMs in Azure. They are provisioned on separate vnets and separate VMs. The Synchronizer is set up for the Destination instance to pull over all the data from the Source instance, but the Synchronizer keeps getting stuck. There is no error in the logs, but the Synchronizer will try to keep creating the same relationships over an over again (see attached logs). Stopping/Starting/Updating the synchronizer doesn't help. But I can delete it and recreate it with a start time just past the issue, and it will resume. Inevitably it will run into the same issue ~24 hours later.

## Environment

1. OS - Ubuntu 16.4
2. OpenCTI version: 5.3.7
3. OpenCTI client: Frontend
4. Other environment details: Using Kubernetes

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. On Source instance, create User, Group, and Stream
2. On Destination instance, create synchronization using credentials for User and Stream from source instance
3. Start Synchronizer on Destination instance

## Expected Output

Destination instance syncs all data from Source instance

## Actual Output

Destination instance imports some data but then gets stuck

## Additional information

[Synchronizer Logs.txt](https://github.com/OpenCTI-Platform/opencti/files/9096563/Synchronizer.Logs.txt)
[Sychronizer Time Stamps.txt](https://github.com/OpenCTI-Platform/opencti/files/9096578/Sychronizer.Time.Stamps.txt)

Data Sources on Source instance include - Alienvault, CVE, Crowdstrike, Hygiene, Mitre, OpenCTI, and RiskIQ

**Comment by richard-julien** [comment]
Synchronizer will now use an internal queue combine with the worker aborption system.
Error management will now be handle by the worker.
Dont forget to setup some workers on your sync instances if you dont have one.
