### ISSUE TITLE
"Expand labels" functionality in Investigations view

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2237]
## Use case

It would be very useful to be able to expand just on labels when in the Investigations view. 

## Current Workaround

Expand on "all entities", then delete anything that isn't a label. Doesn't work when report contains too many objects to be rendered

## Proposed Solution

See below screenshots. The list should include the ability to add only labels. 

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/179856136-4cd3b694-2796-4ced-ab76-fbe4b0d9dca3.png)

![image](https://user-images.githubusercontent.com/78382789/179856286-a594d03f-2e76-44a1-9227-2ec7e5120fc8.png)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by securitiz** [comment]
@SamuelHassine can you please confirm that this was completed? Checking in 5.3.2 and the demo instance, I don't see the ability to expand by label. Screenshot:

![image](https://user-images.githubusercontent.com/78382789/216232795-e89fa5cf-b8fa-4f10-9b15-c4d4090b9c95.png)

**Comment by mattreduce** [comment]
@SamuelHassine +1 to what @securitiz said above—I'm also not able to expand by label in investigations
