### ISSUE TITLE
Artifact file not included in stream files extensions

### ISSUE THREAD

**Issue by kmcmahon1959** [LuatixHQ/opencti#2247]
## Description
When running connectors/stream/backup-files/src/backup-files.py the resultant output data for artifacts does include the actual file data in the bundles.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.4
2. OpenCTI version: OpenCTI 5.3.7
3. OpenCTI client: python
4. Other environment details: docker version

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. python backup-files.py config.yml
2. examine output files in <backup.path>

## Expected Output

Expected a "data" element in the JSON below containing the file contents. As is expected by the _enrich_with_files function.

## Actual Output

kjmcmahon@opencti-dev:~/projects/opencti/sync/src/connectors-master/stream/backup-files/src/backup/opencti_data/20220720T163500Z$ jq . artifact--015eb792-78e5-58a8-8932-54d468885e89.json
{
  "type": "bundle",
  "objects": [
    {
      "id": "artifact--015eb792-78e5-58a8-8932-54d468885e89",
      "spec_version": "2.1",
      "type": "artifact",
      "extensions": {
        "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
          "extension_type": "property-extension",
          "id": "dad9b76e-0756-4b0f-8440-11345fe15089",
          "type": "Artifact",
          "created_at": "2022-07-20T16:35:03.181Z",
          "updated_at": "2022-07-20T16:35:03.764Z",
          "is_inferred": false
        },
        "extension-definition--f93e2c80-4231-4f9a-af8b-95c9bd566a82": {
          "extension_type": "property-extension",
          "labels": [
            "malware-bazar",
            "exe",
            "icedid"
          ],
          "description": "Uploaded to MalwareBazaar by Twitter user: pr0xylife.",
          "external_references": [
            {
              "source_name": "MalwareBazaar Recent Additions",
              "description": "MalwareBazaar Recent Additions",
              "url": "https://bazaar.abuse.ch/sample/77c3de1c2a5ced907159777ff648c2a1f3c4bdb8b6a9fbc9d06c76d8e6cb2c8d/"
            }
          ],
          "additional_names": [
            "b4ramo.dll"
          ]
        }
      },
      "mime_type": "application/x-dosexec",
      "hashes": {
        "MD5": "ceca6e5bf97cd7f3511764ed1d180702",
        "SHA-1": "72324eebf9f558933a14e0613abfd2b48dc06590",
        "SHA-256": "77c3de1c2a5ced907159777ff648c2a1f3c4bdb8b6a9fbc9d06c76d8e6cb2c8d"
      }
    }
  ]
}
 
## Additional information

Searching for this artifact in the UI, and selecting the associated observable for the SHA-256 above shows the following:

## Screenshots (optional)

![Screen Shot 2022-07-21 at 3 13 19 PM](https://user-images.githubusercontent.com/6818572/180297647-fbe37c0c-1f67-42be-a029-972178254c68.png)

**Comment by richard-julien** [comment]
Reopen, migration for existing artifacts is needed.
Data will be migrated but not the stream. Artificat never touch after the migration will not have the file information in the stream. Migration of the stream is theoricaly feasible but requirea huge amount of work

**Comment by kmcmahon1959** [comment]
Will the issue with existing artifacts be resolved by standing up a new instance from scratch? If so, I'm ok with that. As long as the stream will have the data going forward. I don't know how many other users might be dealing with the same issue.

**Comment by richard-julien** [comment]
With a new instance from scratch, every artifacts will be created correctly yes.
