### ISSUE TITLE
Remove the default search wildcard and check the behaviour in Elastic

### ISSUE THREAD

**Issue by nicocti** [LuatixHQ/opencti#2248]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hello !

I'm wondering whether there is a reason for adding a trailing wildcard on the elasticsearch "query_string" generated by a search for the frontend search bar. 

Because of it, exact matches end up with a much lower score than less relevant documents where the keyword is embedded within text.

In some cases, the exact match (for instance a country entity) won't even be returned by the query results.

From my tests, removing the trailing wildcard from the query string gives the same results overall.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend
4. Other environment details: dockerized

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Search for a single keyword
2. Catch the elasticsearch query
3. Remove the trailing wildcard in the ES query

**Comment by Jipegien** [comment]
There was some changes in 5.8 regarding the search result priorities. Can you check if it is ok for you @nicocti ?

**Comment by SamuelHassine** [comment]
This feature is considered as complete given all recent changes to search and filters.
