### ISSUE TITLE
Better management of enrichment / expired works in Redis

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2251]
## Use case

All the works that have not been finished or are still waiting can fill the Redis with thousands / hundreds of thousands database keys. It  crucial to be able to handle this without manual intervention to purge the Redis.

## Current Workaround

Purge Redis keys manually except the OpenCTI stream.

## Proposed Solution

Better management of work keys.

**Comment by richard-julien** [comment]
- When deleting a connector => delete associated works
- Delete all works older than 7 days. (platform configuration)
- No longer redis usage before work execution
