### ISSUE TITLE
User Account Expiration Date

### ISSUE THREAD

**Issue by remydewa** [LuatixHQ/opencti#2254]
## Use case

In the user creation page, I would like to be able to put an expiration date on the account.

## Current Workaround

Currently, I have to remember the expiration date of the account and go delete myself the roles and groups assigned to it to prevent it from accessing the data

## Proposed Solution

Add an expiration account date field in the user creation page

## If the feature request is approved, would you be willing to submit a PR?

Unfortunately no

**Comment by richard-julien** [comment]
Could you describe a bit more why this feature is needed? Thanks

**Comment by remydewa** [comment]
Hello @richard-julien ,

François talk about this with Samuel this week. Our use case in few words is: we just want that account expire for our customer automatically in our cloud platform. I think it could good for you too ;)

Thanks for understanding

**Comment by richard-julien** [comment]
In you use case you dont manage the users through a SSO?

**Comment by remydewa** [comment]
unfortunately not (yet)

**Comment by ParamConstructor** [comment]
@richard-julien / @SamuelHassine / @Jipegien - Recommend closure of this item. It has been added to the platform.
