### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'serv'

### ISSUE THREAD

**Issue by inura-katulanda** [LuatixHQ/opencti#2259]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
![image](https://user-images.githubusercontent.com/78894960/181403811-d31cfc81-6ce1-4cc9-ae18-8c69e798263b.png)

I tried to install the Opencti according to the manual mode provided in the documentation and I followed every step accordingly. But after I execute the command 'yarn serv'.I got the error as '00h00m00s 0/0: : ERROR: [Errno 2]' No such file or directory: 'serv' '. Could you please help me to solve the issue?

## Environment

1. OS (where OpenCTI server runs): Kali Linux 2022.2
2. OpenCTI version: opencti-release-5.3.7.tar.gz
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. sudo apt-get install nodejs npm python3 python3-pip 
2. cd opencti
3. cp config/default.json config/production.json
4. cd src/python
5. pip3 install -r requirements.txt
6.  cd ../..
7. yarn serv

**Comment by richard-julien** [comment]
Can you do a "yarn -v" command and send the result? Thanks

**Comment by inura-katulanda** [comment]
Thanks for the reply, Much appreciated. 

Sure. It gives 2 different values in 2 different locations. When,

1. In the ~/Downloads , it gives the value as 1.22.19
2. In the ~/Downloads/opencti , it gives the value as 3.2.0

![image](https://user-images.githubusercontent.com/78894960/181497073-35415ddc-2ba7-41b1-9b85-348e7aea9c36.png)

**Comment by richard-julien** [comment]
For me the correct yarn version should be the 1.22.19.
Looks like you have a problem with the yarn installation.
Try to remove all yarn installation and reinstall.

**Comment by pulpon6** [comment]
> Can you do a "yarn -v" command and send the result? Thanks

opencti@opencti:~/opencti$ yarn -v
ERROR: There are no scenarios; must have at least one.

**Comment by richard-julien** [comment]
You used another utils. Please check https://github.com/yarnpkg/yarn/issues/2821
