### ISSUE TITLE
Ability to "auto-fill" parameters of a new object, when manually created in GUI

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2271]
## Use case

When a team has to enter a large amount of data manually, it is very helpful and saves lots of time to have some fields pre-filled. Specifically: author and marking definition

The values should be decided upon by the administrator

## Current Workaround

All parameters selected manually, which takes a lot of time

## Proposed Solution

An administrator can select in Settings that every new object that is created manually via the GUI should have the Author and Marking Definition parameter pre-set.

When a user adds a new object, the values for those parameters are pre-filled

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by nino-filigran** [comment]
This is doable in the Setting/customization/entity type section. For a subset of fields for each entity you can chose default values. I'm closing this issue since it seems that all the needed work has been done, but feel free to re-open it if you do not agree or have a specific question.
