### ISSUE TITLE
Ability to move multiple objects at once in the Knowledge Graph / Investigations

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2274]
## Use case

It is useful to be able to move multiple objects at once in the visual graphs, especially when when the graph (in a knowledge graph, or investigation) contains a lot of objects

## Current Workaround

Move each object manually, which takes a lot of time

## Proposed Solution

When multiple objects are selected (either by selecting them individually, or selecting by object type), moving one object moves all the other selected objects

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
This is currently the case.
