### ISSUE TITLE
Automatically add object (both entities and observables) to a Report, when they are created in the context of the Report

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2275]
## Use case

Currently, when an object is created in the context of a Report, once the object is created, the user must separately select the object to be added to the Report. This can be confusing to a user, and there are few, if any, circumstances in which a user would be creating an object in the context of a Report, but not wanting it to be added to the same Report.

This feature would cut down on manually created objects that need to end up in Reports, but don't. It would also remove a step in the process of adding objects to a Report.

Notably, this is how External References currently already work. When an External Reference is created in the context of an object, the user doesn't have to select it separately - it is automatically added to the object

## Current Workaround

Create an object in the context of a Report. Then search for it, and add it to the report. 

## Proposed Solution

When an object (Entity or Observable) is created in the context of a report, automatically add it to the same Report.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
Currently, any entities created from Entities tab, Observables tab or Knowledge graph are added to the report (for Entities and Observables tab you just need to check a button after creation).

From my point of view, this issue is solved.
