### ISSUE TITLE
Remove "linked to" nested relationship

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2284]
## Use case

Based on my research in STIX 2.1 specs, there is no functional difference between the "linked to" nested relationship and "relates to". The only difference appears to be in the permissions - who can create a relationships between objects (https://github.com/oasis-tcs/cti-stix2/issues/285)

As such, it is confusing to have two "generic" relationship types, and it seems best to do away with one of them. I'm offering up "linked to", since it is the one that was added most recently.

## Current Workaround

Hope that "linked to" and "related to" relationships are treated the same way within OpenCTI. I doubt this is the case, because filtering in Investigations view on "related to" relationships won't return "linked to" relationships

## Proposed Solution

Combine/merge the two, so that only one exists in OpenCTI. On the backend, "linked to" relationships can be supported, and interpreted as "related to" relationships, in order to not break already existing "linked to" relationships

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Do a migration to migrate linked-to into related-to SRO and remove linked-to everywhere.

**Comment by nino-filigran** [comment]
Will be tackled in https://github.com/OpenCTI-Platform/opencti/issues/3389. We'll remove the link to ref and replace them by related to. I'm closing your ticket for now, feel free to reopen it if you think it's not the best course of action.
