### ISSUE TITLE
Add Infrastructure fields to UI when creating new Objects

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2293]
## Use case

As an Analyst, I require the ability to specify the various Infrastructure fields when creating a new Object in the Frontend.

## Current Workaround

Create Object, then edit to add additional fields

Example, in order to specify the Infrastructure Type, you would need to create the object first, then edit in order to set the Type field.

## Proposed Solution

Add the fields to the UI when creating new Infrastructure objects.

## Additional Information

<img width="891" alt="Screen Shot 2022-08-22 at 11 38 03 AM" src="https://user
<img width="891" alt="Screen Shot 2022-08-22 at 11 37 24 AM" src="https://user-images.githubusercontent.com/30411037/185974527-fc49fa73-7f62-47b2-a5a0-bf2f03eba2d1.png">
-images.githubusercontent.com/30411037/185974481-2c472fbd-5d93-4486-b169-ca33ef79a8c0.png">

## If the feature request is approved, would you be willing to submit a PR?

No - Would be willing, but not sure where this needs to be implemented.

**Comment by richard-julien** [comment]
Related to https://github.com/OpenCTI-Platform/opencti/issues/2294

**Comment by SamuelHassine** [comment]
Currently, the "infrastructure types" field is not available at Infrastructure create, only when editing. We should add the field in the creation form.
