### ISSUE TITLE
Allow default TLP to be set

### ISSUE THREAD

**Issue by h-kubokawa** [LuatixHQ/opencti#2299]
## Use case
In the current OpenCTI, if TLP was not set when the Object was created, the Object is visible to any user.
To prevent confidential data from being exposed to other users due to human error, we would like to set a default TLP for each group.

## Current Workaround
I currently do not have a solution.

## Proposed Solution
Allow default TLP to be set when updating groups.

![image](https://user-images.githubusercontent.com/112062850/186604695-ab9e0280-095c-434e-ba3e-97cbb6d32a21.png)

### If the feature request is approved, would you be willing to submit a PR?
No (I am not familiar with this code and lack the ability...)

**Comment by SamuelHassine** [comment]
Be able to have a default marking definition in the platform.

**Comment by SamuelHassine** [comment]
2 things to implement:

* Be able to set a default marking definition at a platform level (in settings)
* Be able to set a default marking definition for each group of users (as requested)
