### ISSUE TITLE
exec /entrepoint.sh: exec formar error

### ISSUE THREAD

**Issue by juazunco** [LuatixHQ/opencti#2301]
## Description

I tried to install the AlienVault Connector but I couldn't make it. I ran sudo docker-compose up but the following error was shown:

 exec /entrepoint.sh: exec formar error

## Environment

1. OS: Ubuntu 22.04.1 LTS (arm64)
2. OpenCTI version: 5.3.7
3. OpenCTI client: web browser
4. Other environment details: Oracle Cloud VPS

## Reproducible Steps

cd ~/opencti/connectors/external-import/alienvault

nano docker-compose.yml

Change the values of the variables OPENCTI_URL, OPENCTI_TOKEN, CONNECTOR_ID and ALIENVAULT_API_KEY.

At the bottom of  docker-compose.yml file add:

networks:
  default:
    external: true
    name: docker_default

sudo docker-compose up         

## Expected Output

Download and run the AlienVault connector with OpenCTI on an Ubuntu server.

## Actual Output
I downloaded the AlienVault connector but then it shows the error "exec /entrepoint.sh: exec format error" where I tried to run it

## Additional information

I have no problem running OpenCTI on an Ubuntu Desktop VM

## Screenshots (optional)
![Issue](https://user-images.githubusercontent.com/11825341/186797129-4b5991d2-9fd6-4308-be12-3f272d2870e3.png)

**Comment by juazunco** [comment]
I read some posts that this error is an architecture mismatch. I am running OpenCTI on an arm64 cloud VPS with no problem. Can the AlienVault connector be installed on the arm64 architecture?

**Comment by SamuelHassine** [comment]
Hello @juazunco,

Unfortunately only platform components Docker containers are supported on ARM64.

For connectors, you need to run them manually. This is something we plan to fix in the future but in the mean time, just know that you only need Python to run connectors.

Kind regards,
Samuel

**Comment by juazunco** [comment]
Hello Samuel

Thank you for your reply.

I ran the AlienVault connector manually but it didn't work. A name resolution error.

The value of the url variable in config.yml file is 'http://172.18.0.6:8080'. I have a doubt that is if the value of the url variable must be between single quotes.

Thanks in advance for all your support and help.

![Error](https://user-images.githubusercontent.com/11825341/186973072-e66f5033-1b37-4f3f-a9fb-c302cda509a4.png)

**Comment by juazunco** [comment]
I solved the problem. I just added the rabbitmq, opencti, and elasticsearch hostnames and their IP addresses to the /etc/hosts file.

If you run a connector manually, it won't bind to those hostnames automatically and they don't exist in any dns zone.

Thank you very much for your support. :)
