### ISSUE TITLE
`observedDatas` query does not filter by `objectContains`

### ISSUE THREAD

**Issue by eliataylor** [LuatixHQ/opencti#2305]
## Description

The `observedDatas` query does not filter by `objectContains`

## Environment

1. OS: osX & Ubuntu 18
2. OpenCTI version: Opencti 5.2.4
3. OpenCTI client: Opencti 5.2.4

## Reproducible Steps
1. Created Observed Data with some observables attached.
2. Query by `objectContains`: 
A.
```
def test(self):
        context = ["known-observable-id"]
        observed = self.helper.api.observed_data.read(filters=[{"key": "objectContains", "values": context}])
        if observed is None:
            print('success')
        else:
           print('failed')
```

or 
B. Using curl from graphql playground: 

`curl 'http://localhost:3000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' --data-binary '{"query":"query ObservedDatas($filters: [ObservedDatasFiltering], $search: String, $first: Int, $after: ID, $orderBy: ObservedDatasOrdering, $orderMode: OrderingMode) {\n    observedDatas(filters: $filters, search: $search, first: $first, after: $after, orderBy: $orderBy, orderMode: $orderMode) {\n        edges {\n            node {                            \n              standard_id\n              id \n              number_observed\n              objects {\n                  edges {\n                      node {\n                          ... on BasicObject {\n                              id\n                              entity_type\n                          }\n                          ... on BasicRelationship {\n                              id\n                              entity_type\n                          }\n                          ... on StixObject {\n                              id\n                              entity_type                                                      \n                          }                      \n                          ... on StixDomainObject {\n                              id\n                              entity_type                                                      \n                          } \n                      }\n                  }\n              }\n            }\n        }\n        pageInfo {\n            startCursor\n            endCursor\n            hasNextPage\n            hasPreviousPage\n            globalCount\n        }\n    }\n}"}' --compressed`

with variables:

```
{
  "search": null,
  "first": 1,
  "orderBy": null,
  "orderMode": null,
  "filters": [{"key": "objectContains", "values": ["known-observable-id"]}],
}
```

## Expected Output

A filtered listed of Observed Data which contain the provided observables.

## Actual Output

Either 0 results or all results.

## Screenshots (optional)
![Screen Shot 2022-08-30 at 1 35 52 PM](https://user-images.githubusercontent.com/6335974/187561870-3ad05377-3622-463b-9909-244324fcea39.png)

**Comment by eliataylor** [comment]
Interesting @SamuelHassine , 

i had tried using `export const RELATION_OBJECT_CONTAINS = 'objects';` as well as `export const RELATION_OBJECT_CONTAINS = 'object_refs'`

think this was more consistent with the stix2 schema.


i'm try this change.

**Comment by SamuelHassine** [comment]
Hello @eliataylor,

Your queries were correct, it was a bug on our side. Fixed in the latest release.

Kind regards,
Samuel
