### ISSUE TITLE
Disappearing Sectors

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#2330]
## Description

I guess there is a limited number of sectors/subsectors allowed. While adding in new subsectors and linking them to primary sectors and started noticing that previous entries began disappearing. 

## Environment

1. Latest Ubuntu version
2. openCTI version 5.3.7 (upgrading soon, might be solved in one of the three updates out but figured I would log it anyways.)
3. OpenCTI client: frontend
4. Other environment details: n/a

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add sectors (easily noticed by adding numbers to watch them disappear)
2. After adding more than 25 total sectors/sub-sectors, start checking every 5 for missing numbers.

## Expected Output

Was hoping to have 15 main sectors with further clarity through subsectors that linked back to main sector activity.

## Actual Output

Same as above, after a certain number, older entries begin disappearing.

**Comment by richard-julien** [comment]
I try to reproduce locally and on the demo without success.
Looks like in the code the list maximum result is set to 500.

Can you use chrome dev tools to look the network query fetching for the sectors and copy the payload and the result preview?

Thanks

**Comment by Astral-Reaper** [comment]
Wonder if it has to do with having more than 3300 entries in the countries/regions section (and more than 1500 cities) because the platform doesn't have a geographic location portion for smaller governing/territorial entries such as counties, internal territories, administrative divisions,  states, etc.

Will look into if the system is throwing any types of errors.

**Comment by Astral-Reaper** [comment]
Going to close the issue. Upgrading from 5.3.7 to 5.3.10 solved the problem. Thank you!
