### ISSUE TITLE
There are some Bugs in Content menu(download)

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#2358]
My OpenCTI version is below.(I'll update all images to 5.3.12 after hardware capacity expanding)

![6](https://user-images.githubusercontent.com/19428462/190587984-fd425cb9-e610-43c8-a96e-7f8eea3969c3.png)

**_Test results may not be accurate due to some lower version images._**

==========================================================
**1. Images in downloaded PDF are not shown**
- Downloaded html is fine

![1](https://user-images.githubusercontent.com/19428462/190585631-7461153f-20c8-4a95-b57e-453db152c628.png)
![2](https://user-images.githubusercontent.com/19428462/190589800-aaa46919-80d4-4e08-8b95-40fabdb504e0.png)

**2. If there is Image uploaded by URL, PDF download button don't work.**
- html download button works fine.

![3](https://user-images.githubusercontent.com/19428462/190586815-ff35661f-ecf8-4e63-a0c6-72fbad7a9571.png)

**3. Showing UNICODE error in downloaded PDF**
- When Unicode such as Korean exists, characters are not displayed correctly in the downloaded PDF. (Same for all PDF files in the Content menu)
- Downloaded html is fine

![4](https://user-images.githubusercontent.com/19428462/190586400-5f5594e9-e8d9-4ce8-95d0-9d9aabbe12f1.png)
![5](https://user-images.githubusercontent.com/19428462/190586415-4fea647a-129e-44df-ba24-2f4f61922eff.png)

==========================================================

I hope these bugs will be fixed.

Thank you for reading :)

**Comment by SamuelHassine** [comment]
Hello @misohouse,

Can you please share the HTML file that causes the PDF download problem? 

Thanks!

Kind regards,
Samuel

**Comment by misohouse** [comment]
> 
@ [SamuelHassine](https://github.com/SamuelHassine)

Sure! 👍
 
[test.html.txt](https://github.com/OpenCTI-Platform/opencti/files/9630053/test.html.txt)
=> You should remove "txt" extension. (I can't upload html extension file)

And, unfortunately I can't download korean_test.html file because my opencti down.. :(
#2378

I can upload test.html since I did download before.

And I upload pdf files.

[test.html.pdf](https://github.com/OpenCTI-Platform/opencti/files/9630046/test.html.pdf)
[korean_test.txt.pdf](https://github.com/OpenCTI-Platform/opencti/files/9630047/korean_test.txt.pdf)

**Comment by SamuelHassine** [comment]
Ok nice, here is the PDF file generated now: 
[dsdqdtest.html (2).pdf](https://github.com/OpenCTI-Platform/opencti/files/9630102/dsdqdtest.html.2.pdf)

I will close this issue and re-open a new one as feature for Korean since it is something we need to implement.

**Comment by SamuelHassine** [comment]
Uploaded images are ok in PDF.
Images from URL it depends on the remote cross scripting policy, generally it will not work. We will try to find another solution but it is also a feature to implement.
