### ISSUE TITLE
Consider adding a custom confidence scale for sources and contents

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#2362]
## Use case

Currently confidence scale is fixed to certain values. For example, confidence values in STIX are mapped onto `confidence_0` , `confidence_15`, `confidence_50`, `confidence_75` and `confidence_85`.

```
      confidence_0: 'Desconocida',
      confidence_15: 'Débil',
      confidence_50: 'Moderada',
      confidence_75: 'Buena',
      confidence_85: 'Fuerte',
      confidence_unknown: 'Desconocida',
```

Considering the usage of the Admiralty Scale already applies to Sources as proposed in the STIX 2.1 standard and according to the [FM 2.22-3](https://armypubs.army.mil/epubs/DR_pubs/DR_a/pdf/web/fm2_22x3.pdf).
```
      reliability_A: 'A - Completamente fiable',
      reliability_B: 'B - Usualmente fiable',
      reliability_C: 'C - Bastante fiable',
      reliability_D: 'D - No habitualmente fiable',
      reliability_E: 'E - No fiable',
      reliability_F: 'F - La fiabilidad no puede ser juzgada',
```

## Current Workaround

None. Using the predefined confidence proposal.

## Proposed Solution

Adding a new setting to make it an option to use the admiralty scale as defined in appendix B1 of the FM 2.22-3 when setting the confidence on an observation.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Linked to #2555.

**Comment by SamuelHassine** [comment]
Reliability is only on "Organization". We need to:

* Extend the attribute to all SDOs and SCOs.
* Introduce the capability to customize reliability scale (based on letters) to say A = XX, B = XX.
* Display the confidence and the reliability in the same place in the overview of entity with a nice layout
