### ISSUE TITLE
Threat Actor Entity ID Not Found During Export

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#2380]
## Description

I was in the process of developing the ExportReportPDF connector further, to allow exporting Threat Actor entities to PDF.

Code example:

```
self.helper.api.stix2.export_entity(
    "Threat-Actor", entity_id, "full"
)
```

This results in the following error:

```
Cannot export entity (not found)
```

## Environment

1. OS: AWS
2. OpenCTI version: 5.3.15
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Threat Actor entity.
2. Attempt to export to PDF like so:

![image](https://user-images.githubusercontent.com/93540406/191895419-62d54bcc-30be-415c-a640-bfe467c8efad.png)

Note: For testing purposes, the image at ```yungbinary/export_report_pdf:5.3.15``` can be used.

**Comment by SamuelHassine** [comment]
Hello @YungBinary,

I've tested on demo and the payload is received on the connector is correct:

![image](https://user-images.githubusercontent.com/1334279/191901085-c15e387c-8479-438d-9448-82af10cc5aa7.png)

```
{'export_scope': 'single', 'export_type': 'full', 'file_name': '2022-09-23T06:07:43.323Z_TLP:ALL_(ExportReportPdf)_Threat-Actor-Russian cyber threat_full.pdf', 'max_marking': None, 'entity_type': 'Threat-Actor', 'entity_id': '8d7f5990-d4ce-43c7-9333-f6a5b921865b'}
``` 

The export SDOs option is generic and the same for all entities. Can you double check that the entity has not been merged in the mean time? Can you copy/paste the entiere `data` received in the _process_message function?

Kind regards,
Samuel

**Comment by YungBinary** [comment]
@SamuelHassine Interesting, it appears the id in the URL is different from the entities actual id? Just tested in 5.3.15 and seeing this as the payload:

```
{
  "export_scope": "single",
  "export_type": "full",
  "file_name": "2022-09-23T22:27:51.425Z_TLP:ALL_(ExportReportPdf)_Threat-Actor-Wizard Spider_full.pdf",
  "max_marking": null,
  "entity_type": "Threat-Actor",
  "entity_id": "079608b2-4545-4fe9-91e3-02eb3fa41bc5"
}
```

As seen in the screenshot below, the Threat Actor entity id is supposed to be `61817879-c864-5559-806d-e473e4869998`:

![image](https://user-images.githubusercontent.com/93540406/192064571-c13e7995-570a-4eb7-9975-9ca4c8240be5.png)

**Comment by YungBinary** [comment]
@SamuelHassine I just updated the original issue with a code example. Perhaps I have confused the entity id and stix id. I figured they would be the same, nonetheless, it seems export_entity may not handle Threat-Actor objects?

**Comment by SamuelHassine** [comment]
@YungBinary the `entity_id` is the "internal ID" of the entity (check the URL of the Threat Actor). As I checked previously, Threat Actor are supported. 

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Check if the user of the connector is in the correct group that have access to all marking definitions of the Threat Actor :)

**Comment by YungBinary** [comment]
@SamuelHassine That did it, thank you very much!
