### ISSUE TITLE
The "Subscriptions & digests" email returns "{defaultValue(entry)}"

### ISSUE THREAD

**Issue by tanyawang1218** [LuatixHQ/opencti#2381]
## Description

For subscription generated emails – it looks like there is some bug in terms of showing content. 

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version:  OpenCTI 5.3.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a subscription
2. Update the target entity
3. Receive the email but not showing content.

## Expected Output

The email shows what new entity is added or updated.

## Actual Output

The email shows {defaultValue(entry)}.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/10161931/191927184-fdff2164-3093-4986-a653-84dd1cd33059.png)

**Comment by SamuelHassine** [comment]
Solved in 5.3.16.
