### ISSUE TITLE
SAML not working. Configuration error?

### ISSUE THREAD

**Issue by smclinden** [LuatixHQ/opencti#2383]
## Prerequisites

- [ x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x ] I went through old GitHub issues and couldn't find anything relevant
- [x ] I googled the issue and didn't find anything relevant

## Description

SAML auth does not seem to be invoked 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 5.3.7
3. OpenCTI client: Browser
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Configure SAML connector
2. Attempt SAML authentication
3. OpenCTI skips SAML attempt and goes straight to localStrategy

## Additional information

```
    "saml": {
        "identifier": "saml",
        "strategy": "SamlStrategy",
        "config": {
            "issuer": "opencti",
            "entry_point": "https://login.microsoftonline.com/{UID}/saml2",
            "saml_callack_url": "https://xxxxx.yyy.com:4000/auth/saml/callback",
            "authnContext": "https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows",
            "identifierFormat": null,
            "cert": "MIIC8DCCAdigAwIB...Yys57Fim",
            "roles_management": {
              "role_attributes": ["Role"],
              "roles_mapping": ["ITSecOps"]
            }
        }
    },
```

**Comment by lachlan112** [comment]
Am receiving similiar when trying to set-up SAML with Azure AD.

**Comment by smclinden** [comment]
The issue appears to be with the SAML interface. Closing this and reopening as a bug.

**Comment by smclinden** [comment]
The issue appears to be with the SAML interface. Closing this and reopening as a bug.
