### ISSUE TITLE
Add States to Location

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#2385]
## Use case

Tracking or logging activities within specific areas, more granular than just a general country.

## Current Workaround

Adding them as Countries and linking to the Region: United States of America. (You can sublink Regions to Regions, but you cannot Sublink Countries to Countries.)

## Proposed Solution

- Either add a custom option on Location to include States, or 

- rework openCTIs usage of "Administrative Positions" to encompass States and other local controlling divisions.  (And preferably make them sub-linkable to other admin regions)

Example1:
Region: Americas
Sub-Region: Northern Americas
Country: United States of America
State:  Florida
County: Broward County

Example2:
Region: Europe
Country: Germany
State: Thuringia

_13 countries across the world have state divisions, including the United States, Mexico, Australia, Brazil, Germany, etc._

## Additional Information

Would be nice to include map-geo-highlighting as well.
Please feel free to reach out for more information.
Thank you!

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by SamuelHassine** [comment]
Add a new location entity type "Administrative Area". Linked to #1683.

City => Located-at => Administrative Area
Administrative Area => located-at => Country
