### ISSUE TITLE
Filtering for Attack Patterns

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#2388]
## Use case

We use attack patterns in a variety of ways and are always adding in new paradigms.

## Current Workaround

Can only do through search bar.

## Proposed Solution

Add in filter functions like other tabs have (Label, Marking, Created After/Before, Author) And potentially even different groupings like you can do in Analysis/Reports and has been requested for Events earlier. :D

## Additional Information

Although it is a convenience thing right now, soon the dataset size will call for this level of granular filtering.

## If the feature request is approved, would you be willing to submit a PR?

Sure can provide positive PR responses and promotion. :D

**Comment by nino-filigran** [comment]
I'm closing this issue since in the attack pattern screen, you can now filter on lots of parameters including: Label, Marking, Created After/Before, Author...
