### ISSUE TITLE
Improve Report Knowledge Graph Note display

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#2398]
## Description

When creating and refining reports, notes included as a nested object are pulled into the visualization but display their stix ID and not their label name.

## Environment

1. Latest Ubuntu
2. OpenCTI version: 5.3.15
3. OpenCTI client: Frontend/GUI
4. Other environment details: n/a

## Reproducible Steps

Knowledge section on reports with items that have nested notes.

## Expected Output

Display Note name and not the Stix ID number

## Actual Output

Stix ID number making it difficult to identify what it is without opening it separately.

## Additional information

n/a

**Comment by richard-julien** [comment]
![image](https://user-images.githubusercontent.com/285555/193121873-4c298b41-2c9b-470f-bad2-8bf83e7b6325.png)

**Comment by Archidoit** [comment]
outdated issue -> notes are correctly displayed
![image](https://user-images.githubusercontent.com/75783086/226609955-ff961476-cbcb-483d-a345-a69fad4b9409.png)
