### ISSUE TITLE
Variable "$fromId" of type "String" used in position expecting type "StixRef"

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#2399]
## Description

I am adding the capability to the Export Report PDF connector to process threat actors and running into an issue as seen below.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/93540406/193151014-a6abc2f2-410b-49ea-82fd-979e10e6fbfb.png">

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: 5.3.15
3. OpenCTI client: frontend

**Comment by richard-julien** [comment]
Hi, you need to align th version of the platform with the verison of the connectors.

**Comment by YungBinary** [comment]
> Hi, you need to align th version of the platform with the verison of the connectors.

Thank you! It turns out the image I was testing with in Dockerhub had ```pycti==5.3.8``` in the requirements.txt, however we are on version 5.3.15.
