### ISSUE TITLE
Improve of performance indicator checkIndicatorSyntax function

### ISSUE THREAD

**Issue by nikolaiav** [LuatixHQ/opencti#2401]
## Indicators mass upload

Hi.
I have created external import connector.
Each day i have 300K (indicators+threats+relations) for uploading.
I find out that opencti-platform validate 'pattern' attribute for each stix indicator and do that by invoking python validator.

## Current Workaround

After comment this lines [Code](https://github.com/OpenCTI-Platform/opencti/blob/5164ee6a1d57e42dc5fa16ed6335a3b32be0cf9a/opencti-platform/opencti-graphql/src/domain/indicator.js#L183) upload performance dramatically increase.

## Proposed Solution

It will be very pleasant if you try to think about optimization this code.

## Additional Information
Before  
[opencti-before.jpg](https://postimg.cc/HrH5K1Vm)  
After (Now I'm stuck on the performance of my single node Elastic)  
[opencti-after.jpg](https://postimg.cc/qgyxZLj8)

**Comment by richard-julien** [comment]
Reopen, not finished yet

**Comment by richard-julien** [comment]
Usage of a new library to prevent spawning a child python process each time.
https://github.com/hmenyus/node-calls-python
https://github.com/hmenyus/node-calls-python/issues/33
