### ISSUE TITLE
[Feature] Filter for 'Score less than' within Retention Policy Rules 

### ISSUE THREAD

**Issue by gbikram** [LuatixHQ/opencti#2406]
## Use case

As an admin, I should be able to auto-delete indicators/observables from the OpenCTI platform, based on "less than" thresholds for the indicator score (eg. score > 0 AND < 30). 

Currently, the filters for retention policies do not include a "score less than" filter, making it challenging to apply a retention policy to indicators under a certain score.

## Current Workaround

Implement a connector (similar to Hygiene) that checks an indicator's score at the time of ingestion and applies a label to it that is indicative of the retention policy that should be applied to the indicator (eg. retain_30d). A retention policy is configured to filter for indicators with this specific label (retain_30d) and delete the matching indicators from the platform.   

## Proposed Solution

Add a new filter to Retention Policies that would allow filtering for indicators that have a score that is less than a certain threshold. This would be very similar to the "score greater than" filter. 

## Additional Information
Here is a [link](https://luatix.slack.com/archives/CHZC2D38C/p1664553900196319) to the Slack message for reference

**Comment by ckane** [comment]
I'd love to see an implementation of this that could be used to make the "deletion" or "disabling" decision based upon any arbitrary criteria. There appears to be some interesting examples of complex logic being used to perform data management operations in the "Rules Engine" panel, but most of these seem to be statically designed and I cannot find where to create your own. Building a connector that runs on a periodic basis to perform the complex tests and data manipulation would be my approach right now too.

One key thing I would add is that "deletion" as the outcome is probably not the preferable approach for many users, but rather "disable the indicator" through some means, when the "deprecation" criteria is met. In my uses, I always want to know what used to be deployed, and being able to continue to retain that detail, and the time windows it was deployed, in the CTI knowledge base is the most valuable approach for me and others I know in the CTI space.

So, definitely support "deletion" as an outcome, but also recommend supporting the maintaining of permanent retention combined with turning the "Detection" switch off in the indicators, and have that non-destructive option be the default behavior.
