### ISSUE TITLE
Full refactor of pre-validation screen into an analyst workbench

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2408]
## Use case

Refactor the pre-validation screen into an analyst temporary workbench:

* Lines/Columns layout
* Save current state
* Add new element
* Be able to add columns for new relationship (victimology, attribution)
* Remember choices for adaptive behavior over time

**Comment by SamuelHassine** [comment]
Related to #1799.

**Comment by kudrew** [comment]
@SamuelHassine from testing this in Demo and comparing it to 5.3.17, importing the same pdf will give different results. 

Also on Demo, adding entities manually in the workbench section of the validation screen and validating will create them on the platform, but doesn't add them to the report.
