### ISSUE TITLE
Workspaces seggregation by user and/or group

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2418]
## Use case

Be able to have a more granular seggregation / RBAC on workspaces (dashboard and investigations):

* By default, workspace is only accessible to the current user
* Can be shared with one (or multiple) of the groups he is part of
* Can be shared with any users
* Can be shared publicly (#2101)

**Comment by richard-julien** [comment]
New idea that need to be discussed in the current modelization https://github.com/OpenCTI-Platform/opencti/issues/3181
