### ISSUE TITLE
Automatically create groups on SSO

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2419]
## Use case

When variables `ROVIDERS__OPENID__CONFIG__ROLES_MANAGEMENT__ROLES_MAPPING` and `PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING` are defined, automatically create the group if it does not exist and map the user on it.

**Comment by richard-julien** [comment]
Should be linked to an AUTO_CREATE_GROUP option

**Comment by GraemeMeyerGT** [comment]
> Should be linked to an AUTO_CREATE_GROUP option

@richard-julien was this option created? I can't see anything mentioned in the docs

**Comment by richard-julien** [comment]
You're right @GraemeMeyerGT , this config is missing in  the documentation. We will add it.
for information this option "auto_create_group" must be setup in the config part

```
"oic": {
    "identifier": "oic",
    "strategy": "OpenIDConnectStrategy",
    "config": {
         ...
        "auto_create_group": true,
    }
}
```

**Comment by GoZ8** [comment]
Hello @richard-julien I haven't found the right name for the docker variable "auto_create_group". Is it implemeted ? Maybe "PROVIDERS__SAML__CONFIG__AUTO_CREATE_GROUP" if I guess right ?

Would it also be possible to have an exhaustive list of Docker environment variables in the documentation?
