### ISSUE TITLE
Helm charts for platform / connectors (sub charts for dependencies)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2422]
## Use case

Helm charts for platform / connectors (sub charts for dependencies)

**Comment by zentavr** [comment]
Hi @SamuelHassine.

I'm checking https://github.com/Ascend-Technologies/OpenCTI-HELM-CHART and see that there is a chart contains everything (I mean dozens of connectors, web-deployment, worker-deployment, rabbitMQ, Redis, minio, etc). Is that chart comes from your company or you would like to build your own?

Saying:
- RabbitMQ could be done by [bitnami/rabbitmq-cluster-operator](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq-cluster-operator) or [bitnami/rabbitmq](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq)
- Redis could be done by [bitnami/redis](https://github.com/bitnami/charts/tree/main/bitnami/redis) or [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster)
- Minio could be done by [bitnami/minio](https://github.com/bitnami/charts/tree/main/bitnami/minio)
- Elasticsearch could be done by [bitnami/elasticsearch](https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch)

We would like to test OpenCTI internally in our organization and thinking about how to deploy it to Kubernetes (to ouse the chart I'd mentioned or create our own). We have own Ceph clusters and probably having Minio would be an overhead here. The same is for Elasticsearch.
