### ISSUE TITLE
Custom Dashboards Entity Filtering Feature Request

### ISSUE THREAD

**Issue by akshaysth** [LuatixHQ/opencti#2425]
## Use case

I'm looking to create custom dashboards for select entities filtered by labels or marking definitions.

## Current Workaround

None. Currently only able to choose by entity type.

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by richard-julien** [comment]
Should be covered by https://github.com/OpenCTI-Platform/opencti/issues/2409
