### ISSUE TITLE
don´t see the Marking Definition 

### ISSUE THREAD

**Issue by jcandiat** [LuatixHQ/opencti#2426]
## Description

You don't see the marking definition

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: 5.3.16

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create new report or when I choose several reports for modification

## Expected Output

![image](https://user-images.githubusercontent.com/5710026/193693062-cf60caa1-a38b-4ccf-9110-89b7d8d79016.png)

## Actual Output

![image](https://user-images.githubusercontent.com/5710026/193692985-00a7d58b-75ac-4fab-9c00-d0deb9ad80bb.png)

![image](https://user-images.githubusercontent.com/5710026/193693000-d3bf54f6-2c9e-42c3-b2bd-90f5b417fffd.png)

**Comment by richard-julien** [comment]
Please check that your user have access to the marking. (User -> Group -> Markings)

**Comment by jcandiat** [comment]
validated with a user with the following groups:
![image](https://user-images.githubusercontent.com/5710026/193821491-261617fc-3777-467d-a81e-ce09e5a0bf57.png)

group:
![image](https://user-images.githubusercontent.com/5710026/193821508-63709096-e874-43ec-916e-1a6264d25aae.png)

**Comment by richard-julien** [comment]
Check in permissions tab the marking granted for this group

**Comment by jcandiat** [comment]
Permissions Tab:

![image](https://user-images.githubusercontent.com/5710026/193823558-2e5a754c-d9e2-4bd3-abc9-7fc1aada002b.png)

**Comment by jcandiat** [comment]
Permissions Tab:

![image](https://user-images.githubusercontent.com/5710026/193823795-eabd28ce-60b4-4094-b07a-f7f967a7e266.png)

**Comment by richard-julien** [comment]
Do you try to logout/login again?
Permissions are not dynamically applied yet.

**Comment by jcandiat** [comment]
@richard-julien I did indeed try, even try removing and reselecting the markings in the permissions tab. This error arises after I updated to version 5.3.16, in the previous one it did not happen to me.

**Comment by Astral-Reaper** [comment]
@jcandiat 
We had this happen as well when updating from 5.3.10 to 5.3.15. What happened was, all the TLP Markings were gone and we needed to re-add.

**Comment by jcandiat** [comment]
@Astral-Reaper I tried, even took the user out of the group and re-integrated it, but it doesn't work.

**Comment by SamuelHassine** [comment]
Duplicate of #2436

**Comment by richard-julien** [comment]
This bug prevent use to add new marking definition on elements.
For information is **not impacting** data seggregation / visibilty.
