### ISSUE TITLE
Elastic is not found after version 5.3.7

### ISSUE THREAD

**Issue by Bella-chris** [LuatixHQ/opencti#2430]
Hello,

I tired to upgrade my 5.3.7 version of OpenCTI and any version after that creates the below error:
{"category":"APP","error":{"context":{},"message":"The client noticed that the server is not Elasticsearch and we do not support this unknown product.","name":"ProductNotSupportedError","stack":"ProductNotSupportedError: The client noticed that the server is not Elasticsearch and we do not support this unknown product.\n    at Mme.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:476:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at JF.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:84:10)\n    at reloadStatuses (/opt/opencti/build/src/manager/cacheManager.ts:31:23)\n    at workflowStatuses (/opt/opencti/build/src/manager/cacheManager.ts:39:20)\n    at Object.start (/opt/opencti/build/src/manager/cacheManager.ts:66:35)\n    at boot (/opt/opencti/build/src/boot.js:12:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-05T17:43:19.273Z","version":"5.3.16"}

Could you tell me a fix for that?

**Comment by Bella-chris** [comment]
Could you please support on this @nor3th @richard-julien @SamuelHassine?

**Comment by richard-julien** [comment]
Hi @Bella-chris , can you specify the version and the type of deployment that you used for your elasticsearch? Thanks

**Comment by Bella-chris** [comment]
@richard-julien I deployed elastic via docker, and it is version 7.13.1 
![image](https://user-images.githubusercontent.com/92671957/194750664-bdcd30a6-9de7-4909-af97-1617caacacf1.png)

**Comment by richard-julien** [comment]
Can you start by upgrading your elasticsearch to the latest version?

**Comment by Bella-chris** [comment]
Thanks @richard-julien , its working now

**Comment by richard-julien** [comment]
Ok perfect. Dont forget to upgrade your dependencies (redis, elastic, ...) regularly for the mino version. For major version we annonce it on the release note.
