### ISSUE TITLE
Synchronizer Erroring and Looping

### ISSUE THREAD

**Issue by mbixler-var** [LuatixHQ/opencti#2432]
## Description

I have 2 instances of OpenCTI. One has all the connectors (Instance 1), the other (Instance 2) is ingesting the data from Instnace 1 using a synchronizer. On Instance 2 (receiver) the synchronizer keeps getting stuck and then resetting itself to an earlier time. It loops indefinitely. It is also throwing TLS errors, even though TLS is not enabled.
## Environment

1. Ubuntu 16.4 on Azure
2. 5.3.15
3.  OpenCTI client: { e.g. frontend or python }
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. On Instance 1 (Sender) create Role- Sync with only Connect and consume the platform streams (/stream, /stream/live) permission. Create Group with Permissions to All Markings. Create User and add them to Sync role and Group.
2. On Instance 2 (Receiver) Add synchronizer using URL for Instance 1 and credentials for Sync user that was created.
3. Start synchronizer

## Expected Output

Synchronizer ingests all the data from Instance 1 to Instance 2.
 
## Actual Output

Synchronizer Errors out and Restarts at original time. Also TLS errors even though TLS is not enabled.

## Additional information

{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:21:12.897Z","timestamp":"2022-10-06T17:57:23.914Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:21:25.739Z","timestamp":"2022-10-06T17:57:39.245Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:21:34.094Z","timestamp":"2022-10-06T17:57:54.254Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:21:44.921Z","timestamp":"2022-10-06T17:58:09.317Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:21:56.417Z","timestamp":"2022-10-06T17:58:24.334Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:22:08.434Z","timestamp":"2022-10-06T17:59:38.950Z","version":"5.3.15"}
{"category":"APP","error":{"context":{},"message":"self signed certificate","name":"Error","stack":"Error: self signed certificate\n at TLSSocket.onConnectSecure (node:_tls_wrap:1535:34)\n at TLSSocket.emit (node:events:513:28)\n at TLSSocket._finishInit (node:_tls_wrap:949:8)\n at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:730:12)"},"level":"error","message":"[OPENCTI] Sync error processing event","timestamp":"2022-10-06T18:01:21.594Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:22:09.090Z","timestamp":"2022-10-06T18:01:21.963Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:22:20.320Z","timestamp":"2022-10-06T18:01:37.440Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:22:34.546Z","timestamp":"2022-10-06T18:01:52.448Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:22:47.698Z","timestamp":"2022-10-06T18:02:07.452Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:23:01.372Z","timestamp":"2022-10-06T18:02:25.023Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:23:07.614Z","timestamp":"2022-10-06T18:02:40.658Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:23:12.275Z","timestamp":"2022-10-06T18:02:55.691Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:23:37.276Z","timestamp":"2022-10-06T18:03:10.888Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:24:08.999Z","timestamp":"2022-10-06T18:03:25.918Z","version":"5.3.15"}
{"category":"APP","level":"error","message":"[OPENCTI] Error in sync manager for [UUID IS HERE]: undefined","timestamp":"2022-10-06T18:04:32.509Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:00:48.335Z","timestamp":"2022-10-06T18:04:36.653Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:00:52.440Z","timestamp":"2022-10-06T18:04:51.675Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:00:57.248Z","timestamp":"2022-10-06T18:05:06.914Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:01:01.173Z","timestamp":"2022-10-06T18:05:21.925Z","version":"5.3.15"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync Prod Conn Synchronizer: saving state to 2022-09-10T04:01:05.476Z","timestamp":"2022-10-06T18:05:39.957Z","version":"5.3.15"

**Comment by richard-julien** [comment]
For now im not able to reproduce. Still looking into it.
Will also add more logs in the synchronizer to have more information

**Comment by richard-julien** [comment]
Reproduced. Fixed the loop back / improve the ssl rejection.
Also add more log info in case of error.
