### ISSUE TITLE
[api] Filters support multiples keys to search on

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2435]
## Use case

Filters on "name" should also look into aliases

**Comment by richard-julien** [comment]
We decide to add a support for filter with multiple keys.
Value will be search on each key with an logical OR

Here an example

query malware {
```
  malwares(filters: [{ key: [name, aliases], values: ["black energy"] }]) {
    edges {
      node {
        id #
        name
        aliases
      }
    }
  }
}
```
