### ISSUE TITLE
No available options in marking field

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#2436]
## Description

No available options in marking field of the "Update à report" panel

## Environment

1. OS (where OpenCTI server runs): Mac OS 12.
2. OpenCTI version: 5.3.16
3. OpenCTI client: Frontend
4. Other environment details: Firefox 105.0.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on a report in the reports list
2. Click on Update when you select the list of three points near the name of the report
3. Try to change the marking

## Expected Output

List of the available markings

## Actual Output

No available options

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/68632445/194697741-e7569a99-94fd-4e2c-973c-5b2f6f6d0b73.png)

**Comment by richard-julien** [comment]
Close duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2426
