### ISSUE TITLE
Redis occupy too many memory

### ISSUE THREAD

**Issue by little-roach** [LuatixHQ/opencti#2438]
## Description

Using docker to deploy OpenCTI, Redis will occupy too many memory and lead to system crash and reboot all the time.

we find out the key "stream.opencti" in redis is the main reason.  we hope the size of key "stream.opencti" can be limited.

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.3.16
3. Other environment details: 15 cores, 32 GB memory space

## Screenshots (optional)

![OpenCTI_bugs](https://user-images.githubusercontent.com/77371166/194733872-f74b9f65-b429-4382-bc69-2b8e4c1229eb.PNG)

![OpenCTI_bugs-2](https://user-images.githubusercontent.com/77371166/194733877-d236915e-4623-400d-be61-2a2a657fcc67.PNG)

**Comment by SamuelHassine** [comment]
Hello @little-roach,

At the platform level, you can change the parameter `redis:trimming` (`REDIS__TRIMMING`) to limit the number of events retained in the `stream.opencti`. By default, this parameter is set to 0 (unlimited). We advise `500,000` for a optimal memory consumption and platform work in medium tenants, `1,000,000` in large tenants.

Kind regards,
Samuel

**Comment by little-roach** [comment]
Hello @SamuelHassine,

Thanks for your reply! 

How can I modify this parameter in docker-compose.yml？

**Comment by SamuelHassine** [comment]
Hello @little-roach,

Yes, using the env var `REDIS__TRIMMING` on the platform container.

**Comment by gbikram** [comment]
Adding additional context from Slack channel since this was helpful

<img width="890" height="486" alt="Image" src="https://github.com/user-attachments/assets/a07dac15-3338-42c6-a60d-147221619ae4" />
