### ISSUE TITLE
Add "Shodan" Pattern Type to Indicators

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2446]
## Use case

As a cyber Threat Analyst, I use various Shodan filters to find data about different observables.  I require the ability to store Shodan search queries within the OpenCTI so that I can automate the process of running targeted searches using observables and indicators within the platform.

Example:
Write a custom Shodan search that searches across a CIDR network, search for hostnames, etc.

## Current Workaround

Have to store searches in a separate platform.

## Proposed Solution

Add a Shodan Pattern Type to the Indicators Objects/graph.

## Additional Information

The functionality of the existing Shodan Connector could be updated to leverage these detections/indicators to further enhance the data that is enriched.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by richard-julien** [comment]
+ find a way to check if this pattern type is correct
