### ISSUE TITLE
Expand Pattern Types to include Major AV Vendors

### ISSUE THREAD

**Issue by TechBurn0ut** [LuatixHQ/opencti#2447]
## Use case

As a Cyber Threat Analyst, I require the ability to create indicators for vendor specific AV/EDR Signatures.  Currently, the Indicator pattern types currently do not contain any other vendors.  We would like the ability to store Signatures for these vendors:

McAfee
Broadcom/Symantec
Cisco (for platforms other than Snort)
Microsoft Defender
TrendMicro
Crowdstrike
SentinelOne 

## Current Workaround

There is currently no solution for this other than storing the data as a different SDO/Cyber Observable.

## Proposed Solution

Add the above vendors/platforms to the available Indicator/Detection pattern Types

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by richard-julien** [comment]
Related to https://github.com/OpenCTI-Platform/opencti/issues/2446

**Comment by SamuelHassine** [comment]
Hello @TechBurn0ut,

Pattern types OV is now customizable so you can add as many as pattern type you need.

Closing this.

Kind regards, 
Samuel
