### ISSUE TITLE
Public Dashboard

### ISSUE THREAD

**Issue by jcandiat** [LuatixHQ/opencti#2454]
## Use case

As analysts and MSSP company, we would like the possibility of publicly displaying IOCs analyzed by us, without the need for authentication, rather as external consumption, for the same reason, having the possibility of generating public dashboards, with data that we stipulate in display by the definition of marking.

**Comment by richard-julien** [comment]
Thanks for your issue @jcandiat .
This is an already existing ticket https://github.com/OpenCTI-Platform/opencti/issues/2101
Closing this one, dont hesitate to add information on the other one if needed.
