### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by kohsawa** [LuatixHQ/opencti#2456]
## Use case

Users (mainly: Japanese speakers) will be able to choose Japanese as the displayed language.

## Current Workaround

No

## Proposed Solution

Add Japanese localization.

## Additional Information

No

## If the feature request is approved, would you be willing to submit a PR?

Yes, I've already made PR as https://github.com/OpenCTI-Platform/opencti/pull/2455 .

**Comment by richard-julien** [comment]
Hi @kohsawa , thats really cool ! Thanks for the PR!
