### ISSUE TITLE
Connector role doesn't get stream data.

### ISSUE THREAD

**Issue by RaulSokolova** [LuatixHQ/opencti#2467]
## Description

 Stream only works with a user with the Administrator role, not the Connector role even with the preselected `"Connect and consume the platform streams (/stream, /stream/live)" ` capability.

It doest get the data from the Stream. Please check the screenshots with the connector role.

## Environment

1. Docker deployment
2. OpenCTI version: 5.3.17

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an account with the Connector role attached.
2. Use the Token ID from the account created in the Splunk Connector.
3. Start the connector. 

## Screenshots
With the connector role, we can see how it doesn't get any data.
![image](https://user-images.githubusercontent.com/30608998/196455967-e20eb90b-9dae-4d50-bb34-aea85f3d2a40.png)

With the administrator role, how it gets the data from the stream.
![image](https://user-images.githubusercontent.com/30608998/196456907-ace72968-1f98-4cca-9cce-51d6a80cc28f.png)

**Comment by richard-julien** [comment]
Hi, for now im not able to reproduce.
Can you copy paste:
- a screenshot of the live stream configuration (edition view)
- a screenshot of the role configuration (edition view)
- a screenshot of your user configuration (roles and groups)

Thanks.

**Comment by RaulSokolova** [comment]
Hi @richard-julien ,

I apologized for missing some steps to reproduce it correctly. As you mentioned, it works as long we don't set filters, after setting the filters in Stream Live using an Admin account, that's when it does not work. Please see the screenshots below.

1. Stream configuration.

![image](https://user-images.githubusercontent.com/30608998/196711138-b7e3e47e-9746-44b4-ba28-f167f4c45193.png)

2. Role configuration.

![image](https://user-images.githubusercontent.com/30608998/196711623-c06b7109-4dd5-4064-b1f8-de868e349926.png)


3. User configuration.

 ![image](https://user-images.githubusercontent.com/30608998/196711292-6420f6f8-53a9-46b9-9897-d8e11ed05ff0.png)

4. Connector configuration
![image](https://user-images.githubusercontent.com/30608998/196710928-d17fb222-7b5c-4dd6-9df4-b991bda87f23.png)

**Comment by richard-julien** [comment]
Can you also add the full configuration of the stream (screenshot after click on edit button).
Thanks

**Comment by RaulSokolova** [comment]
Is it this one? 

![image](https://user-images.githubusercontent.com/30608998/196731567-9edef6db-387d-42eb-8f10-7b9bb7dd475d.png)

**Comment by richard-julien** [comment]
Ok thanks.

Can you try to login to the interface with the connector credential, and then go with chrome to the URI /stream/[ID_OF_LIVE_STREAM] and see what happens? Thanks

**Comment by RaulSokolova** [comment]
Hi @richard-julien , truly apologize but I'm not able to reproduce it anymore. Closing this, thank you for your support!
