### ISSUE TITLE
In Small screens, in "entities" section, the top menu can be hidden by the search bar

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2472]
## Description

In Small screens, in "entities" section, the top menu can be hidden by the search bar

**Comment by nino-filigran** [comment]
@SamuelHassine I'm closing this ticket since with the new UI refactor, menus are only on the left and breadcrumbs are also added to ease navigation. If you disagree with this, please feel free to re-open the ticket.
