### ISSUE TITLE
Enhance global search and advanced search capabilities (not operator, fuzzy, double quotes, etc.)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2486]
## Use case

The current search surrounds with wilcard, except when surrounding with double quotes. Analyse a more "natural" way to search with full text and eventually have more advanced (documented) syntax.

See: https://filigran.atlassian.net/browse/OCTI-62.

**Comment by SamuelHassine** [comment]
Also:

Uses semantic indexing or boolean operators, and includes fuzzy searches, “not” operator.

**Comment by 2xyo** [comment]
Some UX inspiration for advanced search  https://www.elastic.co/blog/whats-new-kibana-ml-cloud-8-7-0#the-support-of-the-creation-of-complex-filter-relationships-(ands-/-ors)  🙂

**Comment by SamuelHassine** [comment]
@Jipegien: we need to discuss this one.

**Comment by Jipegien** [comment]
Need to re-scope after the work done on filters.

**Comment by SamuelHassine** [comment]
Duplicate of #2686.
