### ISSUE TITLE
Opencti Elasticsearch won't work

### ISSUE THREAD

**Issue by InnerFireZ** [LuatixHQ/opencti#2491]
## Description
I update OpenCTI to last version 5.3.17 using portainer and now the web service is down, and I cannot reach the page on port 8080. I recrate the container (opencti_elasticsearch_1) but the problem persists.

From logs on opencti_opencti_1 container i got:

`{"category":"APP","error":{"context":{"category":"technical","error":"connect ECONNREFUSED 172.18.0.24:9200","http_status":500,"reason":"ElasticSearch seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:54:53)\n    at /opt/opencti/build/src/database/engine.js:161:15\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:151:3)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:117:3)\n    at boot (/opt/opencti/build/src/boot.js:10:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-26T12:49:21.284Z","version":"5.3.17"}

{"category":"APP","error":{"context":{"category":"technical","error":"connect ECONNREFUSED 172.18.0.24:9200","http_status":500,"reason":"ElasticSearch seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:54:53)\n    at /opt/opencti/build/src/database/engine.js:161:15\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:151:3)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:117:3)\n    at boot (/opt/opencti/build/src/boot.js:10:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-10-26T12:49:35.291Z","version":"5.3.17"}`

**From elasicsearch container (opencti_elasticsearch_1) logs i got:**

`{"type": "server", "timestamp": "2022-10-26T12:49:36,268Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "starting ..." }
{"type": "server", "timestamp": "2022-10-26T12:49:36,300Z", "level": "INFO", "component": "o.e.x.s.c.f.PersistentCache", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "persistent cache index loaded" }
{"type": "server", "timestamp": "2022-10-26T12:49:36,301Z", "level": "INFO", "component": "o.e.x.d.l.DeprecationIndexingComponent", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "deprecation component started" }
{"type": "server", "timestamp": "2022-10-26T12:49:36,535Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "publish_address {172.18.0.24:9300}, bound_addresses {0.0.0.0:9300}" }
{"type": "server", "timestamp": "2022-10-26T12:49:37,607Z", "level": "WARN", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]" }
{"type": "server", "timestamp": "2022-10-26T12:49:37,609Z", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "cluster UUID [ftLJA2_JQQ-sfXPEa66L7g]" }
{"type": "server", "timestamp": "2022-10-26T12:49:37,843Z", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "elected-as-master ([1] nodes joined)[{77bc58d0816d}{nOAflhWkTw6unT35rxl2FQ}{XDx3yKuQSsKa3_k6kjEgOA}{172.18.0.24}{172.18.0.24:9300}{cdfhimrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1705, version: 50833, delta: master node changed {previous [], current [{77bc58d0816d}{nOAflhWkTw6unT35rxl2FQ}{XDx3yKuQSsKa3_k6kjEgOA}{172.18.0.24}{172.18.0.24:9300}{cdfhimrstw}]}" }
{"type": "server", "timestamp": "2022-10-26T12:49:38,017Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "master node changed {previous [], current [{77bc58d0816d}{nOAflhWkTw6unT35rxl2FQ}{XDx3yKuQSsKa3_k6kjEgOA}{172.18.0.24}{172.18.0.24:9300}{cdfhimrstw}]}, term: 1705, version: 50833, reason: Publication{term=1705, version=50833}" }
{"type": "server", "timestamp": "2022-10-26T12:49:38,331Z", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "publish_address {172.18.0.24:9200}, bound_addresses {0.0.0.0:9200}", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:38,349Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "started", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:38,787Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "license [53879da5-067d-4690-a792-5b84815b3b6a] mode [basic] - valid", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:38,789Z", "level": "INFO", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "Active license is now [BASIC]; Security is disabled", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:38,789Z", "level": "WARN", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "deprecation.elasticsearch", "timestamp": "2022-10-26T12:49:38,793Z", "level": "CRITICAL", "component": "o.e.d.x.s.s.SecurityStatusChangeListener", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "The default behavior of disabling security on basic licenses is deprecated. In a later version of Elasticsearch, the value of [xpack.security.enabled] will default to \"true\" , regardless of the license level. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security, or explicitly disable security by setting [xpack.security.enabled] to false in elasticsearch.yml", "key": "security_implicitly_disabled", "category": "security", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:38,804Z", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "recovered [20] indices into cluster_state", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:39,584Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "updating geoip databases", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:39,586Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "fetching geoip databases overview from [https://geoip.elastic.co/v1/database?elastic_geoip_service_tos=agree]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:39,706Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "downloading geoip database [GeoLite2-Country.mmdb] to [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-Country.mmdb.tmp.gz]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:39,710Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "downloading geoip database [GeoLite2-ASN.mmdb] to [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-ASN.mmdb.tmp.gz]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:39,711Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "downloading geoip database [GeoLite2-City.mmdb] to [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-City.mmdb.tmp.gz]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:40,372Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "successfully reloaded changed geoip database file [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-Country.mmdb]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:40,402Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "successfully reloaded changed geoip database file [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-ASN.mmdb]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:40,869Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "geoip database [GeoLite2-ASN.mmdb] is up to date, updated timestamp", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:41,452Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "geoip database [GeoLite2-City.mmdb] is up to date, updated timestamp", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:41,721Z", "level": "INFO", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "geoip database [GeoLite2-Country.mmdb] is up to date, updated timestamp", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:42,570Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "successfully reloaded changed geoip database file [/tmp/elasticsearch-7504636972868123710/geoip-databases/nOAflhWkTw6unT35rxl2FQ/GeoLite2-City.mmdb]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:49:43,923Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[opencti_history-000001][0]]]).", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "deprecation.elasticsearch", "timestamp": "2022-10-26T12:50:47,648Z", "level": "CRITICAL", "component": "o.e.d.a.s.IndicesOptions", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices.", "key": "ignore_throttled_param", "category": "api", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:52:33,989Z", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "[gc][177] overhead, spent [436ms] collecting in the last [1s]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }
{"type": "server", "timestamp": "2022-10-26T12:55:12,103Z", "level": "INFO", "component": "o.e.m.j.JvmGcMonitorService", "cluster.name": "docker-cluster", "node.name": "77bc58d0816d", "message": "[gc][335] overhead, spent [250ms] collecting in the last [1s]", "cluster.uuid": "ftLJA2_JQQ-sfXPEa66L7g", "node.id": "nOAflhWkTw6unT35rxl2FQ"  }`

## Environment

1. OS  Ubuntu 21.10
2. OpenCTI version: 5.3.17
4. Other environment details: using portainer to manage docker containers

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on update the stack and wait to complete.
2. check for web service on port 8080

## Expected Output

To run web service on port 8080 like before.

**Comment by InnerFireZ** [comment]
It's fixed by himself... just start working...

**Comment by alirf81** [comment]
Hi @innerfirebg , could you explain how you solved it? I have the same issue.

**Comment by InnerFireZ** [comment]
> Hi @innerfirebg , could you explain how you solved it? I have the same issue.

I just wait copule of minuts after i start the containers... that's it.
