### ISSUE TITLE
Allow filtering for labels in the Global>Activity>Vulnerability list custom dashboard

### ISSUE THREAD

**Issue by 11eddie** [LuatixHQ/opencti#2496]
In the custom dashboard for "reports>activity>list", we can filter for labels, this would also be useful to implement in the vulnerabilities list custom dashboard.

i.e. If I add the label "Affects_us" to several CVE's and I only want to see CVE's in a list with the label "Affects us".

**Current Workaround:**

At present, the same can be achieved by navigating to Arsenal>Vulnerabilities>Filtering via Label

## Proposed Solution
The option to filter based on labels in dashboards is a very useful component of OpenCTI and should be implemented on as many dashboards as is practical

Activity Reports:
![image](https://user-images.githubusercontent.com/17877791/198070708-e15b671e-1534-4d21-82d6-f1704231e1af.png)

![image](https://user-images.githubusercontent.com/17877791/198071232-9a8dfee3-de52-4455-a1ce-89842ed16f1b.png)

**Comment by SamuelHassine** [comment]
Related to #1348

**Comment by 11eddie** [comment]
Also, if i create several report filters i.e. filter reports for cisco talos, filter for microsoft, filter for mitre corp, and i save the dashboard page and come back, they all revert to the last filter i set. I.e. all 4 saved dashboards will filter for mitrecorp if this was the last change i made. The same happens if i refresh the page.

It would be nice if they persisted
