### ISSUE TITLE
Email Ingest

### ISSUE THREAD

**Issue by jcandiat** [LuatixHQ/opencti#2498]
## Use case

the possibility of email ingestion would provide us with the possibility of entering the notified communications, with the possibility of detecting the IOC contained in it.

Maybe configure an email account, so that it reads the emails from that account, defining capture parameters to define which emails to capture.

**Comment by Jipegien** [comment]
from #3793 : 
Open a case by email (IMAP integration)

**Comment by nino-filigran** [comment]
Linked to: https://github.com/OpenCTI-Platform/opencti/issues/3111, as a result, I'm closing this ticket to ensure we just keep track of a single ticket on this topic. Feel free to reopen it if needed
