### ISSUE TITLE
Refactor RBAC / seggregation to put everything under the "group"

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2512]
## Use case

Today, markings are mapped on group and role are mapped on users. This is not standard and complexify a lot the management because generally, directories (LDAP/AD) are only based on groups. The purpose of this use case is to simplify the management to put attach roles to groups and not users.

After the refactor, it should be possible to have more metadata on the role to allow default dashboards / default hidden entities.

Current situation:

* Users has roles
* Users are part of groups
* Groups are granted to markings

Modification:

* Users are part of groups (no change)
* Roles are attributed to groups (change)
* Groups are granted to markings (no change)

Add:

* Role can have a default dashboard (can be overridden by the user)
* Role can have default hidden entities (overriding the default platform settings)

**Comment by richard-julien** [comment]
Take a look also to https://github.com/OpenCTI-Platform/opencti/issues/2419
