### ISSUE TITLE
5.3.17 - An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

### ISSUE THREAD

**Issue by Bakacolak** [LuatixHQ/opencti#2518]
**Description**
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

**Environment**
OS docker
OpenCTI version: 5.3.17
OpenCTI client: frontend

**Steps to create the smallest reproducible scenario:**
create a user with group dedicated with the same permission of default
login with this user and try to open events, or observation -> Error : An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

Actual Output
Additional information
Firefox Console error:
index-7FCE4QW3.js:7 Error
    at Object.render (index-7FCE4QW3.js:7566:42254)
    at r.render (index-7FCE4QW3.js:41:44743)
    at d4n (index-7FCE4QW3.js:5:66655)
    at Est (index-7FCE4QW3.js:5:66448)
    at _dt (index-7FCE4QW3.js:9:9950)
    at vdt (index-7FCE4QW3.js:9:975)
    at iJa (index-7FCE4QW3.js:9:898)
    at rpe (index-7FCE4QW3.js:9:746)
    at k4n (index-7FCE4QW3.js:7:11094)
    at index-7FCE4QW3.js:5:39595
c4n @ index-7FCE4QW3.js:7
o.componentDidCatch.r.callback @ index-7FCE4QW3.js:7
Sst @ index-7FCE4QW3.js:5
nJa @ index-7FCE4QW3.js:7
lJa @ index-7FCE4QW3.js:9
k6.unstable_runWithPriority @ index-7FCE4QW3.js:1
YQ @ index-7FCE4QW3.js:5
WQ @ index-7FCE4QW3.js:9
k4n @ index-7FCE4QW3.js:7
(anonyme) @ index-7FCE4QW3.js:5
k6.unstable_runWithPriority @ index-7FCE4QW3.js:1
YQ @ index-7FCE4QW3.js:5
$1t @ index-7FCE4QW3.js:5
dL @ index-7FCE4QW3.js:5
EW @ index-7FCE4QW3.js:7
enqueueSetState @ index-7FCE4QW3.js:5
jie.setState @ index-7FCE4QW3.js:1
(anonyme) @ index-7FCE4QW3.js:41
(anonyme) @ index-7FCE4QW3.js:41
error @ index-7FCE4QW3.js:41
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
e.error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
e._error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
error @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:54
Promise.then (asynchrone)
subscribe @ index-7FCE4QW3.js:54
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
n @ index-7FCE4QW3.js:11
Cii @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:12
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
e.fetch @ index-7FCE4QW3.js:41
e8t @ index-7FCE4QW3.js:41
e @ index-7FCE4QW3.js:41
X1t @ index-7FCE4QW3.js:5
Est @ index-7FCE4QW3.js:5
_dt @ index-7FCE4QW3.js:9
vdt @ index-7FCE4QW3.js:9
iJa @ index-7FCE4QW3.js:9
rpe @ index-7FCE4QW3.js:9
k4n @ index-7FCE4QW3.js:7
(anonyme) @ index-7FCE4QW3.js:5
k6.unstable_runWithPriority @ index-7FCE4QW3.js:1
YQ @ index-7FCE4QW3.js:5
$1t @ index-7FCE4QW3.js:5
dL @ index-7FCE4QW3.js:5
EW @ index-7FCE4QW3.js:7
enqueueSetState @ index-7FCE4QW3.js:5
jie.setState @ index-7FCE4QW3.js:1
(anonyme) @ index-7FCE4QW3.js:41
(anonyme) @ index-7FCE4QW3.js:41
e._onQueryDataAvailable @ index-7FCE4QW3.js:41
next @ index-7FCE4QW3.js:41
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
e.next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
e._handleNext @ index-7FCE4QW3.js:12
(anonyme) @ index-7FCE4QW3.js:11
Qri @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
e._schedule @ index-7FCE4QW3.js:11
e._next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
next @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:54
Promise.then (asynchrone)
subscribe @ index-7FCE4QW3.js:54
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
n @ index-7FCE4QW3.js:11
Cii @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:12
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
(anonyme) @ index-7FCE4QW3.js:11
gti @ index-7FCE4QW3.js:11
e.subscribe @ index-7FCE4QW3.js:11
e.fetch @ index-7FCE4QW3.js:41
e8t @ index-7FCE4QW3.js:41
e @ index-7FCE4QW3.js:41
X1t @ index-7FCE4QW3.js:5
Est @ index-7FCE4QW3.js:5
_dt @ index-7FCE4QW3.js:9
vdt @ index-7FCE4QW3.js:9
iJa @ index-7FCE4QW3.js:9
rpe @ index-7FCE4QW3.js:9
k4n @ index-7FCE4QW3.js:7
(anonyme) @ index-7FCE4QW3.js:5
k6.unstable_runWithPriority @ index-7FCE4QW3.js:1
YQ @ index-7FCE4QW3.js:5
$1t @ index-7FCE4QW3.js:5
dL @ index-7FCE4QW3.js:5
d1t @ index-7FCE4QW3.js:9
eZa @ index-7FCE4QW3.js:5

Case similar to https://github.com/OpenCTI-Platform/opencti/issues/2347

**Comment by SamuelHassine** [comment]
Hello @Bakacolak,

Do you have more information in your browser console? Because it seems the actual error stack is missing here.

Thanks a lot.

Kind regards,
Samuel

**Comment by Bakacolak** [comment]
Hello
![image](https://user-images.githubusercontent.com/11148432/200281122-340a21ef-d481-4dd0-9467-dfe846266edd.png)

Thks for the work

**Comment by Bakacolak** [comment]
The problem was on my reverse proxy,
i close
