### ISSUE TITLE
Ability to request takedowns

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2528]
## Use case

Ability to request takedowns

**Comment by Jipegien** [comment]
Is it not covered by RFT Cases?

**Comment by nino-filigran** [comment]
Closing this ticket for now since we have RFT cases. @Jipegien or @SamuelHassine you might find that I closed this "too easily", if it's the case, please re-open ticket with a comment.

**Comment by Jipegien** [comment]
I cannot say what the issue initially covered. But there is currently something lacking about RFT. We cannot initiate actual request for takedown to the hosting provider.
