### ISSUE TITLE
Be able to hide background tasks screen using RBAC capabilities

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2535]
## Use case

Be able to hide background tasks screen using RBAC capabilities

**Comment by richard-julien** [comment]
New capability @SamuelHassine or on existing one?

**Comment by SamuelHassine** [comment]
Short: existing. Background tasks are displayed even if a user has only the "Access knowledge" capability. We should hide the section if you don't have at least update knowledge privileges.
