### ISSUE TITLE
Events/Incidents/Observables. Doesn't display more than 25 observables.

### ISSUE THREAD

**Issue by RaulSokolova** [LuatixHQ/opencti#2550]
## Description

The observables window inside of an incident doesn't display more than 25 observables. This is an issue if an analyst is trying to review all of them.

## Environment

1. Demo instance
2. OpenCTI version: 5.4.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an incident
2. Add or import more than 25 observables 

## Expected Output

Being able to see all of them.

## Actual Output

Only displays 25 observables.

**Comment by richard-julien** [comment]
Hi, thanks for the report, even if the 5.4.0 is still under active development.
Just tried to do it on the demo (https://demo.opencti.io/dashboard/events/incidents/4f9d7684-e61f-4b35-9f7b-39fb6f06e4ca/knowledge/overview?) without problem.
Do you talk about this screen?

**Comment by RaulSokolova** [comment]
Thanks @richard-julien... Missed mentioning one step. 
Please select the entities view on the top right and click one by one. You will see we are only able to select 25 manually, since thats only what is displaying. 

![image](https://user-images.githubusercontent.com/30608998/201140224-98e01e42-54ab-4fdf-8a6b-f380ebfb4e5c.png)
