### ISSUE TITLE
Customizable confidence scale

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2555]
## Use case

Customizable confidence scale.

Confidence = 0 to 100

Currently, the confidence labels "low / medium / high etc" are hardcoded. Be able to customize the confidence labels in the settings of the platform for intervals:

* 1 to 10: xxx
* 10 to 30: xxx

etc.

**Comment by richard-julien** [comment]
Also take a look to https://github.com/OpenCTI-Platform/opencti/issues/2772
