### ISSUE TITLE
[BUG/FEATURE] 5.4.0 Upgrade Revoking Indicators w/o valid_until set on upgrade

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2578]
## Description

On upgrade to 5.4.0 any indicators that dont have `valid_until` set on them (Misp connector does this for example), have valid_until set to the value of valid_from. So upon upgrading to 5.4.0 I had %95 off the indicators get revoked this morning

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 8
2. OpenCTI version: 5.4.0
3. OpenCTI client: N/A
5. Other environment details: Kubernetes Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import the attached bundle on 5.3.xx
2. Upgrade to 5.4.0
3. valid_until should be stomped and set to valid_from
4. Indicator is revoked :/

## Expected Output

So 2 things here:

1. Bug on upgrade
2. Can we make a platform setting for default indicator lifetime, and write that to the stix json if not set?

## Additional information

test bundle
```json 
{
    "id": "bundle--4e645764-5b96-4a59-92e4-70115ff5db57",
    "objects": [
        {
            "confidence": 100,
            "created": "2022-11-18T21:37:13.708996Z",
            "description": ":|",
            "id": "indicator--f9a864d7-7e97-4e91-91ff-035ce82177f9",
            "indicator_types": [
                "malicious-activity"
            ],
            "modified": "2022-11-18T21:37:13.708996Z",
            "name": "1.1.1.1",
            "pattern": "[ipv4-addr:value = '1.1.1.1']",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "spec_version": "2.1",
            "type": "indicator",
            "valid_from": "2022-11-18T13:37:13Z",
            "x_opencti_detection": true,
            "x_opencti_main_observable_type": "IPv4-Addr",
            "x_opencti_score": 100
        }
    ],
    "type": "bundle"
}
```

**Comment by richard-julien** [comment]
Just tested with the 5.4.0 and for me the behavior is still the same.
When valid_until is not specified we compute a date based on the valid from. Today is + 1 month.
With your bundle freshly imported it looks like this.

![image](https://user-images.githubusercontent.com/285555/202847608-c517fb26-c8b4-4b9f-8ec9-3fb5187704fe.png)

If i understand well, 1 month looks to short for you and you want this period to be customizable in the platform config?

**Comment by MaxwellDPS** [comment]
Hey @richard-julien so 2 things there:
1. importing to 5.4.0 works fine. in has to be imported on 5.3.X and then upgraded to 5.4.0
2. Yes, making the 1 month default customizable 

Thanks!

**Comment by MaxwellDPS** [comment]
Hey @richard-julien to follow up on this, this seems like this may actually be a symptom of something else. 

All newly imported Indicators from the MISP connector following the upgrade are revoked on import. I did notice that [here](https://github.com/OpenCTI-Platform/connectors/blob/8385f027c50da3e2bf482bade09f280f4f71f397/external-import/misp/src/misp.py#L1002) that connector is not setting `valid_until` on the indicator. 

So it seems like there is something wonky on the indicator import, leading to the `valid_until` to be set to to the `valid_from` in certain instances

**Comment by richard-julien** [comment]
Ok for the 1 month default customizable improvement.
For the connector side, its normal that valid_until is not set. The api auto compute the valid_until only if is not set.

`importing to 5.4.0 works fine. in has to be imported on 5.3.X and then upgraded to 5.4.0`
We have no migration from 5.3.x to 5.4.0 that change the value of any indicators, i really dont think that upgrading is not responsible for the revokation.

Do you think you can give a clear repro case ? Like exporting the MISP event or sending me the bundle generated by the MISP connector?

Thanks

**Comment by MaxwellDPS** [comment]
Hey @richard-julien 

Here is a stix indicator imported from the a MISP feed this morning, but you'll see the platform set the `valid_until` to `created` and did not keep the `valid_from` in the stix bundle. But it was revoked as soon as it was imported

```json
{
    "id": "indicator--<REMOVED>",
    "spec_version": "2.1",
    "revoked": true,
    "confidence": 80,
    "created": "2022-11-21T23:53:14.000Z",
    "modified": "2022-11-22T00:07:39.458Z",
    "pattern_type": "stix",
    "pattern_version": "2.1",
    "pattern": "[ipv4-addr:value = '<REMOVED>']",
    "name": "<REMOVED>",
    "description": "login attempt (via fail2ban)",
    "indicator_types": [
        "malicious-activity"
    ],
    "valid_until": "2022-11-21T23:53:14.000Z",
    "x_opencti_score": 60,
    "x_opencti_detection": false,
    "x_opencti_main_observable_type": "IPv4-Addr",
    "labels": [
        "clear"
    ],
    "x_opencti_id": "<REMOVED>",
    "type": "indicator",
    "created_by_ref": "identity--<REMOVED>",
    "object_marking_refs": [
        "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
    ]
}
```

**Comment by nimaike** [comment]
I have the same issue.

In my case, under the following conditions, valid_until was not set correctly:
1. only `valid_from` is set. (`valid_until` is not specified.)
2. `object_marking_refs` has some value.

Here is a stix bundle that reproduces the situation. (Just added object_marking_refs to https://github.com/OpenCTI-Platform/opencti/issues/2578#issue-1455861887 test_bundle)

```json
{
    "id": "bundle--4e645764-5b96-4a59-92e4-70115ff5db57",
    "objects": [
        {
            "confidence": 100,
            "created": "2022-11-18T21:37:13.708996Z",
            "description": ":|",
            "id": "indicator--f9a864d7-7e97-4e91-91ff-035ce82177f9",
            "indicator_types": [
                "malicious-activity"
            ],
            "modified": "2022-11-18T21:37:13.708996Z",
            "name": "1.1.1.1",
            "pattern": "[ipv4-addr:value = '1.1.1.1']",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "spec_version": "2.1",
            "type": "indicator",
            "valid_from": "2022-11-18T13:37:13Z",
            "x_opencti_detection": true,
            "x_opencti_main_observable_type": "IPv4-Addr",
            "x_opencti_score": 100,
    		"object_marking_refs": [
        "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
    ]
        }
    ],
    "type": "bundle"
}
```

**Comment by richard-julien** [comment]
Ok, quick status.

* Invalid valid_until
There is a bug when markings or killChain are in the indicator that prevent the creation or put the valid_until to current date. Will be fixed.

* empty valid_from in bundle
If the bundle doesnt specify a valid_from et will be set to the valid_until date. Of course depending of the "Invalid valid_until" problem, it can also be set to current date.

**Comment by richard-julien** [comment]
Job done to resolve the situation.

* valid_from
Will be compute in this order.
valid_from > if not found > created > if not found > current date.

* valid_until
Computed from the valid_from + a statically configured ttl (for now, will be added in the platform settings later).
Depending of the max TLP and main observable type.

```
export const DEFAULT_INDICATOR_TTL = 365;
const INDICATOR_TTL_DEFINITION: Array<TTL_DEFINITION> = [
  {
    target: ['IPv4-Addr', 'IPv6-Addr'],
    definition: {
      [MARKING_TLP_CLEAR]: 30,
      [MARKING_TLP_GREEN]: 30,
      [MARKING_TLP_AMBER]: 30,
      [MARKING_TLP_AMBER_STRICT]: 60,
      [MARKING_TLP_RED]: 60,
    },
    default: 60
  },
  {
    target: ['File'],
    default: DEFAULT_INDICATOR_TTL
  },
  {
    target: ['Url'],
    definition: {
      [MARKING_TLP_CLEAR]: 60,
      [MARKING_TLP_GREEN]: 60,
      [MARKING_TLP_AMBER]: 180,
      [MARKING_TLP_AMBER_STRICT]: 180,
      [MARKING_TLP_RED]: 180,
    },
    default: 180
  },
];
```
