### ISSUE TITLE
[BUG] OIDC reports invalid token from ADFS 

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2579]
## Environment

1. OS (where OpenCTI server runs): CentOS Stream 8
2. OpenCTI version: 5.4.0
3. OpenCTI client: Frontend
4. Other environment details: Kubernetes Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup OIDC /w ADFS
2. Attempt Login
3. 🔥 

## Expected Output

A successful login flow, or even better error handling

## Actual Output

**Note:** It is causing a continer crash
```json
{
    "auth": {
        "ip": "<REMOVED>",
        "referer": "https://adfs.<REMOVED>/"
    },
    "category": "AUDIT",
    "level": "error",
    "message": "LOGIN",
    "resource": {
        "error": "invalid_token (MSIS9921: Received invalid UserInfo request. Audience 'microsoft:identityserver:<REMOVED(OIDC ClientID)>' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'.)",
        "provider": "oic"
    },
    "timestamp": "<REMOVED>",
    "version": "5.4.0"
}
{
    "auth": {
        "ip": "<REMOVED>",
        "referer": "https://adfs.<REMOVED>/"
    },
    "category": "AUDIT",
    "level": "info",
    "message": "LOGIN",
    "resource": {
        "provider": "oic"
    },
    "timestamp": "<REMOVED>",
    "version": "5.4.0"
}
TypeError: Cannot read properties of undefined (reading 'id')
    at buildSessionUser (/opt/opencti/build/src/domain/user.js: 579: 14)
    at internalAuthenticateUser (/opt/opencti/build/src/domain/user.js: 676: 23)
    at processTicksAndRejections (node:internal/process/task_queues: 95: 5)
```

**Comment by richard-julien** [comment]
Error handling will be improved.
For the invalid_token, dont know that to do, looks like a config problem between the client and the server

**Comment by MaxwellDPS** [comment]
Yeah, @richard-julien enhanced logging wold be awesome. It sounds like the config issue may be client side, based on what I am seeing from the backend

**Comment by SamuelHassine** [comment]
Hello,

We are fixing the container crash and uncatched exception. But the original OIDC error is still valid and seems to be linked to a configuration problem.

Kind regards,
Samuel
