### ISSUE TITLE
[BUG][5.4.0] Custom SAML config options dont seem to be passed to passportjs

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2580]
## Description

After upgrading to 5.4.0, I can no longer specify custom config options for passport-saml, like `disableRequestedAuthnContext`, or `authnContext `

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 8
2. OpenCTI version: 5.4.0
3. OpenCTI client: frontend
4. Other environment details: Kubernetes Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. set `PROVIDERS__SAML__CONFIG__DISABLEREQUESTEDAUTHNCONTEXT=true`
2. Verify the SAML Request still contains the `samlp:RequestedAuthnContext ` key(s)

## Expected Output

Pass extra config to the upstream auth library

## Additional information

This breaks ADFS if you cant use `PasswordProtectedTransport`

**Comment by richard-julien** [comment]
Not sure its a new behavior of the 5.4.0.
Custom properties are well understand only if you use the configuration file. If you use the env vars, unfortunalty its impossible for OpenCTI to convert the variable to the right case.

`DISABLEREQUESTEDAUTHNCONTEXT must be translated to disableRequestedAuthnContext`

For this problem we have rebind the main variables to support the case changes.
Actuel rebinded variables

```
  saml_callback_url: 'callbackUrl',
  identifier_format: 'identifierFormat',
  entry_point: 'entryPoint',
  private_key: 'privateKey',
  signing_cert: 'signingCert',
  signature_algorithm: 'signatureAlgorithm',
  digest_algorithm: 'digestAlgorithm',
  want_assertions_signed: 'wantAssertionsSigned',
```

By splitting the word and introducing _ we are able to correctly translate.

For me we need to add the variable binding you need. Thats not a lot of work and can be done in the 5.4.1 if you can validate that im not misenderstanding your problem.
And if yes the full list of options that could be interesting to rebind :)

**Comment by MaxwellDPS** [comment]
Hey @richard-julien, yes, if possible can y'all please add `disableRequestedAuthnContext` to the map, I think thats all I need to get ADFS working. That is odd however, as I was able to set those config options in 5.3.X via the env

Thanks! :)

**Comment by MaxwellDPS** [comment]
@richard-julien is there an easy way to override this in the interim to re-enable SSO. Can I create a config file with just that `disableRequestedAuthnContext` and set everything else via the env?

**Comment by MaxwellDPS** [comment]
Just as an update for anyone in the same spot, It looks like you can configure just this one flag via the config.json

Not Ideal, but you can set `CONF: /path/to/config.json`
then set the contents to 
```json
{
  "providers": {
    "saml": {
      "config": {
         "disableRequestedAuthnContext": true
      }
    }
  }
}
      
```
