### ISSUE TITLE
[back/front] Be able to use negative operator in filters

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2588]
## Use case

Allow filtering of Indicators (and other types), by objects that dont contain certain labels. This way you could make a feed and filter out any Indicator with the label "safelist" for example

## Current Workaround

None that I'm aware of

## Proposed Solution

Allow an "Excluded Labels" filter on feeds

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
Linked to #2507.

**Comment by SamuelHassine** [comment]
Linked to #1528.
