### ISSUE TITLE
[BUG] Setting the maxmemory flag on Redis, causes the platform pods to crash loop once Redis reaches max memory

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2603]
## Description

Setting the `maxmemory` flag on redis, causes the platform pods to crash loop once redis reaches max memory

```
ReplyError: OOM command not allowed when used memory > 'maxmemory'.
    at parseError (/opt/opencti/build/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/opencti/build/node_modules/redis-parser/lib/parser.js:302:14)
 ```

## Environment

1. OS (where OpenCTI server runs): Cent OS Stream 8
2. OpenCTI version: 5.4.0
3. OpenCTI client: frontend
4. Other environment details: Kubernetes Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start Redis server with `redis-server --maxmemory 6442450944 --maxmemory-policy volatile-lru`
2. Wait for memory usage to balloon in the rdis container 
3. Once it levels of at ~6GB (Or what you set above ^), the platform pods will start to crash after some time

## Expected Output

Better management ofd Redis connection handing. Ive got kinda a catch 22 here:

On one hand, If I dont set the maxmemeory Kubernetes will OOMKill Redis (This its self is fine), but when that happens OpenCTI Stalls, CPU usage drops to near 0 and the WebUI locks up

On the other hand If I cap Redis, Kubernetes wont OOMKill it, but the OpenCTI platform pods will throw the error in this issue and crash.

So since clustering isnt supported, this makes it where the platform is requiring manual interaction to keep running every 12-36 hours

## Actual Output

```
ReplyError: OOM command not allowed when used memory > 'maxmemory'.
    at parseError (/opt/opencti/build/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/opt/opencti/build/node_modules/redis-parser/lib/parser.js:302:14)
 ```

## Additional information

Please let me know if I can help testing here, as this is a big stability issue at the moment

**Comment by richard-julien** [comment]
Redis store essential data for opencti. (sessions, work statistics,...) and in top 1 the stream.
Every action is stored in the stream to be used by internal component and connectors.
So every action will take some memory in Redis.
If you want to control the size of your redis you need to control the depth of the stream though the opencti trimming option.
You need to know that if you size too short and you have some component like inference engine that need to recover some stream data you will lose some events. In resume, more memory = more stream depth = more security.

**Comment by MaxwellDPS** [comment]
@richard-julien Ok, yeah thats what I was thinking. But so far It has eaten 10GB of memory, as of <10 hours ago it was using 5GB. I really dont think it has ingested enough data to really explain the increase. Should the data in the store not age off? This seems to be fast un-capped growth.
![image](https://user-images.githubusercontent.com/11069376/203668005-be8b1bc3-0cb8-44a4-9606-327fd89db713.png)

**Comment by MaxwellDPS** [comment]
@richard-julien this seems to be a major issue atm, I cant keep the platform alive >24 Hr even with 24GB of RAM on Redis

**Comment by richard-julien** [comment]
You can directly check what is contained in your redis with redissinsight, but as i explained redis is currently supporting a specific set of data (work tracking, user sessions and stream).
Have you setup the trimming option as mentionned in my previous comment?

**Comment by MaxwellDPS** [comment]
Hey @richard-julien, I have not set trimming, but again at this time there is little user activity in the platform, and not a lot of data syncing. I did more testing and in < 16 hours Redis ate 24GB of memory. again no users active in the platform, and minimal data ingest, and no streams configured. This seems like a platform bug

**Comment by richard-julien** [comment]
We need to take a look about what is currently taking space in your redis.
I can recommand to use redisinsight that will provide you a nice UI to explore the current redis data and try to find that keys or stream are currently taking so much space.

**Comment by MaxwellDPS** [comment]
Hey Richard, I am still workin on getting the redisinsight tool and will post back once I have that done. Still working on this, just didnt want to leave you hanging.

Is there a way todo this with out the redisinsight tool if I am unable to get that approved?

**Comment by MaxwellDPS** [comment]
Hey @richard-julien, was just able to run redis-insights and it looks like the usage is solely the `stream.opencti` key. It is currently at 16GB (was cleared < 24 HR ago)  with 15,488 Entries. I dont have any streams configured as of now

**Comment by MaxwellDPS** [comment]
@richard-julien Since I posted that last message Redis memory usage by the stream.opencti key is now 4GB (I cleared it). Thats like 1GB an hour in new memory thats not being freeded.

I cant even get the client to load it to see the age of the oldest key

**Comment by MaxwellDPS** [comment]
@richard-julien is there any other troubleshooting I can do here?

**Comment by richard-julien** [comment]
Do you ingest in your platform a feed that give you artifact with payload bin ?

**Comment by MaxwellDPS** [comment]
It does not as of now

> Do you ingest in your platform a feed that give you artifact with payload bin ?

**Comment by MaxwellDPS** [comment]
@richard-julien, Do yall have any update here?

**Comment by CauchY75** [comment]
Same problem here.

**Comment by MaxwellDPS** [comment]
Hey @CauchY75, do you mind posting some debug info... Trying to build my case lol

**Comment by richard-julien** [comment]
After a lot of testing, this situation can occured if you have a connector that update big data (like massive report) too often. (Like a connector that resend every time this report with a different id, or an external-reference with no consitant data). After each update the data is push in the stream so you can have a massive update of the memory usage when this situation occured. 

Today its a bit hard to identify the culprit. You need to lookup the stream and try to identify the messages that continouesly occured and:
- Check in the origin part where the data come from. 
- Check the patch to understand the kind of data that change in the event
With this information we should be able to fix the connector responsible of the situation.

**Comment by MaxwellDPS** [comment]
@richard-julien Thanks!!! 

I can actually verify this, yesterday I upgraded 5.4.1 -> 5.5.2. [Connectors #958](https://github.com/OpenCTI-Platform/connectors/issues/958) is still affecting myself, I had a major backlog occur in the span of 8 hours from the misp connector after upgrading. Then I saw the redis behavor again, which I had fixed previously by limiting how often Misp can run, but that seems to not be helping at this point. 

Can y'all re-open [Connectors #958](https://github.com/OpenCTI-Platform/connectors/issues/958) as thats the root cause on my platform.

@CauchY75 what connectors are you using?

**Comment by richard-julien** [comment]
Hi @MaxwellDPS , any possibility for you to share an access to your MISP in order for us to reproduce your problem? We can sign any NDA is necessary.

**Comment by MaxwellDPS** [comment]
To update here 5.5.4 has caused a sharp increase in AMQP throughput for us from ~3 Acks/Sec -> 30+ Acks/sec as of 5.5.4 
Redis memory has also leveled off at < 400MB for us over the last 12 Hr post upgrade

**Comment by SamuelHassine** [comment]
Solved thanks to Redis trimming and enhancement on connectors which does not generate predictive IDs.

**Comment by symsal** [comment]
I have the same problem with 5.6.0 version.
