### ISSUE TITLE
Unable to downgrade Elasticsearch to 7.6.0

### ISSUE THREAD

**Issue by gh-xj** [LuatixHQ/opencti#2605]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I googled the issue and didn't find anything relevant
- [x] I went through old GitHub issues and couldn't find anything relevant

## Description

I'm trying to downgrade "@elastic/elasticsearch" to from "8.4.2" to version "7.6.0", but the app is not able to start, and seem the `listEntities` function is broken after downgrade.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
Mac OS 13.0.1

2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
OpenCTI 5.4.0

3. OpenCTI client: { e.g. frontend or python }
python

4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. in `package.json` change the version of "@elastic/elasticsearch" to "7.6.0"
2. run `yarn install && yarn build:dev`
3. run `yarn serv`
4. error:

```txt
{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2022-11-23T22:04:05.474Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2022-11-23T22:04:05.475Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[SEARCH ENGINE] Elasticsearch (8.4.2) client selected / runtime sorting enabled","timestamp":"2022-11-23T22:04:06.936Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2022-11-23T22:04:06.937Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2022-11-23T22:04:07.885Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2022-11-23T22:04:12.583Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2022-11-23T22:04:13.984Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2022-11-23T22:04:13.986Z","version":"5.4.0"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Initializing cache manager","timestamp":"2022-11-23T22:04:13.987Z","version":"5.4.0"}
{"category":"APP","error":{"context":{},"message":"Cannot read properties of undefined (reading 'body')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'body')\n    at /Users/bytedance/codebase/OpenCTI-Platform/opencti/opencti-platform/opencti-graphql/src/database/engine.js:1749:38\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at reloadStatuses (/Users/bytedance/codebase/OpenCTI-Platform/opencti/opencti-platform/opencti-graphql/src/manager/cacheManager.ts:20:23)\n    at workflowStatuses (/Users/bytedance/codebase/OpenCTI-Platform/opencti/opencti-platform/opencti-graphql/src/manager/cacheManager.ts:28:20)\n    at Object.start (/Users/bytedance/codebase/OpenCTI-Platform/opencti/opencti-platform/opencti-graphql/src/manager/cacheManager.ts:62:47)\n    at boot (/Users/bytedance/codebase/OpenCTI-Platform/opencti/opencti-platform/opencti-graphql/src/boot.js:12:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2022-11-23T22:04:14.934Z","version":"5.4.0"}
```

**Comment by richard-julien** [comment]
Hi @xj-m , as elastic has change is result format in newest version, we adapt the code to follow this change. Downgrade the elastic client in the source code is not possible.

**Comment by gh-xj** [comment]
> Hi @xj-m , as elastic has change is result format in newest version, we adapt the code to follow this change. Downgrade the elastic client in the source code is not possible.

Got it, so to use 7.6.0 Elasticsearch client (I have to use it since internally the company only provide 7.x ES cluster), I have to use old version of openCTI? Before this commit?
https://github.com/OpenCTI-Platform/opencti/commit/86db51f15c8fed9717c5425442e14fae4fd5ed4d

**Comment by richard-julien** [comment]
Have you tried to just use the current opencti with elastic 7.6.0. We not officially support it and i strongly encourage you to upgrade the elasticsearch cluster of your company but its not impossible that the client 8.x still support elastic 7.

**Comment by gh-xj** [comment]
> Have you tried to just use the current opencti with elastic 7.6.0. We not officially support it and i strongly encourage you to upgrade the elasticsearch cluster of your company but its not impossible that the client 8.x still support elastic 7.

Thanks! Downgrade the package will cause error, and after modify  the function `oebp` in `src/database/engine.js` to `return queryResult.body;` solved the issue
