### ISSUE TITLE
[Feature] Add UI element to indicate which connector the object was imported by

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2618]
## Use case

When handling many feeds, it can be useful to know what came from a specific connector.

## Current Workaround

None that I am aware of

## Proposed Solution

add a `x-opencti-ingest-connector` and display in the ui for objects imported via connector

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by richard-julien** [comment]
5.4.1 introduce this concept. Creator of the information is now written in the database. To achieive your use case you need to create a specific user for each connector.

**Comment by MaxwellDPS** [comment]
> 5.4.1 introduce this concept. Creator of the information is now written in the database. To achieive your use case you need to create a specific user for each connector.

Awesome! Does that work if local auth is disabled?

**Comment by richard-julien** [comment]
Yes, its not related to the type of auth
