### ISSUE TITLE
[Feature] Rework of Filter.js

### ISSUE THREAD

**Issue by Kedae** [LuatixHQ/opencti#2621]
We need to rework some code of the Filters, mostly on the ['fromId', 'toId', ...] part. 
The useSearchEngines should be rewritten, SearchScope should use the entityTypesList in a most efficient way and the duplicated code part for  ['fromId', 'toId', ...] are mutualized and rework to be working.

**Comment by RomuDeuxfois** [comment]
Referring discussion : https://github.com/OpenCTI-Platform/opencti/pull/2610
