### ISSUE TITLE
SSDEEP hashes stored in lowercase

### ISSUE THREAD

**Issue by fscc-samiR** [LuatixHQ/opencti#2626]
## Description

Storing SSDEEP hashes with file observables in OpenCTI turns the hashes into lowercase.
This is a problem as those should be case sensitive.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Store SSDEEP into a file observable with the stix hases structure.
2. SSDEEP is stored in lowercase format and exported out in lowercase.

Tested on platform version 5.3.17

**Comment by czechnology** [comment]
To clarify, we have observed this when sending data to OpenCTI as STIX2 bundles through the worker. Not possible to do this via UI in this version.
