### ISSUE TITLE
This page is not found on the OpenCTI application

### ISSUE THREAD

**Issue by bigverm23** [LuatixHQ/opencti#2653]
## Description

Two distinct errors occur when clicking through the application: page is not found AND An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS Ubuntu 22.10 docker 20.10.17, build 100c701
2. OpenCTI version: 5.4.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Knowledge
2. Overview
3. Malware
4. Click Malware name
5. Click Knowledge and errors produce

## Expected Output

Expected to load visual context for section clicked

## Actual Output

An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Screenshots (optional)
The only error that continuously pops up is  `2022-12-16T17:22:12.463153280Z (node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

**Comment by SamuelHassine** [comment]
Hello @bigverm23,

Can you please share the logs of your brower dev tool console when the error occurs?

Thanks!

Kind regards,
Samuel

**Comment by bigverm23** [comment]
will pulll those tonight, is it possible it's just a caching issue?

**Comment by bigverm23** [comment]
Error logs from Chrome attached

[opencti-1671725735485.log](https://github.com/OpenCTI-Platform/opencti/files/10288431/opencti-1671725735485.log)
