### ISSUE TITLE
Can't access to my reports

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#2669]
## Description

The analysis tab doesn't show the list of the reports (cf. picture)

## Environment

1. OS (where OpenCTI server runs): MacOS 12.6.2
2. OpenCTI version: OpenCTI 5.5.0
3. OpenCTI client: Firefox 108.0.1
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the OpenCTI UI with Firefox
2. Click on Analysis / Reports on the left

## Expected Output

List of the reports stored in the OpenCTI Platform

## Actual Output

Cf. picture

## Additional information

The problem happened after the update of OpenCTI from 5.4.1 version to 5.5.0 version

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/68632445/209113110-3a858e53-a8c0-4b3d-bb14-d6358d732b82.png)

**Comment by SamuelHassine** [comment]
Hello @JeromeSRT,

Can you please share any relevant logs? We need:

* The logs of your browser console dev tools
* The logs of the platform container when you try to access to your data.

Kind regards,
Samuel

**Comment by JeromeSRT** [comment]
Hello @SamuelHassine

I have a manual deployment of OpenCTI, I don't use Docker container.

I extracted some logs from the Firefox console, but I'm sure it will help you.

Best regards, Jerome


Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/1/1.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/2/1.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/1/0.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/2/0.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/1/2.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/2/2.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/0/1.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/3/1.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/0/0.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/3/0.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/0/2.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/3/2.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/3/0.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/0/2.png front-NHAZL3Z3.js:868:139050
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://map.opencti.io/styles/luatix-dark/2/3/2.png front-NHAZL3Z3.js:868:139050
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177
TypeError: r.template is null
    SLa http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:36842
    g9n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:6
    H6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    V6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    dvi http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    tTe http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    Bfn http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    q6t http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:8
    O8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
    k8n http://127.0.0.1:4000/static/js/front-NHAZL3Z3.js:1
front-NHAZL3Z3.js:8:177

​

**Comment by JeromeSRT** [comment]
Sometimes, I have this error message in the logs of my OpenCTI platform : 

> (node:2149) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by JeromeSRT** [comment]
Below, you will find information from the browser console : 

> 16:28:06.688 1671722886688	addons.xpi	WARN	Checking /Applications/Firefox.app/Contents/Resources/distribution/extensions for addons
> 16:28:09.077 TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource. TopSitesFeed.jsm:208
> 16:28:09.182 Experiment dap-telemetry-first-ingress-test has unknown featureId: dapTelemetry RemoteSettingsExperimentLoader.jsm:490
>     _validateBranches resource://nimbus/lib/RemoteSettingsExperimentLoader.jsm:490
>     updateRecipes resource://nimbus/lib/RemoteSettingsExperimentLoader.jsm:341
>     AsyncFunctionNext self-hosted:807
> 16:28:09.264 Structured Ingestion ping failure with error: error PingCentre.jsm:136
>     sendStructuredIngestionPing resource:///modules/PingCentre.jsm:136
> 16:28:09.475 NetworkError when attempting to fetch resource. ASRouter.jsm:124:8
>     reportError resource://activity-stream/lib/ASRouter.jsm:124
>     _remoteSettingsLoader resource://activity-stream/lib/ASRouter.jsm:329
>     InterpretGeneratorResume self-hosted:1819
>     AsyncFunctionThrow self-hosted:811
> 16:28:09.490 Structured Ingestion ping failure with error: error 2 PingCentre.jsm:136
>     sendStructuredIngestionPing resource:///modules/PingCentre.jsm:136
> 16:28:09.534 BackgroundUpdate: _reasonsToNotScheduleUpdates: Failed to check for Maintenance Service Registry Key: [Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIUpdateProcessor.getServiceRegKeyExists]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource://gre/modules/BackgroundUpdate.jsm :: _reasonsToNotScheduleUpdates :: line 255"  data: no] BackgroundUpdate.jsm:257
> 16:28:09.534 1671722889534	addons.repository	ERROR	Error in addon metadata check: GET https://services.addons.mozilla.org/api/v4/addons/search/?guid=%40unitedstatesenglishdictionary%2Cmarcoagpinto%40mail.telepac.pt%2Clangpack-en-GB%40firefox.mozilla.org%2Clangpack-en-US%40firefox.mozilla.org%2Cdefault-theme%40mozilla.org%2Cfirefox-compact-light%40mozilla.org%2Cfirefox-compact-dark%40mozilla.org%2Cfirefox-alpenglow%40mozilla.org%2Cgoogle%40search.mozilla.org%2Cwikipedia%40search.mozilla.org%2Cbing%40search.mozilla.org%2Cddg%40search.mozilla.org%2Cebay%40search.mozilla.org%2Cqwant%40search.mozilla.org%2Camazon%40search.mozilla.org%2Caddons-search-detection%40mozilla.com%2Celemental-bold-colorway%40mozilla.org%2Cplaymaker-soft-colorway%40mozilla.org%2Cplaymaker-balanced-colorway%40mozilla.org%2Cplaymaker-bold-colorway%40mozilla.org%2Cexpressionist-balanced-colorway%40mozilla.org%2Cexpressionist-soft-colorway%40mozilla.org%2Cexpressionist-bold-colorway%40mozilla.org%2Cvisionary-balanced-colorway%40mozilla.org%2Cvisionary-soft-colorway%40mozilla.org%2Cvisionary-bold-colorway%40mozilla.org%2Cactivist-soft-colorway%40mozilla.org%2Cactivist-balanced-colorway%40mozilla.org%2Cactivist-bold-colorway%40mozilla.org%2Cdreamer-soft-colorway%40mozilla.org%2Cdreamer-balanced-colorway%40mozilla.org%2Cdreamer-bold-colorway%40mozilla.org%2Cinnovator-soft-colorway%40mozilla.org%2Cinnovator-bold-colorway%40mozilla.org%2Cinnovator-balanced-colorway%40mozilla.org&lang=en-US failed Log.sys.mjs:719
>     append resource://gre/modules/Log.sys.mjs:719
>     log resource://gre/modules/Log.sys.mjs:375
>     error resource://gre/modules/Log.sys.mjs:383
>     _getFullData resource://gre/modules/addons/AddonRepository.jsm:514
>     InterpretGeneratorResume self-hosted:1819
>     AsyncFunctionThrow self-hosted:811
> 16:29:06.822 1671722946822	Toolkit.Telemetry	WARN	TelemetryStorage::_scanArchive - have seen this id before: 229c6408-ee49-4527-b1a0-f394a0758e00, overwrite: false
> 16:34:53.755 Missing resource in locale en-GB: devtools/client/toolbox.ftl
> 16:34:53.918 Unknown property ‘-moz-border-radius’.  Declaration dropped. codemirror.css:244:22
> Elements matching selector: .CodeMirror pre.CodeMirror-line, .CodeMirror pre.CodeMirror-line-like
> NodeList []
> 16:37:14.336 POSThttps://incoming.telemetry.mozilla.org/submit/firefox-desktop/baseline/1/622e6d9e-da11-4285-9674-02b85c1fe358
> [HTTP/2 200 OK 496ms]
> 
> 16:37:14.409 POSThttp://ocsp.digicert.com/
> [HTTP/1.1 200 OK 96ms]
> 
> 16:37:14.815 POSThttps://incoming.telemetry.mozilla.org/submit/firefox-desktop/newtab/1/252796a0-dce8-4cc0-aebd-fcd7ade41010
> [HTTP/2 200 OK 369ms]
> 
> 16:37:15.186 POSThttps://incoming.telemetry.mozilla.org/submit/firefox-desktop/background-update/1/4873cfef-bdb4-46af-a545-b6bcc7b2137d
> [HTTP/2 200 OK 191ms]
> 
> 16:37:15.381 POSThttps://incoming.telemetry.mozilla.org/submit/firefox-desktop/baseline/1/b5868189-301b-43f5-bbe7-7f693b3a9d35
> [HTTP/2 200 OK 203ms]
> 
> 16:37:15.588 POSThttps://incoming.telemetry.mozilla.org/submit/firefox-desktop/events/1/80d2bdd0-6e9d-497b-b2a3-aabb8c134555
> [HTTP/2 200 OK 518ms]
>

**Comment by SamuelHassine** [comment]
@Archidoit : repro case: 

- Delete a status template that is actually used in a report
- Go on reports
- Go on incidents

node.template is null.

All pages are broken.

To be sure to break everything, just delete all status templates in the admin.
