### ISSUE TITLE
Ability to expand by External Reference in Investigations

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2673]
## Use case

Observe if objects are related by the fact that they share the same external reference(s)

## Current Workaround

None, due to #2672 

## Proposed Solution

Allow ability to expand on external references in investigations page

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
External References are already expanded when selecting "All types of entity".

@team: Add the capability to choose "External Reference" in the entity type list when double clicking on a node.

**Comment by securitiz** [comment]
I'd like to revisit #2237 as well - expanding only on labels would be very helpful as well

**Comment by nino-filigran** [comment]
Given that this feature is present (to only expand on an external ref), I'm closing this ticket. If you do not agree with this, or if I misunderstood your request, please feel free to re-open this ticket.
