### ISSUE TITLE
Can't install/start OpenCTI 5.5.1

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#2690]
## Description

Can't install/start OpenCTI 5.5.1

## Environment

1. OS (where OpenCTI server runs): MacOS 12.6.2
2. OpenCTI version: OpenCTI 5.5.1
3. OpenCTI client: Firefox
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. tar xvfz opencti-release-5.5.1.tar.gz => OK
2. pip3 install -r src/python/requirements.txt => OK
3. yarn install
4. yarn serv

- 

- ## Expected Output

## Actual Output

**Output yarn install** 
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.2 [5bd70] doesn't provide @types/node (p94346), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.2 [5bd70] doesn't provide ts-node (p5d017), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-codegen/cli@npm:2.16.2 [5bd70] doesn't provide typescript (pa40d0), requested by cosmiconfig-typescript-loader
➤ YN0002: │ @graphql-tools/graphql-tag-pluck@npm:7.4.2 [3e5f4] doesn't provide @babel/core (ped9b4), requested by @babel/plugin-syntax-import-assertions
➤ YN0002: │ graphql-config@npm:4.3.6 [6b5c1] doesn't provide @types/node (p1def7), requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.6 [6b5c1] doesn't provide @types/node (pa530a), requested by ts-node
➤ YN0002: │ graphql-config@npm:4.3.6 [6b5c1] doesn't provide typescript (p6815f), requested by cosmiconfig-typescript-loader
➤ YN0002: │ graphql-config@npm:4.3.6 [6b5c1] doesn't provide typescript (p13d4c), requested by ts-node
➤ YN0002: │ opencti-graphql@workspace:. doesn't provide @aws-sdk/abort-controller (p3cec6), requested by @aws-sdk/lib-storage
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (pebcd9) with version 16.6.0, which doesn't satisfy what graphql-import and some of its descendants request
➤ YN0060: │ opencti-graphql@workspace:. provides graphql (p2c3b2) with version 16.6.0, which doesn't satisfy what merge-graphql-schemas and some of its descendants request
➤ YN0002: │ opencti-graphql@workspace:. doesn't provide webpack (p25690), requested by ts-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 268ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable-ts@npm:0.8.21 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 902ms
➤ YN0000: ┌ Link step
➤ YN0008: │ esbuild@npm:0.15.18 must be rebuilt because its dependency tree changed
➤ YN0008: │ node-calls-python@patch:node-calls-python@npm%3A1.7.4#./patch/node-calls-python-1.7.4.patch::version=1.7.4&hash=719dfd&locator=opencti-graphql%40workspace%3A. must be rebuilt because its dependency tree changed
➤ YN0008: │ esbuild@npm:0.16.12 must be rebuilt because its dependency tree changed
➤ YN0008: │ protobufjs@npm:7.1.1 must be rebuilt because its dependency tree changed
➤ YN0008: │ @apollo/protobufjs@npm:1.2.6 must be rebuilt because its dependency tree changed
➤ YN0008: │ @apollo/protobufjs@npm:1.2.7 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js-pure@npm:3.27.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ es5-ext@npm:0.10.62 must be rebuilt because its dependency tree changed
➤ YN0008: │ protobufjs@npm:7.1.2 must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 6s 805ms
➤ YN0000: Done with warnings in 9s 188ms

**Output yarn serv**
TypeError: Tvs.PyInterpreter is not a constructor
    at new Interpreter (/Users/Jerome/Applications/OpenCTI/opencti/build/node_modules/node-calls-python/index.js:45:19)
    at /Users/Jerome/Applications/OpenCTI/opencti/build/node_modules/node-calls-python/index.js:169:10
    at /Users/Jerome/Applications/OpenCTI/opencti/build/back.js:1:410
    at Object.<anonymous> (/Users/Jerome/Applications/OpenCTI/opencti/build/src/python/pythonBridge.js:3:34)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

**Comment by Aspidoquelona** [comment]
Probably a yarn rebuild is needed. See: https://github.com/OpenCTI-Platform/opencti/issues/2608

**Comment by JeromeSRT** [comment]
@Aspidoquelona,
Thank you for your help. I achieved to install and to start OpenCTI 5.5.1.
Have a nice day.
