### ISSUE TITLE
Add dst_ref and src_ref properties in networktraffic or networktrafficadd object.

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#2695]
Hi, it would be interesting to have dst_ref and src_ref properties in network-traffic object.
Either that or find a way so we can store that information in a stix2.1 compliant way.

We are trying to acomplish something like this;
"type": "network-traffic",
 "spec_version": "2.1",
 "id": "network-traffic--53e0bf48-2eee-5c03-8bde-ed7049d2c0a3",
 "src_ref": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",
 "dst_ref": "ipv4-addr--ffe65ce3-bf2a-577c-bb7e-947d39198637",
 "src_port": 24678,
 "dst_port": 80,
 "protocols": [
   "ipv4",
   "tcp",
   "http"
 ]
}

## If the feature request is approved, would you be willing to submit a PR?

Can't help with coding, but will be happy to test or help in any other way

**Comment by Jipegien** [comment]
From 4476 : 
**Network Traffic object:** https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_rgnc3w40xy

**Error:**
```
Traceback (most recent call last): File "/opt/opencti-worker/worker.py", line 224, in data_handler self.api.stix2.import_bundle_from_json( File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 209, in import_bundle_from_json return self.import_bundle( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2361, in import_bundle self.import_observable(item, update, types) File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 1007, in import_observable self.opencti.stix_nested_ref_relationship.create( File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_nested_ref_relationship.py", line 261, in create result = self.opencti.query( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 358, in query raise ValueError( ValueError: {'name': 'UnsupportedError', 'message': 'Cant add another relation on single ref'}
```

**Object submitted by connector:**
```
{"type": "bundle", "id": "bundle--01bad548-253b-4e83-ad3d-d06fcded03b8", "spec_version": "2.1", "x_opencti_seq": 4, "objects": [{"type": "network-traffic", "spec_version": "2.1", "id": "network-traffic--10f24956-90b4-4402-9a0d-6ff7a654ab39", "dst_ref": "ipv4-addr--0000000-90b4-4401-0000-6ff7a6540000", "protocols": ["tcp"], "object_marking_refs": ["marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"], "nb_deps": 4}]}
```

**Comment by Jipegien** [comment]
We need to:
- check which STIX attributes are missing in OpenCTI data model
- implement _ref as "nested object" as in other SDO/SCO of the data model
- add nested objects list and "+" button in the UI Overview of Network traffic

**Comment by Jipegien** [comment]
@AlexSanchezN Actually, the information is already store via nested_ref. To add dst & src, you must add it via the "Knowledge tab" of the Network traffic you've created. 
For ingestion process, dst & src are not properties but references.

**Comment by AlexSanchezN** [comment]
Thanks, @Jipegien 
We are interested in ingesting NetworkTraffic from external sources, and create new ones for those same sources.
We currently preprocess the bundles and we strip that info.
As soon as the new release is out, we will test.

**Comment by Jipegien** [comment]
Not sure here that the issue is solve the way you intended it @AlexSanchezN. Just checking here. 
As it is already possible to add dst and src as ref, we won't add them as properties.
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/338f19f7-ef96-498d-906e-08698d5fa6fc)

**Comment by AlexSanchezN** [comment]
OK. Nice to be able to add the IPs as nested relations.

Just to clarify: that does not follow the STIX standard... or am I missing something? 
I mean, we have no control over third party bundles. 
If those 3rd party bundles conform to the STIX standard (https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_rgnc3w40xy), then, as noted by @SYNchroACK in https://github.com/OpenCTI-Platform/opencti/issues/4476, that means that we can't ingest those bundles without preprocessing them. 
Should we be using a mixture of bundles + API to create the objects? (we've never added a nested relationship via bundle, I don't know if it is even possible)
I suppose those objects won't be shareable with anybody outside OpenCTI.

If that is the official position, it is OK with us, and we will adapt to it.
Maybe a clarification about what is not going to follow the official standard is needed. 
Or what will converge with the standard in the future, and some milestones? :-)

So, please take no offense, but we honestly think it should be possible to ingest data like the one in this examples that come from the official STIX documentation (first link above):

`Basic TCP Network Traffic

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",

  "value": "198.51.100.2"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--ff26c055-6336-5bc5-b98d-13d6226742dd",

  "value": "198.51.100.3"

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--2568d22a-8998-58eb-99ec-3c8ca74f527d",

  "src_ref": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",

  "dst_ref": "ipv4-addr--ff26c055-6336-5bc5-b98d-13d6226742dd",

  "protocols": [

    "tcp"

  ]

}

 

Basic HTTP Network Traffic

{

  "type": "domain-name",

  "spec_version": "2.1",

  "id": "domain-name--3c10e93f-798e-5a26-a0c1-08156efab7f5",

  "value": "example.com"

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--15a157a8-26e3-56e0-820b-0c2a8e553a2c",

  "dst_ref": "domain-name--3c10e93f-798e-5a26-a0c1-08156efab7f5",

  "protocols": [

    "ipv4",

    "tcp",

    "http"

  ]

}

 

Network Traffic with Netflow Data

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "value": "203.0.113.1"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--03b708d9-7761-5523-ab75-5ea096294a68",

  "value": "203.0.113.5"

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--630d7bb1-0bbc-53a6-a6d4-f3c2d35c2734",

  "src_ref": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "dst_ref": "ipv4-addr--03b708d9-7761-5523-ab75-5ea096294a68",

  "protocols": [

    "ipv4",

    "tcp"

  ],

  "src_byte_count": 147600,

  "src_packets": 100,

  "ipfix": {

    "minimumIpTotalLength": 32,

    "maximumIpTotalLength": 2556

  }

}

 

Basic Tunneled Network Traffic

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",

  "value": "198.51.100.2"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "value": "203.0.113.1"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--ffe65ce3-bf2a-577c-bb7e-947d39198637",

  "value": "203.0.113.2"

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--ac267abc-1a41-536d-8e8d-98458d9bf491",

  "src_ref": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",

  "dst_ref": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "src_port": 2487,

  "dst_port": 1723,

  "protocols": [

    "ipv4",

    "pptp"

  ],

  "src_byte_count": 35779,

  "dst_byte_count": 935750,

  "encapsulates_refs": [

    "network-traffic--53e0bf48-2eee-5c03-8bde-ed7049d2c0a3"

  ]

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--53e0bf48-2eee-5c03-8bde-ed7049d2c0a3",

  "src_ref": "ipv4-addr--4d22aae0-2bf9-5427-8819-e4f6abf20a53",

  "dst_ref": "ipv4-addr--ffe65ce3-bf2a-577c-bb7e-947d39198637",

  "src_port": 24678,

  "dst_port": 80,

  "protocols": [

    "ipv4",

    "tcp",

    "http"

  ],

  "src_packets": 14356,

  "dst_packets": 14356,

  "encapsulated_by_ref": "network-traffic--ac267abc-1a41-536d-8e8d-98458d9bf491"

}

 

Web traffic tunneled over DNS

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "value": "203.0.113.1"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--f2d3c796-6c1a-5c4f-8516-d4db54727f89",

  "value": "198.51.100.34"

}

 

{

  "type": "ipv4-addr",

  "spec_version": "2.1",

  "id": "ipv4-addr--bb884ffe-f2e4-56bb-a0c3-21f6711cb649",

  "value": "198.51.100.54"

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--b4a8c150-e214-57a3-9017-e85dfa345f46",

  "src_ref": "ipv4-addr--e42c19c8-f9fe-5ae9-9fc8-22c398f78fb7",

  "dst_ref": "ipv4-addr--f2d3c796-6c1a-5c4f-8516-d4db54727f89",

  "src_port": 2487,

  "dst_port": 53,

  "protocols": [

    "ipv4",

    "udp",

    "dns"

  ],

  "src_byte_count": 35779,

  "dst_byte_count": 935750,

  "encapsulates_refs": [

      "network-traffic--65a6016d-a91c-5781-baad-178cd55f01d4"

    ]

}

 

{

  "type": "network-traffic",

  "spec_version": "2.1",

  "id": "network-traffic--65a6016d-a91c-5781-baad-178cd55f01d4",

  "src_ref": "ipv4-addr--f2d3c796-6c1a-5c4f-8516-d4db54727f89",

  "dst_ref": "ipv4-addr--bb884ffe-f2e4-56bb-a0c3-21f6711cb649",

  "src_port": 24678,

  "dst_port": 443,

  "protocols": [

    "ipv4",

    "tcp",

    "ssl",

    "http"

  ],

  "src_packets": 14356,

  "dst_packets": 14356,

  "encapsulated_by_ref": "network-traffic--b4a8c150-e214-57a3-9017-e85dfa345f46"

}`

**Comment by Jipegien** [comment]
@SamuelHassine & @richard-julien what do you think about this situation? For me we are currently aligned with the STIX 2.1 spec but I probably miss something here.

**Comment by richard-julien** [comment]
We are aligned for what i know.
Can you share @AlexSanchezN the stix bundle file you try to inject instead of raw text in the ticket?
Thanks

**Comment by AlexSanchezN** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/4476

That issue was opened by another user, but is valid for us. The bundle he used is there.

{"type": "bundle", "id": "bundle--01bad548-253b-4e83-ad3d-d06fcded03b8", "spec_version": "2.1", "x_opencti_seq": 4, "objects": [{"type": "network-traffic", "spec_version": "2.1", "id": "network-traffic--10f24956-90b4-4402-9a0d-6ff7a654ab39", "dst_ref": "ipv4-addr--0000000-90b4-4401-0000-6ff7a6540000", "protocols": ["tcp"], "object_marking_refs": ["marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"], "nb_deps": 4}]}

Please note that our original post is about creating the Network Traffic objects via API.
Our needs have evolved since January, and we'd like to share network-traffic objects with other people also

**Comment by richard-julien** [comment]
Its always hard to reproduce with partial data. This bundle is not consistent, the dst_ref id is pointing an element that not exist in the bundle.

**Comment by AlexSanchezN** [comment]
OK. I'll get one of ours and get back

**Comment by richard-julien** [comment]
After building my own bundle looks like the situation is good and bad :)
- At creation, its working correctly
- At upsert/update -> {'name': 'UnsupportedError', 'message': 'Cant add another relation on single ref'}
So we are compliant but the bug in https://github.com/OpenCTI-Platform/opencti/issues/4476 is definitly not solved.
Will keep this one close and reopen the 4476

**Comment by AlexSanchezN** [comment]
[e4f2a4bc-4b3f-477c-8471-8b4e6cc29c2b.bundle.json](https://github.com/OpenCTI-Platform/opencti/files/13476872/e4f2a4bc-4b3f-477c-8471-8b4e6cc29c2b.bundle.json)
![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/753c8cd7-0d32-4085-8640-154745b4498d)


It fits with my scenario. That is the error also in our case. I can't test with 'live' data, so I created a new bundle
