### ISSUE TITLE
Automatically generate ID in external references

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2703]
## Use case

Automatically generate ID in external references

**Comment by Archidoit** [comment]
To do, in the 'create an external reference' form :
- move the field 'associated file' above the field 'description'
- translate the missing expressions 'Choisir un fichier' and 'Aucun fichier n'a été sélectionné'
- if the external Id is an empty string && a file is selected : fill the external id field with the file name
