### ISSUE TITLE
Incorrect values for Incident severity break incident listing in version 5.5.1

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#2711]
## Description

In version 5.5.1 when updating the severity of an Incident, the following choices are showed:
![image](https://user-images.githubusercontent.com/14950949/210825473-fbf31a35-9cdc-45bb-82a8-c95f56df6c8a.png)

choosing one of them (in my case **03 - high**) causes an error of GraphQL:
`GraphQLError: Enum "IncidentSeverity" cannot represent value: "03 - high"`

The error propagates into the listing view of the UI, making the view of the section **events** impossible.

I had to fix the stix object by searching its ID and then by changing the severity with the right value ("high" instead of "03 - high") to have the incident listing working again.

I suppose that the values of the combobox are not passed in the right way or that number listing (01, 02, ...) was not intended to be there.

## Environment

1. OS (where OpenCTI server runs): I'm using the official OpenCTI Docker Image
2. OpenCTI version: OpenCTI 5.5.1
3. OpenCTI client: frontend
4. Other environment details: /

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an incident
2. Set the severity of the incident
3. Go back to the Incident listing
4. Enjoy the broken listing

## Expected Output

The expected output should be the severity without the numeric identifier (eg "03 - high" should be "high")

## Actual Output

The severity is set in the wrong way, which causes the incident listing to break.

## Additional information

No additional information

**Comment by rgsax** [comment]
After some more research I found that the "wrong" values are located in the "Vocabularies" section of the "Labels & Attributes" Settings tab.

Changing the values of the category **incident_severity_ov** to
 - critical
 - high
 - medium
 - low

resolves the bug 👍

**Comment by richard-julien** [comment]
Thanks for the report. We need to remove the limitation on the graphql side.
