### ISSUE TITLE
Analyst Workbench does not appear to parse STIX Observables of type File 

### ISSUE THREAD

**Issue by gbikram** [LuatixHQ/opencti#2730]
## Description

`Observables` of type `Indicator` that are passed to the Analyst Validation Workbench as part of STIX bundles, are not extracted for validation. However, `File Entities` of type `Indicator` do seem yo work. I have been using the `ImportDocument` connector as well as a custom connector to test these uploads. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.10
2. OpenCTI version: OpenCTI 5.5.1
3. OpenCTI client: Front-end
4. Other environment details:

## Reproducible Steps
1. Launch the ImportDocument connector on a free-text file upload containing various IOCs. 
2. Open the generated STIX JSON within the Analyst Workbench. 
3. You should notice that file hashes are not present within the workbench. 
4. However, the generated STIX JSON file does appear to be containing file hashes as File observables, indicating that the ImportDocument connector is correctly parsing file hashes. 

## Expected Output
File observables should be present in Analyst Workbench > Observables. 

## Actual Output

No File Observables extracted within the Analyst Workbench

## Screenshots/Files
The ImportDocument connector is launched on the following free-text upload. 
```
65e939cf7642294d6fbfc3052ca8167c
065e07187b8452c44563d8f15858995d6845804a
992c8451e4bc512069fbad2320c6af9c32642cd50700e8b45717068746112d36
http://3.66.213.216:60782/
```

The connector generates the following STIX JSON which contains the File Observables:
```JSON
{
    "type": "bundle",
    "id": "bundle--110a7856-4c5b-40d8-aed1-fe7b9adad4f8",
    "objects": [
        {
            "type": "ipv4-addr",
            "spec_version": "2.1",
            "id": "ipv4-addr--049e503a-1306-5dad-93ae-9b40964a9627",
            "value": "3.66.213.216",
            "x_opencti_create_indicator": true
        },
        {
            "type": "file",
            "spec_version": "2.1",
            "id": "file--23aaec0a-818a-50b4-8eab-4cd2cbe03a4f",
            "hashes": {
                "MD5": "65e939cf7642294d6fbfc3052ca8167c"
            },
            "x_opencti_create_indicator": true
        },
        {
            "type": "file",
            "spec_version": "2.1",
            "id": "file--bd6fa599-28e1-5b39-b992-405c81cecb92",
            "hashes": {
                "SHA-1": "065e07187b8452c44563d8f15858995d6845804a"
            },
            "x_opencti_create_indicator": true
        },
        {
            "type": "url",
            "spec_version": "2.1",
            "id": "url--b5a90402-5edb-5c00-8aec-92f978a2d94c",
            "value": "http://3.66.213.216:60782/",
            "x_opencti_create_indicator": true
        },
        {
            "type": "report",
            "spec_version": "2.1",
            "id": "report--a9b817fc-d2ab-5afd-9ce3-e132d5b51027",
            "created": "2023-01-10T23:48:46.452307Z",
            "modified": "2023-01-10T23:48:46.452307Z",
            "name": "2023-01-10T16:12:42-05:00_global.txt",
            "description": "Automatic import",
            "report_types": [
                "threat-report"
            ],
            "published": "2023-01-10T23:48:46Z",
            "object_refs": [
                "ipv4-addr--049e503a-1306-5dad-93ae-9b40964a9627",
                "file--23aaec0a-818a-50b4-8eab-4cd2cbe03a4f",
                "file--bd6fa599-28e1-5b39-b992-405c81cecb92",
                "url--b5a90402-5edb-5c00-8aec-92f978a2d94c"
            ],
            "x_opencti_files": [
                {
                    "name": "2023-01-10T16:12:42-05:00_global.txt",
                    "data": "NjVlOTM5Y2Y3NjQyMjk0ZDZmYmZjMzA1MmNhODE2N2MKMDY1ZTA3MTg3Yjg0NTJjNDQ1NjNkOGYxNTg1ODk5NWQ2ODQ1ODA0YQo5OTJjODQ1MWU0YmM1MTIwNjlmYmFkMjMyMGM2YWY5YzMyNjQyY2Q1MDcwMGU4YjQ1NzE3MDY4NzQ2MTEyZDM2Cmh0dHA6Ly8zLjY2LjIxMy4yMTY6NjA3ODIv",
                    "mime_type": "application/pdf"
                }
            ]
        }
    ]
}
```

However, the workbench does not show any of the file observables. 
![image](https://user-images.githubusercontent.com/8872186/211688921-96864209-f2e1-4e68-b551-d87488d8d355.png)

## Workaround
I am currently using a custom connector to upload File observables as entities of type indicator.

**Comment by ckane** [comment]
Thanks, I believe this behavior is possibly also related to this other issue I opened in the connectors project
https://github.com/OpenCTI-Platform/connectors/issues/941
