### ISSUE TITLE
relationship_image relation only allows 1 relation

### ISSUE THREAD

**Issue by fscc-samiR** [LuatixHQ/opencti#2732]
## Description

Cyber observable relationship "relationship_image" from **file** to **process** only allows for single relationship per file.

This means that a single unique file observable can be only associated to a single process object as the image reference. A file should be allowed to be a reference image on multiple different process objects.

## Environment

OpenCTI version: 5.5.0

## Reproducible Steps

1. Create two process observables
2. Create a file observable
3. Create a nested relation from file to process observable with type: "relationship_image"
4. Create a second relation from the same file to another process with relation type: "relationship_image"
5. Receive error "Cant add another relation on single ref"

## Expected Output

Expect to be able to have a single file object as image reference for multiple process objects .

## Actual Output

Error "Cant add another relation on single ref"

**Comment by SamuelHassine** [comment]
Hello @fscc-samiR,

It seems to be compliant with the STIX standard, which allows only one image ref by process:

https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_99bl2dibcztv.

![image](https://user-images.githubusercontent.com/1334279/212060101-46eb8ad6-b3e6-4319-8759-2ab0cef0d74f.png)

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
@fscc-samiR you're right, we will take a look.
