### ISSUE TITLE
Report with large amount of entities causing crashes

### ISSUE THREAD

**Issue by rlynch-ironnet** [LuatixHQ/opencti#2737]
## Description

One of the AlienVault pulses `Malware - Malware Domain Feed V2 - November 03 2020` has over 80k IOCs, which has resulted in a report object in OpenCTI having the same amount of data. It's become too large to view in the OpenCTI app, and even Kibana throws errors if you don't use the dev tools to view it. 

This does not require going to the entities page of the report either, from the Chrome network debug, it looks like it may be related to the `ContainerHeaderObjectsQuery` GQL query, which was the only one that did not finish before an internal error occurred, followed shortly by the container itself going down. 

This may be related to #2493 

## Environment

1. OS (where OpenCTI server runs): AWS Fargate
2. OpenCTI version: 5.5.1
3. OpenCTI client: Frontend
4. Other environment details: n/a

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Make a report, add 80k indicators to it, try to view.

## Expected Output

Doesn't crash, maybe viewable with reduced information.

## Actual Output

Crash. 

## Additional information

n/a

**Comment by rlynch-ironnet** [comment]
To clarify, "rel_object.internal_id" had upwards of 267k items in it.

**Comment by SamuelHassine** [comment]
Hello @rlynch-ironnet,

We're well aware of the fact that such report can be sometimes difficult to display but this also depends on your Elastic config. Not directly linked to #2493 but yes the header query should be optimized as well at least to handle a fluid display of the report except the knowledge graph.

We will fix this asap.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Will be solved in #2493.
