### ISSUE TITLE
"Dashboard > Analysis > Notes" page shows an error message

### ISSUE THREAD

**Issue by Aspidoquelona** [LuatixHQ/opencti#2739]
## Description

Dashboard > Analysis > Notes page shows this error message

*Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.*

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
2. OpenCTI version: OpenCTI 5.5.2
3. OpenCTI client: frontend
4. Other environment details: manual installation

## Reproducible Steps

Accessing the Notes view causes the error.

## Expected Output

Dashboard > Analysis > Notes page must show the list of Note objects.

## Actual Output

No external reference is listed. The following message is shown instead:

*Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.*

## Additional information

Notes have neither dissapeared nor been deleted because if we open an entity (eg. a Report), we can see the Notes realated to the Report.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/119074626/212253544-76edeffa-5093-4c0b-b8cd-ab451f75cce2.png)

**Comment by SamuelHassine** [comment]
Hello @Aspidoquelona,

Can you please try to clear the cache / local storage of your browser and full-reload the page? If this is not working, can you please copy/paste here the output of your browser dev console log? 

Thanks!

Kind regards,
Samuel

**Comment by Aspidoquelona** [comment]
Clearing the browser's cache does not fix the error.

**Browser Console Log**
front-SCNPRCGI.js:8 Error
    at Object.render (front-SCNPRCGI.js:8453:44665)
    at a.render (front-SCNPRCGI.js:40:44414)
    at D8n (front-SCNPRCGI.js:8:6281)
    at i0t (front-SCNPRCGI.js:8:6073)
    at ppt (front-SCNPRCGI.js:8:45917)
    at dpt (front-SCNPRCGI.js:8:40591)
    at $bi (front-SCNPRCGI.js:8:40514)
    at vMe (front-SCNPRCGI.js:8:40362)
    at H8n (front-SCNPRCGI.js:8:36621)
    at opt (front-SCNPRCGI.js:8:35552)

L8n @ front-SCNPRCGI.js:8
o.componentDidCatch.a.callback @ front-SCNPRCGI.js:8
Gct @ front-SCNPRCGI.js:6
c0t @ front-SCNPRCGI.js:8
ipt @ front-SCNPRCGI.js:8
ipt @ front-SCNPRCGI.js:8
jbi @ front-SCNPRCGI.js:8
Hbi @ front-SCNPRCGI.js:8
TZ @ front-SCNPRCGI.js:8
opt @ front-SCNPRCGI.js:8
Imn @ front-SCNPRCGI.js:1
Mmn @ front-SCNPRCGI.js:1

**OpenCTI Log**
{"category":"APP","error":{"stacktrace":["Error: Cannot return null for non-nullable field Note.content.","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:594:13)","at executeField (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:635:12)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:584:23)","at executeField (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:635:12)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:584:23)","at /usr/local/opencti/build/node_modules/graphql/execution/execute.js:696:25","at Function.from (<anonymous>)","at completeListValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:676:34)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:607:12)","at completeValue (/usr/local/opencti/build/node_modules/graphql/execution/execute.js:584:23)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"NotesLinesPaginationQuery","operation_query":"query NotesLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:NotesOrdering$orderMode:OrderingMode$filters:[NotesFiltering]){...NotesLines_data_2wN0PW}fragment NoteLine_node on Note{id entity_type attribute_abstract content created note_types likelihood confidence createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}creator{id name}status{id order template{name color id}}workflowEnabled}fragment NotesLines_data_2wN0PW on Query{notes(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{id attribute_abstract content created createdBy{__typename __isIdentity:__typename id name entity_type}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}...NoteLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}","size":90,"time":24,"timestamp":"2023-01-13T12:16:13.005Z","type":"READ_ERROR","user":{"ip":"::ffff:127.0.0.1","referer":"https://opencti.rra.lan/dashboard/analysis/notes?","user_id":"HIDDEN FOR SECURITY REASONS"},"variables":{"count":25,"cursor":null,"filters":[],"orderBy":"created","orderMode":"desc","search":""},"version":"5.5.2"}

Thanks.

**Comment by Aspidoquelona** [comment]
**More info about this error**

The same errror occurs when calling "list()" from python, so it seems it is not browser-related.

*opencti_api_client.note.list()* or just only the first one: *opencti_api_client.note.list(first=1)*

.
.
.
ERROR:root:Cannot return null for non-nullable field Note.content.
Traceback (most recent call last):
  File "C:\Users\sdalva\Desktop\OPENCTI\notes.py", line 56, in <module>
    print(api.note.list(first=1))
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdalva\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycti\entities\opencti_note.py", line 265, in list
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdalva\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycti\api\opencti_api_client.py", line 326, in query
    raise ValueError(
ValueError: {'name': 'Cannot return null for non-nullable field Note.content.', 'message': 'Cannot return null for non-nullable field Note.content.'}
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\sdalva\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycti\connector\opencti_connector_helper.py", line 33, in killProgramHook
    os.kill(os.getpid(), signal.SIGKILL)
                         ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGKILL'. Did you mean: 'SIGILL'?

Original exception was:
Traceback (most recent call last):
  File "C:\Users\sdalva\Desktop\OPENCTI\notes.py", line 56, in <module>
    print(api.note.list(first=1))
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdalva\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycti\entities\opencti_note.py", line 265, in list
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdalva\AppData\Local\Programs\Python\Python311\Lib\site-packages\pycti\api\opencti_api_client.py", line 326, in query
    raise ValueError(
ValueError: {'name': 'Cannot return null for non-nullable field Note.content.', 'message': 'Cannot return null for non-nullable field Note.content.'}

**Comment by Aspidoquelona** [comment]
The problem seems to be due to the existence of a **NOTE** with a *NULL* value in a **REQUIRED** field. I don't know how this NOTE could have been created. My data comes both through the connectors and through the python client (pycti).

I have restored previous data from a backup and the error message no longer appears.

**Comment by SamuelHassine** [comment]
Hello,

Thanks for following up. Yes this is what the error indicated, but we're investigating how it happened because APIs are protected as well as Elastic updates. Still need testing on our side.

Kind regards,
Samuel

**Comment by Aspidoquelona** [comment]
Hello,

It's only a suggestion, but... could the error have occurred because an earlier version of the python client was used that does not make use of a new required attribute that exists in the current version?

Regards.
