### ISSUE TITLE
Incident/Knowledge/Observables once you select filter it provides an error

### ISSUE THREAD

**Issue by RaulSokolova** [LuatixHQ/opencti#2757]
## Description

We select filter in the Incident/Knowledge/Observables , which prompts an error

```
Error
An unknown error occurred. Please contact your administrator
```

## Environment

2. OpenCTI version: 5.5.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by SamuelHassine** [comment]
Hello @RaulSokolova,

I'm not able to reproduce, can you please share the log of your browser dev console and the log of your platform?

Thanks.

Kind regards,
Samuel

**Comment by RaulSokolova** [comment]
Hello @SamuelHassine ,

I'm able to reproduce it in Demo instance as well. See the screenshots below. 

![image](https://user-images.githubusercontent.com/30608998/213275340-9d559868-8f79-47d9-adce-df68cff4f706.png)


![image](https://user-images.githubusercontent.com/30608998/213274971-765243b6-d87f-49c2-ad5a-710b1416541d.png)


Thanks,
RS
