### ISSUE TITLE
Latitude/longitude values should stay float if updated

### ISSUE THREAD

**Issue by marieflorescontact** [LuatixHQ/opencti#2762]
## Description

On a Location type, update the latitude or the longitude turns the value into integer (should be kept as float)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new position with a latitude: 48.856614 and a longitude: 2.3522219
2. Open the update panel
3. Modify the latitude =>48.888888 and longitude =>4.5555555
4. Latitude is now eq to 48 and longitude eq to 4

**Comment by guys1444** [comment]
Hi , on what page ? Add a screenshot also please.
