### ISSUE TITLE
LDAP not functioning 

### ISSUE THREAD

**Issue by srobier** [LuatixHQ/opencti#2764]
## Description

When attempting to log into the OCTI UI using the LDAP configuration the docker container stops and restarts the opencti platform. No logs are captured.

## Environment

OS: LINUX (Centos7)
OCTI version: 5.5.2
OCTI client frontend
Other environment details: 
1. running HTTPS 8443
2. deployed using docker-compose.yml

  - PROVIDERS__LDAP__STRATEGY=LdapStrategy
  - PROVIDERS__LDAP__CONFIG__URL=ldap://LDAPserverIP:389
  - PROVIDERS__LDAP__CONFIG__BIND_DN=CN=ldapadm,OU=People,DC=opencti,DC=com
  - PROVIDERS__LDAP__CONFIG__BIND_CREDENTIALS=password
  - PROVIDERS__LDAP__CONFIG__SEARCH_BASE=OU=(objectClass=People)
  - PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=(cn={{username}})
  - PROVIDERS__LDAP__CONFIG__MAIL_ATTRIBUTE=userPrincipalName
  - PROVIDERS__LDAP__CONFIG__ACCOUNT_ATTRIBUTE=givenName
  - PROVIDERS__LDAP__CONFIG__ALLOW_SELF_SIGNED=true
  - PROVIDERS__LOCAL__STRATEGY=LocalStrategy

## Reproducible Steps

1. Have a LDAP server setup.
2. Have a LDAP client setup and running OCTI on same instance for simplicity.
3. Add LDAP config to OCTI deployment config.
4. Attempt login via OCTI UI dashboard with username and password.

## Expected Output

OCTI should reach out to LDAP server via the client and allow user access into the OCTI platform.

## Actual Output

The OCTI Platform container restarts on every attempt to authenticate via LDAP.

**Comment by richard-julien** [comment]
Hi @srobier , our current instances configured with LDAP are currently working.
Do you have any logs to help?

**Comment by srobier** [comment]
Hello Richard,
Currently the browser console displays "POST https://myiip/dnsname/graphql" net::ERR_EMPTY_RESPONSE. I understand what that error means, just not sure why when I run a ldapsearch query it returns the expected user data. See below for query run on LDAP server that is successful in returning user information:
ldapsearch -x uid=test@test.com -b dc=opencti,dc=com -H ldap://LDAPserverIP:389 -s sub "(objectClass=People)" givenName -D "cn=ldapadm,dc=opencti,dc=com" -W

**Comment by srobier** [comment]
**OCTI log** "{"auth":{"email": "testuserone","ip":"::ffff:7.211.0.218","referer":"http://opencti:8080/dashboard"},"category":"AUDIT","level":"error","message":"LOGIN","resource":{"provider":"ldapauth"}}"

**Comment by srobier** [comment]
Issue has been resolved.
