### ISSUE TITLE
[SSO] SAML SSO login overrides path to /dashboard

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2768]
## Description

If you goto a url and are not signed in, upon SSO, URL path is lost so you have to re-click the link after login

ie, if you have no session and navigate to
`https://opencti.<REMOVED>/dashboard/observations/observables/<REMOVED>`

After SSO you will load into 
`https://opencti.<REMOVED>/dashboard`

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 8
2. OpenCTI version: 5.4.1
3. OpenCTI client: Frontend
4. Other environment details: Kubernetes Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup SAML SSO
2. Log out of OCTI
3. Navigate directly to any object in OCTI
4. SSO Login to SAML
5. Sadness

## Expected Output

SSO redirect should preserve path

## Actual Output

SSO redirect overwrites path

## Additional information

N/A

**Comment by SamuelHassine** [comment]
Confirmed in our Filigran environment at filigran.opencti.io. SAML2 does not correctly redirect.

**Comment by LiamWBA** [comment]
Is this the same issue I am having? 

I have set up SAML2 using Azure AD. I can see my sign ins to the application succeeding in the sign in logs in AAD but when I complete the authentication process in OpenCTI I get redirected back to the login page. It's like nothing happened.

**Comment by MaxwellDPS** [comment]
> Is this the same issue I am having?
> 
> I have set up SAML2 using Azure AD. I can see my sign ins to the application succeeding in the sign in logs in AAD but when I complete the authentication process in OpenCTI I get redirected back to the login page. It's like nothing happened.

Hey @LiamWBA I dont beleve so, I think you will want to check your SAML flow in the dev tools. This issue is when you properly authenticate and are logged in it takes you to the main dashboard and stops the URL that you signed in on.

ie, if you have no session and navigate to
`https://opencti.<REMOVED>/dashboard/observations/observables/<REMOVED>`

After SSO you will load into
`https://opencti.<REMOVED>/dashboard`

**Comment by acm5708** [comment]
@MaxwellDPS Would you mind sharing how you successfully implemented your SSO implementation? I have followed all the documentation from docs.opencti.com and searched high and low and have yet to successfully get the SSO to work properly. Any help you can share would be greatly appreciated!

**Comment by MaxwellDPS** [comment]
Hey @acm5708,

Issuer will be the instance URL.
The call back is the issuer + `/auth/saml/callback`
Entry_point is your IDP. 
The cert is just the base64 of the pem, so remove the `--- Begin Cert ---` etc

I ened up having to add this to the config.json (cant set in env)
```json
{
        "providers": {
          "saml": {
            "config": {
                "disableRequestedAuthnContext": true,
                "signatureAlgorithm": "sha256",
                "digestAlgorithm": "sha256",
                "identifierFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
            }
          }
        }
      }
  
```
