### ISSUE TITLE
[Platform][5.5.2] Indicator valid_ date changes not reflected in stream

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#2773]
## Description

Upon updating from 5.4.1 -> 5.5.2, changes to the `valid_` dates are not reflecting in the Live Stream

## Environment

1. OS (where OpenCTI server runs): CentOS Stream8
2. OpenCTI version: 5.5.2
3. OpenCTI client: Frontend
4. Other environment details: Kube Deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create stream
2. update Indicator Valid date
3. Verify no stream activity

## Expected Output

An update event with the changes

## Actual Output

Nothing

## Additional information

N/A

**Comment by richard-julien** [comment]
Hi @MaxwellDPS , im not able to reproduce.
Can you share a screenshot of your live stream configuration ? And also the exact action you currenlty do. Thanks

**Comment by MaxwellDPS** [comment]
Hey @richard-julien,

I cant share a screen shot, but Live stream is configured as follows:

Groups limiting: None
Filters:
- Entity Type: [Indicator]
- Author: [Identity-1,Identity-2,Identity-3,Identity-4]

No action, just missing the event on the stream for the connector to process
