### ISSUE TITLE
Capability to add Indicator Decaying Tool

### ISSUE THREAD

**Issue by akshaysth** [LuatixHQ/opencti#2774]
## Use case

Currently, there's no mechanism in OpenCTI that allows for the decaying of Indicators. MISP released a tool that allows models to be created for decaying indicators.

## Current Workaround

None. This can only be performed outside of OpenCTI and change the score using the API.

## Proposed Solution

Create a tool that allows creating models and decaying STIX Indicators.

## Additional Information

+ https://github.com/MISP/misp-decaying-models
+ https://www.misp-project.org/misp-training/a.5-bis-decaying-indicators-light-version.pdf

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by guys1444** [comment]
can you show an example of using it with OpenCTI API?

**Comment by SamuelHassine** [comment]
Duplicate of #2859.
