### ISSUE TITLE
Segfault after manual install on RHEL 8.5

### ISSUE THREAD

**Issue by timebotdon** [LuatixHQ/opencti#2784]
## Prerequisites
- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
I'm trying to manually deploy OpenCTI 5.5.0 on a RHEL 8.5 server. 
Followed the manual steps for installing the frontend.  Upon running `yarn serv`, the nodejs process fails in a segmentation fault.

## Environment

1. OS (where OpenCTI server runs): RHEL 8.5
2. OpenCTI version: OpenCTI 5.5.0
3. OpenCTI client: Frontend
4. Other environment details:
- NodeJS 18
- Docker backend (Elk, redis, minio, rabbitmq)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `yarn install`
2. `yarn build`
3. `yarn serv` or `node build/back.js`

## Additional information
Tried the following troubleshooting steps:
- Rebooting does'nt help
- Remove `node_modules` and rebuild
- Run as a non-root user (tried a root user as well)
- Install an older NodeJS version (16)

I can provide the full install logs if necessary! Thank you!

**Comment by timebotdon** [comment]
Some contextual info: I'm upgrading my OpenCTI instance from 5.2.4. in RHEL.

Additional findings:
- OpenCTI version 5.3.17 works after manual deployment.
- noticed that the refactoring from 5.4.0 onwards doesn't work.
- No issue running 5.5.0 in Ubuntu.

**Comment by timebotdon** [comment]
Solved the issue after doing a fresh install of the RHEL OS and OpenCTI 5.7.6.

**Comment by timebotdon** [comment]
Need to reopen this because it seems that I'm still getting segfaults when upgrading from version 5.3.17 onwards.
- reinstalled OS (RHEL 8.4++)
- reinstalled NodeJS 16
- reinstalled Python

Getting this ```Segmentation Fault (core dumped)```
when running `node build/back.js` on any version later than 5.3.17.

**Comment by sbocahu** [comment]
Hi,
Did you run yarn build ?
what does _ldd build/nodecallspython*_ say (in opencti-graphql) ?
