### ISSUE TITLE
Performing bulk operations via Global Search results in an inaccurate scope being passed to the background job (May 2023 Update)

### ISSUE THREAD

**Issue by gbikram** [LuatixHQ/opencti#2787]
## Description

There appears to be a bug that could result in unexpected modifications made to all entities within OpenCTI. 

The bug is associated with bulk operations carried out via OpenCTI’s global/advanced search menus and has been detailed below. Launching an "Update" job on a subset of entities selected via the "select all" checkbox results in the background job being launched on all entities stored within the platform.

## Environment

1. OS: Linux openSUSE 6.1.8
2. OpenCTI version: 5.5.2
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. User conducts a search via the global search bar.

![image](https://user-images.githubusercontent.com/8872186/215194025-4fff0f3b-e265-418a-a6ea-5659ae0916c3.png)

2. From the resulting search results, user clicks the “select all” checkbox right under “Search for an entity” to bulk update all entities. In the below screenshot, it should be noted that the bulk update menu at the bottom of the webpage shows “2 selections”. However, this is inaccurate – the “select all” checkbox results in selecting all entities stored on the platform.

![image](https://user-images.githubusercontent.com/8872186/215194264-3d53cd23-fd2a-4add-a559-b1f048dd3849.png)

3. User proceeds with creating a bulk update job. It should be noted that the “launch a background task” menu shows “2 selected elements” which is inaccurate. We can see the values column for the scope step is blank, indicating that the operation is not correctly parsing the entity selection.

![image](https://user-images.githubusercontent.com/8872186/215194509-2dbdda99-65a8-48df-9256-ead8084dbd5a.png)

4. Launching the background task will actually queue a job that would append the selected label(s) (`test label` in this instance) to about 4 entities. You can verify this by navigating to `Data > Background Tasks`.

![image](https://user-images.githubusercontent.com/8872186/215194677-3bfa4f19-a946-4efb-bf9e-4aeda92daa97.png)

5. As an alternative to the above operation, the user needs to manually select each checkbox for the listed items, or use the `Observations > Observables` and `Observations > Indicators` menus as these seem to be working on the correct selections.

## Expected Output

Update background job should launch on the actual number of selected entities instead of all entities.

## Actual Output

Update background job is launched on all entities stored within the platform.

**Comment by SamuelHassine** [comment]
Thanks a lot for this issue well documented. Will be fixed in 5.3.3.

**Comment by gbikram** [comment]
Hello, I think this issue may have been **partially fixed.** 

At the time the issue was created, it appeared that the bug was limited to the **Global Search UI** only. However, I have encountered it under **Observables => Indicators**.  The Observable/Pattern Type filters (Domain, Yara etc.) are not propagated to the "scope" that defines the target entities for a bulk operation such as bulk enrichment or add/delete/replace operation. This occurs when the "select all" checkbox is used for selecting all Indicators visible after applying the filters.

You can see in the below image that Indicators are filtered to show Directories only. The background task verification box also shows that the task is being launched on **7 elements**. However, the task is actually launched on all indicators saved within the platform. This can be verified by checking the targeted entities listed for that background task within **Data => Background Tasks.**

![image](https://user-images.githubusercontent.com/8872186/235529935-9b74d43f-d441-42da-a6a1-e84bf91280b0.png)

The bug was encountered on **v5.6.2 of OpenCTI.** I tried testing it on **v5.7.3, however, I was unable to do so since the Observable/Pattern type filters do not appear to be working** (#3219 ).
