### ISSUE TITLE
Refactor TopBar

### ISSUE THREAD

**Issue by Kedae** [LuatixHQ/opencti#2796]
We always use two topbar at the same place for entities as the main TopBar doesn't work. It needs to be redone completely to prevent multiple renders with no reason

**Comment by RomuDeuxfois** [comment]
Bug report by @yassine-ouaamou 

If we add an announcement banner and refresh the app, it floates instead of being on top of the app zone
![banner_issue](https://github.com/OpenCTI-Platform/opencti/assets/7083405/77f3637b-5092-46e9-915d-310c45750610)
