### ISSUE TITLE
Visualizing ATT&CK mapping should be ordered by staging steps. ref: https://attack.mitre.org/

### ISSUE THREAD

**Issue by tanyawang1218** [LuatixHQ/opencti#2799]
## Use case

It will be better if the MITRE table shown in the Knowledge of Threat Actor can be mapping with MITRE: https://attack.mitre.org/

## Current Workaround

It doesn't map to MITRE now.

## Proposed Solution

Show the table just like MITRE's. It orders by stage.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

N/A

**Comment by SamuelHassine** [comment]
Hello @tanyawang1218,

The kill chain phases may not be always linked to the MITRE ontology. Ordering can be defined directly in Settings => Labels & Attributes => Kill Chain Phases.

Kind regards,
Samuel
