### ISSUE TITLE
Number of elements not immediately updated when we add an element

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#2810]
## Description

The number of elements in a list is not immediately updated when we add an element.

## Reproducible Steps

Go to Groupings (or an other entity type).
Look at the number of elements.
Add a grouping.
The number of elements is not updated (except if you go to an other tab and come again).

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/75783086/216573292-da1fd5ee-1eaa-434b-8f32-15cde72781b1.png)

**Comment by Kedae** [comment]
This will be fixed later on when we will have a proper "real-time" effect in list in OpenCTI.
