### ISSUE TITLE
Incident pages never show a donut chart of Observables distribution

### ISSUE THREAD

**Issue by mattreduce** [LuatixHQ/opencti#2814]
## Description

The "Observables distribution" section on Incident pages does not show the distribution of related observables

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04 Linux
2. OpenCTI version: 5.5.2
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. If one doesn't exist, create an Incident and relate some Observables to it
2. Visit that Incident's page
3. Look at the "Observables distribution" (should be a donut chart) in the "Details" section

## Expected Output

When the Incident has related Observables, I expect to see a donut chart visualizing the proportion of each related Observable type

## Actual Output

"No entities of this type has been found."

## Additional information

N/A

## Screenshots (optional)

<img width="644" alt="Screen Shot 2023-02-03 at 5 04 37 PM" src="https://user-images.githubusercontent.com/66427/216736974-1890a294-3f63-419d-a133-35d95bc353b3.png">

**Comment by SamuelHassine** [comment]
Hello,

This will be solved in 5.3.3. Global problem for dashboarding and relationships count.

Kind regards,
Samuel

**Comment by mattreduce** [comment]
Thank you, @SamuelHassine! 😄👍
