### ISSUE TITLE
Implement tasks and tasks template in cases

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2846]
## Use case

* Create a new type of entity "Task"
  * Name / Description / Due Date / Workflow
* In the settings of the platform, be able to pre-defined list of tasks (aka tasks list template)
* ~~In the Case menu, add a top menu "Tasks" to list all tasks~~
* In a Case, display the list of the tasks with the ability to:
  * Apply a task list template
  * Create a new task
* When creating a case, be able to select a task list template at creation to be applied automatically

**Comment by richard-julien** [comment]
Should be done after https://github.com/OpenCTI-Platform/opencti/issues/2977
