### ISSUE TITLE
Add "quick subscription" icon on top right of somes entities

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2853]
## Use case

Concerned entities:

* Cases
* Threat Actor
* Intrusion Set
* Campaign
* Incident
* Tool
* Malware
* Vulnerability

Quick subscription should cover:

* Update
* Delete
* Creation of new containers containing the entity
* Creation of new relationship from/to the entity

Engine must be adapted to:
- support listening on a single instance
- single instance must auto listen on containers modification concerning this instance

When clicking on the Quick Subscription icon, the user should be able to select the outcome (email, notification).

**Comment by SamuelHassine** [comment]
@Archidoit, can you please think about something like this:

![image](https://user-images.githubusercontent.com/1334279/232391358-6f790ef2-525d-43ab-8b93-f2bcfb5cf507.png)
 
On the top right, having a "Bell" instead of a "Star" and replacing "Follow" / "Followers" by "Subscribe / Subscribers".

Thanks!

**Comment by Kedae** [comment]
@SamuelHassine why not in Channels aswell ?
