### ISSUE TITLE
Improve Redis cluster configuration + platform stops when redis is not available

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2875]
## Description

Improve Redis cluster configuration > Hostnames must be converted to a simple list of string.
`"hostnames": ["localhost:7000", "localhost:7001", "localhost:7002"]`
and for nat mapping if needed

`nat_map: ['10.0.1.230:30001>203.0.113.73:30001', '10.0.1.231:30001>203.0.113.73:30002']`

When Redis becomes unavailable, platform stops in some conditions:

```
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 10). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/var/data/app/opencti-platform/opencti-graphql/build/node_modules/ioredis/built/redis/event_handler.js:177:37)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
```

**Comment by ckyoog** [comment]
I can confirm this issue. Just ran into it. when the redis was killed by OOM, the opencti crashed.
