### ISSUE TITLE
Error when trying to update a Note

### ISSUE THREAD

**Issue by Aspidoquelona** [LuatixHQ/opencti#2885]
## Description

Error when trying to update a Note.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
2. OpenCTI version: 5.5.4
3. OpenCTI client: frontend
4. Other environment details: Manual installation

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Note
2. The Note has been created
3. Try to update it
4. Error message

See attached screenshots.

## Expected Output

A Note update form window

## Actual Output

Error message

*"An unknown error occurred. Please contact your administrator or the OpenCTI maintainers."*

## Additional information

The error is reproducible also in previous OpenCTI version 5.5.2

### Create a Note
![create_note](https://user-images.githubusercontent.com/119074626/218808624-cb5df27b-40bd-4f7c-87b0-60434e5fcd77.png)
### The Note has been created
![note01](https://user-images.githubusercontent.com/119074626/218808704-356b0421-bbc3-458d-975e-a10331a3a046.png)
### Try to update it
![update](https://user-images.githubusercontent.com/119074626/218808835-4fb5765e-d370-4f01-83fc-3df38b81172d.png)
### Error message
![update_error](https://user-images.githubusercontent.com/119074626/218808901-49454278-e05f-4e91-8f14-15417c952a1b.PNG)

**Comment by SamuelHassine** [comment]
Hello @Aspidoquelona,

We're not able to reproduce. Can you please share:

1. The logs of your browser console when you've the error
2. Any logs on the OpenCTI container you may have (may be nothing)

Thanks!

Kind regards,
Samuel

**Comment by Aspidoquelona** [comment]
Hi,

These days I'm out of my working environment, but the error occurs also in the demo instance https://demo.opencti.io/

Please note that the update fails when launched from the "Data" view:

![image](https://user-images.githubusercontent.com/119074626/219139237-bb072792-65c2-4eb0-a55a-f369ea113117.png)

**Comment by Aspidoquelona** [comment]
UPDATE: something has happened to the demo instance. I was creating Notes looking for other similar situations and now the Notes view shows an error message (it reminds me a situation similar to the one I've got time ago regarding non-nullable attributes). I'm sorry for this breakage.

**Comment by Aspidoquelona** [comment]
UPDATE2: Trying to remember what I've done, I believe that the sequence of operations that caused this breakage was the following:

1. Select a Report
2. Go to Entities view of the Report
3. Click the + sign to add an Entity
4. Click the + sign in the form "Add entities"
5. Select Entity Type = Note
6. Give a Name to the Note
7. Create

Hope this helps and I apologize again for causing this problem in your demo instance.

**Comment by RomuDeuxfois** [comment]
Hello @Aspidoquelona,

I am able to reproduce it in the Data menu, I missed this spot the first time.
I also reproduced your second scenario.

Thanks a lot for the informations.

**Comment by richard-julien** [comment]
For information, first case will be solved.
Second case, it will no longer be possible to create note like this due to technical restriction. Will be reintroduced later.
