### ISSUE TITLE
The relationship type "contains" is not allowed between StixFile and Url

### ISSUE THREAD

**Issue by matthieuxyz** [LuatixHQ/opencti#2896]
## Description

Error message while trying to create a "contains" relationship between a File and an URL

`The relationship type "contains" is not allowed between StixFile and Url`

This relationship is useful for files other than archives that contains URL, IP addresses or other observables in the content of the file and is part of the STIX 2.1 standard. ( https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070697 )

## Environment

1. OpenCTI version: 5.5.2
2. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open an object and go to the "knowledge" tab
2. Click on the plus sign next to "linked objects"
3. Select an URL (or IP adress or other Cyber Observable)
4. Select "contains" as the relationship type (pre-selected)
5. Click "Create"

## Expected Output

The creation of a new relationship.

## Actual Output

`The relationship type "contains" is not allowed between StixFile and Url`

**Comment by richard-julien** [comment]
Will be fixed in https://github.com/OpenCTI-Platform/opencti/issues/1850
