### ISSUE TITLE
Expose "contains" relationship to Custom Dashboards

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#2914]
## Use case

We are trying to created the following dashboard:
`Horizontal graph of top Malwares, by their appearance in Alienvault reports`

Even more useful:
`Horizontal graph of top Malwares, by their appearance in <our org> reports`

My understanding of the custom dashboards isn't 100%, but it seems like this is best achieved by using the Knowledge Graph/Relationships functionality. However, in order to make clear that we want to count Malware objects _only_ in reports, we need to reference the malware by using the "contains" relationship.

I'm open to implementing this a different way as well. 

## Current Workaround

n/a

## Proposed Solution

Expose "contains" relationship to Custom Dashboards

## Additional Information

![image](https://user-images.githubusercontent.com/78382789/220447497-e69491cf-3e21-4268-9e8d-482adb660abc.png)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by richard-julien** [comment]
Will be handle by https://github.com/OpenCTI-Platform/opencti/issues/2921
