### ISSUE TITLE
"is_family" is "null" in STIX because of "Is family" is "NOT APPLICABLE" in portal. stxi2-validator will fail if is_family is null

### ISSUE THREAD

**Issue by tanyawang1218** [LuatixHQ/opencti#2915]
## Description

When creating a malware, it can't identify the "Is family" in the beginning. At the moment, the "Is family" is "NOT APPLICABLE" and  "is_family" shows "null" in STIX. It will result in stix2-validator fail if is_family is null.

## Environment

1. OS (where OpenCTI server runs): AWS
2. OpenCTI version: {OpenCTI v5.1.17
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a malware, and it shows in portal. The "Is family" shows "NOT APPLICABLE"
2. Check the STIX of the malware. "is_family" field shows "null"

## Expected Output
The default value should be yes or no by default, so that work well in stix2-validator.

## Actual Output

User didn't identity the Is family as Yes or No in the beginning. Stix2-validator will fail when encounter "is_family" is null.

## Additional information
If user update Is family as Yes or No, both portal and STIX can show correctly.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/10161931/220549971-21ad78d9-5b76-489b-8174-b0c791a9c910.png)
![image](https://user-images.githubusercontent.com/10161931/220550012-7aa29c25-975c-4d7f-8e17-e3c3e41ccdc3.png)

**Comment by richard-julien** [comment]
Must be done after https://github.com/OpenCTI-Platform/opencti/issues/1850

**Comment by richard-julien** [comment]
Close directly with https://github.com/OpenCTI-Platform/opencti/issues/1850
