### ISSUE TITLE
The relationship type targets is not allowed between Attack-Pattern and System

### ISSUE THREAD

**Issue by matthieuxyz** [LuatixHQ/opencti#2923]
## Description

Error message while trying to create a "target" relationship between an Attack-Pattern and a System

`The relationship type targets is not allowed between Attack-Pattern and System`

## Environment

1. OpenCTI version: 5.5.2
2. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a report
2. In the knowledge tab, add an Attack-Pattern and a System
3. Select the Attack-Pattern and the System
4. Try to create a relationship of type "targets"

## Expected Output

The creation of a new relationship.

## Actual Output

`The relationship type targets is not allowed between Attack-Pattern and System`

**Comment by richard-julien** [comment]
You're right, according to https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_e33ahkddw0q1 we need to add this support as System is an identity
