### ISSUE TITLE
GraphQL Introspection 

### ISSUE THREAD

**Issue by llid3nlq** [LuatixHQ/opencti#2932]
## Description

GraphQL Introspection is allowed on the platform. This allows unauthenticated users to query the graphql endpoint, revealing the schema and other valuable information. https://lab.wallarm.com/why-and-how-to-disable-introspection-query-for-graphql-apis/

## Environment

Default Installation using Docker (potentially all installations)

## Reproducible Steps

Deploy OpenCTI
Navigate to /graphql endpoint
Run:
{__schema{queryType{name}mutationType{name}subscriptionType{name}types{...FullType}directives{name description locations args{...InputValue}}}}fragment FullType on __Type{kind name description fields(includeDeprecated:true){name description args{...InputValue}type{...TypeRef}isDeprecated deprecationReason}inputFields{...InputValue}interfaces{...TypeRef}enumValues(includeDeprecated:true){name description isDeprecated deprecationReason}possibleTypes{...TypeRef}}fragment InputValue on __InputValue{name description type{...TypeRef}defaultValue}fragment TypeRef on __Type{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name ofType{kind name}}}}}}}}

## Expected Output

GraphQL Introspection is enabled by default in GraphQL, so this is expected. It is expected that OpenCTI would have it disabled, though. 

## Actual Output

Too lengthy to paste. Will provide if you really need it.

## Additional Information

Introspection can be disabled with NodeJS in the following way:

app.use('/graphql', graphqlHTTP({
  schema: MyGraphQLSchema,
+ validationRules: [NoIntrospection]
}));

**Comment by richard-julien** [comment]
Thanks for the report, introspection will be disable in production.
(https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/)

**Comment by richard-julien** [comment]
Ok so we will use a different approach than just disable.

By default the playground and the introspection will be still available **but only for authenticated users**
Introspection is still used a lot to play with the api and discover it.

+ Add to more options.

```
    "graphql_playground": {
      "enabled": true,
      "force_disabled_introspection": false
    },
```

1. Possibility to disable the playground completly through graphql_playground:enabled.
This option will also disable the introspection

2. Possibilty to force the disable of the introspection query with graphql_playground:force_disabled_introspection.
