### ISSUE TITLE
Import an investigation

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2954]
## Use case

After #1374, be able to import an investigation based on a STIX 2.1 JSON bundle.

**Comment by SamuelHassine** [comment]
Blocked by #1374.

**Comment by Jipegien** [comment]
Importing an investigation is a nonsense: an imported investigation is likely to contain non existing data we will have to create but Investigation graph does not aim to create data, just explore it.
Plus, it will be possible to easily switch between Report and Investigation, and import/export of Report is already implemented.
