### ISSUE TITLE
Specific dashboard filters cause crash of the dashboard

### ISSUE THREAD

**Issue by fscc-samiR** [LuatixHQ/opencti#2963]
## Description

When adding entities visualization into a dashboard and choosing filters for entity type and related entity type, the dashboard will crash due to invalid GraphQL query.

## Environment

1. OpenCTI version: 5.5.3
2. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new dashboard and add a visualization:
![image](https://user-images.githubusercontent.com/91312589/222764201-56083d6d-bcc4-41a2-8f27-29f55b2e42cc.png)

2. Add a filter for entity type: malware, related entity: specific intrusion-set:
![image](https://user-images.githubusercontent.com/91312589/222764429-e3db8923-5860-4bb8-90cc-b96f4f56efde.png)

4. After validation and creation, the dashboard will crash with error:
`
"{\"category\":\"APP\",\"error\":{\"stacktrace\":[\"GraphQLError: Variable \\\"$timeSeriesParameters\\\" got invalid value \\\"relationship_type\\\" at \\\"timeSeriesParameters[0].filters[0].key\\\"; Value \\\"relationship_type\\\" does not exist in \\\"StixCoreObjectsFilter\\\" enum.\",\"at onError (/opt/opencti/build/node_modules/graphql/execution/values.js:147:11)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:154:9)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:49:14)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:79:13)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:49:14)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:117:34)\",\"at /opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:75:16\",\"at Function.from (<anonymous>)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:73:20)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:117:34)\",\"at /opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:75:16\",\"at Function.from (<anonymous>)\",\"at coerceInputValueImpl (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:73:20)\",\"at coerceInputValue (/opt/opencti/build/node_modules/graphql/utilities/coerceInputValue.js:32:10)\",\"at coerceVariableValues (/opt/opencti/build/node_modules/graphql/execution/values.js:132:52)\",\"at getVariableValues (/opt/opencti/build/node_modules/graphql/execution/values.js:45:21)\"]},\"inner_relation_creation\":0,\"level\":\"error\",\"message\":\"API Call\",\"operation\":\"StixCoreObjectsMultiHeatMapTimeSeriesQuery\",\"operation_query\":\"query StixCoreObjectsMultiHeatMapTimeSeriesQuery($operation:StatsOperation!$startDate:DateTime!$endDate:DateTime!$interval:String!$timeSeriesParameters:[StixCoreObjectsTimeSeriesParameters]){stixCoreObjectsMultiTimeSeries(operation:$operation startDate:$startDate endDate:$endDate interval:$interval timeSeriesParameters:$timeSeriesParameters){data{date value}}}\",\"size\":279,\"time\":5,\"timestamp\":\"2023-03-03T14:58:45.850Z\",\"type\":\"READ_ERROR\",\"user\":{\"ip\":\"XXXX\",\"referer\":\"XXXX/dashboard/workspaces/dashboards/afb9757f-ef39-41b3-90ae-cc89f8448d63\",\"user_id\":\"XXXX\"},\"variables\":{\"endDate\":\"2023-03-03T16:58:45+02:00\",\"interval\":\"day\",\"operation\":\"count\",\"startDate\":\"2022-03-03T00:00:00+02:00\",\"timeSeriesParameters\":[{\"field\":\"created\",\"filters\":[{\"filterMode\":\"or\",\"key\":\"relationship_type\",\"operator\":\"eq\",\"values\":[\"related-to\"]}],\"types\":[\"Malware\"]}]},\"version\":\"5.5.3\"}\n"
`
Filters which cause a problem:
`
      "timeSeriesParameters": [
        {
          "field": "created",
          "filters": [
            {
              "filterMode": "or",
              "key": "relationship_type",
              "operator": "eq",
              "values": [
                "related-to"
              ]
            }
          ],
          "types": [
            "Malware"
          ]
        }
      ]
`

## Expected Output

Expect the visualization to be added to the dashboard instead.

## Actual Output

The dashboard becomes inaccessible due to the error.

**Comment by richard-julien** [comment]
Should be fix by https://github.com/OpenCTI-Platform/opencti/issues/2921
