### ISSUE TITLE
Separate Case and Feedback, and implement Request for Information

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#2977]
## Use case

* Separate Case and Feedback

For types of entity: 

* Feedback = Feedback
* Case = Case-Incident
* Request For Information = Case-RFI

Implement a new screen / list + Case RFI.

Kind regards,
Samuel

**Comment by TechBurn0ut** [comment]
@SamuelHassine I ran into a weird issue involving Case types.  If the Case types are going to be effect the way that the platform operates ( i.e. case_types != incident) then the case objects do not populate in the UI.

**Comment by Kedae** [comment]
> @SamuelHassine I ran into a weird issue involving Case types. If the Case types are going to be effect the way that the platform operates ( i.e. case_types != incident) then the case objects do not populate in the UI.

HI @TechBurn0ut, currently only the 'incident' and the 'feedback' case types are handled in the UI. Next step is to provide some hard-coded types (such as request for incident, request for takedown) and you won't be able to provide custom ones. In addition, some case types will have sub-types that you could customize.
