### ISSUE TITLE
Extend reliability score to Individual entity

### ISSUE THREAD

**Issue by akshaysth** [LuatixHQ/opencti#2989]
## Use case

Currently, there's the ability to set a reliability score based on the Admiralty Code only for organizations. Ideally, this should get extended to individual entities in OpenCTI.

## Current Workaround
None

## Proposed Solution
Provide option for setting the reliability score for the individual entity.

## Additional Information

**Organization:**
<img width="789" alt="Screenshot 2023-03-07 at 11 44 38" src="https://user-images.githubusercontent.com/1302562/223495005-60770561-2b12-41cc-a798-f54e02256373.png">

**Individual:**
<img width="783" alt="Screenshot 2023-03-07 at 12 02 48" src="https://user-images.githubusercontent.com/1302562/223495055-b61606cf-8e3d-4a61-bc5a-d972a449c417.png">

## If the feature request is approved, would you be willing to submit a PR?
No

**Comment by SamuelHassine** [comment]
Duplicate of #2362.
