### ISSUE TITLE
Improve Synchronizer client to try reconnect if started but connection is closed (404, ..)

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#2990]
## Description

Hello,

I use Synchronization between 2 Opencti. And regularly (about once a day) sync freezes. The sync current state date no longer changes.

I need to stop and start the sync to make it work again.
## Environment

1. OS (where OpenCTI server runs): Debian
2. OpenCTI A version: 5.5.4
3. OpenCTI B version: 5.5.4
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Sync 2 Opencti

## Additional information

Logs:

```
{"category":"APP","level":"info","message":"[OPENCTI] Sync fdad04da-64b8-4a91-aadd-742ad4197708: saving state from heartbeat to 1678251949170-0/2023-03-08T05:05:49.170Z","timestamp":"2023-03-08T05:05:49.178Z","version":"5.5.4"}
{"category":"APP","level":"info","message":"[OPENCTI] Sync fdad04da-64b8-4a91-aadd-742ad4197708: saving state from heartbeat to 1678251976584-0/2023-03-08T05:06:16.584Z","timestamp":"2023-03-08T05:06:16.591Z","version":"5.5.4"}
{"category":"APP","error":{"type":"error"},"level":"error","message":"[OPENCTI] Sync fdad04da-64b8-4a91-aadd-742ad4197708: error in sync event","timestamp":"2023-03-08T05:06:17.527Z","version":"5.5.4"}
{"category":"APP","error":{"message":"Not Found","status":404,"type":"error"},"level":"error","message":"[OPENCTI] Sync fdad04da-64b8-4a91-aadd-742ad4197708: error in sync event","timestamp":"2023-03-08T05:06:18.569Z","version":"5.5.4"}
```

Live stream configuration:

![image](https://user-images.githubusercontent.com/9503671/223678001-36ec8794-0a74-4871-8ace-24f54b0081b9.png)

Thank you

**Comment by richard-julien** [comment]
Can you also check the logs on the OpenCTI that share the data?

**Comment by richard-julien** [comment]
Checking the code looks like the client doesnt reconnect automatically in case of 404 error.

```
      if (res.statusCode !== 200) {
        _emit('error', new Event('error', {status: res.statusCode, message: res.statusMessage}))
        return self.close()
      }
```

Its a bit strange you receive a 404 from the remote OpenCTI but I will take a look to see if we can bypass that and try to reconnect even if the error is a 404.

**Comment by Tonnulus** [comment]
@richard-julien thank you for your reply.

I juste figured out, that an automatic restart of the OpenCTI (source) is scheduled at this time.

If you have a retry policy, or macanism to restart the Sync, I'm interested.
