### ISSUE TITLE
[FYSA] Platform performance is heavily degraded if there are a lot of pending analyst workbenches/ bundles. 

### ISSUE THREAD

**Issue by Drookoo** [LuatixHQ/opencti#2995]
just for awareness, in our environments where we have external import connectors that import pdfs turned on for years (ie. Crowdstrike) we were noticing heavy platform slownesss and degradation even though we were using S3 and premium SSDs for all of our infrastructure and couldn't pinpoint the root cause from our monitoring dashboards.

We couldn't figure out why our stuff was slow when we compared our elasticsearch index sizes with other teams and saw comparible amounts of data but saw that our platform instances was slow in comparison. 

The problem for us was that we had many pending bundles and workbenches from opencti v4 till now that our global data import tab wouldn't load properly. We deleted all the json files sitting in the `pending` directory on S3 (our import document connector has been set to auto for years), because we figured that if we ever needed it, the pdf is already attached to the report and we can just run a manual import, and our platforms' performance across the board improved drastically.

**Comment by richard-julien** [comment]
First idea about that is to add a "files" handling in retention policies.
Like that it will be possible to describe the retention time to keep the files for specific entities.
Example:

Name: **Files Report Retention policy**
Maximum rentention days: **20**
Filters: **Entity type -> Report**, **Target -> Files**

**Comment by SamuelHassine** [comment]
Will be addressed here: #3016.
