### ISSUE TITLE
Role can have a default dashboard

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3002]
## Use case

Roles can have a default dashboard (can be overridden by the user)

## Additional Information

this feature was part of the issue https://github.com/OpenCTI-Platform/opencti/issues/2512 but it is not developped in the original issue which is quite big.

**Comment by SamuelHassine** [comment]
Default dashboards can be set:

- On a role
- On a group
- On an organization

If default dashboard is conflicting, just display the first in the alphabetical order. User may override this by setting another one of course.

**Comment by Jipegien** [comment]
Issue closed following decision to limit Role configuration to Capabilities. Reference is #3163
