### ISSUE TITLE
Make the platform supports opinion custom vocab / scale

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3003]
## Use case

Currently, opinion scale is:

![image](https://user-images.githubusercontent.com/1334279/224316054-9f1f4994-9c5b-4059-bbb5-c0ba26421ef0.png)

When changing the vocab in the opinions_ov, the scale remains the same.

**Comment by SamuelHassine** [comment]
@Jipegien need to discuss this.

**Comment by SamuelHassine** [comment]
We need to take into account opinions_ov in:

* The scale
* The radar

**Comment by SarahBocognano** [comment]
- The order doesn't work at creation of a new vocab (it works on update though)

Otherwise, everything works perfectly 🕺🏼
