### ISSUE TITLE
OpenCTI SSL Not Running HTTPS

### ISSUE THREAD

**Issue by vorschit** [LuatixHQ/opencti#3010]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.1 LTS
2. OpenCTI version: OpenCTI 5.6.1
3. OpenCTI client: Runs on Docker-Compose
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I am attempting to run opencti with a domain cert (Self Assign Cert).
2. I have attached the docker-compose file.
3. OpenCTI was running perfectly except without https. ![screenshot](https://cdn.discordapp.com/attachments/774623866940424202/1084802051600568400/image.png).
4. I tried to switch from port 8080 to port 443. It still ran with http not https

## Additional information

I did refer almost the same which is on issue [#2307](https://github.com/OpenCTI-Platform/opencti/issues/2307) but the issue still persist.

Im sorry I didnt know how to export ENV File

| No| Env Variable| Value|
| ------------- |:-------------:| -----:|
| 1 | OPENCTI_KEY_PATH |/etc/ssl/certs/opencti-certs/opencti.key |
| 2 | OPENCTI_CRT_PATH |/etc/ssl/certs/opencti-certs/rootCA.crt |

[docker-compost.txt](https://github.com/OpenCTI-Platform/opencti/files/10956872/docker-compost.txt)

**Comment by vorschit** [comment]
My issue was the Cert was not valid. Create a new one and now run as HTTPS

**Comment by nhs1925** [comment]
How did you do it? im trying and im not able to set the certs in order to use https. Could you give me a quick guide o an example or link to check or something?
