### ISSUE TITLE
Notifications keep being generated when the trigger is removed

### ISSUE THREAD

**Issue by Eusebius** [LuatixHQ/opencti#3014]
## Description

When a live trigger is created, and later deleted, then OpenCTI keeps generating notifications for the user.

## Environment

1. OS: Linux Debian 11
2. OpenCTI version: 5.4.4
3. OpenCTI client: frontend
4. Other environment details: Portainer-managed Docker swarm, 3 workers, single VM

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to "triggers and digests", create new live trigger for entity creation, notifications on user interface.
2. Create a first bogus entity, like a threat actor. 
3. Go to "triggers and digests", delete the live trigger.
4. Create a second bogus entity. 

## Expected Output

Only the first bogus entity should raise a notification.

## Actual Output

Both bogus entities, and all later entity creations, raise notifications.

## Additional information

Restarting the stack from Portainer seems to refresh the trigger/notification system and no further notification are created for deleted trigger. It is probably not the minimal operation leading to this result (restarting a single service should probably do the trick) but this kind of server-side operations should not be necessary, in my opinion, for a user setting to take effect. A misconfigured live trigger still generates notifications hours after its deletion.

**Comment by SamuelHassine** [comment]
Hello @Eusebius,

This is a known bug in 5.4.4 and has been fixed in 5.6.2. Can you please retry with the latest version and tell us if everything is ok?

Kind regards,
Samuel

**Comment by Eusebius** [comment]
Hi @SamuelHassine, thanks for the response and sorry about reporting on an older version.
Not an upgrade on the same platform (which has to stay in 5.4.4 for now), but I confirm that I cannot reproduce the bug on another 5.6.2 install.
