### ISSUE TITLE
Creating and deleting "child" relationships between 2 Process Objects throws "t.substr is not a function"

### ISSUE THREAD

**Issue by bentengly** [LuatixHQ/opencti#3027]
## Description

With 2 Process Objects inserted, inserting "child" relationships between them returns the error t.substr is not a function.
This happens on both the web interface and the pycti library and caused after the graphql api is called and returns the error message in the response

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.1 LTS
2. OpenCTI version: both OpenCTI 5.6.2 and OpenCTI 5.5.2
3. OpenCTI client: both front-end and python
4. Other environment details:
python version: 3.11.0
pycti version: 5.6.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
On front-end:
1. Inserting a Process Object with a "child" relationship to another Process Object
2. Deleting the "child" relationship

On python (pycti):
1. Insert a Process Object into OpenCTI
2. Insert another Process, with the first process' ID in the "child_refs" field, using the `opencti_api_client.stix2.import_observable` function

## Expected Output

On front-end:
The child relationship is deleted with no errors

On python:
The child relationship is inserted with no errors

## Actual Output

On front-end:
The child relationship is not deleted and a error toast notification is displayed with "t.substr is not a function"

On python:
The child relationship is inserted but the import_observable function throws a ValueError with the message `{'name': 't.substr is not a function', 'message': 't.substr is not a function'}`

## Additional information

On the front-end:
![webinterface](https://user-images.githubusercontent.com/66705076/225801956-a1c97202-d667-4823-a830-cb2046d7ea03.PNG)

*query request*
![query_request](https://user-images.githubusercontent.com/66705076/225802496-c2e32950-71b8-417e-ac81-e7fe0f64dc61.PNG)
*query response*
![query_response](https://user-images.githubusercontent.com/66705076/225802544-2e1b2731-041b-48fd-ad90-214a63538fa8.PNG)

From pycti:
![Capture](https://user-images.githubusercontent.com/66705076/225802034-e58d06e8-fe2f-4cbd-9917-e0cdcd2b3b17.PNG)

**Comment by richard-julien** [comment]
Hi, im not able to reproduce for now, can you try to reproduce on the demo? Thanks

**Comment by bentengly** [comment]
Hello, I am unable to reproduce the error in the demo, but using the same attached code throws the error on my local deployment.

I deployed OpenCTI locally using the readme here: https://github.com/OpenCTI-Platform/docker with the same version as the demo (v5.6.2) and my pycti version is also 5.6.2. Is this readme deployment steps the same as the steps used to deploy the demo?


Code that throws the error on my local but not on the demo:
```python
from pycti import OpenCTIApiClient


TEST_API_URL = "http://192.168.191.130:8080"
TEST_API_TOKEN = "<api token>"
opencti_api_client = OpenCTIApiClient(TEST_API_URL, TEST_API_TOKEN)
test_process1 = {
            "type": "process",
            "spec_version": "2.1",
            "id": "process--6736a540-6676-49a4-b3c1-84098734ede6",
            "pid": 2500,
            "command_line": "attrib +h ."
        }

opencti_api_client.stix2.import_observable(test_process1)


test_process2 = {
            "type": "process",
            "spec_version": "2.1",
            "id": "process--8fcd4ece-6533-4e28-a7c6-3c9cf979577d",
            "pid": 316,
            "command_line": "\"C:\\Users\\Brian\\AppData\\Local\\Temp\\ed01ebfbc9eb5bbea545af4d.exe\" ",
            "child_refs": [
                "process--6736a540-6676-49a4-b3c1-84098734ede6"
            ]
}

opencti_api_client.stix2.import_observable(test_process2)
```

**Comment by richard-julien** [comment]
If you cannot reproduce on the demo means that the problem is already fix on the current dev branch.
Problem will so be fixed in the next release.

**Comment by TheMythologist** [comment]
Agreed, just deployed a local instance using version 5.7.2 and the issue no longer occurs, thanks for the help

**Comment by TheMythologist** [comment]
Seems to have been fixed by https://github.com/OpenCTI-Platform/opencti/issues/3067

This was the full error log:
```json
{
    "category": "APP",
    "error": {
        "stacktrace": [
            "TypeError: t.substr is not a function",
            "at truncate (/opt/opencti/build/src/utils/mailData.ts:24:26)",
            "at /opt/opencti/build/src/database/utils.js:348:41",
            "at Array.map (<anonymous>)",
            "at /opt/opencti/build/src/database/utils.js:348:28",
            "at Array.map (<anonymous>)",
            "at /opt/opencti/build/src/database/utils.js:333:47",
            "at Array.map (<anonymous>)",
            "at generateUpdateMessage (/opt/opencti/build/src/database/utils.js:332:54)",
            "at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2791:27)",
            "at createRelation (/opt/opencti/build/src/database/middleware.js:2815:16)",
            "at addStixCyberObservableRelationship (/opt/opencti/build/src/domain/stixCyberObservableRelationship.js:38:19)"
        ]
    },
    "inner_relation_creation": 0,
    "level": "error",
    "message": "API Call",
    "operation": "StixCyberObservableRelationshipAdd",
    "operation_query": "mutation StixCyberObservableRelationshipAdd($input:StixCyberObservableRelationshipAddInput!){stixCyberObservableRelationshipAdd(input:$input){id standard_id entity_type parent_types}}",
    "size": 302,
    "time": 167,
    "timestamp": "2023-04-26T00:24:42.995Z",
    "type": "WRITE_ERROR",
    "user": {
        "ip": "::ffff:172.27.0.1",
        "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f"
    },
    "variables": {
        "input": {
            "created": null,
            "createdBy": null,
            "fromId": "c32c83b6-4504-424a-b6cc-764de68ec9ad",
            "modified": null,
            "objectMarking": null,
            "relationship_type": "child",
            "start_time": null,
            "stix_id": null,
            "stop_time": null,
            "toId": "process--6736a540-6676-49a4-b3c1-84098734ede6",
            "update": false,
            "x_opencti_stix_ids": null
        }
    },
    "version": "5.6.2"
}
```
