### ISSUE TITLE
After update, I can't add or edit note right away.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3052]
[Before] 5.3.14
![image](https://user-images.githubusercontent.com/19428462/227110264-875905f4-2e8d-475d-aca5-857c074ebba8.png)

[After] 5.6.2
![image](https://user-images.githubusercontent.com/19428462/227110285-66770701-cd2a-4ba0-ba08-4ad43fc1349f.png)

Because there is no edit button, I go to "Analysis - Notes" tab and add or edit note.

I think it's too inconvenient.

Would you like to add an edit button like before?

**Comment by Archidoit** [comment]
In which entity do you have this problem? It seems I still have a Note edit button in the Overview of entities : 
![image](https://user-images.githubusercontent.com/75783086/227181454-8040ec87-981a-4d99-8f67-42f419fa9f90.png)

**Comment by misohouse** [comment]
> In which entity do you have this problem? It seems I still have a Note edit button in the Overview of entities : ![image](https://user-images.githubusercontent.com/75783086/227181454-8040ec87-981a-4d99-8f67-42f419fa9f90.png)

Um... I checked again today and I see that button.

There was no button yesterday, it's weird..

Thank you for the reply :)
