### ISSUE TITLE
Custom dashboard iframe widget

### ISSUE THREAD

**Issue by PekkaJalonen** [LuatixHQ/opencti#3054]
## Use case

Embed another web page/site in custom dashboard

## Current Workaround

N/A

## Proposed Solution

To be able to embed external tool, such as other monitoring tools in custom dashboard via iframe

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/3054 Closing your issue since it's been duplicated
