### ISSUE TITLE
Author negative filtering not working on streams

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3059]
Author negative filtering not workings on streams.

## Reproductible steps

- Create a stream with a negative filtering on the author XX.
- Start and open the stream.
- Modify an object which Author = XX
- the update appears in the stream whereas it shouldn't.

**Comment by richard-julien** [comment]
This situation occurs only on negative filter for ref relationships, negative filtering on simple attribute are working as expected
