### ISSUE TITLE
Enable quick dashboard deployment, streamline custom workflows, and potential external sharing

### ISSUE THREAD

**Issue by Astral-Reaper** [LuatixHQ/opencti#3076]
## Use case

Facilitate quick dashboard and customized work flow creation.

## Current Workaround

Manually create every dashboard.

## Proposed Solution

Enable the copying/duplication of any existing dashboards and renaming, as appropriate, to deploy new or tailored versions.

## Additional Information

Rather than having to create dashboards from scratch over and over again. Being able to copy/duplicate any existing dashboard, including the openCTI pre-defined one would extremely speed up the process of custom work flows or specific data visualizations.

- Maybe even the potential to export dashboard configurations for external sharing.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by Jipegien** [comment]
Duplicate of issue #3241
