### ISSUE TITLE
Multiple data sources partially failing to show up in the platform

### ISSUE THREAD

**Issue by GraemeMeyerGT** [LuatixHQ/opencti#3107]
## Description

We have at least 3 connectors - VX Vault, DISARM Foundation and CyberCrime Tracker - that are putting data in the platform, but it's failing to show up in some locations, such as the Data --> Entities panel. We have two instances of OpenCTI with near-identical configs (deployed as code), and one is effected, but one is not. The access controls, org configuration, marking definitions, groups, connectors and connector configurations are identical between the two.

As it's our Dev instance displaying the problem, it could be that the nature of the dev instance (which is regularly started/stopped), has revealed a subtle bug in the platform.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } Ubuntu 22 LTS running Docker and Docker Compose.
```
docker --version
Docker version 23.0.2, build 569dd73
```
```
docker compose version
Docker Compose version v2.17.2
```
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 5.6.2
<img width="376" alt="image" src="https://user-images.githubusercontent.com/107847353/229464951-dcd2a88d-960b-4018-b103-a97040ccd564.png">

3. OpenCTI client: { e.g. frontend or python } N/A (whole-platform, including connectors, which use the python client)
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Search in the Data --> Entities panel for an entity from a connector like vx vault in both platforms (prod on the left, dev on the right):
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/107847353/229466308-bd0ca94d-5d73-4d39-92d4-867ffe711f2b.png">

2. See that the entity is visible in Prod, but not Dev in that panel.

3. Search for the entity in the general search box in the top-right hand corner of the interface

4. See that the entity _is_ visible in both platforms (Prod on the right, Dev on the left):
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/107847353/229466606-b77072b4-8f89-4aee-8b5f-c57ddf4e8013.png">

5. Confirm that both entities are identical (using the Indicator entity), and have the correct Author and Technical Creator (VX Vault, and connector-vxvault respectively):
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/107847353/229466837-403933f1-34c7-4123-b73f-420822e9c627.png">
6. Verify that the connector user has the same `connector` role, the same `default` group, and the platform org set:
<img width="1923" alt="image" src="https://user-images.githubusercontent.com/107847353/229467876-ab053078-9baf-47b3-b504-89f33e48f5d6.png">
7. Verify that connector permissions are the same (and unchanged from the default permissions):
<img width="1923" alt="image" src="https://user-images.githubusercontent.com/107847353/229468162-ba9123fd-d6ea-4aff-a7de-bb5e3804fa9e.png">
8. Verify that the "Default" group is granted at user creation and automatically authorized for new marking definitions: 
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/107847353/229468565-dc416f64-0f16-4eb7-926b-9a1f1ad4595b.png">
9. Verify the same situation with several more connectors (in our case, DISARM, and CyberCrime Tracker):
DISARM - showing the data in the Data --> Entities panel in the left-hand platform, but not the right:
<img width="1922" alt="image" src="https://user-images.githubusercontent.com/107847353/229470316-48b00678-c353-420f-8b9a-2b1f97b85d33.png">
DISARM - showing that the data actually is in both platforms, using the general search:
<img width="1923" alt="image" src="https://user-images.githubusercontent.com/107847353/229470394-e651d053-bc48-4c46-b8b2-c5064a9b85f9.png">
CyberCrime Tracker - showing the data in the Data --> Entities panel in the left-hand platform, but not the right:
<img width="1923" alt="image" src="https://user-images.githubusercontent.com/107847353/229470690-2b441e34-7f93-41d5-a997-37d8f0b78ff5.png">
CyberCrime Tracker - showing that the data actually is in both platforms, using the general search:
<img width="1921" alt="image" src="https://user-images.githubusercontent.com/107847353/229470754-868286f0-3cd1-4459-be16-1963740f4768.png">

## Expected Output
Data should show up identically in both platforms.

## Actual Output
Data is wildly different in both platforms. Despite having identical connectors and configurations, the entity, relationship and report counts are completely divergent:
<img width="1923" alt="image" src="https://user-images.githubusercontent.com/107847353/229471347-ab3e9d5a-c0ba-44eb-91d4-18eae5597e38.png">

**Comment by GraemeMeyerGT** [comment]
Using the dashboards, I can see that the "relationship" counts are completely and nonsensiscally different as well.

E.g. connector-cve has 200K relationships in one platform, 30K in the other. Alienvault has 12K in one, 52K in the other.

![image](https://user-images.githubusercontent.com/107847353/229474126-4c18646e-abac-48a4-a89d-0504540927d6.png)

**Comment by GraemeMeyerGT** [comment]
I should mention also, I tried recreating the vxvault connector with a new ID as a debugging step, but it didn't seem to change anything (that's why the vx vault connector screenshot on the right shows a couple of extra "replaces" events)

**Comment by GraemeMeyerGT** [comment]
I've just added the Abuse.ch URLHaus connector to both platforms and it seems to be doing the same thing. The "working" platform (left in my screenshots) shows the data, but the "not-working" platform (right in my screenshots doesn't show the data in the Data --> Entities screen, even though you can search for an entity (like an indicator) and see it manually 🤔

<img width="1921" alt="image" src="https://user-images.githubusercontent.com/107847353/229492379-f0f9625e-0299-4b3f-855d-24530a07ded3.png">
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/107847353/229492387-b2502b7a-89e2-452b-8db0-c88050de0f7e.png">

**Comment by richard-julien** [comment]
HI @GraemeMeyerGT ,

Can you the connector jobs to compare the number of injection asked by each?

Can you also check for any error in logs?

Do you have some information available in the platform with less data but not assigned to the expected creator?

Thanks

**Comment by GraemeMeyerGT** [comment]
Hi @richard-julien,

> Can you the connector jobs to compare the number of injection asked by each?

I'm not sure what you mean by connector jobs and injections. We have following connectors (first "working", and then "not-working").

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/107847353/229728872-44bf5f8f-6f54-4b54-b89e-17ea8610b9d6.png">
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/107847353/229728891-618b1aaa-d2c5-41b2-97f2-6cbd24175d06.png">

Neither instance has any background jobs.

Comparing the connector's work - first, working, then not-working, seems identical:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/107847353/229729283-bfff68c5-f073-4e18-9dc8-eda100a2da76.png">
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/107847353/229729322-d0d116b5-c886-494d-a779-18f2e0984761.png">

> Can you also check for any error in logs?

There's no sign of significant errors in the logs that I can see. 

> Do you have some information available in the platform with less data but not assigned to the expected creator?

Not 100% sure what you mean, but the information that is partially missing in the "dev" platform is actually there and seems to be assigned to the correct creator (e.g. the vxvault connector shows entities assigned to the connector-vxvault user), but filtering in the main Data --> Entities panel returns nothing. If I search for an IOC like `orderedami` in the main search box in the top right, it does show up with correct creator, and can be filtered for by that creator:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/107847353/229732304-8a07d281-f132-4ee0-b392-76afc01925c9.png">

**Comment by GraemeMeyerGT** [comment]
Interesting, I've just noticed that actually the entity count for Data --> Entities is very low when no filters are applied in our "broken" platform as well:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/107847353/229732641-8f697144-3ef9-4220-89a3-ca716c92a128.png">

All entities listed are from Alienvault connector.

Not so in our "working" platform:

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/107847353/229732809-6ef66ada-0454-4cb4-b80d-b7f6d612aca4.png">

**Comment by richard-julien** [comment]
Are both platform completly isolated or share some dependencies (elastic, rabbit, redis, ...)?

**Comment by GraemeMeyerGT** [comment]
They're both completely isolated. Using the provided docker-compose config with few modifications for variables etc., but both platforms are identical config

**Comment by GraemeMeyerGT** [comment]
Is there any more debugging info I can collect to figure out what's happening here? Really don't want to have to rebuild that second environment if I don't have to

**Comment by GraemeMeyerGT** [comment]
My testing has concluded that hard-coding the RabbiMQ hostname eliminates a significant data loss problem with Docker deployments, and I think there's a good chance this is what has caused or significantly contributed to this issue of data showing up inconsistently in the platform. I have submitted a PR to fix this in the provided Docker Compose example configuration here: https://github.com/OpenCTI-Platform/docker/pull/90

**Comment by nino-filigran** [comment]
Closing this issue since nothing has been rasied since 6 months.

**Comment by GraemeMeyerGT** [comment]
Confirm this was resolved in the ensuing discussion [here](https://github.com/OpenCTI-Platform/opencti/issues/3373#issuecomment-1578334028), related to [#90 ](https://github.com/OpenCTI-Platform/docker/pull/90)
