### ISSUE TITLE
Rework module for interfaces

### ISSUE THREAD

**Issue by Kedae** [LuatixHQ/opencti#3128]
We need to rework a bit the modules to handle interfaces:

- The functions using isTypeIncludedIn to be recursive to be able to get all parents/childs
- Rework getParentTypes to handle this recursivness
- Change registerDefinition of module to only register its own parent
- Update the registration of converters

**Comment by nino-filigran** [comment]
@Kedae is this still needed?

**Comment by Kedae** [comment]
Probably not with all the work there has been on model. We can close it.
