### ISSUE TITLE
Suggestions for modifying the search function (searching for the middle part of a string)

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3131]
## Current Workaround

When I search something, it must match from the beginning to be searched.
![image](https://user-images.githubusercontent.com/19428462/230803385-de789616-4a62-4a40-8f9a-e28315b8259e.png)
![image](https://user-images.githubusercontent.com/19428462/230803398-c494dc7f-b105-4f50-ba85-537ba172f4e8.png)

## Proposed Solution

Please change it to be searchable even if I type in the word in the middle

## Additional Information

Present OpenCTI version is 5.6.2.

Thanky :)

**Comment by richard-julien** [comment]
Closing, will be covered by https://github.com/OpenCTI-Platform/opencti/issues/2486

**Comment by misohouse** [comment]
> Closing, will be covered by #2486

Um... did I get it wrong? Searching like below doesn't show any results.

![image](https://user-images.githubusercontent.com/19428462/231018033-3f4c7240-3683-42fc-8b3f-69ac3e5a6523.png)
![image](https://user-images.githubusercontent.com/19428462/231018059-87386b71-6d17-4f75-8377-4a3724dd75f3.png)
![image](https://user-images.githubusercontent.com/19428462/231018092-b43a7e97-0feb-4e30-8924-6d35f5996114.png)
![image](https://user-images.githubusercontent.com/19428462/231018146-aca16ce2-22f9-4f44-85c7-130f8d120329.png)
![image](https://user-images.githubusercontent.com/19428462/231018180-f0ecc291-84ec-44ba-8ebf-d0f2004cbab4.png)

**Comment by richard-julien** [comment]
No. Its not covered yet. I just closed your issue to prevent any duplicate. You can track the progress of this in the https://github.com/OpenCTI-Platform/opencti/issues/2486
