### ISSUE TITLE
Unable to restrict data access using marking definitions

### ISSUE THREAD

**Issue by openctitest** [LuatixHQ/opencti#3133]
## Description
Users are able to see data that their assigned group does not have permission to see

## Environment

1. OS (where OpenCTI server runs): Docker (Centos 7)
2. OpenCTI version: OpenCTI 5.5.4
3. OpenCTI client: frontend

## Reproducible Steps
I will use the following data in this example:
- User A
- User B
- Group A
- Group B
- Marking Definition A
- Threat Actor assigned Marking Definition A

I have two users (A, B) in my opencti instance, each is assigned to a different group (A assigned to A, B assigned to B). Group A has permissions to Marking Definition A, Group B does not.

I create a Threat Actor and assign it Marking Definition A.

## Expected Output

I expect to only be able to see the Threat Actor as User A, and not as User B.

## Actual Output

I see the Threat Actor as User A and B.

**Comment by SamuelHassine** [comment]
Hello @openctitest,

What are the role / capabilities of User A and B, if they are both administrator, they bypass all marking seggregation.

Kind regards,
Samuel

**Comment by debelyoo** [comment]
Hello,
I experience a. similar problem: I have entities with multiple markings (TLP + custom markings), and what I observe is that a user that has permission for only one of the markings is able to see the entity. Is that the desired behavior ? That looks buggy to me 🤔 
**example:** 
A report has two markings: "TLP amber", "Source Kaspersky". My user has only “TLP amber” in his allowed markings, but still he can see the report.

I would expect that any user that does not have all markings attached to the entity would not be able to see the entity.

# Environment
- OS (where OpenCTI server runs): Docker (Ubuntu 22.04)
- OpenCTI version: OpenCTI 5.12.26
- OpenCTI client: frontend

**Comment by debelyoo** [comment]
More details about how to reproduce the problem:
1. Create one custom marking of type "source" with value "vmray" and order 0.
2. Create one report "reportA" and assign it two markings: "TLP:AMBER" and the new "vmray" marking.
3. Create security group "group1" and set "TLP:AMBER" in its allowed markings.
4. Create user "user1" and add it in "group1".
5. Login to OpenCTI as user1.
6. The report "reportA" is visible in the analyses (but it should not since "user1" hasn't the "vmray" marking).

**Comment by Jipegien** [comment]
@debelyoo Is the group1 associated with a role with "bypass" capability?

**Comment by debelyoo** [comment]
No. group1 is associated with role "default"

**Comment by Jipegien** [comment]
@nino-filigran, are you able to reproduce? It might be a critical...

**Comment by nino-filigran** [comment]
@debelyoo and @Jipegien I'm not able to reproduce. To be precise:

**I've created the following objects:** 
- Group: groupwithCustommarking (marking def = custom, marking type = custom1, with the right create and access knowledge)
   - user: userwithCustommarking, org filigran
- groupwithTLPmarking (marking def = TLP, marking type = TLP:RED , with the right create and access knowledge)
   - user: userwithTLPmarking, org filigran
- groupwithCustomAndTlpmarking (marking def = custom AND TLP, marking type = custom1 AND TLP:RED, with the right create and access knowledge)
   - user: userwithCustomAndTLPmarking, org filigran

**With an Admin user, I've created 3 reports:** 
- reportWithCustomMarking, shared with Filigran. Marking = custom1
- reportWithTlpMarking, shared with Filigran. Marking = TLP:RED
- reportWithCustomAndTLPmarking, shared with Filigran. Marking = custom1 AND TLP:RED

**Result**: 
- userwithCustommarking only sees reportWithCustomMarking
- userwithTLPmarking only sees reportWithTlpMarking
- userwithCustomAndTLPmarking sees all reports (reportWithCustomMarking, reportWithTlpMarking and reportWithCustomAndTLPmarking)


@debelyoo, in case it helps, in our config, default role has the bypass capability.

**Comment by debelyoo** [comment]
What is the order of the custom marking you created ?

**Comment by nino-filigran** [comment]
TLP:RED has 4 and custom1 has 0.

**Comment by debelyoo** [comment]
OK. I actually found what was wrong in my use case. 
I created multiple markings with the same marking type. But I actually needed markings of different types to implement the access rules I had in mind.

Thanks for having looking at it.

**Comment by nino-filigran** [comment]
Great to hear that at least, we found what is wrong (and that we do not disclose information that we should not). I'm closing this issue for now. If you have any problem with this topic, I'll let you reopen it.
