### ISSUE TITLE
Expand name in "progress works panel"

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#3154]
## Use case

I would like to have in the name the following string: `Reports from 2020-01-01T00:00:00Z to 2022-12-31T23:59:59Z`
![image](https://user-images.githubusercontent.com/4184292/231793656-035f1444-9313-4e40-a9d4-009c50adf142.png)

#### If the feature request is approved, would you be willing to submit a PR?

No

**Comment by SamuelHassine** [comment]
Increase the limit of the name characters and a tooltip with mouseover to display everything.
