### ISSUE TITLE
Unknown Opinion in related entities and timelines

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3156]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps
- Go to the overview of an entity
- Add an opinion
![image](https://user-images.githubusercontent.com/75783086/232035358-22789dec-ae1e-442e-8d1e-73d52ece557c.png)
- refresh
- in the list of related entities, the opinion is displayed as Unknown
- in Knowledge > Timeline : the opinion is displayed as Unkown

## Expected Output

the default value of the opinion

## Actual Output

'unknown'

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/75783086/232035208-c057b641-eb35-4c82-91f7-93ac6747633b.png)

![image](https://user-images.githubusercontent.com/75783086/232035567-9ec3fed5-b15c-4fb0-a259-143c48b664cb.png)

**Comment by SamuelHassine** [comment]
@Archidoit, closing this, problem is deeper: #3168. Opinion resolver is certainly not correct but still, opinions SHOULD NOT be displayed here.
