### ISSUE TITLE
Collect reader feedbacks

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3159]
## Use case

Read-only user in the platform should be able to express their feedbacks on the content and on the platform itself.

Feature to implement:

- Associate Opinion edition to the "Access to collaborative creation" capability
- Associate Note addition to the "Access to collaborative creation" capability
- Verify that read-only user can use the general Feedback feature under Profile
- general Feedbacks are displayed in a dedicated panel (as Cases to respond)

**Comment by Jipegien** [comment]
Has been covered by the work on #3003
