### ISSUE TITLE
Be able to define default dashboards in groups / organizations

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3163]
## Use case

Administrator needs to be able to define default Dashboard in Settings for Groups and Organizations. Default Dashboards need to be listed in Overview of Users, Group and Organizations (As this feature requires to implement an overview of an organization in the settings panel, need sync with https://github.com/OpenCTI-Platform/opencti/issues/3520).

Users without admin (or dedicated) capability should not be able to modify the content of Group, Organization default Dashboards.

For a user when login, this order should apply for the default dashboard:
- User defined (already implemented)
- Organization defined
- Group defined

**Comment by Jipegien** [comment]
should be done after #2853

**Comment by SamuelHassine** [comment]
Need to discuss this @Jipegien

**Comment by SamuelHassine** [comment]
Only groups and organizations, no roles.
