### ISSUE TITLE
Be able to customize the pagination window in the native TAXII server

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3170]
## Use case

When consuming the native OpenCTI TAXII Server, default number of results is 100 (window). If the feed contains 1 millions of objects to be fetched, the number of required queries to paginate over all of them create a useless overhead.

==> Implement a settings to customize the pagination window of the TAXII server with a maximum of 10,000.

**Comment by richard-julien** [comment]
Let move the max size to 500 to limit some round trips
