### ISSUE TITLE
Be able to filter on empty values

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3171]
## Use case

Add the possibility to filter on empty / null values. A few examples:

* List of reports with no author
* List of cases with no assignee
* List of threat actor with no primary_motivation

etc.

**Comment by Jipegien** [comment]
This has been solved.

**Comment by nino-filigran** [comment]
This is in place, with the new filter. I'm closing this ticket. Feel free to re-open it if you think it's needed.
