### ISSUE TITLE
OpenCTI Slack Link Broken

### ISSUE THREAD

**Issue by AliceGrey** [LuatixHQ/opencti#3174]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

The slack link at https://community.filigran.io/ is no longer valid

## Environment
N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click https://community.filigran.io/

## Additional information
N/A

**Comment by SamuelHassine** [comment]
Hello @AliceGrey,

Thanks a lot for the heads-up! It's now solved.

Kind regards,
Samuel

**Comment by AliceGrey** [comment]
@SamuelHassine link is broken again. Slack invite is no longer active.

**Comment by SamuelHassine** [comment]
Thanks @AliceGrey, solved!
