### ISSUE TITLE
Increase audit logging capabilities with more data points

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3176]
## Use case

Increase audit logging capabilities with more data points:

* Login / logout events, including unsuccessful login events
* Users management events (create / update / delete)
* Groups management events (create / update / delete)
* Role management events (create / update / delete)
* All Users / Groups / Roles relations events (add user to group, add role to group, etc.)
* All "entity types" configuration changes (enforce references, custom mandatory attributes, etc.)

Also: provide a documentation listing all logged events in Notion.

**Comment by richard-julien** [comment]
Close as duplicate of https://github.com/OpenCTI-Platform/opencti/issues/2509
