### ISSUE TITLE
Deprecated filters with deleted entities as value

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3179]
## Use case

When an entity is deleted, filters with this entity in their values are still present in the platform.

## Current Workaround

If an entity is deleted, what do we do with elements with this entity in their filters?
Example of concerned filters: labelledBy (a deleted label) / contains (a deleted entity) / fromId / toId / createdBy...
Example of elements that can have such deprecated filters: triggers, streams, taxii collection, entity lines display...

Example: a stream with a filter pointing to a deleted entity.
What do we do with the stream?
    - delete the stream ? 
    - mark the stream as deprecated ?
    - delete the deprecated filter in the stream? (and even delete the stream if no filter is remaining)

**Comment by Archidoit** [comment]
Will be resolved in #2686

**Comment by nino-filigran** [comment]
Closing this issue given your comment @Archidoit
