### ISSUE TITLE
Add participants in addition to assignees everywhere

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3180]
## Use case

- Having a way for a user to know who is involved in a Case (to eventually reach out)
- Having a quick way for users to see which Case they are involved in.

## To implement

- [ ] Allowing user to see Assignee and Participant of a Case in the Overview
    - [ ] In Overview of Cases: Add a list of “Participants”(Same as “Assignees” list)
-  [ ] Allowing user with enough rights to create and update Cases by adding/removing Assignees and Participants
    - [ ] In Creation form and Update form: Add a field to set Participants (as Assignees)
    - [ ] In Overview of Cases: Add a “+” button inline with Assignee to Add Assignee (same as Labels)
-  [ ] Allowing users to see which Cases they are “assigned to” (the user is an assignee of the Case) and which they are “participant to” (the user is a participant of the Case)
    - [ ] In Cases’ list: replace column “Author” by a column “Assignee”
    - [ ] Be able to set a dashboard widget query with “participants” (same as assignee)
    - [ ] Communicate the way to create a dashboard widget to list all Cases with specific assignee field or participant field

**Comment by Jipegien** [comment]
Details added in description
