### ISSUE TITLE
Be able to create an analyst workbench from an entity

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3188]
## Use case

In the "Data" section of an entity, the top right panel is for attached pending STIX bundles (aka Analyst workbenches).

![image](https://user-images.githubusercontent.com/1334279/232694681-f73f78b9-3202-4bc7-8fb6-d9b39fc1a8ca.png)

There is no reason to not having a "+" button here to be able to create an empty workbench (aka empty STIX JSON file in pending mode) from this screen.

**Comment by Jipegien** [comment]
The associated analyst workbench(es) should then be visible in the list below the button.

By extension, for every Entity, Data tab should display analyst workbenches containing the Entity.
