### ISSUE TITLE
Add a new capability (RBAC) for RFI / RFT creation

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3198]
## Use case

Add a new capability (RBAC) for RFI / RFT creation.

Those types of case are not like other "Knowledge" objects.

**Comment by Jipegien** [comment]
Will be done with #3181

**Comment by Jipegien** [comment]
Closed as will be covered by https://github.com/fbicyber/opencti__opencti/tree/capabilities_by_entity_types.
