### ISSUE TITLE
Can't create Data sharing Feed CSV

### ISSUE THREAD

**Issue by 2xyo** [LuatixHQ/opencti#3199]
## Description

I can't create a CSV feed.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 5.17.1
3. OpenCTI client: frontend
4. Other environment details: docker-compose 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Data
2. Click Data Sharing
3. Click Feeds (CSV)
4. Click (+)
5. Fill "Name" field
6. Click [Entity Types]
7. Click any entity

## Expected Output

no error

## Actual Output

Error in console 

````
front-XQBQSTU5.js:190137 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at y (front-XQBQSTU5.js:190137:1814)
    at onChange (front-XQBQSTU5.js:190137:5003)
    at front-XQBQSTU5.js:32146:1482
    at Me (front-XQBQSTU5.js:9704:41672)
    at front-XQBQSTU5.js:9784:69504
    at Object.PAi (front-XQBQSTU5.js:5:10009)
    at EAi (front-XQBQSTU5.js:5:10174)
    at DAi (front-XQBQSTU5.js:5:10234)
    at Gpt (front-XQBQSTU5.js:5:32092)
 ````

Can't click on [Create] button

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/31675/232852459-b68e1b57-6a86-4078-8dbd-11bb68029116.png)

**Comment by richard-julien** [comment]
Thanks for the report, I dont think this create any issue in the creation but will be fixed asap.
