### ISSUE TITLE
Problem that data name after "_" cannot be searched

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3204]
OpenCTI version: 5.6.2

When creating a data name, the value after "_" is not visible in the search.
![image](https://user-images.githubusercontent.com/19428462/233232151-fcabeb80-4556-4b22-8162-7f7d202830a9.png)
![image](https://user-images.githubusercontent.com/19428462/233232254-cd0ffafb-68a6-43bc-93f2-1385e4b0a92d.png)
![image](https://user-images.githubusercontent.com/19428462/233232300-cdf8cbca-e352-4225-9e6f-468e97980815.png)

I think this is a very inconvenient and serious problem because a large amount of artifact information (malware filename, URL, etc.) contains "_".

Hopefully this issue will be fixed in the next update.

Thank you for reading :)

**Comment by richard-julien** [comment]
Its more than a bug, you need a way to have some wildcard prefix search.
We plan to have some advance search to do it in https://github.com/OpenCTI-Platform/opencti/issues/2486
Closing this one.
