### ISSUE TITLE
Relationships containing not visible entities for a certain user gives a platform error

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#3208]
## Description

When trying to render a relationship (for example in Rerports, or Incidents, or searching for relationships in Data section), if it contains a source or a target which is not visible by the user (the user cannot access to a specified marking or the entity was not shared with his organization), a platform error arises.

This makes impossible to consult every page which contains at least one relationship of that kind.

## Environment

1. OS: the officiale OpenCTI Platform Docker image
2. OpenCTI version: OpenCTI 5.7.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
0. Operate as Admin user to speed up the process
1. Use 2 different Organizations (eg. A and B) and assign a user to one of them
2. Create 2 entities of any kind to use into a relationship
3. Share one entity with both orgs and the other only with the organization that doesn't contain the user
4. Create a relationship that uses the entities created as source and target
5. Try to access the relationships view in the Data section or in some other section that can contain it (Events/Analysis/etc)
6. The error of the screenshot should arise

## Expected Output

I suppose that the relationship that has the source or the target not visible for the user should be partially or not visible.

## Actual Output

The platform gives an error which causes the entire window to be emptied (like in the screenshot).

## Additional information

Looking at the platform logs, the error given by OpenCTI is the following:

```
{
    "category": "APP",
    "error": {
        "stacktrace": [
            "Error: Cannot return null for non-nullable field StixCoreRelationship.from.",
            "at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:594:13)",
            "at /opt/opencti/build/node_modules/graphql/execution/execute.js:486:9",
            "at processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "at async Promise.all (index 1)",
            "at async Promise.all (index 0)",
            "at async Promise.all (index 1)",
            "at async Promise.all (index 0)",
            "at async Promise.all (index 0)",
            "at k (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:501:14)",
            "at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:407:22)",
            "at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"
        ]
    },
    "inner_relation_creation": 0,
    "level": "error",
    "message": "API Call",
    "operation": "StixCoreRelationships",
    "operation_query": "query StixCoreRelationships($elementId:[String]$elementWithTargetTypes:[String]$fromId:[String]$fromTypes:[String]$toId:[String]$toTypes:[String]$relationship_type:[String]$startTimeStart:DateTime$startTimeStop:DateTime$stopTimeStart:DateTime$stopTimeStop:DateTime$filters:[StixCoreRelationshipsFiltering]$first:Int$after:ID$orderBy:StixCoreRelationshipsOrdering$orderMode:OrderingMode){stixCoreRelationships(elementId:$elementId elementWithTargetTypes:$elementWithTargetTypes fromId:$fromId fromTypes:$fromTypes toId:$toId toTypes:$toTypes relationship_type:$relationship_type startTimeStart:$startTimeStart startTimeStop:$startTimeStop stopTimeStart:$stopTimeStart stopTimeStop:$stopTimeStop filters:$filters first:$first after:$after orderBy:$orderBy orderMode:$orderMode){edges{node{relationship_type from{...on StixCoreObject{standard_id entity_type}}to{...on StixCoreObject{standard_id entity_type}}}}pageInfo{startCursor endCursor hasNextPage hasPreviousPage globalCount}}}",
    "size": 550,
    "time": 2899,
    "timestamp": "2023-04-19T07:35:41.401Z",
    "type": "READ_ERROR",
    "user": {
        "ip": "::ffff:10.0.7.4",
        "user_id": "5f1c7d84-2489-4959-bd4f-9e3c6aeb6575"
    },
    "variables": {
        "after": null,
        "elementId": null,
        "elementWithTargetTypes": null,
        "filters": [],
        "first": 100,
        "fromId": null,
        "fromTypes": [
            "ipv4-addr",
            "domain-name",
            "indicator",
            "incident",
            "campaign",
            "observable",
            "organization",
            "url",
            "threat-actor",
            "malware"
        ],
        "orderBy": null,
        "orderMode": null,
        "relationship_type": "attributed-to",
        "startTimeStart": null,
        "startTimeStop": null,
        "stopTimeStart": null,
        "stopTimeStop": null,
        "toId": null,
        "toTypes": [
            "tool",
            "incident",
            "instrusion-set",
            "sector",
            "observable",
            "attack-pattern",
            "organization",
            "campaign",
            "intrusion-set",
            "threat-actor",
            "malware"
        ]
    },
    "version": "5.7.1"
}
```

## Screenshots

![image](https://user-images.githubusercontent.com/14950949/233403092-fd1c3ccc-6d7d-4bab-a909-a7b80b8dc60f.png)

**Comment by rgsax** [comment]
With version 5.7.2 the problem is partially fixed. Now the relationships are visible, but the error arises when trying to visualize the single relationship details.

**Comment by richard-julien** [comment]
I have also tried that during the fix.
Can you give more info on the type of relationship?

**Comment by rgsax** [comment]
It seems that the error occurs only with automatically inferred relationships.
