### ISSUE TITLE
Unknown type \"StixMetaRelationshipAddInput\". Did you mean...

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#3212]
## Description

Messages as the one below appear in error log after update to 5.7.2 from 5.7.0
There are about 20 of them so far. Updated 30min ago.

{
  "category": "APP",
  "error": { "stacktrace": [ "GraphQLError: Unknown type \"StixMetaRelationshipAddInput\". Did you mean \"StixRefRelationshipAddInput\", \"StixCoreRelationshipAddInput\", \"StixRefRelationshipsAddInput\", \"InternalRelationshipAddInput\", or \"StixSightingRelationshipAddInput\"?", "at Object.NamedType (/opt/opencti/build/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)", "at Object.enter (/opt/opencti/build/node_modules/graphql/language/visitor.js:301:32)", "at Object.enter (/opt/opencti/build/node_modules/graphql/utilities/TypeInfo.js:391:27)", "at visit (/opt/opencti/build/node_modules/graphql/language/visitor.js:197:21)", "at validate (/opt/opencti/build/node_modules/graphql/validation/validate.js:91:18)", "at validate (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:474:12)", "at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:265:30)", "at processTicksAndRejections (node:internal/process/task_queues:95:5)", "at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)" ] },
  "inner_relation_creation": 0,
  "level": "error",
  "message": "API Call",
  "operation": "Unspecified",
  "operation_query": "mutation StixCyberObservableAddRelation($id:ID!$input:StixMetaRelationshipAddInput){stixCyberObservableEdit(id:$id){relationAdd(input:$input){id}}}",
  "size": 147,
  "time": 5,
  "timestamp": "2023-04-21T09:28:12.559Z",
  "type": "READ_ERROR",
  "user": {
    "ip": "::ffff:10.113.100.20",
    "user_id": "fb7afd2-77f9-403a-92b0-50sdfa10"
  },
  "variables": {
    "id": "ipv4-addr--b5XXX-5177-5e46-98f3-383XXXXX5ad9",
    "input": {
      "relationship_type": "object-label",
      "toId": "7c3XXX3c-bXXX-4XX7-9XX5-9XXXXXXXXd"
    }
  },
  "version": "5.7.2"
}

## Environment

1. Ubuntu 22
2. OpenCTI version: 5.7.2
3. OpenCTI client: Don't know
4. Other environment details: Bare metal installation

**Comment by AlexSanchezN** [comment]
Just to add information:
I was seeing the same error in some connector logs (AbuseIPDB).
We solved by installing latest requirements (pip3 install -r requirements.txt) 
This was done on another machine where we run connectors and workers, not on the ones that run the platform

**Comment by SamuelHassine** [comment]
Yes, definitely linked to an outdated Python client.
