### ISSUE TITLE
No distribution statistics in incidents

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#3213]
## Description

There use to appear some circular graphics in Incidents->Overview. They are no longer shown, I think since 5.7.0
Although there are indicators and observables associated to the incident, the graphics never appear: 
![image](https://user-images.githubusercontent.com/6607235/233621662-d32ddbf2-7527-4ee1-869e-d1dbb13a8de4.png)
![image](https://user-images.githubusercontent.com/6607235/233621260-9146f5d8-7ad9-461f-8d24-fbf9f25b18f4.png)

The problem appears in our developement and production environments
Please, excuse if this is a new behavior.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22
2. OpenCTI version: 5.7.2
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Go to Incidents -->Overview

**Comment by RomuDeuxfois** [comment]
Hi @AlexSanchezN ,

Can you try to extend the time slot of your incident ? To see if your data comes back.

From what I see, the date of first seen and last seen are identical (seconds included).

**Comment by AlexSanchezN** [comment]
Hi @RomuDeuxfois
Please see attached image. We have extended the incident for 1h and the result is the same:

![image](https://user-images.githubusercontent.com/6607235/234519861-4fe77279-c59f-4d3f-b36c-76f0232fd269.png)

Circular graphics where there in versions 5.6.x with the incidents created the same way. A single port scan does hardly take more than milliseconds.
The same result with incidents that are longer:

![image](https://user-images.githubusercontent.com/6607235/234519782-a981c1e5-c90f-4758-ac45-90a66403b2aa.png)

Cheers

**Comment by RomuDeuxfois** [comment]
Hi @AlexSanchezN ,

Thank you for the information given, we were able to investigate and fix the bug.
