### ISSUE TITLE
Version 5.7.2 partially fixes the relationships visibility problem. The relationships are visible, but the error arises when trying to visualize the single relationship details.

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#3215]
With version 5.7.2 the problem is partially fixed. Now the relationships are visible, but the error arises when trying to visualize the single relationship details.

_Originally posted by @rgsax in https://github.com/OpenCTI-Platform/opencti/issues/3208#issuecomment-1517828333_

**Comment by richard-julien** [comment]
I have also tried that during the fix.
Can you give more info on the type of relationship?

**Comment by rgsax** [comment]
It seems that the error occurs only with automatically inferred relationships.

Like the following
![image](https://user-images.githubusercontent.com/14950949/233649567-54ccca45-d096-4168-8866-422a5cd30e1e.png)

**Comment by richard-julien** [comment]
Nice catch you're right, if an element is missing in the explanation due to access right, an error occured.
Will look on that quickly

**Comment by rgsax** [comment]
@richard-julien 
The error seems to be still present for relationships with restricted entity as target (if the restricted entity is the source, everything works fine).

Just for clarification:
This works
![image](https://user-images.githubusercontent.com/14950949/235870622-4736e4e8-d63b-40ea-b928-471d54f3f54a.png)

---

This doesn't work
![image](https://user-images.githubusercontent.com/14950949/235871222-b76e985b-3699-490f-979c-17f7483f9744.png)
