### ISSUE TITLE
Ambiguous Error For SSO Failure when Missing Groups

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#3223]
Working on investigating the “Invalid authentication, please ask your administrator” error when using OIDC for SSO.

I’ve included an error below that was logged after the messages **[OPENID] Successfully logged** and **[OPENID] Groups mapping on decoded id_token** so login was successful and OpenCTI acquired the groups associated with the user account.

`{"0":"L","1":"O","2":"G","3":"I","4":"N","category":"APP","level":"error","message":{"origin":{"ip":"::ffff:10.1.14.159"}},"timestamp":"2023-04-23T00:03:08.041Z","version":"5.7.2"}`

Continued investigating and added a debug statement to line 258 of httpPlatform.js, and I encountered the actual error message:

`[SSO] Can't login. The user has groups that don't exist and auto_create_group = false.`

I think other users will run into this same issue eventually, so this issue is for updating the error logging.

Additionally, the documentation is vague and specifies that "else: an error is raised.", so updating that will help users in troubleshooting in the future.

**Comment by SamuelHassine** [comment]
Hello @YungBinary,

Thanks a lot, the error message you got is not normal.

@team we need to log the true error message  "[SSO] Can't login. The user has groups that don't exist and auto_create_group = false."
