### ISSUE TITLE
App - Error Platform cannot get the lock for initialization

### ISSUE THREAD

**Issue by mattseymour** [LuatixHQ/opencti#3226]
## Description

I am trying to upgrade to OpenCTI 5.7.1 / 5.7.2 and i get the following error (resulting in the app not starting).

```
{
   "category":"APP",
   "error":{
      "context":{
         "category":"business",
         "http_status":500,
         "participantIds":[
            "platform_init_lock"
         ],
         "reason":"[OPENCTI] Platform cant get the lock for initialization (can be due to other instance currently migrating/initializing)"
      },
      "message":"Lock timeout",
      "name":"LockError",
      "stack":"LockError: Lock timeout\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at LockTimeoutError (/opt/opencti/build/src/config/errors.js:100:51)\n    at platformInit (/opt/opencti/build/src/initialization.js:388:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:168:5)"
   },
   "level":"error",
   "message":"[OPENCTI] Platform start fail",
   "timestamp":"2023-04-24T09:40:48.280Z",
   "version":"5.7.2"
}
```

## Environment

1. OS (where OpenCTI server runs): Opencti platform docker image
2. OpenCTI version: 5.7.0-> 5.7.2
3. OpenCTI client: platform - backend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upgrade opencti from 5.6

## Expected Output

Opencti is working

## Actual Output
Opencti server fails to run. 

## Additional information

Upgrade / migration.

**Comment by SamuelHassine** [comment]
Hello @mattseymour,

Migration is still on-going on another instance of your cluster. just wait for the migration to finish (it can take some time).

Kind regards,
Samuel

**Comment by mattseymour** [comment]
Where is the lock for this held? Elastic, Redis, Rabbit? The reason for asking is, if the platform app crashed while in process whats the recovery process around this, how do i know that i'm not waiting for a lock which will ever be released. Just want to check i am waiting for something that will end.

**Comment by mattseymour** [comment]
Confirmed that this process can take a long time and the system will not be responsive until complete. In my instance the migration took 3 days to complete. It is now up and running successfully.
