### ISSUE TITLE
Missing first_seen date causes errors in data synchronization

### ISSUE THREAD

**Issue by ristowee** [LuatixHQ/opencti#3238]
## Description

If e.g. a sighting object does not have a `first_seen` date set (shown as **None** in UI and as 1970-01-01T00:00:00.000Z in ElasticSearch) the value is dropped in the stream and the receiver tries to create one based on the current date.

If the `last_seen` is earlier than current date (usually the case) the receiver cannot write the data and prints an error:
```"reason": "You cant create a relation with last_seen less than first_seen"```

Of course an empty `first_seen` is not desirable but we have seen it in our system—probably created by an enrichment connector.

## Environment

1. OS (where OpenCTI server runs): Debian Buster
2. OpenCTI version: 5.7.2
3. OpenCTI client: frontend (/backend?)
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
- Create a sighting
- Edit the `first_seen` date in ElasticSearch:
```
POST opencti_stix_sighting_relationships-000001/_update/SIGHTING_INTERNAL_ID
{
  "doc": {
    "first_seen": "1970-01-01T00:00:00.000Z"
  }
}
```
- Create & start a synchronization stream at the client before the addition time (with `recover` date). The stream ingestion must be off when doing the dirty Elastic hack.

The stream should have a sighting object without a `first_seen` value:

`id: 1682512983594-0`
`event: create`
`` data: {"data":{"id":"sighting--d941b2bb-9a59-4b74-9b63-a90c4dec0b3b","spec_version":"2.1","type":"sighting","extensions":{"extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba":{"extension_type":"property-extension","id":"ba230d6b-0037-4d8a-be8f-ef5841d9ece3","type":"stix-sighting-relationship","created_at":"2023-04-26T12:39:41.894Z","updated_at":"2023-04-26T12:43:03.594Z","is_inferred":false,"creator_ids":["88ec0c6a-13ce-5e39-b486-354fe4a7084f"],"sighting_of_value":"one.two","sighting_of_ref":"97cc1a5d-c440-4ed3-9515-5c434b77927c","sighting_of_type":"Domain-Name","where_sighted_values":["Zimbabwe"],"where_sighted_refs":["230f9a23-01fb-4134-8295-a7b15caf3bac"],"where_sighted_types":["Country"],"where_sighted_refs_object_marking_refs":["3cc54463-4c50-43f4-a4d1-3a9ed7de0e4a"],"negative":false}},"created":"2023-04-26T12:39:41.894Z","modified":"2023-04-26T12:43:03.594Z","revoked":false,"confidence":75,"lang":"en","last_seen":"2023-04-25T21:17:00.000Z","count":1,"sighting_of_ref":"domain-name--baea1a9d-84d6-590f-a7eb-175beb0ebf01","where_sighted_refs":["location--e5e12939-fe9a-5e19-804f-9ad8ceec2889"]},"message":"creates the relation stix-sighting-relationship from `one.two` (Domain-Name) to `Zimbabwe` (Country)","origin":{"referer":"init-create"},"version":"4"} ``

## Expected Output

The sighting is somehow ingested in the system. Possibly with a **None** or some other sensible date in the `first_seen`.

## Actual Output

The sighting is not created and the log shows:

```
{
  "category": "APP",
  "error": {
    "data": {
      "category": "technical",
      "from": null,
      "http_status": 500,
      "input": {
        "_index": "opencti_stix_sighting_relationships",
        "attribute_count": 1,
        "confidence": 75,
        "created": "2023-04-26T12:39:41.894Z",
        "createdBy": null,
        "description": null,
        "entity_type": "stix-sighting-relationship",
        "externalReferences": [
        ],
        "first_seen": "2023-04-26T13:15:50.000Z",
        "from": {
          "--8<-- Clipped --8<-- "
        },
        "fromId": null,
        "last_seen": "2023-04-25T21:17:00.000Z",
        "modified": "2023-04-26T12:43:03.594Z",
        "objectLabel": [
        ],
        "objectMarking": [
        ],
        "relationship_type": "stix-sighting-relationship",
        "stix_id": "sighting--d941b2bb-9a59-4b74-9b63-a90c4dec0b3b",
        "to": {          
          "--8<-- Clipped --8<-- "
        },
        "toId": null,
        "update": true,
        "x_opencti_negative": false,
        "x_opencti_stix_ids": null
      },
      "reason": "You cant create a relation with last_seen less than first_seen"
    },
    "stacktrace": [
      "DatabaseError: A database error has occurred",
      "at error (/opt/opencti/build/src/config/errors.js:8:10)",
      "at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)",
      "at buildRelationData (/opt/opencti/build/src/database/middleware.js:2610:13)",
      "at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2763:17)",
      "at createRelation (/opt/opencti/build/src/database/middleware.js:2809:16)",
      "at addStixSightingRelationship (/opt/opencti/build/src/domain/stixSightingRelationship.js:98:19)"
    ]
  },
  "inner_relation_creation": 0,
  "level": "warn",
  "message": "API Call",
  "operation": "StixSightingRelationshipAdd",
  "operation_query": "mutation StixSightingRelationshipAdd($input:StixSightingRelationshipAddInput!){stixSightingRelationshipAdd(input:$input){id standard_id entity_type parent_types}}",
  "size": 513,
  "time": 30,
  "timestamp": "2023-04-26T13:15:50.511Z",
  "type": "WRITE_ERROR",
  "user": {
    "applicant_id": "6a4b11e1-90ca-4e42-ba42-db7bc7f7d505",
    "call_retry_number": "1",
    "ip": "::ffff:172.18.0.8",
    "user_id": "6a4b11e1-90ca-4e42-ba42-db7bc7f7d505"
  },
  "version": "5.7.2"
}
```

**Comment by ristowee** [comment]
Hmm. This should set the **None** value if the value is missing:
https://github.com/OpenCTI-Platform/opencti/blob/5.7.2/opencti-platform/opencti-graphql/src/database/middleware.js#L2606
But why does this still happen and where does the current date come from?

**Comment by richard-julien** [comment]
Ok so after dig in looks like it comes from the python lib

```
            date = datetime.datetime.today().strftime("%Y-%m-%dT%H:%M:%SZ")
            ...
            first_seen=stix_sighting["first_seen"]
            if "first_seen" in stix_sighting
            else date,
            last_seen=stix_sighting["last_seen"]
            if "last_seen" in stix_sighting
            else date,
```

Will talk with the team about that.

**Comment by richard-julien** [comment]
On python client, removing the default value: https://github.com/OpenCTI-Platform/client-python/issues/359
On platform, opening the first/last seen to setup empty values.
