### ISSUE TITLE
Duplicate Custom Dashboard

### ISSUE THREAD

**Issue by Arcuza** [LuatixHQ/opencti#3241]
## Use case

I often find it useful to be able to duplicate a Custom Dashboard

## Current Workaround

Create a new Custom Dashboard and create widgets from scratch.

## Proposed Solution

Add the Custom Dashboard Duplicate menu item to the existing Update and Delete and make the duplication.

## Additional Information

No

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
@Arcuza this has been done in 5.12: https://github.com/OpenCTI-Platform/opencti/issues/3242
