### ISSUE TITLE
In threat actors / intrusion sets / campaigns list, search keyword is not remembered 

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3251]
## Description

In threat actors / intrusion sets / campaigns list, search keyword is not remembered .

1. Threat actor list => Search for a threat actor
2. Come back on dashboard
3. Go back to threat actor list, search keyword is not here

**Comment by Archidoit** [comment]
same issue in other js entities: malwares, events, attack patterns, organizations...
