### ISSUE TITLE
Better handling of empty trigger outcome

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3256]
## Use case

Repro case:

* Create a trigger (any filter) with output = Email
* Update the trigger and remove all outputs so there is no more output for the trigger
* Reload the page

The whole screen is broken

**Comment by Archidoit** [comment]
bug resolved in #2853 
associated PR: https://github.com/OpenCTI-Platform/opencti/pull/3144

**Comment by richard-julien** [comment]
Any quick fix we can do before merging the complete feature of quick subscription @Archidoit ?

**Comment by Archidoit** [comment]
@richard-julien  i'm going to do a quick fix and the whole correct behavior (at least 1 outcome in the attribute 'outcomes' and at least 1 event in the attribute 'trigger_events' for live triggers) will be implemented in the feature of quick subscription
