### ISSUE TITLE
SSL Wrong Version Number Error when trying to receive email notification

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#3278]
## Description

Using Office365 Outlook as smtp server, when a new notification has to be sent, the following error arises:

```
{
"category": "APP",
    "error": {
        "context": {},
        "message": "78DB74A4C77F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n",
        "name": "Error",
        "stack": "Error: 78DB74A4C77F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n"
    },
    "level": "error",
    "message": "[OPENCTI-MODULE] Error executing publication",
    "timestamp": "2023-05-04T11:36:25.818Z",
    "version": "5.7.3"
}

```

I don't know if the error is given also for other providers.

## Environment

1. OS: Official OpenCTI Docker Image
2. OpenCTI version: OpenCTI 5.7.3
3. OpenCTI client: frontend

## Reproducible Steps

1. Create a new subscription (eg. for new observables)
2. Trigger the creation of a notification (eg. create an observable)

## Expected Output

An email notification should be sent

## Actual Output

Nothing happens. The error is displayed in the logs.

## Additional information

There are no additional information.

**Comment by richard-julien** [comment]
Looks like the mail needs more option https://github.com/nodemailer/nodemailer/issues/165
I will add some extra parameters to allow that
