### ISSUE TITLE
OpenCTI down after upgrading from 5.6.2 to 5.7.4

### ISSUE THREAD

**Issue by sanam-arora** [LuatixHQ/opencti#3282]
opencti-platform logs
`{"category":"APP","error":{"context":{"category":"technical","error":"connect ECONNREFUSED 172.24.0.2:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:61:53)\n    at /opt/opencti/build/src/database/engine.js:174:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:164:3)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:131:3)\n    at platformStart (/opt/opencti/build/src/boot.js:164:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-05-05T06:58:17.123Z","version":"5.7.4"}`

elasticsearch logs
`{"@timestamp":"2023-05-05T06:58:26.232Z", "log.level": "WARN",  "data_stream.dataset":"deprecation.elasticsearch","data_stream.namespace":"default","data_stream.type":"logs","elasticsearch.event.category":"api","event.code":"ignore_throttled_param","message":"[ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices." , "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"deprecation.elasticsearch","process.thread.name":"elasticsearch[f03b331e7b62][transport_worker][T#4]","log.logger":"org.elasticsearch.deprecation.action.support.IndicesOptions","elasticsearch.cluster.uuid":"RDzvOYpiShmGRJemtJ4WTA","elasticsearch.node.id":"gSBdT62NRJGFH8pib745XA","elasticsearch.node.name":"f03b331e7b62","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2023-05-05T06:58:19.760Z", "log.level": "INFO", "message":"successfully loaded geoip database file [GeoLite2-City.mmdb]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[f03b331e7b62][generic][T#5]","log.logger":"org.elasticsearch.ingest.geoip.DatabaseNodeService","elasticsearch.cluster.uuid":"RDzvOYpiShmGRJemtJ4WTA","elasticsearch.node.id":"gSBdT62NRJGFH8pib745XA","elasticsearch.node.name":"f03b331e7b62","elasticsearch.cluster.name":"docker-cluster"}`

**Comment by Kedae** [comment]
Hello @sanam279 , the log from Elastic is a warning, it does not indicate any issue. But OpenCTI does tell you that your elastic is down, can you check the status ? Have you tried starting it again ?

**Comment by sanam-arora** [comment]
> Hello @sanam279 , the log from Elastic is a warning, it does not indicate any issue. But OpenCTI does tell you that your elastic is down, can you check the status ? Have you tried starting it again ?

Tried starting the stack multiple times. Same story. OpenCTI won't come up.

**Comment by Kedae** [comment]
Can you provide more log for elastic then ?

**Comment by misohouse** [comment]
When I upgrade 5.7.x, I had a similar problem with ElasticSearch.

In my case, I solved problem by changing docker-compose in portatiner.io.

I attached my docker-compose.

![image](https://user-images.githubusercontent.com/19428462/236708641-e87f7b79-a8f3-4312-8e94-241d098a73ff.png)

The changed part is the red square part.

I hope this helps :)
