### ISSUE TITLE
5.7.4 version packages problem

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#3289]
## Description

There seems to be some problem with packages available at github for version 5.7.4.
Packages are 196bytes long... you are good people, but nobody is that good compressing 😀
It looks like some problem with the build/packaging or similar

![image](https://user-images.githubusercontent.com/6607235/236443984-66d8e97b-e7e5-4b8a-b9f7-c0a02fe26a12.png)

The actual body of the 'packages' is: 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

**Comment by SamuelHassine** [comment]
Thanks for the heads up @AlexSanchezN. This is now solved.
