### ISSUE TITLE
Improve filtering indicators by valid_from and valid_until

### ISSUE THREAD

**Issue by gmlink1** [LuatixHQ/opencti#3292]
## Use case

Currently on the Observations->Indicators page if I were to filter by valid until a certain date, I get many expired indicators when I'd expect to see only those will still be valid at that date. I believe the root of the problem is that valid_from and valid_until are each their own dates rather than a single 'created' date with its own before and after filters up higher in the filter options.

## Current Workaround

Nothing truly viable without running graphql queries directly. Adding a revoked=No filter does not include indicators that continue to be valid past the date specified.

## Proposed Solution

It is possible to swap the _end_date and _start_date suffixes on the front end to achieve the behavior I'd expect, but that would break anyone using the current behavior. It may be best to set up separate before and after filters for each date field.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
Covered by new filtering system
