### ISSUE TITLE
Create a new capa to byPass mandatory fields

### ISSUE THREAD

**Issue by CyberKaizen** [LuatixHQ/opencti#3304]
## Problem to Solve

So I found something interesting. If I try to enforce mandatory attributes for the Report entity, it breaks the MITRE Datasets connector. If it breaks MITRE, it likely breaks other connectors handling it.
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/84a32058-49ae-4a6c-ac94-619dc06af04d)

The reason a user may want to enforce mandatory attributes on that, is to prevent users from improperly filling out the details for the Report entity.

The error I started getting from the worker logs was:
`2023-05-09T22:04:58.235430037Z ERROR:pycti.api:Invalid field createdBy`
`2023-05-09T22:04:58.235457637Z ERROR:root:{'name': 'ValidationError', 'message': 'Invalid field createdBy'}`
`2023-05-09T22:04:58.263740311Z ERROR:pycti.api:[SEARCH] Error updating elastic (update)`
`2023-05-09T22:04:58.263763511Z ERROR:pycti.api:Cannot report expectation`

The error pointed to something going wrong with the Author entity or createdBy field.
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/72408ae7-e561-4ec4-8bab-ae2868ee83a8)

The end result is that reports might still get output but certain entities or relationships getting excluded from the Report container.

I believe this error might be caused when certain fields in the STIX bundles have a null createdBy field, leading to that data getting excluded upon matching the mandatory attributes rules. 

## Current Workaround

To resolve this issue, undoing the enforcement of mandatory attributes on the Report entity causes the problem to go away.

But this means the user becomes unable to make use of the enforce mandatory attributes feature, because it breaks the connectors that handle the Report entity.

## Proposed Solution

I believe a sound, interim solution would be to add a new permission that can be added to the Connector Role, that would allow the connector to bypass mandatory field attributes.
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/eea3af8b-9f2d-4cd4-92c9-b98772d7680f)

A longer term solution I think should be considered is adopting the concept of internal service users (these handle all backend OpenCTI operations) and regular users. This is because often times, what we want to happen for a front end user is different from the service user (connector).

## Final approach
Create a new capa called "Bypass mandatory fields" that would allow admins to enable some custom mandatory attributes so that their connectors for instance will be able to byPass any fields that are marked as required, while analyst will be have to comply with the filling of the needed fields when creating or updating an entity.

**Comment by adel-akloul-mox** [comment]
As a more general rule, I would like least privileges for connectors service account as much as possible ! 
However I believe some capabilities required by connectors are simply missing, and therefore many of those connectors can’t work with the only Connector role, and we are required to `bypass all capabilities` which is excessive permissions.

```
AS a Cyber Engineer 
I WANT to have more capabilities 
SO THAT I am not required to provide `Adminstrator` role or `Bypass all capabilities`  for some connectors, 
AND I can tweak connector-specific capabilities with the principle of least privileges.
```

example of connectors that won't work with only `Connector` role and require additional `Bypass all capabilities` (non exhaustive list):
- alienvault
- misp-feed
- shodan-internetdb

example of connectors that work very well with only `Connector` role without additional privileged capabilities (non exhaustive list):
- mitre
- cape-sandbox
- cape

Documentation on which capabilities are required by each connector is totally missing

**Comment by nino-filigran** [comment]
@CyberKaizen I've slightly modified the title of your ticket make celarer the approach we would like to take on this topic: 
We will Create a new capa called "Bypass mandatory fields" that would allow admins to allow some users to not be force to add these custom fields.
This way, you could achieve your use case by: 
- providing all your connector users this capa 
- keep your analyst without the capa so that they would need to provide the mandatory custom attributes.

**Comment by labo-flg** [comment]
reopened until Feature Flag is removed
