### ISSUE TITLE
Missing relationship type in a knowledge screen

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3308]
## Description

1. In the knowledge section of Arsenal > Channels, when attempting to make a relationship with Vulnerabilities, the dropdown menu of Relationship type is empty and no relationship type can be selected.

=> Should be "targets"

3. In the knowledge section of Entities > Event, when attempting to make a relationship with Threat Actor, the dropdown menu of Relationship type is empty and no relationship type can be selected.

=> Should be "targets"

**Comment by Archidoit** [comment]
@SamuelHassine in Channel knowledge, relationship creation with a Malware has no relationship either. According to Relation.js, the relationship types would be: 'delivers' and 'drops'. Am I right?

There are also some inconsistencies between the relationship types describe in Relation.js and the ones available in the relationship creation forms of entities Knowledge.
Exemple:
- in Relation.js, 'Channel_Attack-Pattern': ['uses', 'drops', 'delivers'], 
- but in Channel Knowledge, the only relationship type available when creating a relationship with an attack pattern is 'used'.
--> Should this be modified?

SEEN WITH JULIEN AND ROMUALD
