### ISSUE TITLE
top:amber marking grants also access to top:amber+strict

### ISSUE THREAD

**Issue by eitlev** [LuatixHQ/opencti#3312]
## Description
When provisioning a user with permission to access TLP:AMBER markings the user is able to also access TLP:AMBER+STRICT, which should not be the case. 

## Environment
Hosted opencti at energicert.cloud.filigran.io

Steps to create the smallest reproducible scenario:
1. Create a group with Allowed Marking of TLP:GRENN
2. Add target user to the group
3. { e.g. Error ... }

## Expected Output
A user with TLP:AMBER marking permissions should not be allowed to see TLP:AMBER+STRICT

Group settings. 
<img width="1224" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/133096645/c412542f-f9aa-43a2-8d9a-0aca146e78a3">

User is not shown report marked as TLP:AMBER
<img width="1301" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/133096645/e66f1d3a-53e5-4553-8b61-a62416cbce20">

TLP:AMBER marking permission added to group 
<img width="1230" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/133096645/69b0392e-0bf8-449c-9eb1-fa2a4c16763e">

TLP:AMBER+STRICT reports are now accessible 
<img width="1299" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/133096645/ceb7f039-a0f4-4665-9b6b-5242b2676ec4">

The report is only marked with TLP:AMBER+STRICT
<img width="807" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/133096645/1a19df1d-9496-423a-a802-a009ffedae0c">

**Comment by SouadHadjiat** [comment]
Hello @eitlev ! What are your marking definitions ? If TLP:AMBER and TLP:AMBER+STRICT have the same order (3 by default), then users with TLP:AMBER can see both. If you want to change this, TLP:AMBER+STRICT should have a higher order.

![Capture d'écran 2023-05-11 135419](https://github.com/OpenCTI-Platform/opencti/assets/668192/efcf13ad-495e-43b9-8370-36f3d78c0995)

**Comment by eitlev** [comment]
They were. I have now changed this and will test. Thank you.

From: Souad Hadjiat ***@***.***>
Date: Thursday, 11 May 2023 at 14.55
To: OpenCTI-Platform/opencti ***@***.***>
Cc: Eitan Levi ***@***.***>, Mention ***@***.***>
Subject: Re: [OpenCTI-Platform/opencti] top:amber marking grants also access to top:amber+strict (Issue #3312)

EKSTERN MAIL

Hello @eitlev<https://github.com/eitlev> ! What are your marking definitions ? If TLP:AMBER and TLP:AMBER+STRICT have the same order (3 by default), then users with TLP:AMBER can see both. If you want to change this, TLP:AMBER+STRICT should have a higher order.

[Capture d'écran 2023-05-11 135419]<https://user-images.githubusercontent.com/668192/237694046-efcf13ad-495e-43b9-8370-36f3d78c0995.png>

**Comment by eitlev** [comment]
That fixed the issue. Thank you.

From: Eitan Levi ***@***.***>
Date: Thursday, 11 May 2023 at 15.00
To: OpenCTI-Platform/opencti ***@***.***>, OpenCTI-Platform/opencti ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [OpenCTI-Platform/opencti] top:amber marking grants also access to top:amber+strict (Issue #3312)
They were. I have now changed this and will test. Thank you.

From: Souad Hadjiat ***@***.***>
Date: Thursday, 11 May 2023 at 14.55
To: OpenCTI-Platform/opencti ***@***.***>
Cc: Eitan Levi ***@***.***>, Mention ***@***.***>
Subject: Re: [OpenCTI-Platform/opencti] top:amber marking grants also access to top:amber+strict (Issue #3312)

EKSTERN MAIL

Hello @eitlev<https://github.com/eitlev> ! What are your marking definitions ? If TLP:AMBER and TLP:AMBER+STRICT have the same order (3 by default), then users with TLP:AMBER can see both. If you want to change this, TLP:AMBER+STRICT should have a higher order.

[Capture d'écran 2023-05-11 135419]<https://user-images.githubusercontent.com/668192/237694046-efcf13ad-495e-43b9-8370-36f3d78c0995.png>

**Comment by SouadHadjiat** [comment]
Perfect, I'm closing the issue.
