### ISSUE TITLE
Set/change "Creation date" of relations

### ISSUE THREAD

**Issue by b1nbash** [LuatixHQ/opencti#3315]
## Prerequisites

- [ x ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [ x ] I went through old GitHub issues and couldn't find anything relevant
- [ x ] I googled the issue and didn't find anything relevant

## Description

Is it possible to set or change the "Creation date" of a relationship? If I add a relation between a threat actor and a region f.ex, I would want to set or edit the creation date of that specific relation.
This would help when visualizing data in custom dashboards. Now, newly added relations would show up on the current day in a dashboard widget, when the relation actually happened f.ex a year ago.

A workaround is to use the Python API and manually set the creation date of the relationship, but it would be helpful to have the same feature in the WEB-UI.

## Example

If I create a relationship: APT28 "targets" USA today (Creation date: May, 10th),
then the dasboard widget with the required filters will show that on May, 10th APT28 targeted USA

But what I want is to edit the "Creation date" such that I could choose which date APT28 *actually* targeted USA, and then correctly show this on the dashboard widget.

**Comment by Jipegien** [comment]
At the creation of the relationship, you have to set the start time and stop time (can be the same). Then in the dashboard, you have to create your widget and select in the last step "start time" (or "end time").
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/f6fa5449-79fa-4647-a06c-9dee5661f4f0)
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/b2e3e492-f95f-4148-ade0-2aea0e57c957)

Seems there is a bug if you try to filter your dashboard with start time and end time. I'll create an issue.
