### ISSUE TITLE
User with Knowledge capability can't do mass operations on notifications

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3331]
## Description

A user with default rights (no update/delete rights / only Knowledge capability) can't do mass operations on notifications (i.e. delete all notifications, mark notifications as read or not read).

## Reproducible Steps

Log in as a user with only the Access Knowledge capability.
Subscribe to a trigger with no filters. Do operations (creation /upate of entities) in an admin platform.
In the platform of the user with knowledge access, you should have several notifications.
You can delete them or mark them as read line by line.
If you select some notifications via the checkboxes, you have no 'delete' icon in the tool bar.
If you click on the 'mark as read' icon of the toolbar and launch the background task, a message said you can't do this operation.

## Expected Output

A user can manage his notifications via the toolbar and do mass operations on them.

## Actual Output

Admin (or users with edition/deletion rights) can do such operations, but not users with no update/delete rights.

## Additional information

Must be done after the merge of the issue 2418 (https://github.com/OpenCTI-Platform/opencti/pull/3122)
A user with knowledge rights can't do such mass operations because these operations are only available for users with edition/deletion rights (tool bar is generic). The solution is to enable all users to have admin rights for their notifications. For this, we can use 'authorized_members' and the way of bypassing some rights that have been implemented in issue 2418.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/a29e313b-681f-4241-930b-e30378c7faa3)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/2291b732-ddd6-45f6-bbdc-9afcc7d16122)

**Comment by Jipegien** [comment]
duplicate
