### ISSUE TITLE
"Plus" button in Analyst Workbenches doesn't work anymore for adding entities

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#3337]
## Description

In any Analyst workbench (new or already created), the "+" button doesn't work to add Entities, but works for Observables.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Create an Analyst Workbench, go to the "Entities" tab, try the "+" button.

## Expected Output

A panel with a selection list of entity types to add.

## Actual Output

Nothing

**Comment by SarahBocognano** [comment]
It's also doesn't work for Add Container
