### ISSUE TITLE
Allow creating a stream filter based on organization

### ISSUE THREAD

**Issue by ristowee** [LuatixHQ/opencti#3340]
## Use case

If we (say OrganizationA) provides data for OrganizationX & OrganizationY and we'd like to stream the data that's organization specific it would make process much simpler if we could create a separate stream for each organization and only allow output based on the organization.

If I have not misunderstood the internal data segregation is already possible:
https://blog.filigran.io/opencti-organizations-segregation-and-sharing-b7d4ba3f9398

However, the stream filters do not seem to have anything that'd support organization filtering (`granted_refs`).

## Current Workaround

It's not possible to create complex streaming filters at the moment to make a workaround (e.g. negative filters with OR combiner). There is an issue that would make it better https://github.com/OpenCTI-Platform/opencti/issues/2686 but the target is quite far off.

## Proposed Solution

Add a functionality that'd allow streaming data based on organization (`granted_refs`?).

## Additional Information

Current filter options (5.7.4):
![image](https://github.com/OpenCTI-Platform/opencti/assets/123449325/7b468a66-f5f2-4e57-937f-5c90915372ca)

## If the feature request is approved, would you be willing to submit a PR?

Most likely not

**Comment by richard-julien** [comment]
Today any users connected to a stream will have data according to their restrictions. So by default restricted to organization(s) of the connected user. Are you targeting public stream for that kind of filter or a user with multiple organizations you want to restrict to only one?

**Comment by ristowee** [comment]
OK. Good point. I may have understood the mechanism the wrong way around. So, if there are no `granted_refs` with OrgX present in the system, a user belonging to that organization can see "everything". However,  if something is "tagged" with `granted_refs` to OrgX the user can see only those items. Then the stream for that user should show only items that have OrgX in `granted_refs` list.
I should have asked this in the Slack first. Sorry for the noise. This ticket can be closed.

**Comment by ristowee** [comment]
Closing as the feature already exists in the system in different form.
