### ISSUE TITLE
Integrating with SIEM QRadar

### ISSUE THREAD

**Issue by wonhee0410** [LuatixHQ/opencti#3341]
I have a question about integration with SIEM QRadar.

Does OpenCTI has any connectors or solutions to connect to my QRadar ?

If not, could you guys please suggest me the way how OpenCTI helps SIEM QRadar ?

Thank you.

**Comment by Jipegien** [comment]
We are planning to add a connector to feed Qradar SIEM from OpenCTI.

It will be great if you participate to build this bye sharing with us example of how you imagine your usage of such a connector! So feel free to comment here or contact me on PM. 🙂

**Comment by ASQ505** [comment]
actually, my colleague @khanafeer made a script that acts as a connector between OpenCTI which uses TAXII2.1 and Qradar TAXII2.0 and other SIEMs, you can find it here https://github.com/khanafeer/Taxii_SQL
it is tested on Splunk, Qradar and Logrythm

**Comment by Jipegien** [comment]
PR of Khanafeer linked to the connector issue.
