### ISSUE TITLE
Force pattern to either have spaces or remove them

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#3351]
## Use case
Currently if you create an observable and then select "Create an indicator from this observable" it will have space around the = symbol. However some data sources I am ingesting, do not have a space, which means I end up doing two Graphql filter queries to cover both scenarios (I'm not doing a search). Can we force a standard within the platform and correct if necessary. I realize this could become complicated with an indicator that has multiple IOCs within it.

Pattern Example:
[domain-name:value = 'testdomain.com']
[domain-name:value='testdomain.com']

## Current Workaround

Edit the pattern.

## Proposed Solution

Possibly just do a replace, e,g, "e='" with "e = '" or vice versa.

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by richard-julien** [comment]
Hi @annoyingapt, starting version of february we implement a pattern cleaner based on ANTLR to format stix pattern.
Currently in the demo if you try to create an indicator with [domain-name:value='testdomain.com'] it will be converted to [domain-name:value = 'testdomain.com'].
Can you specify in your ticket the version of OpenCTI you use and can you test your case on the demo to see if you can reproduce?
In case of reproduction please document here a step by step repro case.

**Comment by annoyingapt** [comment]
Well this is awkward, we upgraded recently and I didn't test this on it. Give me a few days to double check, if its all good, I'll close this off.
