### ISSUE TITLE
TAXII v2.1 compatibility: sort order of result objects

### ISSUE THREAD

**Issue by basvs** [LuatixHQ/opencti#3376]
## Description

According to https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107516 objects MUST be sorted in ascending order by the date it was added.

I think this was always the case with OpenCTI 5.6.2, but changed somewhere in OpenCTI 5.7.x.

## Environment

1. OS (where OpenCTI server runs): Debian Bullseye
2. OpenCTI version: 5.7.6
3. OpenCTI client: manual GET requests
4. Other environment details: Kubernetes 1.24

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create OpenCTI environment with several objects
2. Create TAXII feed
3. Retrieve TAXII objects

Result with retrieving manifest: (results are in the correct order; added whitespace for readability)
```
GET /taxii2/root/collections/9ae2e9ae-8ffd-4ac6-a5fb-3844f304f569/manifest/?limit=10

HTTP/1.1 200 OK
X-TAXII-Date-Added-First: 2023-04-18T16:38:48.155Z
X-TAXII-Date-Added-Last: 2023-05-15T13:15:42.584Z
…

{"more":false, "next":"WzE2ODQxNTY1NDI1ODQsIjE2ZTQzNDZhLTg2MGItNGQxOS04YjY3LTQwZDg2NjAxNjc0OSIsImluZGljYXRvci0tMDBhMmZhOWQtN2ZjNS01NWYwLWEwNzUtMzc0MTY2N2I1MjNkIl0=",
"objects":[
{"id":"domain-name--5f56e25e-a309-5915-b0fa-bb76972f67a4", "date_added":"2023-04-18T14:21:42.313Z", "version":"2023-04-18T16:38:48.155Z", "media_type":"application/stix+json;version=2.1"},
{"id":"indicator--df5f2cb9-d41a-5e8d-b303-03e7a48fe9e1", "date_added":"2023-04-18T14:21:42.213Z", "version":"2023-04-18T22:04:02.209Z", "media_type":"application/stix+json;version=2.1"},
{"id":"hostname--2b737964-5e86-5b3a-a1be-6959d63bd0e7", "date_added":"2023-04-18T15:32:57.638Z", "version":"2023-05-10T08:42:41.717Z", "media_type":"application/stix+json;version=2.1"},
{"id":"indicator--00a2fa9d-7fc5-55f0-a075-3741667b523d", "date_added":"2023-04-18T15:32:57.602Z", "version":"2023-05-15T13:15:42.584Z", "media_type":"application/stix+json;version=2.1"}
]}
```

Result with retrieving objects: (results are in wrong order; added whitespace for readability)
```
GET /taxii2/root/collections/9ae2e9ae-8ffd-4ac6-a5fb-3844f304f569/objects/?limit=10

HTTP/1.1 200 OK
X-TAXII-Date-Added-First: 2023-04-18T22:04:02.209Z
X-TAXII-Date-Added-Last: 2023-05-10T08:42:41.717Z
…

{"more":false, "next":"WzE2ODQxNTY1NDI1ODQsIjE2ZTQzNDZhLTg2MGItNGQxOS04YjY3LTQwZDg2NjAxNjc0OSIsImluZGljYXRvci0tMDBhMmZhOWQtN2ZjNS01NWYwLWEwNzUtMzc0MTY2N2I1MjNkIl0=",
"objects":[
{"id":"indicator--df5f2cb9-d41a-5e8d-b303-03e7a48fe9e1", …},
{"id":"domain-name--5f56e25e-a309-5915-b0fa-bb76972f67a4", …},
{"id":"indicator--00a2fa9d-7fc5-55f0-a075-3741667b523d", …},
{"id":"hostname--2b737964-5e86-5b3a-a1be-6959d63bd0e7", …}
]}
```

**Comment by basvs** [comment]
In both results the next points to the indicator--00a2fa9d-7fc5-55f0-a075-3741667b523d object.

In the get-objects result, I would expect the same ordering, and would expect that the next token always points to the last object in 'objects'.

**Comment by basvs** [comment]
@richard-julien can this be a regression of #3214 ?

**Comment by richard-julien** [comment]
Hi @basvs , looks like its possible that the ordering is lost with the new batch loading yes :(

I will take a look quickly

**Comment by richard-julien** [comment]
After looking into it, its a design choice that we have from the beginning. 
**All information in taxii are ordered with the updated_at field instead the creation.**
We decide to use the updated_at to provide the capability to get update of elements in taxii.
Maybe im wrong but in my understing of taxii, each element should be "duplicated/recreated" and so rely on the creation date should be the way. In OpenCTI we dont duplicate the information, we query the current state of the database. Its a choice to prevent data duplication but force us to use the updated_at date to query/sort the information.

The headers also rely on the updated_at information.

```
      res.set('X-TAXII-Date-Added-First', getUpdatedAt(R.head(stix.objects)));
      res.set('X-TAXII-Date-Added-Last', getUpdatedAt(R.last(stix.objects)));
```

Maybe the confusing part we need to change is the manifest generation where we put the created_at for the date_added instead of the updated_at information.

```
const prepareManifestElement = async (data) => {
  return {
    id: data.standard_id,
    date_added: data.created_at,
    version: data.updated_at,
    media_type: STIX_MEDIA_TYPE,
  };
};
```

**Comment by basvs** [comment]
I already assumed that. I think that's ok. But if you look at the two requests in my reproducible steps, you'll see that the /manifest/ has a different ordering than the /objects/. (these are the same four objects, which haven't changed between my requests)

If I decode the 'next' token from the last example, I get '[1684156542584,"16e4346a-860b-4d19-8b67-40d866016749","indicator--00a2fa9d-7fc5-55f0-a075-3741667b523d"]', which is not the first or last element, but the third element.

**Comment by richard-julien** [comment]
Ok, i have a too small datasets in my dev env to reproduce, with a bigger one I can confirm than its due to the performance improvment in the loader that break the ordering. Fix in progress.
