### ISSUE TITLE
Filtering Observables by Sector

### ISSUE THREAD

**Issue by micaelalex** [LuatixHQ/opencti#3379]
## Prerequisites

- [X] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

I am trying to filter in GraphQL all IPV4 that have a relationship with the Sector Universities, I have made a filter but it doesn't seem to be doing what it should.

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 22.04
2. OpenCTI version: OpenCTI 5.7.6
3. OpenCTI client:GraphQL
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an IPV4 with a relation to the Sector Universities
2. Insert the following code snippet in the online GraphQL:
`query {
  stixCoreRelationships(
    fromTypes: "IPv4-Addr"
    toTypes: "Sector"
    filters: [
      {key: toName, values:"Universities"}
    ]
  ) {
    edges{
      node{
        fromType
        entity_type
        toType
        toStix
        created_at
        updated_at
        }
      }
    }
  }`

## Additional information

![image](https://github.com/OpenCTI-Platform/opencti/assets/8707982/d4898092-5591-432f-8200-0a021dc23f55)
![image](https://github.com/OpenCTI-Platform/opencti/assets/8707982/f4a683f9-5bdc-4a49-93e7-5497215a892b)

The objective is to create somehow a feed of observables that are related to specefic sectors.

**Comment by micaelalex** [comment]
I have tryed to use the CSV with the filters to create the filter witouth  any result, no IPV4 will happear there.

![image](https://github.com/OpenCTI-Platform/opencti/assets/8707982/7f51e751-4c3c-411c-bd36-6b780e6ec8f7)

The examples were made in the demo OpenCTI, so it can be checked easier.

**Comment by Kedae** [comment]
I think you are mixing concept (or I'm not getting your question right). If you want to get the Observables linked through a relation to a specific object you can do : 

`{
  stixCyberObservables(filters:[{key: relatedTo, values: ["ID_OF_YOUR_SECTOR"]}]) {
    edges {
      node {
        id
        ... on IPv4Addr { // For your example, can be change
          value
        }
      }
    }
  }
}
`

**Comment by micaelalex** [comment]
@Kedae For Sectors it seems to work, but let's say the relation is to a country for example: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/8707982/9ea4a880-5391-4aa3-b76d-1fc08e5b3c23)

The key only works for the specefic relations relatedTo in the case of a relation located-at or other types of relations it doesn't seem to work.

**Comment by nino-filigran** [comment]
Closing this issue since nothing happened on the ticket for 6months
