### ISSUE TITLE
Improve usage of Tasks

### ISSUE THREAD

**Issue by Kedae** [LuatixHQ/opencti#3382]
- [x] Add a simple page for Tasks (get the same template as Note page with simple information => without external references)
- [x] Add task list in Case menu
- [x] Overview of Incident Response & Request for Takedown: 
    - [x] Add the missing "Share to organization" button
    - [x] Replace the “Incidents & Alerts” list by “Origin of the case” list containing related `Incidents`, `Sightings`, `Report`.
    - [x] “+” button to quickly add a Report too
- [x] Overview of Request for Information: Replace the “Incidents & Alerts” list by “Origin of the case” list containing related `Report`.
    - [x] Add the missing "Share to organization" button
    - [x] +” button to quickly add a Report too
- [x] Overview: Modification of the Tasks’ list:
    - [x] Task list “expanded” on the full width (like Notes below)
    - [x] Be able to sort by “status” and “due date”
    - [x] Be able to click on a Task to view its details
    - [x] ~~Be able to filter or search a Task by “assignee”~~
    - [x] Display “due date” in red if overdue
- [x] Knowledge: set the Timeline view as the default view

--- 
Update of 09/06:
- [x] List when no item of task in case is broken
- [x] Update of task seems broken
- [x] Revoked to be removed from task
- [x] Sort by assignee should sort by name
- [x] Resolver.jsx needs to be removed ?
- [x] Update of Localization
- [x] Align date chip with indicator, see with Samuel
- [x] List CSS to check with Adrien

**Comment by Jipegien** [comment]
Description updated as discussed @SarahBocognano :)
