### ISSUE TITLE
Error when trying to add an external references with same source_name or url AND a file

### ISSUE THREAD

**Issue by SarahBocognano** [LuatixHQ/opencti#3386]
## Description

When trying to add an External References, if we give the same source_name or the same url as one already in the platform. and add a File in creation. It returns an error : 

```
{"category":"APP","error":{"stacktrace":["TypeError: Cannot read properties of null (reading 'label')","at C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\utils.js:339:44","at Array.map (<anonymous>)","at C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\utils.js:331:47","at Array.map (<anonymous>)","at generateUpdateMessage (C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\utils.js:330:54)","at upsertElementRaw (C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:2546:16)","at createEntityRaw (C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:3090:22)","at createEntity (C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-graphql\\src\\database\\middleware.js:3182:16)","at addExternalReference (C:\\Users\\SarahBocognano\\IdeaProjects\\opencti\\opencti-platform\\opencti-gra
phql\\src\\domain\\externalReference.js:55:19)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ExternalReferenceCreationMutation","operation_query":
"mutation ExternalReferenceCreationMutation($input:ExternalReferenceAddInput!){externalReferenceAdd(input:$input){id source_name description url external_id created fileId}}","size"
:274,"time":147,"timestamp":"2023-05-25T07:34:20.461Z","type":"WRITE_ERROR","user":{"ip":"::1","referer":"http://localhost:3000/dashboard/analysis/external_references","user_id":"88
ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{"input":{"description":"","external_id":"","file":{"file":{"encoding":"7bit","filename":"2023-05-22T12_54_08.565Z_TLP_ALL_(ExportFileStix)_Report_full.json","mimetype":"application/json"},"promise":{}},"source_name":"FireEye APT41 Aug 2019fefe","url":"https://google.com"}},"version":"5.7.6"}
```

![Capture d’écran (42)](https://github.com/OpenCTI-Platform/opencti/assets/98532359/bb4e4eb8-03b5-42c4-9c93-ab19e6964c92)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an external reference
2. Create a new external reference with the same source_name or url that the one created before
3. The bug will display when clicking create

## Expected Output

Be able to have a message informing that the source_name or url is already taken and/or reparing the bug

**Comment by richard-julien** [comment]
Looks like schema definition for external reference is not consistent.
The attribute definition getter return null.

`const attributeDefinition = schemaAttributesDefinition.getAttribute(entityType, key);`

**Comment by Kedae** [comment]
This issue is replicable on almost every entity that uses files at creation :(

**Comment by SarahBocognano** [comment]
It looks like at the upsert of entities, if we upload a file, the attribute modified is "x_opencti_files" , but that attribute is not define is the schema definition (on any entities) so, maybe we need to declare that attribute at a high level so that all entities can heritate of it.

**Comment by richard-julien** [comment]
Thats a good idea to investigate
