### ISSUE TITLE
Be able to customize the time range of relationship de-deduplication mechanism

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3387]
## Use case

Be able to customize the time range of relationship de-deduplication mechanism.
Be able to add (as an option) the author as a deduplication key.

Currently, we deduplicate relationships on:

- source ID
- target ID
-  -1 month < start_time  < +1 month
- -1 month < stop_time  < +1 month

We need to propose the ability to change the resolved range for de-deplucation.

- [ ] Add static configuration in platform config
- [ ] Adapt engine algorithm to take into account the configuration

This will enable a powerful capability for the platform to be more "precise" as a threat intelligence team but also to de-duplicate everything based on 12 months range for instance for less mature / less resourced team that just need the "higher level" insights.

**Comment by Jipegien** [comment]
adding the option to take "author" as a deduplication key

**Comment by richard-julien** [comment]
Sample config:

```
  "relations_deduplication": {
    "past_days": 30,
    "next_days": 30,
    "created_by_based": false,
    "types_overrides": {
      "targets": {
        "past_days": 2,
        "next_days": 2,
        "created_by_based": true
      }
    }
  },
```

**Comment by SamuelHassine** [comment]
Doc: https://docs.opencti.io/latest/deployment/configuration/#functional-customization.
