### ISSUE TITLE
Import problem: MITRE CAPEC source

### ISSUE THREAD

**Issue by f-castano** [LuatixHQ/opencti#3388]
## Description
I am trying to export the Common Attack Pattern Enumerations and Classifications from MITRE (https://github.com/mitre/cti/raw/master/capec/2.1/stix-capec.json) using the ImportFileStix connector. Although the process is completed successfully, the data is not displayed.

## Environment
OPENCTI 5.7.6

## Reproducible Steps
1. Load the CAPEC data in the data import and analyst workbenches section

![import1](https://github.com/OpenCTI-Platform/opencti/assets/134516815/999d79c9-853c-4f7d-bdbc-d2166904be7d)

2. The data is loaded in the analyst workspaces section, and it seems correctly parsed

![import2](https://github.com/OpenCTI-Platform/opencti/assets/134516815/c3bc8122-9a1f-4ef8-b4f5-8bb5e1600fed)

3. Launch the importation task

![import3](https://github.com/OpenCTI-Platform/opencti/assets/134516815/10d71e55-ec12-475c-a3d5-eb81a79b70c1)

4.  The task appears as completed in the ImportFileStix connector details

![import5](https://github.com/OpenCTI-Platform/opencti/assets/134516815/da2ce5c3-726c-4f07-96ba-9c0f33c4b58c)

## Actual Output
No data is displayed at the end of the process.

![import4](https://github.com/OpenCTI-Platform/opencti/assets/134516815/0f97b7eb-01b3-4ac3-92f2-69f8418351e0)

**Comment by richard-julien** [comment]
Did you click on the workspace validation button to start the import?

**Comment by f-castano** [comment]
Youre right, Im sorry! I clicked in the validation button and the import process was successful. 

Thank you.
