### ISSUE TITLE
Global problem about displayed nested / refs relationships everywhere

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3389]
## Use case

Right now, only a few types of entities have a display widget to display nested entities:

* Observables

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/2206a38c-3a5e-401a-bda2-5e54adfc938d)

* Malware

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/e4464ef9-0e6d-4af5-9610-34ef2fe7c8ed)

This is because, in most cases, having nested ref objects is not supported by the type of entity.

However, in OpenCTI, there is a `linked-to_ref` attribute available for all entity types. Therefore, it is possible to create this in report, here an example for a relationship:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/71b532ea-929b-4299-baaf-8eabc0327217)

But this is possible basically on everything in the graph. Taking the example of this previous relationship, the "linked-to_ref" is not displayed anywhere in the relationship overview:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/1feb0b10-a8ed-4760-a6ba-c470b1976541)

This leads to an inconsistent behavior between the graph where it is possible to create at least a linked-to_ref attribute on anything, including relationships, but then the platform is not displaying them in overviews.

We need to think about displaying nested / ref attributes everywhere in the platform, as we are supporting this since v1.

**Comment by SamuelHassine** [comment]
Nested relationships display in relationships.

**Comment by SamuelHassine** [comment]
To be discussed.

**Comment by nino-filigran** [comment]
After a discussion, decision to remove the capbility to created nested relationships "link to (ref)" (cc @Jipegien and @SamuelHassine ). This is what will be implemented.
