### ISSUE TITLE
Unable to use AND operator when searching on observables with the same filter key

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#3390]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

When filtering for observables, it is not possible to use the AND operator for two labels or two filters of the same type. Only the OR operator can be used or AND NOT if alt+click is used on the filter key.

This brings up a larger discussion regarding an issue I submitted in the past that was closed - https://github.com/OpenCTI-Platform/opencti/issues/1635. It would benefit users to search via a Query Builder UI that builds the GraphQL query. This seems like a good option based on other tools I have used like Kibana.

**Comment by Jipegien** [comment]
Covered by #2686
