### ISSUE TITLE
User is redirected to the URL in the description when adding organization to a report

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3403]
## Description

When attempting to add an organization that has a url in the description to a knowledge graph, it instead redirected me to the url listed.

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/6d9ff28e-4916-40ff-927e-52f7fa43ed5c)

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/4ad18383-b12e-492f-8927-e244a33b7b23)

**Comment by Archidoit** [comment]
The entity is added to the knowledge graph if you click anywhere in the organization line, except if you click on the url.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/64a1943e-6929-4b35-9cf2-53fae5351ef9)

**Comment by SamuelHassine** [comment]
@Archidoit please reach me tomorrow about this issue.
