### ISSUE TITLE
Add a new version of platform / workers images OpenSSL FIPS 140

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3406]
## Use case

In addition to current images, we need to build images using https://github.com/NineFX/alpine-fips.

**Comment by SamuelHassine** [comment]
Can be more tricky than expected. Huge brainstorm to have with Julien and Adrien.

**Comment by richard-julien** [comment]
Some interesting links.

**NodeJS**
https://github.com/nodejs/node/blob/main/BUILDING.md#enabling-fips-using-openssl-config
https://github.com/nodejs/help/issues/4085

**Python**
https://discuss.python.org/t/python-3-with-openssl-3-fips-enabled/20287/3
