### ISSUE TITLE
Disabling Two Factor Authentication From Server CLI

### ISSUE THREAD

**Issue by iman006** [LuatixHQ/opencti#3418]
## Description

I have enabled the two-factor authentication feature in the user settings of the opencti platform, but after that, when I try to log in, it does not accept the code that I receive from the Google Authenticator app, and I can no longer log in to the system. Is there a way to disable the two-factor authentication security feature via CLI? Unfortunately, I don't have any backups of the information. Please let me know if you have a solution. This system is installed on an Ubuntu server via Docker.
@richard-julien 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04, etc. 
2. OpenCTI version: OpenCTI 5.7.4 
3. OpenCTI client: python

## Additional information

  opencti:
    image: opencti/platform:5.7.4
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
      
![Capture](https://github.com/OpenCTI-Platform/opencti/assets/79222802/0937957e-70e3-4850-814e-70c642ae1a2a)

**Comment by richard-julien** [comment]
For now there is no specific way to disable the activation. You need to patch directly the data in elasticsearch to do that.
But this feature works well for a a lot users so i dont understand what kind of problem you can have.
Looks like you are at the activation phase where you need to scan the bar code to validate that the code is good, are you sure that the code you enter is directly generated by the bar code you see on the screen?

**Comment by iman006** [comment]
> For now there is no specific way to disable the activation. You need to patch directly the data in elasticsearch to do that. But this feature works well for a a lot users so i dont understand what kind of problem you can have. Looks like you are at the activation phase where you need to scan the bar code to validate that the code is good, are you sure that the code you enter is directly generated by the bar code you see on the screen?

Thanks for you answer.
Yes, I am in the activation phase. Here, I scan the barcode and then enter the code received in Google Authenticator into the platform, but the platform does not accept the entered code and does not allow access.
Is there anything else I need to do for full activation? I only enabled the activation checkbox for this feature in the user settings, and now I have this problem. @richard-julien

**Comment by richard-julien** [comment]
Just retested without problem right now. My workflow.
1. With Admin => Settings > Access > Enforce two-factor authentication
2. With User => Login > scan the QR Code generated specically for this user, activation by typing the code.

For now there is no way to simply disable that. We need to directly patch the instance of settings in elasticsearch to move " "otp_mandatory": true"  to false. Do you have a Kibana deployed where you can do queries?

**Comment by iman006** [comment]
I appreciate your response. I tested the same process with 3 different users and while I received errors with 2 users, I was able to log in with the third user using the Firefox browser (not Chrome) and eventually problem is solved. 👍

**Comment by dominictory** [comment]
> Just retested without problem right now. My workflow.
> 
>     1. With Admin => Settings > Access > Enforce two-factor authentication
> 
>     2. With User => Login > scan the QR Code generated specically for this user, activation by typing the code.
> 
> 
> For now there is no way to simply disable that. We need to directly patch the instance of settings in elasticsearch to move " "otp_mandatory": true" to false. Do you have a Kibana deployed where you can do queries?

I am having the same issue albeit in multiple browsers (Firefox, Chrome). I cannot get past the activation stage as it tells me the code is not correct.

Can you please guide me on how would I patch the ""otp_mandatory":true" field in ES?
