### ISSUE TITLE
NOT operator in filter of Incident Response/Knowledge/Timeline View doesn't work

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#3422]
## Description

By "alt-clicking" an Entity Type in the filter of the Timeline View of an Incident Response Case, for example "Task", the ENtity type is not excluded and the view is limited to this Entity.

![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/e5faaf51-bc36-40a1-9d44-c0decc013652)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: filigran instance

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an INcident Response case with different entities related to it
2. Go to Knowledge/TImeline View
3. Click on filter, select an Entity type to filter with but use Alt-Click to select it.

## Expected Output

The timeline with the specified entity type excluded

## Actual Output

The timeline with only the specified Entity type

**Comment by SarahBocognano** [comment]
Apparently, the filter 'not'  is not working for any entity type, not only Task
