### ISSUE TITLE
Connectors with work in progress do not complete the work job if platform is upgraded during the job

### ISSUE THREAD

**Issue by GraemeMeyerGT** [LuatixHQ/opencti#3424]
## Description

We just upgraded one of our instances from 5.6.2 --> 5.7.6 - it looks like the AlienVault connector had a "job" in progress when the platform was shutdown, and the job has not resumed or completed now that the upgrade is complete. Subsequently scheduled jobs by that same connector seem to work okay. It's not clear if any data/work was lost - whether the job actually completed and just wasn't marked as complete, or whether the job actually was lost.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } Docker 24.0.1 and Docker Compose version v2.18.1 on Ubuntu 22 (we use the provided Docker Compose configuration)
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 5.7.6
3. OpenCTI client: { e.g. frontend or python } N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.Have a Docker Compose version of the platform on version 5.6.2
2. Wait until an AlienVault job is in progress (I think the logs will say something like ["Pulse importer completed (imported: {0}"](https://github.com/OpenCTI-Platform/connectors/blob/ad8d5edcee266765e7747fc5e7d5e6da0d409c1e/external-import/alienvault/src/alienvault/importer.py#LL161C14-L161C53))
3. Check that the workers are processing the new work - they will show events in the Docker logs, or presumably in your Elastic logs
4. Stop OpenCTI gracefully (in my case, `docker compose down`)
5. Upgrade the docker compose configuration to 5.7.6
6. Start the system up again (`docker compose up -d`)
7. Observe that the page for the connector (e.g. AlienVault) will show a job in progress, with a start time before the upgrade, which will not finish/complete

## Expected Output

I would expect the work in progress to be paused or cached somewhere when the system is shutdown, and that it should be resumed when the system comes back up. 

## Actual Output

A connector job is created "in progress", but not finished. See the following screenshot, which shows the stuck 10:35 job, and a subsequent 11:52 job which completed without issue: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/107847353/85cf17b2-2f73-4c55-b2cb-6a445d575014)

## Additional information

Note: our system is in UK TZ, which I believe explains why some timestamps show up an hour ahead of some others.

Unfortunately, the Docker log seems to have been wiped after the upgrade, so I do not think it covers the events in question. This could be how docker compose works, or could be a side-effect of how we use it.

**Comment by GraemeMeyerGT** [comment]
This was most likely caused solely by RabbitMQ hostname changing during Docker deployments, as decribed in the PR I just raised: https://github.com/OpenCTI-Platform/docker/pull/90

Unless the devs are already aware of another possible cause of this, I'd suggest closing this issue once the PR is merged. (Unless you want to add in any other protective/preventative logic to the application - a detection/warning for similar issues could be useful).

**Comment by tomibennett** [comment]
Hello, 

Thank you for your report and your help.

As you already know, a [fix](https://github.com/OpenCTI-Platform/docker/commit/af352b5049227ec4e447f275e32c7701c6f0a8be) that sets statically the RabbitMQ's `nodename` has been pushed. This solves the error mentioned in this issue and it can be closed.
