### ISSUE TITLE
Uploading images & screenshots to the content tab for all objects.

### ISSUE THREAD

**Issue by adreasy** [LuatixHQ/opencti#3427]
## Use case
The ability to upload images and screenshots to the content tab across the application. specifically useful for incident response cases where images related to phishing, brand abuse, or internal cases could be used to identify and collect additional threat information.

## If the feature request is approved, would you be willing to submit a PR?
yes

**Comment by Jipegien** [comment]
It is not easy as just add an image file, but you can already do this through the upload of an HTML file. 
1. Create an HTML file
2. Edit it within the enrich editor
3. copy paste your image or use the image button of the editor
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/d598a3e2-8181-4ede-90e4-869c127bb5d1)

Did you know that and do you think it solve your issue?

**Comment by adreasy** [comment]
thank you. i did not know that but will give that a try with our current integration.
