### ISSUE TITLE
my stream is not sending the updates

### ISSUE THREAD

**Issue by ASQ505** [LuatixHQ/opencti#3435]
## Prerequisites

- [*] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [*] I went through old GitHub issues and couldn't find anything relevant
- [*] I googled the issue and didn't find anything relevant

## Description

Hello, the problem is when I visit "https://myOpenCTIserver/stream/live" my stream isn't sending the new updates on the indicators, it just sending heartbeats as follows. (there are no filters) 

event: connected
data: {"lastEventId":"1683802765699-0","firstEventId":"1673866826972-0","firstEventDate":"2023-01-16T11:00:26.972Z","lastEventDate":"2023-05-11T10:59:25.699Z","streamSize":2000000,"connectionId":"d7d7d7d7-d7d7-d7d7-d7d7-67e3191dd7d7"}

id: 1685523857951-0
event: heartbeat
data: "2023-05-31T09:04:17.951Z"

id: 1685523863171-0
event: heartbeat
data: "2023-05-31T09:04:23.171Z"

id: 1685523868288-0
event: heartbeat
data: "2023-05-31T09:04:28.288Z"

id: 1685523873383-0
event: heartbeat
data: "2023-05-31T09:04:33.383Z"

id: 1685523878491-0
event: heartbeat
data: "2023-05-31T09:04:38.491Z"

id: 1685523883652-0
event: heartbeat
data: "2023-05-31T09:04:43.652Z"

**Comment by khanafeer** [comment]
I have the same issue.

**Comment by khanafeer** [comment]
After reading the documentation and some open issues, the solution for me was the Redis trimming I set the value to be 2 million 
REDIS__TRIMMING=2000000
