### ISSUE TITLE
Organizations types to be in the vocabularies

### ISSUE THREAD

**Issue by RaulSokolova** [LuatixHQ/opencti#3470]
## Use case

We might need to add different types of organizations to identify them.

## Current Workaround

None

## Proposed Solution

Add a organization_type_ov for users to customize it

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
Can you specified your need plz? To what end do you want to add "types" to Organization and how the labels and "part of" relations do not cover it?

**Comment by RaulSokolova** [comment]
We need to be able to add more. In the vocabularies is where we can add different types for each entity. 

![image](https://github.com/OpenCTI-Platform/opencti/assets/30608998/221db6c5-67ab-4b12-b4e5-36d9e9734886)

**Comment by Jipegien** [comment]
Ok I was thinking about something else, my bad. We will add a organization_type_ov.

**Comment by RaulSokolova** [comment]
Thank you for working on adding it, sorry for coming short explaining the feature request.
