### ISSUE TITLE
Cannot return null for non-nullable field System.name 

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#3480]
## Description
When  I create a System via API, I get a response like this indicating there is NO error:
{"systemAdd":{"standard_id":"identity--aafc9ecc-35df-5bce-b3fd-01717751cf55"}}

When we search for that entity in the front-end we receive a generic error:

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/1d860104-0a91-49b7-bf80-f5ed41c369c3)

When we search via graphql we receive the following:

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/06fa413d-ee3e-4dd6-a286-d6891ea4cf7d)

In the logs we see the following message:

{"category":"APP","error":{"stacktrace":["Error: Cannot return null for non-nullable field System.name.","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:594:13)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeAbstractValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:795:10)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:624:12)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:584:23)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:489:19)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:413:20)","at completeObjectValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:914:10)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:635:12)","at /opt/opencti/build/node_modules/graphql/execution/execute.js:696:25","at Function.from (<anonymous>)","at completeListValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:676:34)","at completeValue (/opt/opencti/build/node_modules/graphql/execution/execute.js:607:12)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:489:19)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"SearchStixCoreObjectsLinesPaginationQuery","operation_query":"query SearchStixCoreObjectsLinesPaginationQuery($types:[String]$search:String$count:Int!$cursor:ID$orderBy:StixCoreObjectsOrdering$orderMode:OrderingMode$filters:[StixCoreObjectsFiltering]){...SearchStixCoreObjectsLines_data_4GmerJ}fragment SearchStixCoreObjectLine_node on StixCoreObject{__isStixCoreObject:__typename id parent_types entity_type created_at ...on AttackPattern{name description aliases}...on Campaign{name description aliases}...on Note{attribute_abstract content}...on ObservedData{name first_observed last_observed}...on Opinion{opinion explanation}...on Report{name description}...on Grouping{name description}...on CourseOfAction{name description x_opencti_aliases}...on Individual{name description x_opencti_aliases}...on Organization{name description x_opencti_aliases}...on Sector{name description x_opencti_aliases}...on System{name description x_opencti_aliases}...on Indicator{name description}...on Infrastructure{name description}...on IntrusionSet{name aliases description}...on Position{name description x_opencti_aliases}...on City{name description x_opencti_aliases}...on AdministrativeArea{name description x_opencti_aliases}...on Country{name description x_opencti_aliases}...on Region{name description x_opencti_aliases}...on Malware{name aliases description}...on ThreatActor{name aliases description}...on Tool{name aliases description}...on Vulnerability{name description}...on Incident{name aliases description}...on Event{name description aliases}...on Channel{name description aliases}...on Narrative{name description aliases}...on Language{name aliases}...on DataComponent{name}...on DataSource{name}...on Case{__isCase:__typename name}...on StixCyberObservable{__isStixCyberObservable:__typename observable_value}...on IPv4Addr{countries{edges{node{name x_opencti_aliases id}}}}...on IPv6Addr{countries{edges{node{name x_opencti_aliases id}}}}createdBy{__typename __isIdentity:__typename name id}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}creators{id name}reports{pageInfo{globalCount}}}fragment SearchStixCoreObjectsLines_data_4GmerJ on Query{stixCoreObjects(types:$types search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{__typename id entity_type created_at createdBy{__typename __isIdentity:__typename name id}creators{id name}objectMarking{edges{node{id definition_type definition x_opencti_order x_opencti_color}}}...SearchStixCoreObjectLine_node}cursor}pageInfo{endCursor hasNextPage globalCount}}}","size":148,"time":199,"timestamp":"2023-06-07T11:42:33.345Z","type":"READ_ERROR","user":{"ip":"::ffff:10.xxx.xxx.30","referer":"https://cti.etic.security/dashboard/search/identity--aafc9ecc-35df-5bce-b3fd-01717751cf55?sortBy=_score&orderAsc=false&filters=%7B%7D&deSelectedElements=null","user_id":"xxxxx-e7d9-4xx9-802f-4fc8xxxxxxb7"},"variables":{"count":25,"cursor":null,"filters":[],"orderBy":"_score","orderMode":"desc","search":"identity--aafc9ecc-35df-5bce-b3fd-01717751cf55","types":null},"version":"5.7.6"}

We think there is some problem when creating Systems via API.

## Environment

Bare metal installation on Ubuntu 22

**Comment by richard-julien** [comment]
Looks like if no input is specified, the API still create an element, that is of course invalid.
We need to fix this.
Waiting for the fix you can bring back the UI to life using an upsert api query.

```
mutation addSystem {
  systemAdd(input: {
    stix_id: "identity--aafc9ecc-35df-5bce-b3fd-01717751cf55"
    name: "The mandatory name"
    update: true
  }) {
    standard_id
    name
  }
}
```

**Comment by AlexSanchezN** [comment]
The interesting thing, is that we send a name in the query... I'll check we are not doing something wrong.
Incredible fast reply! 
Thanks

**Comment by AlexSanchezN** [comment]
As usual, you were correct. Our mutation had some errors.
Thanks again!
