### ISSUE TITLE
Make the based-on Pane Collapsible in the SCO view

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#3494]
## Use case

When an Indicator gets a lot of  `based-on` relations it makes the UI wonky

Thus make the indicator `based-on` pane collapsible (IMO default to collapsed w/ a 5-10 limit is probably the sweat spot)

## Current Workaround

None :(

## Proposed Solution

Thus make the indicator `based-on` pane collapsible (IMO default to collapsed w/ a 5-10 limit is probably the sweat spot)

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by Jipegien** [comment]
Hello @MaxwellDPS! Could you provide a screenshot of the wonky UI?

**Comment by MaxwellDPS** [comment]
Hey @Jipegien, I cant in this context, but TLDR The page scroll is so long it makes getting to the notes a hastle
