### ISSUE TITLE
[Dashboards] Dynamic Filters on SRO Graph Queries Seem to Have No Effect

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#3495]
## Description

The dynamic filters on SRO graph queries seem to have no effect

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.7.6 - Clustered Deployment
3. OpenCTI client: Frontend
4. Other environment details: Kubernetes - Large scale clustered deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an identity (Ref as `ORG-Z`)
2. Create 2 Indicators one labeled with `example--pain` (Ref as `IN-1` & `IN-2L` with the ladder having the label)
3. Create sighting SRO's for `IN-1 -> ORG-Z` & `IN-2L -> ORG-Z`
4. Create a dashboard graph with the axis
         - Relationship: `Sighing SROs -> ORG-Z `
         - Relationship: `Sighing SROs -> ORG-Z ` (Dynamic Source filter on label:`example--pain`)
5. The graphs are the same 🥲

## Expected Output

Proper filtering of the returned data

## Actual Output

Identical graphs with unfiltered data

**Comment by Kedae** [comment]
Could you provide more info about that ? I maybe have missed a thing but here is what I tested:
<img width="1025" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/50013774/a9c31fa6-511a-4d90-a09f-2650e4d7672a">
<img width="1003" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/50013774/f7e364e5-f9fb-49d6-9ed2-e5f9c58548f9">

As you can see the graphs **are** different
