### ISSUE TITLE
Unavailable documentation

### ISSUE THREAD

**Issue by ThijsAkkerman** [LuatixHQ/opencti#3498]
Can the documentation be made available? I'm trying to research all features but about 75% of the pages dont work.
They are all error 404 pages, for example the link about setting up RBAC: https://docs.opencti.io/5.7.X/administration/users.md

Is the documentation available elsewhere or can it be updated?

Kind regards,

**Comment by Jipegien** [comment]
Hello, the documentation is in refactoring. Previous one is accessible here : https://filigran.notion.site/Version-5-7-X-current-04fd9fb36dab483b819934acdcc1345e
