### ISSUE TITLE
Enable notifications mass deletion for all roles

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3506]
## Use case

A user with only the Knowledge role can't mass delete his notifications. He should delete them one by one.

## Current Workaround

Log as a user that has not the capability to delete entities. Go to the notifications tab. There are a 'delete' icon at the right of each row: the user can delete a notification. But there are no delete button in the tool bar: the user can't delete all the notifications or a selection of notifications.

## Proposed Solution

Add the delete button in the toolbar for all users for the notifications rows.

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/39e46140-66ef-4a55-834a-b189aeee618a)

**Comment by richard-julien** [comment]
Be careful also about notification access and background task rights to prevent a user to delete notification from another user
