### ISSUE TITLE
User with only the 'Access knowledge' capability can't log in

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3507]
## Description

A user with only the knowledge capability can't login.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Create a user with the Default group: he only has the 'Access knowledge' capability.
Open a window in private.
Try to login.
Nothing happens.
Put the user in an admin group: he has 'bypass all capabilities'.
You can now login.

**Comment by richard-julien** [comment]
Due to reworking of policies in screen. Working on it
