### ISSUE TITLE
Failed yarn insert-dev

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3509]
## Description

'yarn insert-dev' is not working anymore because of a type issue.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Run  'yarn insert-dev' in the terminal to insert data in the platform.
An error is raised (see the screenshot)

## Error in back

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/415d8a90-c1b4-4b65-b8ab-2899b699f3aa)

## Solution
Update the types in script-insert-dev.js (AddInputs are now mandatory)

**Comment by marieflorescontact** [comment]
Closing as wont fix because it is a local issue: `client python` was not updated
