### ISSUE TITLE
Subscriptions Manager will rapid fire Digest Email

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#3512]
## Description

If a trigger is setup, then an hourly digest is setup. The trigger will cause the digest to fire in ~60-120 window if the trigger is matched. So instead of one digest email it can be a bunch over a 60-120 sec windows

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.7.6 - Clustered Deployment
3. OpenCTI client: Frontend
4. Other environment details: Kubernetes - Large scale clustered deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create trigger
2. Create hourly digest
3. Match trigger multiple times at the top of the hour
4. Get multiple digest emails

## Expected Output

A single email

## Actual Output

Ya know the scene from harry potter with the letters 😅

**Comment by richard-julien** [comment]
Can you add some screenshot of :
- your trigger digest configuration
- your triggers live configuration you select in the digest.
Thanks
