### ISSUE TITLE
5.7.6 Upgrade Seems to have Majorly Impacted Read Speed

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#3513]
## Description

Following upgrading to 5.7.6, there was a noticeable drop in CPU usage from the platform like from ~20c sustained to 2c.

Read Ops on TAXII and WebUI are slow to the point of constant errors and timeouts, majorly affecting the platforms usability 

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.7.6 **(LATEST 6/12/23)**
3. OpenCTI client: All of the above
4. Other environment details: K8s Clustered deployment w/ LOTS of HP

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Errm 

## Expected Output

A load time that is operable by users and by the python client and the taxii client

## Actual Output

- Crazy slow load time
- Timeouts on TAXII w/ a page > 10 items
- non-stop webui issues. 
- Pain... Seems reminiscent of the previous performance issues from 2021

## Additional information
**THIS IS NOT A RESOURCING ISSUE** and was beyond a shadow of a doubt introduced by 5.7.6

This is the current scaling (although since compute usage is low things are scaled to the lower end)
- API (Connector-only) 5-10x replicas
     - 150m / 500Mi (reserved/pod) 
     -  No Limit / 4Gi (Limit/pod) 
- WEB (Users/TAXII) 5-10x replicas
     - 500m / 1Gi (reserved/pod) 
     -  No Limit / 4Gi (Limit/pod) 
- Workers 15-50x replicas
     - 50m / 100Mi (reserved/pod) 
     -  No Limit / 4Gi (Limit/pod) 

Redis is a Cluster of 3x Pods 
Elastic is a cluster of 6 Node with no resource limits
RabbitMQ is a 3 node cluster

**Nodes are not IO bound**

DM me for further diagnostic data please

## Other
@richard-julien is there any known-safe roll-back procedure?

**Comment by richard-julien** [comment]
In the latest version we introduce batching resolution to improve speed of taxii feed and streaming dependency fetching. For now successfully tested with some users with very large usage of taxii feeds.

There is no safe roll-back procedure.

Require investigation to see what can happen ou your infra.

**Comment by SamuelHassine** [comment]
Closing this for the moment, let's follow up progress after 5.8.0 release directly between Filigran and your organization.

**Comment by MaxwellDPS** [comment]
If anyone stumbles upon this one day, this issue was fixed by #7436
