### ISSUE TITLE
False duplicates found for cases + some design for cases

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#3515]
## Description

False duplicates found at cases creation

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Create a new case incident.
Write a name : duplicates are found, whatever the name is.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/81b8154d-71ca-4574-a1ca-80eea45c88f9)

Clic on 'duplicated entities', the list shows lines and the entities of type Case have no name displayed:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/184ca506-3e1c-4764-ba78-8b66bf8426fc)

## Other bugs on cases
- case incident update form > bad space between 'name' and 'incident date'
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/8ac8f3a9-b80b-4fc0-bb54-3bbf4625dc28)

- case incident overview, RFTs overview, RFIs overview: bad space between 'related case' and '-' (should be the same space as for 'description')
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/c8dbcec9-aacd-4b7c-9487-4b13ae8b3413)

**Comment by SarahBocognano** [comment]
Linking this issue to : https://github.com/OpenCTI-Platform/opencti/pull/3508

**Comment by SarahBocognano** [comment]
Update: Bug fixed in pull request: #3508
