### ISSUE TITLE
Multiple Notifications for a single triggered event

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#3518]
## Description

After setting a trigger and create an SDO, there is multiple notifications for this creation (all notification are the same).

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: demo

## Reproducible Steps

- Create a trigger on malware creation, to be displayed in user interface.
- Create a new malware
- Go to the notification panel

## Expected Output

One notification for the malware creation

## Actual Output

Multiple notifications for the same malware creation.

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/316e7386-cfd7-4e7d-a6b0-152afc97b7ba)

**Comment by RomuDeuxfois** [comment]
I can't reproduce locally, I continue to investigate

**Comment by RomuDeuxfois** [comment]
I can't reproduce in demo instance either
