### ISSUE TITLE
Error occured when click on correlation view for all entities

### ISSUE THREAD

**Issue by helene-nguyen** [LuatixHQ/opencti#3519]
## Description

An error occured when going into knowledge tab and click on correlation view for all entities.

## Environment

1. OS Windows 11
2. OpenCTI version: 5.8.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create new entity
2. Click on knowledge tab
3. Click on correlation view icon
4. Error appears

## Expected Output

Correlation view must appear

## Actual Output

```sh
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.
```

## Screenshots (optional)

![incident_bug](https://github.com/OpenCTI-Platform/opencti/assets/75518128/6468dda6-4fe2-4290-8c84-ea2ca117272a)

![analysis_bug](https://github.com/OpenCTI-Platform/opencti/assets/75518128/74dcb53b-22c0-407b-b6f2-cb96d8f87837)

**Comment by Kedae** [comment]
We have been missing resetAllFilters in graphCorrelation since 6daf9f857e9b300fa010db1c367c49aa21ab3173. @SamuelHassine  can you check ?
