### ISSUE TITLE
Incident Response workbench fails to build relationship.

### ISSUE THREAD

**Issue by RaulSokolova** [LuatixHQ/opencti#3521]
## Description

When using the import, in this case, the text import, the workbench doesn't build the relationship, only shows unknown. 

## Environment

1. Demo environment.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an incident response case.
2. Text import and validate the workbench
3. Relationship view in the workbench shoes as unknown. 

## Expected Output

To have a relationship with the Incident response case , and show there.

## Actual Output

It doesnt show in the case.

## Additional information

Link to the demo instance case: https://demo.opencti.io/dashboard/cases/incidents/30a0ae07-85cf-4e9b-8073-3652a95da23f

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/30608998/20cdf847-c19b-414b-88d3-776105a0196b)

**Comment by SamuelHassine** [comment]
Fixed  by https://github.com/OpenCTI-Platform/connectors/issues/1207. Should not happen: text import on containers attach the knowledge to the container and does not created related-to relationships (fix tested already in master branch).
