### ISSUE TITLE
Split capability "Manage labels & Attributes" into 2 capabilities

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3527]
## Use case

Split the capability "Manage labels & Attributes" into:

* Manage labels
* Manage attributes

Indeed, to cover this use case: 

> I have a connector account with connector role that has the default permissions, except the `Manage labels & Attributes`.
> I would like to be able to enable connectors and have them create automatically the report types OV but not labels.

**Comment by Jipegien** [comment]
linked to #3757

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5550
