### ISSUE TITLE
OpenCTI 5.8.0 crash when adding entity to container

### ISSUE THREAD

**Issue by b1nbash** [LuatixHQ/opencti#3542]
## Description

Failing to add entity to container

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
- Ubuntu 22.04
3. OpenCTI version: { e.g. OpenCTI 1.0.2 }
- OpenCTI 5.8.0
5. OpenCTI client: { e.g. frontend or python }
- frontend
7. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create report
2. Click Knowledge tab
3. Click "+" to add entity

## Expected Output

Able to add any entity

## Actual Output

"Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers."

**Comment by b1nbash** [comment]
Adding entity to "Investigation" works fine

**Comment by b1nbash** [comment]
Did you close this as completed because you were not able to reproduce the error?

**Comment by SamuelHassine** [comment]
No sorry! We will release a 5.8.1 now with the fix.

**Comment by SamuelHassine** [comment]
Ok, @b1nbash finally we will override the current 5.8.0. Please re-pull the image as soon as the release is here again.
