### ISSUE TITLE
alientvault connector - ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start 

### ISSUE THREAD

**Issue by th2scaface** [LuatixHQ/opencti#3554]
i'm faicing an issue with my opencti connector it keep restarting again and again, when i check the logs i get this: "ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration... Terminated"
 any help plz

**Comment by Kedae** [comment]
Hi, can you check the configuration of your opencti within the alienvault connector ? In the config.yml file

**Comment by pavel0807** [comment]
in OPENCTI_URL( something that) write the ip your docker addresses (http://172.*.0.1:8080)  also if you add gpg key then delete key

**Comment by nino-filigran** [comment]
@th2scaface we're currently reveiwing open tickets. Did the support provided helped you?

**Comment by nino-filigran** [comment]
Closing the ticket since no response
