### ISSUE TITLE
Docker: "Platform start fail - [SEARCH] Search engine seems down" on fresh install

### ISSUE THREAD

**Issue by FIying-Scotsman** [LuatixHQ/opencti#3560]
## Description

Using the default Docker compose file found [here](https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml) and following the guide (including setting the ES memory limit) results in a:

> ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":"connect ECONNREFUSED 172.x.x.x:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:61:53)\n    at /opt/opencti/build/src/database/engine.js:182:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:172:3)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:131:3)\n    at platformStart (/opt/opencti/build/src/boot.js:179:5)"} timestamp=2023-06-21T13:52:12.496Z version=5.8.2 

Message loop in the logs before the event emitter runs out of memory:-

> (node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
2023-06-21T13:53:43.634994183Z (Use `node --trace-warnings ...` to show where the warning was created)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } _Ubuntu 20.04 under an Azure VM_
3. OpenCTI version: { e.g. OpenCTI 1.0.2 } _5.8.2_
4. OpenCTI client: { e.g. frontend or python } _Backend/Node_
5. Other environment details: _Environment is being run through a fresh instance of Portainer with the required ports open (8000, 9000 and 8080)._

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Via Portainer, use the Docker Compose config linked above and start a single node stack. The stack will pull the images as expected, and the front end will load but no data is ingested; no containers run (an error about the OpenCTI API being down is printed to their respective logs) and the message above is shown in the OpenCTI container logs.

## Expected Output

Platform should accept connections between connectors and should print activity logs when a user logs in etc.

## Actual Output

Connectors fail to connect to the OpenCTI main instance citing: 

> ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

Only the above error is shown in the OpenCTI container log (where as before it would show users logging in etc).

**Comment by Archidoit** [comment]
Can you provide more information?

**Comment by FIying-Scotsman** [comment]
> Can you provide more information?

Apologies - pressed return a bit too early. Added more details to the issue.

**Comment by walkee-slush** [comment]
I am experiencing the same issue. Any update on this?

**Comment by StitchDave** [comment]
I too am experiencing this issue.   Please update.

**Comment by FIying-Scotsman** [comment]
Updated to 5.8.7 and it appears this issue may have been fixed. Connectors are communicating as expected and the "Search engine" error appears to have stopped after the ES cluster finishes initialising.

**Comment by StitchDave** [comment]
Would you mind sharing the docker-compose.yml and your ENV vars?  Sanitized, of course.   What version of portainer are you using also?

**Comment by FIying-Scotsman** [comment]
> Would you mind sharing the docker-compose.yml and your ENV vars? Sanitized, of course. What version of portainer are you using also?

I'm using the [latest compose file](https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml) (updated yesterday at time of this post). It's literally copy-pasted from that directly with only the required changes (username/password changes). Connectors were re-added after verifying the error stopped after the ES cluster had settled (which took 3 - 5 mins depending on whether you've got a fresh instance/deleted the old ES volume or whether it was upgrading an existing one).

ENV (same one as on the above repo):

OPENCTI_ADMIN_EMAIL= ---
OPENCTI_ADMIN_PASSWORD= ---
OPENCTI_ADMIN_TOKEN= ---
OPENCTI_BASE_URL=http://localhost:8080
MINIO_ROOT_USER= ---
MINIO_ROOT_PASSWORD= ---
RABBITMQ_DEFAULT_USER= ---
RABBITMQ_DEFAULT_PASS= ---
CONNECTOR_EXPORT_FILE_STIX_ID= [UUID]
CONNECTOR_EXPORT_FILE_CSV_ID= [UUID]
CONNECTOR_EXPORT_FILE_TXT_ID= [UUID]
CONNECTOR_IMPORT_FILE_STIX_ID= [UUID]
CONNECTOR_IMPORT_DOCUMENT_ID=  [UUID]
SMTP_HOSTNAME=localhost
ELASTIC_MEMORY_SIZE=4G


Portainer version: 2.18.3 BE.

**Comment by Obdam** [comment]
For what's worth: I had the exact same problem, and my issue indeed was resolved by waiting on the ElasticSearch container. However, to make it work, I needed to remap the default RABBITMQ_NODENAME=rabbit01@localhost username to the RABBITMQ_DEFAULT_USER username filled in the .env file.

**Comment by SaintPepsi2481** [comment]
I had this issue as well, using /sys/proc/kernel/random was not taking. I manually generated UUID's and filled them in to .env - then brought up the docker containers, waited 5 minutes for ES and attempted successfully.
