### ISSUE TITLE
Display T-number ID (or CAPEC ID) of Attack pattern in the "Add Entities" screen

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3565]
When entering the MITER ATT&CK pattern, in the previous version (5.7.4), a code starting with T appeared in the name to distinguish whether it was mobile or enterprise, but now only the name appears and it is not distinguished.

Below is a picture showing the issue mentioned above.
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/2ebc4797-dd6c-4c8e-af64-89f833e6aa53)

Is it possible to change the UI in settings? If not, I hope the issue is fixed.

Thanks for reading :)

**Comment by Jipegien** [comment]
Not normal. We must display the T number.
