### ISSUE TITLE
Add EPSS Support for Vulnerability Entity

### ISSUE THREAD

**Issue by lister-b** [LuatixHQ/opencti#3568]
## Use case

Support using EPSS for scoring Vulnerability Entities. 

Details on EPSS can be found here https://www.first.org/epss/faq 

## Current Workaround

Current workaround is to use the CVSS Score field, but add the EPSS score. Ideally we would want to use both at the same time 

## Proposed Solution

Add an extra field for the Vulnerability entity that allows for EPSS to be scored

**Comment by Arcuza** [comment]
One MASSIVE vote for this to be implemented! We also need a way to see EPSS score history, because EPSS is not a scalar, it's a time series of values, Where change/delta in EPSS is important.
