### ISSUE TITLE
Add "updated_at" / "modified" field in "enum ReportsFilter"

### ISSUE THREAD

**Issue by vinisimoes** [LuatixHQ/opencti#3580]
## Use case

When filtering reports, it is currently not possible to do so using the "updated_at" or "modified" fields, because they are not included in the ReportsFilter enum.

## Proposed Solution

Insert these fields inside the ReportsFilter enum.

## If the feature request is approved, would you be willing to submit a PR?

Yes, but help would be needed.

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/4393
