### ISSUE TITLE
SAML SSO Group Mapping not functioning

### ISSUE THREAD

**Issue by j-wade** [LuatixHQ/opencti#3589]
## Description

When attempting to map users to groups in a docker swarm deployment for SAML SSO, we are able to see the user creation, but we have not been able to successfully map using the group mapping. The configuration is added below

For PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING we have tried all 6 group GUIDs to a group that is already deployed, we've attempted to change the name of the group to not include spaces, we even tried mapping to the internal_id associated with group object. 
Finally I tried mapping to a new non existent group with auto-create enabled, we see the user get created, but the user is not associated with any groups/organizations and the new "Random" group was not created, with no error messages logged.

## Environment

1. Docker container running locally on Mac for testing and deployed to production within Azure
2. OpenCTI version: OpenCTI 5.7.6
3. OpenCTI client: Frontend
4. Other environment details:

- PROVIDERS__SAML__STRATEGY=SamlStrategy 
- "PROVIDERS__SAML__CONFIG__LABEL=Login with SAML"
- PROVIDERS__SAML__CONFIG__ISSUER=http://localhost:8088
- PROVIDERS__SAML__CONFIG__SAML_CALLBACK_URL=http://localhost:8088/auth/saml/callback
- PROVIDERS__SAML__CONFIG__ENTRY_POINT=https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/saml2
- PROVIDERS__SAML__CONFIG__CERT=MIIC8DCCAdixxxxxx
- PROVIDERS__SAML__CONFIG__ACCOUNT_ATTRIBUTE=[\"nameID\"]
- "PROVIDERS__SAML__CONFIG__FIRSTNAME_ATTRIBUTE=[\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname\"]"
- "PROVIDERS__SAML__CONFIG__LASTNAME_ATTRIBUTE=[\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname\"]"
- "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUP_ATTRIBUTES=[\"http://schemas.microsoft.com/ws/2008/06/identity/claims/groups\"]"
- "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:Random\"]"
- PROVIDERS__SAML__CONFIG__AUTO_CREATE_GROUP=true

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Attempt to use "Login with SAML"

## Expected Output

User will be created with auto-mapping of user to group based off of PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING

## Actual Output

User is created with no group assignments

## Additional information

{"category":"APP","level":"debug","message":"[SAML] Successfully logged","profile":{"attributes":{"http://schemas.microsoft.com/claims/authnmethodsreferences":["urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","http://schemas.microsoft.com/claims/multipleauthn"],"http://schemas.microsoft.com/identity/claims/companyname":"xxxx xxxx","http://schemas.microsoft.com/identity/claims/displayname":"First Last","http://schemas.microsoft.com/identity/claims/identityprovider":"https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/","http://schemas.microsoft.com/identity/claims/objectidentifier":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","http://schemas.microsoft.com/identity/claims/tenantid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","http://schemas.microsoft.com/ws/2008/06/identity/claims/groups":["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"user@company.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname":"First","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"user@company.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname":"Last"},"http://schemas.microsoft.com/claims/authnmethodsreferences":["urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","http://schemas.microsoft.com/claims/multipleauthn"],"http://schemas.microsoft.com/identity/claims/companyname":"xxxx xxxx","http://schemas.microsoft.com/identity/claims/displayname":"First Last","http://schemas.microsoft.com/identity/claims/identityprovider":"https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/","http://schemas.microsoft.com/identity/claims/objectidentifier":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","http://schemas.microsoft.com/identity/claims/tenantid":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","http://schemas.microsoft.com/ws/2008/06/identity/claims/groups":["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"],"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"user@company.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname":"First","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"user@company.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname":"Last","inResponseTo":"_ef2dcb18467b405fa0a7","issuer":"https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/","nameID":"user@company.com","nameIDFormat":"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress","sessionIndex":"_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"},"timestamp":"2023-06-26T19:20:25.871Z","version":"5.7.6"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"User"}},{"match_phrase":{"parent_types.keyword":"User"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["user_email.keyword"],"query":"user@company.com"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"track_total_hits":true},"timestamp":"2023-06-26T19:20:25.873Z","version":"5.7.6"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"User"}},{"match_phrase":{"parent_types.keyword":"User"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["user_email.keyword"],"query":"user@company.com"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"track_total_hits":true},"timestamp":"2023-06-26T19:20:25.877Z","version":"5.7.6"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"User"}},{"match_phrase":{"parent_types.keyword":"User"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["user_email.keyword"],"query":"user@company.com"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_internal_relationships*","opencti_stix_meta_objects*","opencti_stix_meta_relationships*","opencti_stix_cyber_observable_relationships*","opencti_stix_domain_objects*","opencti_stix_core_relationships*","opencti_stix_sighting_relationships*","opencti_stix_cyber_observables*","opencti_inferred_entities*","opencti_inferred_relationships*"],"track_total_hits":true},"timestamp":"2023-06-26T19:20:26.321Z","version":"5.7.6"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Individual"}},{"match_phrase":{"parent_types.keyword":"Individual"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["contact_information.keyword"],"query":"user@company.com"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-06-26T19:20:26.338Z","version":"5.7.6"}
{"category":"APP","level":"debug","message":"[SEARCH] paginate","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"Individual"}},{"match_phrase":{"parent_types.keyword":"Individual"}}]}},{"bool":{"minimum_should_match":1,"should":[{"multi_match":{"fields":["contact_information.keyword"],"query":"user@company.com"}}]}}],"must_not":[]}},"size":200,"sort":[{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-06-26T19:20:26.500Z","version":"5.7.6"}
{"category":"APP","error":"You can't login without an organization","level":"error","message":"Error login through provider saml","timestamp":"2023-06-26T19:20:26.725Z","version":"5.7.6"}

**Comment by SamuelHassine** [comment]
Hello,

The relevant error message is at the end: `{"category":"APP","error":"You can't login without an organization","level":"error","message":"Error login through provider saml","timestamp":"2023-06-26T19:20:26.725Z","version":"5.7.6"}`.

Can you check that your user is in an organization (because you set a default platform organization)?

Kind regards,
Samuel

**Comment by j-wade** [comment]
Instead of setting a default platform organization and having all users be added to that, we want the mapping of groups to identify a security group the user is part of to decide the organization.

I have also tried using the config to map organizations with no success
- "PROVIDERS__SAML__CONFIG__ORGANIZATIONS_MANAGEMENT__ORGANIZATIONS_PATH=[\"http://schemas.microsoft.com/identity/claims/companyname\"]"
- "PROVIDERS__SAML__CONFIG__ORGANIZATIONS_MANAGEMENT__ORGANIZATIONS_MAPPING=[\"TenantOrgName:InternalOrgName\"]"

Is there a place I can write debug for what the mapped export is of https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/config/providers.js#L257 and/or L269?

**Comment by j-wade** [comment]
Closing, this issue was resolved with https://github.com/OpenCTI-Platform/opencti/issues/3938
