### ISSUE TITLE
Add a search field in the members' list of an Organization/Group Overview in Settings

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#3595]
## Use case

Being able to search for a specific user in a list of members of an Organization or a Group

## Current Workaround

ctrl-f

**Comment by SamuelHassine** [comment]
Also included here:

* List of members should be sortable / searchable
* List of triggers should be sortable / searchable
* There is no pagination and no infinite loading, the number of results to be displayed is unclear
  * Use props height in the ListLineContent to limit the height and connect infinite loading fonctions to infinite load inside the paper.
