### ISSUE TITLE
Bulk search does not return values from "x_opencti_additional_names" field

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#3598]
## Use case

The "additional names" field is functionally an alias for a file name. While bulk search returns values from based on the file's name, it doesn't return values from this field. So if we observe a file with multiple names, it is only identifiable by a one of the names (from the bulk search).

## Current Workaround

Search all file names individually in the global search

## Proposed Solution

Have the bulk search also query the "additional names" field for files

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by securitiz** [comment]
This also applies to Indicator patterns - unless the Indicator name matches the value searched (which likely doesn't happen if the pattern is regex or sqlite syntax), or there is a matching observable, the Indicator won't be returned in bulk search

**Comment by Jipegien** [comment]
Thanks for having posted this issue :)
