### ISSUE TITLE
opencti works only on localhost

### ISSUE THREAD

**Issue by irfaan0999** [LuatixHQ/opencti#3603]
Hello,

I followed the procedure to install opencti using docker. Everything installed correctly but I can run it only on localhost. I get a connection refused when trying to access it by  ip address. There are no fw rules. The opencti ip address is 192.168.70.134

<img width="599" alt="opencti" src="https://github.com/OpenCTI-Platform/opencti/assets/98009839/075e3b1f-1807-4a2e-8ea3-552dc066e975">

Can you advise how to access opencti by its ip address instead of localhost?

Regards,

**Comment by GoZ8** [comment]
Hey, can you send your docker-compose file ?

**Comment by irfaan0999** [comment]
The opencti platform were not able to start. The elasticsearch shards remained stuck at 54%. I installed it manually and it worked correctly. Unfortunately the lab has been destroyed :(.
