### ISSUE TITLE
The MITRE ATT&CK pattern is not visible in the correlation view.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3608]
Before update(ver 5.6.2), all entities including attack patterns were displayed in the correlation view.

However, in the current version(ver 5.7.4), the correlation view is shown with the attack pattern excluded.
![1](https://github.com/OpenCTI-Platform/opencti/assets/19428462/ff4242c4-54af-4084-90bf-02d4299acd17)
![2](https://github.com/OpenCTI-Platform/opencti/assets/19428462/2be2c9eb-4e5f-4db2-a27b-2b85b2a5d2b1)

Has this problem been fixed in the latest updated version(ver 5.8.7)?

**Comment by SamuelHassine** [comment]
For the moment, the list of entity types used for correlation has been reduced to a set of entity types. Turning this to feature to be able to select the entity types from a filter.

**Comment by misohouse** [comment]
> Thank you for answer.

Then, may I understand that the attack pattern entity type is not currently visible?

I wonder if it will be reflected in version 5.11.0

Below is current view.
![1](https://github.com/OpenCTI-Platform/opencti/assets/19428462/b513446e-88f1-4487-a5b9-3356867b2b47)
![2](https://github.com/OpenCTI-Platform/opencti/assets/19428462/62b57512-9371-4477-8943-9d64e18bd569)

**Comment by misohouse** [comment]
> For the moment, the list of entity types used for correlation has been reduced to a set of entity types. Turning this to feature to be able to select the entity types from a filter.
@SamuelHassine 

Then, may I understand that the attack pattern entity type is not currently visible?

I wonder if it will be reflected in version 5.11.0

Below is current view.
![1](https://github.com/OpenCTI-Platform/opencti/assets/19428462/6ed53c7b-851a-4b34-9cae-34c6bc4ac367)


![2](https://github.com/OpenCTI-Platform/opencti/assets/19428462/98d04606-c9ca-40c2-a38f-516c98f244c4)

**Comment by SamuelHassine** [comment]
This should be resolved now.
