### ISSUE TITLE
Vocab management does not work as expect

### ISSUE THREAD

**Issue by RomuDeuxfois** [LuatixHQ/opencti#3620]
## Description

- opinion vocab sorting by name seems incorrect
![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/83f370a1-9fb3-4b0b-a425-96ff70e9519e)

- the delete icon in the toolbar is not present
![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/5d9f8071-b048-4619-bc40-d012a338bd0d)

- in the toolbar, the 'add in container' appears if we do a select all, but not if we select some vocabs manually
![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/7a9e7bfe-718e-440d-912e-4a362fae7502)

**Comment by Archidoit** [comment]
Precision for the first point: the name sorting is uncorrect if we have had some vocabs, but correct if we keep only the built-in vocabs.
Steps to reproduce:
- Go to a list of vocabs. Sort by name -> correct sorting.
- Create a new vocab. Sort by name. -> incorrect sorting
