### ISSUE TITLE
What's the difference between "Nested objects" and "Relationships" in the Malware tab?

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#3625]
I'm trying to connect a malware entity with File Observables that store information about the malware (hash value, etc.).

**There must have been some intention to separate the two fields**, but usually in this case, **how should they be connected?**

Below is a screen showing that one file observable data (hash value starting with 9a43) is linked to both "Nested objects" and "Relationship" to the malware entity.

![1](https://github.com/OpenCTI-Platform/opencti/assets/19428462/9564c830-57c3-413f-93a9-f280365e495f)

**Comment by Jipegien** [comment]
The STIX 2.1 standard implements 2 "types" of relations:
- relationships like "located-at", "indicates", etc. to indicate a relationship between 2 distinct Objects.
- Nested object to represent sub-components, or other Objects that participates to define the Object.

After that, it depends how you consider things in your context, and of course how connectors have been implemented.
