### ISSUE TITLE
Run OpenCTI with existing S3 bucket

### ISSUE THREAD

**Issue by leitosama** [LuatixHQ/opencti#3641]
## Use case

Deploying OpenCTI with external S3 storage without creating new bucket (using already created S3 bucket by cloud admin)

## Current Workaround

Using MINIO instead of corporate S3 storage.

## Proposed Solution

Add new environment variable and config option (`minio:no_create_bucket` for example).  Option is boolean switch to create/no create bucket after connection to S3.

## If the feature request is approved, would you be willing to submit a PR?

Yes, I will try to code this feature.

**Comment by richard-julien** [comment]
Its already something we do but automatically.
Current process when connecting to AWS/Minio:
1. Try to access the bucket.
2. If succeed, continue
3. If fail, try to create the bucket
4. If fail, stop the platform start
