### ISSUE TITLE
Adding Observables and Task List to Threat Actors

### ISSUE THREAD

**Issue by cyberrunnerz** [LuatixHQ/opencti#3706]
## Use case
Improve the workflow of adding observables to Threat Actors. Often times we want to add an IP address or another observable to a threat actor.

## Current Workaround

Currently you have to add the observable, then go back to a threat actor and link that observable.  

## Proposed Solution

Duplicating what is already existing under Cases. Adding the grids for both Observables and Tasks would be useful for Threat Actors as well. 

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/139139743/6b6d0965-9f7d-4400-8fc8-3b227b9847f4)

**Comment by Jipegien** [comment]
In the Threat actor Knowledge tab, when you are in the Observables section, you can add a relationship to an existing Observable but also create it on the fly (click the + button a second time).

I don't understand your use case about the Tasks though. Why do you want to add this case management feature to a Threat Actor?
