### ISSUE TITLE
Knowledge graph filters alignment for containers

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#3716]
## Description

Knowledge graph filter make some entities fully disappears

Repro case.

1. Create Grouping A
2. Create Grouping B
3. Go to grouping A and add grouping B in entities
4. Go to knowledge graph
5. Play with the "filter entity types" filter to check/uncheck the Grouping entity type
6. After uncheck, grouping will not be displayed again if check again

**Comment by SouadHadjiat** [comment]
I can't reproduce this issue, what should we see exactly in the knowledge graph ? After step 3 (Go to grouping A and add grouping B in entities), when I go to the knowledge graph of Grouping A, I don't see anything, without even changing the filters. What should we see ?
https://demo.opencti.io/dashboard/analyses/groupings/f07dd5a4-04e6-45cb-a77c-096a0f363531/knowledge/graph
