### ISSUE TITLE
SAML Login Is Broken in OpenCTI 5.9.0

### ISSUE THREAD

**Issue by CyberKaizen** [LuatixHQ/opencti#3722]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.9.0
3. Other environment details: Running on Docker, Using Azure AD SAML for SSO

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Follow the instruction for SAML setup in https://docs.opencti.io/5.9.X/administration/introduction/

## Expected Output

For SAML to work.

## Actual Output

Was give the error message: Invalid authentication, please ask your administrator.

Also was given the error in logs shown below.
## Additional information

ERR Error login through provider saml | category=APP error=y.map is not a function timestamp=2023-07-11T23:33:21.589Z version=5.9.0
ERR Error login through provider saml | category=APP error=y.map is not a function timestamp=2023-07-11T23:33:42.188Z version=5.9.0
ERR Error login through provider saml | category=APP error=y.map is not a function timestamp=2023-07-11T23:36:00.878Z version=5.9.0

**Comment by richard-julien** [comment]
Can you please give us your configuration? (redacted of course for sensitive information)
Thanks

**Comment by SamuelHassine** [comment]
Turning to questions until qualification.

**Comment by CyberKaizen** [comment]
@SamuelHassine @richard-julien  Here's our configuration.
`

      # Authentication Strategy for SAML SSO
      - PROVIDERS__SAML__STRATEGY=SamlStrategy 
      - "PROVIDERS__SAML__CONFIG__LABEL=Login with Azure AD"
      - PROVIDERS__SAML__CONFIG__ISSUER=https://subdomain.ourdomain.com
      - PROVIDERS__SAML__CONFIG__ENTRY_POINT=https://login.microsoftonline.com/directorytenantid/saml2
      - PROVIDERS__SAML__CONFIG__SAML_CALLBACK_URL=https://subdomain.ourdomain.com/auth/saml/callback
      - PROVIDERS__SAML__CONFIG__CERT=MIIC..redacted
      - PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUP_ATTRIBUTES=[\"http://schemas.microsoft.com/ws/2008/06/identity/claims/groups\"]
      - PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"AzureSSOGroup:OpenCTIGroup\"]
      - PROVIDERS__SAML__CONFIG__AUTO_CREATE_GROUP=true
      # Authentication Fallback
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
`

**Comment by richard-julien** [comment]
Configuration in docker for array is a bit special.
Please take a look to https://docs.opencti.io/5.9.X/deployment/configuration/

```
If you need to put a list of elements for the key, it must have a special formatting. Here is an example for redirect URIs for OpenID config:


"PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=[\"https://demo.opencti.io/auth/oic/callback\"]"
```

**Comment by SamuelHassine** [comment]
Also, be sure that AzureSSOGroup is respecting case.

**Comment by CyberKaizen** [comment]
Thanks, I'll give this a shot and then get back to you on this.

**Comment by CyberKaizen** [comment]
By changing my config to use the special format for a list of elements, it allowed a user to sign in via SSO, only if the following was true:

- No Platform Organization is set
- There is a group a user can join automatically upon creation

`

      # Authentication Strategy for SAML SSO
      - PROVIDERS__SAML__STRATEGY=SamlStrategy 
      - "PROVIDERS__SAML__CONFIG__LABEL=Login with Azure AD"
      - "PROVIDERS__SAML__CONFIG__ISSUER=[\"https://subdomain.ourdomain.com\"]"
      - "PROVIDERS__SAML__CONFIG__ENTRY_POINT=[\"https://login.microsoftonline.com/directorytenantid/saml2\"]"
      - "PROVIDERS__SAML__CONFIG__SAML_CALLBACK_URL=[\"https://subdomain.ourdomain.com/auth/saml/callback\"]"
      - PROVIDERS__SAML__CONFIG__CERT=MIIC..redacted
      - "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUP_ATTRIBUTES=[\"http://schemas.microsoft.com/ws/2008/06/identity/claims/groups\"]"
      - "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"AzureSSOGroup:OpenCTIGroup\"]"
      - PROVIDERS__SAML__CONFIG__AUTO_CREATE_GROUP=true
      # Authentication Fallback
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
`

### Issues in this configuration
In this configuration an issue that comes up is that the **first and last names in the OpenCTI user profile is not auto set**:
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/77bba144-6f39-41dc-bcaa-90d7cfe86818)

The group and org assignment environment variables appear to be ignored and only the group with default membership enabled is attached to the new user created by SSO login.
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/16811091-c60c-4340-acea-96a1fe2c7884)
 
Proof of **group and org env variables potentially being ignored** comes from removing any groups that a user can be added to on user creation.
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/2a146eb7-023b-4dfd-b471-66f8f2face34)

If the configuration for group mapping is correct, should I be having this issue (on new SSO user created in OpenCTI upon login)?:
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/28281c7a-6f44-4bc8-9413-cdcae17f4602)


What I've observed happens **when a platform org is set** is of course a series of errors that the user needs to join an organization. Which happens by design I believe?:
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/c55b854a-7224-4d06-93b3-e5bc61e8e8ec)
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/fc8365b6-3044-4796-9954-b4bbc785a206)
`ERR Error login through provider saml | category=APP error=You can't login without an organization timestamp=2023-07-24T23:17:09.872Z version=5.9.0`

**Comment by CyberKaizen** [comment]
@SamuelHassine 
I've come up with this configuration in order to address the issues I shared in that basic config:
- Have a platform org set
- Not be reliant on setting a group with default membership via SSO provider group or role claim mapped to OpenCTI group. **I think by design we aren't supposed to have to enable default membership on every OpenCTI group we want a new user joined to, as that is what group mapping is for?**
- Automatically add any new SSO user to a defined Organization based on group or role claim from SSO provider
- Automatically populate First Name and Last Name in the OpenCTI profile using identity claims from SSO provider

```
      # Authentication Strategy for SAML SSO
      - PROVIDERS__SAML__STRATEGY=SamlStrategy 
      - "PROVIDERS__SAML__CONFIG__LABEL=Login with Azure AD"
      - "PROVIDERS__SAML__CONFIG__ISSUER=[\"https://subdomain.ourdomain.com\"]"
      - "PROVIDERS__SAML__CONFIG__FIRSTNAME_ATTRIBUTE=[\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname\"]"
      - "PROVIDERS__SAML__CONFIG__LASTNAME_ATTRIBUTE=[\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname\"]"
      - "PROVIDERS__SAML__CONFIG__ENTRY_POINT=[\"https://login.microsoftonline.com/directorytenantid/saml2\"]"
      - "PROVIDERS__SAML__CONFIG__SAML_CALLBACK_URL=[\"https://subdomain.ourdomain.com/auth/saml/callback\"]"
      - PROVIDERS__SAML__CONFIG__CERT=MIIC..redacted
      - "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUP_ATTRIBUTES=[\"http://schemas.microsoft.com/ws/2008/06/identity/claims/groups\"]"
      - "PROVIDERS__SAML__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"AzureSSOGroupUUID:OpenCTIGroup\"]"
      - "PROVIDERS__SAML__CONFIG__ORGANIZATIONS_MANAGEMENT__GROUP_ATTRIBUTES=[\"http://schemas.microsoft.com/ws/2008/06/identity/claims/groups\"]"
      - "PROVIDERS__SAML__CONFIG__ORGANIZATIONS_MANAGEMENT__GROUPS_MAPPING=[\"AzureSSOGroupUUID:My Platform Org\"]"
      - PROVIDERS__SAML__CONFIG__AUTO_CREATE_GROUP=true
      # Authentication Fallback
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
```

The SSO user is successfully created in OpenCTI but is unable to login, because no groups or organizations are added to the user (even though the environment variables are configured per documentation).
![image](https://github.com/OpenCTI-Platform/opencti/assets/78124503/0a81717c-0a60-491c-8697-6410d3b5d03c)

With this config I resolved the issue with first name and last name not auto populating, but I was unable to solve any of the other issues. Using developer tools I can see that OpenCTI receives the SAML payload from the Azure SSO provider with the correct values. In the logs, I can also see that Passport has properly parsed the SAML payload. I even tested using first name and last name attributes for group and org mapping (to check if the claim values from the SSO provider were the problem) with no luck.

Which is why I'm confused, that just the group and organization mapping is having problems. Because everything should have the right values but the DB is not committing what it needs to add to the user profile.

It is incredibly difficult for me to troubleshoot this on my own to find out if this is a user error or an actual bug.

**Comment by CyberKaizen** [comment]
@richard-julien @SamuelHassine 
Issue with group mapping was fixed using code changes suggested here:
#3938 

Additional code changes were required to fix mapping SSO group to OpenCTI Orgs. The code that does this for SAML is written as if it is the same for OpenID. Causing issues.

Now have working mapping for both organizations and groups.
