### ISSUE TITLE
TAXII filter: "spec_version", Unsupported parameters provided

### ISSUE THREAD

**Issue by timebotdon** [LuatixHQ/opencti#3765]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description
I'm attempting to poll a collection created from the OpenCTI frontend using this:
```
from requests import get
url = "http://192.168.1.100:8080/taxii2/root/collections/8efa253f-78c2-43d9-bec4-442c674d1d70/objects/?match%5Btype%5D=indicator&match%5Bspec_version%5D=2.1"

headers = {
    "Accept": "application/taxii+json;version=2.1",
    "Authorization": "Basic _redacted_"
}
response = get(url, headers=headers)
print(response.text)
```

However I'm receiving this:
`{"title":"Business validation","error_code":"FunctionalError","description":"Unsupported parameters provided","http_status":400,"details":{"category":"business","spec_version":"2.1"}}`

Removing the `match_spec_version` filter works, and I've come to understand that it is indeed an unsupported parameter for OpenCTI as seen [here](https://github.com/OpenCTI-Platform/opencti/blob/bc9e0700c2c8773a4a493a6845185aa730f39a89/opencti-platform/opencti-graphql/src/domain/taxii.js#L100). Could someone explain what was the rationale behind this? Based on the [TAXII 2.1 specifications](https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107518) it is mentioned that TAXII service should include the `match_spec_version` filter.  Thank you!

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.7.6
3. OpenCTI client: Python requests
4. Other environment details:
TAXII collection poll

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the above script as shown in the description
2. HTTP 400 code

**Comment by richard-julien** [comment]
As we only support 1 version (2.1) we go for throwing an unsupported error for now. We should authorized the parameter and throw only if not 2.1 for now. We will fix that.

**Comment by timebotdon** [comment]
I see, thanks for the clarification @richard-julien ! Would this change be implemented into the upcoming release?

**Comment by richard-julien** [comment]
Done. Will be released in the next version
