### ISSUE TITLE
Take into account Sightings in Distribution of Relations counts

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#3766]
## Use case

The APT Storm-0558, recently identified by Microsoft, originates from China and targets government agencies in the US.

We created an Intrusion Set for the APT, and wanted to create these relationships. However, as pointed out by Samuel Hassine, only STIX core relationships are taken into account on the Distribution of Relations section of the Knowledge tab, and not sightings. The sightings being Storm-0558 -> Sighted in/at -> USA and Sighted in/at -> Government.

It would be useful for this to be taken into account, so the knowledge section can be complete.

## Current Workaround

None, but can see the relations in the timeline.

## Proposed Solution

Allow for Sightings in Distribution of Relations as well as core relationships.

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/fe7cb39a-cad7-4ac4-b864-3e4bec9e65fe)
![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/4ccc1e46-b9b2-4da2-ac89-f9f7c58dcb67)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by Jipegien** [comment]
The usual way to describe an Intrusion Set targetting an org, sector or country is by using the relationship target.

Sighting has, originally, a more technical meaning. It describe the fact that a technical element (an observable) has been sighted in a system.

Have you consider using the "targets" relationship in your use case?

**Comment by dominictory** [comment]
> The usual way to describe an Intrusion Set targetting an org, sector or country is by using the relationship target.
> 
> Sighting has, originally, a more technical meaning. It describe the fact that a technical element (an observable) has been sighted in a system.
> 
> Have you consider using the "targets" relationship in your use case?

Hi, thank you for clarifying that. What would be the best way to create the "targets" relationship in this case?

**Comment by Jipegien** [comment]
You can go on the Knowledge tab of your Intrusion Set, section Victimology, hit the + button and select the target of your choice.

If you have a bunch of relationships and Entities to add, consider using the Analyst Workbench features that have a (little bit) more efficient way to chain the creation of entities and relationships. You will also be able there to verify what you have done before importing it in the platform.

Let me know if you need more information. :)

**Comment by dominictory** [comment]
> You can go on the Knowledge tab of your Intrusion Set, section Victimology, hit the + button and select the target of your choice.
> 
> If you have a bunch of relationships and Entities to add, consider using the Analyst Workbench features that have a (little bit) more efficient way to chain the creation of entities and relationships. You will also be able there to verify what you have done before importing it in the platform.
> 
> Let me know if you need more information. :)

Awesome, thank you.
