### ISSUE TITLE
OpenID is not catching user roles and restricted access log error

### ISSUE THREAD

**Issue by SergioIbIGZ** [LuatixHQ/opencti#3774]
## Prerequisites

- [X] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

Hello everyone!
We are configuring OpenCTI user access using OpenID. To do that, we use our internal company IDP identity provider. But we are unable to get it working!

The users in IDP/SSO have groups and roles, but the idea is to map user roles to OpenCTI groups and OpenCTI organizations.

We are following the documentation to achieve it (https://docs.opencti.io/5.9.X/deployment/authentication/#openid-connect-button), but after a lot of test and values changes, it is not working; seems that the users logs in properly, but OpenCTI can't match the user role to OpenCTI groups/orgs, and the access is not authorized.

Our OpenCTI server runs on K8S so we use environment variables to achieve the proper configuration. We are going to share it the current one, and the logs output, OPENID related (I ommit the CLIENT__ID and CLIENT__SECRET values).

```
  # OPENID:
  PROVIDERS__OPENID__STRATEGY: "OpenIDConnectStrategy"
  PROVIDERS__OPENID__CONFIG__LABEL: "Login with IDP"
  PROVIDERS__OPENID__CONFIG__ISSUER: "https://idp.****"
  PROVIDERS__OPENID__CONFIG__REDIRECT_URIS: "[\"https://opencti.url/auth/oic/callback\"]"

  # OPENID GROUPS ROLE MAPPING:
  PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_PATH: "[\"roles\"]"
  PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING: "[\"ACME_EU-ADMIN:Administrator\",\"ACME_HO-ADMIN:Administrator\",\"ACME_HO-ANALYST_CTI:Analyst\",\"ACME_HO-VIEWER_CTI:Viewer\"]"

  # OPENID ORGS ROLE MAPPING:
  PROVIDERS__OPENID__CONFIG__ORGANIZATIONS_MANAGEMENT__ORGANIZATIONS_PATH: "[\"roles\"]"
  PROVIDERS__OPENID__CONFIG__ORGANIZATIONS_MANAGEMENT__ORGANIZATIONS_MAPPING: "[\"ACME_EU-ADMIN:ACME_EU\",\"ACME_HO-ADMIN:ACME_HO\",\"ACME_HO-ANALYST_CTI:ACME_HO\",\"ACME_HO-VIEWER_CTI:ACME_HO\"]"
```

The groups and roles exist already in OpenCTI.
When clic on "Login with IDP", we are forwarded to our IDP login site, and after a proper login in that, we are sent to the main OpenCTI login form, but without any error in the user interface.
But according to logs (DEBUG level):

```
{"category":"APP","level":"debug","message":"[OPENID] Successfully logged","timestamp":"2023-07-12T13:15:03.613Z","userinfo":{"country":"ESP","email":"JOHNDOE@ACME.COM","given_name":"JOHN","name":"JOHN DOE","preferred_username":"E057603","roles":["ACME_EU-ADMIN"],"sub":"E057603"},"version":"5.9.0"}

{"category":"APP","decoded":{"azp":"fa89d7b3-b297-4a57-8f39-807123cbbcf7","exp":1689210902,"iat":1689167702,"iss":"https://idp.****/oidc/","jti":"5a40487a-a988-42f7-80e9-8d0ed4bce072","sub":"E057603"},"level":"debug","message":"[OPENID] Groups mapping on decoded access_token","timestamp":"2023-07-12T13:15:03.613Z","version":"5.9.0"}

{"category":"APP","error":"Restricted access, ask your administrator","level":"error","message":"Error login through provider oic","timestamp":"2023-07-12T13:15:03.614Z","version":"5.9.0"}
```
Looks like the user login is successful, but OpenCTI can't match the user roles to OpenCTI Groups/Organizations and the access is forbidden.
The message _[OPENID] Groups mapping on decoded access_token_ let me think about a posible idea. Maybe is the IDP not providing the user roles throught access_token to OpenCTI? I found a old issue about OPENID token use ( https://github.com/OpenCTI-Platform/opencti/issues/1521 ) but I can't figure out if it is related to our problem.

Is there any way to specify to OpenCTI where the user roles are coming in the IDP response?
Another possibility we are evaluating is that our internal IDP is not responding with the standard format that OpenCTI is waiting.

Please, if you have any idea to help us and you are so kind, is appreciated. Thank you!!!

## Environment

1. OS (where OpenCTI server runs): Alpine Linux v3.18 (official image, pod in K8S)
2. OpenCTI version: OpenCTI 5.9.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. OpenCTI 5.9.0 stock configuration
2. Create OpenCTI groups, organizations, roles
3. Set-up OpenID button config in OpenCTI using env values as explained

**Comment by SamuelHassine** [comment]
Hello @SergioIbIGZ,

It seems roles are not included in the JWT token given by your OIDC provider. I think you should add "groups_scope": "roles" to your configuration to be sure to request the scope "roles".

Kind regards,
Samuel

**Comment by SergioIbIGZ** [comment]
Hello Samuel, thanks for your answer.
We already test that config, according to the documentation, with no success.

```
PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_SCOPE: "roles"
```

I read in another recent issue (https://github.com/OpenCTI-Platform/opencti/issues/3718) about a broker OpenID using 5.9.x
Maybe is this related with my issue?

Thank you!

**Comment by Augustin-FL** [comment]
Hello
I noticed something which can explain your issue:

Currently, OpenCTI only support mapping roles and organizations from claims in the OpenID JWT itself. (the `access_token`). 

in my situation, the claims i'd like to map to OpenCTI roles are given through the `userinfo` endpoint and are not provided in the JWT by my OpenID Connect Provider. OpenCTI simply does not support that.

What's frustrating is that OpenCTI actually query the userinfo endpoint, but it only uses the response to fetch the user name and email.

Also, changing this behavior ("`using the claims from the userinfo endpoint instead of the JSON Web Token to retrieve user's roles`") would be a breaking change, some users may not be happy with it.

**Comment by SergioIbIGZ** [comment]
Hello @Augustin-FL 
Finally, we get the issue solved, as you can see in this another issue:

https://github.com/OpenCTI-Platform/opencti/issues/4463

Please check it out.
Im going to close this one. Thank you for your interest.
