### ISSUE TITLE
obserables show only 25 realtions

### ISSUE THREAD

**Issue by jack-reso** [LuatixHQ/opencti#3778]
## Description

when i use observation->12.1.1.1(one of my ipv4 address，it's belongs to ABC case) -> knowledge ,only shows 25 relationships when there are actually 40 relationships 
      ,however in cases->ABC case ->knowledge,it can show all 40 relations。

is it a bug?
## Environment 

1. OS docker
2. OpenCTI version: OpenCTI 5.8.7
3. OpenCTI client: chrome

**Comment by RomuDeuxfois** [comment]
Investigation : We need to use the ListLine with infinite loader component to handle this case.

**Comment by RomuDeuxfois** [comment]
@SamuelHassine do you have any idea how to implement list line in StixCyberObservableEntities ?
Thank you

**Comment by jack-reso** [comment]
i'm sorry to tell you that i found same question,the bug don't fixed.!!!
Environment
OS docker
OpenCTI version: OpenCTI 5.9.4
OpenCTI client: chrome


First, i need to tell you that the question still exists.
the first time page was show 40 enties,but when fresh it only last 25 too...

i try to find,i find this below, this.props.relay.refetchConnection(25);
![image](https://github.com/OpenCTI-Platform/opencti/assets/112871294/0eb2b330-ad03-4da8-8aec-c6698bff9adb)


howerer,in SyncLines.jsx ,it's "this.props.relay.refetchConnection(200);"
![image](https://github.com/OpenCTI-Platform/opencti/assets/112871294/f685814f-94bf-465f-8991-a67f60ec2841)

**Comment by jack-reso** [comment]
@SamuelHassine @RomuDeuxfois

**Comment by sher2020** [comment]
The best solution is to refer to Entities->Knowledge->'Observables'->  'Relationsships view'
@SamuelHassine @RomuDeuxfois
