### ISSUE TITLE
Cannot configure OpenID

### ISSUE THREAD

**Issue by kodebrain** [LuatixHQ/opencti#3782]
## Issue

Error login through provider oic - OpenID

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 22.04 }
2. OpenCTI version: { 5.8.7 }

## Additional information

  - PROVIDERS__OPENID__STRATEGY=OpenIDConnectStrategy 
  - "PROVIDERS__OPENID__CONFIG__LABEL=Log using OpenID"
  - PROVIDERS__OPENID__CONFIG__ISSUER=${sso_issuer}
  - PROVIDERS__OPENID__CONFIG__CLIENT_ID=${client_id}
  - PROVIDERS__OPENID__CONFIG__CLIENT_SECRET=${sso_client_secret}
  - "PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=[\"https://opencti.local.home.cti/auth/oic/callback\"]"
  - "PROVIDERS__OPENID__CONFIG__ROLES_MANAGEMENT__ROLES_SCOPE="roles"
  - "PROVIDERS__OPENID__CONFIG__ROLES_MANAGEMENT__ROLES_PATH=[\"roles\", \"realm_access.roles\", \"resource_access.account.roles\"]"
  - "PROVIDERS__OPENID__CONFIG__ROLES_MANAGEMENT__ROLES_MAPPING=[\"openctisso_default:Default\", "openctisso_admin:Administrator\]"
  
  
The redirection is working but it shows as authentication failing between the access management(openID)
The only error that lists from docker logs is 
"Error login through provider oic"
Other applications that use SSO works fine so it suggest issue is with some parameters that I'm missing on the application side of OpenCTI rather than openId

Do I've to remove any default group from the OpenCTI GUI when configuring SSO using OIDC ?

**Comment by SamuelHassine** [comment]
Hello,

Can you please put your application in "debug" log level. You should have more information about why the OIDC authentication if failing.

Kind regards,
Samuel

**Comment by kodebrain** [comment]
Hi Samuel,

Even after setting APP__APP_LOGS__LOGS_LEVEL=debug, I get the  generic error  "Error login through provider oic"
The authentication flow works (as I'm being redirected to the SSO and then back to the login page of the application), I'm not sure this is due to the roles mapping configuration.
["openctisso_default:Default", "openctisso_admin:Administrator]" - The administrator, connector and default are the groups/roles that I can see in opencti. 

Thank you
KB

**Comment by kodebrain** [comment]
The concept of roles between OpenCTI and Keycloak worked rather than groups configuration in keycloak.
for my config to work in keycloak
- created client scopes called groups
- created Realm roles called sso_lkio
- assigned the sso_lkio scope to the groups
- Add the groups to the client scopes in the client
This is supported by the fact that the realm_access claim contains roles and that configuring OpenCTI to handle these roles (instead of groups(keycloak)) resolved the issue.


      - "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_SCOPE=groups"
      - "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_PATH=[\"groups\", \"realm_access.groups\", \"resource_access.account.groups\"]"
      - "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"sso_lkio:Administrator\"]"

**Comment by it-mak** [comment]
PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_PATH does not work as documented when using array-style nested paths.
Do not trust logs or documentation here — they are misleading!

Just create keycloak role, and map it for your group, then map role for client. After that just use path with **POINT** notation. 
      - PROVIDERS__OPENID__CONFIG__PARAMS__SCOPE=openid email profile
      - "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_PATH=[\"resource_access.opencti.roles\"]"
      - "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"opencti-admin-role:Administrators\"]"
