### ISSUE TITLE
Create new Inferred Rule in Rules Engine: Inverse of "OBSERVABLES PROPAGATION IN REPORTS"

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#3784]
## Use case

When adding observables to a Report, it would be very helpful to also have the Indicator(s) that the observables are based on added to the report. That allows analysts to easily:

- see which Indicators would are associated with the Report's observables
- triage the relevant Indicators (make edits, especially to the Indicator Type [see #3783 ])

There is a way to generate indicators to observables and vice versa, but upon doing so from the context of a Report, the generated objects don't get added to the Report - so the analyst has to separately track down each of the generated objects and add them. This is even more difficult if a generated object was a duplicate.

Not all may want to pull in Indicators based on Observables, so this is a good candidate for an optional Rules Engine rule

## Current Workaround

Manually track down the Indicators for each Observable in a Report (this could be hundreds), add them all to the Report

## Proposed Solution

Create a Rules Engine rule such that:
IF
 - Report A contains Observable B
 - Indicator C based on Observable B
THEN
- Report A contains Indicator C

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
It has been covered with the rule "INDICATORS PROPAGATION IN REPORTS"
