### ISSUE TITLE
Custom Dashboard - Ability to reference Report's Publish Date

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#3796]
## Use case

We want to build a widget (vertical bar graph) in the custom dashboard based on the dates that reports were published. There used to be an option to choose created/modified/updated times, but not published time (see screenshot).

In version 5.9.3, I can't find any option to control which date is used

## Current Workaround

n/a

## Proposed Solution

Introduce ability to build widgets based on a Report's published date. This should be optional.

Published date is useful if the publishing of the report is an event. I.e. an uptick in cyber events (which result in Reports) can be identified with this graph. This date correlates more closely with when the activity potentially happened

Created date is useful for the maintainer of the platform, to see when reports were being created, especially by a connector (if filtered by technical creator/author). This date correlated more with when an action was taken in the platform. 

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/74f6b12a-d4d1-4b6f-8413-7d1d24dda535)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

In the platform `published` and `created` are synchronized. You can then safely use `created`. 

Kind regards,
Samuel

**Comment by securitiz** [comment]
Hi @SamuelHassine, thank you for the quick response. Validating in the demo instance, this is what I see:

1. I create a Vertical Bar Graph filtered on Alienvault Reports
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/2678dbf0-e459-4571-8263-c2149771cd64)

2. Parameters step doesn't offer a choice of timestamp
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/285de8bc-2c94-4922-92d0-539ce67eeeba)

3. Between 2011-2021, there are no reports with an Alienvault author:
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/57785f82-4716-4693-af24-b3f8aee254b3)

4. However, display 2011-2023 shows that 4,400+ Alienvault-authored reports were created in 2022
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/3f53f028-862d-455d-966c-917549562518)

4a. Side note: I think I found a small bug? The above screenshot encompasses 3/31/2023. The graph doesn't include 2023, and shows that all the reports were created in 2022. However, the below screen shot ends at 1/1/2023 which should still include all of 2022, but shows no reports created in 2022. This is because the Reports were generated roughly Jan 17, 2023, so there should be an extra space for 2023 and the 4k+ reports should be represented in 2023 (if we use the 'created in platform' date, and I'd argue we shouldn't :) ): 
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/8e8946ad-07f7-44bb-b228-78135bb46f50)

5. Sorting in the Reports view on Alienvault-authored reports shows that there are plenty of reports created/published in 2014
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/77daca7f-e4c3-425c-80ca-6e046861c328)

5a. Digging deeper into the first report shows that the published/created date are the same as you said (2014), but the report was created in the platform on January 17, 2023. **So, it seems that the widget reflects the date created in the platform, not the created/published date**
![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/8e45fd3b-3d56-4805-b4e2-31c3344ed27c)

**Comment by SamuelHassine** [comment]
Hello,

Yes, it is a bug on our side, you should be able to select the time field for timeseries (histogram) but right now it is hardcoded to `created_at`. Will change this asap.

Kind regards,
Samuel

**Comment by securitiz** [comment]
great, really appreciate your work samuel! thank you
