### ISSUE TITLE
Retention policy to delete Artifacts uses all memory until node stops

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#3819]
## Description

I create a retention policy to delete all artifacts older than 190 days.
Immediately memory use starts growing until a few minutes later node processes stop and we have to restart them manually.
Once restarted it is a loop, and the server keeps going to 100% memory use and stops again.

If we take a while restarting the service, another different server on the cluster, seems to take the retention policy and enters the same loop. 
As soon as we delete the retention policy, every thing works perfectly.

The policy is supposed to delete less than 8000 objects as seen on image below
![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/b07aee75-01f9-4d33-a385-823c131cd216)

In this other image below, you can see the ram of the first server (green) growing in a few minutes, then we restart the process, it repeats the RAM issue until node fails. We take some time to restart the green server so another server (red)  starts doing the same (We think it tries to execute the retention as first server is not available).
As we take some time in restarting this second server(red) the first one(green) starts to consume RAM again until fails.
Then we delete the retention policy and all normalizes and memory use is back to normal.

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/2c6ed0f8-e979-45da-9137-36805eba7eb0)

## Environment

Bare metal installation in Ubuntu 

If you need any other debugging, please ask.
The only information I can find on the logs, seems to be a connection error when the node process fails:
{"category":"APP","error":{"data":{"category":"technical","error":{"address":"10.113.100.130","code":"ECONNRESET","errno":-104,"port":5672,"syscall":"connect"},"http_status":500,"reason":"Error in amqp command execution"},"stacktrace":["UnknownError: An unknown error has occurred","at error (/opt/opencti/build/src/config/errors.js:8:10)","at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)","at amqpExecute (/opt/opencti/build/src/database/rabbitmq.js:72:11)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at askElementEnrichmentForConnector (/opt/opencti/build/src/domain/stixCoreObject.js:201:3)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"Unspecified","operation_query":"mutation($id:ID!$idConnector:ID!){stixCoreObjectEdit(id:$id){askEnrichment(connectorId:$idConnector){id}}}","size":109,"time":22991,"timestamp":"2023-07-21T19:41:24.378Z","type":"WRITE_ERROR","user":{"group_ids":["5ce56b5c-XX-XX-XXX-XXXXX"],"ip":"::ffff:10.111.100.32","organization_ids":[],"socket":"query","user_id":"XX-XX-XX-XX-XX"},"variables":{"id":"ipv4-addr--17c8278b-8bde-5a3e-a346-3ca2c4d2ba8c","idConnector":"a1XXXX6-68fd-4XXc-8XX5-XXXXX"},"version":"5.9.6"}

**Comment by richard-julien** [comment]
Hi @AlexSanchezN ,

Can you setup your logs in debug to have more information about the problem?

Thanks

**Comment by richard-julien** [comment]
Could you also tell us:
- how much memory you assign to the node? 
- The source you use to absorb your artefacts? 
- If artefact you absorb have a payload_bin property and the average size?
Thanks

**Comment by AlexSanchezN** [comment]
Hi @richard-julien ,

As we are having the problem in our production environment, I can't restart services without an 'excuse', so I will enable debug logs in next platform update (at your rate of versions, should not be long from now ! :-) )

Each node has 16GB of RAM memory. I tested with 32GB and the problem was the same.
In normal operation it hardly uses more than 8GB

Artifacts were imported from Malware Bazaar, and url-payload connectors (we are no longer using them in auto mode)
They may come from other connectors from opencti ecosystem (Shodan probably).

Please, find attached some example of the artifacts with the information you request. 
[artifacts.txt](https://github.com/OpenCTI-Platform/opencti/files/12312179/artifacts.txt)

Should you need any other information, don't hesitate to ask.

Thanks,
Àlex

**Comment by richard-julien** [comment]
Unfortunatly nothing very relevant in the txt.
Can you try to extract directly from elastisearch with Kibana the 100 oldest Artefact you have in database? Could be very helpful.

**Comment by AlexSanchezN** [comment]
Hi @richard-julien ,

please find attached the requested information (I think... never used kibana before): 
[Artifacts.csv](https://github.com/OpenCTI-Platform/opencti/files/12321673/Artifacts.csv)

If you need something else, don't hesitate to ask

Cheers,
Àlex

**Comment by AlexSanchezN** [comment]
Forgot to mention that I deleted creator_id and creator_id.keyword, in case it was 'dangerous' information to put in a public place

**Comment by richard-julien** [comment]
Unfortunatly I dont see anything problematic in the export.
At this point its impossible to help you without having access to your data.
Dont hesitate to start a conversation with me on slack, it will be easiest to find a way.
Thanks

**Comment by AlexSanchezN** [comment]
Hi, @richard-julien ,
We found that one index in the cluster had corruption problems. 
After recreating that index, the retention policy is now working.
Thank you very much for your help!
Hope we were not much of a nuisance...

Cheers,
Àlex
