### ISSUE TITLE
multi relationship with entities(system)

### ISSUE THREAD

**Issue by jack-reso** [LuatixHQ/opencti#3826]
## Use case

i need to create several relationships between system(belongs to entities),but now i can't.
however,for obervations,it can create multi relationship between two obervation.

## Proposed Solution

can you add this feature about create several relationships between system(belongs to entities) ?

thank you

**Comment by Jipegien** [comment]
Not sure to understand. You definitely can create multiple relationships between Systems, leveraging the common relationship "related-to".

Can you explain your use case?

**Comment by jack-reso** [comment]
in my case,for a systemA ,i have already create one relation between systemA and systemB ,named relation_1,have description named description_1 .
after that,i want to add a relation between systemA and systemB,have description named description_2 ,but it will update my relation_1,not add a new one.
for example:
first create relation:     systemA -> date: 2023.7.1-2023.7.2 -> systemB, description_1:this is first.
add relation:                systemA -> date: 2023.7.4-2023.7.5 -> systemB description_2:this is add.
final show:                   systemA -> date: 2023.7.1-2023.7.5 -> systemB description_2:this is add.

it's mix first relation and add relation.update relation,not create a new one,update date and  description.

**Comment by Jipegien** [comment]
it is because we deduplicate all objects in OpenCTI, including relationships, based on multiple criterias. For related-to relationships, as it is a "by default" relationship type, if the 2 relationships are not separated enough in time, it merges the 2 (I think).

Can you explain the nature of the relation between the 2 systems you have? What are you trying to represent?

**Comment by Jipegien** [comment]
related issue to the comment above : #3387

**Comment by Jipegien** [comment]
Should be solved by #3387. Feel free to reopen the issue if you still encounter the problem.
