### ISSUE TITLE
The search bar cannot implement the search function

### ISSUE THREAD

**Issue by jack-reso** [LuatixHQ/opencti#3827]
## Description

in observations -> knowledge > search bar,when i want to search one of my ip,search result is empty,however,ip is exists.
is it a bug?
besides,Can filter function be added?

1. OS docker
2. OpenCTI version: OpenCTI 5.9.6
3. OpenCTI client: chrome

**Comment by SarahBocognano** [comment]
![Capture d’écran (51)](https://github.com/OpenCTI-Platform/opencti/assets/98532359/10c2d375-f539-49ea-a979-71cb392f1530)
![Capture d’écran (52)](https://github.com/OpenCTI-Platform/opencti/assets/98532359/834c2943-9a1f-4ef3-87e0-0cc65f676fe5)


The search bar seems to works fine on my side, both in global observables and knowledge of those.
Can you try this on the demo at https://demo.opencti.io/dashboard and feedback us if it's not working ?
