### ISSUE TITLE
Important issue when udating an open vocab with alias

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3929]
## Reproducible Steps

1. Create a threat actor X
2. Update secondary motivation to "personal-gain"
3. Go in Settings => Taxonomies => Vocab => attack_motivation_ov
4. Update "personal-gain" and change to "financial-gain", and put "personal-gain" as alias, then click on update

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/234afbe0-fec7-4349-808a-e1f1508cd13a)

Result: The Threat actor now has "financial-gain" in primary motivation (and not only on secondary motivations)

Also, it has been seen, both from customers and in the Filigran instance, that this can lead to secondary motivations to be a string instead of a list:

Lunar Spider broken with this move: https://filigran.opencti.io/dashboard/threats/intrusion_sets/9adc75c6-704e-474f-9188-6ec7a83c55fd (but a lot of other intrusion sets as well).

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/a38be65d-78b9-4468-b715-bf790d767de9)

**Comment by Kedae** [comment]
Update : The issue for iterable is coming from the other way around.

1. No secondary motivation
2. One primary
3. Update vocab of primary
4. Kaboom
