### ISSUE TITLE
Bug when trying to add Observables in content mapping

### ISSUE THREAD

**Issue by SarahBocognano** [LuatixHQ/opencti#3934]
## Description

When trying to add observables of type media content (and possibly others, not tested) from the content mapping screen of the Cases > Incident Responses, we receive the following error (see picture attached) : [SEARCH] Error updating elastic (bulk indexing).

![image-20230804-105040](https://github.com/OpenCTI-Platform/opencti/assets/98532359/7d14706a-c866-4322-80b7-9d8c06fc533c)

**Comment by Kedae** [comment]
Fixed by https://github.com/OpenCTI-Platform/opencti/commit/ef3be1ff31db9f7f75a6193f2e210db29a73112f
