### ISSUE TITLE
Migrate to GraphQL tools

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#3991]
## Use case

➤ YN0061: │ @graphql-toolkit/common@npm:0.10.3 is deprecated: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

**Comment by Jipegien** [comment]
@Kedae The 5.13 is really packed already. Are you able to evaluate the amount of work it will imply and if it is something that can be done in 5.13? Or do we need to postponed in 5.14?
