### ISSUE TITLE
Error upon creation of "media-content" or "network-traffic" type observable

### ISSUE THREAD

**Issue by diasporado** [LuatixHQ/opencti#3992]
## Description

Once a "media-content" or "network traffic" type observable is created, clicking on it will trigger an unknown error.

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Create a "media-content" or "network-traffic" observable:
![image](https://github.com/OpenCTI-Platform/opencti/assets/9367969/fa1cedf8-c540-4f76-97fa-f7a80aed4ada)

2. Click into the created observable:
![image](https://github.com/OpenCTI-Platform/opencti/assets/9367969/1068f86c-e9a9-4b9c-8ea8-4580528e6983)

3. Exporting the observable in json format also triggers an error (issue with datetime suspected):
![image](https://github.com/OpenCTI-Platform/opencti/assets/9367969/f16e4612-b484-463c-a748-da1e48e600b0)

**Comment by Archidoit** [comment]
Hello! I've been able to reproduce the bug for network-traffic but not for media-content... Can you precise the fields you filled in the media-content creation form?

**Comment by diasporado** [comment]
> Hello! I've been able to reproduce the bug for network-traffic but not for media-content... Can you precise the fields you filled in the media-content creation form?

Please see screenshot below:

![image](https://github.com/OpenCTI-Platform/opencti/assets/9367969/42eff0b3-b664-4385-a5d2-41855ac1dee1)

corresponding error "GraphQLError: DateTime cannot be serialized from a non string, non numeric or non Date type {}"

**Comment by Kedae** [comment]
Could have been fixed by https://github.com/OpenCTI-Platform/opencti/commit/ef3be1ff31db9f7f75a6193f2e210db29a73112f 

To check

**Comment by SamuelHassine** [comment]
Yes, I think so.

**Comment by SamuelHassine** [comment]
To check on network-traffic! I did not make the modification.

**Comment by Archidoit** [comment]
yes the bug is fixed for media-content, I'm going to fix it for network-traffic
