### ISSUE TITLE
OpenCTI fails to start after upgrade to 5.9.6 and AWS Opensearch in 2.3 version

### ISSUE THREAD

**Issue by robert-pudlowski-mox** [LuatixHQ/opencti#3999]
## Description

I have OpenCTI on EKS cluster **fully working** on version 5.8.7 and AWS Opensearch in 1.3 version. 

After upgrade the OpenCTI to 5.9.6 version and AWS Opensearch to 2.3 version, OpenCTI platform fails to start. 

`{
    "category": "APP",
    "error": {
        "context": {
            "category": "technical",
            "error": {
                "meta": {
                    "headers": {
                        "access-control-allow-origin": "*",
                        "connection": "close",
                        "content-length": "8742",
                        "content-type": "application/json; charset=UTF-8",
                        "date": "Tue, 08 Aug 2023 09:04:56 GMT"
                    },
                    "meta": {
                        "aborted": false,
                        "attempts": 0,
                        "connection": {
                            "headers": {},
                            "id": "https://vpc-cyberoperations-opensearch-xxxxx.ap-east-1.es.amazonaws.com/",
                            "status": "alive",
                            "url": "https://vpc-cyberoperations-opensearch-xxxxx.ap-east-1.es.amazonaws.com/"
                        },
                        "context": null,
                        "name": "elasticsearch-js",
                        "request": {
                            "id": 2,
                            "options": {},
                            "params": {
                                "headers": {
                                    "accept": "application/vnd.elasticsearch+json; compatible-with=8,text/plain",
                                    "user-agent": "elasticsearch-js/8.8.1 Node.js 20.4.0; Transport 8.3.2; (linux 5.4.242-155.348.amzn2.x86_64 x64)",
                                    "x-elastic-client-meta": "es=8.8.1,js=20.4.0,t=8.3.2,hc=20.4.0"
                                },
                                "method": "HEAD",
                                "path": "/opencti_internal_objects",
                                "querystring": ""
                            }
                        }
                    },
                    "statusCode": 200,
                    "warnings": null
                },
                "name": "ProductNotSupportedError"
            },
            "http_status": 500,
            "reason": "[OPENCTI] Platform initialization fail"
        },
        "message": "An unknown error has occurred",
        "name": "UnknownError",
        "stack": "UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:393:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"
    },
    "level": "error",
    "message": "[OPENCTI] Platform start fail",
    "timestamp": "2023-08-08T09:04:56.075Z",
    "version": "5.9.6"
}`
## Environment

1. EKS
2. OpenCTI version: 5.9.6
3. Opensearch as managed service in AWS in 2.3 version

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run OpenCTI in 5.9.6 version
2. Run AWS Opensearch in 2.3 version
3.Try to connect opencti to open search

## Expected Output

OpenCTI is able to start

**Comment by SouadHadjiat** [comment]
Hello @robert-pudlowski-mox, 
Do you have more logs before the error ? Could you share the complete log of opencti platform start ?

**Comment by richard-julien** [comment]
Thats remind me a thread in the community slack.

Sean Monaghan
[1 year ago](https://filigran-community.slack.com/archives/CHZC2D38C/p1646403659462899?thread_ts=1646157964.585629&cid=CHZC2D38C)
`Circling back on this @Julien in case others experience the same. The root cause of our issue, and why the distribution field was not present within our opensearch version was that the cluster had been upgraded from ES with compatibility mode - compatibility.override_main_response_version: true.`

You need to add a config in opensearch: compatibility.override_main_response_version: true

**Comment by robert-pudlowski-mox** [comment]
@richard-julien @SouadHadjiat 

I added the compatibility.override_main_response_version: true and the issue still exists. Should I enable the compatibility on version 1.3 and after that upgrade it to 2.3? Or I can execute it already on upgraded cluster 2.3? 

I enabled it directly on 2.3 version and still the same error:

More logs: 

`{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-08-08T16:33:29.362Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-08-08T16:33:29.364Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[SEARCH] Elasticsearch (7.10.2) client selected / runtime sorting disabled","timestamp":"2023-08-08T16:33:29.468Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-08-08T16:33:29.469Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2023-08-08T16:33:29.490Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2023-08-08T16:33:29.566Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'base' client ready","timestamp":"2023-08-08T16:33:29.577Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Clients initialized in Single mode","timestamp":"2023-08-08T16:33:29.578Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2023-08-08T16:33:29.578Z","version":"5.9.6"}
{"category":"APP","level":"warn","message":"[CHECK] SMTP seems down, email notification will may not work","timestamp":"2023-08-08T16:33:29.582Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2023-08-08T16:33:29.616Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'subscriber' client ready","timestamp":"2023-08-08T16:33:29.620Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager pub sub listener initialized","timestamp":"2023-08-08T16:33:29.620Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'lock' client ready","timestamp":"2023-08-08T16:33:29.624Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2023-08-08T16:33:29.626Z","version":"5.9.6"}
{"category":"APP","error":{"context":{},"message":"{\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}","name":"ResponseError","stack":"ResponseError: {\"error\":\"Content-Type header [application/vnd.elasticsearch+json; compatible-with=8] is not supported\",\"status\":406}\n    at eTt.request (/opt/opencti/build/node_modules/@elastic/transport/src/Transport.ts:535:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at CDe.SearchApi [as search] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/search.ts:85:10)\n    at loadEntity (/opt/opencti/build/src/database/middleware.js:388:20)\n    at isExistingPlatform (/opt/opencti/build/src/initialization.js:342:23)\n    at platformInit (/opt/opencti/build/src/initialization.js:370:27)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[SEARCH] Paginate fail","query":{"_source":true,"body":{"query":{"bool":{"must":[{"bool":{"minimum_should_match":1,"should":[{"match_phrase":{"entity_type.keyword":"MigrationStatus"}},{"match_phrase":{"parent_types.keyword":"MigrationStatus"}}]}}],"must_not":[]}},"size":200,"sort":[{"_score":"desc"},{"standard_id.keyword":"asc"}]},"ignore_throttled":false,"index":["opencti_internal_objects*","opencti_stix_meta_objects*","opencti_stix_domain_objects*","opencti_stix_cyber_observables*","opencti_inferred_entities*"],"track_total_hits":true},"timestamp":"2023-08-08T16:33:29.663Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] New platform detected, initialization...","timestamp":"2023-08-08T16:33:29.663Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2023-08-08T16:33:29.742Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":{"meta":{"headers":{"access-control-allow-origin":"*","connection":"close","content-length":"8742","content-type":"application/json; charset=UTF-8","date":"Tue, 08 Aug 2023 16:33:29 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"headers":{},"id":"https://vpc-cyberoperations-opensearch-xxxx-east-1.es.amazonaws.com/","status":"alive","url":"https://vpc-cyberoperations-opensearch-xxxx-east-1.es.amazonaws.com/"},"context":null,"name":"elasticsearch-js","request":{"id":2,"options":{},"params":{"headers":{"accept":"application/vnd.elasticsearch+json; compatible-with=8,text/plain","user-agent":"elasticsearch-js/8.8.1 Node.js 20.4.0; Transport 8.3.2; (linux 5.4.242-155.348.amzn2.x86_64 x64)","x-elastic-client-meta":"es=8.8.1,js=20.4.0,t=8.3.2,hc=20.4.0"},"method":"HEAD","path":"/opencti_internal_objects","querystring":""}}},"statusCode":200,"warnings":null},"name":"ProductNotSupportedError"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:393:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-08-08T16:33:29.743Z","version":"5.9.6"}`

**Comment by robert-pudlowski-mox** [comment]
The issue is fixed after changing the value to false: `compatibility.override_main_response_version: false`

Now, there is issue with database, any idea? 

Why the migration want to be executed? 

`{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-08-08T19:00:05.448Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-08-08T19:00:05.451Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[SEARCH] OpenSearch (2.3.0) client selected / runtime sorting disabled","timestamp":"2023-08-08T19:00:05.542Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-08-08T19:00:05.543Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2023-08-08T19:00:05.564Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2023-08-08T19:00:05.630Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'base' client ready","timestamp":"2023-08-08T19:00:05.642Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Clients initialized in Single mode","timestamp":"2023-08-08T19:00:05.642Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2023-08-08T19:00:05.643Z","version":"5.9.6"}
{"category":"APP","level":"warn","message":"[CHECK] SMTP seems down, email notification will may not work","timestamp":"2023-08-08T19:00:05.647Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2023-08-08T19:00:05.682Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'subscriber' client ready","timestamp":"2023-08-08T19:00:05.686Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager pub sub listener initialized","timestamp":"2023-08-08T19:00:05.687Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'lock' client ready","timestamp":"2023-08-08T19:00:05.691Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2023-08-08T19:00:16.337Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2023-08-08T19:00:16.376Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2023-08-08T19:00:18.099Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 3 migrations from the database","timestamp":"2023-08-08T19:00:18.287Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] 6 migrations will be executed","timestamp":"2023-08-08T19:00:18.289Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids","timestamp":"2023-08-08T19:00:18.290Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids > started","timestamp":"2023-08-08T19:00:18.291Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids > elastic running task gntnqM36QvKoz8QqVVl-mw:274459","timestamp":"2023-08-08T19:00:18.302Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"task [gntnqM36QvKoz8QqVVl-mw:274459] isn't running and hasn't stored its results","root_cause":[{"reason":"task [gntnqM36QvKoz8QqVVl-mw:274459] isn't running and hasn't stored its results","type":"resource_not_found_exception"}],"type":"resource_not_found_exception"},"status":404},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"301","content-type":"application/json; charset=UTF-8","date":"Tue, 08 Aug 2023 19:00:28 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://vpc-cyberoperations-opensearch-xxx-east-1.es.amazonaws.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://vpc-cyberoperations-opensearch-xxxxx-east-1.es.amazonaws.com/"},"context":null,"name":"opensearch-js","request":{"id":28,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.3.0 (linux 5.4.242-155.348.amzn2.x86_64-x64; Node.js v20.4.0)"},"method":"GET","path":"/_tasks/gntnqM36QvKoz8QqVVl-mw%3A274459","querystring":"","timeout":30000}}},"statusCode":404},"name":"ResponseError"},"http_status":500,"reason":"Error updating elastic"},"message":"A database error has occurred","name":"DatabaseError","stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)\n    at /opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:47:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at oqs.up (/opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:52:3)"},"level":"error","message":"[MIGRATION] Error during migration","timestamp":"2023-08-08T19:00:28.321Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2023-08-08T19:00:28.322Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"_stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)\n    at /opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:47:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at oqs.up (/opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:52:3)","data":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"task [gntnqM36QvKoz8QqVVl-mw:274459] isn't running and hasn't stored its results","root_cause":[{"reason":"task [gntnqM36QvKoz8QqVVl-mw:274459] isn't running and hasn't stored its results","type":"resource_not_found_exception"}],"type":"resource_not_found_exception"},"status":404},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"301","content-type":"application/json; charset=UTF-8","date":"Tue, 08 Aug 2023 19:00:28 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://vpc-cyberoperations-opensearch-yvysv245yj4yev4s7kv6bkqj4e.ap-east-1.es.amazonaws.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://vpc-cyberoperations-opensearch-xxxx-east-1.es.amazonaws.com/"},"context":null,"name":"opensearch-js","request":{"id":28,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.3.0 (linux 5.4.242-155.348.amzn2.x86_64-x64; Node.js v20.4.0)"},"method":"GET","path":"/_tasks/gntnqM36QvKoz8QqVVl-mw%3A274459","querystring":"","timeout":30000}}},"statusCode":404},"name":"ResponseError"},"http_status":500,"reason":"Error updating elastic"},"internalData":{},"name":"DatabaseError","time_thrown":"2023-08-08T19:00:28.320Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:393:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-08-08T19:00:28.323Z","version":"5.9.6"}`

**Comment by richard-julien** [comment]
It could be a problem on your opensearch cluster.
I remember a user that have this kind of problem and have rebuild the opensearch cluster because of that.
Looks like on certain cases there is some problem with the tasks management on opensearch see https://github.com/opensearch-project/OpenSearch/issues/9183.

Sorry to not have a clear fix answer for this problem that is more related to the opensearch cluster health.

**Comment by robert-pudlowski-mox** [comment]
@richard-julien so do You think that recreating the cluster will fix the issue? It is not connected to the indexes which were created in 1.3 version and they can be problematic in 2.3 version after upgrade?

**Comment by richard-julien** [comment]
The error is de to a problem accessing elasticsearch background tasks that migration triggers.
We see that once for a user that have resolved this problem by rebuilding a new cluster.
So not 100% sure but that how it was fixed by this user.

**Comment by robert-pudlowski-mox** [comment]
@richard-julien  I reverted the Opensearch to 1.3 version and the application started working, after that I upgraded the Opensearch to 2.3 and one more time the same issue :/ Error with database:

My full logs: 

`{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-08-09T14:42:08.708Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-08-09T14:42:08.710Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[SEARCH] OpenSearch (2.3.0) client selected / runtime sorting disabled","timestamp":"2023-08-09T14:42:08.810Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-08-09T14:42:08.810Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Minio is alive","timestamp":"2023-08-09T14:42:08.831Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2023-08-09T14:42:08.899Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'base' client ready","timestamp":"2023-08-09T14:42:08.906Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Clients initialized in Single mode","timestamp":"2023-08-09T14:42:08.907Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Redis is alive","timestamp":"2023-08-09T14:42:08.907Z","version":"5.9.6"}
{"category":"APP","level":"warn","message":"[CHECK] SMTP seems down, email notification will may not work","timestamp":"2023-08-09T14:42:08.915Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Python3 is available","timestamp":"2023-08-09T14:42:08.949Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'subscriber' client ready","timestamp":"2023-08-09T14:42:08.954Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI-MODULE] Cache manager pub sub listener initialized","timestamp":"2023-08-09T14:42:08.955Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[REDIS] Redis 'lock' client ready","timestamp":"2023-08-09T14:42:08.959Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Starting platform initialization","timestamp":"2023-08-09T14:42:08.962Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2023-08-09T14:42:09.094Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] admin user initialized","timestamp":"2023-08-09T14:42:13.386Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Read 3 migrations from the database","timestamp":"2023-08-09T14:42:13.799Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] 6 migrations will be executed","timestamp":"2023-08-09T14:42:13.802Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids","timestamp":"2023-08-09T14:42:13.803Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids > started","timestamp":"2023-08-09T14:42:13.803Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Triggers remove unused fields: recipients, user_ids, group_ids > elastic running task QOFSwWvIQHS87tX4eRdoOA:24483","timestamp":"2023-08-09T14:42:13.903Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"task [QOFSwWvIQHS87tX4eRdoOA:24483] isn't running and hasn't stored its results","root_cause":[{"reason":"task [QOFSwWvIQHS87tX4eRdoOA:24483] isn't running and hasn't stored its results","type":"resource_not_found_exception"}],"type":"resource_not_found_exception"},"status":404},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"299","content-type":"application/json; charset=UTF-8","date":"Wed, 09 Aug 2023 14:42:23 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://vpc-cyberoperations-opensearch-xxx.ap-east-1.es.amazonaws.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://vpc-cyberoperations-opensearch-xxxx-east-1.es.amazonaws.com/"},"context":null,"name":"opensearch-js","request":{"id":28,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.3.0 (linux 5.4.242-155.348.amzn2.x86_64-x64; Node.js v20.4.0)"},"method":"GET","path":"/_tasks/QOFSwWvIQHS87tX4eRdoOA%3A24483","querystring":"","timeout":30000}}},"statusCode":404},"name":"ResponseError"},"http_status":500,"reason":"Error updating elastic"},"message":"A database error has occurred","name":"DatabaseError","stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)\n    at /opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:47:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at oqs.up (/opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:52:3)"},"level":"error","message":"[MIGRATION] Error during migration","timestamp":"2023-08-09T14:42:23.925Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[INIT] Platform initialization done","timestamp":"2023-08-09T14:42:23.926Z","version":"5.9.6"}
{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"_stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:54:48)\n    at /opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:47:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at oqs.up (/opt/opencti/build/src/migrations/1687529127415-triggers-remove-unused-field.js:52:3)","data":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"task [QOFSwWvIQHS87tX4eRdoOA:24483] isn't running and hasn't stored its results","root_cause":[{"reason":"task [QOFSwWvIQHS87tX4eRdoOA:24483] isn't running and hasn't stored its results","type":"resource_not_found_exception"}],"type":"resource_not_found_exception"},"status":404},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"299","content-type":"application/json; charset=UTF-8","date":"Wed, 09 Aug 2023 14:42:23 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://vpc-cyberoperations-opensearch-xxx-east-1.es.amazonaws.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://vpc-cyberoperations-opensearch-xxxx-east-1.es.amazonaws.com/"},"context":null,"name":"opensearch-js","request":{"id":28,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.3.0 (linux 5.4.242-155.348.amzn2.x86_64-x64; Node.js v20.4.0)"},"method":"GET","path":"/_tasks/QOFSwWvIQHS87tX4eRdoOA%3A24483","querystring":"","timeout":30000}}},"statusCode":404},"name":"ResponseError"},"http_status":500,"reason":"Error updating elastic"},"internalData":{},"name":"DatabaseError","time_thrown":"2023-08-09T14:42:23.924Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:68:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:393:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:183:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-08-09T14:42:23.927Z","version":"5.9.6"}`

Any ideas? Cluster is working and is green. There is no any errors with indices.

**Comment by robert-pudlowski-mox** [comment]
@richard-julien - now i just reverted opencti from 5.9.6 version to 5.8.7 and everything works well. So it looks thats it issue with latest version and : 

` Triggers remove unused fields: recipients, user_ids, group_ids `

Should I execute any specific action during upgrading the opencti from version 5.8.7 to 5.9.6? 

BTW. is it possible to upgrade opensearch to 2.7.0 version and the openCTI will be compatible? or the 2.3.0 opensearch is the maximum version for now?

**Comment by robert-pudlowski-mox** [comment]
The main issue is fixed, I will close new one for new issue with upgrade
