### ISSUE TITLE
Unable to verify first certificate (elasticsearch)

### ISSUE THREAD

**Issue by Pez721** [LuatixHQ/opencti#4001]
## Description

Hi, I am attempting to install opencti in kubernetes (GKE). The idea is to use our existing elasticsearch instance, also in GKE but in another GCP project. The opencti deployment pods do not start, with the following error logs:

{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-08-08T10:45:55.007Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-08-08T10:45:55.010Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[SEARCH] Elasticsearch (8.7.1) client selected / runtime sorting enabled","timestamp":"2023-08-08T10:45:55.104Z","version":"5.9.6"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-08-08T10:45:55.105Z","version":"5.9.6"}
{"category":"APP","error":{"context":{},"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1627:34)\n    at TLSSocket.emit (node:events:512:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1038:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:824:12)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-08-08T10:45:55.159Z","version":"5.9.6"}

The environment variables are set as:
      ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED:  true
      ELASTICSEARCH__URL:                       https://vseca-pp-data-elastic-es-http.elastic-stack.es.local:9200
      ELASTICSEARCH__USERNAME:                  opencti
      ELASTICSEARCH__PASSWORD:                  <password>
      ELASTICSEARCH__SSL__CA:                   <set to the key 'ca.crt' in secret 'opencti-elastic-cert'>  Optional: false
      ELASTICSEARCH__INDEX_PREFIX:              opencti-

If I curl to the elastic instance from within my opencti cluster using the certificate, it suggests it is valid:

[ansible@0bc8ca192b88 ~]$ curl -v https://vseca-pp-data-elastic-es-http.elastic-stack.es.local:9200 --cacert cert.crt
*   Trying 10.60.1.199:9200...
* Connected to vseca-pp-data-elastic-es-http.elastic-stack.es.local (10.60.1.199) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: cert.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Unknown (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Unknown (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=vseca-pp-data-elastic; CN=vseca-pp-data-elastic-es-http.elastic-stack.es.local
*  start date: Mar 10 11:28:58 2023 GMT
*  expire date: Mar  9 11:38:58 2024 GMT
*  subjectAltName: host "vseca-pp-data-elastic-es-http.elastic-stack.es.local" matched cert's "vseca-pp-data-elastic-es-http.elastic-stack.es.local"
*  issuer: OU=vseca-pp-data-elastic; CN=vseca-pp-data-elastic-http
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Unknown (23):
> GET / HTTP/1.1
> Host: vseca-pp-data-elastic-es-http.elastic-stack.es.local:9200
> User-Agent: curl/7.76.1
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Unknown (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Unknown (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Basic realm="security" charset="UTF-8"
< WWW-Authenticate: Bearer realm="security"
< WWW-Authenticate: ApiKey
< content-type: application/json
< content-length: 459
< 
* Connection #0 to host vseca-pp-data-elastic-es-http.elastic-stack.es.local left intact

Can you advise what causes this error "unable to verify the first certificate"?

Many thanks for your assistance.

**Comment by nino-filigran** [comment]
@Pez721 did you manage to get additional information/support for your query?

**Comment by nino-filigran** [comment]
Closing for now as no response.
