### ISSUE TITLE
In knowledge > indicators, select n things, try to export

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4009]
## Description

In knowledge > indicators, select n things, try to export in STIX:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/54b852ef-e457-42d8-9d26-3c25d8586d77)

Export is empty.

**Comment by RomuDeuxfois** [comment]
Reproducible in all entities

**Comment by RomuDeuxfois** [comment]
Fix on connectors side -> https://github.com/OpenCTI-Platform/connectors/issues/1337
