### ISSUE TITLE
When a banner in security policies in set, right menu in container => content is not correct

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4010]
## Description

When a banner in security policies in set, right menu in container => content is not correct:

Padding top is too low:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/286c8b1a-d5eb-4218-bac3-a195fd7390e6)

**Comment by RomuDeuxfois** [comment]
Deprioritized at 5.11.0
Goal: create a wrapper component containing bannerHeightNumber (userAuth) and applying it to the drawer + icon button
