### ISSUE TITLE
When having a platform with header, creating live trigger / digest, padding top is too low

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4011]
## Use case

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/8a092d47-a314-40ce-a731-fa57ab14055f)

When a banner in security policies in set, right menu in container => content is not correct:

Padding top is too low:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/286c8b1a-d5eb-4218-bac3-a195fd7390e6)

**Comment by SamuelHassine** [comment]
Sames in enrichment:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/e4801d16-b1b2-4f56-bfe0-5ca08785eb0b)

**Comment by SamuelHassine** [comment]
But is is correct in "Reports" => Create.

**Comment by RomuDeuxfois** [comment]
Deprioritized at 5.11.0
Goal: create a DrawerOpenCTI component containing bannerHeightNumber (userAuth) and applying it to the drawer + icon button

**Comment by RomuDeuxfois** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/4010
