### ISSUE TITLE
In the history of a sector, the relationship historic is not correct

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4012]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/cdb19c72-94f3-4391-a58c-d6f34fcc0747)

Originally:

* Only contains create / delete of relationships

Even if we would like to display also the modifications of the relationships:

* Icon is incorrect
* Message is not clear about which relationship has been modified so most of those messages are useless

**Comment by RomuDeuxfois** [comment]
Which icon we want depending on case (for relation) :
- create
- delete
-

**Comment by RomuDeuxfois** [comment]
Today we have :

For relation
| create | delete |
|----------|:-------------:|
| LinkOutlined | LinkOffOutlined |

For entity
| create | merge | update && replaces | update && changes | update && adds | update && removes | delete |
|----------|:-------------:|----------|:-------------:|----------|:-------------:|-------------:|
| AddOutlined | Merge | EditOutlined | EditOutlined | LinkVariantPlus | LinkVariantRemove | DeleteOutlined |

What do we want for the missing cases on relation ?

**Comment by Archidoit** [comment]
Comment: We don't want to display the modifications of relationships, but only the creations and deletions. The issue concerns all the entities (not only sectors).
