### ISSUE TITLE
Stix Sighting Validity Period

### ISSUE THREAD

**Issue by BradCookFCNZ** [LuatixHQ/opencti#4013]
## Scenario

There is no clear guidance within the stix specification as to how long a sighting should be valid for. OpenCTI's implementation graphql endpoint stixSightingRelationshipAdd produces the same sighting id unless first_seen changes by at least a month.

ref: [buildRelationTimeFilter](https://github.com/OpenCTI-Platform/opencti/blob/9d3439d1578ca7789b93bdd1b85eccc6e920fd92/opencti-platform/opencti-graphql/src/database/middleware.js#L2380)

In most instances we increment attribute counts and send upstream but some processors beyond our organization can't upsert existing sighting id's and require new unique sighting id's per bundle sent.

We don't have the ability within OpenCTI to force a new sighting id.

## Possible Solutions

Any combination of the following could work.

- Ability to set forceNew on stixSightingRelationshipAdd
```
mutation sighting {
  stixSightingRelationshipAdd(
    input: {
      attribute_count: 1
      forceNewId: true
      fromId: "indicator--ZZZ"
      toId: "identity--ZZZ"
      first_seen: "2023-06-27T09:48:44.000Z"
      last_seen: "2023-06-27T09:58:44.000Z"
    }
  ) {
    standard_id
    toStix
  }
}
```

- Set optional validity period on stixSightingRelationshipAdd
```
mutation sighting {
  stixSightingRelationshipAdd(
    input: {
      attribute_count: 1
      validForSeconds: 600
      fromId: "indicator--ZZZ"
      toId: "identity--ZZZ"
      first_seen: "2023-06-27T09:48:44.000Z"
      last_seen: "2023-06-29T09:48:44.000Z"
    }
  ) {
    standard_id
    toStix
  }
}
```

- Ability to mark a sighting as expired on stixSightingRelationshipEdit so that future stixSightingRelationshipAdd's generate new id's.
```
mutation sightingEdit {
  stixSightingRelationshipEdit(id: "ZZZZ") {
    fieldPatch(input: { key: "expired", value: true, operation: replace }) {
      standard_id
    }
  }
}
```

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by Jipegien** [comment]
We do not plan to differentiate deduplication rules for relationships at the moment. If done, it will be at a more generic level (deduplication rules customization panel).
