### ISSUE TITLE
Error when importing a file

### ISSUE THREAD

**Issue by OCTItest** [LuatixHQ/opencti#4040]
Hello,
We would like to import a JSON file into an analyse in our local  (updated) OpenCTI instance and on the demo version online. When we try to do it by clicking on Reports > Data > Uploaded files,  it appears that :

- Our observables, that are presents in our exported file, aren't imported in Open CTI
- Even if we can see how many entities and relationships were imported, we can not find them in the analyse.

We made that process few weeks ago and it worked.
Is it a bug or our method isn't good ?
Thanks,

**Comment by RomuDeuxfois** [comment]
Hi,

Can you send us the file you are trying to import ?
you can send it to us on slack in private message (filigran-community.slack.com - @Romuald Lemesle)
