### ISSUE TITLE
Ability to select objects in the Report's Correlation View

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#4065]
## Use case

Correlation view is very useful. Once identifying correlated objects, user should be able to view and/or open that object. Instead the user must search for that object  in the search bar

## Current Workaround

Search for the correlated object in the search bar

## Proposed Solution

Provide a link / method to open objects presented in the Correlation view. The same as the function currently available in the standard Knowledge Graph view

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
Same comportment as in Knowledge graph and investigation graph
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/239ba85f-16d7-449f-b3d9-2bd7e9dc3b45)

**Comment by Archidoit** [comment]
to be resolved with this feature: fix bad superposition of the correlation view bar (see the left side of the bottom bar in the capture) : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/59118b98-ff7a-42f0-a843-0366c44bab30)
