### ISSUE TITLE
issue for accessing Opencti by using docker

### ISSUE THREAD

**Issue by nsengiyumvamoses90** [LuatixHQ/opencti#4069]
I am trying to open localhost:8080 when I tried it failed what is the issues everything is setting it clearly

**Comment by nino-filigran** [comment]
@nsengiyumvamoses90 did you manage to get support on your issue?

**Comment by nsengiyumvamoses90** [comment]
Hello OpenCTI-Platform/opencti
I manage to solve it on my own

**Comment by nino-filigran** [comment]
Glad to hear! I'm closing this issue then :)

**Comment by nsengiyumvamoses90** [comment]
Awesome, thanks for the update!
