### ISSUE TITLE
Triggers and digests screen broken

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#4084]
## Description

In Filigran's instance, the Triggers and digests screen is broken

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/c629e22d-9cb2-4b00-8bb2-3a0a5508d328)

**Comment by SamuelHassine** [comment]
```
front-JBTNAK3K.js:8 RRNLRequestError: Relay request for `TriggersLinesPaginationQuery` failed by the following reasons:

1. Cannot read properties of undefined (reading 'includes')
     notifiers {
     ^^^
2. Cannot read properties of undefined (reading 'includes')
     notifiers {
     ^^^
3. Cannot read properties of undefined (reading 'includes')
     notifiers {
     ^^^
    at mys (front-JBTNAK3K.js:50:68)
    at front-JBTNAK3K.js:54:8442
```

**Comment by Archidoit** [comment]
@SamuelHassine @yassine-ouaamou 

To reproduce: 
- launch the platform in a state of OpenCTI before the migration "1691821747145-default-outcomes.js".
- create a trigger
- launch the platform in the current version,
- go to the 'Triggers and digests' tab
- an error occurs.

**Comment by Archidoit** [comment]
Explanation: the 'old' triggers have no notifiers...

**Comment by Archidoit** [comment]
Explanation: some triggers have 'null' as their notifiers... 
Solution: do a new migration to add the field notifiers to all the triggers (default value: UI)

**Comment by Archidoit** [comment]
To reproduce the bug:
- Launch the platform in a state before migration "1691821747145-default-outcomes"
- Create a trigger logged as admin, and an other logged as userX, different outcomes etc
- Launch the platform in the current state
- Go to the 'Triggers and digests' tab
- ERROR

**Comment by Archidoit** [comment]
Explanation: after the migration some triggers have 'notifiers' = null (why???), and that causes an error.
Solution:
- Do a migration to add notifiers = [] to all the triggers with notifiers = null

**Comment by Archidoit** [comment]
the number of the commit just before the commit with the "default-outcomes" migration : 7ee8a2e

**Comment by SamuelHassine** [comment]
Found with Julien. Not a but.
