### ISSUE TITLE
PDF viewer broken

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#4085]
## Description

The PDF viewer is broken in Filigran's instance of OpenCTI

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/81f6ed1a-5905-4ad0-a3a8-e54dcfd6877f)

**Comment by SarahBocognano** [comment]
The bug is due to the depedency update of react-pdf. It's working if we downgrade the version.
