### ISSUE TITLE
Timeout in platform startup, could we get a more descriptive error?

### ISSUE THREAD

**Issue by StitchDave** [LuatixHQ/opencti#4090]
## Use case

I have just installed the latest version of the docker-compose setup using portainer, and 3 instances in AWS.   I waited all day yesterday for the elasticsearch to settle.   This morning, I am getting the error:

opencti_opencti.1.13nc85qluwod@opencti-controller    | {"category":"APP","error":{"context":{},"message":"connect ETIMEDOUT 10.0.4.23:9000","name":"TimeoutError","stack":"Error: connect ETIMEDOUT 10.0.4.23:9000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1592:16)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-08-17T11:57:14.383Z","version":"5.9.6"}

## Current Workaround

None.

## Proposed Solution

It is hard to know WHAT is timing out.  So I would propose to change this in opencti-platform/opencti-graphql/src/boot.js:174

export const platformStart = async () => {
  logApp.info('[OPENCTI] Starting platform');
  try {
    // Check all dependencies access
    await checkSystemDependencies();
    // Init the cache manager
    await cacheManager.start();
    // Init the platform default
    await platformInit();
    // Init the modules
    await startModules();
  } catch (e) {
    logApp.error('[OPENCTI] Platform start fail', { error: e });
    process.exit(1);
  }
};

It would be better if there was an error for each thing... like one for cacheManager, one for checkSystemDependencies, one for modules, so we know which part of startup is failing.

## If the feature request is approved, would you be willing to submit a PR?

I am not a node guy, I mostly do python, so I don't really know where to start here.

**Comment by nino-filigran** [comment]
@richard-julien Do you have an opinion on this?

**Comment by richard-julien** [comment]
Hi @StitchDave, thats actually directly the error from the dependency lib. We will take a look to wrap that but for now  `ETIMEDOUT 10.0.4.23:9000` should be related to your configuration. Usually the 9000 port is used for minio/S3 connection

**Comment by shawrupesh** [comment]
@Jipegien Can I work on it? I will add few lines of code then we can easily identify which promise is getting failed

**Comment by Jipegien** [comment]
@shawrupesh Absolutely!

**Comment by shawrupesh** [comment]
Hi @Jipegien Raised the PR https://github.com/OpenCTI-Platform/opencti/pull/6242.
Thank You!
