### ISSUE TITLE
No relationship type available when creating a relationship from an Area

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4092]
No relationship type available when creating a relationship from an Area

## Steps to reproduce
Go to an Area. Go to the Knowledge tab.
Select 'Incidents' in the right tab.
Select an incident.
You can't create the relationship because there is no relationship type available.

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/8fde3dab-a21c-4d5d-8362-be5e06ea9bf7)

It is the same from relationship from Area to other entity types (Threat actor, campaigns etc)

**Comment by RomuDeuxfois** [comment]
Add a targets relationship from Incident to Area

**Comment by Archidoit** [comment]
Note: Area will be added to Victimology.
