### ISSUE TITLE
Map not showing activity or heat

### ISSUE THREAD

**Issue by javanothompson** [LuatixHQ/opencti#4093]
## Description

I've recently stood up an instance on OpenCTI and i've noticed that the maps does not show any activity.
The issue seems similar to https://github.com/OpenCTI-Platform/opencti/issues/1064 , but the dataset connector does not seem to be a thing anymore.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04 via Docker 
3. OpenCTI version: OpenCTI 5.9.6
4. OpenCTI client: Frontend
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Click Threats (left menu)
2.  Click Intrusion Sets (top tab)
3.  Pick an intrusion set.  (I made sure to choose one with targeted countries. In my example I used PUNK SPIDER)
4.  Click the Knowledge (top tab)
5.  Click Victimology (right side)

## Expected Output

I would expect that any countries listed under the Victimology graph to also be highlighted on the map. 

## Actual Output

Map has not highlights or heat.

## Screenshots (optional)
<img width="1923" alt="no heat" src="https://github.com/OpenCTI-Platform/opencti/assets/26121932/5c8e9183-c752-437f-90b6-5d2181f1911f">

**Comment by SamuelHassine** [comment]
Hello @javanothompson,

Do you use the OpenCTI Datasets connector for your countries?

 Actually, for the map to work, all the countries in the platform should have the 2 letters / 3 letters ISO codes in aliases like this:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/f3e959fb-9c56-4fb7-bd6b-b5d377762ebd)

If it is not the case, please use the connector to update your existing data, it will solve your problem.

Kind regards,
Samuel

**Comment by mhafizworks** [comment]
Hello @SamuelHassine 

I'm encountering the same issue where the map isn't functioning. As I'm relatively new to using OpenCTI, I've been searching for resources to assist me in enabling the dataset connector, but so far, I haven't had any luck finding guidance. I would greatly appreciate it if you could provide some assistance in enabling the dataset connector within OpenCTI. I've attached a screenshot for reference. Thank you!

<img width="2350" alt="Screenshot 2024-03-17 at 3 10 00 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/108706056/1feb21c8-deba-40b9-b2d1-4ccd2c474eec">

**Comment by javanothompson** [comment]
My apologies for not circling back to this.
@mhafizworks, the solution here was to add the opencti connector.  In my case, since we are using docker-compose, I was able to add the following to my config. https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/opencti/docker-compose.yml

**Comment by javanothompson** [comment]
Resolved on my end by using the provided connector

**Comment by mhafizworks** [comment]
Thank you very much @javanothompson for the sharing, it works now from my side. 

Beside that, I have encountered another issue related to the graph above the map, specifically with the 'relationship created' data not being displayed. However, when I change the opencti dashboard setting to 'Functional Date' for the data reference, it shows the data, but none of the other widgets display any data. Have you faced this issue before? Alternatively, do you have any suggestions to solve this problem? cc: @SamuelHassine 

<img width="919" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/108706056/480c827c-043e-4c3e-b100-205b7d39f886">
<img width="474" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/108706056/95c4c1da-0df2-49bd-b980-4198188e2ead">
<img width="1368" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/108706056/85c0fb6b-462b-410a-bab6-8058681273e4">
