### ISSUE TITLE
Missing icon for Threat Actors in Workbench

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4099]
## Description

Missing icon for Threat Actors in Workbench

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Create a workbench with a threat actor (group or individual) inside.
In the workbench display, the threat actor logo is not correct:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e9679608-bb37-4133-8a73-9e8545aa90ac)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/85c0dfd4-1750-41f9-a771-247adeb749f2)

**Comment by RomuDeuxfois** [comment]
I am not able to reproduce in master
![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/e88d401c-9cd3-4294-a2ce-75d12cd0298d)

Did I miss something?

**Comment by Archidoit** [comment]
If you add your threat actor from the + button at the bottom, the icon is correct.

To have the bad icon, follow these steps:
- import a file
- use ImportDocument to create a Workbench
- go to the workbench to see its content

**Comment by Archidoit** [comment]
Here is the file I use (generated from a threat actor, by doing an export-to-pdf) :
[2023-08-18T15_00_53.320Z_TLP_ALL_(ExportReportPdf)_Threat-Actor-Group-complete TA group_full (1).pdf](https://github.com/OpenCTI-Platform/opencti/files/12393279/2023-08-18T15_00_53.320Z_TLP_ALL_.ExportReportPdf._Threat-Actor-Group-complete.TA.group_full.1.pdf)

**Comment by Archidoit** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e43d1f50-eb0d-469d-83ed-ab700d866ba3)
