### ISSUE TITLE
Relationships with same start_time and stop_time

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#4130]
## Description

When a user creates a relationship through Knowledge (Graph) tab on a report the relationship will have the same start and stop times, which leads to issues like:

```
  File "/home/vscode/.local/lib/python3.10/site-packages/stix2/v21/bundle.py", line 35, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/stix2/base.py", line 212, in __init__
    temp_custom = self._check_property(
  File "/home/vscode/.local/lib/python3.10/site-packages/stix2/base.py", line 59, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': relationship--89cdfb12-c84a-446c-af2d-270bfbbc368b 'stop_time' must be later than 'start_time'
```

## Environment

2. OpenCTI version: 5.9.6

**Comment by SYNchroACK** [comment]
Also, then is not possible to change the timestamps, it will not update even if I change like the following:
![image](https://github.com/OpenCTI-Platform/opencti/assets/4184292/5339fa56-e574-4031-b215-977f0f904ab1)

**Comment by Archidoit** [comment]
It is possible to create relationships with stop time before the start time if the day is the same : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/bf079cc3-f647-42d6-a864-38b34be00a21)

Same for events start_time and stop_time

**Comment by Archidoit** [comment]
What did you do that leads to this python error?

**Comment by Archidoit** [comment]
For the bug about relationship stop_time edition, I've been able to reproduce it, and it will be resolved here: https://github.com/OpenCTI-Platform/opencti/issues/4133

**Comment by SYNchroACK** [comment]
> What did you do that leads to this python error?

@Archidoit `stix2.parse(bundle, allow_custom=True)`
Create a bundle with those relationships and you have the same result.

**Comment by Archidoit** [comment]
In OpenCTI we allow start_time and stop_time to be the same. But if you want to use some stix2 library functions that don't allow that, you can remove the stop_time attribute of the relationships that have same start_time and stop_time for instance. After creating a relationship from a report knowledge graph, you can also edit it from the graph to change the stop/start_time.
