### ISSUE TITLE
UI issue in Arsenal -> Malware React virtualised not behaving correctly.

### ISSUE THREAD

**Issue by sandeshkumart** [LuatixHQ/opencti#4132]
## Description

An UI issue is occurring in Arsenal -> Malware Cards after selecting multiple favourite entities and scrolling.

## Environment

1. OS (where OpenCTI server runs): Windows 10
2. OpenCTI version: OpenCTI 5.9.6
3. OpenCTI client: frontend

## Reproducible Steps

1. Go to Arsenal -> Malware.
2. Set 8 Malware as favourite entities.
3. Scroll and look at empty area.

## Expected Output

There shouldn't be any empty area.

## Actual Output

There is empty area in Malware cards UI.

## Screenshots (optional)

https://github.com/OpenCTI-Platform/opencti/assets/10473402/9c796f5e-c40b-41e6-b733-8faf4ad4454e

**Comment by RomuDeuxfois** [comment]
Seems to be a problem in the https://github.com/bvaughn/react-virtualized library.
