### ISSUE TITLE
Problem with Media content creation

### ISSUE THREAD

**Issue by OCTItest** [LuatixHQ/opencti#4136]
## Description

While creating a new media content, OpenCTI replace the new one by an old one that allready exist in the platform and add the selected label to the former media content.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.9.6
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. In Report, Knowledge, Graph View
2. Create an observable
3. Select Media Content
4. Add the Name "X" in : description, content, ,title
5. add Media category : hashtag
6. add URL : "no url"
7. add label "Y"
8. Click on Create

## Expected Output

A media content with the name X

## Actual Output

An old media content name "W" that allready exist and  was created for another report appears
The platform added the label selected to this media content

**Comment by Archidoit** [comment]
If you create a media content with an url that already exists, it is the same media content as the existing one, and the created observable is 'merged' with the existing one : its label is added in the labels of the old media content, etc. It's a normal behavior.

**Comment by OCTItest** [comment]
Thank you for the answer
