### ISSUE TITLE
Malware global kill chain doesn't display correct info

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4155]
## Description

Malware global kill chain lines always display the entity in the 'to' of the relationship.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

- Go to the Knowledge tab of a malware
- Add a relationship with several threat actor group/individual
- At the bottom of the Knowledge tab, go on 'Global kill chain'
- The relationship appears but we have no info on which entity is linked to the malware. If we want to edit a relation there, we don't know which relation we edit, etc.

Explanation: The entity displayed in the line is always the 'to' of the relationship

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3b3b8953-2f7c-4656-b8ec-5a2307f34d19)

**Comment by Archidoit** [comment]
2 solutions: 
- display the 'from' of the relationship when the 'to' is the entity itself
- don't display relationships when the 'to' it the entity itself

**Comment by SamuelHassine** [comment]
@Archidoit please use the first solution.
