### ISSUE TITLE
Can't create some relationships from Narrative Knowledge

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4157]
## Description

Can't create relationships from Narrative Knowledge to some entities because no relationship type available in the creation form:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/02368559-50f8-4888-89df-5c2cdfddcd5a)

## Reproducible Steps
- Go to the Knowledge tab of a Narrative
- Go to Vulnerability (right menu)
- Create a relationship with a Vulnerability
- relationship_type is empty, we can't create a relationship

It is the case for relationship with : Vulnerability, Attack Pattern, Malware.

**Comment by RomuDeuxfois** [comment]
Today, there are no possible relationships between narrative and : Vulnerability, Attack Pattern, Malware
Should we remove this entries from the knowledge bar ?

**Comment by Archidoit** [comment]
I think there are 2 possibilities: 
- remove these entries from the knowledge bar
- add a "uses" relationship between those entities and Narrative

**Comment by richard-julien** [comment]
Choice: remove these entries from the knowledge bar
