### ISSUE TITLE
Error when navigating from a note to a related incident

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#4176]
## Description

When we try to navigate from a note to a related incident, we receive an error:

When we click the incident in related entities-->

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/5d9f6abd-956b-47d0-af45-7a5574f76071)

The error appears in the front-end -->

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/57407709-7194-49fe-bb32-6734a45410b7)

And the following error appears in the logs:

`{"category":"APP","error":{"stacktrace":["GraphQLError: Cannot query field \"outcomes\" on type \"Trigger\".","at Object.Field (/opt/opencti/build/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)","at Object.enter (/opt/opencti/build/node_modules/graphql/language/visitor.js:301:32)","at Object.enter (/opt/opencti/build/node_modules/graphql/utilities/TypeInfo.js:391:27)","at visit (/opt/opencti/build/node_modules/graphql/language/visitor.js:197:21)","at validate (/opt/opencti/build/node_modules/graphql/validation/validate.js:91:18)","at validate (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:474:12)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:265:30)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:436:24)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"Unspecified","operation_query":"query StixCoreObjectQuickSubscriptionContentPaginationQuery($filters:[TriggersFiltering!]$first:Int){triggersKnowledge(filters:$filters first:$first){edges{node{id name trigger_type event_types description filters created modified outcomes resolved_instance_filters{id valid value}__typename}cursor}pageInfo{endCursor hasNextPage}}}","size":168,"time":2,"timestamp":"2023-08-27T10:56:41.515Z","type":"READ_ERROR","user":{"group_ids":["8814cec5-320b-4904-93a2-5c4349fc88d0","a6188da8-a3ec-4327-90d4-037bff10d496"],"ip":"::ffff:eee.ccc.yyyy.30","organization_ids":[],"referer":"https://cti.etic.security/dashboard/events/incidents/c8347b35-4967-482d-9177-7bca88a18fc2","socket":"query","user_id":"xxxx-xxxxx-xxxx-xxxx-xxxxxxxx"},"variables":{"filters":[{"key":["filters"],"operator":"match","values":["c8347b35-4967-482d-9177-7bca88a18fc2"]},{"key":["instance_trigger"],"operator":"match","values":["true"]}]},"version":"5.10.0"}`

## Environment

Ubuntu baremetal installation
We just updated to 5.10.0
The problem does not appear in 5.9.6

## Additional information

The problem does NOT appear in 5.10.0 if we right click to open in another window.

**Comment by SamuelHassine** [comment]
Hello @AlexSanchezN,

I think you just have to reload the page.... :)

Can you please test and tell me?

Kind regards,
Samuel

**Comment by AlexSanchezN** [comment]
The problem seems to also appear when we click in the 'eye' from the Data --> Entities tab on any Incident in our platform

**Comment by SamuelHassine** [comment]
Your web browser JS is outdated, just full reload or try to clear cache.

**Comment by AlexSanchezN** [comment]
Correct, had to CTRL+ F5 and everything started working...
The curious thing is that it happens on different computers only on 5.10

Thanks for the speedy response, and sorry to annoy you on a Sunday :-(
