### ISSUE TITLE
Unable to modify notifiers in Settings => Customizations => Notifiers

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4179]
## Description

Go to the section, try to change the name of a notifier, click on save. Nothing happen.

**Comment by Archidoit** [comment]
I am able to modify and create notifiers in local, but not in test env.

**Comment by Archidoit** [comment]
When clicking on the 'update' button in a notifier line : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/2c7cab8b-57d7-4de2-aef7-a3bdf06421da)

**Comment by Archidoit** [comment]
Other bug to be resolved in the same issue: can't create a notifier (nothing happens).

**Comment by Archidoit** [comment]
Error at notifer edition: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/ce46ad5a-7cd7-4cc5-942a-8d99fe702b98)

**Comment by Archidoit** [comment]
To reproduce the bug in local:
- yarn build (in the front)
- yarn build (back)
- yarn serv (back)   
- go to port 4000 to see the built version
