### ISSUE TITLE
Error in Observable > Data

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4200]
## Description

Error in Observable > Data

## Reproducible Steps
- Go to an observable
- Go to the Data tab
- An error occurs

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/14195a87-d291-4535-89c6-7f3df2480432)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/db58d2cc-609a-4383-b503-745b597b395b)

**Comment by SouadHadjiat** [comment]
The error in local is : 
```
Relay: Expected to receive an object where `...PictureManagementViewer_entity` was spread, but the fragment reference was not found`
```

**Comment by RomuDeuxfois** [comment]
We need to disabled the picture management for the entities no target by this issue : https://github.com/OpenCTI-Platform/opencti/issues/2540
