### ISSUE TITLE
Add a "Indicators propagation in reports" rule in the rule engine

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4201]
## Use case

Rule : IF "Report A" contains "Observable B" AND "Indicator C" based-on "Observable B" THEN create "Report A" contains "Indicator C" AND create "Report A" contains "relation D (based-on)"

Deactivated by default.

Facilitate the response to question #4140

**Comment by RaulSokolova** [comment]
Hi @Jipegien ,

I just tried this in the demo instance, and did not work, and the rule engine is already enabled. 

Thanks,
Raul Sokolova

**Comment by Jipegien** [comment]
It is not implemented yet @RaulSokolova. We have not provisioned it in the next 2 releases but as "short-term candidates". Thus it should be done for 2023.

**Comment by RaulSokolova** [comment]
Thanks for the update @Jipegien 

Looking forward to see the same capability across all most of the used entities to track indicators relationship for example, threat-actor or groups, and malware.

For example if I uploaded indicators manually for a malware or threat group the observables will create the relationship with those entities, but not the indicators, creating a gap or extra manual steps for analysist.
