### ISSUE TITLE
ContainerHeaderObjectsQuery error when attempting to view a Report, after Objects with relationships in the Report are removed

### ISSUE THREAD

**Issue by jklepsercyber** [LuatixHQ/opencti#4204]
## Description

After removing an Object (Attack Pattern, in our case) from a Report, if that Object had relationships to other Objects in that report as well, then OpenCTI will generate an error when trying to view the Report again. Checking the logs after this happened revealed a "API Call - ContainerHeaderObjectsQuery" error returned from the API, while the StackTrace stated "Error returning null from non-nullable field StixCoreRelationship.to". Attached below is a screenshot showing line numbers included in the StackTrace. 

## Environment

1. OS (where OpenCTI server runs): Windows 10
2. OpenCTI version: OpenCTI 5.6.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add object(s) to the Report
2. Create relationships in the Report between two Objects (in our case, an Attack Pattern and multiple other objects in the report)
3. Remove the Attack Pattern from the Report
4. Close Report, and attempt to view again

## Expected Output

View the Report with no problems.

## Actual Output

OpenCTI states that "an error has occurred" when attempting to click on the report and view.

## Additional information

![image](https://github.com/OpenCTI-Platform/opencti/assets/94950521/b091641e-e275-4ad6-a288-2edfec20b77b)

**Comment by Archidoit** [comment]
I can't reproduce your error... Can you give me more details?

**Comment by SamuelHassine** [comment]
I think this has been already solved in 5.9 / 5.10, can you please confirm your version number?

**Comment by nino-filigran** [comment]
Given that we have just released the 6.0 and that we're unable to reproduce this issue (since it should have been fixed), I'm closing this issue for now. Feel free to re-open it if the problem persists.
