### ISSUE TITLE
Latest 5.10.1 tar.gz installation files have not been properly generated

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#4216]
## Description

Latest 5.10.1 tar.gz installation files have not been properly generated. They are 196byte long only.
Very interested in https://github.com/OpenCTI-Platform/opencti/issues/4156
Would like to install :-)

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/4320dfb1-a953-45ec-b098-f75ef5a70a11)

## Environment

Does not apply

## Reproducible Steps

go to: 
https://github.com/OpenCTI-Platform/opencti/releases/tag/5.10.1

**Comment by SamuelHassine** [comment]
Fixed.
