### ISSUE TITLE
In TA, inferred relationships located-at should not have a button "unlink / delete"

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4220]
## Bug

In Threat Actor (all) => Overview:

Quick located-at is displaying the button "unlink" on inferred relationships (no effect).

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/93b82c24-279c-410b-8f7e-c4cf9627b14c)

**Comment by SamuelHassine** [comment]
Hello @SarahBocognano,

Same in sectors / subsectors. Repro case:

1. Enable part-of propagation rule
2. Create a sector A with sub-sectors
3. Create a sector B and put sector A as a subsector
4. Go to sector B. You will see all the sub-sectors of sector A (inferred), and you can try to unlink them.

**Comment by Jipegien** [comment]
What is the situation here @SarahBocognano ?

**Comment by SarahBocognano** [comment]
Brainstorm tomorrow with Julien, we're back on it !

**Comment by SamuelHassine** [comment]
@SarahBocognano @Kedae we need to close this one.
