### ISSUE TITLE
best way to add bulk of IOCs to OpenCTI

### ISSUE THREAD

**Issue by ASQ505** [LuatixHQ/opencti#4223]
## Description

Dears, I am using OTX to add bulks of IOCs to OpenCTI, but this way is getting worse because of OTX crashing.

Do any one have a better way?

**Comment by nino-filigran** [comment]
@ASQ505 did you manage to get some support from anybody?

**Comment by nino-filigran** [comment]
@ASQ505 I'll close this issue given I did not have response to my comment. Feel free to re-open it if needs be or to even reach out on slack if you need.
