### ISSUE TITLE
Merging a report into another report lead to have the same report in object_refs

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4226]
## Description

1. Create 2 reports
2. Merge the first one in the other one

Result: 

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/00844f58-adf4-4297-b2d9-38d60ace1a61)

In entities and the knowledge graph, the report seems to be in the object_refs of itself.

This behavior should be discussed with @richard-julien because I thought we have a low level prevention on relationship between the same source and target (and this ref is obviously not respecting this rule).

**Comment by SamuelHassine** [comment]
Also, when trying to remove this ref, it removes everything in the report....

**Comment by yassine-ouaamou** [comment]
I could not reproduce. In my case, the entites were properly merged but not the relations (Knowledge)
Report A
![report_3](https://github.com/OpenCTI-Platform/opencti/assets/7083405/71b5e056-cd7c-4e0e-9bc4-d4de4bcfe28b)
Report B
![report_4](https://github.com/OpenCTI-Platform/opencti/assets/7083405/e2698841-b43b-435e-9ffd-24e4e9e50eba)
Resulting report
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/7d01fa48-17e9-44d8-add8-e3c56259944b)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/153c6e09-515c-4109-a43c-9a4fa9fdb32f)

**Comment by SamuelHassine** [comment]
@yassine-ouaamou can you please try with reports with the same name (and different publication date)?

**Comment by SamuelHassine** [comment]
Ok Yass, I will give you a repro case.

**Comment by SamuelHassine** [comment]
No reproducing anymore.... Will talk with Julien tonight.

**Comment by richard-julien** [comment]
For your problem @SamuelHassine i think its another report already referenced but not directly part of the merge.

For the @yassine-ouaamou problem its more a feature request to also be able to merge the x_opencti_graph attributes of multiple containers.

**Comment by richard-julien** [comment]
After talk with @SamuelHassine , we have a repro case.
1. Create report A
2. Create Report B with object_refs A
3. Merge B into A
