### ISSUE TITLE
Malware Analysis is unknown in an investigation graph

### ISSUE THREAD

**Issue by SarahBocognano** [LuatixHQ/opencti#4236]
## Description

Malware Analysis entity is not recognize in an investigation graph

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to an investigation graph
2. Add a malware analysis
3. The name/value is unknown

## Screenshots (optional)
![Capture d'écran 2023-09-06 094710](https://github.com/OpenCTI-Platform/opencti/assets/98532359/846c04fe-9b63-4377-81af-8b295d10eaa5)

**Comment by SamuelHassine** [comment]
@SarahBocognano can you also please fix Kill-Chain-Phase which is also unknown?

**Comment by SamuelHassine** [comment]
This is available on indicators for instance.
