### ISSUE TITLE
Invalid TAXII 2.1 Accept Header in OpenCTI GET Request

### ISSUE THREAD

**Issue by zhanttt** [LuatixHQ/opencti#4246]
## Description

The OpenCTI GET request to a TAXII server contains the following Accept headers: `application/json, text/plain, */*`.
However in the TAXII 2.1 spec (https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107505), the Accept header needs to be `application/taxii+json;version=2.1`.
This causes problems polling TAXII 2.1 servers (for example medallion).

I set up a test medallion TAXII server (https://github.com/oasis-open/cti-taxii-server) in my environment and want my OpenCTI instance to ingest the STIX objects from the TAXII server. After configuring a TAXII Feed and starting it, I do not see any new STIX objects in OpenCTI. I do not see any TAXII-specific errors in the OpenCTI error log. On the Medallion side, the request is seen, but returns HTTP status code 406. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 5.10.1
3. OpenCTI client: frontend
4. Other environment details: OpenCTI docker installation

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up medallion server with a few STIX objects
2. Create TAXII Feed in OpenCTI
![image](https://github.com/OpenCTI-Platform/opencti/assets/71095260/243ca036-e169-4117-8dc1-c08272734b37)
3. Expect STIX objects to be imported, but get HTTP code 406 response

## Additional information

The TAXII server is reachable from my OpenCTI machine. The following curl command polls STIX data from the server:
![image](https://github.com/OpenCTI-Platform/opencti/assets/71095260/c788e50e-a565-463b-afb8-2bb1f59f59e1)

Medallion 406 code from an OpenCTI request: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/71095260/23be0068-0cf2-4c84-ade6-312ca0694821)

**Comment by zhanttt** [comment]
I discovered that the Accept header sent by OpenCTI is not valid for medallion. The Accept header sent by OpenCTI is `application/json, text/plain, */*`. Medallion also needs "application/taxii+json;version=2.1". If this is not included, medallion returns HTTP code 406. I reproduced the 406 code when I did not include "application/taxii+json;version=2.1" in my curl command.

The OpenCTI platform should add "application/taxii+json;version=2.1" to the Accept HTTP header to communicate with medallion.

Medallion response to my curl command without "application/taxii+json;version=2.1": 
![image](https://github.com/OpenCTI-Platform/opencti/assets/71095260/28dc9192-ea4f-4e19-847e-b958804f98f2)

**Comment by RyanOchieng** [comment]
I believe by the TAXII 2.1 standard, the Accept header must be `application/taxii+json;version=2.1` anyway, I had also discovered this in my own private testing with Medallion as the TAXII server

https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107505

**Comment by zhanttt** [comment]
@RyanOchieng thanks for your input, I edited the issue. I would also add the Bug label, but I don't seem to have permission to do so.

**Comment by SamuelHassine** [comment]
Hello,

This issue has been fixed in 5.10.3.

Kind regards,
Samuel
