### ISSUE TITLE
Promote observable to indicators in bulk in observables list and container / observables is not displayed

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4251]
## Description

Promote observable to indicators in bulk in observables list and container / observables is not displayed.

1. Create a report
2. Go to report / observables
3. Add a few observables
4. Check boxes or select all

Toolbar should propose: 

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/b5bc5eb1-f4e4-4811-8bef-802d88d6d659)

But the button is not here.

Same in the global screen Observations / Observables.

**Comment by Archidoit** [comment]
I can't reproduce, I have this button...

**Comment by SamuelHassine** [comment]
Ok @Archidoit. It is when you have a quick filter on the right, for instance only scoping on Ipv4, the button disappears.
