### ISSUE TITLE
Export in Data / Relationships is broken

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4253]
## Use case

2 cases here:

1. Go in Data / Relationships
2. Use filters (and no checkboxes), try to export

=> Error in the backend

1. Go in Data / Relationships
2. Use checkboxes

=> No error, but export is empty.

**Comment by SouadHadjiat** [comment]
Issue created in connectors : https://github.com/OpenCTI-Platform/connectors/issues/1387
