### ISSUE TITLE
Export full in list of report is broken

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4259]
## Description

1. Go to Analysis / Reports
2. Select the 2 first reports with checkboxes
3. Select application/json + Full export

Results bundle fully empty:

{
    "type": "bundle",
    "id": "bundle--54a72696-62ea-4f49-a44d-5e6fcc89bb6b",
    "objects": []
}

**Comment by RomuDeuxfois** [comment]
I have the feeling that this kind of bug comes back: export list

It would be good to add tests

**Comment by SouadHadjiat** [comment]
Even simple export in list is broken, this needs to be fixed both in connector and python client

**Comment by SouadHadjiat** [comment]
Issue created in connectors : https://github.com/OpenCTI-Platform/connectors/issues/1387
