### ISSUE TITLE
Add Confidence level on Users

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4304]
## Use case

Users have a Max Confidence level that will be used when creating Knowledge. 
As connectors, stream and feeds used a user to upsert data, confidence level in their config is no longer needed. They will use the max confidence level of the users they are associated with.

In User's edition form, a dedicated panel allows to set the max confidence level

### No migration

We do not know what is the value used in the connectors configuration files of our users, and we cannot know which user is used for a connector, thus we cannot magically migrate the existing users with a smart max confidence value.
For instance, migrating users to 100 would be a very dangerous move as connectors would suddenly be able to overwrite all data in the platform. 

For this reason, no migration will be executed. Platform admins are expected to configure their confidence policy throughout their platform.

### Subtasks:
* Managing a “max confidence level” for a user
* Enforce specific rights to manage confidence levels of users (capability SETACCESS)
* [Product] Anticipate the breaking change using Filigran's communication tools

### Linked to issues
* #4901 
* #5692 
* #5694
* #5695
* #5697
* #5696

### Next steps
* Using max confidence level of the associated user when upserting data
* Taking into account the max confidence level of users when they try to modify the confidence level of an Object

### Further comments
Note this feature will then be leveraged for #2517 in the future.

**Comment by SamuelHassine** [comment]
Also implement the option "validate_before_import".
