### ISSUE TITLE
Country flag icon not showing when observable with relation located at country is created.

### ISSUE THREAD

**Issue by RegturH** [LuatixHQ/opencti#4312]
## Description

Observable of type Ipv4 has not the country flag icon when the located at relation is present.

## Environment

1. OS (where OpenCTI server runs): k8s - not sure which os
2. OpenCTI version: 5.7.6
3. OpenCTI client: front-end
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an observable using python script:
```cticlient = pycti.OpenCTIApiClient(api_url, api_token)

value="1.1.1.2"
country = cticlient.location.create(
                            name="Belgium",
                            type ="Country"
                            )

marking = cticlient.marking_definition.create(
                            definition_type="TLP",
                            definition="TLP:AMBER+FINANCE",
                            x_opencti_order=4,
                            x_opencti_color="#5a551a",
                                )
author = cticlient.identity.create(
            type="Organization",
            name="name",
            description="description",
    
        )
label =cticlient.label.create(value="label")


observable = cticlient.stix_cyber_observable.create(
        objectLabel=label["id"],
        objectMarking =marking["id"],
        createdBy = author["standard_id"],
        update =True, 
        observableData={
                "type": "ipv4-addr",
                "x_opencti_description": "description",
                "value":value,
                "x_opencti_score": 90,
                "x_opencti_create_indicator":True,
            }
    )
cticlient.stix_cyber_observable.add_marking_definition(id=observable["id"], marking_definition_id=marking["id"])
cticlient.stix_core_relationship.create(
                toId=country["id"],
                fromId=observable["id"],
                confidence=90,
                relationship_type="located-at",
                description="Relation between the Ip and Location",
            )
```

## Expected Output

Creation of an observable with the relation : located at country Belgium and the country flag is visible on the observable.

## Actual Output

observable is created and the relation is created as well but the flag is not visible.

## Screenshots (optional)
<img width="918" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/111435050/8ccf2976-318b-4306-a6e3-56fd6c4f7845">
<img width="826" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/111435050/b0517dd9-d2fd-40d0-ba71-a11c8c5996be">

**Comment by RegturH** [comment]
Here is an overview of the created relation: 
<img width="815" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/111435050/9cbc8895-c2d6-4c9e-95c6-0ea8a113d54c">

**Comment by SarahBocognano** [comment]
Did you add the aliases for the country ? Like BEL and BE for Belgium. 
To have the flag display, you must put this country code aliases in your country. You can find the aliases for each country in the geography.json file

**Comment by RegturH** [comment]
Hey Sarah, I found my solution. thank you for the help. I did not have the import base connector active. This solved my issue
