### ISSUE TITLE
Only 25 items available in report--> observables and report --> entities

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#4328]
## Description

As you can see in the first image, there are thousands of observables and entities in the report.

![thousands](https://github.com/OpenCTI-Platform/opencti/assets/6607235/0cc3f1ab-e8a0-45af-b26f-03b351c2548d)

But only 25 are shown in report --> Observables and report --> entities

![25](https://github.com/OpenCTI-Platform/opencti/assets/6607235/68c0ef68-d54c-4722-85ab-063c57d48a2a)

![252](https://github.com/OpenCTI-Platform/opencti/assets/6607235/617a6075-b0ac-42a4-88f6-11aa801699bd)

## Environment

3 node cluster on Ubuntu bare metal installation
OpenCTI version 5.10.2

## Reproducible Steps

Go to any report with more than 25 observables/entities and move to the corresponding tab
We have tested with reports generated by us, and from other sources (AlienVault for instance)

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/111e2cd7-0386-440e-bba9-4ff05fa0e211)

## Expected Output

To be able to see all entities/observables

## Actual Output

Only 25 are shown

**Comment by Archidoit** [comment]
Indeed, the number of elements to display there is limited to 25. Do we want to increase this number @Jipegien ?

**Comment by Jipegien** [comment]
All content should be displayed
