### ISSUE TITLE
Quick button to add Assignees and Participants

### ISSUE THREAD

**Issue by SYNchroACK** [LuatixHQ/opencti#4333]
## Use case

Add a quick button near to Assignees list to add quickly assignees. (the same can be applied to Participants)

![image](https://github.com/OpenCTI-Platform/opencti/assets/4184292/d4f8f967-3cc3-4056-852d-2d056c3ff350)

**Comment by nino-filigran** [comment]
@SYNchroACK we understand your use case. However, our roadmap is currently quite packed and we will not work on this anytime soon. Additionnaly, we will tackle this issue in a wider approach UI refactoring approach
