### ISSUE TITLE
Home custom dashboard is not resizing correctly when opening / closing the left menu

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4334]
## Description

Home custom dashboard is not resizing correctly when opening / closing the left menu.

https://github.com/OpenCTI-Platform/opencti/assets/1334279/ab704a85-c11b-4935-8873-0bdb11ffe3e9

**Comment by tomibennett** [comment]
Tested and working on Chromium 116.0 & firefox 117.0.1 with (local -fbb5228df- and demo builds).

on which browser (& version) do you see this behavior?

**Comment by SamuelHassine** [comment]
@tommychat : On https://demo.octi.filigran.io/dashboard. Master branch / Latest chrome version.

Be aware of the fact that you need to have the menu open, then full reload, then close the menu.

**Comment by SamuelHassine** [comment]
Version 117.0.5938.89 (Build officiel) (64 bits)

**Comment by tomibennett** [comment]
I tested it on chrome (same build) but could not reproduce it either. Even with a full reload.
[Peek 2023-09-21 09-51.webm](https://github.com/OpenCTI-Platform/opencti/assets/3235855/0dfb42f7-f506-44a5-b21b-558ce6bab7ff)

**Comment by SamuelHassine** [comment]
Confirmed that I'm not reproducing anymore :)
