### ISSUE TITLE
Problem with sending data to Splunk.

### ISSUE THREAD

**Issue by Security-Team12** [LuatixHQ/opencti#4347]
## Description

I want to transfer the data collected in the openCTI system to the Splunk KV Store via a Splunk connector. I have configured the settings for the connector like other connectors, and the connector seems to be working fine without any errors. However, the KV Store in Splunk is not getting populated with the sent information. I would appreciate it if you could guide me on this issue or provide any instructions if available.
@richard-julien 
@SamuelHassine 

Is there a need for further action to be taken on Splunk? I have only created a KV Store and provided Splunk and KV Store information to the connector, and I did not receive any errors on the connector.
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 5.7.4
3. OpenCTI client: Docker

**Comment by nino-filigran** [comment]
@Security-Team12 did you manage to get support for your question?

**Comment by nino-filigran** [comment]
@Security-Team12 given I did not receive answer to the question I'll close the ticket for now. Feel free to re-open it if needs be.
