### ISSUE TITLE
Add Rolling time base attribute time selection (created_at, updated_at)

### ISSUE THREAD

**Issue by RegturH** [LuatixHQ/opencti#4349]
## Description

When creating an data sharing CSV feed you give an Rolling time(in minutes). This should give all entities with a modified time within this timeframe.

example of how it should be: 

- entity of IP address has been created at 1pm.  
- rolling time is 60 minutes
- till 2pm the entity should be in the list. After this time it will be removed (this happens)
- If we update the entity or it is added again at 3pm it should be readded to the feed. The modified time has been changed and is in the timeframe of 60 minutes. (this does not happen)

## Environment

1. 
2. OpenCTI version: 5.10.1
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an entity : creation time is 1pm
2. Create a CSV shared feed with a rolling time of 5 minutes (so at 1:05pm the entity should be gone)
3. after 1:05 PM reingest or update the entity so the modified time is changed.
4. Check if the entity is back in the feed 

## Expected Output

Entity is being added to the feed

## Actual Output

it remains empty the feed

**Comment by RegturH** [comment]
@SamuelHassine Does this work as intended?

**Comment by richard-julien** [comment]
For now the csv feeds is explicitly based on entity creation time. 
I think we imagine the feature at first to expose observables, elements that doesnt really change over time. 
Can you specify a bit your use case @RegturH ? type of element you want to share and the remote system targeted for consumption?

**Comment by RegturH** [comment]
Hey Julien, We use this to create a Blocklist. We create a CSV feed that we feed to the firewall. Everytime we see an IP doing malicious behaviour we create an observable/indicator. This IP will then be added to the csv feed. This will then be picked up to create a firewall rule. The element we share is an observable with a value/TLP/location/label. example of the element: 
<img width="896" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/111435050/373cd64e-c319-43a6-8f86-42872f130165">

We use an Ansible script to generate a firewall rule.

This works but if there is an indicator that is created outside the rolling time and we see it again. This will not be blocked again. We can increase the rolling time but then the content will be less accurate.

**Comment by richard-julien** [comment]
After discussion with @SamuelHassine , we think about simply add the option to pickup the date attribute you want to use.
Work in progress

**Comment by RegturH** [comment]
Thank you Guys!
