### ISSUE TITLE
Add `modified` and `updated_at` fields for `ReportsFilter`

### ISSUE THREAD

**Issue by axelfahy** [LuatixHQ/opencti#4393]
## Use case

I would like to retrieve reports based on the `modified` and `updated_at` fields, but it is not in the available filters of the report type. 

## Current Workaround

Query all reports, and filter manually on the `modified` and `updated_at` field, which is really not optimal.

## Proposed Solution

Add the `modified` field in the `ReportsFilter` enumeration. 

## Additional Information

It is already possible to filter on the `modified` or `updated_at` field for some entities, but not for reports. My guess is that the field could just be added [here](https://github.com/OpenCTI-Platform/opencti/blob/58a7f8a19d4e754fa063ea978a13bf4ee0129326/opencti-platform/opencti-graphql/config/schema/opencti.graphql#L3528-L3547), but maybe I am missing some information. 

## If the feature request is approved, would you be willing to submit a PR?

Yes if needed

**Comment by SYNchroACK** [comment]
related to #3580

**Comment by Jipegien** [comment]
to take into account on the ongoing refactor of filters @Archidoit

**Comment by Archidoit** [comment]
@Jipegien to be done in a separate branch.
Add a filter for the modified date
To check: for the creation date filter, sometimes created_at is used, sometimes it's created...

**Comment by richard-julien** [comment]
Fields added in filter for API. User interface improvement will be part of a more global refactor.

**Comment by vinisimoes** [comment]
@richard-julien Could you provide some minimal example on how to use this field more exactly, please? 

Does it work only for a specific date, or are we able to retrieve reports that were modified from a given date, or for a specific interval?
