### ISSUE TITLE
Error creating report

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4402]
## Description
When I try to create a report on the platform, an error occurs while entering any value::

Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.6 
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to dashboard/analyses/reports
2. Click on Plus (Create a report)
3. Enter any value

## Expected Output

New report

## Actual Output

Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/be81fa3a-4605-4e43-a797-977d1cc3510c)

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/6dad4be6-2369-490b-a991-d3a55fed7124)

**Comment by Archidoit** [comment]
I can't reproduce your error. Can you give more details or provide the logs?

**Comment by rattat0r** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/ed205a5d-0e1e-45d9-a939-70d74a3c64de)

**Comment by rattat0r** [comment]
I solved the problem. I used a modified image of opencti platform 5.10.1 for my purposes, returning to the original image solved the problem.
