### ISSUE TITLE
When adding the targets filter on malware list got an error

### ISSUE THREAD

**Issue by Kedae** [LuatixHQ/opencti#4410]
https://testing.octi.staging.filigran.io/dashboard/arsenal/malwares?filters=%7B%22targets%22%3A%5B%7B%22id%22%3A%22ff47ff45-217d-4d03-8cab-752040dc33cd%22%2C%22value%22%3A%22ev2%22%7D%5D%7D&sortBy=modified&orderAsc=false

**Comment by Archidoit** [comment]
'targets' filter not working at all for Malwares and Incidents
