### ISSUE TITLE
Threat Actors and Intrusion Set goals as Taxonomy

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4420]
## Use case
As an intelligence analyst I would like to search for threat actors and intrusion sets by their goals.

## Current Workaround
Strict naming convention. But is still limited to human mistakes.

## Proposed Solution
To have a guaranteed consistency of the goals they should be configurable in taxonomy.

**Comment by Jipegien** [comment]
The "goals" field is to be considered as a free text addition to the primary and secondary motivations open_vocabularies. I recommend you to modify the motivation taxonomies to cover your need.
We also may cover your need with a more general feature of adding custom attributes to entities.

**Comment by ghost** [comment]
Adding custom attributes would be a great solution. 👍

Mit freundlichen Grüßen / Kind regards
________________________________
