### ISSUE TITLE
Correlation View not Identifying all correlations

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#4431]
## Description

The correlation view (within the context of Report A), is supposed to show all the objects in Report A that are located in other Reports, and those Reports.

We have identified instances where observables (in this specific case, a File) aren't being displayed properly

This is difficult to identify / reproduce in the Demo instance, or any instance - we only notice this when we're specifically looking for it.  We will try give as much relevant information as we can about the specific issue (hiding sensitive information)

It's possible this has to do with the hardcoded limits referenced here #2351 but it's not clear how to validate this

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 5.6.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

While we are running v 5.6.2, we haven't observed completed issues between that version and the latest (5.10.2) that seems like it would have addressed this issue

Report A  contains 17 objects (13 entities, 4 observables)
One of the observables is a file, with hashes filled in ("The File")
Opening Correlation view for Report A shows lots of overlaps with other Reports, but not The File or Report B

Opening the page for The File shows that there are two Reports that contain The File: Report A, Report B

Report B contains 27 objects (12 entities, 15 observables), including The File
Correlation View for Report B also doesn't reference The File or Report A

## Expected Output

The File in the correlation view for both Reports A and B

## Actual Output

The File is not is not in Report A or B's Correlation views

## Additional information

It's worth noting some other odd behavior we've observed in Correlation View:
- When viewing Correlation View for Report X, sometimes the object for Report X itself is found in the Correlation View, but sometimes it is not.

**Comment by securitiz** [comment]
Perhaps a way to help with this would be to (perhaps in Settings? or directly in Correlation View?) allow the user to decide what types of objects they're interested in overlaps for.

E.g. I'm not interested in Country, Region, Sector overlaps etc. These objects tend to be particularly noisy as well.  So there should be a way to hardcode the types of objects to not extend on, so that overlaps by these entities don't count against the hardcoded limits

**Comment by tomibennett** [comment]
There is a filtering system yes! A quite heavy one actually that takes predicate on many aspect of the data and whose objective is to prevent noise as you mentioned. I don't know (yet) if the user can interact with it through the UI, though I bet for it.

In fact, that's precisely this filtering system that is faulty here. It's too restrictive and discards too much SDOs & SCOs. Investigation is ongoing.
