### ISSUE TITLE
Changing OpenSearch xms and xmx values leads to Platform error "initialization failed"

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4446]
## Description
When changing (increase) the xms and xmx values it leads to the error message initialization failed in the platform container.
Only undoing the change gets the instance up again.

## Environment

1. OS: Debian
2. OpenCTI version: 5.10.2
3. OpenCTI client: NA
4. Other environment details: K8s deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Deploy the platform, redis, rabbitmq and opensearch with xms and xmx values set to any value
2. Set the replicas of the platform to 0
3. Change the xms and xmx values to a higher value
4. Wait until opensearch is up again and set the replicas for the platform to 1
5. Platform doesn't start anymore with the error message initialization failed

## Expected Output
Platform comes up again normal

## Actual Output
Platform doesn't come up anymore with the error message initialization failed

**Comment by richard-julien** [comment]
Can you please share you error logs? Thanks.

**Comment by ghost** [comment]
I tried it again and saw in the logs of opensearch that there was a migration ongoing that had not finished. After it has finished the opencti instance came up normally.
