### ISSUE TITLE
Migrate redirection buttons to a "settings" button with popup

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4448]
## Problem to Solve

![image](https://github.com/OpenCTI-Platform/client-python/assets/1334279/fc7723ff-02d4-4fa2-96b5-5819de1f0c10)

Those button should not be on the top right as they are not "doing" anything. We should just have a "cog" icon on top right with a tooltip: "Settings of the list view", opening a dialog with the redirect option in a select field.

**Comment by nino-filigran** [comment]
@SamuelHassine could you please be more explicit?

1. Do you confirm that the screenshot is taken from the **analysis** screen?
2. The cog is qlreqdy existing with your request (see my screenshot), thereofre, what is the exact purpose of this feature request?

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/a9928a53-3b0e-4cf0-ab87-9b376f418620)


![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/cec6d26d-66af-4a1e-b7ea-7f4d616d3b16)

**Comment by SamuelHassine** [comment]
I've implemented this a few weeks ago....

**Comment by nino-filigran** [comment]
Ah ok, this makes more sense! Thanks 👍 
cc @Jipegien
