### ISSUE TITLE
Unable to filter severity and create a trigger from Vulnerabilities data.

### ISSUE THREAD

**Issue by Huiicat** [LuatixHQ/opencti#4449]
## Description

I would like to create a trigger from Vulnerabilities and would like to filter on severity and search if contains "gitlab" in description.
However, I can't add filter on severity, it shows no available options.

## Environment

1. OS (where OpenCTI server runs): Ubuntu22
2. OpenCTI version: 5.10.3
3. OpenCTI client: docker
4. Other environment details: portainer 2.11.1, opencti/connector-cve:5.10.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. goto triggers and digests pages. (/dashboard/profile/triggers?sortBy=name&orderAsc=false)
2. create a live trigger and select filters.
3. select from severity but showing no available options.

## Screenshots (optional)
<img width="515" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/32323466/3eea8a53-18d5-4041-a202-0e16c10b534f">

<img width="748" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/32323466/862c9678-6ca2-4461-a838-c4fbfd44e29a">

**Comment by marieflorescontact** [comment]
after investigation, there's no bug on the filter: it's missing. the `severity` property of a `Vulnerability` is `CVSS3-Severity`. The severity filter you see applies to cases.
As we're going to refactor this filters part very soon, we won't be adding the filter for now.
