### ISSUE TITLE
Report names are not displaying in the list widget in custom dashboards

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4450]
Within the custom dashboards, the report names are not displaying in the list widget.
![OpenCTI 5 10 2 Bug Report names are not displaying in the list widget in custom dashboards](https://github.com/OpenCTI-Platform/opencti/assets/70956706/0726976b-b1de-4589-9102-2d27e0640c15)

**Comment by SamuelHassine** [comment]
Taking care of this.
