### ISSUE TITLE
How to delete a connector 

### ISSUE THREAD

**Issue by kodebrain** [LuatixHQ/opencti#4457]
## Prerequisites

- [x ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x ] I went through old GitHub issues and couldn't find anything relevant
- [x ] I googled the issue and didn't find anything relevant

## Description
What's the proper procedure to delete or clear all data that the connector has previously imported?
After making the necessary modifications in the Docker file, how do I redeploy the connector stack without causing any issues to the  OpenCTI application?

should the steps be as below or am i missing anything else
reset the connectors from the UI
stop the stack 
modify the docker file
redeploy the entire stack

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 22.04. }
2. OpenCTI version: { 5.9.6 }
3. OpenCTI client: { python }

**Comment by ghost** [comment]
Well, it depends on what you want to achieve. If you only want to import more data from a connector you can simply modify that date in your deployment and reset the connector state. All data will be imported but previously existing will stay untouched, so no duplication (Expecting you have not modified the data after creation).
If you really want to delete all data of a certain connector it depends if you used a dedicated user for the connector or not.
If you used a dedicated user you could go to data/entities and data/relations and use a filter for creator and delete all of them.
If you did not use a dedicated user you have to take a look what author was used in these entities the connector created and delete it by author. But you should take care that the author is not used by another connector, or also this data will be deleted if you take this approach.

**Comment by kodebrain** [comment]
Thank you @iFrozenPhoenix  
I understand that by removing data from Data/Entities, it should remove all the associated sections within the platform that are linked to that specific connector, eliminating the need for individual removal from sections like Events, Observations, etc. Is my understanding correct ?

**Comment by ghost** [comment]
@kodebrain Correct. Deleting an entity that is part of a relation also deletes the relation itself.
But in data/entities you have to delete all entites the connector has created, like described in my comment.
