### ISSUE TITLE
Can't do mass operations on Sightings

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4459]
- Go to the sightings list
- Select a sighting via the checkbox
- Do an action via the toolbar (ex: replace a field of the sighting)
- An error occurs

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/4126d863-2050-45ef-8d5b-cf43483a04ca)

**Comment by lhviet** [comment]
I see the same issue in Settings > Taxonomy > Labels.

I couldn't mass delete labels.
