### ISSUE TITLE
Can't mass delete Labels

### ISSUE THREAD

**Issue by lhviet** [LuatixHQ/opencti#4460]
## Description

Settings > Taxonomy > Labels.

I try to select multiple labels and mass delete them.
No errors and the job is Complete in the Background Task page.

However, they are still there.

## Environment

demo.opencti.io

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by SamuelHassine** [comment]
Duplicate of #4504.
