### ISSUE TITLE
OpenCTI 5.8.7 OTX connector no longer working

### ISSUE THREAD

**Issue by Crankinator** [LuatixHQ/opencti#4462]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Running the AlienVault OTX connector, we continue to get errors on ingestion. There has not been any significant changes to the connector, and I am confused as to what it is complaining about. I have double checked my environment values and everything matches up with 5.8.7

## Environment

1. OS (where OpenCTI server runs): EKS
2. OpenCTI version: 5.8.7
3. OpenCTI client: Frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Spin up OTX connector
2. Remove has exclusions and set "update existing data" to true (or false, didn't seem to make a difference)
3. When the connector runs, I get a bunch of errors stating the following:
`{'name': 'Variable "$input" of type "ExternalReferenceAddInput" used in position expecting type "ExternalReferenceAddInput!".', 'message': 'Variable "$input" of type "ExternalReferenceAddInput" used in position expecting type "ExternalReferenceAddInput!".'}`

Please let me know if you require any information.

**Comment by nino-filigran** [comment]
@Crankinator did you manage to solve your issue? I would advice now to upgrade if you have not done it before. Also, you can ask your question on Slack to get visiblity of the community!

**Comment by Crankinator** [comment]
Closing this. Update OCTI to fix this if you are on this old of a version.
