### ISSUE TITLE
"Artifacts" tab displays all observables after upgrade to 5.10.3

### ISSUE THREAD

**Issue by ckane** [LuatixHQ/opencti#4468]
## Description

After upgrading to 5.10.3 from 5.10.2, the "Artifacts" tab in the Observations section displays all observables in the Artifacts list - resulting in a bunch of fields that display 0-length, N/A, and/or mangled data.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04 LTS on EC2
2. OpenCTI version: 5.10.3
3. OpenCTI client: 5.10.3
4. Other environment details: Using Docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install 5.10.3
2. Go to Observations->Artifacts
3. See artifacts intermingled with other observables that should be filtered out

## Expected Output

The Artifact observables should be the only things rendered in the list

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/3454769/75fced64-73e9-4c84-9624-27a449d9371e)

**Comment by ckane** [comment]
Clicking on the top item of the list renders the appropriate observable page for the underlying data type (SOFTWARE), but the navigation tabs at the top still shows "Artifact":
![image](https://github.com/OpenCTI-Platform/opencti/assets/3454769/2f374456-c8ae-4a96-b1cc-98b28c0b213b)

**Comment by marieflorescontact** [comment]
Hi @ckane 
I can't reproduce the bug, either locally or in the test environment. 
can you send me the url for the Artifacts list, to find out the params?

**Comment by ckane** [comment]
Ok, I'll take a closer look tonight and see what's going on... I just tested logging into my instance from a private window in Firefox and the bug doesn't happen there, so it seems like it might be a result of that the session cookies from the prior session (under 5.10.2 and earlier) are probably causing the issue. It'll probably be fixed if I clear the cookies for my site.

**Comment by ckane** [comment]
Ok, that seems to have done it: closed the tabs and cleared the cookies for my OpenCTI server's domain

**Comment by ckane** [comment]
Ok I spoke too soon - I can reproduce it now. If I put the following filter in place, it co-mingles all the observables, so I think adding a filter might be removing the "must be an Artifact" filter criteria:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3454769/efc5f297-b147-421b-b0f6-a3d93a74f014)

**Comment by ckane** [comment]
False alarm @SamuelHassine, I accidentally jumped back to the "Observables" tab in the screenshot above. I have re-re-tested Artifacts a few more times now and can confirm it was just a stale session state, after all. You can re-close.

**Comment by ckane** [comment]
I'm closing it as it isn't a bug.
