### ISSUE TITLE
The cyber threat activity map on the dashboard breaks down

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4470]
## Description

I go to the dashboard page, click on the gear to the right of the "Dashboard" inscription, select "Date reference"->"Functional date" (but the new value is not set, this is strange...) and click "Close". After these actions, colored countries disappear from the map of cyber threat activity.
When I log in as another user, the cyber threat activity map is not broken, but after repeating the same actions, it breaks.

## Environment

1. OS: Ubuntu 21.1, 
2. OpenCTI version: OpenCTI 5.10.1 
3. OpenCTI client: frontend
4. Other environment details: Portainer 2.11.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the dashboard page
2. Click on the gear to the right of the "Dashboard" inscription
3. Select "Date reference"->"Functional date"
4. Click "Close". After these actions, colored countries disappear from the map of cyber threat activity.

## Expected Output

Nothing breaks down

## Actual Output

Colored countries disappear from the map of cyber threat activity.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/c93d45f1-72b9-4038-b8bb-1455d470eace)

**Comment by SouadHadjiat** [comment]
Hello @rattat0r,
Thank you for the bug report, there is indeed an issue with the date reference setting update which will be fixed. 
About the targeted countries map, if you select "functional date", it will display the targeted countries in the last 3 months based on "start time", which might not be defined in the imported stix data. So this is why the map is empty.
