### ISSUE TITLE
In the live stream, add NOT operator filter for “observable type”

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4484]
There is no current Not Operator filter use case for the "observable type" filter

**Comment by Jipegien** [comment]
Might be covered by refactoring of filters.

**Comment by SamuelHassine** [comment]
@Lhorus6 I don't understand this one, can you please do some testing? For me this is implemented....

**Comment by Lhorus6** [comment]
Press Alt before clicking on a filter to "Not" the chosen filter. In the case of filters on "Observable type", this does not work : there is no "NOT"

**Comment by SamuelHassine** [comment]
Yes ok I saw it.

**Comment by SamuelHassine** [comment]
Quickly fixed as  x_opencti_main_observable_type already supported in the backend (Elastic + Stream) as not operator (just missing in frontend definition).
