### ISSUE TITLE
Fine grained access restrictions with marking definitions

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4490]
## Use case
To have a more fine grained access restriction I'd like to apply custom marking definitions to an entity. The user should only have access to the entity if he has the tlp level and the custom marking definition.

## Proposed Solution
Check beneath the tlp marking definition also for custom marking definitions. If multiple custom marking definitions are applied to a entity and the user has one of it he should get access.

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
This is already implemented: https://docs.opencti.io/latest/administration/users/.

**Comment by ghost** [comment]
@SamuelHassine Unfortunately not.
Example. If I add the marking definitions TLP:GREEN (Type TLP) and AREA:GEOPOLITCAL (Type AREA) and use a User that just has the right access knowledge, with the allowed marking definition TLP:GREEN I can see the entity.
If the user has just AREA:GEOPOLITICAL I cannot see the entity.
My expected outcome would be that the TLP:GREEN marking definition is not enough to see the entity and that also the marking definition AREA:GEOPOLITICAL is needed (Beside the TLP definition).

If it should already work like this, then there is a bug, because currently it doesn't work like this.
Also the hint in the application states that if the TLP marking is fulfilled all custom marking definitions are also granted.
