### ISSUE TITLE
Unable to Deploy OpenCTI Dashboard

### ISSUE THREAD

**Issue by Cyberweasel777** [LuatixHQ/opencti#4493]
Hello I am struggling to deploy to the OpenCTI Dashboard

I'm using a private IP on my vmware? Could this be the issue? I have the resources, 32gb of ram and 200 gb of hard disk space. I can get everything on portainer, and on my docker swarm and worker. I am using version 3 of the compose.yml..

![image](https://github.com/OpenCTI-Platform/opencti/assets/56981548/d9bbd657-b11a-442f-92b6-2ca599076012)

![image](https://github.com/OpenCTI-Platform/opencti/assets/56981548/ed0e9460-b43c-4418-8bba-ec1b84df7b15)

![image](https://github.com/OpenCTI-Platform/opencti/assets/56981548/c2ce109f-34d2-41f0-b00e-59731e21e9f7)

![image](https://github.com/OpenCTI-Platform/opencti/assets/56981548/f635b608-1260-489f-a8b3-e73270f43f6d)

Any assistance, would be appreciated!

**Comment by Cyberweasel777** [comment]
note, I have swtiched back and forth between port 80 and port 8080 for the opencti container. So I dont believe that is the issue..

**Comment by AlexSanchezN** [comment]
Try changing OPENCTI_BASE_URL to http://0.0.0.0:8080
If you have localhost in there, it will only be visible from... localhost... :-)
Also be sure you access via http and NO via https

**Comment by Cyberweasel777** [comment]
that didnt help, but thank you. I've tried changing the /etc/hosts to that ip address. Nothing works I dont get it, I have the swarm, worker swarm, and portainer are working, but I cant deploy this. I'm using a vmmachine with ubuntu 22.04 desktop, bridged connection

**Comment by Cyberweasel777** [comment]
these are my service logs:

{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"Token must be a valid UUID"},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-10-06T06:00:11.014Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:395:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:192:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-10-06T06:00:11.016Z","version":"5.10.3"}

{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"Token must be a valid UUID"},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-10-06T05:59:31.988Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:395:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:192:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-10-06T05:59:31.991Z","version":"5.10.3"}

{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"Token must be a valid UUID"},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-10-06T05:59:58.916Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:395:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:192:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-10-06T05:59:58.919Z","version":"5.10.3"}

{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"category":"technical","http_status":500,"reason":"Token must be a valid UUID"},"internalData":{},"name":"ConfigurationError","time_thrown":"2023-10-06T05:59:46.978Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:395:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:192:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-10-06T05:59:46.982Z","version":"5.10.3"}

**Comment by Cyberweasel777** [comment]
wow, my env variables were off! thank you!!

**Comment by AlexSanchezN** [comment]
Glad to hear

Cheers

**Comment by deepakray184** [comment]
Hi, I am also getting a similar error, One of containers is throwing the error. Please help me in resolving the same. 

![image](https://github.com/user-attachments/assets/1a9e8ac6-04ae-4621-92cc-e8012d3682bf)
 

![image](https://github.com/user-attachments/assets/e3d3dc59-3011-43fa-a0d9-95a4ec1409cd)

The opencti container seems to be running but unable to access in browser **http://{Machineip}:8080**

![image](https://github.com/user-attachments/assets/05ad0a70-9e25-47ff-8c5a-9d7a3b74f39d)

**Comment by AlexSanchezN** [comment]
Check your tokens in .env file are valid. It looks like you have an error in one (or many).
You can get valid tokens from here: https://www.uuidgenerator.net/

**Comment by deepakray184** [comment]
Yes I double checked tokens in env variables and rechanged https://www.uuidgenerator.net/ still the same error persists. 

![image](https://github.com/user-attachments/assets/dc5519cf-788b-480e-a579-aa12b97a256c)
