### ISSUE TITLE
A table too large is cut off in the pdf export

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4501]
## Description

Exporting files containing large tables does not work correctly (i.e. tables are cut off).

## Reproducible Steps

1. Create a report, then go to its "Content" tab
2. Create an HTML file and add a table with several columns
3. Fill in the columns to make the table very large
4. Export the file in pdf format
=> The table not fully displayed (see screenshot attached)

<img width="962" alt="Table_in_OCTI" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/23979f15-af44-4927-89de-b35522a5c89b">
<img width="652" alt="Table_cut" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/e4ece5c5-bbbe-456d-b8c8-7d868ae2480c">

**Comment by marieflorescontact** [comment]
to solve this bug properly, the user needs to be able to set the format and orientation of the pdf before exporting it. We need to discuss this @Jipegien  and @nino-filigran 💐

**Comment by nino-filigran** [comment]
@Lhorus6 we'll provide a quick fix for this: basically if your content is larger than an A4 page in protrait mode, we'll switch to landscape mode when you want to print it. However if the text is bigger than the landscape, it would still be cropped. This is an easy fix before we do create a more sustainable feature around this. We'll track the implementation of this feature in here https://github.com/OpenCTI-Platform/opencti/issues/4862 and we'll close your bug as soon as the PR will be merged.

**Comment by Lhorus6** [comment]
That's great thank you!
