### ISSUE TITLE
CSV column mapping when a column can have different representations

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4505]
## Use case

A CSV contains a list of different objects. One of the column represent the type of object. According to the type, mapping of other column will differ.

## Current Workaround

Split the csv file

## Proposed Solution

In the CSV mapper, be able to define the column representing the objects' type and the value to use for the current representation mapping.
Example : Representation for "Threat Actor" when column Index "D" with value "equals/not equals" "threat_actor"

**Comment by securitiz** [comment]
@Jipegien was this feature implemented? I'm having a difficult time figuring out how to define the proposed columns.

My understanding is there should be one column, we'll call it "Value" - and it can contain all sorts of object types - files, IPv4s, URLs, etc. There is another column where we specify what type of object each value should be ingested as. Is my understanding correct?

**Comment by Jipegien** [comment]
This is clearly not implemented. Title of the issue has not been changed I think. Sorry about that. I confirm you cannot map such type of csv at the moment. @romain-filigran: to include in the long list of improvements for the CSV mapper.

**Comment by nino-filigran** [comment]
closing this one since it's a duplicate of https://github.com/OpenCTI-Platform/opencti/issues/4935
