### ISSUE TITLE
Unexpected Results in Widgets/Custom Dashboards

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4506]
## Description

The results of the number of connections differ when using regular filters as opposed to dynamic ones when I create a widget.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Horizontal bar widget
2. Set dynamic filters as in the screenshot below
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/1454819a-5019-4329-8d7f-3806cd492c66)

3. Create a new Horizontal bar widget
4. Set static filters as in the screenshot below
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/ffa562fa-999e-46fc-bf97-206869120085)

## Expected Output

The data on the widgets will be the same

## Actual Output

The data on the widgets does not match. Only on a widget with static filters the number of relationships is the same as in the Data->Relationships tab

## Screenshots
Dynamic filters
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/98d095cc-5f4a-4b47-a475-3f44c0284daf)

Static filters
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/d1567ad9-c27a-4ea5-9e59-c79a53335123)

**Comment by rattat0r** [comment]
Can you help me please?

**Comment by SamuelHassine** [comment]
Hello @rattat0r,

This has been fixed in 5.10.3. Can you please test and come back to me?

Kind regards,
Samuel

**Comment by rattat0r** [comment]
Thanks for the answer. I'll update later. In this case, the issue can be closed
