### ISSUE TITLE
Not all available assignees are displayed when creating or modifying a live trigger

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4527]
## Description

Not all available assignees are displayed when creating or modifying a report. Cannot assign report work to the correct user because he is not in the list of available ones.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login as admin
2. Go to analyses -> Reports
3. Click on "plus"
4. Сlick on the "Assignee(s)" button to select the desired user from the list

## Expected Output

Desired user does not appear in the list of available ones

## Actual Output

All users in the list of available ones are displayed

**Comment by rattat0r** [comment]
Sorry, I mixed up the expected and actual results.

**Comment by Archidoit** [comment]
Hello! This is a wanted behavior: max 10 assignees are displayed in the filter list. If you want to select a user that is not in the list, you can begin to enter its name, and you'll see it in the list.

**Comment by rattat0r** [comment]
The user will not appear in the Assignee in the live trigger if he is not added to the Assignee in the Report at least once.

**Comment by rattat0r** [comment]
If I try to add a new user in the Assignee filter in the Live trigger edit, then that user won't be there. When I add this user in the Assignee filter in the Report edit, then this user becomes available in the Assignee filter in the Live trigger edit.

**Comment by Archidoit** [comment]
Indeed that's another issue. I'm going to reopen the issue.

**Comment by Archidoit** [comment]
Comment : it's the same for assignee filter in Feed, Stream, Taxii.

**Comment by Archidoit** [comment]
@Jipegien When you create/edit a Feed/Stream/Taxii, only the users that are assigneed to at least an entity are displayed in the Assignee filter list. Do we want to extand these assignee filter lists to all the users? (Because we may want to create a trigger with the filter assignee = user1 even if user1 is assigneed to nothing for the moment...)

**Comment by Jipegien** [comment]
Yes. It is a more broad issue : https://github.com/OpenCTI-Platform/opencti/issues/3585

Filters for list should be limited to data that already exists in the platform. Filters for feed/stream/widget/notifier/automation/etc. should not.

**Comment by Archidoit** [comment]
Ok, @rattat0r your issue will be resolved in #3586 . Thanks for reporting the bug.
