### ISSUE TITLE
Extend authorized_member system to Cases, Groupings and Reports

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4538]
## Use case

Same as #3181 but for Cases

**Comment by richard-julien** [comment]
@marieflorescontact , @SouadHadjiat , think also about 

The 2 methods userFilterStoreElements and isUserCanAccessStixElement
They are used to control the access after a loading and also need to support the conditions of the authorized members

A possible capability to bypass the authorized members restrictions for the user that represent connectors (to discuss with product)
