### ISSUE TITLE
Question about the relationship between SDO and SCO based on STIX 2.1.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#4539]
I have a question while defining the relationship between SDO and SCO in the Knowledge tab in the report.

Before studying STIX 2.1, I simply defined relationships intuitively.
Example) When installing and accessing malware from a specific IP, **IP -(related to)-> Malware**

However, after studying STIX 2.1 in detail, accessing the OpenCTI Demo, and checking other reports, I found that there was a difference from the relationship I currently defined.

I did not use a indicator but define the relationship between SDO and SCO directly. Would it be okay if I did this?

I think you can understand it just by looking at the relationship without using indicators, but other reports do not and STIX uses many other SDOs, so I am asking.

I would be grateful if you could give me advice on whether there will be any problems with this, and if the relationship needs to be changed, how to change it.

Below is an example of the relationships I defined.
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/4a35ec46-7db0-4892-b2d2-a7e430fc9fba)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/b68e3ba9-3f1d-4c37-b091-4d7f5bd3df27)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/d85f4244-0c97-4c77-af17-1bee66e94633)

**Comment by Jipegien** [comment]
In OpenCTI, you can easily see if a relationship has been designed to be used between to Entity: if your relationship is not "related-to" then it has a meaning and has been designed to be used in this situation. But STIX 2.1, and OpenCTI, has been made to be adaptable and propose a by-default "related-to" relationship you can use everywhere. This "meaningless" relationship will lack of feature though in OpenCTI. 

The most important is that your data model is meaningfull to you and coherent for all the data in your platform. 

To be more compliant with the way STIX 2.1 has been designed, I'd advise you to put Indicator between your SCO and your Malware and Attack pattern, levering the relationship "indicates" and "based on". You can easily promote an observable to Indicator through the UI (Overview of the observable or even by selecting multiple ones from a list and using the bottom toolbar)
