### ISSUE TITLE
Is it possible to duplicate the dashboard in order to customize it in the future?

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4542]
Is it possible to duplicate the dashboard in order to customize it in the future?  I use OpenCTI 5.10.1.

I want to create a second dashboard like the one I created. This is required so that the platform user can slightly change my customized dashboard for themselves.

It would be a good solution to add a "Dublicate" button in the "Custom dashboards" window.

**Comment by SarahBocognano** [comment]
This capability is planned for the next milestone (5.12.0) , you can find the issue tracking here : https://github.com/OpenCTI-Platform/opencti/issues/3242

**Comment by nino-filigran** [comment]
@rattat0r just to confirmed that this has been shipped through the above issue in 5.12
