### ISSUE TITLE
Notifier Classification Banner

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#4543]
## Use case

Add classification banners to notifier email.

## Current Workaround

Currently there is no work around for this issue.

## Proposed Solution

Add selectable classification banners when sending triggers with "Default Mailer", currently none are available.

## Additional Information

Good resource and examples https://cyberintelsystems.com/classification-banner/

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by explorecti** [comment]
Is there any status update available?

**Comment by nino-filigran** [comment]
@explorecti Could you please specify why do you need these banners?
Indeed, we do not share any data in the email (in theory).
Do you need to share the received email with anybody and make them aware of the classification? Or is it just for you and your users, to feel that some information is confidential? Or do you have any regulatory requirement ?

**Comment by explorecti** [comment]
@nino-filigran This would be for a regulatory requirement.

**Comment by nino-filigran** [comment]
Can you please let me what's the exact requirement please?

**Comment by explorecti** [comment]
@nino-filigran I will work with one of our FILIGRAN partners to provide that exact requirement. Thank you.
