### ISSUE TITLE
SMTP__FROM_EMAIL not working

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#4544]
## Description

despite the use of SMTP__FROM_EMAIL="opencti@mydomain.com" on my docker-compose, Opencti continue to use admin@opencti.io

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.10.3
3. OpenCTI docker-compose configuration:
                "NODE_OPTIONS=--max-old-space-size=8096",
                "APP__BASE_PATH=/opencti",
                "APP__ADMIN__EMAIL=admin@mydomain.com",
                "APP__ADMIN__PASSWORD=XXX",
                "APP__ADMIN__TOKEN=XXX",
                "APP__APP_LOGS__LOGS_LEVEL=info",
                "APP__APP_LOGS__LOGS_FILES=false",
                "APP__AUDIT_LOGS__LOGS_FILES=false",
                "REDIS__HOSTNAME=redis-opencti",
                "REDIS__PORT=6379",
                "REDIS__TRIMMING=1000000",
                "REDIS__PASSWORD=XXX",
                "ELASTICSEARCH__URL=XXX",
                "MINIO__ENDPOINT=minio",
                "MINIO__PORT=9000",
                "MINIO__USE_SSL=false",
                "MINIO__ACCESS_KEY=XXX",
                "MINIO__SECRET_KEY=XXX",
                "RABBITMQ__HOSTNAME=rabbitmq.",
                "RABBITMQ__PORT=5672",
                "RABBITMQ__PORT_MANAGEMENT=15672",
                "RABBITMQ__MANAGEMENT_SSL=false",
                "RABBITMQ__USERNAME=XXX",
                "RABBITMQ__PASSWORD=XXX",
                "PROVIDERS__LDAP__STRATEGY=LdapStrategy",
                "PROVIDERS__LDAP__CONFIG__URL=XXX",
                "PROVIDERS__LDAP__CONFIG__BIND_DN=XXX",
                "PROVIDERS__LDAP__CONFIG__BIND_CREDENTIALS=XXX",
                "PROVIDERS__LDAP__CONFIG__SEARCH_BASE=XXX",
                "PROVIDERS__LDAP__CONFIG__SEARCH_FILTER=XXX",
                "PROVIDERS__LDAP__CONFIG__MAIL_ATTRIBUTE=mail",
                "PROVIDERS__LDAP__CONFIG__ACCOUNT_ATTRIBUTE=sAMAccountName",
                "PROVIDERS__LDAP__CONFIG__FIRSTNAME_ATTRIBUTE=givenName",
                "PROVIDERS__LDAP__CONFIG__LASTNAME_ATTRIBUTE=sn",
                "PROVIDERS__LDAP__CONFIG__GROUP_SEARCH_BASE=XXX",
                "PROVIDERS__LDAP__CONFIG__GROUP_SEARCH_FILTER=XXX",
                "PROVIDERS__LDAP__CONFIG__AUTO_CREATE_GROUP=true",
                "PROVIDERS__LDAP__CONFIG__GROUPS_MANAGEMENT=XXX",
                "PROVIDERS__LDAP__CONFIG__ALLOW_SELF_SIGNED=true",
                "PROVIDERS__LOCAL__STRATEGY=LocalStrategy",
                "PROVIDERS__OPENID__STRATEGY=OpenIDConnectStrategy",
                "PROVIDERS__OPENID__CONFIG__LABEL=Login with Keycloak",
                "PROVIDERS__OPENID__CONFIG__ISSUER=XXX",
                "PROVIDERS__OPENID__CONFIG__CLIENT_ID=XXX",
                "PROVIDERS__OPENID__CONFIG__CLIENT_SECRET=XXX,
                "PROVIDERS__OPENID__CONFIG__REDIRECT_URIS=XXX",
                "PROVIDERS__OPENID__CONFIG__AUTO_CREATE_GROUP=true",
                "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=XXX
                "PROVIDERS__OPENID__CONFIG__ROLES_SCOPE=opencti",
                "PROVIDERS__OPENID__CONFIG__GROUPS_SCOPE=opencti",
                "NODE_EXTRA_CA_CERTS=/XXX",
                "SMTP__HOSTNAME=smtp.lan.mydomain.com",
                "SMTP__PORT=25",
                "SMTP__USE_SSL=false",
                "SMTP__REJECT_UNAUTHORIZED=false",
                "SMTP__USER=",
                "SMTP__PASSWORD=",
                "SMTP__FROM_EMAIL=opencti@mydomain.com",
                "APP__PORT=8086",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=20.7.0",
                "YARN_VERSION=1.22.19",
                "PYTHONUNBUFFERED=1",
                "NODE_ENV=production"

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Start OpenCTI with 2 nodes without subscription_scheduler and no SMTP config
2. Add  SMTP config and remove SUBSCRIPTION_SCHEDULER__ENABLED=false on both opencti instance

## Expected Output

I expected mail from opencti@mydomain.com and not admin@opencti.io

## Actual Output

```
==> /var/log/mail.info <==
Oct 11 21:57:10 dt-mail-relay-01 postfix/smtpd[15600]: NOQUEUE: reject: RCPT from unknown[MY_OPENCTI]: 554 5.7.1 <admin@opencti.io>: Sender address rejected: Access denied; from=<admin@opencti.io> to=<me@mydomain.com> proto=ESMTP helo=<[127.0.0.1]>
```

Thank you in advance for your help

**Comment by richard-julien** [comment]
Hi @Tonnulus , this configuration is not in the config file but directly accessible in the UI.
Do you thing this in the documentation?

You setup this in the UI in
`Parameters > Sender email address`

**Comment by Tonnulus** [comment]
Great It's working ! :)
Sorry to bother you for this 
Thank you
