### ISSUE TITLE
Is there a way to link multiple objects that exist in the Knowledge tab of a report?

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#4552]
Below is a screen shot of the SDO and SCO objects that currently exist in the report.
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/07fab2f2-867a-435f-a49f-2c7906c2460e)

When the number of objects was small, I created arrows (links) between objects by manually clicking on them one by one. However, if the number of objects is too large, I think this method is impossible.

In some reports on the OpenCTI demo site, hundreds of SDOs and SCOs are connected to each other, and I wonder how they made.(Below is an example.)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/ada37b69-6722-4df6-881c-dbb5c1a16056)

I would appreciate it if you could tell me how to connect or a page worth referring to.

**Comment by nino-filigran** [comment]
@misohouse these are foten created by connectors, where we also define some relations to create whenever some objects are created. I can understand that creating relations manually can be cumbersome. Therefore my advice is either to use connectors or to use another view, such as any entity view (ex: attack pattern) go in the knowledge tab, select the type of view you would like (for instance victimology) and add from there all the entities which are victims of this attack pattern. then you can add it directly in a container. This is still highly manual, but could be potentially easier.

**Comment by misohouse** [comment]
@nino-filigran Thank you for reply. Would you tell me what connector is used??

**Comment by nino-filigran** [comment]
@misohouse I can't, as you can see [in this page](https://filigran.notion.site/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76), there are hundreds of them! Usually, platform users know which connectors they need daily, so I would not be able to "advise" any since it would depend on your needs.

**Comment by misohouse** [comment]
@nino-filigran I'm aware of that page and I'm using various connectors. However, I asked because of what you said about creating relationships through connectors.

Currently, I'm using the API provided by OpenCTI to establish relationships between a large number of objects.

I don't think there's a connector that can accomplish what I'm looking for, so I guess the only way to do it is to set up a large number of object-to-object relationships based on the API.

Thank you for reply :)
