### ISSUE TITLE
Problem with filter feeds CSV

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4555]
## Description

I'm publishing a feed for a firewall from the platform with only IPs, and I'm having problems in the filtering since I'm getting urls.

## Environment

1. OS (Ubuntu)
2. OpenCTI version: OpenCTI 5.10.3
4. Other environment details:

## Reproducible Steps
When I configure the following filters:
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/a760ce00-ecbf-4524-ad7e-982168ed9bbc)

It seems that it does not filter well because of the filter that I put on it:
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/afe87f60-6edb-4833-ad95-37a2e866d301)

Another example:
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/45f5adb7-f5ea-43e0-92e5-5affe4429686)
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/d2a6fb8a-610c-4b46-9760-f4302904502c)

I have tried varying the filters or using the opposite, but to no avail.

 I think it's a bug, or I'm doing it incorrectly. Can you help me?

**Comment by richard-julien** [comment]
As you choose to expose indicator, filter on an entity type is not relevant. I think you want to filter on the main observable type to get all indicator that are IPv4. We will remove entity_type from the filter and add the main observable in the next version

**Comment by softengsistemas** [comment]
Hello Richard,
Thanks for your response, I just updated to the latest version and I still have the problem. I can't find the filter "type of observable":
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/aab96786-e122-4e80-822d-f84dcde17c1a)
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/67f09f5b-a246-4a55-9e73-81ac744a0191)
Same result
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/fd868c04-339a-43d3-a233-7d33a3696290)

Thx

**Comment by softengsistemas** [comment]
> As you choose to expose indicator, filter on an entity type is not relevant. I think you want to filter on the main observable type to get all indicator that are IPv4. We will remove entity_type from the filter and add the main observable in the next version

Hello Richard,
Thanks for your response, I just updated to the latest version and I still have the problem. I can't find the filter "type of observable":
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/f013f7b9-1e07-42d7-b347-49c6a1e968ea)
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/80929e27-5217-4a9f-ae03-9a801749733a)
Same result
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/1e5a07c1-1ebd-4378-8583-4948b54afed5)

Thx

**Comment by richard-julien** [comment]
Remove type de entidad + Add Typo de indicator?

**Comment by softengsistemas** [comment]
Something is not going well...

The desired behavior is a CSV list of IPv4 indicators (7.230 indicators) that match the following filters:
- Author isn't "SOFTENG".
- Confidence greater than 3.
- Created after 3 months.

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/4d7704b6-428b-419d-93cc-04b9bf1ff64e)

If I configure the CSV export with these filters, the list only returns me 2 indicators and not the 7.230 indicators...:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/b8cd3cb8-69e0-463a-8248-74c7897daced)

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/5d58fc6b-8650-4115-849b-c8a88ef63db1)

**Comment by richard-julien** [comment]
Sorry its not typo de indicator but typo de observable.

**Comment by softengsistemas** [comment]
Type of observable doesn't exist in the filter!

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/39a3577f-852c-4466-a337-e5cbc9968d26)
![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/f13c661c-46f0-4a16-9cb2-04615c420925)

**Comment by softengsistemas** [comment]
It works well! Thanks!
