### ISSUE TITLE
Implement Ingestion CSV Feeds (like TAXII, RSS, etc.) using mappers

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4569]
## Use case

Implement Ingestion CSV Feeds (like TAXII, RSS, etc.) using mappers.

Examples of CSV feeds:

https://www.misp-project.org/feeds/.

**Comment by SamuelHassine** [comment]
Please note that those feed can handle also .txt with only one column or column based.

**Comment by Goumies** [comment]
Subsidiary tasks need to be done in a complementary PR.
The first one was long-awaiting.
