### ISSUE TITLE
CodeCov is not updated since 2 months (0% coverage)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4595]
## Description

CodeCov is not updated since 2 months (0% coverage)

**Comment by Kedae** [comment]
@SamuelHassine  ?
![image](https://github.com/OpenCTI-Platform/opencti/assets/50013774/5df6057b-aef5-4f8b-b222-778e264194bb)

**Comment by SamuelHassine** [comment]
Hello @Kedae,

Still not working. Tracked lines  / files is not correct.

**Comment by SamuelHassine** [comment]
Only those files are tracked:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/1ad77be9-dc22-4782-968a-b0be723d99bb)

**Comment by SamuelHassine** [comment]
Any news on this @Kedae?
