### ISSUE TITLE
Unable to delete the last filter in a TAXII collection

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4622]
## Description

When modifying TAXII collection, it is impossible to delete a filter when it is the only one remaining. Is this intentional?
If I want to delete all the filters and start the configuration from scratch, that's not possible.

## Reproducible Steps

1. Create a TAXII collection with one or more filters. 
2. Edit TAXII collection to change filters -> Try to remove all filters. The last remaining filter is grayed out and cannot be deleted.

## Screenshots
<img width="1722" alt="Screenshot 2023-10-16 184046" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/34fb03d3-8934-4693-892c-d40eca647525">

**Comment by ckane** [comment]
I noticed this too. It would be nice to be able to make an "everything" feed by leaving the filter blank.
