### ISSUE TITLE
OPENCTI issue while using docker

### ISSUE THREAD

**Issue by Escabelado** [LuatixHQ/opencti#4624]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 16.4
2. OpenCTI version: OpenCTI 5.10.2 }
3. OpenCTI client: docker
4. Other environment details: docker version 24.0.6

Issue description:
1. Deployed the open CTI stack using the official YAML file
2. WIth all the dependents (redis, elasticsearch, minio, rabbitmq) up and running, opencti service does not start and its containners present the following error logs:

INF [OPENCTI] Starting platform | category=APP timestamp=2023-10-16T16:16:04.436Z version=5.10.2
INF [OPENCTI] Checking dependencies statuses | category=APP timestamp=2023-10-16T16:16:04.444Z version=5.10.2
INF [SEARCH] Engine client not specified, trying to discover it with opensearch client | category=APP timestamp=2023-10-16T16:16:04.445Z version=5.10.2
ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":"connect ECONNREFUSED 127.0.0.1:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:65:53)\n    at /opt/opencti/build/src/database/engine.js:181:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:177:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:216:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:139:3)\n    at platformStart (/opt/opencti/build/src/boot.js:188:5)"} timestamp=2023-10-16T16:16:04.556Z version=5.10.2

The elasticsearch service is up and running, with no "failed" containers. Can you help solving this issue? Thank you so much in advance.

**Comment by helene-nguyen** [comment]
Hello @Escabelado,
Sure we can help :) Could you please give us more details about the steps to reproduce your error ? 
And maybe some screenshots ?

**Comment by Escabelado** [comment]
<img width="1195" alt="Screenshot 2023-10-17 at 10 26 57" src="https://github.com/OpenCTI-Platform/opencti/assets/132770787/58e11dc8-a2f2-403f-9395-ddf8c9890c63">
<img width="1176" alt="Screenshot 2023-10-17 at 10 23 59" src="https://github.com/OpenCTI-Platform/opencti/assets/132770787/1e1ea019-a3d4-4f20-aa07-c935e104742c">

Hello, thank you for the quick response. You can find attached the services status screenshot and their respective containers. All the "failed" containers present the same error logs thus, I only send one sample.
I used portainer to deploy the docker-compose.yml file provided in OpenCTI-Platform github as well as the environment variables
Steps:
1. install portainer
2. define the env variables (uuid, passwords, etc)
3. copy the yml file to portainer
4. upload an .env file to portainer
5. deploy stack

You won't see any worker or connector in the screenshot attached because i commented the yml file after the opencti image (since opencti would not start and everything that comes after depends on it)
Thank you

**Comment by helene-nguyen** [comment]
Hello @Escabelado,

I've reproduced the steps you gave to me.
When I start to launch the stacks with portainer, I received the error message that you sent to me:

![image](https://github.com/OpenCTI-Platform/opencti/assets/75518128/2f486cfd-3794-4bfd-8213-272d62eb5af2)

> ERR [OPENCTI] Platform start fail | category=APP error={"context":{"category":"technical","error":"connect ECONNREFUSED 172.23.0.5:9200","http_status":500,"reason":"[SEARCH] Search engine seems down"},"message":"A configuration error has occurred","name":"ConfigurationError","stack":"ConfigurationError: A configuration error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:65:53)\n    at /opt/opencti/build/src/database/engine.js:182:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:178:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:217:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:137:3)\n    at platformStart (/opt/opencti/build/src/boot.js:215:5)"} timestamp=2023-10-18T06:04:30.133Z version=5.11.4

But everything works fine after a few minutes, time for containers to run properly:

![image](https://github.com/OpenCTI-Platform/opencti/assets/75518128/4dd6d41a-07d3-473d-bf55-04114f77cd74)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75518128/58bb3215-f990-4132-9a51-75bec2349fe4)

Can you check your configurations again ?

Please find the YAML file I use:
https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml

And the sample for .env
https://github.com/OpenCTI-Platform/docker/blob/master/.env.sample

If needed and if it can help, you can join our Slack community and you can schedule a moment to share screen with me if you still have any error:
https://community.filigran.io/

For the moment, I close the ticket but it can be re-opened if needed :)
Hope it can help :)
