### ISSUE TITLE
Backup and Disaster Recovery

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#4628]
Hi all,

We have been using OpenCTI for a while now, and would like to spin up a new environment that looks similar to the high level architecture found on your clustering deployment page. https://docs.opencti.io/latest/deployment/clustering/

With this is mind, can you please advise what the best backup procedure and data recovery procedure is for an architecture like this. Currently, our indicators are coming from Taxii feeds, so there is not a requirement to back up this data. We do need to backup configuration data though, configuration settings for CSV and Taxii feeds, as well as roles/groups/users/tokens need to be securely backed up.

In a worst case scenario, where everything but backups was destroyed, what is vital for the OpenCTI configuration to get it back up and running again as soon as possible.

I've had a real quick look at the backup files stream connector, it looks like it backs up each indicator and relationship individually, do you intend that we then import this into the new OpenCTI instance? I imagine this could take a real long time to re-import if there a re a lot of indicators. Is there a better way to do this?

**Comment by CyberKaizen** [comment]
@annoyingapt A great deal of the OpenCTI data goes into ElasticSearch. You'll need to make sure that to create scheduled snapshots of your ElasticSearch. The easiest way to do this is via Kibana. I've actually started working on this today. https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html

**Comment by nino-filigran** [comment]
@annoyingapt feel also free to raise your question on Slack as some member of the community coudl help!

**Comment by annoyingapt** [comment]
I chose this platform over Slack as the question will get buried after a week or so. Look, I totally don't mind if there is no answer, but anyone trying to get this into production will be asked questions  around disaster recovery and backup. Having some documentation around this should help people in the future and make it easier for them to get past a minimal viable product to something in production.

**Comment by tutueh** [comment]
@annoyingapt Can you share how you proceeded with this topic? Did you manage to find any answers about Backup & Disaster Recovery?
