### ISSUE TITLE
Error unknown when creating observable in analyst workbench - where to look for logs?

### ISSUE THREAD

**Issue by tintinkuifje** [LuatixHQ/opencti#4637]
## Prerequisites

Looked at the logs from openCTI, couldn't find an error message

## Description

Creating a new observable in /dashboard/import/pending/ creates an "unknown error contact openCTI maintainers", see screenshot.
Not sure where to look for an error message?

## Environment

OpenCTI 5.11.3

## Reproducible Steps

Import pdf, go extracted entities/observvables and click on the button to add an observable

![opencti data import unknown error](https://github.com/OpenCTI-Platform/opencti/assets/131458486/81d1382e-d5d3-4236-a888-eedbbf53b01f)

**Comment by SamuelHassine** [comment]
Hello @tintinkuifje,

Can you please share the console error log (browser console)?

Thanks!

Kind regards,
Samuel
