### ISSUE TITLE
Filters layout is incorrect in feeds

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4646]
## Description

Filters layout is incorrect in feeds:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/6ecd7f4e-3407-4e93-914b-fc39a3854895)

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/5c36096d-ac9e-4dab-b1e3-09f82eecf712)

Same for CSV / Streams / TAXII. May also be in triggers.

**Comment by SamuelHassine** [comment]
@SouadHadjiat: still happening on retention policies (Settings => Customization => Retention policies):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0983549b-b772-4e63-905e-d062d5065d5a)

Is it a more global problem we have broken in the refactor of the drawer by @Kedae?

**Comment by Kedae** [comment]
Nop we had that before, I checked. 

The issue with the alignment the first time, but if you close and come back usually it's better. I haven't investiguated far

**Comment by SouadHadjiat** [comment]
> @SouadHadjiat: still happening on retention policies (Settings => Customization => Retention policies):
> 
> ![image](https://user-images.githubusercontent.com/1334279/276598776-0983549b-b772-4e63-905e-d062d5065d5a.png)
> 
> Is it a more global problem we have broken in the refactor of the drawer by @Kedae?

Oh I thought I checked everywhere :( I can open another PR to fix it for retention policies
