### ISSUE TITLE
Due date are not displayed correctly in case tasks

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4647]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/636ee460-f66d-4a41-9916-b7ff95f33bba)

**Comment by Archidoit** [comment]
Is this really a bug? We want the date to be in a certain color depending if the due date is passed or not.

**Comment by Archidoit** [comment]
Is this really a bug? We want the due date to be displayed in a certain color according to the current date (if the due date is passed : red, else: blue)

**Comment by richard-julien** [comment]
I think its more about the bottom crop and maybe the length that mask most of the date

**Comment by SamuelHassine** [comment]
Yes sorry, it is the size of the chip which is not correct @Archidoit.
