### ISSUE TITLE
Error with Default mailer

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4649]
## Description

I have set up a live trigger on modifying the Report with notification using Default mailer. I specified all the data necessary for smtp in the docker-compose file.
When I change the report to cause the trigger to fire, I see an error in the opencti/platform logs:
{
  "category": "APP",
  "error": {
    "context": {
      "category": "business",
      "http_status": 500,
      "reason": "No representative extractor available for User"
    },
    "message": "Unsupported operation",
    "name": "UnsupportedError",
    "stack": "UnsupportedError: Unsupported operation\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnsupportedError (/opt/opencti/build/src/config/errors.js:80:51)\n    at extractStixRepresentative (/opt/opencti/build/src/database/stix-representative.ts:268:9)\n    at convertFiltersFrontendFormat (/opt/opencti/build/src/utils/filtering.js:115:23)\n    at buildTargetEvents (/opt/opencti/build/src/manager/notificationManager.ts:446:30)\n    at notificationStreamHandler (/opt/opencti/build/src/manager/notificationManager.ts:519:25)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:600:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:654:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:671:13)"
  },
  "level": "error",
  "message": "[OPENCTI-MODULE] Error executing notification manager (live)",
  "timestamp": "2023-10-18T12:12:09.386Z",
  "version": "5.10.1"
}

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.6 (docker)
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings -> Security -> Users -> Our_user
2. Add a live trigger to change reports from the user Our_user
3. Set Notifiers=Default mailer
4. Set up a real email for the user Our_user
5. We cause the trigger to fire by modifying the report
6. An error appears in the platform logs, but the message does not arrive by email to the user

## Expected Output

The user receives a notification by email.

## Actual Output

The user does not receive an email notification. An error appears in the logs.

**Comment by rattat0r** [comment]
I encountered a similar error name - "No representative extractor available for User"

Steps to reproduce the error:
1. Create a CSV feed in the "Data sharing" subsection
2. Specify the required user in the Technical creator filter
3. Open CSV Feed

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/a9d302b5-bae2-494f-affb-0938e403db2e)
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/21f3156c-cd3b-4291-95b4-c93a3a06adad)

But if instead of user you specify Organization in the "Author" filter, then the CSV feed works well.

**Comment by rattat0r** [comment]
If the organization is specified in the "Authon" filter, then everything works:
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/73fa515f-a8b5-4a82-b256-051ad7f76104)

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/45c81cb3-4e2f-4096-82c3-e37e0c7cc1b9)

**Comment by SouadHadjiat** [comment]
Hello @rattat0r,
This issue has been fixed in 5.11 (linked to this [issue](https://github.com/OpenCTI-Platform/opencti/issues/4461)).
I now can't reproduce this bug since our latest release, so I can only recommend to upgrade to the latest version. 
I suggest however to wait for [5.11.5](https://github.com/OpenCTI-Platform/opencti/milestone/119) since we have some important bug fixes to deploy.

**Comment by SamuelHassine** [comment]
5.11.5 is out.
