### ISSUE TITLE
Form freezes when adding references to a "uses" relationship between Incident and Narratives

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4652]
## Description

In an incident, when adding a uses relationship to a narrative, the form is unable to grab external references by, for example, URL address and gets stucked. This happens when URLs are searched using quotes and without them.

This may happen in other forms but has not been tested on all.

## Environment

1. Docker
2. OpenCTI 5.11.2
3. frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on an incident
2. Click on knowledge
3. Click on narratives
4. Click on the +  button to add some
5. Select one or several narratives
6. Try to add an external reference to the relationship

## Expected Output

Add the relationships with the references

## Actual Output

Form freezes

## Additional information

N/A

## Screenshots (optional)

N/A

**Comment by SarahBocognano** [comment]
It seems to works fine on my platform. The form doesn't freeze and I have the external reference in the relationship. 
I've try to add an existing external ref and also I've had one created from scratch and it works on both cases.
Do you have any log or something ?

**Comment by febrezo** [comment]
Hmmm... How are you searching the External reference? Using the full URL between quotes? Note that this only happens to us when adding a uses relationship between an incident and a narrative. I can reproduce it again in our platform but with your comment I'm wondering if what is broken is something else.
