### ISSUE TITLE
Inconsistent info in the Knowledge - Victimology screen

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4653]
## Description

The victimology screen shows information which seems inconsistent showing information of more relationships that the ones that exist.

## Environment

1. Docker
2. OpenCTI 5.11.2
3. frontend
4. Other environment details:

- There exists an incident targetting organization A.
- Organization A is located in Country C
- Organization A is part of Subector Ss1 which is part of Sector 1
- Organization A is part of Subector Ss2 which is part of Sector 2
- Organization A is part of Subector Ss3 which is part of Sector 3
- targets rules engine is active to set the target Country C in Subregion S and Region R
- targets rules engine is active to set the target Subsector Ss1 and Sector 1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a similar environment
2. Activate rules
3. Click on the incident
4. Click on knowledge
5. Click on victimology
6. Check the graphs there

## Expected Output

The expected output is that there exists ONLY ONE relationship between:

- Incident I and Subsector Ss1
- Incident I and Subsector Ss2
- Incident I and Subsector Ss3
- Incident I and Sector S1
- Incident I and Sector S2
- Incident I and Sector S3
- Incident I and Country C
- Incident I and Subregion S
- Incident I and Region R

## Actual Output

The actual output is that there exists the following relationships (check image below):

- Incident I and Subsector Ss1
- Incident I and Subsector Ss2
- Incident I and Subsector Ss3
- Incident I and Sector S1: **2 relationships**
- Incident I and Sector S2: **2 relationships**
- Incident I and Sector S3: **2 relationships**
- Incident I and Country C
- Incident I and Subregion S: **2 relationships**
- Incident I and Region R: **4 relationships**

## Additional information

There seems to be a number which is powered to 2 but could not guess the reason.

## Screenshots (optional)

![imagen](https://github.com/OpenCTI-Platform/opencti/assets/1590496/9c0b1056-f92d-4e4c-b201-fb29ebeab59f)

**Comment by helene-nguyen** [comment]
Hello @febrezo, thank you for reporting this. We have made some changes since version 5.11.2 that may correct this behavior.

You can find all the changes that have been made in the link below:
https://github.com/OpenCTI-Platform/opencti/releases

Could you try to update your instance and tell me if the behavior is still the same?

**Comment by febrezo** [comment]
I'll let you know soon as soon as I can built the scenario. :)

**Comment by helene-nguyen** [comment]
Hi @febrezo, I close the issue since we are on version 5.11.12 that correct some bugs. Maybe you can try again ?
The ticket can be re-open if needed :)
