### ISSUE TITLE
Allow Incident filtering by Status

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4660]
## Use case

Usually, analysts need focus only in "Opened" or "New" incidents. It would be useful to permit to filter by status.

## Current Workaround

Set a label and filter by it.

## Proposed Solution

Adding a new filter.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

Yes (but need some guidance)

**Comment by nino-filigran** [comment]
@febrezo I'm assuming you're talking here about incident response right?
If so, you can filter by status on it. Let me know if it is what you expected with this ticket.

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/a6e5350c-5823-4cd3-a646-50db572f1176)

**Comment by nino-filigran** [comment]
@febrezo I'm closing this ticket given this feature is available. If I did not understand your request, feel free to re-open the ticket.
