### ISSUE TITLE
In investigation, it is not possible to pivot on external references

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4664]
## Description

In investigation, it is not possible to pivot on external references (but label is ok, kill chain phase is ok etc.)

**Comment by labo-flg** [comment]
It seems to work when I try to expand external references from a random entity (here a vulnerability):

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/7d5ab625-be0b-42f0-a817-2689ca1acaf8)

Did you experience this bug in another context ? maybe a specific entity type to pivot from ?

**Comment by SamuelHassine** [comment]
Sorry, false positive.
