### ISSUE TITLE
Be able to use relationship from/to in CSV feeds

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4665]
## Use case

For instance, be able to craft a CSV Feed with incidents and columns such as:

* Name
* Description
* Targeted sectors
* Targeted countries
* Labels

Relationships should be separated by commas and use the entity representative of the from or to.

**Comment by nino-filigran** [comment]
@SamuelHassine could you specify where does this need comes from? Is this a request from anybody or some limitations that you have noticed?

**Comment by SamuelHassine** [comment]
@nino-filigran It has been covered by the CSV mapper!
