### ISSUE TITLE
Release notes are incorrect

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4666]
## Description
If an issue is opened as a feature it is mentioned in the release notes as an enhancement even if the issue was closed as wontfix or notplanned.

## Expected Output
Correct release notes. E.g. only those are considered enhancements that are closed and have a merged PR. For example...

**Comment by SamuelHassine** [comment]
Do you have an example please? This should not happen.

**Comment by ghost** [comment]
@SamuelHassine sure. Release note [5.11.0](https://github.com/OpenCTI-Platform/opencti/releases/tag/5.11.0) mentions #4420 as enhancement (6th from top). But this issue was closed as not planned.
