### ISSUE TITLE
In Threat-Actor-Individual some demographics infos are not working properly

### ISSUE THREAD

**Issue by SarahBocognano** [LuatixHQ/opencti#4667]
## Description

When you try to create or update a threat actor individual, you cannot fill in the "Place of Birth" / " Ethnicity " and some fields are missing such as :
- Place of Residence
- Citizenship
- Nationality

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Threat Actor Individual
2. Go to the Demographics section
3. Try to fill Place of Birth and/or Ethnicity
4. Nothing's happening

## Expected Output

The field should be filled, and displayed on the demographics overview

**Comment by richard-julien** [comment]
To discuss @SarahBocognano as i cant reproduce this behavior and Place of Residence, Citizenship and Nationality must be created through relationships

**Comment by SarahBocognano** [comment]
My bad @richard-julien , it works fine.
