### ISSUE TITLE
Can't export knowledge entities 

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#4670]
## Environment

1. OS (where OpenCTI server runs): Testing plateform
2. OpenCTI version: 5.11.4
3. OpenCTI client:frontend 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Go to a Malware Overview -> Knowledge Section -> Indicators -> Select some and export

It's the same for all the entities

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/9349ea3e-9a43-4bd7-97af-d0021603ce9e)

**Comment by labo-flg** [comment]
This is a drawer issue (cc @Kedae). I'm on it.
