### ISSUE TITLE
Table text does not change color after switching from dark theme to light theme

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4693]
## Description

The text in the report content edit table does not change color after changing from a dark theme to a light theme. Because of this, the text is not visible.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.10.1
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Report->Knowledge->Content mapping view
2. Switch to Edition mode
3. Add a table and enter text into it
4. Change the theme to light
5. The text remains white, so it is not visible

## Expected Output

After changing the theme color, the text will change to the opposite color.

## Actual Output

After changing the theme color, the text remains the same color, so it is not visible

## Screenshots
Before
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/fce9f38a-d3fc-4f53-bfac-9b92419cf326)
After
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/c9f75bea-258d-461d-83ff-a2ae331e660a)

**Comment by lndrtrbn** [comment]
Until this is fix, you can manually change the color of the text using the tool in the screenshot below
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/59994965-4868-443e-a1fa-0774aa5e1a1d)

**Comment by rattat0r** [comment]
@lndrtrbn I discovered that this issue occurs when using the "Inter" font. When using the font "Arial" everything works fine.

**Comment by lndrtrbn** [comment]
After some tests, I don't think it's font family related. I could reproduce the issue no matter the font I chose.

However, it seems that the issue is that rich text editor theme is not reloaded correctly when changing the theme in settings.
If I reproduce the steps of the issue, and refresh the page then I have correct font colors and text in the table is so visible.
