### ISSUE TITLE
Frontend stop working after a minute

### ISSUE THREAD

**Issue by Hmarionx** [LuatixHQ/opencti#4701]
## Description

Frontend stop working

## Environment

1. OS Ubuntu 20.04
2. OpenCTI version: 5.11.6
3. OpenCTI client: Frontend
4. Other environment details: Docker compose

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Start the stack, and after one minutes frontend not responding

## Expected Output
-

## Actual Output
-

## Additional information

{"category":"APP","error":{"context":{},"message":"write ECONNRESET","name":"Error","stack":"Error: write ECONNRESET\n    at afterWriteDispatched (node:internal/stream_base_commons:160:15)\n    at writeGeneric (node:internal/stream_base_commons:151:3)\n    at Socket._writeGeneric (node:net:952:11)\n    at Socket._write (node:net:964:8)\n    at writeOrBuffer (node:internal/streams/writable:447:12)\n    at _write (node:internal/streams/writable:389:10)\n    at Socket.Writable.write (node:internal/streams/writable:393:10)\n    at ejt.Tm.sendMethod (/opt/opencti/build/node_modules/amqplib/lib/connection.js:541:17)\n    at send (/opt/opencti/build/node_modules/amqplib/lib/connection.js:181:10)\n    at k (/opt/opencti/build/node_modules/amqplib/lib/connection.js:208:7)\n    at k (/opt/opencti/build/node_modules/amqplib/lib/connection.js:165:32)\n    at cb (/opt/opencti/build/node_modules/amqplib/lib/connection.js:159:12)\n    at Socket.recv (/opt/opencti/build/node_modules/amqplib/lib/connection.js:507:12)\n    at Object.onceWrapper (node:events:628:28)\n    at Socket.emit (node:events:514:28)\n    at emitReadable_ (node:internal/streams/readable:641:12)"},"level":"error","message":"[OPENCTI-MODULE] Import Csv built in connector manager failed to start","timestamp":"2023-10-20T14:01:20.966Z","version":"5.11.6"}

**Comment by SamuelHassine** [comment]
Hello @Hmarionx,

We are working on a fix and we will release a new version as soon as possible (today).

Kind regards,
Samuel
