### ISSUE TITLE
Allow filter incidents by assigned (participants filter is active but not assigned)

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4704]
## Use case

Currently, the incidents table shows assigned Incidents. However, the filter is only available by participants so it is not possible to filter by assigned.

## Current Workaround

Duplicate in participants and assigned the people working on the case. However, this implies a double effort in the assignment to keep the assigned person being shown in the Webui and make it filterable.

At the same time, I guess that participants and assigned people might not be the same. I feel that assigned would be the person that would be working on the incident while participants may involve third parties (e. g., contacts or information providers) who are not part of the investigation.

## Proposed Solution

Make the assigned field searchable in the webui.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

Yes (still need time to deploy a frontend development environment).

**Comment by Jipegien** [comment]
Covered by the new filtering system
