### ISSUE TITLE
Make Entities Status an updatable field

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4705]
## Use case

Analysts might need to automatically reopen an incident which was closed by setting a new Status. This seems not to be doable from the PyCTI since it seems that it is not activated from the GraphQL API.

## Current Workaround

None.

## Proposed Solution

Making the Status something which is updatable from the GraphQL API.

## Additional Information

It would be nice to make it configurable by both, index (or order) and String considering localization.

## If the feature request is approved, would you be willing to submit a PR?

Yes (for PyCTI)

**Comment by nino-filigran** [comment]
@febrezo you can already do this. As a result, I'm closing this ticket.
You need to use the variable `x_opencti_workflow_id` to achieve it.

Here's is a query example that might help you out (done through playground): 
```
mutation ReportEditionOverviewFieldPatchMutation ($reportId: ID!, $input: [EditInput]!){
  reportEdit(id: $reportId) {
    fieldPatch(input: $input) {
      id
      name
      status {
        template {
          name
        }
      }
    }
  }
}

```

With the following variables:
```
{
  "reportId": "idofyourreport",
  "input": {
    "key": "x_opencti_workflow_id",
    "value": "idofyourstatus"
  }
}

```
