### ISSUE TITLE
Error with Default mailer (again). Authentification unsuccessful

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4721]
## Description

I have set up a live trigger on modifying the Report with notification using Default mailer. I specified all the data necessary for smtp in the docker-compose file.
When I change the report to cause the trigger to fire, I see an error in the opencti/platform logs:
![image_2023-10-23_15-32-48](https://github.com/OpenCTI-Platform/opencti/assets/122795003/52faf24d-b533-47dc-82ee-41972bbe8b01)

## Environment

1. OS: Ubuntu 20.04.6 (docker)
2. OpenCTI version: OpenCTI 5.11.8
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Go to Settings -> Security -> Users -> Our_user
2. Add a live trigger to change reports from the user Our_user
3. Set Notifiers=Default mailer
4. Set up a real email for the user Our_user
5. We cause the trigger to fire by modifying the report
6. An error appears in the platform logs, but the message does not arrive by email to the user

## Expected Output

The user receives a notification by email.

## Actual Output

The user does not receive an email notification. An error appears in the logs.

**Comment by SamuelHassine** [comment]
Hello @rattat0r,

It is working well in our cloud environments. Can you please double check your SMTP configuration. The log message seems to be pretty clear about the authentication problem.... Please share the config here as well.

Kind regards,
Samuel

**Comment by rattat0r** [comment]
Hello @SamuelHassine,

The SMTP server is accessible via telnet. The web version of the mail server allows me to log in with my user credentials from the settings

1) Previous settings:

Config:
- SMTP__PORT=25
- SMTP__USE_SSL=false
- SMTP__REJECT_UNAUTHORIZED=false
- SMTP__USERNAME=my-login
- SMTP__PASSWORD=my-password

Error:
Authorization error


2) New settings:

Config:
- SMTP__PORT=465
- SMTP__USE_SSL=true
- SMTP__REJECT_UNAUTHORIZED=false
- SMTP__USERNAME=my-login
- SMTP__PASSWORD=my-password

Error
{
  "category": "APP",
  "error": {
    "context": {},
    "message": "184C9E16CD7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n",
    "name": "Error",
    "stack": "Error: 184C9E16CD7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:\n"
  },
  "level": "error",
  "message": "[OPENCTI-PUBLISHER] Error email publication",
  "timestamp": "2023-10-24T11:28:22.684Z",
  "version": "5.11.8"
}

**Comment by sbocahu** [comment]
Hello @rattat0r, looks like your mail server is not using implicit tls. please test with use_ssl: false so insecure connection will be upgraded to a secure one with STARTTLS (and maybe port 587, see what is supported by your mail server)

**Comment by rattat0r** [comment]
Hello @sbocahu, Thank you very much for your help. It helped to switch to port 587
