### ISSUE TITLE
Empty TAXII collection when "Make this taxii collection public and available to anyone" is disabled

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4726]
## Description

When a TAXII collection is created with "Make this taxii collection public and available to anyone" set to "disabled" and including a group with "data sharing reader" role, the users incuded in this grup can't see the indicators when they access the TAXII collection URL (the collection is empty). However, when the config  "Make this taxii collection public and available to anyone" is set to "enabled", the collection can be seen.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: 5.11.8.
4. Other environment details: OpenCTI instance running in Docker Swarm.

## Expected Output

If the TAXII collection is created with "Make this taxii collection public and available to anyone" set to "disabled" and including a group with "data sharing reader" role, the users incuded in this grup should see the indicators included in the scope of the TAXII collection.

## Screenshots

- Group config:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/07bd89e0-1a25-400f-8265-dc7aeea77619)

- Role config:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/54e8b339-d6f8-4234-90b7-c2d44de2ab84)

- TAXII collection output when the collection is created with "Make this taxii collection public and available to anyone" set to "disabled" and including the group with "data sharing reader" role:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/76f969eb-d570-4a60-a30a-68ed073b3029)

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/044c4374-5c67-4653-9fe9-a4b4a0d3f22b)

**Comment by SamuelHassine** [comment]
Hello @softengsistemas,

In the screenshots, the group is missing marking definition allowed. So if your indicator are even TLP:CLEAR, they will not be able to see them.

Can you pleaser try to set correct "Allowed markings" in your group?

Kind regards,
Samuel
