### ISSUE TITLE
Access to RabbitMQ management console

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4728]
## Description

Can someone explain us how to access to RabbitMQ management console to monitor the ingestion performance of OpenCTI workers? We have deployed OpenCTI using a single docker-compose file in Portainer.

## Environment

1. OS (where OpenCTI server runs): Ubunru 20.04.
2. OpenCTI version: 5.11.8.

**Comment by Hmarionx** [comment]
Hello,

You can use the [rabbitmqctl](https://www.rabbitmq.com/rabbitmqctl.8.html) in the container, simply docker exec -it <id> /bin/sh
You can also expose the web console port to access it

**Comment by softengsistemas** [comment]
Hello @Hmarionx,

Could you tell me what ports do I have to publish? I've published the ports 15672 and 5672 in RabbitMQ container but I can't connect through web browser:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/a33db07f-48b8-483a-bafd-e63e8ed338d4)

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/34775aaf-1e67-4290-90d8-467de079e13b)

Thanks.

**Comment by Hmarionx** [comment]
Port 15672 is enough for me. Perhaps you have specific network setup.
First, try to docker inspect the rabbit container and connect your browser directly to the container IP with port 15672
