### ISSUE TITLE
"All threats" filter missing on Areas object

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4730]
[Platform harmonization] In the "Knowledge" tab of the "Areas" objects, the "All threats" filter available on all other Location objects is missing.

<img width="962" alt="Screenshot 2023-10-24 161458" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/fb11c0a1-f413-47bf-99b1-1a301392601d">
<img width="962" alt="Screenshot 2023-10-24 161503" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/59d169cb-6c75-47d0-8a31-f0aead47340f">

**Comment by yassine-ouaamou** [comment]
I believe it is more of a feature.

@Jipegien @Lhorus6 @nino-filigran Which relationships/entities should be included in "All threats"?
For instance, in country, we include all entities having "targets" relation with the country but this excludes Intrusion sets and campaigns as they are linked through "orginiates-from".

Let's discuss about this
