### ISSUE TITLE
Permit to edit the revoked attribute on Threat actors, Intrusion Sets and Campaigns

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4736]
## Description

Unless I'm mistaken, the `Revoked` attribute cannot be edited in the UI. I guess that it is not the expected usage.

## Environment

1. Docker
2. OpenCTI 5.11.2
4. Frontend
5. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on Threat Actor
2. Check Revoked state
3. Try to edit

## Expected Output

An optional field that allows to edit that attribute.

## Actual Output

No attribute edit field.

## Additional information

We currently set the revoke status with a specific label.

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/1590496/75d6bf12-f9c6-4a31-8dbf-6454240402f9)

**Comment by SarahBocognano** [comment]
Hello @febrezo , Thanks for your contribution. We've created a feature issue for this subject. You can track it here : https://github.com/OpenCTI-Platform/opencti/issues/4749
