### ISSUE TITLE
Add the possibility of merging labels

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4737]
## Use case

Sometimes several sources may provide similar but different labels such as `ddos attack`, `ddos-attack`, etc. It would be nice to be able to merge them. It cannot be done from the web UI.

## Current Workaround

Bulk select the entities with a specific label, add the final label. Bulk select the entities with the old label and remove it.

## Proposed Solution

Add a similar button in the label administration system to merge the labels too as happens with other entities.

## Additional Information

N/A.

## If the feature request is approved, would you be willing to submit a PR?

Yes.

**Comment by SamuelHassine** [comment]
Duplicate of #4737.

**Comment by febrezo** [comment]
Great, saw that. A minor comment since the issue in which it is being tracked is #3473.
