### ISSUE TITLE
Add a label normalization rule engine

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4738]
## Use case

Sometimes several sources may provide similar but different labels such as `cobalt strike`, `cobalt-strike`, `cobalt strike`, `cobaltstrike`, etc. It would be nice to have a normalization label engine that would let analysts to provide specific merging rules to convert any set of labels to a specific one whenever a not normalized label is ingested.

## Current Workaround

Periodically perform the manual task of bulk deleting old labels, and bulk adding normalized ones.

## Proposed Solution

Provide a simple web UI that would let analyst to provide a target label (i. e., `cobalt-strike`) in a textfield for example and a set of labels that would be converted to the target label. These labels could be set in a text area, one per line. 

A ridiculous mockup of what is in my mind would be sth like this:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1590496/bf1205e9-d1e5-4d28-af72-fc315b670f0e)

## Additional Information

This would imply adding some steps in the ingestion process to control if a proposed new label is already registered as a label that needs to be converted to apply the rules before it gets created into the platform. It also would be interesting to delete old labels to prevent them from being accidentally added by analysts in the UI.

## If the feature request is approved, would you be willing to submit a PR?

N/A

**Comment by nino-filigran** [comment]
@febrezo we are planning to work on something similar, see this ticket: https://github.com/OpenCTI-Platform/opencti/issues/3473
