### ISSUE TITLE
Connectors ingestion performance issues

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4748]
Hello,

We are finding some performance troubles when the connectors try to ingest thousands of entities in OpenCTI instance. For example, we have configured the AlienVault connector ant the ingestion process of 2 millions of entities is in stuck:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/4b65aced-d822-431a-9827-e05ea377fa6f)

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/2fa1dc53-5ca3-474d-9c87-bd7bc22993c3)

The process of ingestion is very slow and if we connect to the RabbitMQ admin console, we can see that the message are in stuck with a slow ratio of ingestion:

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/1e610ee0-f027-4fe1-94aa-dbb6a7bc943e)

Can someone help me to speed up the ingestion process?

Thanks,
Softeng team

**Comment by ckane** [comment]
Which version of OpenCTI do you have installed?

**Comment by softengsistemas** [comment]
Sorry. Last version, 5.11.9, but this problem has remained in all old versions.

**Comment by ckane** [comment]
5.11.10 was just released this morning with some fixes that seem to address a problem I had last night that was very similar to what you've described, so I'd recommend trying that and seeing if it helps.
