### ISSUE TITLE
Since version 5.11 backend is really unstable and stop working, even in 5.11.10 version

### ISSUE THREAD

**Issue by Hmarionx** [LuatixHQ/opencti#4759]
## Description

Version 5.11.10 is still unstable, despite numerous commits. The backend runs for a few minutes before stopping and disconnecting from the rabbit without being able to reconnect.
Note that version 5.11.10 no longer provides logs

## Environment

1. OS Ubuntu 20.04
2. v5.11.10
4. OpenCTI client: backend
5. Other environment details: docker-compose deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Just start the stack and wait for the backend to consume bundle for a few minutes

## Actual Output

backend stop working

## Additional information

No logs available in 5.11.10

**Comment by SamuelHassine** [comment]
Hello @Hmarionx,

Without further information it is difficult to do something. For the moment feedback and cloud instances are stable we don't plan to do more.

Can you join the Slack channel?

Kind regards,
Samuel

**Comment by Hmarionx** [comment]
Okay, perhaps my setup is bad. I"ll join the Slack and you can close this issue.
