### ISSUE TITLE
Timeouts When Accessing Various Pages

### ISSUE THREAD

**Issue by YungBinary** [LuatixHQ/opencti#4762]
## Description

We are having a new issue with certain pages timing out with 504 response and the message "An unknown error occurred. Please contact your administrator or the OpenCTI maintainers." Is there any way to make this error message less ambiguous?

This happens only at the following URLs:

```
/dashboard/data/connectors
/dashboard/settings
```

## Environment

1. OS (where OpenCTI server runs): ECS
2. OpenCTI version: 5.11.10

**Comment by SouadHadjiat** [comment]
Hello @YungBinary,
Could you share your OpenCTI server logs ?

**Comment by leetn00b** [comment]
@SouadHadjiat Forgive me for the late response, this is my second account. This is still happening as of 5.12.33. Nothing is printed to logs related to this issue. It is a timeout to the graphql endpoint.

Screenshot (504 response)

![Screenshot 2024-02-23 at 5 53 47 PM](https://github.com/OpenCTI-Platform/opencti/assets/91347619/0ff60ebd-047f-48fa-addd-a2e12c30b0b8)

**Comment by leetn00b** [comment]
This has been resolved. Ended up being a missing security group ingress rule for port 15671 to the rabbitmq security group.

**Comment by SouadHadjiat** [comment]
Closing the issue as a won't fix then. Thanks for the update !
