### ISSUE TITLE
CSV import does not create a Workbench

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4764]
## Description

CSV import does not create a Workbench

## Environment

5.11.11

## Reproducible Steps

1. Create a CSV mapper suitable for the file
2. Import the CSV file
3. Choose the CSV import connector and the mapper created
4. Wait for the import connector to finish loading
5. No workbench appears

## Screenshots

<img width="1721" alt="Screenshot 2023-10-26 085237" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/6a4e984e-33b2-4558-8665-ca220d967d70">

**Comment by SamuelHassine** [comment]
This is a feature requests to be able to turn the CSV importer in "validate before import" mode.

**Comment by Lhorus6** [comment]
In the platform's import-csv manager configuration, I see an "import_csv_built_in_connector:validate_before_import" parameter. 

- Isn't this intended to generate a workbench?
- If so, can we close this issue?
- If not, what is the purpose of this parameter?

![image](https://github.com/OpenCTI-Platform/opencti/assets/70956706/c8353624-5def-4b68-83a1-be5cecda9f65)

cf https://docs.opencti.io/latest/deployment/configuration/#engines-schedules-and-managers

**Comment by Lhorus6** [comment]
"Isn't this intended to generate a workbench?" -> Yes it is

Issue resolved
