### ISSUE TITLE
Display a "By Filigran" logo on login page and on all pages of the app 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#4765]
## Use case

Ability for our comminutiy users to clearly see that Filigran developped the tool and for Entreprise Edition users to remove it, in order to easily create a whitelabled solution
## Proposed Solution

Add a Filigran logo on the login page and on all pages of the app.
Create a toogle within settings to remove this logo (only avaiable to Entreprise Edition users).

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Kedae** [comment]
Additonnally it will also include the support of the new EE branding in the platform to allow user to know which features are under EE.

It will only lacks the messaging and call to action that are currently under development.
