### ISSUE TITLE
Redact credentials for ingestion (password and private keys) of ingester in the audit logging

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4770]
## Use case

Redact credentials for ingestion RSS / TAXII / Remote OCTI sync (password, token and private keys) of ingester in the audit logging

**Comment by nino-filigran** [comment]
@SamuelHassine I have a few question: 
- are they in clear at the moment? And are they the only ones that we store in the logs in clear? Yes (and in UI)
- does it mean that we always need to "mask" them through this REDACT ?
- can it be at the hand of the user to chose whether or not they want to have them in clear?
- the output in the logs would something like "username: ((redact))" right?

**Comment by SamuelHassine** [comment]
@nino-filigran Please schedule a meeting to discuss this one.

**Comment by nino-filigran** [comment]
We already discussed it a while ago (we have some specs attached internally). Do you still want to discuss this? Because for me at least, the need is clear, unless it changed

**Comment by nino-filigran** [comment]
This has been done but not closed ![Image](https://github.com/user-attachments/assets/e4f7a6a8-4021-411e-81b5-5615f0cca0b5)
