### ISSUE TITLE
Incorrect relationship counter

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4771]
## Description

In the knowledge view (at least in my example, see screenshot) the counter of relation is incorrect. I assume that a related entity type is not taken into account (I'd put my money on the System)

## Environment

5.11.11

## Screenshots

<img width="842" alt="Incorrect_counter" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/4458992e-a2e6-4120-8e70-231cf9e3511f">

**Comment by SouadHadjiat** [comment]
@Lhorus6 Could you give more details on the relationship between your organization and the System ?

**Comment by Lhorus6** [comment]
After several attempts, I was unable to reproduce it.
We can close this issue.
