### ISSUE TITLE
Investigation graph dezoom and loses the entity

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4776]
## Description

When a single element is added to a new investigation graph, a dezoome occurs until the entity is lost.

Note: 
1. The graph is unzoomed when the side window for adding an entity is closed. If you put the mouse in the middle of the screen and scroll to zoom in, with a bit of chance, you can find the entity again.
2. This also happens if you add an entity to an empty graph in a "Knowledge" tab (in a report, for example).

## Environment

5.11.11

## Reproducible Steps

1. Create an investigation
2. Add a single entity (an intrusion set, for example)
3. Remove the lateral window used to add entities to return to the investigation graph.
4. You will see the graph zoom out until you lose the entity.

## Additional idea

A button for grouping entities and refocusing the view on them would be a good addition.

**Comment by SamuelHassine** [comment]
Not able to reproduce either on Chrome or Edge, zoom is well adjusted. Maybe a screen size issue?
