### ISSUE TITLE
Add the possibility of filter by no participant

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#4777]
## Use case

Filter incidents which have not been assigned to anyone.

## Current Workaround

N/F.

## Proposed Solution

Add no assignation as an option.

## Additional Information

N/A.

## If the feature request is approved, would you be willing to submit a PR?

N/A.

**Comment by nino-filigran** [comment]
@febrezo you can now filter on incidents using the attribute "participant" with the operator "is empty" (since 5.12).
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/654b2ae4-123b-458b-a3dc-0eb0c35b10bb)
