### ISSUE TITLE
Let MINIO__USE_AWS_ROLE use defaultProvider for AWS EKS hosted OpenCTI

### ISSUE THREAD

**Issue by RyanOchieng** [LuatixHQ/opencti#4784]
## Description

Setting MINIO__USE_AWS_ROLE environment variable to true causes platform pod to fail starting, throwing a "could not load credentials from any providers"

## Environment

1. OS (where OpenCTI server runs): AWS EKS
2. OpenCTI version: 5.11.11
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Deploy OpenCTI to an AWS EKS cluster, having set MINIO__USE_AWS_ROLE to true
2. Check logs for platform container - this returns error "could not load credentials from any providers"

## Expected Output

Platform should launch correctly, having assumed credentials from the attached ServiceAccount role, and should be able to upload files to S3

## Actual Output

Platform fails to start, throwing error "could not load credentials from any providers"

## Additional information

I have confirmed my ServiceAccount is correctly attached to the pod that the platform container is running on and has the correct permissions. I have checked file-storage.js ( /src/database/ ) and it appears that it uses `remoteProvider` from the AWS SDK. This should be changed to `defaultProvider` as the former is referenced in the latter and should not break functionality for workloads hosted in ECS and EC2. Workloads that require AWS credentials gain this via an attached ServiceAccount, and a token file is mounted to the pod. I have tested changing to `defaultProvider` and have had success, therefore I can confirm that this should be the fix adopted for this issue. See below link for context on defaultProvider

https://github.com/aws/aws-sdk-js-v3/blob/ba83d46690522a0a18094d7cd72d95724c95177b/packages/credential-provider-node/src/defaultProvider.ts

**Comment by richard-julien** [comment]
We are not able to test ourself this but I will trust you on the solution :)
So I will add an option in to select the provider you need
