### ISSUE TITLE
Sources for observables

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4785]
## Use case
We'd like to categorize the origin of an observable and event. We gather observables and events from multiple sources like commercial ti streams, open ti streams, web crawling, deep and dark web crawling, social media, ...
Therefore it would be very beneficial to somehow store the source of the entity.

## Current Workaround
A combination of author and labels. E.g. Author Dark Web Crawler, Label source:russianmarket.

## Proposed Solution
Allow to add sources to entities. The source should be a separate entity type (or role, like described in #4757).

## Additional context
The current solution of "voting" for reliability only works at small scale because if you have e.g. 100k ingestions / day no company is capable to analyze this with personnel efforts. Therefore a pre categorization of the sources could help to further analyze the entities with AI and then only give the rest that have to be verified to the real analysts.  

## If the feature request is approved, would you be willing to submit a PR?
Yes

**Comment by Jipegien** [comment]
You have already multiple elements that can be used a source of an Object in the platform:
- technical creator : the technical source of the creation of the Object in the platform. For example a dedicated connector for your Dark Web crawler
- Author : a "functional" source, at the discretion of the technical creator. Could be anything, like russianmarket
- External references : a web ressource sourcing the Object details
- Label : as labels can serve to store any unstructured metadata. 

Currently, the fact that something is a "source" is modelized as a relation (between the Object and its Author, etc.). 

I don't really see the benefits to create a specific "Source" entity type. Can you precise the need?

**Comment by nino-filigran** [comment]
Given the inactivity on the ticket, I'm closing it for now. @iFrozenPhoenix if you think our response is not satisfactory or if you have any other comment, please feel free to re-open the ticket. We'll be happy to take it from there.
