### ISSUE TITLE
Playbooks don't work correctly

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4786]
## Description

"Listen knowledge events" does not work.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.11.11
3. OpenCTI client: frontend

## Reproducible Steps

1. Create playbook with filters: 
- Observable type: Url
- Entity type: Observable
2. Enable the "Creation events" and "Modification events" checkboxes  (*screenshot 1*)
3. And for example add "Send user notification"  (*screenshot 2*) with:
- Notifiers: User interface
- Targets: Default
4. Start the playbook
5. Create an observable Url and modify it  (*screenshot 4*)
6. Look that nothing appeared in "Last execution traces"  (*screenshot 5*)

## Expected Output

Executed playbooks are displayed in "Last execution traces".

## Actual Output

Executed playbooks are not displayed in "Last execution traces".

## Screenshots (optional)

![image_2023-10-27_09-58-19](https://github.com/OpenCTI-Platform/opencti/assets/122795003/21462663-a534-40aa-9ac8-c517f903cf7a)

![image_2023-10-27_10-17-54](https://github.com/OpenCTI-Platform/opencti/assets/122795003/9c40ee88-9c9c-436c-96a1-191ea2e28b44)

![image_2023-10-27_10-00-10](https://github.com/OpenCTI-Platform/opencti/assets/122795003/ba180e63-84b5-4e1a-9db0-b5a74f44e33e)

![image_2023-10-27_10-23-13](https://github.com/OpenCTI-Platform/opencti/assets/122795003/4d6c7c13-ed66-4261-b6fb-f89b4997f46e)

![image_2023-10-27_10-27-18](https://github.com/OpenCTI-Platform/opencti/assets/122795003/6bccb323-6cb5-4f36-8997-7c6b20eef9a2)

**Comment by SamuelHassine** [comment]
Hello @rattat0r,

Your filter is not correct.

Use: Entity type: URL

Observable type is linked to Indicator main observable type.

**Comment by rattat0r** [comment]
Hello, @SamuelHassine, thanks for the answer.
I changed the filter according to your advice and added the VirusTotal connector for enrichment. But the VirusTotal connector produces errors:
{
  "timestamp": "2023-10-27T09:53:52.451967Z",
  "level": "ERROR",
  "name": "pycti.connector",
  "message": "Error in message processing, reporting error to API",
  "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 279, in _data_handler\n    message = self.callback(json_data[\"event\"])\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 388, in _process_message\n    return self._process_url(stix_objects, stix_entity, opencti_entity)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-virustotal/virustotal/virustotal.py\", line 348, in _process_url\n    return builder.send_bundle()\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-virustotal/virustotal/builder.py\", line 450, in send_bundle\n    bundles_sent = self.helper.send_stix2_bundle(serialized_bundle)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py\", line 963, in send_stix2_bundle\n    self.api.playbook.playbook_step_execution(self.playbook, bundle)\n  File \"/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_playbook.py\", line 17, in playbook_step_execution\n    self.api.query(\n  File \"/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py\", line 365, in query\n    raise ValueError(\nValueError: {'name': 'ForbiddenAccess', 'message': 'You are not allowed to do this.'}"
}

**Comment by rattat0r** [comment]
When I run the enrichment myself, everything works fine. The error only occurs when running enrichment via Playbook. Other internal enrichment connectors also cause errors when run through Playbook.

**Comment by SamuelHassine** [comment]
Thanks @rattat0r. Will fix this.
