### ISSUE TITLE
Infinite loading is broken on create relationships since new drawer

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4792]
## Description

Infinite loading is broken on create relationships since new drawer.

## Reproducible Steps

1. Go to an Intrusion Set or a Campaign
2. Go to Knowledge
3. Go to Indicator in the right menu
4. Click on "+"
5. Scroll

## Expected Output

Infinite loading is working due to parent div container correctly set.

## Actual Output

No infinite loading.

## Additional requests

When addressing this bug, please also increase a little the left padding of the checkboxes (too close to the border of the drawer):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/3eece884-d1a7-46e3-a377-9a433af31999)

**Comment by labo-flg** [comment]
I've not found yet the source of the problem.

FYI workaround is to use the search bar that still works correctly.

**Comment by labo-flg** [comment]
Ok so I've fixed the padding, that's something I guess 😅

For the scrolling issue, here is our current analysis:
* in `ListLineContent`, the `<WindowScroller>` expects the right `ref` to listen to scroll events
* it works fine in the context of a plain page, the scrolling being on `window`
* in the context of a drawer, we set a ref on the `<Drawer>`  at `StixCoreRelationshipCreationFromEntity.jsx` and use it in the `<WindowScroller>`, but it won't work
* the scrolling is actually handled deep inside the MUI drawer, the ref on the root element is not the right one

**Comment by labo-flg** [comment]
I've hacked my way around the issue by setting the reference we give to the ListLinesContent [here](https://github.com/OpenCTI-Platform/opencti/blob/ec29c9fc387f35d94eb4c13ad428207a56de1c2e/opencti-platform/opencti-front/src/private/components/common/stix_core_relationships/StixCoreRelationshipCreationFromEntity.jsx#L780) to the `parentElement` of the very first child set inside the Drawer.

```diff
- <div style={{ minHeight: '100%' }}>
+  <div
+    style={{ minHeight: '100%' }}
+    ref={(ref) => {
+      if (ref) {
+        containerRef.current = ref.parentElement;
+      }
+    }}
+  >
``` 

This targets the right element, the one that actually scrolls. Then the List and everything works fine.
I'm pushing a PR.

**Comment by labo-flg** [comment]
Even better using MUI drawer `SlideProps` 😇
