### ISSUE TITLE
Open vocab severity / priority filters are displaying only used attributes

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4799]
## Description

Open vocab priority filter is displaying only used attributes.

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/b3ac1eee-bd9d-4518-8b90-c57d3285224c)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

1. Ensure to not have any incident with priority p1
2. p1 is never displayed in filters (on triggers, automation, etc.)

## Expected Output

All the list is available.

**Comment by Kedae** [comment]
@SamuelHassine I think we need to discuss that because ATM severity can be either "case" severity or incident. Both are a different vocabulary, and I don't think we want to mix them within the same filter.

**Comment by SamuelHassine** [comment]
Ok @Kedae but this is a problem for all stored filters and priority / severity are the most used filters in triggers and playbooks.

**Comment by Kedae** [comment]
Duplicate of #3585
