### ISSUE TITLE
Avoid upserting an filled attribute with something null

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4804]
## Description

The connector correctly adds Intrusion set information to the import. However, for some Intrusion sets, it deletes the description afterwards. The description is still on the CrowdStrike portal, so I don't know if this is a bug in the connector or if it is caused by an action by CrowdStrike that needs to be managed by the connector.

## Screenshots

<img width="780" alt="History_tab" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/00adff3a-03d6-40ae-8cca-1ca28ed90abd">

**Comment by SamuelHassine** [comment]
Hello,

Feature request to avoid upsert when replacing an attribute wich is filled by something empty. As we have in the other direction to fill any empty attribute even if the confidence level is below.
