### ISSUE TITLE
Map with CSV mapper a file containing columns sha1, sha256, md5, sha-512

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4806]
## Use case

Expand the ability to load different types of hashes in relation to one Observable File in CSV Mapper.

## Current Workaround

At this moment you can select only one column for the hashes field for the File entity type.

## Proposed Solution

Add the ability to select a column for the field MD5, SHA1, SHA256, so that one line of a CSV file belongs to one Observable File.

## Screenshots

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/81b72a36-8616-49a4-a6cc-0fe39ccfab0a)

**Comment by securitiz** [comment]
Checking in on this - is this on the roadmap? This is a key feature of the CSV ingest, as most CSVs with files break out MD5, SHA1, SHA256 into their own columns @Jipegien

**Comment by Jipegien** [comment]
We will try and do this in 5.13.
