### ISSUE TITLE
Select All Marking Definitions in Groups

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#4808]
## Use case

Have the ability to select all Marking Definitions at once.

## Current Workaround

Selecting each individual marking, this can be very time consuming when there are hundreds of markings.

## Proposed Solution

Add selectable box that checks all available Marking Definitions under groups in security.

## Additional Information

No additional information

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
Hey there, as you can see in the follwoing issue, this needs will be adressed soon: https://github.com/OpenCTI-Platform/opencti/issues/2747 

Let us know if you any further questions.
