### ISSUE TITLE
Empty TAXII Ingester User Reverts to Previous User instead of System

### ISSUE THREAD

**Issue by zhanttt** [LuatixHQ/opencti#4813]
## Description

The "User responsible for data creation (empty = System)" reverts to the previously set user when changing the field blank. There doesn't appear to be a way to set the User back to "System".

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 5.11.12
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a TAXII Ingester. Set the user to an existing user. 
2. Click Update
3. Set the user field to blank and hit the "X" to close the UI element
4. Hit Update again to view the User field and notice that the value is no longer blank or set to System. It is the previous user.

## Expected Output

When the User field is blank, the value becomes System.

## Actual Output

The User field becomes the previous user value.

## Screenshots (optional)
Changing value to empty:
<img width="299" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/71095260/e7d775d9-69cd-4c26-8bb3-b593943ec06f">

Value after change (reverted to previous user "admin"):
<img width="209" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/71095260/76456f3a-a5ec-411d-a9eb-4fa76f2693bd">

**Comment by helene-nguyen** [comment]
Hi @zhantt1,

I open a PR to fix it, you can follow it on the link below:

https://github.com/OpenCTI-Platform/opencti/pull/4834
