### ISSUE TITLE
Taxonomies Importing & Exporting

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#4820]
## Use case

Add the ability to import and export Taxonomies - Vocabularies.

## Current Workaround

Manually enter into OpenCTI prior to data import .

## Proposed Solution

Have the ability to import and export vocabularies to help expedite future data installations and extractions.

## Additional Information

If taxonomies - vocabularies are not entered prior to data importation unrecognized property values are stripped from the data.

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by Jipegien** [comment]
Can you verify that the the open vocabularies are stripped from the data when importing? It should not.

**Comment by explorecti** [comment]
Closing for a feature request after further investigation.
