### ISSUE TITLE
Include "Analyses" Column in Knowledge section for each object

### ISSUE THREAD

**Issue by securitiz** [LuatixHQ/opencti#4825]
## Use case

It's useful to know how many times a relationship between two objects has been observed. This would be visible in the Knowledge page, in the context of a specific object, see screenshots below. For example:

In the context of a threat actor, it's very useful to know how many times we've observed
1) a direct relationship to each each associated Tool, Attack Pattern, etc:
2) an analysis (Case, Report etc) that contains each of the two objects (regardless of if they are related.

2 Is important because we may have 5 instances / reports that reference BlackCat using AnyDesk, but each report represents the same relationship. But we want to know that it's been observed 5 times. 

## Current Workaround

Investigations view, perhaps? Unclear if there is one

## Proposed Solution

An extra column (or two) representing the above two integers.

## Additional Information

![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/a4d28ff1-6e2b-4dfb-bb6d-0500bfa9c52a)

![image](https://github.com/OpenCTI-Platform/opencti/assets/78382789/0df4bbc7-c670-4258-abe2-c5218a539d61)

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
You can see how many time two Entities are related to each other here : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/faed1d77-274c-45c3-8ec4-fa75a76a4cce)
In the screenshot, the Threat actor has 2 relationships "uses" reported for the Malware SpaceColon. If you click on the line, you will see the details of the relationship and any container (for example a report) containing the relation.
