### ISSUE TITLE
Some entities are not accessible: Error

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4826]
## Description

Two Intrusion sets (and potentially others) are not accessible. When I click on them to open their page, an error appears (see screenshot).
The Knowledge, Analyses, etc. tabs produce the same error

## Environment

OpenCTI 5.11.12

## Screenshots

<img width="1713" alt="Screenshot 2023-11-01 104621" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/6cf5c2b4-efda-4cdb-a29a-63725f393312">
<img width="1716" alt="Screenshot 2023-11-01 104740" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/99328436-0335-408e-a5c4-22c9dfb17621">

**Comment by SarahBocognano** [comment]
It's working on my instance. What is a particular intrusion set ?

**Comment by Kedae** [comment]
Look a lot like https://github.com/OpenCTI-Platform/opencti/issues/4553

**Comment by richard-julien** [comment]
@Lhorus6 , any more info?

**Comment by richard-julien** [comment]
Closed as it was originated from data inconsistency
