### ISSUE TITLE
Investigation Entity Display

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#4827]
## Description

When attempting to add a new entity for a newly created investigation the single entity does not show. If you to add a second entity then it will show on the investigations.

## Environment

1. OS version: CENTOS 7.9
2. OpenCTI version: 5.11.11
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new investigation
2. Select newly created investigation and select a single entity, then exit

## Expected Output

The investigation should show the single selected entity.

## Actual Output

The UI doesn't show the single entity selected.

**Comment by SarahBocognano** [comment]
I didn't succeed to reproduce the bug, it's working fine on my instance. Do you have more information to give me to try to reproduce exactly?

**Comment by explorecti** [comment]
Are you using version 5.11.11? I have 5 instances running and they are all having the same issue.

**Comment by marieflorescontact** [comment]
I can't reproduce either on my side.

**Comment by SouadHadjiat** [comment]
Which browser are you using ? Could you try another browser to see if you reproduce this issue ? @explorecti

**Comment by explorecti** [comment]
I tried another browser and it still doesn't display the single object. Now if I select a single object, then click 3D on the footer toolbar the single object appears.

**Comment by SouadHadjiat** [comment]
Hello @explorecti,
Could you send screenshots to have a better understanding of the issue you have ? or a small video if possible ?

Thanks

**Comment by explorecti** [comment]
This has been resolved by one of the recent releases. We updated from 5.11.11 to 5.11.14 and do not see the display issue anymore. Thank you.
