### ISSUE TITLE
Add threat actor location: can't create a location + bad design

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4832]
- Go to the overview of a threat actor group.
- Add a location 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/ac37fc5f-f4ed-43bf-8105-818a9d9c57c9)

- The header design of the add location panel is not correct 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3650b118-ac19-4f0c-8197-7485139ebc46)

- We can't create a location from this place (the 'add' pink button is missing).

**Comment by SarahBocognano** [comment]
I don't think we want the pink "create button" on the Add Location Panel. It is also not the case in Intrusion Set. What should I do @Jipegien ?

**Comment by Jipegien** [comment]
Add the creation button. Threat actor(group), threat actor(individual) and Intrusion set panel.
Fix the position of the search bar.
Add french translation for located at.
