### ISSUE TITLE
Prevent live stream cyclic resolutions on relation dependencies

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4840]
## Description

Some filters in the live stream don't work -> the live stream becomes empty. After several tests, here's what I found:

- Entity type : Report -> feed empty (but Entity type : Indicator works)
- Label : [Any] -> feed empty (I tested several labels, the live stream was always empty)
- Marking definition : TLP:AMBER -> feed empty (but Marking definition:TLP:CLEAR works)

nb: I only tested a few filters, there's a good chance that others will produce the same effect

## Environment

OpenCTI 5.11.12

## Reproducible Steps

1. Create a Live Stream
2. Use one of the filter which I noted as not working in the description
3. Look inside the stream (with the parameter "?from=0-0&recover2023/11/03") -> the stream will be empty

**Comment by labo-flg** [comment]
Thanks for your feedback 🙌
Without the parameter `?from=0-0&recover2023/11/03` it seems to work fine (having events in stream when I update a report for instance). Can you confirm on your side please ?

**Comment by SamuelHassine** [comment]
@Lhorus6 please talk to @richard-julien. Your parameters are definitely not correctly formatted.

**Comment by Lhorus6** [comment]
I made a mistake in my message by forgetting one "=" (a mistake I didn't make in my url). Here is the parameter used : `?from=0-0&recover=2023/11/03` as it can be seen at the end of the documentation page here : https://docs.opencti.io/latest/reference/streaming
I also tried without this parameter, it didn't work either.
Ok Samuel, I will talk with Julien 👍
