### ISSUE TITLE
"Merge" icon appears in the "Labels" panel

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4844]
## Description

In the "Settings > Taxonomies > Labels" window, when you select all the labels, the "Merge" icon appears. NB: It's greyed out, which is normal because the feature doesn't exist at the moment. 

It only appears when a very large number of labels are selected apparently (when only a few labels are selected, it doesn't appear).

## Environment

OpenCTI 5.11.12

## Screenshots

<img width="1713" alt="Screenshot 2023-11-03 151036" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/70f92d43-6f17-4928-864f-f7e66746a8aa">
<img width="1711" alt="Screenshot 2023-11-03 151046" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/71e4442d-e8a9-4949-84a7-ddb20822f486">

**Comment by jpkha** [comment]
Here is the condition to display or not the icon.
```
 const typesAreNotMergable = R.includes(
      R.uniq(R.map((o) => o.entity_type, R.values(selectedElements || {})))[0],
      notMergableTypes,
    );
   ```
   
The icon is displayed when this checkbox is checked :
  
![image](https://github.com/OpenCTI-Platform/opencti/assets/18297909/4d960f5f-0b84-4df1-b618-2b8655fc28f3)

**Comment by SamuelHassine** [comment]
Hello,

Not really a bug. Do not spend time on this as it will be solved by : https://github.com/OpenCTI-Platform/opencti/issues/3473.
