### ISSUE TITLE
One Organisation on my platform can no longer be added as an "Author"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4845]
## Description

One Organisation on my platform can no longer be added as an "Author". Let me explain: 

- An Organization called X is present on my platform
- I can find it in the "Organization" menu
- I can create relationships with it
- ... nothing unusual so far

but when I look for it in the "Author" drop-down menu (when creating a report, for example), it's nowhere to be found.

Ask me for more information

## Environment

OpenCTI 5.11.12

**Comment by labo-flg** [comment]
I've tried to reproduce this issue on OCTI latest version (5.11.12), without success so far.

Here's what I do :
* in entities, organizations, I create a new organisation
* In analyses, report, I create a new report
* In field Author, I correctly find my new organisation when I type its name
* Same when I try to edit an existing report, I find my new organisation in the author dropdown.

Do you have a specific config or parameters that might get in the way somehow?

**Comment by Lhorus6** [comment]
It cannot be reproduced. It's a bug that happens unexpectedly. It used to be possible to find this Organization, but now it's not, for no apparent reason. I remember encountering the same bug a long time ago (on a completely different OpenCTI instance and a different Organization).

**Comment by Lhorus6** [comment]
**Initial condition:**
- An Organization A is present on my platform
- This Organization A has the alias "BBB".

**Here are the tests performed during report creation:**
- I search in author "A" -> nothing appears
- I search in author "BBB" -> nothing appears (normal, searching for authors by their alias does not seem to be implemented in this field)
- I search for author "BBB", I wait, then I search for "A" -> my Ogranization appears...
- I change the name from "A" to "Aa", I search in author "Aa" -> I find my Organization
- I change the name of my Organization from "Aa" to "A" (the original name) -> the problem reappears...
