### ISSUE TITLE
Product instead of Software in observables

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#4851]
## Use case
The Software observable provides the capability to add a CPE and can be linked to a vulnerability. But also hardware can have vulnerabilities. Therefore the Cyber Security community almost completely agreed on the term Product instead of Software.
This would allow to also correctly link products like intel or amd cpus to vulnerabilities (e.g. heartbleed).

## Current Workaround
Define also hardware products as software, which is by term incorrect.

## Proposed Solution
Rename software in product and add a type field (Taxonomie). 

## If the feature request is approved, would you be willing to submit a PR?
Yes

**Comment by Jipegien** [comment]
Hello and thank you! :)  We need to be compliant with STIX 2.1 so we won't change the Software SCO. 

Can an "hardware" vulnerability be something else than a vulnerability affecting its firmware ? Because I think considering firmware as software (even if not exactly true) is less problematic.

**Comment by ghost** [comment]
@Jipegien indeed hardware vulnerabilities doesn't need to be related to firmware, e.g. early AMD EPYC cpus had a vulnerability where SEV could be bypassed by manipulating the voltage.

**Comment by ghost** [comment]
@Jipegien just an additional hint concerning stix compatibility. I think stix compatibility should not be given in that sense that everything is everywhere in the storage backend represented as stix objects but should be given during import / ingestion and export.

**Comment by Jipegien** [comment]
@iFrozenPhoenix Ok I get it for the hardware vulnerability. But I think it is clearly not so common. As I said, we won't modify the Software SCO, but we could add an Hardware SCO. 
Another workaround might be to use the "infrastructure" Object to represent your hardware and link it to a vulnerability with the "has" SRO.

**Comment by Jipegien** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/4905
