### ISSUE TITLE
Containers, Entities and Relationships not correctly created upon Analyst Workbench validation

### ISSUE THREAD

**Issue by kcg-gh** [LuatixHQ/opencti#4857]
## Description

When using the Analyst Workbench function, once the entities that did not previously exist are validated, they are created in the platform and the container is also created, for example a Report if one has been indicated. However, when accessing the report, the entities do not appear associated to the report and within the Knowledge tab, in the Mapping view, what has been previously added to the "Content" section is not saved either.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add entities, relationships and containers in the Analyst Workbench.
2. Validate the Analyst Workbench (No errors throwed)
3. Report created does not contain entities, relationships or other fields filled during the Analyst Workbench.

## Expected Output

A report with the entities and their relationships already linked, as well as the information entered during the Analyst Workbench stored and visible in the Knowledge tab.

## Actual Output

Report and entities created separately, without any linkage. Additionally, the "Content" section of the report is not populated with what was filled in during creation in the Analyst Workbench.

**Comment by SouadHadjiat** [comment]
Hello @kcg-gh 
Thank you for the bug report. Do you add the entities in the context of the report in the analyst workbench ?
Like this : 

![Capture d'écran 2023-11-07 152759](https://github.com/OpenCTI-Platform/opencti/assets/668192/636acdb6-1d54-4c4d-bff1-134f0ad36627)

If you don't select the entities in the report context, it won't be added in the report.

**Comment by kcg-gh** [comment]
Hi @SouadHadjiat ,

No, I add them in the Entities and Relationship tab. If in order to link them to the report I have to create them inside the context of the reports that fine.

I guess the "new test campaign" entity was added first in the Entities tab and then added into the Container's context, right?

The only matter left would be the report "Content" being lost upon validation.

Thank you very much for your prompt response.

**Comment by SouadHadjiat** [comment]
Hello @kcg-gh, 

I just tested again, and indeed, the report "content" is lost after validation, so I will investigate this issue.

About the context, yes the entity is first created in the entities tab and then you need to update the container and select it to add it to the context.

**Comment by SouadHadjiat** [comment]
Issue created on client python : https://github.com/OpenCTI-Platform/client-python/issues/519
PR open : https://github.com/OpenCTI-Platform/client-python/pull/520
