### ISSUE TITLE
Cannot ingest Malware sample_refs

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#4858]
## Prerequisites

- [X] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

Currently I have not been able to successfully ingest Malware SDOs which provide a valid sample_ref value. The "Nested Objects" data within the Malware overview does not display the sample_ref provided. Is there another accepted practice for being able to correlate Malware SDOs to File SDOs that would populate the "Nested Objects" UI element within the Malware Overview?

I have tried manually creating the nested object in the UI, exporting the data with the sample_ref, and reingesting the exported data. This still does not populate the "Nested Objects". Another thing to take into account for this use-case, at ingest time, the uuid on the File SCO, will likely be different than the File SCO which OpenCTI will create for the object. The uuid of the ingested object will likely be placed into the "Other STIX IDs" field, but at ingest time there is not a succinct way to determine what the OpenCTI version of the id will be in order to pre-populate the sample_ref

## Environment

1. OS (where OpenCTI server runs): CENTOS 7.9
2. OpenCTI version: 5.11.11
3. OpenCTI client: frontend

**Comment by Jipegien** [comment]
Hello! Could you detail your ingestion process please?

**Comment by explorecti** [comment]
Currently the ingestion process is still a work in progress, I will review another option for explanation.
