### ISSUE TITLE
Enhance retention policy deletion performances / speed

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4864]
### Enhance retention policy deletion performances / speed

- Scheduling moving to dynamic instead of static (that will improve the reschedule)
- Base schedule change to 30 sec / can be change with retention_manager:interval
- Pagination number move to 1500 / can be change with retention_manager:batch_size
- Introduction of deletion parallelization (10 by default) / can be change with retention_manager:max_deletion_concurrency option

### Side
- Upgrade axios dependency

### Testing
Testing was done with standard observable (multi relationships and multiple labels).
```
retentionManager.ts:95 > Deleted 1500 in 33604 (10)
retentionManager.ts:107 > retentionHandler 2024-10-01T20:08:53.567Z
retentionManager.ts:95 > Deleted 1500 in 33855 (10)
retentionManager.ts:107 > retentionHandler 2024-10-01T20:09:37.507Z
```
Lets take 35 seconds to delete 1500 observables.
Thats almost 42 delete per seconds and so almost 3.5 millions of deletion per day.

**Comment by Jipegien** [comment]
For client: script ad-hoc in short notice.
For more general issue: We need to think about a clever way to do it and it will not be done in 5.12
