### ISSUE TITLE
[Dashboard] The donuts and radar view don't take dynamic filters into account

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4868]
## Description

The widget "donuts view" and "radar view" seem to be buggy. they appear not to take dynamic filters into account.

## Environment

OpenCTI 5.11.13

## Reproducible Steps

The easiest way is to ping me. I've got a dashboard set up to show you straight away. Alternatively, here's a repro case

1. Set up two "donuts" widgets giving statistics on an identical type of entity
2. Added a dynamic parameter filter to one of them (cf screenshot for config example)
3. Look at the results (they are identical) (cf screenshot)
4. Now modify these widgets by switching to "horizontal bar" view (and don't touch anything else in the config)
5. Look at the results: (cf screenshot)
    - the results of the widget not containing a dynamic filter are identical to the results observed in its donuts view
    - the results of the widget containing a dynamic filter aren't identical to the results observed in its donuts view

## Screenshots

Without dynamic filter config : 
<img width="684" alt="Screenshot 2023-11-08 162343" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/e22362d6-a46e-4fb9-a2b8-3a91c3c69aeb">

With dynamic filter config :
<img width="682" alt="Screenshot 2023-11-08 162506" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/7b107f7e-35fe-4f69-aebb-5601c556f4fa">

Result in donuts view : 
<img width="1033" alt="Screenshot 2023-11-08 162553" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/4f8c3efd-f9e8-467d-b250-c0e6dbf00af6">

Result in horizontal bar view : 
<img width="1037" alt="Screenshot 2023-11-08 162528" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/cbb13666-ac19-42c2-b1e2-e0f2b297dbbc">

**Comment by nino-filigran** [comment]
Discussed with @Lhorus6, issue is clear. 

Possible fix: 
- add dynamic filtering for both widgets
- remove the possibility to add dynamic filters for these (not my preferred solution) 

@Jipegien in my opinion, this is is a major bug, that would need to fix quickly, since some customers can have wrong information displayed. Let's discuss in triage.
