### ISSUE TITLE
[Dashboard] Adding a "related entity" filter results in an error

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4869]
## Description

I haven't tried this with all the views, but for several views, using a "related entity" filter in a "knowledge graph" perspective for an "entities", results in an error in the widget (please see the repro case)

## Environment

OpenCTI 5.11.13

## Reproducible Steps

1. Create a new widget
2. Choose the "Area" view
3. Choose the "Knowledge graph" perspective
4. Add an "Entities" (pink button)
5. Add a "Related entity" filter to this entity (whatever the value of the filter)
6. You can leave only the entity filter object (and delete the relationship filter object) or add others, it doesn't change anything
7. Confirm the creation of the widget
8. An error appears in the widget

## Additional information

- Once the widget has crashed, it remains crashed even if you change the configuration - i.e. changing it back to a config that doesn't make it crash doesn't remove the error.
- Doing the same thing from an "Entities" perspective works

## Screenshots 

Example of config : 
<img width="787" alt="Screenshot 2023-11-08 194404" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/2f13237f-a414-4caa-9c55-db6e0644c639">

Error : 
<img width="1718" alt="Screenshot 2023-11-08 194236" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/8add81fa-bd1b-4a2f-8661-06fa10e7878d">

**Comment by Jipegien** [comment]
It is a misuse of the "Knowledge graph" type of widget. You are trying to create a query designed for "Entities" type of widget and does not create a query for "Knowledge graph" type. If you use the "Entities" type, your query is working fine. But we definitely need to handle this case without throwing an error.
