### ISSUE TITLE
[Dashboard] Area and Line view don't seem to retrieve the data correctly

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4872]
## Description

An inconsistency in the data displayed in different views was observed: two widgets were set up with the same filters but one with the timeline view and the other with the (area OR line) view -> the results observed are different (see screenshot).

After several tests, it seems that it's the area and line views that are buggy. When I remove the "relationship type:targets" filter, I start to get data (which still doesn't correspond to the data seen in the timeline view). This shouldn't change anything, I suppose, given that the only possible relationships between a Campaign entity and the "Finance" sector are "target" relationships (see filter in screenshot)

## Environment

OpenCTI 5.11.13

## Reproducible Steps

1. Create two widgets with the same filters (see screenshot for example) but one with the Area (or Line) view and the other with the Timeline view
2. Data displayed are different

## Screenshots

Filters : 
<img width="692" alt="Screenshot 2023-11-09 095707" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/8f2bab16-b61d-42b0-8a84-f0a61180bdb2">

Parameters : 
<img width="697" alt="Screenshot 2023-11-09 095711" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/46a7c1fd-9e1e-4e0a-a310-3559708a1add">

Displayed data : 
<img width="1558" alt="Screenshot 2023-11-09 095701" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/cb9a4850-3fc7-4b8d-ab01-98bff3e42ae1">

**Comment by nino-filigran** [comment]
Discussed with @Lhorus6, issue is clear.

Possible fix:
- unlcear for now, since the root cause is not clarified.

@Jipegien in my opinion, this is is a major bug, that would need to fix quickly, since some customers can have wrong information displayed. Let's discuss in triage.

**Comment by Jipegien** [comment]
we need to assess the complexity of the task with Engineering first. @Kedae ?
