### ISSUE TITLE
Live trigger on modification triggers a notification when an entity is created

### ISSUE THREAD

**Issue by marieflorescontact** [LuatixHQ/opencti#4873]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. `Create a live trigger on modification` , with user interface notification, for a specific entity, for exemple an Area
2. Go to Area and create an new Area
3. Go to `Notification`s page
4. You will find a `modification` notification

![Capture d'écran 2023-11-09 102809](https://github.com/OpenCTI-Platform/opencti/assets/73853856/3afff935-831e-4eab-b27b-bcb3db1eef30)

![Capture d'écran 2023-11-09 103121](https://github.com/OpenCTI-Platform/opencti/assets/73853856/6ec2cbb9-e538-449b-a266-afe4d555ac30)

**Comment by nino-filigran** [comment]
@Jipegien I've been able to reproduce this bug.

The issue is clear: 
- we need to ensure that a modification trigger does not send a notification for a create event.

In my opinion, this is a minor bug (Minor: Results in some unexpected or undesired behavior, but not enough to disrupt system function). Let's discuss this in triage.

**Comment by Jipegien** [comment]
I am not sure it is really a bug. Creation is, actually, a modification. This is the first modification related to what is surveyed. And I don't see a use case where the user want absolutely to not see this first notification. For me this is an expected, or at least acceptable, behavior.

**Comment by nino-filigran** [comment]
Closing issue based on the above comment.
