### ISSUE TITLE
Bad design alignement in Activity configuration

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#4874]
Reproductible steps:
- Go in Settings > Activity > Configuration
- The 'Add an organization' field is not aligned with the 'group' and 'user' ones
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/110cc751-3013-425e-aca2-b2193e236912)

**Comment by kundan766** [comment]
I want to work on this issue .can you please assign me

**Comment by SarahBocognano** [comment]
A feature is already planned on this subject. Maybe it can be done there : https://github.com/OpenCTI-Platform/opencti/issues/3532

**Comment by SamuelHassine** [comment]
Duplicate of #3532.
