### ISSUE TITLE
[Dashboard] "NOT" filters not available for some filters

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4878]
## Description

For some filters, it is not possible to have a "NOT" filter, i.e. pressing Alt does not produce a "NOT" filter (but a classic filter).

Here is the list of filters for which it doesn't seem to work: 
- In the Entities perspective:
    - Related entity
    - Assigned
    - Participant
    - Kill Chain phase

- In the Knowledge graph perspective, for classic/grey filters:
    - Source entity
    - Target entity
    - Source type
    - Target type
    - Kill Chain phase

- In the Knowledge graph perspective, for dynamic filters (both source/orange and target/green filters):
    - Related entity
    - Assigned
    - Participant
    - Kill Chain phase

## Environment

OpenCTI 5.11.13

## Reproducible Steps

1. Create a widget with the view "Area" (perhaps the problem appears with all the views but I only tested with this one)
2. Try creating a "NOT" filter for one of the filters listed in the description of this issue

**Comment by Archidoit** [comment]
Technical note: the mentionned filters should be added in the 'EqFilters' array to enable their negation

**Comment by nino-filigran** [comment]
@Archidoit does it mean this is taken into account for the delivery of filters refacto?

**Comment by Archidoit** [comment]
I'll resolve the issue in the filters refacto.

**Comment by Archidoit** [comment]
This issue will be resolved in #2686

**Comment by richard-julien** [comment]
Closing as be resolved in https://github.com/OpenCTI-Platform/opencti/issues/2686
