### ISSUE TITLE
Version 5.11.13 packages have not been generated correctly

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#4880]
## Description
The packages for version 5.11.13 available here: 
Are only 11Kb (they are usually over 90MB). 
Probably they have not been generated correctly, so we can update our bare metal installation.

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/17bc4e13-1d46-49c1-b75f-64804dfdec28)

**Comment by Jipegien** [comment]
We are changing our internal release tools and encountering some problems. @Kedae, is there an alternative for having access to the release?

**Comment by AlexSanchezN** [comment]
I see that it has happened again with 5.11.4.
No rush on our part. We will update when possible.

Thanks,
Àlex

**Comment by richard-julien** [comment]
Just fixed and available for 5.11.14.
Will do an extra work to do this for the 5.11.13, so I hope 5.11.14 package will be ok. closing the ticket.

**Comment by richard-julien** [comment]
Looks like node_modules are still missing, reopening

**Comment by richard-julien** [comment]
Should be good now. Waiting for your feedback @AlexSanchezN before closing it

**Comment by AlexSanchezN** [comment]
@richard-julien Updated without any problem. Thank you very much

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/901925b5-ec7e-4f11-85f1-da33a54f135a)

**Comment by AlexSanchezN** [comment]
Closing
