### ISSUE TITLE
Can't download exports from a list

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#4881]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select few observables
2. Export as json
3. { e.g. Error ... }

## Expected Output

Be able to download via a click on the line

## Actual Output

Cannot download the export
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/ec5a4490-dc95-4c2f-a9b2-699008c73d38)

## Question
@Jipegien @nino-filigran As we added the possibility to download the files encrypted in Data section, do we want to have the same behaviour everywhere or not?
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/56daf7c8-33f5-42e0-8acc-8174989d4806)

**Comment by Jipegien** [comment]
The fact it can't be downloaded from the list is to be considered as critical and must be corrected ASAP.
As for adding the encrypted archive option, it can be done later if it take more than a day to fix it. I'll create a second issue about it.

**Comment by Jipegien** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/4883
