### ISSUE TITLE
Error when export list

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4889]
## Description

This error occurs in certain cases of list export:

`Connector ready to process the operation, {'name': 'Variable "$elementId" of type "String" used in position expecting type "[String]".', 'message': 'Variable "$elementId" of type "String" used in position expecting type "[String]".'}`

## Environment

5.11.14

### 1

1. Go to bulk search
2. Looking for something that has several results
3. Try exporting

### 2

1. Go on an Intrusion set
2. Go to the knowledge > Indicator tab
3. Try to export several indicators

## Additional information

Strangely, list export works elsewhere. For example, if you try to export a list of Indicators from Observations > Indicators, it works

## Screenshots
<img width="1710" alt="Screenshot 2023-11-13 150322" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/171b0570-a674-4d65-a586-734dc44f7a35">

**Comment by Jipegien** [comment]
@richard-julien is it related to fixes done lately on the export feature?

**Comment by richard-julien** [comment]
No. Its due to a filter parameter not correctly understand by the export.

**Comment by SouadHadjiat** [comment]
This issue is happening since this commit : https://github.com/OpenCTI-Platform/opencti/commit/698eda6fc6781cb225061f7b5192053a77a1f765
we changed `stixCoreObjects` parameter `elementId` type from `String` to `[String]` for  but we didn't update the python client, which breaks all exports with this param. So the fix needs to be done in python client @richard-julien

**Comment by SouadHadjiat** [comment]
This PR in client-python should solve this issue : https://github.com/OpenCTI-Platform/client-python/pull/492

**Comment by SouadHadjiat** [comment]
This bug should be fixed when client-python is released (https://github.com/OpenCTI-Platform/client-python/pull/492), should I keep it open ? @SamuelHassine

**Comment by SamuelHassine** [comment]
Confirmed fixed, will be ok after 5.12.0 full release.
