### ISSUE TITLE
Error when sending objects from an Investigation to a Container

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4891]
## Description

Two different errors were observed when sending data from an investigation into a container with the "Add to a container" button. These errors occurred when this investigation was started from the same container (see the repro case for more information).

- The error observed each time is : "Unsupported operation". See the screenshot for more information.
- On one occasion (on another platform, ping me for more information), another error was observed : "Business validation". See the screenshot for more information.

## Environment

5.11.14

## Reproducible Steps

1. Create an investigation from a container (via the knowledge tab > "Start an investigation" button)
2. Inside the investigation, expand one of the nodes to add data in the graphs
3. Return this information to the initial container (Use the "Add to a container" button)

#### "Unsupported operation" error:

<img width="1715" alt="Unsupported operation error" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/9a43568b-d17f-4efc-ba87-769cc42f9dd7">

<img width="1691" alt="Unsupported operation error 2" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/b962f297-8b46-4522-bcff-48f4e14400ba">

#### "Business validation" error: 

<img width="362" alt="Business validation error" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/948fac16-3e34-461e-80ad-8d6024a08feb">

**Comment by nino-filigran** [comment]
@Lhorus6 I followed the steps, but could not reproduce. When I perform the same operation, I got an error message displayed on the UI "unsupported operation". Do you also have it?

**Comment by nino-filigran** [comment]
Clarified with @Lhorus6

**Comment by Jipegien** [comment]
@Goumies FYI, it seems that it happens only when the investigation graph contains the container (for example "container1") and we try to add the investigation graph to this container1
