### ISSUE TITLE
Logo for relationship creation suggested stays green 

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4899]
## Description

When you use the suggestions function to create relationships (i.e. in a knowledge view of a container, the "Open the suggestions" button with the pink bubble on top), you can select the entity for which you want to create these relationships from a drop-down menu. If you select an entity, then confirm the creation, the relationships will be created and the icon will turn green (see screenshot 1). If you now change the entity for which you want to create relationships in the drop-down menu, the icon will still be green (see screenshot 2). 

We need to reset the icon status

## Environment

OpenCTI 5.11.14

## Reproducible Steps

1. Create a report and include one intrusion set, one malware and one indicator.
2. Create "indicates" relations for the intrusion set using the suggestion mechanism
3. Change the drop-down menu to focus on malware
4. The button is still green even though this has not been done for the malware

## Expected Output

The state of the button must be in line with the entity selected in the drop-down menu:
- If a relationship has already been created for the entity -> green icon
- Otherwise -> basic icon (pink icon)

### 1
<img width="1212" alt="Screenshot 2023-11-14 121514" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/d0bb53f8-e2df-45df-86e2-e02690ade4af">

### 2
<img width="1207" alt="Screenshot 2023-11-14 121525" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/a3589798-7771-4362-9306-b69bfc65f500">

**Comment by Jipegien** [comment]
Ok we need to save states in the suggestion menu. @Kedae Is it something tiny to do?

**Comment by Kedae** [comment]
Seems so, don't have a lot on insight on that, but shouldn't be long
