### ISSUE TITLE
Add overrides to the max confidence level of Users for specific Entities

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4900]
## Use case

Users (and connectors/feeds/stream) might be more or less trustable in accordance with the nature of data they provide. We will add the possibility to configure overrides to the max confidence level of a user for specific Entities.

Subtask:
* Managing overrides of the max confidence level of a user for specified Objects
* Take into account override when upserting data from a connector or a feed
* Be able to view the max confidence level in the list of users when setting a stream or a feed

Blocked by #4304

**Comment by labo-flg** [comment]
Only chunk 1 merged.
