### ISSUE TITLE
I wonder why there is no "related-to" relationship between File(Observables) and Malware(Entities).

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#4908]
When I look at the various reports on the OpenCTI demo site, I can see that in **all reports there is no relationship between File and Malware directly.**

Instead there is Indicator that generated from File indicates to Malware.

**A Information of Malware entity** of STIX that can be entered in OpenCTI **has limited information that can be entered.**

For example, it is impossible to enter the Malware's hash(MD5,SHA etc.), size etc.

So, I think it would be a good idea **to enter information about the Malware in the File observables, connect to "related-to", and write something like “This file is information about malware” in the description.** Am I wrong?

If I simply link a File's indicator to Malware without "related-to" relationship, **it will be impossible to determine which File observable contains information about the Malware when there are multiple File observables in one report.**

I would appreciate it if someone familiar with STIX could explain.

**Comment by Jipegien** [comment]
Reports imported on the demo instance are compliant with STIX 2.1, the standard does not provide specific relationships between File and Malware.

But you can create a "related-to" relationship between File and Malware if you want in OpenCTI.
