### ISSUE TITLE
Redis RAM increasing with  REDIS__TRIMMING=500000

### ISSUE THREAD

**Issue by Tonnulus** [LuatixHQ/opencti#4919]
## Description

Hello,

I have problems with redis, Redis is using a lot of RAM. He uses a lot of Ram and continues to increase his consumption.

 I had until now a REDIS__TRIMMING=1000000 Now it's REDIS__TRIMMING=500000 But I still use too much Ram more than 11G And it keeps increasing...

![image](https://github.com/OpenCTI-Platform/opencti/assets/9503671/e33cfb2c-a0a9-49e9-9be5-8bf325c3dbaa)

You can see on this graph, I tryed to restart OpenCTI (All nodes, and Redis) at 15h and I changed the configuration to EDIS__TRIMMING=500000  at 15h10

I have over 700 keys in my redis. stream. I don’t have the size of each key. But  stream.opencti is around 1.38 Go.

## Environment

1. OS (Openci and Redis) Debian 10.11 with docker
2. OpenCTI version: 5.11.12
- 6 nodes 
- 2 Workers per nodes

## Reproducible Steps

I don't know...

## Expected Output

A normal use of Redis RAM

## Actual Output

Redis use more then 11G and It's increasing...

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/9503671/ebef19a1-c2a9-4a38-855f-05f4388fd273)

**Comment by Tonnulus** [comment]
All my connectors are stopped but Redis Ram usage continue to increase ...

redis-cli MEMORY USAGE on biggest keys: 

| stream.opencti                        | 2151028280 |
|---------------------------------------|------------|
| stream.notification                   | 123592936  |
| sess:i8PviG1eaOAcDlIXqSvYFClrazo9A-Kq | 12376      |
| sess:k0HQiij5MB5egAhY8MBovQh_9Wk9H5qa | 12376      |
| sess:MG5-r-2_Zv-Dg7jTt7nmGEIJAhRRVhnx | 12376      |
| sess:SUEs9bVMxaE8SUG7oEsxpIQn4zde50b9 | 12376      |
| sess:U3S0lz87t7q0ahbf9g_4kJB8YZA8Hrtd | 12376      |
| sess:WIp9_6vkLDfXDVpFgXaMqnSn6TmeOJ1I | 12376      |
| Total all keys | 2274913296 |

```
redis-cli INFO MEMORY

# Memory
used_memory:13539733992
used_memory_human:12.61G
used_memory_rss:12203397120
used_memory_rss_human:11.37G
used_memory_peak:15566812936
used_memory_peak_human:14.50G
used_memory_peak_perc:86.98%
used_memory_overhead:1124184
used_memory_startup:865992
used_memory_dataset:13538609808
used_memory_dataset_perc:100.00%
allocator_allocated:13539871856
allocator_active:13541744640
allocator_resident:13626785792
total_system_memory:16942936064
total_system_memory_human:15.78G
used_memory_lua:37888
used_memory_vm_eval:37888
used_memory_lua_human:37.00K
used_memory_scripts_eval:1384
number_of_cached_scripts:3
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:32768
used_memory_vm_total:70656
used_memory_vm_total_human:69.00K
used_memory_functions:184
used_memory_scripts:1568
used_memory_scripts_human:1.53K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.00
allocator_frag_bytes:1872784
allocator_rss_ratio:1.01
allocator_rss_bytes:85041152
rss_overhead_ratio:0.90
rss_overhead_bytes:-1423388672
mem_fragmentation_ratio:0.90
mem_fragmentation_bytes:-1336298480
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:216936
mem_cluster_links:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.3.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

```

`MEMORY STATS`
```
 1) "peak.allocated"
 2) (integer) 15566812936
 3) "total.allocated"
 4) (integer) 13543281352
 5) "startup.allocated"
 6) (integer) 865992
 7) "replication.backlog"
 8) (integer) 0
 9) "clients.slaves"
10) (integer) 0
11) "clients.normal"
12) (integer) 94226
13) "cluster.links"
14) (integer) 0
15) "aof.buffer"
16) (integer) 0
17) "lua.caches"
18) (integer) 1384
19) "functions.caches"
20) (integer) 184
21) "db.0"
22) 1) "overhead.hashtable.main"
    2) (integer) 38472
    3) "overhead.hashtable.expires"
    4) (integer) 1384
    5) "overhead.hashtable.slot-to-keys"
    6) (integer) 0
23) "overhead.total"
24) (integer) 1001642
25) "keys.count"
26) (integer) 757
27) "keys.bytes-per-key"
28) (integer) 17889584
29) "dataset.bytes"
30) (integer) 13542279710
31) "dataset.percentage"
32) "99.9990005493164"
33) "peak.percentage"
34) "87.00099182128906"
35) "allocator.allocated"
36) (integer) 13543579408
37) "allocator.active"
38) (integer) 13545439232
39) "allocator.resident"
40) (integer) 13630459904
41) "allocator-fragmentation.ratio"
42) "1.0001373291015625"
43) "allocator-fragmentation.bytes"
44) (integer) 1859824
45) "allocator-rss.ratio"
46) "1.0062767267227173"
47) "allocator-rss.bytes"
48) (integer) 85020672
49) "rss-overhead.ratio"
50) "0.8955461978912354"
51) "rss-overhead.bytes"
52) (integer) -1423753216
53) "fragmentation"
54) "0.9013134241104126"
55) "fragmentation.bytes"
56) (integer) -1336536392
```

**Comment by SamuelHassine** [comment]
Hello @Tonnulus,

The Redis trimming is working well. This may be linked to a bug in a connector that is accumulating IDs or updating a huge report very often.

Can you open (in administrator) http://opencti/stream (raw stream) when you are observing Redis to be filled and observe if you have very large events in the browser (with a lot of object_refs or a lot of "other_stix_ids")?

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
As you are under support, don't hesitate to open a JIRA ticket on this, our team can help you troubleshoot where those events come from.

**Comment by Tonnulus** [comment]
Thank you I will as soon as I have access.

In the meantime. Perhaps these errors can provide more context.
``` 
{"category":"APP","level":"warn","locks":["{locks}:f6c698a9-a089-423b-8202-37ce1436fa84"],"message":"[REDIS] Extending resources for long processing task","stack":"Error: \n    at lockResource (/opt/opencti/build/src/database/redis.ts:335:28)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3278:18)\n    at deleteInferredRuleElement (/opt/opencti/build/src/database/middleware.js:3378:9)\n    at Object.clean (/opt/opencti/build/src/rules/containerWithRefsBuilder.ts:203:5)\n    at rulesCleanHandler (/opt/opencti/build/src/manager/ruleManager.ts:273:13)\n    at callback (/opt/opencti/build/src/manager/ruleManager.ts:188:5)\n    at publish (/opt/opencti/build/src/database/middleware-loader.ts:89:30)\n    at elList (/opt/opencti/build/src/database/middleware-loader.ts:101:9)\n    at applyCleanupOnDependencyIds (/opt/opencti/build/src/manager/ruleManager.ts:190:3)\n    at rulesApplyHandler (/opt/opencti/build/src/manager/ruleManager.ts:232:13)\n    at ruleStreamHandler (/opt/opencti/build/src/manager/ruleManager.ts:299:5)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:630:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:684:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:701:13)","timestamp":"2023-11-21T14:41:53.907Z","version":"5.11.12"
```

**Comment by Tonnulus** [comment]
The latest updates, seem to have solved the problem
![image](https://github.com/OpenCTI-Platform/opencti/assets/9503671/338061bc-204d-491e-bf8e-55ebc6c6ebc1)

**Comment by AlexSanchezN** [comment]
Just updated from 5.12.4 to 5.12.6 and I'm facing the error below:
`{"category":"APP","level":"info","message":"[MIGRATION] Read 38 migrations from the database","timestamp":"2023-12-15T21:20:39.950Z","version":"5.12.6"}
{"category":"APP","level":"info","message":"[MIGRATION] 2 migrations will be executed","timestamp":"2023-12-15T21:20:39.951Z","version":"5.12.6"}
{"category":"APP","level":"info","message":"[MIGRATION] Starting 1701354091161-files-registration.js","timestamp":"2023-12-15T21:20:40.079Z","version":"5.12.6"}
{"category":"APP","level":"warn","locks":["{locks}:platform_init_lock"],"message":"[REDIS] Extending resources for long processing task","stack":"Error: \n    at lockResource (/opt/opencti/build/src/database/redis.ts:318:28)\n    at initialization_default (/opt/opencti/build/src/initialization.js:359:18)\n    at platformStart (/opt/opencti/build/src/boot.js:231:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-15T21:21:28.956Z","version":"5.12.6"}
{"category":"APP","level":"warn","locks":["{locks}:platform_init_lock"],"message":"[REDIS] Extending resources for long processing task","stack":"Error: \n    at lockResource (/opt/opencti/build/src/database/redis.ts:318:28)\n    at initialization_default (/opt/opencti/build/src/initialization.js:359:18)\n    at platformStart (/opt/opencti/build/src/boot.js:231:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-15T21:22:18.355Z","version":"5.12.6"}
{"category":"APP","level":"warn","locks":["{locks}:platform_init_lock"],"message":"[REDIS] Extending resources for long processing task","stack":"Error: \n    at lockResource (/opt/opencti/build/src/database/redis.ts:318:28)\n    at initialization_default (/opt/opencti/build/src/initialization.js:359:18)\n    at platformStart (/opt/opencti/build/src/boot.js:231:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-15T21:23:07.753Z","version":"5.12.6"}
{"category":"APP","level":"warn","locks":["{locks}:platform_init_lock"],"message":"[REDIS] Extending resources for long processing task","stack":"Error: \n    at lockResource (/opt/opencti/build/src/database/redis.ts:318:28)\n    at initialization_default (/opt/opencti/build/src/initialization.js:359:18)\n    at platformStart (/opt/opencti/build/src/boot.js:231:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-12-15T21:23:57.152Z","version":"5.12.6"}`

Not sure if platform will start. I'll leave the process over night in case it is a large migration
