### ISSUE TITLE
Page "group" not updated when adding users

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#4930]
## Description

Page "group" not updated when adding users

## Reproducible Steps

1. Go to settings / security / groups
2. Create a group
3. Edit the group and go to the members tab
4. Add a few members

=> The members do not appear in the list of members, you should reload the page to make them appear.

**Comment by CelineSebe** [comment]
The bug has been fixed with updaters in GroupEditionUsers
