### ISSUE TITLE
Ability to ingest CSV files where each lines can correspond to different objects

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#4935]
## Use case

I have a file containing a list of Observables found during a cyber attack. The list contains IPv4, hash, domain. Column A is the value, column B is the type of observable

As a user, I want to be able to express that when column B has the value “domain”, it is a Domain that need to be created, etc.

### Associated Features to implement

In the CSV mapper, be able to define the column representing the objects' type and the value to use for the current representation mapping.

- Example : Representation for "Threat Actor" when column Index "D" with value "equals/not equals" "threat_actor"

**Comment by sweet-mentat** [comment]
I wish we could upvote issues. This is definitely an issue I would upvote. Have you guys decided not to work this issue?

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/7400
