### ISSUE TITLE
The list of available triggers does not appear when creating a regular digest

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#4938]
## Description

The list of available triggers appears only when creating a regular digest for the Platform Admin user. When I create a regular digest for another user, the list of his available triggers does not appear.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 5.11.12
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create some triggers
2. Start creating a regular digest
3. The triggers field contains "No available options" if this user is not a Platform administrator

## Expected Output

All triggers available to the user are shown.

## Actual Output

All triggers available to the user are not shown.

## Screenshots (optional)
For Platform Admin
![image_2023-11-21_10-47-57](https://github.com/OpenCTI-Platform/opencti/assets/122795003/956fee59-6038-46a9-9a2b-ac1ebba41634)
For common user
![image_2023-11-21_10-45-01](https://github.com/OpenCTI-Platform/opencti/assets/122795003/fad1cfa2-40b1-4ca3-a2a0-e2a7e58e642f)

**Comment by marieflorescontact** [comment]
I can't reproduce, not sure it is a bug.
Triggers are specific to each user, so if an admin user creates a trigger, other users will not have access to it.
