### ISSUE TITLE
RabbitMQ queues is taking up a lot of disk space

### ISSUE THREAD

**Issue by softengsistemas** [LuatixHQ/opencti#4941]
RabiMQ queues is taking up a lot of disk space. When the disk is full, the OpenCTI is down.

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/abb03fb7-9c35-4aa5-820a-4b4031082ede)

![image](https://github.com/OpenCTI-Platform/opencti/assets/32461519/465d686a-ae29-41a3-8edc-4c3a5480cf34)

Can you tell me what the procedure is to clean these logs or the best practices?

Thanks. :)

**Comment by sbocahu** [comment]
hi,
these files are not logs but actual data of the rabbitmq service.
make sure you've provisioned enough disk space for the service and that messages are consumed.
in some external import connectors you may configure a reasonable starting date for data ingestion to prevent too much messages to be added in the queues.
do not delete these files manually, if you want to clear the queues; use rabbitmq tools.
