### ISSUE TITLE
Interface bugs on data import page

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#4942]
## Description

The UI on the data import page is looking messy. Text is crashing into other elements in the main and right columns. Also the import.csv function on the right (see attached image) has a little hyphen next to it that looks like it should be usable interface like a dropdown caret, but it isn't. 

## Environment

1. Mac 13.6.1; Chrome browser
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run OpenCTI with the above specifications
2. Access the data import page

## Expected Output

Either there should be no marking next to import.csv, or if there is a dropdown there, there should be an actionable indicator (caret).

## Screenshots (optional)
<img width="1470" alt="Screenshot 2023-11-17 at 10 25 56 AM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/5c0c3f08-b39d-47b9-adc8-46185a3b796b">

**Comment by Jipegien** [comment]
@RomuDeuxfois & @labo-flg : seems lacking a date for ImportCSV. Is it also possible to limit the display of file_name  in uploaded files and the display of mime-types in the list of connectors, or do we need to create another issue for that?

**Comment by RomuDeuxfois** [comment]
State management should be added at the importCsv connector level by setting the last csv import date. This will replace caret.
What do you think @Jipegien ?

**Comment by Jipegien** [comment]
The comportment needs to be the same as for other connectors.

**Comment by RomuDeuxfois** [comment]
We can set the state connector on polling time

**Comment by lndrtrbn** [comment]
The issue on uploaded files is not specific to CSV page. There is the same issue on other pages listing long filenames.
CSS stuff, I can have a look if you want ? For the CSV date stuff, I leave that to you.
