### ISSUE TITLE
Small interface feature request on csv import modal popup

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#4943]
## Use case

[Nielsen Norman design heuristics #1 Visibility of system status and #6 Recognition rather than recall](https://www.nngroup.com/articles/ten-usability-heuristics/) suggest that this first modal popover should show the configuration option when it appears and leave it unpopulated until the user suggests a connector, rather than not making it appear until the user selects a connector. See attached screenshots.

<img width="1496" alt="Screenshot 2023-11-17 at 10 35 22 AM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/edebcd75-72e4-436d-9a6f-9bf4f83cb878">
<img width="1496" alt="Screenshot 2023-11-17 at 10 35 38 AM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/60fc4e21-d145-4d5f-81d4-1bf9ff52a63a">

## Current Workaround

I actually backed out of the modal a few times before I realized I needed to select ImportCSV in order to make the configuration option show up.

## Proposed Solution

Show the configuration option when it appears and leave it unpopulated until the user suggests a connector, rather than not making it appear until the user selects a connector. 

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
Hey @gusandrews Thanks for raising this issue and your suggestion. Also, this link is very useful and can be something we take inspiration from, for our GUI. 
However, given that the CSV mapper is the single connector which requires a configuration, we do not plan to implement this change for now. Indeed, this field will be empty most of the time and this do not make sense for us.
