### ISSUE TITLE
Improve error messaging on ImportCSV

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#4944]
## Description

I'm getting the error message 'data' when I run my csv connector… not sure what the issue is, this error could use better explanation. See screenshot.

<img width="1496" alt="Screenshot 2023-11-17 at 10 32 30 AM" src="https://github.com/OpenCTI-Platform/opencti/assets/1565981/52ed9fb9-3b9c-4a7d-bd67-a8fed327088f">

1. Mac 13.6.1, Chrome Version 119.0.6045.159 (Official Build) (arm64)
2. OpenCTI version: 5.11.12
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. with setup above
2. launch opencti
3. open data importer
4. Import a .csv with column headers Index, name, type, relation, reported by, and source
5. After sending the bundles to the worker for export,
6. the system returns the message 'data' and the import is marked as failed.

## Expected Output

As a new user of OpenCTI
I need rich feedback about why the import of my .csv has failed
And instructions on file format somewhere in the documentation
So I can successfully import a CSV
and report back to my community of early adopters about how OpenCTI is a useful and powerful tool ;)

## Actual Output

'data'

## Screenshots (optional)
see above

**Comment by Jipegien** [comment]
Are you using a CSV Mapper configured for this type of content?

**Comment by gusandrews** [comment]
It's set up for .csvs, yes. However, I am not sure what columns should appear in the CSV, and I don't know if there are instructions in the documentation about this. Could you point me to some so I can troubleshoot?

**Comment by Jipegien** [comment]
https://docs.opencti.io/latest/administration/csv-mappers/
https://blog.filigran.io/solve-csv-data-import-with-csv-mapper-2fe1dde671c8

**Comment by Jipegien** [comment]
@gusandrews did you manage to resolve the situation with the help of the available documentation?

**Comment by Jipegien** [comment]
@labo-flg Do you know what can cause the 'data' error log? Is it when a file is imported with a CSV mapper not configured for it?

**Comment by labo-flg** [comment]
I just tested an empty mapper (zero representation configured) and you get this "data" error.

The mapper appears as valid in the CSV Mapper interface, maybe we could add a rule so that empty mapper are by definition invalid?

**Comment by Jipegien** [comment]
yes, good idea!
