### ISSUE TITLE
Improve search to make it able to find subparts which are not starting the word

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#4952]
## Use case

The search can’t find a subpart of word that are not at the beginning of the word, e.g. “ware” will not find “malware”. 

## Current Workaround

None. 
## Proposed Solution

Be able to search subparts which are not starting the word. 

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by Jipegien** [comment]
covered by new filters (ends with and contains). duplicate of #2686
