### ISSUE TITLE
Some Countries are not highlighted on the map

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4955]
## Description

Some Countries are not highlighted on the map, cf screenshot

List of countries not highlighted:
- Laos
- Vietnam
- Taiwan

I don't know if there are others

#### For example

If we add "Laos" as a victim of a campaign, we do not see it on the map (unlike with France, Russia, China, ...). Note : the map is visible in the knowledge tab of the campaign

## Environment

OCTI 5.11.14

### 1

1. Go to Laos entity
2. Search Laos in the map

Test with Thailand for example and you will see the difference.

### 2

1. Create a campaign
2. Add Laos (Country) as a victim)
3. Look on the map in the "knowledge" tab of the campaign
4. Search Laos in the map

Test with Thailand for example and you will see the difference.

#### Laos vs Thailand

<img width="1710" alt="Screenshot 2023-11-22 172453" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/99c0b3aa-f607-4fa2-b9e5-1be5fa6f07e1">

**Comment by CelineSebe** [comment]
Laos is missing in the countries.json file, we need to enter the coordinates
![Laos_coord](https://github.com/OpenCTI-Platform/opencti/assets/87119259/77aea7ed-564d-4ce2-9f40-0d0ae913310b)
![props_thailand](https://github.com/OpenCTI-Platform/opencti/assets/87119259/f3da0b9d-8e11-4c69-9927-e77c5f1ab480)

![Thailand_coord](https://github.com/OpenCTI-Platform/opencti/assets/87119259/a8b290d3-0989-491f-80f7-359560e23bc1)

**Comment by CelineSebe** [comment]
Laos is written Lao People's Democratic Republic in data countries
![Lao](https://github.com/OpenCTI-Platform/opencti/assets/87119259/741545e6-0353-487d-90a9-6e6c15ccf393)
Do you think you should rename it Laos ?

**Comment by CelineSebe** [comment]
![Lao People's Democratic Republic](https://github.com/OpenCTI-Platform/opencti/assets/87119259/14932737-ebb5-4449-b584-95278770411a)

**Comment by CelineSebe** [comment]
Vietnam is written Viêt Nam.

![Viet Nam location](https://github.com/OpenCTI-Platform/opencti/assets/87119259/d97be5df-ab36-463d-95f7-af774ae8b2db)

Problem with Taiwan, the data exists in countries.json file, but it's not recovered

**Comment by lndrtrbn** [comment]
So, after debugging with @CelineSebe :
- It works for Laos but the country name is `Lao People's Democratic Republic`, is `Laos` a country you created yourself?
- Same for Vietnam, the name is `Viet Nam`
- For Taiwan there is indeed an issue, we need to update the opencti dataset used by the connector, it misses the aliases `TWN` to be able to work

**Comment by SamuelHassine** [comment]
Explaination:

* Countries need to have 2 letters ISO code to be highlighted
* Only countries coming from the OpenCTI dataset have 2 letters ISO code
* All countries created by other connectors not respecting the OpenCTI dataset should be merged with the correct one in the OpenCTI datasets.
