### ISSUE TITLE
[Dashboard] "Part of" filter not taken into account in some case

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#4957]
## Description

It seems that dynamic filters "part of" are not taken into account. Here is a list of tests carried out:

- Organization part of [a Sector] -> Work
- Intrusion set targeting Organization, but only Organization located at [a Country] -> Work
- Intrusion set targeting Organization, but only Organization part of [a Sector] -> Doesn't work

See screenshots

## Environment

5.11.14

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. New widget "Horizontal Bar"
2. Choose "Knowledge graph" perspective
3. Use the filters visible in the screenshot "Doesn't work" below

### Work

<img width="679" alt="Screenshot 2023-11-22 180731" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/eb108f0e-aa26-44ac-ba1a-4ece73482cc4">

<img width="682" alt="Screenshot 2023-11-22 180609" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/a07fbec9-b8a3-4503-8e3f-419e2993f481">

### Doesn't work

<img width="680" alt="Screenshot 2023-11-22 180703" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/828c34b7-0a40-4ada-9ecb-f99bf33c4350">

**Comment by SamuelHassine** [comment]
The target type is not necessary here as it is already in the dynamic filter.

I've a doubt about this since it is exactly the same logic and there is no specific processing depending on the type of relation.

**Comment by Lhorus6** [comment]
1. If we don’t use the grey filter « target type: Organization », it work as expected ? 
2. in the case of « located at » in the dynamic filter, having this grey filter « target type » doesn’t raise any problem if I am not mistaken

I will do some extra tests tomorrow

**Comment by Lhorus6** [comment]
I've done other tests and the problem no longer seems to exist. I close this issue
