### ISSUE TITLE
Playbook Automation interface is not full screen

### ISSUE THREAD

**Issue by Majin-Jermain** [LuatixHQ/opencti#4964]
## Description

When modifying a playbook, the top and bottom of the tree is hidden before reaching the edge of the sceen. PLease see attached screenshot.

## Environment

1. OS (where OpenCTI server runs): The OS of https://demo.octi.filigran.io/
2. OpenCTI version: 5.11.14
3. OpenCTI client: Front end, browsing the GUI with Google Chrome
4. Other environment details: Version 119.0.6045.160 (Official Build) (64-bit)

## Reproducible Steps

Activate Enterprise Edition, navigate to Processing page and create a long playbook with many steps. Zoom in.

## Expected Output

Expecting the tree to fill up the whole screen i.e. reach all the way to the edge.

## Actual Output

The tree is cut off before reaching the edge of the screen.

## Screenshots (optional)

![Screenshot 2023-11-23 140509](https://github.com/OpenCTI-Platform/opencti/assets/58041836/5b6d94b9-6b0b-4a7e-a6b6-62ad6247ed3d)

**Comment by nino-filigran** [comment]
@Majin-Jermain we both tried to reproduce with @Jipegien but we did not manage.: each time the screen adapted perfectly to the size. Does it happen only with this specific one for you? 
If the problem persists, please come to us directly. In the meantime, I'll close the bug.
