### ISSUE TITLE
Activity audit update events for the same entity are mixed up

### ISSUE THREAD

**Issue by SouadHadjiat** [LuatixHQ/opencti#4969]
## Description

In /dashboard/settings/activity/audit, you can see the activity events of the platform, which can be mixed up when we have more than two different update events for the same entity.

Ex: if I update multiple fields of a report : change confidence level and report types
![image](https://github.com/OpenCTI-Platform/opencti/assets/668192/41f04a3e-07e8-4bb1-9515-ecee53049c7d)

In activity audit, I can see two lines of updates, but with the same message (confidence update), the message of report types updates is overriden by the other message : 
![Capture d'écran 2023-11-23 163212](https://github.com/OpenCTI-Platform/opencti/assets/668192/dfeb19d9-2d2f-47a9-86de-f1dfc8d0084e)

I can see here that one of the message displayed is not the right one : 
![Capture d'écran 2023-11-23 163235](https://github.com/OpenCTI-Platform/opencti/assets/668192/252062f7-54b7-46f8-9f9b-f94019e35e7c)

This issue is related to Relay, we have this warning message in the console, explaining why the messages are the same, because ContextData object has an id field with the entity id : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/668192/8b50605c-73af-4855-a9df-9439035d6a0f)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.11.14
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Update any entity with two differents fields
2. Go to Activity, and check "Include knowledge" to see knowledge update events
=> You'll see twice the same message, for one of the fields only, instead of two different messages.

**Comment by SamuelHassine** [comment]
Thanks @SouadHadjiat for reporting this :)
