### ISSUE TITLE
Be able to flush the bundle in the RabbitMQ queue placed by a connector

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#4974]
## Use case

The connector state can be reset in the interface, but bundles placed in the queue remain there. It would be nice to be able to delete them
## Proposed Solution

Be able to flush the bundle in the RabbitMQ queue placed by a connector

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Duplicate of #3781?

**Comment by nino-filigran** [comment]
Yes, good shot. Closing this one.
