### ISSUE TITLE
Fail to remove element with unfinished works

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#4992]
## Description

When an element have current works and try to be deleted, the deletion of the element fail with

Repro case:

- Start a platform with the connector export file stix
- Create entity A
- Go to data an click on export panel
- Stop the export connector
- Click on export
- The file export is spinning
- Try to delete entity A => crash

`{"category":"APP","error":{"context":{},"message":"UnknownError","name":"NotFound","stack":"NotFound: UnknownError\n    at de_NotFoundRes (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6100:23)\n    at de_HeadObjectCommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4706:25)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20\n    at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26\n    at loadFile (/opt/opencti/build/src/database/file-storage.js:164:20)\n    at deleteFile (/opt/opencti/build/src/database/file-storage.js:95:14)\n    at deleteFiles (/opt/opencti/build/src/database/file-storage.js:118:5)"},"level":"error","message":"[OPENCTI] Retention manager error deleting 0ca98fe6-a2fa-42bc-9fb1-c5f1c4843d65","timestamp":"2023-11-23T13:42:39.160Z","version":"5.11.14"}`

**Comment by PeeBee66** [comment]
This is currently still happening in 5.12.5 to all entities when ingesting malware bazaar feeds 

`category=APPerror.message=UnknownErrorerror.name=NotFounderror.stack=NotFound: UnknownError at de_NotFoundRes (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6222:23) at de_HeadObjectCommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4795:25) at processTicksAndRejections (node:internal/process/task_queues:95:5) at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24 at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20 at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46 at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24 at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20 at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 at loadFile (/opt/opencti/build/src/database/file-storage.js:171:20) at /opt/opencti/build/src/http/httpPlatform.js:167:20level=errormessage=[EXPRESS] Error http calltimestamp=2023-12-13T00:00:09.952Zversion=5.12.5
add category=APP
error=
context=
add message=UnknownError
add name=NotFound
add stack=NotFound: UnknownError at de_NotFoundRes (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6222:23) at de_HeadObjectCommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4795:25) at processTicksAndRejections (node:internal/process/task_queues:95:5) at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24 at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20 at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46 at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24 at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20 at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 at loadFile (/opt/opencti/build/src/database/file-storage.js:171:20) at /opt/opencti/build/src/http/httpPlatform.js:167:20
add level=error
add message=[EXPRESS] Error http call
add timestamp=2023-12-13T00:00:09.952Z
add version=5.12.5`
