### ISSUE TITLE
Error: Enabling photo on for image carousel on Threat Actor

### ISSUE THREAD

**Issue by ParamConstructor** [LuatixHQ/opencti#5015]
## Description

The enable photo for Carousel display within Threat Actor Individual seems to not be working properly.

## Environment

1. OS (where OpenCTI server runs): Docker container deployment
2. OpenCTI version: 5.11.14
3. OpenCTI client: Frontend / Web UI
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to Data tab of an Threat Actor Individual
2. Upload a photo (PNG in this example)
3. Change 'In Carousel' to on and click 'Update' to enable photo for the Carousel display
4. Error will pop up of: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/132086448/073d8136-a260-4dd5-9266-c9c0bb2b2a6d)

## Expected Output

The image will be enabled for carousel display

## Actual Output

Error message displayed and image is not enabled for display.

## Additional information

Logged Error on backend is:
`{"category":"APP","error":{"stacktrace":["TypeError: inputs.map is not a function","at updateAttribute (/opencti/opencti-platform/opencti-graphql/src/database/middleware.js:2130:33)","at stixDomainObjectFileEdit (/opencti/opencti-platform/opencti-graphql/src/domain/stixDomainObject.js:284:39)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"PictureManagementUtilsMutation","operation_query":"mutation PictureManagementUtilsMutation($id:ID!$input:StixDomainObjectFileEditInput){stixDomainObjectEdit(id:$id){stixDomainObjectFileEdit(input:$input){__typename importFiles{edges{node{...PictureManagementUtils_node id}}}id}}}fragment PictureManagementUtils_node on File{id name metaData{description order inCarousel}}","size":192,"time":12,"timestamp":"2023-11-30T14:45:32.998Z","type":"WRITE_ERROR","user":{"group_ids":["26aa7aa1-20ab-4097-b3b3-c24e32cc4311"],"ip":"::1","organization_ids":[],"referer":"http://opencti/dashboard/threats/threat_actors_individual/5b9a37d7-c95f-496f-a63b-e85661b03964/files","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{"id":"5b9a37d7-c95f-496f-a63b-e85661b03964","input":{"description":null,"id":"import/Threat-Actor-Individual/5b9a37d7-c95f-496f-a63b-e85661b03964/example_bad_actor.png","inCarousel":true,"order":null}},"version":"5.11.14"}`

**Comment by Jipegien** [comment]
Any update of the image (ex. description) provoke this error.
