### ISSUE TITLE
Failed exports are grayed out, causing two problems

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5016]
## Description

When exporting data from an object list, we manage the export in a side window containing the export history. When an export fails, the line is grayed out and :
1. It cannot be deleted
2. You can't see the error log by hovering over the red triangle with the mouse (as was the case before).

## Environment

5.11.14

## Reproducible Steps

You need an export that failed

## Screenshots

<img width="1568" alt="Screenshot 2023-11-30 163027" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/38ff5373-e53c-407c-9093-dfeb6e157d55">

**Comment by nino-filigran** [comment]
For information, this bug can be reproduced. Not put as critical since other Exports are working (cc @Jipegien feel free to mdify if you do not agree).
Only PDF is causing issue. 
Additionally, when clicking on the trash, you get redirected to the dashboard view.

**Comment by lndrtrbn** [comment]
I can't reproduce locally. When having a failing PDF export report I can view the error and delete the export.

![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/c871ddd8-e5a8-461a-9bc9-0ddebb82c573)

Do you still have the issue?

**Comment by nino-filigran** [comment]
Yes, still have it (I'm using the Demo environnement)

**Comment by lndrtrbn** [comment]
I suggest we wait the deployment of the release 5.12 to see if there is still the issue after that

**Comment by 2004gixxer600** [comment]
FYI I am on the latest 5.12.15, PDF's started intermittently failing hanging on .13/.14, .15 everyone is now.  Everything else working fantastic.  Just throwing it out there.
