### ISSUE TITLE
CERT-EU rss feeds not loading

### ISSUE THREAD

**Issue by PekkaJalonen** [LuatixHQ/opencti#5028]
## Description

Trying to import CERT-EU rss feeds, such as https://cert.europa.eu/publications/threat-intelligence-rss doe not import anything.

## Environment

1. Docker
2. OpenCTI version: 5.11.14
3. OpenCTI client: frontend
4. Other environment details: n/a

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create new RSS ingest and select any of the feeds from https://cert.europa.eu/publications
2. Click RSS Feed to get the feed address and set to opencti
3. Enable rss feed ingestion

## Expected Output

Receive rss articles

## Actual Output

Nothing gets imported and no logs of any errors

## Additional information

n/a

**Comment by Jipegien** [comment]
RSS ingester working for other rss feeds. CERT-EU feeds contains a blob of text at the beginning. That might cause the issue.

**Comment by PekkaJalonen** [comment]
Rss work for me also for other feeds, and i can see the "blob" when checking the feed page with browser, but not when looking at the source of the page. So could it be content-type issue?

**Comment by labo-flg** [comment]
The blob of text does not seem to be the issue here, the parsing fails when it comes to the pubDate. 
It's formatted as "Mon, 04 Dec 2023 10:25:00 CEST", the 'CEST' is an non-standard format.

I'll have a look
