### ISSUE TITLE
Ability to filter on Organization the data is shared with

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5033]
### As a user I want to be able to filter on the organisation the item is shared with so that it’s convenient for me
- Acceptance criteria: Be able to filter Objects based on Organization they are shared with
GIVEN I’m on an item that can be shared
AND I’m EE 
WHEN I look at the filter
THEN I should see the possibility to filter on Shared with 

- Acceptance criteria: The filter is only available when EE is enabled
GIVEN I’m on an item that can be shared
AND I’m not EE
WHEN I look at the filter
THEN I should not see the filter

**Comment by Jipegien** [comment]
Should be covered in #4939 because this data is contained in the schema of the Object. @Kedae are you able to confirm?

**Comment by Archidoit** [comment]
will be available in 6.0
