### ISSUE TITLE
Migrate status filter to use underlying template to simplify filter usage

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5035]
## Description

Status display several times by entity in status filter

## Reproducible Steps
- Edit a trigger filters
- Click on the status filter
- Statuses are displayed by entity type, and so displayed several times sometimes
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/4e892c31-9eea-4eb5-a280-7c9899fb4855)

**Comment by Jipegien** [comment]
Expected output : one single list with all status possible.
