### ISSUE TITLE
Can't remove search keyword from Global Search

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5039]
## Description

Can't remove search keyword from Global Search

## Reproducible Steps
Error when doing a Search

- Do a global search with no filters (all the entities are displayed)
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/65a37630-0ce2-44b5-ad3e-6bcb2244b918)

- enter a keyword in Search
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/25063a73-34b1-4c4a-a969-0a72a0b00647)

- remove the keyword in Search, tap ENTER : the only entities displayed are the one respecting the previous search keyword
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/5c7add82-f99c-464d-b619-2fbd08a7f68f)

- if you reload the page, the keyword (’test’ in this example) comes back

## Comment
The screenshort have been done with the new filters UI, but the bug is present in testing.

**Comment by Jipegien** [comment]
When no filter active, this comportment is expected.
But if you have filter active, you should be able to search an "empty" key word (example : I search reports whit the name "blabla", but then I juste want to filter on reports)

**Comment by Kedae** [comment]
I don't get how this could be the expected behavior to have a search box emptied and not the according result. 
I suggested a fix.

**Comment by Jipegien** [comment]
> I don't get how this could be the expected behavior to have a search box emptied and not the according result. I suggested a fix.

A search here with the box empty and no filter means to search everything on the entire platform. This is useless.
