### ISSUE TITLE
Issue with editing Taxonomies -> Case templates

### ISSUE THREAD

**Issue by xorhex** [LuatixHQ/opencti#5089]
## Description

docker-opencti-1                     | {"category":"APP","error":{"data":{"category":"business","http_status":500,"keys":["taskContains"],"reason":"incorrect filter keys not existing in any schema definition"},"stacktrace":["UnsupportedError: Unsupported operation","at error (/opt/opencti/build/src/config/errors.js:8:10)","at UnsupportedError (/opt/opencti/build/src/config/errors.js:80:51)","at checkAndConvertFilters (/opt/opencti/build/src/utils/filtering/filtering-utils.ts:251:15)","at listEntitiesPaginated (/opt/opencti/build/src/database/middleware-loader.ts:450:7)","at findAll (/opt/opencti/build/src/modules/task/task-template/task-template-domain.ts:17:10)","at Object.resolve [as taskTemplates] (/opt/opencti/build/src/modules/task/task-template/task-template-resolvers.ts:7:42)","at fieldResolver (/opt/opencti/build/src/graphql/authDirective.js:59:24)","at resolveFn (/opt/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)","at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:492:20)","at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:414:22)","at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:344:14)","at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)","at execute (/opt/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:504:20)","at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/requestPipeline.ts:410:28)","at processTicksAndRejections (node:internal/process/task_queues:95:5)","at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-express/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"CaseTemplateTasksLinesPaginationQuery","operation_query":"query CaseTemplateTasksLinesPaginationQuery($search:String$count:Int$orderMode:OrderingMode$orderBy:TaskTemplatesOrdering$filters:FilterGroup){...CaseTemplateTasksLines_data_3aAMmM}fragment CaseTemplateTasksLine_node on TaskTemplate{id name description}fragment CaseTemplateTasksLines_data_3aAMmM on Query{taskTemplates(filters:$filters search:$search first:$count orderMode:$orderMode orderBy:$orderBy){edges{node{id name ...CaseTemplateTasksLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}","size":203,"time":7,"timestamp":"2023-12-04T22:01:54.652Z","type":"READ_ERROR","user":{"group_ids":["<redacted>"],"ip":"<redacted>","organization_ids":[],"referer":"<redacted>","socket":"query","user_id":"<redacted>"},"variables":{"count":25,"filters":{"filterGroups":[],"filters":[{"key":"taskContains","mode":"or","operator":"eq","values":["66ef0e1c-5044-4dbf-a4ab-67590ef83118"]}],"mode":"and"},"orderBy":"name","orderMode":"asc"},"version":"5.12.1"}

## Environment

1. Docker deployment
2. OpenCTI 5.12.1

## Reproducible Steps

1. Add a new Case Template
2. Save
3. Click on the created case template to edit it.  Should receive the error.

**Comment by nino-filigran** [comment]
Bug is reproducible.
