### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'import_expected_number') a few times per minute in logs

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#5092]
## Description

After updating to 5.12.2, we are getting the errors below continuously. Please see attached file for ratio of errors/minute

`  {
    "category": "APP",
    "error": { "stacktrace": [ "TypeError: Cannot read properties of undefined (reading '_index')", "at updateReceivedTime (/opt/opencti/build/src/domain/work.js:248:30)", "at processTicksAndRejections (node:internal/process/task_queues:95:5)" ] },
    "inner_relation_creation": 0,
    "level": "error",
    "message": "API Call",
    "operation": "workToReceived",
    "operation_query": "mutation workToReceived($id:ID!$message:String){workEdit(id:$id){toReceived(message:$message)}}",
    "size": 128,
    "time": 3,
    "timestamp": "2023-12-05T08:57:24.930Z",
    "type": "WRITE_ERROR",
    "user": {
      "group_ids": [ "5ce56b5c-a968-477a-874f-6e606ba691d5" ],
      "ip": "::ffff:10.113.100.20",
      "organization_ids": [],
      "socket": "query",
      "user_id": "04417d69-14c1-44ec-af62-8724b101332f"
    },
    "variables": {
      "id": "work_6cbd1a73-9cfb-4825-9554-929cc42df702_2023-12-05T00:55:46.056Z",
      "message": "Connector ready to process the operation"
    },
    "version": "5.12.2"
  }
  {
    "category": "APP",
    "error": { "stacktrace": [ "TypeError: Cannot read properties of undefined (reading 'import_expected_number')", "at updateProcessedTime (/opt/opencti/build/src/domain/work.js:257:19)", "at processTicksAndRejections (node:internal/process/task_queues:95:5)" ] },
    "inner_relation_creation": 0,
    "level": "error",
    "message": "API Call",
    "operation": "workToProcessed",
    "operation_query": "mutation workToProcessed($id:ID!$message:String$inError:Boolean){workEdit(id:$id){toProcessed(message:$message inError:$inError)}}",
    "size": 242,
    "time": 3,
    "timestamp": "2023-12-05T08:57:24.936Z",
    "type": "WRITE_ERROR",
    "user": {
      "group_ids": [ "5ce56b5c-a968-477a-874f-6e606ba691d5" ],
      "ip": "::ffff:10.113.100.20",
      "organization_ids": [],
      "socket": "query",
      "user_id": "04417d69-14c1-44ec-af62-8724b101332f"
    },
    "variables": {
      "id": "work_6cbd1a73-9cfb-4825-9554-929cc42df702_2023-12-05T00:55:46.056Z",
      "inError": true,
      "message": "{'name': \"Cannot read properties of undefined (reading '_index')\", 'message': \"Cannot read properties of undefined (reading '_index')\"}"
    },
    "version": "5.12.2"
  }
`

[error.log.2023-12-05.json](https://github.com/OpenCTI-Platform/opencti/files/13557654/error.log.2023-12-05.json)

## Environment

Ubuntu bare metal.

**Comment by AlexSanchezN** [comment]
More information.

The errors have gone after some time. We think they may be related to a connector and they only appear when that connector has pending work. 
We will try to diagnose which connector is throwing the errors

**Comment by SamuelHassine** [comment]
Hello,

This issue only appears if you remove the work of a connector and you still have messages to process attached to the work.

You can just ignore them.

Kind regards,
Samuel

**Comment by AlexSanchezN** [comment]
OK, Thanks!
