### ISSUE TITLE
Be able to take information from SSO and have it in all activity logs in "context_login"

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5105]
## Use case

Be able to take information from SSO and have it in all activity logs in "context_login"

**Comment by nino-filigran** [comment]
@SamuelHassine can you specify a little bit more?
With the current logs, you cannot differentiate if a user connects through username/pwd or through SSO? What are the info that you would need to include in the logs that in SSO?

**Comment by SamuelHassine** [comment]
Duplicate of #5434 (OOB @richard-julien).
