### ISSUE TITLE
Modifications are not always applied to client in streaming

### ISSUE THREAD

**Issue by ristowee** [LuatixHQ/opencti#5141]
## Description

Modifications and deletions are not always applied to objects at “streaming client”.

If a field (e.g. the "Malware types") is empty on the client side the modifications on the server side are applied also in the receiver. If the field already contains something the changes are discarded.

Multiple additions seem to work for the labels but deleting them does not.

## Environment

1. OS (where OpenCTI server runs): Debian 10 (Docker)
2. OpenCTI version: OpenCTI 5.12.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

1. Create 2 instances (a server and a client)
2. Start a stream on the server and listen to it on client (enable "Take deletions into account")
3. Create e.g. a Malware on the server (keep "Malware types" field empty)
4. Observe it appear on the client
5. Add something in "Malware types" on the server
6. Observe it appear on the client
7. Add something else in "Malware types" on the server
8. **The new value is not added on the client "Malware types" field**
9. Add a label on the server
10. Observe it appear on the client
11. Delete the label on the server
12. **The second label remains on the client**

## Expected Output

Modifying fields on the server should be reflected on the client. It should be possible since the stream event contains a `patch` and `reverse_patch` fields.

At least additions should be "merged" like the data from the connectors are merged to the existing data. Deletions may be more difficult.

## Actual Output

The new value is not added in the field. Label deletions are not applied on the client.

## Additional information

Two `update` events captured from the stream:

A working event (the first addition):
```json
{
  "version": "4",
  "type": "update",
  "scope": "external",
  "message": "replaces `bot` in `Malware types`",
  "origin": {
    "socket": "query",
    "ip": "::ffff:10.152.53.72",
    "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f",
    "group_ids": [
      "360e1bad-6fe7-40b2-92ac-cb5a5d3b3716",
      "1896593c-bdc3-4513-83d0-7a847fc2a404"
    ],
    "organization_ids": [
    ],
    "referer": "http://sync-test2.local:8080/dashboard/arsenal/malwares/a77309ce-6044-4640-8582-84b09f3623b5"
  },
  "data": {
    "id": "malware--5486c95a-46a0-5bbb-b906-00510c32ddc3",
    "spec_version": "2.1",
    "type": "malware",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "property-extension",
        "id": "a77309ce-6044-4640-8582-84b09f3623b5",
        "type": "Malware",
        "created_at": "2023-08-28T09:57:04.923Z",
        "updated_at": "2023-12-07T10:15:45.403Z",
        "is_inferred": false,
        "creator_ids": [
          "88ec0c6a-13ce-5e39-b486-354fe4a7084f"
        ]
      }
    },
    "created": "2023-08-28T09:57:04.923Z",
    "modified": "2023-12-07T10:15:45.403Z",
    "revoked": false,
    "confidence": 14,
    "lang": "en",
    "labels": [
      "warzone"
    ],
    "name": "TestMalware",
    "description": "Malware for stream testing",
    "malware_types": [
      "bot"
    ],
    "is_family": false
  },
  "context": {
    "patch": [
      {
        "op": "replace",
        "path": "/modified",
        "value": "2023-12-07T10:15:45.403Z"
      },
      {
        "op": "replace",
        "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
        "value": "2023-12-07T10:15:45.403Z"
      },
      {
        "op": "add",
        "path": "/malware_types",
        "value": [
          "bot"
        ]
      }
    ],
    "reverse_patch": [
      {
        "op": "remove",
        "path": "/malware_types"
      },
      {
        "op": "replace",
        "path": "/modified",
        "value": "2023-12-07T10:09:40.452Z"
      },
      {
        "op": "replace",
        "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
        "value": "2023-12-07T10:09:40.452Z"
      }
    ]
  }
}
```
The second addition, which is not applied on the client:
```json
{
  "version": "4",
  "type": "update",
  "scope": "external",
  "message": "replaces `bot, dropper` in `Malware types`",
  "origin": {
    "socket": "query",
    "ip": "::ffff:10.152.53.72",
    "user_id": "88ec0c6a-13ce-5e39-b486-354fe4a7084f",
    "group_ids": [
      "360e1bad-6fe7-40b2-92ac-cb5a5d3b3716",
      "1896593c-bdc3-4513-83d0-7a847fc2a404"
    ],
    "organization_ids": [
    ],
    "referer": "http://sync-test2.local:8080/dashboard/arsenal/malwares/a77309ce-6044-4640-8582-84b09f3623b5"
  },
  "data": {
    "id": "malware--5486c95a-46a0-5bbb-b906-00510c32ddc3",
    "spec_version": "2.1",
    "type": "malware",
    "extensions": {
      "extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba": {
        "extension_type": "property-extension",
        "id": "a77309ce-6044-4640-8582-84b09f3623b5",
        "type": "Malware",
        "created_at": "2023-08-28T09:57:04.923Z",
        "updated_at": "2023-12-07T10:29:29.421Z",
        "is_inferred": false,
        "creator_ids": [
          "88ec0c6a-13ce-5e39-b486-354fe4a7084f"
        ]
      }
    },
    "created": "2023-08-28T09:57:04.923Z",
    "modified": "2023-12-07T10:29:29.421Z",
    "revoked": false,
    "confidence": 14,
    "lang": "en",
    "labels": [
      "warzone"
    ],
    "name": "TestMalware",
    "description": "Malware for stream testing",
    "malware_types": [
      "bot",
      "dropper"
    ],
    "is_family": false
  },
  "context": {
    "patch": [
      {
        "op": "add",
        "path": "/malware_types/1",
        "value": "dropper"
      },
      {
        "op": "replace",
        "path": "/modified",
        "value": "2023-12-07T10:29:29.421Z"
      },
      {
        "op": "replace",
        "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
        "value": "2023-12-07T10:29:29.421Z"
      }
    ],
    "reverse_patch": [
      {
        "op": "remove",
        "path": "/malware_types/1"
      },
      {
        "op": "replace",
        "path": "/modified",
        "value": "2023-12-07T10:15:45.403Z"
      },
      {
        "op": "replace",
        "path": "/extensions/extension-definition--ea279b3e-5c71-4632-ac08-831c66a786ba/updated_at",
        "value": "2023-12-07T10:15:45.403Z"
      }
    ]
  }
}
```

**Comment by richard-julien** [comment]
The stream is working the same as a connector in case of upserting elements.
Current choice of the platform for now on is to not remove multiple data in case of upsert but to always cumulate.
So upserting labels, vocabularies, etc will never removed information.
The listen deletion event is to intercept and apply deletion of a complete entity or core relationship but never data "inside" an element.

For the other problem about cumulate new malware types (_The new value is not added on the client "Malware types" field_), for now im not able to reproduce, in your example I obtains ""bot" and  "dropper" in the synchronized platform.

**Comment by ristowee** [comment]
Thanks for checking @richard-julien.
I understand the decision behind skipping the deletion. You would not want other people to delete things remotely. However, this makes correcting mistakes quite difficult (syncing the corrections if it means deleting something). I just wonder why the `"op": "remove"` events are sent if they are not used?
I upgraded my test system to 5.12.5 to see if the problem persists. Now, adding more malware types succeeded. Also the description field change worked. Either something has been updated after .3 or there was something wrong in my system.
I think this ticket can be closed.

**Comment by richard-julien** [comment]
**I just wonder why the "op": "remove" events are sent if they are not used?**

This event is used. If you delete the full malware, it will be deleted in the remote platform. The problem here is more about downgrading an existing data that is part of the malware.

If you have a remote source that represent the authority you can maybe use the stream using the perfect sync option.
If you use that, all data absorbed through this stream will do a perfect sync to the data. This option was designed to be used in case of internal data sharing where you rely only one 1 source of data and so want to have a perfect view of the remote authority.

![image](https://github.com/OpenCTI-Platform/opencti/assets/285555/2266eab7-5d59-4651-bfba-2afc426917e7)

We could also imagine to later add an option to only rely on confidence to apply any change without this "downgrade prevention". But this will be a dangerous option because will only works correctly if all the connector will have a different confidence level.
