### ISSUE TITLE
Missing translations in investigation screen in expand dialog

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#5142]
## Description

Some translations are missing in investigation screen. 

They are prefixed `entity_` but should be prefixed `relationship_` I think (see Localization.js).

## Environment

OCTI 5.12.3

## Reproducible Steps
 start an investigation, add an entity, double click on the entity in the graph to open the expansion dialog.

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/45a7f6cc-3042-42f2-a2ae-82c400152e78)

**Comment by Jipegien** [comment]
@lndrtrbn Is it possible to name all this relationships with the following pattern: "nameofrelationship (relationship)". Ex: Located at (relationship) ?

**Comment by lndrtrbn** [comment]
I think it is possible
