### ISSUE TITLE
URL Import error

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#5148]
OpenCTI version: 5.12.2

An error occurs when I try to import multiple URLs into the report.

![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/9fc7bf47-85ca-472a-8904-f477b116b3f9)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/ac69355e-4929-42c7-9872-111beb6e4997)

The list of URLs to import is as follows.

http://154.38.126.29:5002
http://112.104.136.201:5002
http://www.nvoue.site:5002
http://mloixa.atbo.shop:5002
http://118.170.54.96:5002
http://zwlort.ldtz.life:5002
http://118.170.54.150:5002
http://123.204.19.170:5002
http://xms.yeelip.com:6693
http://aoi.wzli.life:5002
http://www.pnrxa.site:5002
http://198.44.188.69:5002
http://rnlio.dinl.life:5002
http://43.251.117.182:5002
http://107.151.255.187:5002
http://zciosare.xiol.shop:5002
http://suio.irhw.shop:5002
http://123.204.132.165:5002
http://118.170.19.211:5002
http://ckloi.irhw.shop:5002
http://43.250.175.120:5002
http://noizs.bdty.life:5002
http://118.170.54.210:5002
http://www.amcu.site:5002
http://silpzx.dinl.life:5002
http://axms.yeelip.com:6693

I would appreciate it if you could tell me the solution.

**Comment by Archidoit** [comment]
@misohouse  This is a bug linked to the filters refacto. We'll have a look at it!

**Comment by Archidoit** [comment]
I can't reproduce your bug. Is your client-python up to date (upgraded after the release)?

**Comment by SamuelHassine** [comment]
Hello,

This bug has been solved in 5.12.13.

Kind regards,
Samuel

**Comment by misohouse** [comment]
@SamuelHassine Oh, Thank you! I'll upgrade my OpenCTI. :)
