### ISSUE TITLE
Bad current state display in Taxii Feeds

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5151]
Go to Data > Ingestion > Taxii Feeds
The 'current state' column display only a blue square

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/42c8e35b-8e0a-4686-8dcb-8b91577bf578)

**Comment by SamuelHassine** [comment]
URL of the feed is not correct on testing.

**Comment by SamuelHassine** [comment]
But still an error to fix when feed is in 404: https://github.com/OpenCTI-Platform/opencti/issues/5147.
