### ISSUE TITLE
Error in some RSS feeds again

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5158]
## Description

Some RSS feeds don't work exactly in this previous issue : https://github.com/OpenCTI-Platform/opencti/issues/5081

Still a 403 error appears but the URL is accessible when I access it directly from my browser.

## Environment

5.12.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import these feeds with the RSS feed feature ("Data > Ingestion > RSS Feeds"):
         - https://sploitus.com/rss
         - https://www.wago.com/global/rss/psirt/rss.xml

## Additional note

It was a user-agent problem before, maybe it's still this. If so, here's my working user-agent (if it helps):

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by SamuelHassine** [comment]
Fixed in 5.12.5.
