### ISSUE TITLE
The top of the graph view in an entity is broken

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5164]
## Description

In a non-container entity (e.g. Intrusion set, Malware, Org, ...), the view available in "Analyses > Graph view" is not displayed correctly. See screenshot.

## Environment

5.12.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an Intrusion set 
2. Navigate on its "Analyses" tab
3. Change for the "Graph view"

## Screenshots

<img width="1566" alt="Screenshot 2023-12-11 065551" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/f174a54a-97a7-4bc5-ab10-80a8ef717551">

**Comment by Jipegien** [comment]
@jpkha
