### ISSUE TITLE
Can't delete artifacts

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5166]
## Description

Can't delete artifacts.

## Reproducible Steps for deletion via an entity overview
Go to an artifact overview.
Try to delete it.
An error message is displayed: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/9580d5c7-e5aa-453a-a867-789f41bd10b4)

## Reproductible steps for deletion via background tasks
Select some artifacts via the checkboxes.
Delete them via the button in the tool bar.
Launch the background task.
Nothing is deleted.
In Data>Processing>Tasks, you can see that the background task has errors: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3f0fec8c-a001-414b-8c44-24806cb085a9)

**Comment by labo-flg** [comment]
the delete operation fails in `deletAllObjectFiles`

cc @richard-julien maybe something related to bb0387e4 ?

**Comment by labo-flg** [comment]
`allFilesForPaths` is missing field `Key` in the returned objects, hence the final error in the UI.

**Comment by richard-julien** [comment]
Yes, maybe related :(
Depends if artefact have on going export/import (aka work) associated
