### ISSUE TITLE
Error when exporting report as PDF

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5171]
## Description

Error when exporting a report, whether a simple or full export

## Environment

1. OS (where OpenCTI server runs): 
2. OpenCTI version: 5.12.5
3. OpenCTI client: web
4. Other environment details: Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Export report as PDF

## Actual Output

Error:
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/d2ce6181-c262-4064-bca6-e6dce46a1ae2)

{'name': 'DatabaseError', 'message': '[SEARCH] Expect only one response'}

**Comment by labo-flg** [comment]
it works on latest testing environment

**Comment by SamuelHassine** [comment]
What is the status @yassine-ouaamou @labo-flg? Can we close?

**Comment by labo-flg** [comment]
Issue not reproducible. I advise to close this one.
