### ISSUE TITLE
Connectors not correctly sorted

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5173]
## Description

The list is not properly sorted. It seems to be sorted alphabeticaly

## Environment

Environment details: Prod instance

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Data > Connectors
2. Sort by Messages

## Expected Output

Correctly sorted

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/af7e667e-8a7d-4ba0-a082-d4961006780e)

**Comment by richard-julien** [comment]
I dont think its possible to sort on the messages as they are fetched directly from rabbitMQ management API.
I think we need to remove the UI capability to sort on messages

**Comment by SamuelHassine** [comment]
This list is frontend sorted, 8 is before 6... (alphabetically). We need to enhance the sorting function to better handle numbers.

**Comment by Jipegien** [comment]
@marieflorescontact do you see a way to enhance the sorting to be able to handle numeric value? and how much time you think it will take ?

**Comment by marieflorescontact** [comment]
> @marieflorescontact do you see a way to enhance the sorting to be able to handle numeric value? and how much time you think it will take ?

Pr is open @Jipegien
