### ISSUE TITLE
[Playbooks] "Apply predefined rule" without objects is not working

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5177]
## Description

The actions performed during a playbook are not performed when an "Apply predefined rule" component is present, despite the fact that the data in the "send for ingestion" logs is correct.

The same playbook without the  "Apply predefined rule" component works as expected. I've carried out a number of tests (e.g. location of the component in the playbook sequence, activation/deactivation of the "Manipulate all elements included in the bundle" options for other components, ...) but I haven't detected any particular logic behind this bug.

## Environment

5.12.5

### Works

1. Create the following Playbooks:
Listen on Report modification --> Manipulate data to add the label "test-label" -> Send for ingestion

It works

-----------------------------------------------

### Doesn't work

Create the following Playbooks:
Listen on Report modification --> Apply predefined rule: Resolve container references (add in bundle) --> Manipulate data to add the label "test-label" -> Send for ingestion

It doesn't work despite the fact that I can see the label on the report in the "send for ingestion" logs (see screenshot).

#### My playbooks:

<img width="469" alt="Screenshot 2023-12-11 191245" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/329bfc5e-9ed5-4762-8b0e-a989924c5f92">

#### The execution logs:

<img width="625" alt="Screenshot 2023-12-11 191332" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/abe8b812-38e6-4fc3-93af-a0046bda1842">

#### Send for ingestion logs:

<img width="678" alt="Screenshot 2023-12-11 184945" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/0e74d1d7-0548-474c-b566-ac906d816b32">

#### My report AFTER playbook execution:

<img width="1482" alt="Screenshot 2023-12-11 185004" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/26a87284-6e4b-4ab5-abf2-bd22a067656d">

**Comment by Jipegien** [comment]
@SamuelHassine or @richard-julien can you check this issue please?
@Lhorus6 can you confirm the platform version is 5.12.5?

**Comment by Lhorus6** [comment]
Ah oui pardon 5, pas 15 ;) 
(sur testing)

**Comment by Lhorus6** [comment]
After retesting, it was impossible to reproduce the bug described in this ticket. However, another error was observed:

## Error

{
  "message": "Cannot set properties of undefined (setting 'labels')",
  "stack": "TypeError: Cannot set properties of undefined (setting 'labels')\n    at Object.add (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:14:16)\n    at applyOperation (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:235:60)\n    at Object.applyPatch (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:280:22)\n    at Object.executor (/opt/opencti/build/src/modules/playbook/playbook-components.ts:585:17)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:135:44)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:202:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:202:9)\n    at playbookStreamHandler (/opt/opencti/build/src/manager/playbookManager.ts:268:13)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:613:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:667:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:684:13)",
  "name": "TypeError"
}
