### ISSUE TITLE
Sometimes import of Stix files stay in progress for ever

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#5178]
## Description

Sometimes importing files get stuck in an infinite state of "in progress".

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on Data import
2. Upload a json file that contains stix data
3. Validate workbench if needed
4. Import starts

Reported with importFileStix connector, but may happens with others import connectors.

## Expected Output

Import finish with a "green check" icon and all data is imported

## Actual Output

Import is stuck, and the progress loop is there for ever. Data is not imported or not totally imported.

## Additional information

Current workaround:
- retart worker and/or restart import.

## Screenshots (optional)
<img width="1578" alt="Screenshot 2023-12-08 141035" src="https://github.com/OpenCTI-Platform/opencti/assets/3634942/98e64ee2-c9dc-4a6a-a93c-44213b341058">

**Comment by Jipegien** [comment]
@aHenryJard did you identified the cause of the blocking progress?

**Comment by SamuelHassine** [comment]
Solved in 5.12.9.
