### ISSUE TITLE
Some filters don't support all modes and operators in widgets

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5181]
## Description
In widgets, relationship_type, elementId and entity_type filters are always done with operator=eq, mode (inside the filter)=or, mode (with other filters)=and.

## Reproducible Steps
An example :

Create a widget with filters: relationship_type = uses OR related-to
The displayed graph is correct.
Same with filters: relationship_type = uses AND related-to
-> we have the same graph (the graph is done with operator 'OR')

**Comment by AliceGrey** [comment]
@Archidoit I'm not sure if this is related to this issue but the dashboard widgets appear to not be working the same as investigations. When making a widget that should show Intrusion Sets that tharget the Utilities sector I get no results. When using investigations to do the same expansion I get several results. If this isn't related to this issue I can open a new one.
<img width="1154" alt="Screenshot 2023-12-12 at 12 07 12 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/8949059/c69faf5e-b525-4824-bab3-7d02335f5e30">
<img width="1154" alt="Screenshot 2023-12-12 at 12 07 21 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/8949059/493c06c2-b571-4fe0-8dc6-b59cd4308f4a">
<img width="694" alt="Screenshot 2023-12-12 at 12 08 20 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/8949059/8a4b394e-b890-48c9-822d-bb12069d2110">

It's working for me... I have the correct result.

**Comment by AliceGrey** [comment]
P.S. The dashboard has no date filter set and the widget has these additional settings
<img width="836" alt="Screenshot 2023-12-12 at 12 12 35 PM" src="https://github.com/OpenCTI-Platform/opencti/assets/8949059/7dac4fa5-76d6-4aeb-b03a-663916d9b5fb">

**Comment by Archidoit** [comment]
> P.S. The dashboard has no date filter set and the widget has these additional settings <img alt="Screenshot 2023-12-12 at 12 12 35 PM" width="836" src="https://private-user-images.githubusercontent.com/8949059/289947330-7dac4fa5-76d6-4aeb-b03a-663916d9b5fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTY1NzgsIm5iZiI6MTcwMjQ1NjI3OCwicGF0aCI6Ii84OTQ5MDU5LzI4OTk0NzMzMC03ZGFjNGZhNS03NmQ2LTRhZWItYjAzYS02NjM5MTZkOWI1ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDgzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA2ZDU0YTk0YjNkYTIzZTFmNGZkMTRiN2UyY2I3Yzk3ZjU5MjFkMjFkMTc1MGQ1MmQyOTJmYmRiNGY1OGY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hzCx0tP9aDurOV1jlTlk7X4yQenLFATuGx0dbghIUUs">

The dashboard date filters are something else. They set the date limitations for all the widgets.
The 'date attribute' additional settings you mentionned is the date taken into account (for ordering, constructing the graph etc) in the widget you are created.
