### ISSUE TITLE
RFI and RFT created by a playbook cannot be updated

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5197]
## Description

RFI and RFT created by a playbook cannot be updated -> "Error An unknown error occurred. Please contact your administrator or the OpenCTI maintainers."

## Environment

5.12.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an playbook that create a RFT or RFI (Cases)
2. Go to the RTF or RFI created by the playbook
3. Try to update it

-> Crash

## Screenshots 
<img width="698" alt="Screenshot 2023-12-13 183020" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/93c6a9ee-658e-407a-817c-be1782a337b2">

**Comment by nino-filigran** [comment]
@SamuelHassine or @richard-julien tagging you in there since it seems you guys know how this work!
