### ISSUE TITLE
Update from 5.11.14 to 5.12.0 seems to not work, getting database errors.

### ISSUE THREAD

**Issue by Crankinator** [LuatixHQ/opencti#5199]
## Prerequisites

- [ x ] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem. (PS. These don't seem to link to anything anymore, but I did look where I could and have been using the system)
- [ x ] I went through old GitHub issues and couldn't find anything relevant
- [ x ] I googled the issue and didn't find anything relevant

## Description

Running a development OpenCTI system with minimal connectors (all OCTI builtin) at 5.11.14 with everything working as intended, wanting to move to 5.12. When pushing the update, I run into an error on the platform. I understand that there were filter conversions, but I do not utilize any custom connectors that should be using these filters.

I am at a loss here, will keep chipping away but figured I would shoot a question.

## Environment

1. EKS, ArgoCD + AWS ECR
2. OpenCTI version: 5.11.14->5.12
3. OpenCTI client: frontend GUI
4. Other environment details:
Redis, RabbitMQ, and Minio are at their latest versions according to the charts from Bitnami

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Update EKS OpenCTI cluster to 5.12.0 from 5.11.14

## Additional information

Database error log, domain redacted for security purposes.

`{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"_stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:748:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elCreateIndexTemplate (/opt/opencti/build/src/database/engine.js:554:3)\n    at elCreateIndex (/opt/opencti/build/src/database/engine.js:806:3)\n    at Sdu.up (/opt/opencti/build/src/migrations/1698678031958-create-index-files.js:8:3)","data":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"index template [opencti_files] has index patterns [opencti_files*] matching patterns from existing templates [opencti-index-template] with patterns (opencti-index-template => [opencti*]) that have the same priority [0], multiple index templates may not match during index creation, please use a different priority","root_cause":[{"reason":"index template [opencti_files] has index patterns [opencti_files*] matching patterns from existing templates [opencti-index-template] with patterns (opencti-index-template => [opencti*]) that have the same priority [0], multiple index templates may not match during index creation, please use a different priority","type":"illegal_argument_exception"}],"type":"illegal_argument_exception"},"status":400},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"763","content-type":"application/json; charset=UTF-8","date":"Wed, 13 Dec 2023 17:47:24 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://search.opencti.dev.eks.REDACTEDDOMAIN.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://search.opencti.dev.eks.REDACTEDDOMAIN.com/"},"context":null,"name":"opensearch-js","request":{"id":27,"options":{},"params":{"body":"{\"index_patterns\":[\"opencti_files*\"],\"template\":{\"settings\":{\"plugins\":{\"index_state_management\":{\"rollover_alias\":\"opencti_files\"}}},\"mappings\":{\"dynamic_templates\":[{\"integers\":{\"match_mapping_type\":\"long\",\"mapping\":{\"type\":\"integer\"}}},{\"strings\":{\"match_mapping_type\":\"string\",\"mapping\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"normalizer\":\"string_normalizer\",\"ignore_above\":512}}}}}],\"properties\":{\"internal_id\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"normalizer\":\"string_normalizer\",\"ignore_above\":512}}},\"standard_id\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"normalizer\":\"string_normalizer\",\"ignore_above\":512}}},\"height\":{\"type\":\"nested\",\"properties\":{\"measure\":{\"type\":\"float\"},\"date_seen\":{\"type\":\"date\"}}},\"weight\":{\"type\":\"nested\",\"properties\":{\"measure\":{\"type\":\"float\"},\"date_seen\":{\"type\":\"date\"}}},\"timestamp\":{\"type\":\"date\"},\"created\":{\"type\":\"date\"},\"created_at\":{\"type\":\"date\"},\"modified\":{\"type\":\"date\"},\"modified_at\":{\"type\":\"date\"},\"indexed_at\":{\"type\":\"date\"},\"uploaded_at\":{\"type\":\"date\"},\"first_seen\":{\"type\":\"date\"},\"last_seen\":{\"type\":\"date\"},\"start_time\":{\"type\":\"date\"},\"stop_time\":{\"type\":\"date\"},\"published\":{\"type\":\"date\"},\"valid_from\":{\"type\":\"date\"},\"valid_until\":{\"type\":\"date\"},\"observable_date\":{\"type\":\"date\"},\"event_date\":{\"type\":\"date\"},\"received_time\":{\"type\":\"date\"},\"processed_time\":{\"type\":\"date\"},\"completed_time\":{\"type\":\"date\"},\"ctime\":{\"type\":\"date\"},\"mtime\":{\"type\":\"date\"},\"atime\":{\"type\":\"date\"},\"current_state_date\":{\"type\":\"date\"},\"confidence\":{\"type\":\"integer\"},\"attribute_order\":{\"type\":\"integer\"},\"base_score\":{\"type\":\"integer\"},\"is_family\":{\"type\":\"boolean\"},\"number_observed\":{\"type\":\"integer\"},\"x_opencti_negative\":{\"type\":\"boolean\"},\"default_assignation\":{\"type\":\"boolean\"},\"x_opencti_detection\":{\"type\":\"boolean\"},\"x_opencti_order\":{\"type\":\"integer\"},\"import_expected_number\":{\"type\":\"integer\"},\"import_processed_number\":{\"type\":\"integer\"},\"x_opencti_score\":{\"type\":\"integer\"},\"connections\":{\"type\":\"nested\"},\"manager_setting\":{\"type\":\"flat_object\"},\"context_data\":{\"properties\":{\"input\":{\"type\":\"flat_object\"}}}}}},\"composed_of\":[\"opencti-core-settings\"],\"version\":3,\"_meta\":{\"description\":\"To generate opencti expected index mappings\"}}","headers":{"content-length":"2239","content-type":"application/json","user-agent":"opensearch-js/2.4.0 (linux 5.10.199-190.747.amzn2.x86_64-x64; Node.js v20.10.0)"},"method":"PUT","path":"/_index_template/opencti_files","querystring":"create=false","timeout":30000}}},"statusCode":400},"name":"ResponseError"},"http_status":500,"reason":"[SEARCH] Error creating index template"},"internalData":{},"name":"DatabaseError","time_thrown":"2023-12-13T17:47:24.426Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:399:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:229:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-12-13T17:47:24.428Z","version":"5.12.0"}`

**Comment by SamuelHassine** [comment]
Hello,

Please try to update directly to 5.12.5 and not 5.12.0.

**Comment by Crankinator** [comment]
Will do! Will follow up shortly.

**Comment by Crankinator** [comment]
Looks like another error unfortunately. Editing because it is not the same error it seems.

`{"category":"APP","error":{"context":{"category":"technical","error":{"_error":{},"_showLocations":false,"_showPath":false,"_stack":"DatabaseError: A database error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/engine.js:800:11\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at elUpdateMapping (/opt/opencti/build/src/database/engine.js:794:3)\n    at tNu.up (/opt/opencti/build/src/migrations/1700492747686-update-manager-configuration.js:15:3)","data":{"category":"technical","error":{"meta":{"body":{"error":{"reason":"No handler for type [flat_object] declared on field [manager_setting]","root_cause":[{"reason":"No handler for type [flat_object] declared on field [manager_setting]","type":"mapper_parsing_exception"}],"type":"mapper_parsing_exception"},"status":400},"headers":{"access-control-allow-origin":"*","connection":"keep-alive","content-length":"271","content-type":"application/json; charset=UTF-8","date":"Wed, 13 Dec 2023 19:44:00 GMT"},"meta":{"aborted":false,"attempts":0,"connection":{"_openRequests":0,"deadCount":0,"headers":{},"id":"https://search.opencti.dev.eks.REDACTED.com/","resurrectTimeout":0,"roles":{"data":true,"ingest":true},"status":"alive","url":"https://search.opencti.dev.eks.REDACTED.com/"},"context":null,"name":"opensearch-js","request":{"id":28,"options":{},"params":{"body":"{\"properties\":{\"uploaded_at\":{\"type\":\"date\"},\"manager_setting\":{\"type\":\"flat_object\"}}}","headers":{"content-length":"87","content-type":"application/json","user-agent":"opensearch-js/2.4.0 (linux 5.10.199-190.747.amzn2.x86_64-x64; Node.js v20.10.0)"},"method":"PUT","path":"/opencti_stix_meta_relationships-000001%2Copencti_history-000001%2Copencti_inferred_relationships-000001%2Copencti_stix_domain_objects-000001%2Copencti_inferred_entities-000001%2Copencti_stix_cyber_observables-000001%2Copencti_stix_sighting_relationships-000001%2Copencti_files-000001%2Copencti_stix_meta_objects-000001%2Copencti_stix_core_relationships-000001%2Copencti_internal_relationships-000001%2Copencti_internal_objects-000001/_mapping","querystring":"","timeout":30000}}},"statusCode":400},"name":"ResponseError"},"http_status":500,"reason":"[SEARCH] Error updating index mapping"},"internalData":{},"name":"DatabaseError","time_thrown":"2023-12-13T19:44:00.938Z"},"http_status":500,"reason":"[OPENCTI] Platform initialization fail"},"message":"An unknown error has occurred","name":"UnknownError","stack":"UnknownError: An unknown error has occurred\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:72:47)\n    at platformInit (/opt/opencti/build/src/initialization.js:399:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at platformStart (/opt/opencti/build/src/boot.js:229:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-12-13T19:44:00.940Z","version":"5.12.5"}`

This development instance hasn't had many changes done to it, mainly just removal of the test TAXII feed I created months ago.

**Comment by SamuelHassine** [comment]
Hello,

It seems you are using an outdated version of OpenSearch. Please note that OpenSearch >= 2.9 is required as noted in https://docs.opencti.io/latest/deployment/overview/#dependencies.

Kind regards,
Samuel
