### ISSUE TITLE
[Dashboards] Difficulties to click on a line on a list widget

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5218]
## Description

When creating a list widget, I can't click on lines. It actually works but randomly after trying many times.

## Environment

Environment details: Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a list wiget on a dashboard
2. Click on a line
3. { e.g. Error ... }

## Expected Output

Redirect to the entity/relation corresponding to the clicked line

## Actual Output

Can't click on lines. It actually works but randomly after trying many times.

## Screenshots (optional)
![issue_list_widget](https://github.com/OpenCTI-Platform/opencti/assets/7083405/987c3776-a70b-4639-8be9-b8351da4bd05)

**Comment by SamuelHassine** [comment]
I know how to fix this.
