### ISSUE TITLE
Filters 'value' on observables of type File is not working

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5225]
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/908507aa-f4b4-4516-bc9f-2cb76033a202)

same for other observables like autonomous system

**Comment by richard-julien** [comment]
I dont think its a bug, its more related to the model and the translation of the "representation" of an observable that we named "value". I think for more clarity we need to rename the column value to "representation". (value in the filter match the "value" attribute that is not the same that the file name)
