### ISSUE TITLE
Bad design in the triggers of a user

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5232]
Settings > Security > overview of a user
Bad design in the 'filters and digest' part (there is a 'point'):
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/d7492937-9d93-4067-8237-a7347c04ac9d)

**Comment by SarahBocognano** [comment]
@marieflorescontact No need to adjust the point in trigger as suggested in your PR. @jpkha is opened a PR already :)
