### ISSUE TITLE
``backup-files`` connector and full backup

### ISSUE THREAD

**Issue by mbonino** [LuatixHQ/opencti#5240]
## Prerequisites

- [x] I read the [Deployment and Setup](https://www.notion.so/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://www.notion.so/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hello,

I'd like to pick your brain on this issue.

I'm currently using the ``backup-files`` connector to backup my OpenCTI platform but I'm having a hard time understanding how it really works.

I started using it after I had already created a lot of campaigns, organisations, etc
I can't find any of them in the JSON files generated by the connector.

It looks to me the connector produces a sort of incremental forever backup with no initial full backup, am I right ?

If that's the case, is it possible to take a full backup/snapshot of the platform ?

Thanks.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
2. OpenCTI version: OpenCTI 5.12
3. OpenCTI client: N/A
4. Other environment details:

**Comment by labo-flg** [comment]
What about using a full synchronization to a remote - backup - OCTI instance?

Data > Ingestion > Remote OCTI Stream and hit '+' to create a new synchronizer.

In the creation form, in advanced settings, tick the option "Use Perfect Synchronization" to replicate the instance

See docs: https://docs.opencti.io/latest/usage/import-automated/?h=

**Comment by nino-filigran** [comment]
@mbonino did this solution work for you?

**Comment by mbonino** [comment]
Hello,

I'm currently on annual leave so I won't be able to test the solution until next week.

However, the main concern with this approach is that replication is not a backup.

If a user deletes by mistake a campaign for example, I won't be able to restore it.

**Comment by nino-filigran** [comment]
@mbonino we're working on a solution called logical deletion, that would definitively solve that pain. I let you have a look at the ticket here for a full description: https://github.com/OpenCTI-Platform/opencti/issues/1536

In short, we'll introduce a new state, "removed", that will allow you to recover elements that you have removed.

**Comment by nino-filigran** [comment]
@mbonino I'm closing this ticket given I did not get a feedback since then. Feel free to reopen it if you have any questions.
