### ISSUE TITLE
When sorting a list with a filter without value being selected, sorting works but also opens the filter.

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5263]
## Description

When I'm on a list view of OpenCTI and I have a filter (without value, but at least, a filter chosen) and I'm clicking on a column to sort it (DESC / ASC ), my column gets sorted but the filter box gets opened.

The steps to reproduce are tricky. Please contact me if need be. 
## Environment

Demo environnement 

## Reproducible Steps

Scenario 1: In a screen without filter chosen
1. Select a filter
2. Do not interact with the filter (do not change operator nor the value)
3. Sort a column
4. The column gets sorted and the filter box opens

Scenario 2: In a screen with a filter that has already a value
1. Select a filter
2. Provide a value to a filter
3. Navigate to another page
4. Go back to the page
5. Delete all filters in the screen
6. Add a new filter 
7. Do not interact with the filter (do not change operator nor the value)
8. Sort a column
9. The column gets sorted and the filter box opens

**Scenario 3**: In a screen with a filter without value but that you have interacted with
1. Provide a value to a filter
2. Remove the value of the filter
3. Keep the filter empty in that page
4. Navigate to another page
5. Go back to that page
6. Delete all filters on the page 
7. Add a new filter 
8. Do not interact with the filter (do not change operator nor the value)
9. Sort a column
10. The column gets sorted and the filter box opens

## Expected Output

Only the column gets sorted, the filter box should not opened

## Actual Output

The filter box gets opened.

**Comment by jpkha** [comment]
just fixed it and merge. Can you try again ? I think it's the same: https://github.com/OpenCTI-Platform/opencti/issues/5254
