### ISSUE TITLE
[DASHBOARD] Entity statuses on the dashboard

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#5265]
## Use case

I need to display report statuses on the Donut widget on the dashboard. This is necessary to compare the number of analyzed reports with the number of unanalyzed ones

## Current Workaround
Status attribute is missing

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/9b0904d2-0e92-4af6-8c66-5a522582f583)

## Proposed Solution

Add status attribute in widget parameters. It needs to look like the screenshot below

![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/a21640c3-a4e8-4546-b089-0b42a02b8714)

**Comment by nino-filigran** [comment]
The final solution needs to be discussed but the use case is valid. Indeed we could think of a wider solution which is to have all attributes of the selected entity type as a parameter to avoid case by case tackling of issue. This is anyway to be defined
