### ISSUE TITLE
Export button on Investigation does nothing

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5271]
## Description

Investigations have an export button that has no effect when clicked. Was this button accidentally added with the dashboard export feature? If so, it should be removed.

If not, we need to fix the problem and add an import option, as I can't currently see how to import an Investigation.

## Environment

OCTI 5.12.9

#### Export button on Investigation

<img width="833" alt="291961239-6244cd8f-34c3-45b6-85e6-0413693485a5" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/ac1e5c0c-d3e0-4aac-8b2e-5c05f342342e">

<img width="832" alt="Screenshot 2023-12-20 175111" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/d3e0a972-997f-4fb1-b9dc-0e2a864495e1">

#### Query response when I click on the button (so I guess it's a side effect of adding dashboard export):

<img width="958" alt="Screenshot 2023-12-20 175257" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/3c8a9db6-2866-45df-92b7-63ff74f8634b">

**Comment by explorecti** [comment]
Also broken on version 5.12.5.

**Comment by Lhorus6** [comment]
@explorecti I don't think it's broken, IMO it's a non-existent feature. This button shouldn't be there

**Comment by nino-filigran** [comment]
Agreed and reproduced, I'm wondering if [this ](https://github.com/OpenCTI-Platform/opencti/issues/2515) could be potentially the source. If the feature does not exist, the CTA should be removed in both screens.

**Comment by CelineSebe** [comment]
We checked, I'm looking for a way to remove this export button
