### ISSUE TITLE
The search is broken in "Add in container"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5276]
## Description

When you are on an entity and want to add it to a container using the "Add in container" button in the top right-hand corner, it is not possible to search among existing containers. When typing text, no characters are taken into account in the search.

## Environment

OCTI 5.12.9

## Reproducible Steps

1. Go to an Incident
2. Click on the "Add in container" button
3. Tried searching for an existing Report
-> No text typed on keyboard is taken into account

**Comment by nino-filigran** [comment]
Reproduced
