### ISSUE TITLE
The platform adds a second extension to the file

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5278]
## Description

When importing a file, the platform (or import connectors?) adds a second extension to the file (see screenshot).

nb: It seems to be only on the interface because when I download my file again, it doesn't have two extensions locally.

## Environment

OCTI 5.12.9

## Reproducible Steps

1. Import a file and view its name

## Screenshots 

<img width="560" alt="Screenshot 2023-12-20 200226" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/6ec17a58-7c17-45b6-9605-18ebd5c45023">

**Comment by nino-filigran** [comment]
Cannot reproduce on Demo env. On which environement did you try @Lhorus6 ? 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/dbf95f7b-8eb6-4629-be5b-b71db24792e1)

**Comment by SamuelHassine** [comment]
Reproduced in testing.
