### ISSUE TITLE
Document import crashes when importing from "Events > Incidents > [any Incident] > Data tab"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5279]
## Description

Document import with the ImportDocument connector crashes when importing from "Events > Incidents > [any Incident] > Data tab". 

NB:
- I tried with a txt file, the bug appears (see screenshot).
- I tried with a json file and no bug. So it seems to be linked exclusively to the ImportDocument connector.
- I tried from the "Data" tabs of Intrusion Set and Organization and no bug either. So it seems to be present exclusively on Incidents.

Attached are the file I used to test.

## Environment

OCTI 5.12.9

## Reproducible Steps

1. import attached file from "Events > Incidents > [any Incident] > Data tab" -> Crash
2. import attached file elsewhere (e.g. in the global import panel at the top right of the interface) -> Work

#### Error from "Events > Incidents > Data"

<img width="434" alt="Screenshot 2023-12-20 200948" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/f336d2e9-3bc8-495e-87fa-5eb7bc7fc451">

#### Work in the general import panel

<img width="538" alt="Screenshot 2023-12-20 202213" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/709ee0a8-27e8-4926-9bf0-a3b49e9e2368">

## The file 

[Partner report.txt](https://github.com/OpenCTI-Platform/opencti/files/13731399/Partner.report.txt)

**Comment by nino-filigran** [comment]
@Lhorus6 I cannot reproduce. On which environment did you try?

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/0f522113-8d71-4c22-96c6-477749745445)
