### ISSUE TITLE
Crash when importing a pdf file

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5280]
## Description

The pdf import doesn't work, an error appears. The import location doesn't change anything. Here are the two pdfs that I tested and that produced the same error:
- https://www.cert.ssi.gouv.fr/uploads/CERTFR-2023-CTI-001.pdf
- https://www.cert.ssi.gouv.fr/uploads/20220309_NP_WHITE_ANSSI_panorama-menace-ANSSI.pdf

Please see the error in the screenshot below

## Environment

OCTI 5.12.9

## Reproducible Steps

1. Go to the general panel to import file (in the top right of the interface).
2. Try to import one of the pdf given in attachment.

## Screenshots

<img width="558" alt="Screenshot 2023-12-20 202550" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/987551b3-cc13-4ba8-a071-47f1fee3f986">

**Comment by nino-filigran** [comment]
@Lhorus6 I cannot reproduce, on which environment did you try? See my comment where I successfuly managed to upload a PDF

https://github.com/OpenCTI-Platform/opencti/issues/5278#issuecomment-1865836466
