### ISSUE TITLE
Problems with proxy connections through the Apache server.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#5290]
**OpenCTI Version : 5.12.9 (Latest)**

I have an **Apache web server(192.168.200.154)** in front of **my Opencti server(192.168.200.121)**, proxying it to prevent OpenCTI load balancing and for added security.

Normal page views and the like will work just fine.

The problem occurs in the **"DATA" tab in the report**. When I upload a file, **it seems to be accessing the webserver's storage instead of the OpenCTI server's storage.**

Here's what I did.
**1. Click Tt(Copy/paste text content)
2. Input 2 IPs and click IMPORT button.
3. Click IMPORT file
4. Error occurs**
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/cd4256be-9826-4077-93e3-3db7203b80bc)
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/c3988077-2048-4495-92f0-fb459bbfaa2c)

'
'
'
'
'
'

In the proxy settings, I have set Storage to be proxied to the OpenCTI server as well, but it is not working correctly.

The following shows the proxy settings on the Apache server.
![image](https://github.com/OpenCTI-Platform/opencti/assets/19428462/fafb25a5-7cd2-4cd0-adf3-f2d08075705e)

I need to check if I'm doing something wrong or if it's a problem with the OpenCTI feature.

Any suggestions on how to fix this would be appreciated.

**Comment by nino-filigran** [comment]
@misohouse could you please also try to ask your question our slack channel, using the openCTI channel please?

**Comment by nino-filigran** [comment]
@misohouse did you manage to get support?

**Comment by misohouse** [comment]
@nino-filigran 

Hi, No, I haven't gotten any support yet, I'm currently using OpenCTI directly without using a proxy server.

Please send me with your solution and I'll try to implement it to system.

**Comment by nino-filigran** [comment]
@Kedae do you think you can provide support for this?

**Comment by nino-filigran** [comment]
@misohouse from our understanding, this seem to be a config issue, not a openCTI issue. Having said this, we have lots of bugs and issues to handle at the moment, and do not have the bandwith to dive into this issue of yours right now, so we don't have a solution for you. We'll look into when we have time, but I cannot tell when this will be. 

Sorry for not having a better answer for you.
