### ISSUE TITLE
CSV mapper => bug while ingesting malware entity?

### ISSUE THREAD

**Issue by R3dHash** [LuatixHQ/opencti#5300]
## Description

Hello, as reported on Slack https://filigran-community.slack.com/archives/CHZC2D38C/p1703196931785729 I could not manage to ingest a malware entity from a CSV via the CSV mapper module. 
I placed as a test two columns with headers separated with semi column (malware_name and is_family with 'test' and false as values, respectively). See screenshots below: 

I checked the oasis 2.1 STIX documentation and the only difference I see maybe is the required "malware_types" field that is actually optional in opencti but it did not solve my problem unfortunately. 

## Environment

OpenCTI version:  OpenCTI 5.12.9

## Expected Output

I expect to see as when I tried with Intrusion Set entity that results into json data while running a test from the CSV mapper.

## Actual Output

No data can be previewed while running a test via the CSV mapper. Data are empty [ ]

## Screenshots (optional)
![image (1)](https://github.com/OpenCTI-Platform/opencti/assets/97284989/7b51ca9b-b40e-423b-8a37-451866be99a2)
![image](https://github.com/OpenCTI-Platform/opencti/assets/97284989/a90f566a-eeaf-4a0a-8180-ed7a29b281b8)

**Comment by nino-filigran** [comment]
Reproduced on 5.12.14.

**Comment by R3dHash** [comment]
As a follow up from discussions on Slack, it seems to work when the is_family boolean state is on True but then we can't ingest malware instances (when is_family is False).
