### ISSUE TITLE
cannot share feed 

### ISSUE THREAD

**Issue by mrd7790** [LuatixHQ/opencti#5301]
Description

Im creating CSV feed sharing but no data shows in result 

1. OS (where OpenCTI server runs): ubuntu22
2. OpenCTI version: 5.12.5

Reproducible Steps

Steps to create the smallest reproducible scenario:
Click Data > Data Sharing
Click Feeds CSV > Click '+' to add a new feed
ENTITY TYPES : ipv4-Addr

Additional information
![Screenshot from 2023-12-25 13-12-25](https://github.com/OpenCTI-Platform/opencti/assets/38424327/288ca337-6598-405b-94bc-c41a5494410c)
![Screenshot from 2023-12-25 13-12-51](https://github.com/OpenCTI-Platform/opencti/assets/38424327/22c15d39-3cd3-44c7-8ea8-dee1c919553e)
![Screenshot from 2023-12-25 13-16-09](https://github.com/OpenCTI-Platform/opencti/assets/38424327/d584ffc0-063c-4ab4-8dbc-dd045e479b3a)

**Comment by nino-filigran** [comment]
@mrd7790 in the last screenshot you posted, I assume it's IPV4 adresses that were already present in your platform. Am I right?
Do you still have the issue? 
Can you also share the feed that you're trying to use so that we can try it out on our side?

**Comment by mrd7790** [comment]
@nino-filigran yes IPV4 addresses are in my platform
I still have this problem, I want to give a list of IPs to the fortigate firewall, but I can't produce such an output!
I would be grateful if you could guide me so that I can generate a csv output

**Comment by mrd7790** [comment]
done!

**Comment by argithubtogo** [comment]
Hi @mrd7790, I am facing similar issue with the native csv feed in OpenCTI showed nothing.
May I know what did you do to solve this?
