### ISSUE TITLE
Locations is empty

### ISSUE THREAD

**Issue by isms-core-project** [LuatixHQ/opencti#5302]
Hi,
I am running the latest Docker Image and Locations is not populated at all.
No Regions, no countries, no areas and no cities.

Docker:

connector-opencti:
image: opencti/connector-opencti:5.11.13
environment:
- OPENCTI_URL=http://opencti:8080/
- OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
- CONNECTOR_ID=${CONNECTOR_IMPORT_DATESETS_ID} # Valid UUIDv4
- CONNECTOR_TYPE=EXTERNAL_IMPORT
- "CONNECTOR_NAME=OpenCTI Datasets"
- CONNECTOR_SCOPE=marking-definition,identity,location
- CONNECTOR_CONFIDENCE_LEVEL=100
- CONNECTOR_UPDATE_EXISTING_DATA=true
- CONNECTOR_RUN_AND_TERMINATE=false
- CONNECTOR_LOG_LEVEL=error
- CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
- CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
- CONFIG_COMPANIES_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/companies.json
- CONFIG_REMOVE_CREATOR=false
- CONFIG_INTERVAL=7 # In days
restart: always

Container Error:
{'name': 'Variable "$input" got invalid value null at "input.id"; Expected non-nullable type "ID!" not to be null.', 'message': 'Variable "$input" got invalid value null at "input.id"; Expected non-nullable type "ID!" not to be null.'}

Any chance to fix this so we do not need to import the json files manually.
TY in advance.
BR
Greg

**Comment by SouadHadjiat** [comment]
This issue has also been created on connectors project : https://github.com/OpenCTI-Platform/connectors/issues/1651
I'm closing it here, so it can be fixed on the connectors side
