### ISSUE TITLE
"An unknown error occurred..." in distribution of opinions of a report

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#5306]
## Description

When you click on "Distribution of opinions" of a report (see pictures below), the "An unknown error occurred..." panel appears.

## Environment

1. OS (where OpenCTI server runs): macOS Sonoma 14.2.1
2. OpenCTI version: 5.12.13
3. OpenCTI client: frontend with Firefox 121
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a report in the list of reports
2. Click on "Distribution of opinions"

## Expected Output

The distribution of opinions concerning the selected report.

## Actual Output

Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Screenshots (optional)

The selected report

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/18c9026c-fa04-45e5-a2f7-79746930365b)

The result after clicking on "Distribution of opinions"

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/10f4257b-54a5-4c9b-a01c-44141d19b4e7)

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/4931b5be-415d-4100-ae08-ae2369ceda0b)

**Comment by Archidoit** [comment]
It seems that you have no opinions available. Do you see opinions in Settings > Taxonomies > Vocabularies > opinion_ov ? If, not you should create some opinions there and then try to open the 'Distribution of opinions' panel' again in reports.
Anyway, an error should not occur even if there are no opinions. We'll have a look at this issue.

**Comment by JeromeSRT** [comment]
> It seems that you have no opinions available. Do you see opinions in Settings > Taxonomies > Vocabularies > opinion_ov ? If, not you should create some opinions there and then try to open the 'Distribution of opinions' panel' again in reports.
> 
> Anyway, an error should not occur even if there are no opinions. We'll have a look at this issue.

I have some opinions in Settings > Taxonomies > Vocabularies > opinion_ov, see picture below.

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/84acfdff-1a7e-4bb6-babf-0917b3cc61b4)

**Comment by Archidoit** [comment]
I have no error when there are opinions in vocabulary, but an error when there are no opinions. I'm going to fix the bug in case no opinion exist. @JeromeSRT

**Comment by JeromeSRT** [comment]
> I have no error when there are opinions in vocabulary, but an error when there are no opinions. I'm going to fix the bug in case no opinion exist. @JeromeSRT 

Hello,

Have you observed the same problem with the relationships form of entities when you click on the relationships button ?

I do an update in the next days and I confirm you the problem or not.

Happy new year...

**Comment by Archidoit** [comment]
@JeromeSRT I have reproduced an error with the relationship view of entities. The issue will be resolved here : https://github.com/OpenCTI-Platform/opencti/issues/5331
Happy new year :)
