### ISSUE TITLE
No status in the list of "Workflow of Report"

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#5307]
## Description

The added status don't appear in the list of Workflow of Report.

## Environment

1. OS (where OpenCTI server runs): macOS Sonoma 14.2.1
2. OpenCTI version: 5.12.13
3. OpenCTI client: frontend with Firefox 121 
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Acccess to the "Customization" tab
2. Choose "Report"
3. Click on pencil workflow
4. Add status with his order

## Expected Output

List of status associated to the Workflow of Report

## Actual Output

List of status is empty

## Screenshots (optional)

Access to the customization of report tab

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/7c2f4ab0-e84a-4afd-925e-133bb276ae5c)

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/4929f0f5-5536-4b41-9563-508585ac3b11)

Add some status in the Workflow of Report

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/3488d2b2-9226-4403-b944-e935e22c7009)

List of status added to the Workflow of Report

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/90a83c26-c2bb-4ffa-a00d-62c0f85d983d)

**Comment by JeromeSRT** [comment]
Add some status in the Workflow of Report

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/913e0e6e-1faf-4acd-9ec6-f50bed83fb76)

**Comment by nino-filigran** [comment]
@JeromeSRT I can't manage to reproduce your bug (I'm on the 5.12.14). could you try to upgrade to this version to see if the problem persists?

As you can see I've added two statues (one created from scratch and the other by choosing from the list). Additionally, have you tried with different orders (I assume that you did) 

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/9c0a9211-6023-41d2-9f56-2781fd6cc81a)

**Comment by JeromeSRT** [comment]
> @JeromeSRT I can't manage to reproduce your bug (I'm on the 5.12.14). could you try to upgrade to this version to see if the problem persists?
> 
> 
> 
> As you can see I've added two statues (one created from scratch and the other by choosing from the list). Additionally, have you tried with different orders (I assume that you did) 
> 
> 
> 
> ![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/9c0a9211-6023-41d2-9f56-2781fd6cc81a)
> 
> 

@nino-filigran,

I updated to 5.12.14, and the "Workflow of Report" is always empty.
May be I have a problem with the privileges of OpenCTI index in Elasticsearch. Where can I find the parameters to configure the privileges in OpenCTI index ?

Thanks.

**Comment by nino-filigran** [comment]
I'll come back to you on this question. Can you also please raise your question on Slack please?

**Comment by SouadHadjiat** [comment]
I still can not reproduce, but I qualify this issue as a bug and continue to investigate

**Comment by JeromeSRT** [comment]
> I'll come back to you on this question. Can you also please raise your question on Slack please? 

Hello @nino-filigran,
I updated to 5.12.15, and I have the same trouble above.

**Comment by SamuelHassine** [comment]
@SouadHadjiat @nino-filigran Can we please qualify this one definitely?

**Comment by SouadHadjiat** [comment]
@SamuelHassine For now I couldn't reproduce the issue and I still don't know why and how it is happening (but it is definitely happening).
Here is some details about the investigation : 
This query : 
```
query { 
  subType(id: "Report") {
    id
    label
    statuses {
      id
      template {
        name
      }
      order
    }
    settings {
      id
      entity_type
    }
  }
}
```
returns this result : 

![image](https://github.com/OpenCTI-Platform/opencti/assets/668192/207ea2a8-9075-41cb-bdb4-317c4513d4af)

But if we query directly statuses, we can list them all correctly :
```
query {
  statuses {
    edges {
      node {
        id
        order
        type
        template {
          name
        }
      }
    }
  }
}
```

**Comment by SamuelHassine** [comment]
@JeromeSRT can you ping me on Slack we will schedule a live troubleshooting session please.

**Comment by JeromeSRT** [comment]
> @JeromeSRT can you ping me on Slack we will schedule a live troubleshooting session please.

@SamuelHassine, which channel can I use to ping you ? I'm gathering some information on the configuration of my OpenCTI platform. I send you a request by the end of the week.

**Comment by Jipegien** [comment]
Do we have some update on this subject? @JeromeSRT & @SamuelHassine
