### ISSUE TITLE
No items in the drop-down list of "Report types" in the "Update a report" form

### ISSUE THREAD

**Issue by JeromeSRT** [LuatixHQ/opencti#5309]
## Description

The drop-down list of "Report types" is empty in the "Update report" form.

## Environment

1. OS (where OpenCTI server runs): macOS Sonoma 14.2.1
2. OpenCTI version: 5.12.13
3. OpenCTI client: frontend with Firefox 121
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Choose a report
2. Click on the update button
3. Click on the drop-down list of "Report types"

## Expected Output

The list of "Report types" is not empty

## Actual Output

No report types in the list.

## Screenshots (optional)

Choose the report to update 

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/cbe30368-c366-401d-89ed-d7f2f23f53c3)

Choose the drop-down list

![image](https://github.com/OpenCTI-Platform/opencti/assets/68632445/e564fdc5-7f08-4152-8c19-e6c13e778092)

**Comment by nino-filigran** [comment]
@JeromeSRT I cannot reproduce your bug. Indeed, my list is complete. Could you please check that you have a list of reports types in your taxonomy (under the report_types_ov)?

**Comment by JeromeSRT** [comment]
> @JeromeSRT I cannot reproduce your bug. Indeed, my list is complete. Could you please check that you have a list of reports types in your taxonomy (under the report_types_ov)?
> 
> 
> 
> 

@nino-filigran ,

Yes I have a list of report types in the taxonomies concerning report_types_ov.

Thanks.

**Comment by JeromeSRT** [comment]
> @JeromeSRT I cannot reproduce your bug. Indeed, my list is complete. Could you please check that you have a list of reports types in your taxonomy (under the report_types_ov)?
> 
> 
> 
> 

Hello @nino-filigran,

I updated to 5.12.14, and I have the same trouble described above.

**Comment by SouadHadjiat** [comment]
@JeromeSRT do you see items in "reliability" drop-down list ?

**Comment by JeromeSRT** [comment]
> @JeromeSRT do you see items in "reliability" drop-down list ?

@SouadHadjiat nope, I don't see items in "reliability" drop-down list.
