### ISSUE TITLE
ERR Platform unmanaged direct error (unable to start platform)

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#5337]
## Description

Upon trying to start OpenCTI (v5.12.15) stack, the following error is observed and the platform will not start:

`ERR Platform unmanaged direct error | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:70:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at platformStart (/opt/opencti/build/src/boot.js:236:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.","name":"TypeError","stack":"TypeError: Cannot destructure property 'password_policy_min_length' of 't' as it is undefined.\n    at checkPasswordInlinePolicy (/opt/opencti/build/src/domain/user.js:407:5)\n    at checkPasswordFromPolicy (/opt/opencti/build/src/domain/user.js:459:18)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at addUser (/opt/opencti/build/src/domain/user.js:489:5)\n    at initAdmin (/opt/opencti/build/src/domain/user.js:1386:5)\n    at initializeAdminUser (/opt/opencti/build/src/config/providers.js:45:5)\n    at platformInit (/opt/opencti/build/src/initialization.js:374:7)\n    at platformStart (/opt/opencti/build/src/boot.js:232:5)"}] timestamp=2024-01-02T10:11:21.158Z version=5.12.15`

I can't think of any changes that may have caused this. 

## Environment

1. Ubuntu 22.04.3 LTS
2. OpenCTI 5.12.15
3. Frontend
4. Other environment details:
Docker via Portainer

## Reproducible Steps

Start stack

## Expected Output

Platform starts

## Actual Output

Platform does not start

**Comment by RegturH** [comment]
I have had the same issue. What I found is the platform is performing a query:  containing these: `             "terms": {
                      "internal_id.keyword": [
                        "ed673371-5655-470c-85db-4630b43a55b5"
                      ]
                    }
                  },
                  {
                    "terms": {
                      "standard_id.keyword": [
                        "ed673371-5655-470c-85db-4630b43a55b5"
                      ]
                    }
                  },
                  {
                    "terms": {
                      "x_opencti_stix_ids.keyword": [
                        "ed673371-5655-470c-85db-4630b43a55b5"
                      ]` This ID is not correct if we change this it works. The settings have been deleted indeed. Could this be solved or is there a sollution?

**Comment by nino-filigran** [comment]
@dominictory and @RegturH could you please also raise your issue on Slack? I'm not able to reproduce it here.

**Comment by dominictory** [comment]
> @dominictory and @RegturH could you please also raise your issue on Slack? I'm not able to reproduce it here.

I originally raised on Slack but wanted to raise here also for visibility. I have since decided to rebuild as a number of settings were, for some reason, deleted from the platform since upgrading to 5.12.15. I was originally on 5.12.9 when the platform wouldn't come up, but wanted to upgrade to enable the better error logging.

**Comment by nino-filigran** [comment]
@dominictory Got it, sorry for the trouble. Hope things are working fine now.

**Comment by RegturH** [comment]
We had to wipe the whole platform and changed our elastic snapshot timefram from 4 days to 14 days
