### ISSUE TITLE
[Dashboards] Map widget filter problem

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5339]
## Environment

Environment: Testing (5.12.15)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a map widget of countries being targeted by campains targeting the **Finance** Sector
2. Create a map widget of countries being targeted by campains targeting the **Diplomacy** Sector
3. Create a map widget of countries being targeted by campains targeting the **Finance OR Diplomacy** Sector

Example of the first widget:
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/6cc05021-b408-45f4-9b3a-2bff4ea975e5)

## Expected Output

The third widget should include all the coutries from the two first widgets

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/f8fd6dc6-59ad-4bb6-9da9-b4472991401e)

## Additional information

A dashboard has been created with the concerned widgets: https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/dda4d333-061e-4234-8cbe-ded17bb94819

**Comment by Archidoit** [comment]
To be also done: reset filters in the widget pop-up

**Comment by Archidoit** [comment]
If the result of the dynamicFrom is empty, the dynamicFrom filter is no more taken into accout.
