### ISSUE TITLE
Bulk search no longer works 

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5341]
## Description

When you perform a search using the "bulk search" function (notebook logo with magnifying glass in the top right-hand corner), the search continues indefinitely.

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on the bulk search window
2. Search for you want (e.g. "1.1.1.1")
-> The search never ends, i.e. nothing appears and the moving blue search banner (the visual animation of the search) continues.

**Comment by SarahBocognano** [comment]
It seems to be linked to filters :
![Capture d'écran 2024-01-03 173455](https://github.com/OpenCTI-Platform/opencti/assets/98532359/dd25689b-b2b9-451b-b3ce-c0a633836b41)
