### ISSUE TITLE
Indicator overview page unknown error

### ISSUE THREAD

**Issue by lesley-tw** [LuatixHQ/opencti#5347]
## Description
Indicator overview page have error: `An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.`

## Environment
Upgrade from OpenCTI `5.3.17` to OpenCTI `5.11.12`

## Reproducible Steps
1. Go to Indicator list
2. Enter into one of indicator

## Expected Output
Show indicator overview

## Actual Output
Unknow error
![Screenshot 2024-01-03 at 3 38 33 PM](https://github.com/OpenCTI-Platform/opencti/assets/9364352/37f76e38-b2ef-4a2a-b6c1-59abeac1c31b)

I could find that the graphql query has already returned the indicator results.
![Screenshot 2024-01-03 at 4 59 24 PM](https://github.com/OpenCTI-Platform/opencti/assets/9364352/154cd3a5-bd62-4046-84f3-3ddf764d841e)

Other tabs like `Knowledge`, `Analyses`, `Sightings`, `Data`, `History` showed correct information.

**Comment by richard-julien** [comment]
Can you check the browser error console ? thanks

**Comment by lesley-tw** [comment]
> Can you check the browser error console ? thanks

Hi @richard-julien 

Following is the console screenshot.
![image](https://github.com/OpenCTI-Platform/opencti/assets/9364352/0882aeb5-91f8-4927-8e44-768e5730ce39)

**Comment by trend-lesley-lin** [comment]
Finally found that it was a frontend bug in our site.
This issue could be closed.
Thanks a lot.
