### ISSUE TITLE
The view on relationships in a knowledge tab crashes

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5352]
## Description

The view on relationships in a knowledge tab crashes. I tried on several entities, and different browser (Edge and Firefox) same results.

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to any Country
2. Go to the Knowledge tab
3. Go to a category for which your Country has relations (e.g. All threats)
4. Try to display the view on relationships (see point 6 on screenshot below)

#### Before clicking on the relationship view (point 6)
<img width="1715" alt="Screenshot 2024-01-03 124403" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/09d446e1-13cc-4c58-83ff-a0485f77e08f">

### After
<img width="1708" alt="Screenshot 2024-01-03 124532" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/7b3143d6-714b-42c7-8290-390bcd71c596">

<img width="518" alt="Screenshot 2024-01-03 124059" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/d4b355ef-87a0-44a9-874c-692b62a7f95e">

**Comment by Archidoit** [comment]
@jpkha  same problem here with the filters ids

**Comment by jpkha** [comment]
I cannot reproduce it on master branch. I think it's solved with the other similar issue but it did not deploy yet on testing env.
I will try later.

**Comment by SamuelHassine** [comment]
Already fixed, duplicate.
