### ISSUE TITLE
Investigation graph dezoom and loses the entity (v2)

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5368]
## Description

Exactly the same bug as described here has reappeared : https://github.com/OpenCTI-Platform/opencti/issues/4776

## Environment

OCTI 2.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Report
2. Go on knowledge tab
3. Add only one entity in the graph
-> The graph dezoom until the entity is lost.

NB: Note that this has less impact than before, as we now have a button to refocus the view.

**Comment by nino-filigran** [comment]
Indeed, it de-zooms, but I still can view the entity. This is anyway a bug to be fixed.

**Comment by lndrtrbn** [comment]
@Lhorus6 @nino-filigran can I have more info please (browser, type of entity) ?
I can't reproduce the issue. On my side when I follow what is described, the zoom works well.

**Comment by SamuelHassine** [comment]
@nino-filigran @Lhorus6 Can we please qualify this one definitely?

**Comment by nino-filigran** [comment]
@lndrtrbn still happens in 5.12.17

I'm using Chrome Version 120.0.6099.217 (Build officiel) (64 bits). I've created a report, with only a name. Then added an indicator (be12e55c7b524947e974677557fc1fda52083891b6aa9bbf9b17341fd9480f5a), using the Public demo environment.

**Comment by Lhorus6** [comment]
Indeed, still there in 5.12.17

I am using Firefox 121.0.1 (64-bit) and I did exactly what @nino-filigran did

**Comment by Jipegien** [comment]
@Lhorus6 is this bug still present in the last version?

**Comment by Lhorus6** [comment]
@Jipegien Yes still there in 5.12.21 (tested now on the filigran prod instance with Firefox 122.0 (64-bit))

**Comment by lndrtrbn** [comment]
Well. I still can't reproduce following steps described in the issue.
Tested on both Edge and Firefox for platforms: local, testing and demo.

**Comment by nino-filigran** [comment]
@lndrtrbn here's a video, recorded on demo
https://github.com/OpenCTI-Platform/opencti/assets/148041607/20bb9d48-7439-4c44-853c-74f65eead239

**Comment by Jipegien** [comment]
Can't reproduced it. A button allows to have the graph view back in order easily. Won't fix for now
