### ISSUE TITLE
Error trying to export with specific API, fromId, toId, fromType etc.. - Data > Relationship 

### ISSUE THREAD

**Issue by jpkha** [LuatixHQ/opencti#5370]
## Description

When selecting specials filters (fromId, toId, fromType, toType) and trying to export we got an error : "incorrect filter keys not existing in any schema definition"

![image](https://github.com/OpenCTI-Platform/opencti/assets/18297909/c8264782-7d41-4ed2-b41a-1336000fb62a)

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Go to Data > Relationships page
2. Select some relationships
3. Click on top-right button "Open export panel"
4. Choose csv export and click "Create"

## Expected Output

Should export with the specials filters

## Actual Output

Got an error

**Comment by nino-filigran** [comment]
I'm not even getting an error on the UI: the screen just freezes. 

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/d6901b23-9b25-43e7-814d-9dd91dcc9cd5)

**Comment by jpkha** [comment]
@nino-filigran should be related to this issue, and just have been solved.
https://github.com/OpenCTI-Platform/opencti/commit/a59e764697b9a437586b87e982ddef97f145b049

Looks like there is still some issue with the synchronisation between the branch master and the deployment on testing.

**Comment by nino-filigran** [comment]
Retested on testing and it works.

**Comment by jpkha** [comment]
Similar error in this case (intrusion sets > knowledge > attacks pattern > export  : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/18297909/bab96f63-e53b-4b37-8547-313b76e25c1c)
