### ISSUE TITLE
Can't create activity digest

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5377]
## Reproducible Steps
- Go to Settings > Activity (EE should be enabled)
- Go to Alerting
- Create an activity trigger
- Create an activity digest
- An error occurs
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f6ab0c3b-0ef8-4527-9819-83854856214f)

**Comment by richard-julien** [comment]
Will be fixed in https://github.com/OpenCTI-Platform/opencti/pull/5340
