### ISSUE TITLE
Can't update log sources of a course of action

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5384]
Go to Techniques > Courses of action
Edit a course of action.
Edit the 'log sources' field to add sources.
You can't edit the field: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/9b3b989d-4777-4eb5-9a6c-0c8a2e8b2cbd)

**Comment by labo-flg** [comment]
See how it's done in ThreatActorGroup > Details > Goals

It should work the same~ish

**Comment by labo-flg** [comment]
Will be fixed in https://github.com/OpenCTI-Platform/opencti/pull/5340
