### ISSUE TITLE
Edit button present in an Analyse screen

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5385]
Go to a malware
Go to the 'Analysis' tab
The edit button is present whereas it is not in other Analysis tabs (ex: in Attack patterns > Analysis, no edit button).
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/38f474a2-ceaa-4136-acea-ad4b44f164f9)

**Comment by CelineSebe** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/4caddad6-fa43-4193-a0a2-d8e71baa5284)

To be sure, is it about this "edit" button?

**Comment by Archidoit** [comment]
No, it's about the pink edit button at the bottom right
