### ISSUE TITLE
Can't create a threat actor individual with roles

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5386]
Create a threat actor individual. In the creation form, enter a name and values for 'roles' (in the 'details' tab).
Error occurs when you click on the 'create' button : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/ac347f29-ac94-4356-84ed-496b56be7226)

**Comment by richard-julien** [comment]
Will be fixed in https://github.com/OpenCTI-Platform/opencti/pull/5340
