### ISSUE TITLE
Default value of a Registry Key is not properly shown in Workbench

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5387]
## Environment

Environment details: Testing (5.12.15)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import a txt file with a list of registry keys (example below)
2. Go to its analyst workbench 
3. Go to Observables section

## Expected Output

The default value column should show the name of the entity (value of register key)

## Actual Output

"Unkown" is shown

## Additional information

Here are two registry key examples to test:
HKEY_LOCAL_MACHINE\SOFTWARE\Adobe
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Office

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/e1b27f62-7239-4fff-8bd1-ddca324ac790)

**Comment by Lhorus6** [comment]
NB: It seems to be only the display in the workbench. Once the workbench has been validated, the registry key created is correct

**Comment by Jipegien** [comment]
Probably something related to the fact that registry key has no "name" property.

**Comment by lndrtrbn** [comment]
Can you provide a valid file to import please ? I don't know with what to test, when I copy the example above in a text file and try to import it, the import fails

EDIT : import should not fail (other issue), for now, using csv mapper to test this issue
