### ISSUE TITLE
Settings platform announcements with recipients are not visible to all admins

### ISSUE THREAD

**Issue by SouadHadjiat** [LuatixHQ/opencti#5396]
## Description

If you set a platform announcement with specified recipients, other plaform admins won't see the setting in the list.

Here is what I see when I set a platform announcement with a recipient (me) : 
![Capture d'écran 2024-01-04 153744](https://github.com/OpenCTI-Platform/opencti/assets/668192/cc5d4182-0218-46b5-89d4-00e2ce78f9e0)

And here is what other admins see : only the platform announcement without recipient, not the one I created.
![capture-bug-platform-announcements](https://github.com/OpenCTI-Platform/opencti/assets/668192/c1977b6a-c51f-47a7-84d1-512067063ccf)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 5.12.15
3. OpenCTI client: frontend
4. Other environment details: reproduced on testing and prod

**Comment by Kedae** [comment]
@richard-julien I'll try to take a look at it but at first sight it seems that we need to rework a bit how we are using settings query

**Comment by richard-julien** [comment]
PR done, please review @Kedae
