### ISSUE TITLE
Breakdown of graphs do not work anymore.

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5420]
## Description

Breakdown of graph do not work when using an entity.

Environment 

Demo

**Steps to reproduce**
1. Brekadwon by entity 
- create a dash
- add a widget
- select the "knowedge graph" visualisation
- add the following as a relation "source type = malware AND relation type = targets AND target type = country"
- click on the + to add a new entity
- add the following attributes "entity type = malware AND relation type = targets"
- in the visualisation, select "malware types"
- validate

2. Breakdwon by relation 
- create a dash
- add a widget
- select the "knowedge graph" visualisation
- add the following as a relation "source type = malware AND relation type = targets AND target type = country"
- click on the + to add a new relation
- add the following attributes "source type = malware AND relation type = targets"
- in the visualisation, select "entity type"
- in the visu, display the source for each.
- validate

Expected output: 
1. breakdown by entity: We should see a list of mawlare targeting some countries, broken down by the amount of types of malware.
2. breakdown by relation:  We should see a list of mawlare targeting some countries, broken down by the amount relations having as source malware and as a relation targets.

Current output: 
1. Breakdown by entity: **it does not work.** We see a list which is not broken down and when hovering, the value is "others = value of the line". 
2. Breakdown by relation: it works, we see a list of relations broken down.
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/87674745-f3fe-4b67-9009-464afa5384d4)

**Comment by nino-filigran** [comment]
@SamuelHassine just to be clear, I've specified 2 scenarios (adding an entity to breakdwon and adding a relation to breakdown) and the relation one is working as expected.

**Comment by SamuelHassine** [comment]
What were the most common Impact (TA0040) techniques observed in incidents targeting the government sector in the last year?
Killchain filtering on "uses" relationship from incident to attack pattern
Breakdown Horizontal Bar Chart
