### ISSUE TITLE
Add information from authentication (headers) in audit logging

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5434]
## Use case

Be able add in a specific key (for instance "extra_auth") information coming from SSO (ie. headers) in the audit logging.

This should be optional.

Config

```
"header": {
      "strategy": "HeaderStrategy",
      "config": {
        "disabled": false,
        "header_email": "auth_email_address",
        "header_name": "auth_matricule",
        "header_firstname": "auth_firstname",
        "header_lastname": "auth_lastname",
        "headers_audit": ["Auth-Institution", "Auth-Matricule"],
        "logout_uri": "https://www.filigran.io",
        "auto_create_group": true,
        "groups_management": {
          "groups_header": "auth_groups",
          "groups_splitter": ",",
          "groups_mapping": ["admin:admin", "root:root"]
        },
        "organizations_management": {
          "organizations_header": "auth_institution",
          "organizations_splitter": ",",
          "organizations_mapping": ["filigran:filigran"]
        }
      }
    }
```

Result in log file:

`{"auth":{"email":"juju2@gmail.com","group_ids":["b483195e-c598-46b4-a5cc-4e87bf2c18bb","e77f1e49-295d-405a-b2c1-60b04f1e8569"],"ip":"::1","organization_ids":[],"referer":"http://localhost:3000/dashboard/settings/activity/audit?sortBy=timestamp&orderAsc=false&types=Activity","socket":"query","user_id":"d193e769-2515-47e1-be49-6cd57452801d","user_metadata":{"Auth-Institution":"filigran","Auth-Matricule":"MATRICULE-01"}},"category":"AUDIT","level":"info","message":"login from provider `header`","resource":{"data":{"provider":"header"},"event_access":"administration","event_scope":"login","type":"authentication","version":"1"},"timestamp":"2024-01-19T12:53:37.367Z","version":"5.12.20"}
`

Result in UI:

![image](https://github.com/OpenCTI-Platform/opencti/assets/285555/765bb935-a07e-419b-b017-f9acf7469bf3)

**Comment by richard-julien** [comment]
Implementation info added in main description
