### ISSUE TITLE
Impossible to see a file uploaded if we are not part of the platform organization

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5435]
## Description

When I upload a file in the platform (from the global import panel or from a "Data" tab of an entity), the file isn't appear if I am not part of the platform organization.

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up user A admin and part of Org A
2. Set up user B normal user and part of Org B
3. Set up Org A as platform organization
4. Create a Report with User B and upload a file from the "Data" tab of the Report
5. Try to see this file from User B (you can't), then from User A (you can)

The screenshot below illustrates this

## Expected Output

I should see the file with User B

## Screenshots

- On the left, my view from User A part of the platform organization and admin
- On the right, my view from User B (not admin), who create the report and upload the file

![Screenshot 2024-01-09 092509](https://github.com/OpenCTI-Platform/opencti/assets/70956706/10f3660e-63b9-451a-89b9-dd6a8d76645b)

**Comment by SamuelHassine** [comment]
@nino-filigran can you confirm this bug? If so, can you sync with @Kedae for a quick resolution?
