### ISSUE TITLE
Automation: the "+" dispaears if you delete 2 times an item

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5437]
## Description

When you add a first component (Listen knowledge event), then add another components after it, then delete it, add it again, delete it again, the + disapears: the user cannot add steps in its automation anymore. 

To add more steps, the users needs to delete the first component and re-add it again
## Environment

Testing + Local (not exsiting in Demo)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a playbook
2. Add the frist component
3. Click on the + to add the next component (whatever it is)
4. Delete the newly added component
5. Add again a component using the +
6. Delete again this component
7. the + has disapeared

## Expected Output

The + CTA remains

## Actual Output

The + CTA disapears.

**Comment by labo-flg** [comment]
I noticed a display problem while working on this issue: the output ports are on top of each others.
I see in the code it's a static style computation. I'll found a way to distribute evenly the ports at the bottom.

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/f6024769-8564-4aed-ae32-28bb20fcac90)

**Comment by labo-flg** [comment]
Better now
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/e415968a-6d2d-4885-8e39-e6cd25eb0e4b)
