### ISSUE TITLE
No distribution statistics in incidents

### ISSUE THREAD

**Issue by AlexSanchezN** [LuatixHQ/opencti#5441]
It looks like this issue is back: https://github.com/OpenCTI-Platform/opencti/issues/3213

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/1f14f6ca-f639-4649-bc20-0987a22a9c90)

## Environment

Baremetal Ubuntu 

## Reproducible Steps

Go to an Incident with relations to Observables and SDOs.

## Expected Output

Some nice round graphics showing the distributions 

## Actual Output

A lot of empty space

## Additional information

Not critical for us. Happy to wait to next version.

**Comment by SamuelHassine** [comment]
This bug was a duplicate and has been resolved in 5.12.17.
