### ISSUE TITLE
Knowledge display - IntrusionSet View Broken

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#5445]
## Description

When visiting a knowledge page, the intrusion set view by relations it breaks

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.12.15
3. OpenCTI client: Frontend
4. Other environment details: Clustered k8s deployment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Visit a knowledge entity
2. Click on Intrusion Sets
3. Flip to relations view

```
/dashboard/locations/countries/<ID>/knowledge/intrusion_sets
```

## Expected Output

List of the data

## Actual Output

>An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information
Console error
```
Error
    at Object.render (front-HW53SX4V.js:91:34855)
    at a.render (front-HW53SX4V.js:49:39368)
    at d2t (front-HW53SX4V.js:8:6275)
    at uja (front-HW53SX4V.js:8:6067)
    at hWa (front-HW53SX4V.js:8:45661)
    at fWa (front-HW53SX4V.js:8:40415)
    at _Ud (front-HW53SX4V.js:8:40338)
    at Jun (front-HW53SX4V.js:8:40185)
    at v2t (front-HW53SX4V.js:8:36454)
    at cWa (front-HW53SX4V.js:8:35374)
l2t @ front-HW53SX4V.js:8
XVa.o.componentDidCatch.a.callback @ front-HW53SX4V.js:8
Jqa @ front-HW53SX4V.js:6
yja @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
uWa @ front-HW53SX4V.js:8
bUd @ front-HW53SX4V.js:8
SUd @ front-HW53SX4V.js:8
w0e @ front-HW53SX4V.js:8
cWa @ front-HW53SX4V.js:8
i0t @ front-HW53SX4V.js:1
Jpt @ front-HW53SX4V.js:1
```

**Comment by Jipegien** [comment]
@Kedae Another critical to investigate ASAP.

**Comment by Archidoit** [comment]
This issue has already been resolved (https://github.com/OpenCTI-Platform/opencti/issues/5331) and the fix will be available in the next minor version.
