### ISSUE TITLE
Tables in description fields can move outside the description space and overlap other fields.

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5447]
## Description

Tables in description fields can move outside the description space and overlap other fields. See screenshot

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Copy-Paste this inside a description field:

| Aligné à gauche  | Centré          | Aligné à droite | Aligné à gauche  | Centré          | Aligné à droite | Aligné à gauche  | Centré          | 
| -------------- |---------------| -----| --------------- |---------------| ----| -------------- |--------------|
| Aligné à gauche  |   ce texte        |  Aligné à droiteAligné à droiteAligné à droiteAligné à droiteAligné à droiteAligné à droiteAligné à droiteAligné à droiteAligné à droite | Aligné à gauche  |   ce textece textece textece texte        |  Aligné à droite | Aligné à gauche  | est             |

## Screenshots

![Screenshot 2024-01-10 123121](https://github.com/OpenCTI-Platform/opencti/assets/70956706/e222588a-0ebc-463e-8e37-89a65096a1b6)

**Comment by CelineSebe** [comment]
On which entity was this result obtained? This issue is not reproducible everywhere, I can see! 
Update: this issue exists at the level of "incidents", "reports", "grouping", "threat actor(group)", "threat actor(individual)", "intrusion sets", "campaigns", ""malware", "channels", "Techniques", "Entities"

**Comment by Lhorus6** [comment]
Note: The table I share above is markdown, but interpreted by Github (sorry about that). You need to fill in a large enough markdown table to get the bug

**Comment by CelineSebe** [comment]
While editing the issue, I was able to retrieve the markdown. No problem with that. Thanks :)

**Comment by CelineSebe** [comment]
I see two possible solutions:
- Quickly adding a slider for horizontal scrolling.
- Providing more space for the description by moving it, similar to what's done in the Case container.
![Table no bug](https://github.com/OpenCTI-Platform/opencti/assets/87119259/610cc4dc-a155-4d99-abbd-75cb2ebbbe12)

@Jipegien  and I have considered both options.

**Comment by Jipegien** [comment]
Option1 as a quick fix. Non critical.

Later, we might implement the option2 in an overall modification of the overview to give a more comprehensive layout.
