### ISSUE TITLE
[Playbooks] Sharing with an organization doesn't seem to work with observables

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5451]
## Description

Sharing with an organization doesn't seem to work when applied on Observables

## Environment

1. Environment details: Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a playbook with the following tasks:
   - Listen knowledge events (Creation + Modification events): Filters: Entity type = Observable AND label=new-stealer)
   - Manage sharing with organizations (define an organization to share with + Operation to apply = Add)
   - Send for ingestion
3. Create an observable with the label "new-stealer"

## Expected Output

The observable should be shared with the indicated organization

## Actual Output

The observable  is not shared with the indicated organization

## Additional information

It works with other entity types: indicators, incidents
To ilustrate the issue, a playbook has been created in the testing environment. It's called "Playbook-sharing-obs"

**Comment by Jipegien** [comment]
@Kedae can someone check this issue ASAP ? it is an important use case of both automation and orga sharing EE features.
