### ISSUE TITLE
 Configure SMTP to receive threat digests/reports via email.

### ISSUE THREAD

**Issue by TeamProtego** [LuatixHQ/opencti#5453]
Hi Team,

We tried to configure SMTP to receive threat digests/reports via email to utilise the IOCs as proactive measure by referring the available documents over the internet but we were not able to achieve the desired output.

Could you please help us by providing complete steps to configure SMTP to receive threat digests/reports via email 

Please find the below details.

1. OS (where OpenCTI server runs): amazon linux 2
2. OpenCTI version: OpenCTI 5.11.11 , Community Edition (CC), Standalone, 1 node
3. OpenCTI client: frontend

**Comment by nino-filigran** [comment]
@TeamProtego Can you also please reach out on Slack to get support from the community?
Additionally, this is an example of our configuration, if this can help: https://docs.opencti.io/latest/deployment/configuration/?h=smtp#smtp-service
