### ISSUE TITLE
Missing button for Timeline view in Groupings/Knowledge

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#5458]
## Description

When in a Grouping/Knowledge/Graph view, the Timeline view button allowing to display the data as a timeline is not present
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/f386ea25-803e-46ac-9eda-22816edc9cae)

The button appears only if another view is selected
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/f372db85-da77-4885-ba9a-28e4f8d383fc)

## Environment

1. OS (where OpenCTI server runs): Windows 11
2. OpenCTI version: 5.12.15
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Groupings containing entities
2. go to Knowledge/Graph view of the Grouping
3. switch view to see the button appears

## Expected Output

the button should be always present

## Actual Output

the button is not present in Graph view

**Comment by Archidoit** [comment]
Timeline is not implemented yet for Groupings: the button should not be present anywhere (except if we implement this functionnality @Jipegien )
