### ISSUE TITLE
Copy-paste does not work on media content observable

### ISSUE THREAD

**Issue by gkallenborn** [LuatixHQ/opencti#5462]
## Environment

1. OS (where OpenCTI server runs): SMP Debian 4.19.289-2 (2023-08-08)
2. OpenCTI version: OpenCTI 5.12.15
3. OpenCTI client: Google Chrome 120.0.6099.201 and Firefox 115.6.0 ESR 64bits
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. open a media content in the observables section
2. click on one of the copy-paste buttons visible on the screen
3. try to copy-paste in windows notepad or another text editor

## Expected Output

the copy-pasted content should appear in the editor

## Actual Output

the copy-pasted content does not appear

![copy-paste-not-working](https://github.com/OpenCTI-Platform/opencti/assets/28608796/899dbe69-6f7d-4daf-9aff-56aaa8a9820d)

**Comment by nino-filigran** [comment]
@gkallenborn I can't manage to reproduce your bug, all the copy paste work fine for me. Does it happen with any other observable type? 
Can your clipboard be full?

**Comment by gkallenborn** [comment]
Wow, how strange. The copy paste button doesn't work for me, regardless the entity type, nor the browser, not the operating system (I tried it on Windows and Linux). Even if the clipboard is empty. I really don't understand. I will ask some collegues to test it...

**Comment by nino-filigran** [comment]
Yes indeed, it's quite odd. Please let me know if your colleagues manage to reproduce. I'll also see on my side if someone manages to reproduce it.

**Comment by gkallenborn** [comment]
I asked a collegue of mine, and she had the same problem: she was unable to use the copy-paste function. Hmm...

**Comment by aHenryJard** [comment]
Hi @gkallenborn, do you have a "insecure connection" warning in your browser when using OpenCTI ? Because in that case copy/paste is disabled by the browser. When copy is working, the is a small green message for some seconds "Copied to clipboard", do you see this green message ?

And also if you have access to the browser console, in order to confirm do you see an error message such as "Uncaught TypeError: navigator.clipboard is undefined" ?

**Comment by Jipegien** [comment]
@gkallenborn Have you upgraded your platform to the last release and do you still encounter this problem?

**Comment by gkallenborn** [comment]
Hi everyone. Sorry for the delay, but the problem is indeed the browser who disabled the copy-paste function because our dev instance is on http. I will try to modify  this parameter. Thanks a lot!
