### ISSUE TITLE
Sorting the "event type" column in the Settings > Activity window crash 

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5464]
## Description

When we try to sort the data in the Settings > Activity window, on the "Event type" column, the window crashes (i.e. an error appears).

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings > Activity
2. Click on "entity type" (the name of the column) to order the list based on this column.
-> Crash

## Screenshots

![Screenshot 2024-01-11 135943](https://github.com/OpenCTI-Platform/opencti/assets/70956706/8c1ffab5-f162-4753-97cf-070e9f95edc8)

![Screenshot 2024-01-11 140143](https://github.com/OpenCTI-Platform/opencti/assets/70956706/58a97d65-5115-44b1-bbf3-941cbfb6ee65)

**Comment by Archidoit** [comment]
same for event_scope and user
