### ISSUE TITLE
"Relationship type: contains" filters are incorrectly displayed in dashboards

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5468]
## Description

We you select the filter "Relationship type: contains" in the configuration of a widget, you obtain "Relationship type: object"

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new widget
2. Choose the view you want as long as the "knowledge" perspective is available.
3. Add the filter "Relationship type: contains" (grey filter)
-> You obtain "Relationship type: object"

## Screenshots

![Screenshot 2024-01-11 163102](https://github.com/OpenCTI-Platform/opencti/assets/70956706/17a5d7b1-50ed-4e87-b7e9-708ebaee3df6)

**Comment by Archidoit** [comment]
relationship types are not translated : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/d7c8ca33-a850-4ba2-a1ec-e57f3d32bbdb)
