### ISSUE TITLE
Integration with Wazuh SIEM

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#5478]
## Use case

[Wazuh is an open source unified XDR and SIEM solution](https://wazuh.com/). We use it as an MSSP, providing security monitoring for clients. We would like to integrate our self-hosted OpenCTI instance with Wazuh to be able to enrich Wazuh alerts, and also query the OpenCTI API to match on indicators, thus creating threat intelligence alerts on Wazuh. Currently, this isn't part of the OpenCTI ecosystem.

## Current Workaround

There are a couple of community integrations (SOC Fortress, and some other forks), however they are not maintained and are unlikely to work with up-to-date OpenCTI instances.

## Proposed Solution

OpenCTI/Wazuh integration.

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/connectors/issues/992

**Comment by misje** [comment]
@dominictory I'm currently working on a Wazuh connector that looks up observables in Wazuh's logs, creating sightings and incidents. I'll release it as an experiment in not too long, and if it is useful for others, it's not unlikely that it can reach a stable version for production.

For the other way around, looking up alerts against indicators in OpenCTI, feel free to test [wazuh-opencti](https://github.com/misje/wazuh-opencti), which is actively maintained. I've got a number of ideas after working on the Wazuh connector that could be implemented in this integration in the future.

**Comment by dominictory** [comment]
> @dominictory I'm currently working on a Wazuh connector that looks up observables in Wazuh's logs, creating sightings and incidents. I'll release it as an experiment in not too long, and if it is useful for others, it's not unlikely that it can reach a stable version for production.
> 
> For the other way around, looking up alerts against indicators in OpenCTI, feel free test [wazuh-opencti](https://github.com/misje/wazuh-opencti), which is actively maintained. I've got a number of ideas after working on the Wazuh connector that could be implemented in this integration in the future.

Been watching your work on wazuh-opencti, going to test it soon :)
