### ISSUE TITLE
Importing Windows Registry Keys with ImportDocument does not extract values

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#5498]
## Description

Importing Windows Registry Keys with ImportDocument connector extracts the registry keys observables, but will not put values inside them.

## Environment

OCTI 5.12.15

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. import a txt file with some reg keys

```txt
HKEY_LOCAL_MACHINE\SOFTWARE\Adobe
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Office
```

2. start an import with `ImportDocument` connector
3. Open the workbench : no default values for the 2 observables

## Expected Output

The values in the file

## Actual Output
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/0f3ea227-c5ff-41e8-89e1-f74e5c3db23c)

**Comment by labo-flg** [comment]
Removing _needs triage_ as per @Jipegien's demand

**Comment by labo-flg** [comment]
duplicate #5387  I guess

**Comment by Jipegien** [comment]
duplicate
