### ISSUE TITLE
Padding not correct in playbook drawers

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5514]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/cdd41af5-2895-4903-85b6-60c8e6926ac1)

**Comment by Jipegien** [comment]
to add in the next UI improvement placeholder @nino-filigran

**Comment by SamuelHassine** [comment]
Incorrect:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0ce79b91-dfc6-4853-96a2-c58b5a160f00)

Correct:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/d61dafb9-a72e-40fc-86c3-41c8ecd799d9)

**Comment by CelineSebe** [comment]
It seems to me that it's correct. Am I wrong?
![Create a report](https://github.com/OpenCTI-Platform/opencti/assets/87119259/baa6dae1-acce-46db-b482-77d1d155d59e)
![create a stream](https://github.com/OpenCTI-Platform/opencti/assets/87119259/08c740c8-46a6-4976-9d40-6327ca89a30f)
![Update addCompoent](https://github.com/OpenCTI-Platform/opencti/assets/87119259/e3a94f1f-e9cf-4a80-a2e3-f56c18068fdc)
![update addplaybookcomponent](https://github.com/OpenCTI-Platform/opencti/assets/87119259/e6470653-8d58-4f43-8c8a-32d883a21f0b)

**Comment by SamuelHassine** [comment]
It is not, and the correct one is the report creation:

https://github.com/OpenCTI-Platform/opencti/assets/1334279/9f270c29-0cae-447b-afe7-0e83a6194ed6

**Comment by SamuelHassine** [comment]
I'm talking about the top padding.
