### ISSUE TITLE
"Related entities" section in Knowledge tab crash

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5518]
## Description

When I go to the "Related entities" section of a Knowledge tab, I get an error. I tried for :

- Intrusion set, Malware, Threat actor, Tool, Organization -> same behavior (error occurs)
- Attack patterns -> No error here
- Other not tested

## Environment

OCTI 5.12.17 (filigran and demo)

Firefox 121.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an Intrusion set
2. Go on the knowledge tab
3. Go on "Related entities"
-> Error 

## Screenshots

![Screenshot 2024-01-16 130439](https://github.com/OpenCTI-Platform/opencti/assets/70956706/323de881-dd3b-49ee-909c-a62eef32323f)

**Comment by Archidoit** [comment]
Will be resolved in : https://github.com/OpenCTI-Platform/opencti/pull/5516
