### ISSUE TITLE
Be able to generate a "support package" by clicking on a button

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5548]
## Use case

Generate a zip file with

- Environment variables with redacted secrets => environment.txt
- Statistics => stats.txt
- Error logs files => in a folder "logs"

**Comment by nino-filigran** [comment]
stats - like in connector. Generate suppot package CTA in the platform.

**Comment by SamuelHassine** [comment]
It should be available only to people with "SETACCESS" capability (aka admins), in the settings, somewhere....
