### ISSUE TITLE
Split capabilities to create labels / marking etc & update other capabilities to provide more clarity in RBAC

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5550]
## Use case

List of required capabilities:

1. Manage parameters
2. Create / update custom workflows
3. Create / update labels
4. Create / update marking definitions

## Solution proposed
- **decorelate Access admin right from the other admin capabilities**
- **create one capa per page**
- **rework some cases to usage of our matrix clearer**
   - split the capa to manage dashboards & investigations
   - add a new capa "bypass mandatory fields" that would allow users to bypass custom mandaotry fields (the ones defined in the customization panel) - potentially in this ticket, if not a new ticket will be created. 
   - split data sharing & ingestion into 2 specific capa

**Comment by Jipegien** [comment]
We need to brainstorm this more broadly and cover all the admin panel in order to differentiate "functional admin" and "technical admin"

**Comment by ParamConstructor** [comment]
Will impact possibly open PR - (https://github.com/OpenCTI-Platform/opencti/pull/5252)
