### ISSUE TITLE
[Investigation] Impossible to create a container from an investigation

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5558]
## Description

When you want to create a container from an investigation, on the fly at the "add to a container" stage, you can't do it because it's impossible to put the name.

## Environment

OCTI 5.15.19 (filigran and demo)
Firefox 121.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an investigation
2. Click on "Add to a container"
3. Create a new container (instead of selecting an existing one), by clicking on the "+"
4. Try to fill in the name -> Impossible (so impossible to create the container)

## Screenshots 

![Screenshot 2024-01-17 181408](https://github.com/OpenCTI-Platform/opencti/assets/70956706/69b40f9e-cf85-495a-82de-dae2a67ff5d5)

**Comment by Lhorus6** [comment]
This issue could be linked to the issue : 
- https://github.com/OpenCTI-Platform/opencti/issues/5563
- https://github.com/OpenCTI-Platform/opencti/issues/5559

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5563
