### ISSUE TITLE
[Investigation] In some cases graph nodes from expand are blacked out

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5562]
## Description

In some cases, in an investigation when I expand an entity, the graph nodes and relationships are blacked out and almost invisible.

## Environment

OCTI 5.12.19

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. On the demo instance (the private one), start an investigation from the report "Issue/5562 DO NOT DELETE" (by going to "knowledge" and click on the blue compass button in the top right-hand corner.)
2. Expand the indicator with only the incident
3. Expand the Incident with Org + Country + Sector
-> These three entities added are blacked out

Ping me if it's not clear and you need a demo

## Screenshots

![Screenshot 2024-01-17 184315](https://github.com/OpenCTI-Platform/opencti/assets/70956706/d2c37da8-53cf-482e-8930-47150e2aca32)

**Comment by Jipegien** [comment]
Blacked out elements are elements that are filtered out. Can you check your filters plz @Lhorus6

**Comment by Lhorus6** [comment]
That's what I told myself and checked -> no filter. 
Have you tried following the repro case? I can show you in 1 minute if you want @Jipegien

**Comment by Jipegien** [comment]
We need a fix before January, 30th.

**Comment by nino-filigran** [comment]
Side note: reproducibility is hard on this bug, when we tried we did not succeed to reproduce elsewhere, with other entities. However, the fact is that it happens with the above description. And on the top of this, clicking on expand on these "dark" nodes makes nothing, as if they were disabled.

**Comment by Kedae** [comment]
To have a proper fix on that we need steps to reproduce locally

**Comment by nino-filigran** [comment]
Closed since the issue was that relations were in the future.
