### ISSUE TITLE
[Dashboard] "Number of results" not taken into account

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5578]
## Description

When I create a "List" > "Activity & History" widget, the "Number of results" parameter in the 4th configuration step is not taken into account. (not critical at all)

## Environment

OCTI 5.12.19

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a widget List > Activity & History
2. In "3. Filters" : No filter
3. In "4. Parameters" : Number of results = 10
-> You get more than 10 entities in the list

See dashboard "issue/5578" on the filigran platform

## Screenshots 

On the left, the buggy config described above, on the right the same config in "Entity" perspective (which is not buggy):

![Screenshot 2024-01-17 230301](https://github.com/OpenCTI-Platform/opencti/assets/70956706/a8e4559e-d5e5-4293-a7a6-d07ce71b4894)

**Comment by nino-filigran** [comment]
@Lhorus6 I cannot reproduce, pelase see my screenshots:

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/f214a887-2f1a-4ea2-96e3-d7d2d202a3fd)
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/212e2a8b-b081-47c9-9791-78b75c08fa7e)
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/2ba31bbc-7f44-4ff5-87d1-0ce4ef47d32a)
