### ISSUE TITLE
CVSS3 Score of a vulnerability can be empty at creation but display error if empty at edition

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5586]
Go to a vulnerability overview.
Click on the 'edit' button.
Go to the 'details' tab.
Add or change the 'CVSS3 - Severity' field.
An error occurs for the field 'CVSS3 - Score' but you can update the vulnerability and you can create a vulnerability with this field empty.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f817c9ad-7947-4c44-b016-fc1897f2e9ce)

**Comment by nino-filigran** [comment]
To add more details, I reproduce this bug, but the error message appears and stays something like 1 second.

**Comment by Archidoit** [comment]
@nino-filigran @Jipegien do we want to make the field CVSS3-Score mandatory or not?

**Comment by nino-filigran** [comment]
@Archidoit not it's not!

**Comment by Archidoit** [comment]
@nino-filigran By default, at a vulnerability creation, the score value is set to 1. Do we want to keep this?
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3a381447-aedd-4ebf-9669-5aa1eb6f4fb5)

**Comment by nino-filigran** [comment]
what @Jipegien explained to me is that bascially it's better if a vulnerability has a score but it should not be blocking. I assume that is the reason why we put a default scor?
e. If we say that the score is not mandatory, my opinion on this topic would be that we should not pre-fill it. @Jipegien ok with this?
