### ISSUE TITLE
Toggle buttons are broken in all headers

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5599]
## Description

Toggle buttons are broken in all headers

Example in ContainerHeader):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0a230c08-1155-4fab-9b6d-5e8d0f1d8f61)

All left border in buttons are missing, in the first one but also in all middle buttons.

**Comment by SouadHadjiat** [comment]
@SamuelHassine I'm adding also this issue that is already in prod (Seen on Filigran instance), when you have a message banner : 

![image](https://github.com/OpenCTI-Platform/opencti/assets/668192/5c46e98b-e490-431b-ad13-2098ae7785bc)
