### ISSUE TITLE
Sorting members of a group is not working

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5607]
Go to Settings>Security>Groups
Go to a group
In the 'members' tab, order members by their email or their name.
The list is not sorted.

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/7e033301-cf07-4425-ac44-56bd8b070374)

**Comment by SouadHadjiat** [comment]
It looks like there is also another bug with members display : we only get the first 25 members (without sorting or pagination). If you query members of a group : 

```
members(first: 25) {
    pageInfo {
      globalCount
    }
  }
```
it will return a globalCount of 25 even if there are more (and in the page we request 25 members).

**Comment by SouadHadjiat** [comment]
About the sorting, my guess is that it's a regression of #4220

```
const targets = await elFindByIds(context, user, targetIds, opts); // ===> **targets are sorted here**
// endregion
// region Enrich all targets with internal types [manual and/or inferred]
const targetsWithTypes = {};
relations.forEach((relation) => {
  const relationTarget = targets.find((i) => i.id === relation[`${opposite}Id`]);
  if (relationTarget) { // Could be empty due to restriction on the entity but not on the relationship
    const isInferred = isInferredIndex(relation._index);
    const targetType = isInferred ? 'inferred' : 'manual';
    if (targetsWithTypes[relationTarget.id] && !targetsWithTypes[relationTarget.id].i_types.includes(targetType)) {
      targetsWithTypes[relationTarget.id].i_types.push(targetType);
    } else {
      targetsWithTypes[relationTarget.id] = { ...relationTarget, i_types: [targetType] };
    }
  }
});
// endregion
// Group and rebuild the result
const processedTargets = Object.values(targetsWithTypes); //  ===> **targets are no longer well sorted here**
```

Not sure about how to fix this bug (sorting and pagination)

**Comment by richard-julien** [comment]
The batchListThrough is currently not so powerful to easily order/sort and paginate.
I get the point to see how we can globally improve this part.
Thanks for the pin point.
