### ISSUE TITLE
Authentication header provider does not entirely support HTTP/1.1 style headers with capital letters

### ISSUE THREAD

**Issue by gkallenborn** [LuatixHQ/opencti#5646]
## Description

Version 5.12.21 should have solved a bug in the authentication header provider, which did not support HTTP/1.1 style headers with capital letters. But it appears that the bug is only partially solved. 

## Environment

1. OS (where OpenCTI server runs): Debian 4.19.0-25-amd64 x86_64 GNU/Linux
2. OpenCTI version: 5.12.21
3. OpenCTI client: Firefox 115.6esr , Vivaldi 6.5.3206.55

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Write the authentication header configuration as showed in the screenshot, in the docker-compose.yml file
2. Send an HTTP Get request with the authentification headers 
3. With the admin account, look at the user profile

## Expected Output

All  the header values should have been mapped in the profile

## Actual Output

Some headers values do not map, like those associated with the Groups and the Organizations. Also, the authentication seems to generate multiple sessions.

## Additional information

![config-SSO](https://github.com/OpenCTI-Platform/opencti/assets/28608796/a6a190ba-dcbc-4b19-a38d-82f62fda3d65)
![resultat-SSO_5_12_21](https://github.com/OpenCTI-Platform/opencti/assets/28608796/33271e2a-c1ff-480a-8baf-f3153d974464)

**Comment by SamuelHassine** [comment]
Hello @gkallenborn,

For the multiple sessions, this is a known problem and we will discuss this internally. For groups and organizations mapping, it has been tested and is working well. According to your screenshot, your environment variables are not correctly defined.

Please check this example: https://docs.opencti.io/latest/deployment/authentication/#openid-connect-button.

Variables should be something like:

```
- PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_SCOPE="groups"
- "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_PATH=[\"groups\", \"realm_access.groups\", \"resource_access.account.groups\"]"
- "PROVIDERS__OPENID__CONFIG__GROUPS_MANAGEMENT__GROUPS_MAPPING=[\"OpenID_Group_1:OpenCTI_Group_1\", \"OpenID_Group_2:OpenCTI_Group_2\", ...]"
```

Sourrounded by double quotes with backslahes internally.

**Comment by gkallenborn** [comment]
Hi @SamuelHassine. Thanks for your feedback. I will investigate this, but I don't think this is the problem. Because when I only use lowercase letters for the header names and no backslashes, the mapping is just working fine.

**Comment by SamuelHassine** [comment]
@gkallenborn Indeed, we have detected that the initial fix was done everywhere except on org / group mapping. Fix will be available in the upcoming minor release.
