### ISSUE TITLE
Can't launch an import of an XML file in Data Import

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5647]
## Environment

1. Environment details: Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on 'Data import and analyst workbenches' (Icon on the top right section)
2. Upload an XML file containing STIX entities

## Expected Output

Be able to start the upload of the file and create an analyst workbench

## Actual Output

The "Launch an import of this file" button is disabled

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/86c5b6dc-9309-4266-9314-8d5fbddbec6a)

**Comment by SamuelHassine** [comment]
This is not a bug. It is the scope of the connector. Looping internally with the platform team.
