### ISSUE TITLE
[Placeholder] Templating deliverables

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5655]
## Use case

This feature needs to be refine. Goal is to be able to set/define templates to export a document.

**Comment by Jipegien** [comment]
@nino-filigran [#3402](https://github.com/OpenCTI-Platform/opencti/issues/3402) must be studied in this context.

**Comment by Lhorus6** [comment]
Inputs from customer:

- Be able to select the data to be exported, apply and create export templates and export them as PDF, MD or HTML files.
- Add an advanced export feature for the CSV, TXT, STIX, TTPs to select what kind of data to export

**Comment by nino-filigran** [comment]
Closing this issue to track through initial created ticket: https://github.com/OpenCTI-Platform/opencti/issues/3402
