### ISSUE TITLE
Error when trying to create a regular digest

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5661]
## Description

Error when trying to create a regular digest.

## Environment

Environment details: Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on the "Notifications and triggers" button on the top bar
2. Go to the "Triggers and digests" section
3. Create a Regular digest

## Expected Output

Regular digestion creation form appears

## Actual Output

Error

**Comment by Archidoit** [comment]
same error at digest edition
