### ISSUE TITLE
entity_user & relationship_obect_assignee & relationship_object_participant should not be dispalyed in investigation graph as elements to expand

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5662]
## Description

In investigation graph, if you select an entity that you participate in and have an assignee, it is currently possible to expand on these elements. It is wrong since the goal of an investigation is to investigate on knowledge not on people themselves. Expanding on these elements makes also the expand not wroking properly. 

## Environment
Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a case that has a participant and a assingee
2. go in knowledge view
3. Click on start an investigation
4. Select the case
5. Click on expand 
6. 

## Expected Output

entity_user & relationship_obect_assignee & relationship_object_participant should not be dispalyed as elements to expand on
## Actual Output

entity_user & relationship_obect_assignee & relationship_object_participant are dispalyed as elements to expand on

**Comment by Archidoit** [comment]
same for 'granted by'

**Comment by Archidoit** [comment]
+ relationships bad display in expansion form: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/b0bba7dd-7c79-4501-b7d1-6fcf4d843bfe)
