### ISSUE TITLE
Rss feed not working

### ISSUE THREAD

**Issue by RegturH** [LuatixHQ/opencti#5710]
## Description

Rss feed not working and giving me an axios error

## Environment

1. linux node
2. OpenCTI version: 5.11.2
3. OpenCTI client: front-end
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a RSS Ingester
2. feed url: https://thedfirreport.com/feed/
3. user -> user in the admins group

## Expected Output

the feed being ingested

## Actual Output

error: 
{"category":"APP","error":{"context":{},"message":"Request failed with status code 503","name":"AxiosError","stack":"AxiosError: Request failed with status code 503\n    at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:572:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},"level":"error","message":"[OPENCTI-MODULE] Rss ingestion execution error for The DFIR Report","timestamp":"2024-01-26T17:28:15.502Z","version":"5.11.2"}

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/111435050/d3f0fcb4-0a55-4e63-9591-7841174ae46e)

**Comment by Lhorus6** [comment]
@RegturH We've fixed some bugs in the RSS feeds since your version. Update your platform and you should be good to go.
@Jipegien I tested it to make sure it worked on our prod instance (filigran), and it does. I'll let you close this ticket

**Comment by Jipegien** [comment]
@Lhorus6 have you got reports created? I did not manage to have one.

**Comment by Lhorus6** [comment]
@Jipegien Yes I have. You can have a look on the Filigran prod instance. You will see the « DFIR » RSS feed. And if you look for « technical creator: [F] Hackread » you will see the DFIR report (I used the [F] Hackread user for the DFIR RSS feed)

**Comment by SamuelHassine** [comment]
Tested locally, working fine.
