### ISSUE TITLE
Widget Horizontal bar is broken when using Label as attribute for breakdown

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#5734]
## Description

Widget Horizontal bar is broken when using Label as attribute for breakdown

![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/5e0ed27d-69a3-4230-8e08-ab9f9c0ab65d)
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/ea081a10-d3fa-4c82-bc59-11782e986cc0)
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/212e133d-04c7-4b03-a291-315ed59b587c)

## Environment
2. OpenCTI version: 5.12.24

## Error log example
`1970/01/01 01:00AM ERR Platform unmanaged direct error | category=APP errors=[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot query field \"edges\" on type \"Label\".","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot query field \"edges\" on type \"Label\".\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at Object.willSendResponse (/opt/opencti/build/src/graphql/loggerPlugin.js:115:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at N (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:530:5)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:273:16)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"},{"message":"Cannot query field \"edges\" on type \"Label\".","name":"GraphQLError","stack":"GraphQLError: Cannot query field \"edges\" on type \"Label\".\n    at Object.Field (/opt/opencti/build/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)\n    at Object.enter (/opt/opencti/build/node_modules/graphql/language/visitor.js:301:32)\n    at Object.enter (/opt/opencti/build/node_modules/graphql/utilities/TypeInfo.js:391:27)\n    at visit (/opt/opencti/build/node_modules/graphql/language/visitor.js:197:21)\n    at validate (/opt/opencti/build/node_modules/graphql/validation/validate.js:91:18)\n    at validate (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:477:12)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:267:32)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"}] inner_relation_creation=0 operation=Unspecified operation_query=query ThreatActors($filters:FilterGroup$search:String$first:Int$after:ID$orderBy:ThreatActorsOrdering$orderMode:OrderingMode){threatActors(filters:$filters search:$search first:$first after:$after orderBy:$orderBy orderMode:$orderMode){edges{node{id standard_id entity_type parent_types spec_version created_at updated_at createdBy{...on Identity{id standard_id entity_type parent_types spec_version identity_class name description roles contact_information x_opencti_aliases created modified objectLabel{edges{node{id value color}}}}...on Organization{x_opencti_organization_type x_opencti_reliability}...on Individual{x_opencti_firstname x_opencti_lastname}}objectMarking{edges{node{id standard_id entity_type definition_type definition created modified x_opencti_order x_opencti_color}}}objectLabel{edges{node{id value color}}}externalReferences{edges{node{id standard_id entity_type source_name description url hash external_id created modified importFiles{edges{node{id name size metaData{mimetype version}}}}}}}revoked confidence created modified name description aliases threat_actor_types first_seen last_seen roles goals sophistication resource_level primary_motivation secondary_motivations importFiles{edges{node{id name size metaData{mimetype version}}}}}}pageInfo{startCursor endCursor hasNextPage hasPreviousPage globalCount}}} size=85 timestamp=2024-01-29T16:01:22.934Z type=READ_ERROR user={"group_ids":["e0045918-b301-487e-aaf1-c735fd28adde"],"ip":"::ffff:10.0.4.4","organization_ids":["8763664e-d84b-4ed1-942d-54891bbba7a8"],"socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}} variables={"after":null,"filters":null,"first":1,"orderBy":null,"orderMode":null,"search":null} version=5.12.24`

**Comment by nino-filigran** [comment]
@Jipegien I cannot reproduce on Demo.
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/3cd7ee99-146b-41e3-920e-1154c6e0ce5b)

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/995e6334-5a3b-4c66-973e-16bfd801996d)


Output: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/a27a2539-241b-4bc0-9bb0-2d81d3a91a2e)

**Comment by SamuelHassine** [comment]
@Jipegien I think after the upgrade you've not reloaded your screen.

**Comment by SamuelHassine** [comment]
Can you just full refresh and check?

**Comment by SamuelHassine** [comment]
Reproduced / fixed

**Comment by rattat0r** [comment]
Hello @SamuelHassine. I encountered the same problem on version 6.0.4 with the rst-threat-feed connector. 
An error will appear in the logs: ```{"timestamp": "2024-03-04T09:28:43.695675Z", "level": "ERROR", "name": "pycti.api", "message": "{'name': 'Cannot query field \"edges\" on type \"Label\".', 'message': 'Cannot query field \"edges\" on type \"Label\".'}"}
  File "/opt/opencti-connector-threatfeed/main.py", line 412, in <module>
    connector = RSTThreatFeed()
                ^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-threatfeed/main.py", line 35, in __init__
    self.helper = OpenCTIConnectorHelper(config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 666, in __init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(```

**Comment by rattat0r** [comment]
Found the problem. The version of pycti is old: https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/rst-report-hub/src/requirements.txt 
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/fa1a3319-bca9-49ca-849e-cb280363aa72)
