### ISSUE TITLE
Multiple inconsistencies and errors on creation forms

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5741]
## Description

On report, at opening creation, name is directly red in error state (should only happen after field is touched or on validation):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/3bd90e16-af79-4f5d-92f8-fd9690e1ef5a)

On threat actors, at opening everything seems correct but after the field is touched, only the red line is displayed, and the error does not replace the helper text:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/666d4590-1fdd-4ffd-bdbe-00fc440c3084)

Grouping:
detect duplicate doesn't work + context field appears to be touched but it is not
![image](https://github.com/OpenCTI-Platform/opencti/assets/73853856/d44cce8e-7f32-45f2-b7a4-9f51f4f3aa95)

**Comment by marieflorescontact** [comment]
Seems to be a formik problem:
https://formik.org/docs/api/useField
touched is always false.

**Comment by richard-julien** [comment]
So linked to a formik upgrade?

**Comment by marieflorescontact** [comment]
I think we're misusing formik, i am working on it

**Comment by richard-julien** [comment]
It was working since a long time so take the time to check what changed and introduced this behavior recently.

**Comment by marieflorescontact** [comment]
To solve this issue we need to rethink the way we are using the lib Formik for our custom fields.
We plan to work on it  @lndrtrbn for 6.0, but not immediately as we prefer to prioritize features for 6.0.
This has been discussed with @Jipegien

**Comment by richard-julien** [comment]
Can you explains where this change come from? Formik validation is not something new so i'm a bit confused.

**Comment by marieflorescontact** [comment]
we haven't found the exact reason, so we'll have to spend more time on it. 
at the moment, there's a strange behavior in the `textField` component :
when using the [formik hook useField](https://formik.org/docs/api/useField) 
`const [, meta] = useField(name) ;`
the value of `meta.touched` seems inconsistent (once it's an object, once it's a boolean, it is supposed to be like [this](https://formik.org/docs/api/field))

**Comment by lndrtrbn** [comment]
I thought in a first place that this behavior was present since a while but it appears my memory is bad. I can't see those issues while testing locally opencti 5.11.14.

I looked into lib versions to compare what changed. Formik did not change since 5.11.14. I tried to reinstall the versions of MUI that were in 5.11.14 but it did not fix the issue. So for now I don't know and will investigate later.

**Comment by Kedae** [comment]
Retaking ownership on this one, this seems linked to CKEditor and default values mapping
