### ISSUE TITLE
When typing in autocomplete field quickly it will not filter correctly

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5742]
## Description

When typing in autocomplete field quickly it will not filter correctly on the last letter:

https://github.com/OpenCTI-Platform/opencti/assets/1334279/59d32fc1-418f-4661-a2b5-21543b1b077b

**Comment by marieflorescontact** [comment]
I can't reproduce 🤔

**Comment by SarahBocognano** [comment]
I was trying to reproduce as well but I didn't succeed

**Comment by SamuelHassine** [comment]
I think this was actually solved by a few upgrades etc. So marking this as solved.
