### ISSUE TITLE
Cannot access Vulnerabilities page on 5.12.24

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#5743]
## Description

Cannot access Vulnerabilities page on 5.12.24.

## Environment

5.12.24

## Log

`1970/01/01 01:00AM ERR incorrect filter keys not existing in any schema definition | category=APP errors=[{"attributes":{"genre":"BUSINESS","http_status":500,"keys":["x_opencti_base_severity"]},"message":"incorrect filter keys not existing in any schema definition","name":"UNSUPPORTED_ERROR","stack":"UNSUPPORTED_ERROR: incorrect filter keys not existing in any schema definition\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnsupportedError (/opt/opencti/build/src/config/errors.js:83:51)\n    at checkAndConvertFilters (/opt/opencti/build/src/utils/filtering/filtering-utils.ts:268:15)\n    at elQueryBodyBuilder (/opt/opencti/build/src/database/engine.js:2077:19)\n    at elPaginate (/opt/opencti/build/src/database/engine.js:2476:22)\n    at listEntities (/opt/opencti/build/src/database/middleware-loader.ts:364:10)\n    at findAll (/opt/opencti/build/src/domain/vulnerability.js:15:10)\n    at Object.resolve [as vulnerabilities] (/opt/opencti/build/src/resolvers/vulnerability.js:14:44)\n    at fieldResolver (/opt/opencti/build/src/graphql/authDirective.js:59:24)\n    at resolveFn (/opt/opencti/build/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)\n    at executeField (/opt/opencti/build/node_modules/graphql/execution/execute.js:492:20)\n    at executeFields (/opt/opencti/build/node_modules/graphql/execution/execute.js:414:22)\n    at executeOperation (/opt/opencti/build/node_modules/graphql/execution/execute.js:344:14)\n    at execute (/opt/opencti/build/node_modules/graphql/execution/execute.js:136:20)\n    at execute (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:504:20)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:410:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"}] inner_relation_creation=0 operation=VulnerabilitiesLinesPaginationQuery operation_query=query VulnerabilitiesLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:VulnerabilitiesOrdering$orderMode:OrderingMode$filters:FilterGroup){...VulnerabilitiesLines_data_2wN0PW}fragment VulnerabilitiesLines_data_2wN0PW on Query{vulnerabilities(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{id name description ...VulnerabilityLine_node __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}}fragment VulnerabilityLine_node on Vulnerability{id name x_opencti_cvss_base_severity created modified confidence objectMarking{id definition_type definition x_opencti_order x_opencti_color}objectLabel{id value color}creators{id name}} size=299 timestamp=2024-01-30T09:13:25.889Z type=READ_ERROR user={"group_ids":["e0045918-b301-487e-aaf1-c735fd28adde"],"ip":"::ffff:10.0.0.2","organization_ids":["8763664e-d84b-4ed1-942d-54891bbba7a8"],"referer":"https://10.254.202.12/dashboard/arsenal/vulnerabilities?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%224a651179-4c59-4649-8e1b-965b2ebcf500%22%2C%22key%22%3A%22x_opencti_base_severity%22%2C%22values%22%3A%5B%5D%2C%22operator%22%3A%22nil%22%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&sortBy=name&orderAsc=false","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}} variables={"count":25,"filters":{"filterGroups":[{"filterGroups":[],"filters":[{"key":"x_opencti_base_severity","mode":"or","operator":"nil","values":[]}],"mode":"and"}],"filters":[{"key":"entity_type","mode":"or","operator":"eq","values":["Vulnerability"]}],"mode":"and"},"orderBy":"name","orderMode":"desc"} version=5.12.24`

## Screenshots

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/6c28d2a6-8619-4779-83e3-8630ababcc03)

**Comment by SamuelHassine** [comment]
Hello @dominictory,

Can you change x_opencti_base_severity in the URL by name?

Kind regards,
Samuel

**Comment by dominictory** [comment]
@SamuelHassine hi, I just cleared filters and it's visible. Thanks!
