### ISSUE TITLE
Not-existing page for redirection to creators that are not user

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5760]
## Bug description
Redirection to creators that are not user redirects to a non-existing page.

## Steps to reproduce

Go to an entity with creator = automation manager
Exemple in testing: go to the overview of the country 'FR' : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/abd62970-abe2-4344-b38f-dcde02dac65d)

Click on 'automation manager':
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/b45998ec-0890-4de7-ade2-0b93ff17f778)

You are redirected to a not-existing page:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e225c001-c075-423a-83eb-50fa4afe59f9)

**Comment by richard-julien** [comment]
Yeah this kind of "internal users" should not be clickable
