### ISSUE TITLE
Allow change of x_opencti_type from Threat-Actor-Individual and Threat-Actor-Group

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#5765]
## Use case

Under OpenCTI 5.12.18, if you have a Threat Actor created as threat actor individual there is no way of changing it to group. This is necessary when initial assessments are not exact and need further updates.

## Current Workaround

Update the value via API or recreating the object and its relationships entirely.

## Proposed Solution

Either consider the usage of the `resource_level` attribute to identify threat actors as groups or individuals or let the user change the object type from the UI.

## Additional Information

None.

## If the feature request is approved, would you be willing to submit a PR?

No.

**Comment by nino-filigran** [comment]
Hey @febrezo thanks for your request. Migrating between entity types is something that we want to do as explained in this ticket with the following priorities: 
- threat actor group <-> threat actor individual 
- threat actors (group/indiv) <-> intrusion sets

You can view the ticket here: https://github.com/OpenCTI-Platform/opencti/issues/3571

To keep things clean, I'm closing your ticket for now. Feel free to re-open it if you think there's a mismatch between my comment and your request.
