### ISSUE TITLE
Change part-of relationship icons to the metaphor of a puzzle

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#5767]
## Use case

It is difficult to infer the `part-of` relationships direction considering the current metaphor. Maybe a single puzzle piece image for one direction (small_member -> big_group) and a 4 piece puzzle image where one is missing  for the reverse relationship (big_group -> small_member) may be easier to identify.

## Current Workaround

None.

## Proposed Solution

Potential update of icons to a metaphor similar to this:  https://www.flaticon.es/icono-gratis/candidato_8347457?related_id=8347457

## Additional Information

None.

## If the feature request is approved, would you be willing to submit a PR?

No.

**Comment by nino-filigran** [comment]
@febrezo not sure to understand the pain here: could you maybe attach a screenshot to understand where the confusion comes form?

**Comment by nino-filigran** [comment]
@febrezo I'm closing this ticket since I did not get any answer back from you.
