### ISSUE TITLE
Knowledge Graph Nodes within a Report

### ISSUE THREAD

**Issue by elwellK** [LuatixHQ/opencti#5789]
## Prerequisites

- [ X ] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [ X ] I went through old GitHub issues and couldn't find anything relevant
- [ X ] I googled the issue and didn't find anything relevant

## Description

One of our OpenCTI Analysts asked me if something changed on the system. When viewing the "knowledge" tab within a report, a graph is displayed. When filtering out entities, the Analyst stated the node are greyed out now where previously the nodes were separated from the graph. The screenshot below shows the current behavior of filtering out entity types and the node(s) gets greyed out. We have been on version 5.12.5 for many months.

## Environment

1. OS Ubuntu 22.04
2. OpenCTI version: 5.12.5
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to a report
2. Click on the Knowledge tab
3. At the bottom of the page, click on filter entity type
4. See how the nodes you filtered out are greyed out?

## Additional information

![image](https://github.com/OpenCTI-Platform/opencti/assets/101361690/625863dc-0e85-4baa-ad38-a8fac4853e2f)

**Comment by nino-filigran** [comment]
@elwellK this is a normal behavior, to grey out the filters. To my knowledge, we have not changed this behavior since at least the 2 past releases (5.11.X and 5.12.X). Is there an issue with this?

**Comment by elwellK** [comment]
Thank you
