### ISSUE TITLE
Export issue with large volume volume of entities

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#5798]
## Description

When creating a report containing many entities (+300) with relationships between them, and performing a full json export of the report, not all entities are exported.

## Environment

OpenCTI version: 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report with many entities in platform A and many relationships,
2. Make a full json export (normally at this stage all entities may not be exported)

## Expected Output

A complete export with no missing entities.

## Actual Output

Not all entities are exported.

## Additional information

Is this a bug or a deliberate limitation?

Note: When ingested into another instance (both instances are of the same version) after workbensh validation, many 'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found' errors appear.

**Comment by richard-julien** [comment]
Looks like more an export problem than an import one.

**Comment by NiQuintin** [comment]
You're right, i've modified the description.

**Comment by richard-julien** [comment]
Im not able to reproduce for now.  Can you pinpoint a specific report for the export and maybe thats missing exactly in it?
Thanks

**Comment by NiQuintin** [comment]
Here is the report we used for the test: https://demo.octi.filigran.io/dashboard/analyses/reports/91d761bd-0f93-4c6d-81a3-681d406b4893

**Comment by Jipegien** [comment]
@NiQuintin Can you test on testing to see if you reproduce it? It might be solved already.

**Comment by NiQuintin** [comment]
It works on testing @Jipegien
