### ISSUE TITLE
Malware Analysis source of a relationship display as 'Unknown'

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#5816]
Go to Data > Relationships.
The source of the relationship is displayed as 'Unknown' if it is a malware analysis : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/4a5ab8d1-900e-4c51-822e-2e3218edca00)

**Comment by nino-filigran** [comment]
Potential similar bug: https://github.com/OpenCTI-Platform/opencti/issues/5817

**Comment by Archidoit** [comment]
@nino-filigran , I don't think the 2 bugs are linked.

**Comment by nino-filigran** [comment]
Ok, since at least on the UI, the problem is pretty similar, I was wondering if they were linked. Thanks @Archidoit for your support :)

**Comment by Archidoit** [comment]
Same problem in the Knowledge tab of an observable overview : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/a152050d-00a8-45ae-9f9a-654fab57037f)
