### ISSUE TITLE
Linking two manually created entities in a workbench displays 'Unknown' in relationship

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#5817]
## Description
In a workbench, by creating a malware entity (exp Hive) and an attack pattern entity (exp [T1011] Exfiltration Over Other Network Medium) then linking the two on the model: Hive -> uses -> Exfiltration Over Other Network Medium, the destination entity (added in add context) is displayed as 'Unknown' in the relationships tab even though both entities are known in the platform.

Note: if you create only the Hive malware and link it to 'Exfiltration Over Other Network Medium' from add context, autocomplete will propose the technique and everything will appear as normal in the relationships tab.

## Environment

OpenCTI version: 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a workbench,
2. Add two entities manually,
3. Linking the first to the second

## Expected Output

In the relationships tab, both entities must appear as known to the platform.

## Actual Output

The destination entity is displayed as 'Unknown' even if it is known in the platform.

## Additional information

If you enter just one entity and use autocomplete from the add context area, the bug doesn't appear.

## Screenshots (optional)
![Bug workbench](https://github.com/OpenCTI-Platform/opencti/assets/155080335/70b57200-1b1d-4af2-ad40-05a78c444526)

**Comment by Jipegien** [comment]
is it the case for every type of entity? @NiQuintin or just attack pattern ?

**Comment by NiQuintin** [comment]
I've try it on attack pattern and malware in both side it reproduces the issue. It seems it's the case for all entity types but I can extend the test to be sure.

**Comment by labo-flg** [comment]
Quick Analysis: when adding the relationship 'uses' through the malware context, the final bundle saved (with the relationship) is like :
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/773bc556-9cd2-4b8f-8787-a5eae3c2b6ec)

As you can see the `target_ref` stix id is entirely different from the attack pattern id in the bundle.

**Comment by labo-flg** [comment]
the ids of the 2 entities in bundle are different from their version already on platform

the ids used in the relationship are mixed, one is the new id one is the id already in platform.


Matching is impossible, this relationship is deemed 'unknown' to one side..

**Comment by Jipegien** [comment]
can we fix this easily @labo-flg ?

**Comment by labo-flg** [comment]
I do not see an easy fix right now.

To me, this comes from how the workbench is designed. 

You add an entity => it gets a freshly generated stix id. The part that tells you it's already in platform won't give you the stix-id of this version on the platform, and I do not see how to change that easily. 

... And would it be a good solution ? if an item is added to workbench should its stix-id be same as the version that might already be in platform ? - same in platform means same name, alias, mitr-id).

On the other way, when you search for T1011 in the context "uses" form, it does not search for things in the workbench, but on the whole platform. So there is no reason to get the one created in the workbench.

In the end, in this use case, the ids are doomed to be irreconcilable and the bundle is probably

**Comment by labo-flg** [comment]
Note that if you validate this workbench with the 'unknown' from in relationship, a new T1011 attack pattern is created and does not upsert the existing one. And the malware gets a relation ship to that one.

**Comment by Jipegien** [comment]
ok. We won't fix it because Draftspaces are on the way to replace this feature. But it is definitly not good enough if it break the deduplication mechanism.
