### ISSUE TITLE
Sharing objects with organizations no longer works properly (linked entities are no longer shared)

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5832]
## Description

When I share an incident with an organization, the relations linked to this incident are also shared, but not the objects at the end (see screenshot).

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an incident
2. Link it to an Observable IPv4
3. From the incident, share it with an organization
4. Check the relation Incident -> IPv4 and the IPv4
-> relation shared, but not the IPv4

## Expected Output

The IPv4 should be shared too

#### Incident after sharing

![Screenshot 2024-02-06 111213](https://github.com/OpenCTI-Platform/opencti/assets/70956706/a284e8fa-8347-44b6-8741-28849e19e9bb)

#### Relation after sharing

![Screenshot 2024-02-06 111234](https://github.com/OpenCTI-Platform/opencti/assets/70956706/51c08fd5-3cc9-46cf-9367-f7702bf65bfe)

#### IPv4 after sharing

![Screenshot 2024-02-06 111237](https://github.com/OpenCTI-Platform/opencti/assets/70956706/c695032e-3b59-4174-8066-414b1dc368a9)

**Comment by Jipegien** [comment]
This is not a bug. In the capture, only the Incident is shared with the Organization. This is the expected behaviour.
