### ISSUE TITLE
Default marking are not cleaned when marking is deleted, leading to full crashed platform

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5835]
## Description

1. Create a group
2. Add a some markings
3. Add a DEFAULT marking
4. Delete the marking (in marking definition list)

=> In Elastic, the rel_accesses-to is cleaned, but not the default_marking field, because it is not a rel_ and no logic has been implemented to do so.

Result as a user part of this group, platform is in full error state. Group is not accessible and cannot be updated. Need to clean default marking in Elastic

**Comment by richard-julien** [comment]
Dont forget the associated backend test :)
