### ISSUE TITLE
Markings Filtering

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#5837]
## Description

When creating a new marking, example TS:RED and attaching that marking to a group the user can still see all markings.

## Environment

1. OS: CENTOS7.9
2. OpenCTI version: 5.12.29
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new marking, example "TS:RED"
2. Create group group_TSRED with only marking TS:RED
3. Create user user_TSRED and assign group_TSRED to user
4. Login as user
5. The user_TSRED can still view all markings

## Expected Output

User should only be able to view data with the specified markings per group the user is assigned

## Actual Output

User can still view all data and markings

## Additional information

None

## Screenshots (optional)

None

**Comment by Jipegien** [comment]
Not able to reproduce.
Verify your user is not part of other groups having others markings.
Verify your users in not part of a group with a role including "bypass all capabilities"

**Comment by explorecti** [comment]
@Jipegien I have verified that the user only has the following:
**Roles**
Capabilities, Access knowledge, Access exploration, and Create / Update exploration is selected.

User is not in any group with "bypass all capabilities".

**Comment by Jipegien** [comment]
Is your user in other groups than the group "group_TSRED" ? If so, check of these groupes have marking definitions allowed.

**Comment by explorecti** [comment]
@Jipegien The user is not listed in any other groups.

**Comment by richard-julien** [comment]
Hi @explorecti , thanks for the report.
We have an issue when the group has currently no roles associated to it.
To quick fix the situation waiting for the resolution on the product, please assign a role and the correct capabilities you want for you user, it will resolve for now your markings visibility issue

**Comment by explorecti** [comment]
This issue has not been resolved with version 6.0.7, please advise to the ticket closure. Thanks

**Comment by richard-julien** [comment]
If user as bypass capability, markings are also bypassed. Can you check?
