### ISSUE TITLE
[CSV Mapper] - Some relations ref is missing on some entity types

### ISSUE THREAD

**Issue by RomuDeuxfois** [LuatixHQ/opencti#5838]
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Csv Mapper
2. Take Mac Adress entity type
3. Created by is not present

## Expected Output

1. Created by and other ref are present

## Additional information

Seems to be a problem in back-end, when we resolve all attributes and all relation refs.
In csvMapper-domain file, we compute attributes and relation refs based on schemaAttributesDefinition & schemaRelationsRefDefinition, but this schema don't have the full list of entity types.

We need to retrieve all entity types before calculating their attributes and relationship references.

**Comment by Jipegien** [comment]
The "created by" is not to be mapped. It is always the OpenCTI user technically creating the entity. For others ref, problems remains. Already disccussed with @lndrtrbn
