### ISSUE TITLE
Broken attack patterns matrix everywhere

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5841]
## Description

1. This issue leads multiple screens to not work correctly.
2. Do a query like:

```
query {
  attackPatterns(first: 5000) {
    edges {
      node {
        id
      }
    }
  }
}
```

Result is:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/faef69f1-a63b-44d1-824d-fb01d57bfe58)

Only 500 first are returned.

**Comment by richard-julien** [comment]
This is expected behavior. If the attackPatterns ask for 5000 elements we need to rework the screen or create a specific API

**Comment by Jipegien** [comment]
This current behaviour is not good enough. We need to fix this for the next major release. We are currently not consistent in our displaying of matrices and this is a major CTI use case.
