### ISSUE TITLE
Hygiene connector displays user's name for enrichment actions

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#5842]
## Description

When creating an observable, the Hygiene connector seems to be using certain user's name for enriching the observable (not necessarily the name of the creator, it may be a completely different user).

## Environment

 OpenCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Choose a domain name for instance [here](https://github.com/MISP/misp-warninglists/blob/main/lists/alexa/list.json) and create it in the OCTI instance
2. The hygiene connector will "impersonate" a user to replace the score, add hygiene to the label and add references.

## Expected Output

Connector must display its own name for enrichment actions.

## Actual Output

The connector impersonates certain users to display the origin of the enrichment.

## Additional information

Example here: https://testing.octi.staging.filigran.io/dashboard/observations/observables/e9adde24-4e07-428e-9173-0e30cfc5404a
## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/d6826cb6-e65a-4e86-b7f5-8b6b6a01b73e)

**Comment by yassine-ouaamou** [comment]
Even when it's another user than yassine.ouaamou who creates the observables, it's the same user who is impersonated:
https://testing.octi.staging.filigran.io/dashboard/observations/observables/1f534482-ebd4-4b7e-b151-8a8c92a1e94c
https://testing.octi.staging.filigran.io/dashboard/observations/observables/befa2a29-82a1-4661-b9cc-053ca24ecd80

**Comment by Jipegien** [comment]
@helene-nguyen & @Megafredo can you take a look when available ?

**Comment by helene-nguyen** [comment]
Yes, we will take a look @Jipegien :)

**Comment by labo-flg** [comment]
I let you guys do it @helene-nguyen or @Megafredo ;)

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/opencti/issues/6042
