### ISSUE TITLE
Investigation Relationships

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#5852]
## Use case

When a user clicks on an entity in the investigation screen the user should have the ability to see relationships in the dialog box to the right that opens. Current fields are Value, Type, Creation date, Description, Confidence level, Marking, Author, Creators, Reports, External references.

## Current Workaround

None

## Proposed Solution

Add relationships to dialog box between Reports and External references.

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
@explorecti so currently, these information pertains to the entity and not the relation. If you click on the relation, you'll have the information from the relation. Isn't this sufficient for you?

What is the use case behind your request that you can't currently achieve? 
Also, for entities that have let's say 5+ more relations, if you would click on this entity, what relation information should we display?

**Comment by nino-filigran** [comment]
@explorecti Given I think we have already a screen for this and I have not heard from you after my question, I'm closing this ticket for now. If you feel that either my answer is not satisfactory or if I have not understood well your request, please re-open this ticket with a more detailed comment. I'll be happy to take it from there.
