### ISSUE TITLE
Inferred Indicators not included in report when generating indicators from observables included in the report

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5853]
## Description

With the rule **INDICATORS PROPAGATION IN REPORTS** enabled, if a user generates indicators from observables that are included in the report, the indicators and the "based-on" relationships are created but not included in the report

## Environment

Local as I didn't want to enable the rule in any platform

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable the rule "INDICATORS PROPAGATION IN REPORTS"
2. Create a report
3. Add two newly created observables (not related to any entity) to the report
4. In the "Observables" tab of the report, select them and click on "Indicators/observable generation"

## Expected Output

The indicators and relationships with the observables should be created and included in the report

## Actual Output

The indicators and relationships with the observables are reated but not included in the report.
They are shown in the overview of the report though

## Screenshots (optional)

![issue_propagate_rule](https://github.com/OpenCTI-Platform/opencti/assets/7083405/7688b746-6cdd-48c0-97e0-bfec681235fa)

## Hint
It seems like the inferred indicators/relations are stored in "object_refs_inferred" and we are maybe not showing the content of this list in the report.

**Comment by richard-julien** [comment]
Does export inferences should be done everywhere?

**Comment by richard-julien** [comment]
Will be handle by https://github.com/OpenCTI-Platform/opencti/pull/5920
