### ISSUE TITLE
[CSV Mapper] TEST function always returns an error when trying to load a csv file on Firefox

### ISSUE THREAD

**Issue by JeremyCloarec** [LuatixHQ/opencti#5854]
## Description

When testing a CSV file in a CSV mapper on Firefox, the error "This file is not in the specified format" is always returned

## Environment

1. OS (where OpenCTI server runs):  Windows
2. OpenCTI version: 5.1.12.29
3. OpenCTI client: frontend
4. Other environment details: running on Firefox 122.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open any CSV mapper
2. Click on "TEST"
3. Select any csv file

## Expected Output

The data of the file, or an error if the data is in an incorrect format

## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/159018898/8fd77535-b96a-41aa-b46b-4325d8a960d0)

## Additional information

The problem doesn't occur on other browsers. 
The problem occurs because Firefox reads the csv file as a MIME type "application/vnd.ms-excel", whereas other browsers read the file as a "text/csv" file.
It seems to also be correlated with the fact that Windows reads the .csv files as an excel file, as seen in the other screenshots. It seems like Firefox trusts the OS with the type of the file, whereas other browsers have their own interpretation of the file type given the file extension.

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/159018898/d699444d-605d-4e4c-be5d-76a36064fb00)

**Comment by lndrtrbn** [comment]
The fix I can see is to add the mimetype `application/vnd.ms-excel` in the list of allowed mimetype when uploading the file. It probably means that user can also imports `.xls` files and the import will obviously crash as we do not managed this format but at least Firefox users can import csv files.
