### ISSUE TITLE
Access denied despite capabilities

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5856]
## Description

This error appears in the context of data segregation by organization

If I am not part of the Platform main organization, I get an "forbidden access" error despite the fact that I have the capabilities to enrich the data (see screenshot to look the full configuration)

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Org A as Platform main organization
2. User B part of Org B
3. User B with read/write/update access on knowledge + enrich capabilities
4. User B create an IPv4 not existing in the platform (ensure this by looking in the platform with a user who has full access)
5. Try to enrich the IPv4 with user B
-> "forbidden access" error

#### Platform main organization (Org A)

![main_org](https://github.com/OpenCTI-Platform/opencti/assets/70956706/04f8f22c-61f8-4e95-a0c5-2d5fb59f1ea2)

#### User B config

![user_org](https://github.com/OpenCTI-Platform/opencti/assets/70956706/783e3753-45e3-47bf-8838-bbd28eb93f50)

#### Config of the User B's Group

![group_config](https://github.com/OpenCTI-Platform/opencti/assets/70956706/2d3f931c-d08b-4666-9184-3fcb5285ad79)

#### Config of the User B's Role

![role_config](https://github.com/OpenCTI-Platform/opencti/assets/70956706/82e1f5dc-428a-499e-ac1d-c07009b9cd72)

#### Error raised

![forbidden_access_to_enrich](https://github.com/OpenCTI-Platform/opencti/assets/70956706/0d3d8901-6b5a-439f-8b14-bacd2387d3c6)

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/opencti/issues/6042
