### ISSUE TITLE
[Data segregation] Enriching an observable removes sharing to organizations

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5857]
## Description

When an observable is enriched, sharing to organizations is removed.

Maybe it's not a bug? The problem appears because even if the observable was created by a user from a non-main organization and someone enriched it, the user who created it will no longer be able to access it.

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. User A part of Org A
2. Org A platform main org
3. User A share an IPv4 with Org B
5. User A enrich the IPv4
-> The sharing with Org B is removed

## Expected Output

Keep the sharing with Org B

**Comment by richard-julien** [comment]
Multiple problems here:
- Enrich must be done as the connector user and not the user that ask for enrich.
- The information of the granted_refs must not be lost by the enrich connector.

**Comment by JeremyCloarec** [comment]
I wasn't sure if the first problem was a design choice or a real problem

Also, correct me if I'm wrong, but think there are two different parts to the problem of granted_refs being lost by the enrich connector.
After fixing the granted_refs being lost for the enriched entity, we should also apply the granted_refs to the entities created during the enrichment with a relationship to the entity.

I've been working on it for some time, but I'm struggling to find a proper fix for it currently

**Comment by richard-julien** [comment]
Seems the same problem as https://github.com/OpenCTI-Platform/opencti/issues/5856

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/opencti/issues/6042
