### ISSUE TITLE
Unable to export as PDF/image

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#5867]
## Description

When attempting to export anything (report, dashboard, entities, etc) as a PDF, it never actually downloads. I am able to download dashboards with no data, but when anything is displayed, the PDF will not generate. JSON/CSV can be downloaded. Image formats of dashboards will not generate.

After waiting:

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/6f076bc3-49c1-43b4-8968-b90e509a0996)

Export PDF connector shows no logs to suggest why this is happening, but I do see the following in platform logs:

`1970/01/01 08:21AM WRN Execution timeout, too many concurrent call on the same entities | category=APP errors=[{"attributes":{"genre":"BUSINESS","http_status":500,"participantIds":["relationship--44c07b56-a8a8-4835-a459-d7c14c1a1dc9","relationship--da16c5a0-5a21-551a-aef4-885a5e634f66","0547dd7c-7c06-470d-bb7d-f37cdc93ac98","a163592f-d28a-4e54-a139-30474fcf539c"]},"message":"Execution timeout, too many concurrent call on the same entities","name":"LOCK_ERROR","stack":"LOCK_ERROR: Execution timeout, too many concurrent call on the same entities\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at LockTimeoutError (/opt/opencti/build/src/config/errors.js:104:51)\n    at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2788:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at createRelation (/opt/opencti/build/src/database/middleware.js:2796:16)\n    at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:91:19)"}] inner_relation_creation=1 operation=StixCoreRelationshipAdd operation_query=mutation StixCoreRelationshipAdd($input:StixCoreRelationshipAddInput!){stixCoreRelationshipAdd(input:$input){id standard_id entity_type parent_types}} size=588 timestamp=2024-02-08T15:45:47.674Z type=WRITE_ERROR user={"applicant_id":"9e63e52f-35e3-4fdd-a379-d0e3420c96f9","call_retry_number":"1","group_ids":["0f8e5d31-56b6-4bda-ad97-af81f28c3283"],"ip":"::ffff:10.0.5.4","organization_ids":["8763664e-d84b-4ed1-942d-54891bbba7a8"],"socket":"query","user_id":"9e63e52f-35e3-4fdd-a379-d0e3420c96f9","user_metadata":{}} version=5.12.28`

`WRN [SEARCH] Pagination limited to max result config | category=APP max=500 size=1000 timestamp=2024-02-08T15:47:44.901Z version=5.12.28`

`ory":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Cannot query field \"edges\" on type \"MarkingDefinition\".","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: Cannot query field \"edges\" on type \"MarkingDefinition\".\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:311:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:321:48)\n    at Object.willSendResponse (/opt/opencti/build/src/graphql/loggerPlugin.js:115:20)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 1)\n    at S (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:530:5)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:273:16)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"},{"message":"Cannot query field \"edges\" on type \"MarkingDefinition\".","name":"GraphQLError","stack":"GraphQLError: Cannot query field \"edges\" on type \"MarkingDefinition\".\n    at Object.Field (/opt/opencti/build/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)\n    at Object.enter (/opt/opencti/build/node_modules/graphql/language/visitor.js:301:32)\n    at Object.enter (/opt/opencti/build/node_modules/graphql/utilities/TypeInfo.js:391:27)\n    at visit (/opt/opencti/build/node_modules/graphql/language/visitor.js:197:21)\n    at validate (/opt/opencti/build/node_modules/graphql/validation/validate.js:91:18)\n    at validate (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:477:12)\n    at processGraphQLRequest (/opt/opencti/build/node_modules/apollo-server-core/src/requestPipeline.ts:267:32)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at processHTTPRequest (/opt/opencti/build/node_modules/apollo-server-core/src/runHttpQuery.ts:437:24)"}],"inner_relation_creation":0,"level":"error","message":"Platform unmanaged direct error","operation":"Unspecified","operation_query":"query StixCyberObservable($id:String!){stixCyberObservable(id:$id){id entity_type objectMarking{edges{node{id definition_type definition}}}observable_value}}","size":56,"time":69,"timestamp":"2024-02-08T15:48:07.837Z","type":"READ_ERROR","user":{"group_ids":["0f8e5d31-56b6-4bda-ad97-af81f28c3283"],"ip":"::ffff:10.0.5.4","organization_ids":["8763664e-d84b-4ed1-942d-54891bbba7a8"],"socket":"query","user_id":"a6a4f7c4-4b37-4216-a8c3-7992643e37f6","user_metadata":{}},"variables":{"id":"ipv4-addr--3da58432-02b7-5e4d-9be4-73c5e7ffd287"},"version":"5.12.28"}`

## Environment

5.12.28

Any help would be appreciated, or if I can help narrow down the cause! :)

**Comment by Jipegien** [comment]
I am not able to reproduce on Dashboards.
Regarding PDF export of Containers or Entities, I am not reproducing the error but the process is very very long! In some configuration, it may cause timeout.

@dominictory can you share options you chose for generating the export ? Full export/simple export? And can you tell us if the entity or report you want to generate a PDF with contains/is linked to a lot of other entities ?

**Comment by SamuelHassine** [comment]
Hello,

It seems your connector version is not aligned with the platform version. Please be sure to upgrade everything to 5.12.29.

**Comment by dominictory** [comment]
> I am not able to reproduce on Dashboards. Regarding PDF export of Containers or Entities, I am not reproducing the error but the process is very very long! In some configuration, it may cause timeout.
> 
> @dominictory can you share options you chose for generating the export ? Full export/simple export? And can you tell us if the entity or report you want to generate a PDF with contains/is linked to a lot of other entities ?

Morning, thank you for reply. I've tried to generate both a simple and full PDF for a report with 16 entities, and both options worked fine. 

Other formats (except image for dashboards) seem to export fine in simple and full.

A report with more entities (96) exports in full, but takes a while. I suspect 150-200+ entities will result in failure here.

I have 6 dashboards with varying amounts of displayed data, and none seem to export as PDF/image.

@SamuelHassine all of my connectors are set to env var OPENCTI_VERSION, which is 5.12.28, the version I am using at the moment. Does 5.12.29 resolve any issues around exporting reports with lots of entities or dashboards with lots of data? Not sure exactly what you mean here.

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/59f7165e-a982-4d70-888f-508fe53209a6)

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/1604e2a9-8be1-4b41-954d-2067a6ad182a)

**Comment by dominictory** [comment]
@SamuelHassine @Jipegien not sure this is solved? All of my connectors/dependencies are set to 5.12.28. Unless there's explicit improvements in 5.12.29 to resolve the above, I wouldn't want to upgrade just yet.
