### ISSUE TITLE
Refinement and enhancement of the rich text editor in content

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5882]
## Use case

Refinement and enhancement of the rich text editor in content:

* Be able to have suggestion "@" with auto completion to use data from the platform (threat actors, intrusion setc, etc.)
* Be able to insert a widget in SVG format like in dashboard
* Optional: graph?

**Comment by nino-filigran** [comment]
Will be tackled in the context of templating: https://github.com/OpenCTI-Platform/opencti/issues/3402
