### ISSUE TITLE
Background tasks errors never have a source info

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#5885]
## Description

The error dialog in data > processing > task never show anything in the source column.

## Environment

OCTI 5.12.29

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. start a bg task that will produce errors (unsure how, it happened to me during development)
2. open error panel for this task once completed

## Expected Output

Something in 'source' column

## Actual Output

Nothing. and judging the code, it will never happen.

## Additional information

`TasksLists.jsx`: `source `field is not queried
Graphql: `source` field not available in `BackgroundTaskError` type
`taskManager.js:appendTaskErrors`: source field is not set when appendign the task error

... so either we implement the feature, or we remove this misleading column.

**Comment by nino-filigran** [comment]
Not sure how to reproduce this @labo-flg. Maybe doable when the confidence level will be enforced. So I would be keen to remove it for now.

**Comment by labo-flg** [comment]
I don't know how we can cause errors in background tasks easily... It's not even linked to confidence level work actually.
I just came across this issue while working on it.

We can remove the column for now, and seek to improve later 👍
