### ISSUE TITLE
Be able to schedule the trigger of a playbook instead of react on some criterias

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5929]
## Use case

As a "trigger" of the playbook, be able to define:

* A scheduling
* A filter

**Comment by sudesh0sudesh** [comment]
Hello @SamuelHassine , I was about to raise similar issue, can this be used as scheduler to trigger something like enrichment connector ?  I don't want to create a duplicate issue. Thank you.

**Comment by nino-filigran** [comment]
@SamuelHassine I'm not sure to understand this request: can you maybe be more explicit of the problem you're trying to solve?
What's the scheduling will enable that we cannot do right now?

**Comment by dominictory** [comment]
@SamuelHassine @sudesh0sudesh @nino-filigran our use case; we'd like to run periodic domain checks using the dnstwist connector without having to run it manually, it would be nice to define targets for the connector (like when you select multiple domain name observables and bulk enrich), a schedule, and enrichment.
