### ISSUE TITLE
Markdown in rich text fields is reverted when first applied

### ISSUE THREAD

**Issue by JeremyCloarec** [LuatixHQ/opencti#5943]
## Description

When typing in a rich text field and selecting a markdown, the markdown is first correctly applied, but is quickly reverted back.
See the linked video for a more explicit description

## Environment

1. OS (where OpenCTI server runs): Windows 10
2. OpenCTI version: 5.12.29
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open Settings/Security/Roles
2. Open and edit any role
3. Write a text in the description field
4. Apply a markdown

## Expected Output

We expect the markdown to be correctly applied.

https://github.com/OpenCTI-Platform/opencti/assets/159018898/9a26fb69-cbc1-42ae-b08b-f14e73843052

**Comment by nino-filigran** [comment]
After trying to reproduce, it happens only in:
- Groups
- users
- organisation 
- groups

**Comment by CelineSebe** [comment]
Tested locally. I didn't see any problem, the markdown is applied correctly after validation of the form

**Comment by nino-filigran** [comment]
@CelineSebe I don't know what to say, it happens on our internal platform, so we still have an issue:
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/18b966b5-9ea0-4360-8858-79564b4f238a)

Feel free to contact me so that I can show you the point.

**Comment by CelineSebe** [comment]
![organization](https://github.com/OpenCTI-Platform/opencti/assets/87119259/1e9e4e6d-2be2-408c-aebe-229907188b70)

**Comment by nino-filigran** [comment]
@CelineSebe I think my comment was not 100% aligned with @JeremyCloarec 's bug.
There are 2 things:
- indeed, when you modify an entity and try to apply a specific look and feel, it is not applied in the editor (cf his video)
- additionally, the markodown style is not applied to the description (which is something different) - this does not happen on testing.

I've modified my comment since it applies everywhere, also in groups.

Are you aligned with testing?

**Comment by CelineSebe** [comment]
Locally, I don't reproduce the bug in the video. Once validated (single click outside the input field), the description is updated with Markdown.

**Comment by Jipegien** [comment]
The result of applying is not consistent. Sometimes it is removed, but not everytime. Seems related to the first try after opening the form.
