### ISSUE TITLE
Knowledge Relationships

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#5944]
## Use case

User navigates to https://opencti:8443/dashboard/arsenal/malwares/d2108fa4-11b6-4bb0-ab09-301bc5bc79d7/knowledge/overview, on the right pane there is no easy pivot to relationships. This relationship page https://opencti:8443/dashboard/arsenal/malwares/d2108fa4-11b6-4bb0-ab09-301bc5bc79d7/knowledge/relations/6d6adab3-6b00-4447-ad6a-497547f19bf5

## Current Workaround

Navigating to https://opencti:8443/dashboard/arsenal/malwares/d2108fa4-11b6-4bb0-ab09-301bc5bc79d7 and selecting individual relationships

## Proposed Solution

Navigating to https://opencti:8443/dashboard/arsenal/malwares/d2108fa4-11b6-4bb0-ab09-301bc5bc79d7/knowledge/relationships will allow the pivot of the related information.

## Additional Information

![malware_overview](https://github.com/OpenCTI-Platform/opencti/assets/141024547/224d2013-5eae-4623-9d87-bcf76ca69e0b)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
@explorecti can you specify a bit more? I'm not able to see your links.

**Comment by nino-filigran** [comment]
@explorecti Without any response, I'm closing this feature request for now since it's a bit unclear to me. Feel free to re-open it once you will have provided some additional details.
