### ISSUE TITLE
[Playbooks] remove marking definition doesn't work

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5950]
## Description

The action of removing marking definitions does not function in playbooks

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have an entity with TLP:GREEN 
1. Create a playbook that does the following:
- Listen to edition
- Manipulate knowledge -> Remove - Marking definitions - TLP_GREEN
- Send to Ingestion
3. Start the playbook
4. Edit a field of the entity

## Expected Output

The marking TLP:GREEN is deleted

## Actual Output

The marking TLP:GREEN is not deleted

## Additional information

Because of this bug, the "Replace Marking Definition" doesn't work in some cases like when replacing TLP:RED by TLP:GREEN.
Since the remove doesn't work, the add is ignored as RED is higher that GREEN.
This case is interesting to check once the issue is fixed.

**Comment by Kedae** [comment]
Need to add a correct cleaning of action on front side

**Comment by richard-julien** [comment]
Could be done along with https://github.com/OpenCTI-Platform/client-python/issues/566
