### ISSUE TITLE
User without rights can access specific pages through URL of the platform (CSV mapper)

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#5954]
## Description

A user without rights can access specific pages of the platform by entering the URL. 

## Environment

Testing

## Reproducible Steps

User see page with data: 
1. Have a user without any rights (or at least without access knoweldge)
2. Input in the URL the path to go to specific pages
3. User can access these pages and view data

Specific pages: 
- data/processing/csv_mapper

User see pages without data:
1. Have a user without any rights (or at least without access knoweldge)
2. Input in the URL the path to go to specific pages
3. User can access these pages but no data are present view data

Specific pages: 
- data/connectors

Additionnally, user is not logged out when navigating to: 
settings/parameters OR security OR customization OR activity OR file indexing 

Also, some other pages dispaly an error message
dashboard/import = This page is not found on this OpenCTI application.

## Expected Output
If user does not have the right, the user should not be able to access these pages and should land on login page/

## Actual Output

User access the page and view data.
## Additional information

I've created a user on testing: 
username: testNoright@test.com

**Comment by aHenryJard** [comment]
> should land on login page/

I disagree with this last part, if user has an account it means that user is authorized to login: he/she is authorized to enter the application. There is no need to redirect to login page, redirect to tge home page is enough. If user has no right on nothing, then he/she should just see an empty data application.
