### ISSUE TITLE
"Create and map" > Knowledge crashes when certain content is entered

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#5961]
## Description

I have tried to copy the readme from https://github.com/AmnestyTech/investigations/tree/master/2021-05-28_qatar into a new report and tag it, but when I do, I get "Error: An unknown error occurred. Please contact your administrator or the OpenCTI maintainers." The content includes images. Is this why create and map is crashing?

## Environment

1.     Mac OS 14.3
2.     OpenCTI version: 5.11.12
3.     OpenCTI client: frontend
4.     Other environment details: Chrome browser

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Copy and paste the readme from https://github.com/AmnestyTech/investigations/tree/master/2021-05-28_qatar into a new report 
2. Select "create and map." 
3. The report gets created.
4. Go to Reports>Knowledge and try to select the content you pasted. Just selecting may throw an error.

## Expected Output

OpenCTI should handle unexpected content more gracefully, either excluding content it is not equipped to handle, or letting the user select and tag any content that appears in this view.

## Actual Output

I get "Error: An unknown error occurred. Please contact your administrator or the OpenCTI maintainers."

## Additional information

none

**Comment by nino-filigran** [comment]
@gusandrews 
Can you try to upgrade to latest version? Let me know if the problem persists

I cannot reproduce your bug: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/acb1e564-a0eb-427c-9dc4-dceb6eae78a5)

**Comment by marieflorescontact** [comment]
I cannot reproduce either

**Comment by gusandrews** [comment]
Yeah, alas I no longer have access to my older instance, and I can't reproduce it in the demo instance. Probably best to close. Apologies for the distraction.
