### ISSUE TITLE
Quick subcription button is not working properly

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#5963]
## Description

1. Go to a threat actor
2. Click on the bell

=> The subscription is created but button is not turned to active. Re-clicking do nothing (where it should open a panel). You have to reload the full page.

**Comment by nino-filigran** [comment]
@CelineSebe, @lndrtrbn @Kedae  there is a regression on this one: does not work anymore niether in demo nor testing.

**Comment by nino-filigran** [comment]
@CelineSebe @lndrtrbn & @Kedae there've been a small regression: the bell does not look active, but there is at least a success message. However, the counter of subscriber is not updated, nor the the bell, unless you reload the page (both in testing and demo), hence the reason wh'y I've reopened it.

**Comment by Kedae** [comment]
I'm on it.
