### ISSUE TITLE
Error when accessing the analyst workbench of an imported Malware Analysis

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5965]
[malware_analysis.json](https://github.com/OpenCTI-Platform/opencti/files/14283919/malware_analysis.json)
## Description

After importing a STIX bundle with a malware analysis, I have an error when accessing its workbench

## Environment

Filigran Prod

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data Import page
2. Upload the attached file (it contains one Malware Analysis)
3. Import it using ImportFileStix
4. A workbench is created. Click on it

## Expected Output

Access to the Analyst Workbench where we can see one Malware Analysis

## Actual Output

Error

**Comment by nino-filigran** [comment]
Reproduced on Demo but not on Testing, meaning that a fix is already there. Therefore, tagged as won't fix.
