### ISSUE TITLE
[Dashboard] Show TTP id on Horizontal Bar Widget

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5966]
## Use case

Unlike Radar widget, Attack patterns ids are not show on a Horizontal bar issue:
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/3e932aaa-821b-416a-bd82-22038b106503)

**Comment by labo-flg** [comment]
the labels are also wrong: on horizontal bars, we are missing the mitre id as prefix.
We'll fix this in the same batch.

**Comment by nino-filigran** [comment]
Closing this issue since it's avaiable on testing.
