### ISSUE TITLE
Give the user a GUI to de-select tagged entities when OpenCTI imports a PDF

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#5968]
## Use case

As a threat intelligence analyst importing a lot of PDFs with newspaper citations in them
I want a GUI for quickly adding certain IoCs to a whitelist any time I import
So I don't need to add a filter for (for example) nytimes.com or guardian.co.uk at the command line every time I import a PDF
Or manually validate these domain names every time I import a new report

As OpenCTI users named Kevin and Elise**
We want a GUI for quickly dismissing and whitelisting entities when we import PDFs
So that we don't have to remove tags for the malware named "Kevin" and "Elise" every time someone cites our work in their report

** yes, I realize this is entirely the fault of whatever genius gave malware the names "Kevin" and "Elise," but this is the world we find ourselves in, no? And yes, everyone else also needs to be able to un-tag Kevin, Elise, or who or whatever else they need to when necessary.

## Current Workaround

Users currently need to either create a whitelist by editing a file at the command line, or repeatedly manually dismissing certain tagged entities when validating a workbench of imported entities. This takes additional time and annoyance. At the command line, whitelisting could result in errors due to typos. "Validate workbench" does not always work as expected; I sometimes told it to dismiss domain names, but found they had been imported into my entities database anyway.

## Proposed Solution

It would be nice to have a screen, preferably right after a PDF is ingested, when the user can choose and discard the auto-tags generated on import. If that is not possible, once a report has been pulled into reports>knowledge>content mapping view>mapping, the user needs to be able to 
1) quickly see where in the report they were generated (to validate when it is referring to Report Author Kevin and when it is referring to Malware Kevin—and note, both could be the case in one report) 
2) possibly indicate that they don't want entities pulled in from certain parts of the paper, like footnotes or citations,
3) delete entity tags if desired, and
4) it would additionally be nice if they could have a dropdown to select the entity category, particularly in the cases of sectors/systems/organizations/individuals, as they can share names (see again, Individual Kevin vs Kevin Enterprises LLC vs Malware Kevin)

## Additional Information

For an example of some of the challenges of PDF import, try using https://stratcomcoe.org/cuploads/pfiles/5december_report_philippines.pdf as a test case. Among other things, it tagged one of the *Panda APTs as an entity, when the word "panda" does not appear anywhere in that report. It would be good to support the user in dismissing false positives as quickly as possible.

Despite this minor UX friction I continue to be delighted both by the fact that you've made the PDF import > unstructured content tagging flow possible, and that your team is user-responsive and has long-term vision for how interfaces are evolving!

## If the feature request is approved, would you be willing to submit a PR?

I don't have the coding skills to submit a PR, but I'd love to discuss possible UX contracting with Filigran :)

**Comment by gusandrews** [comment]
trivia relevant to this ticket: I believe I was told that in some parts of Germany when you want to refer to the Platonic ideal of the stupidest person you can imagine, you use the name "Kevin"

**Comment by gusandrews** [comment]
One more thing that could quickly make this easier for users is adding information about whitelists to the documentation around PDF import. What I was told when I asked for whitelists was:
 https://github.com/OpenCTI-Platform/connectors/blob/master/internal-import-file/import-document/src/reportimporter/filter_list/filter_list_Domain  is the whitelist file to edit.
"1. An observable is not necessarily malicious. I suggest you let them import and lower their score to 0 (= legitimate). Each time they're imported, they'll be merged with existing observables with their score set to 0.
2. Advice: If this is not the case, use the Hygiene connector. It will automatically detect these legitimate Observables. It will lower their score (to 15 from memory) and add its "hygiene" label to note that it processed them."

**Comment by Jipegien** [comment]
Draft mode should cover the need to better see irrelevant elements imported from documents. Regarding domain names from header or footer of documents, best way to handle it is to let them be imported and either be treated by the hygiene whitelist or setting them a low score/low confidence at the first import. This way, even if they are present in the platform, they are considered as begnin and the de-duplication mechanism will handle further import of these observables.

**Comment by gusandrews** [comment]
Whitelisting is useful, but is there a plan to make a GUI interface for it? The command-line interface is a nuisance.

**Comment by Jipegien** [comment]
We haven't planned to add a GUI for it at the moment.
