### ISSUE TITLE
Names are truncated when exporting a Radar widget as CSV

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#5969]
## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Radar widget showing used Attack patterns (You can find screenshots of the config of the widget I used in the Screenshots section)
2. Create a Horizontal widget with the same config
3. Export the widgets as CSV

## Expected Output

CSV with two columns: the category of the Attack pattern and the count

## Actual Output

The category of the attack pattern is truncated for the Radar widget

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/290cd700-86b8-41fb-9f31-e43141aa3306)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/2f5794d7-613a-47a0-9845-21a77792f84e)

**Comment by yassine-ouaamou** [comment]
A dashboard has been created to illustrate this issue in the Testing platform. It's called **TTPs issue 5969**

**Comment by nino-filigran** [comment]
Reproduced. To be specific, you need to download the CSV and see that in the in the name column (first column), anything displayed with "..." in the widget will also be displayed with "..." on the CSV (for the radar), while it's displayed in full for the horizontal bars.

**Comment by CelineSebe** [comment]
Once the csv has been downloaded, in the first column: the name of the category is displayed and in the second column: the number is displayed correctly.
[gyinhwq2.csv](https://github.com/OpenCTI-Platform/opencti/files/14313421/gyinhwq2.csv)

**Comment by nino-filigran** [comment]
@CelineSebe you need to have data with longer names. To give you an example, this is the output in Yassine's example: 
- not truncated: 
[tth2nzx3.csv](https://github.com/OpenCTI-Platform/opencti/files/14328376/tth2nzx3.csv)
- truncated: 
[409u6kwuf.csv](https://github.com/OpenCTI-Platform/opencti/files/14328386/409u6kwuf.csv)

**Comment by CelineSebe** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/520f893a-02e0-447e-96b0-a5c56ecc534e)
A solution has been found, but the combination of the name and reference number appears cluttered on the radar display.

**Comment by CelineSebe** [comment]
@nino-filigran 
![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/520f893a-02e0-447e-96b0-a5c56ecc534e)

A solution has been found:

- We keep all the name information for the csv.
- We no longer truncate the name in the radar. The combination of the name and reference number may appear cluttered on the radar display.
