### ISSUE TITLE
Reports with many observables cause errors, hangs in PDF imports

### ISSUE THREAD

**Issue by gusandrews** [LuatixHQ/opencti#5972]
## Description

OpenCTI hangs for a long time or says "an error occurred" when you try to view the observables extracted from an imported PDF; it appears to happen when there are many observables. See for example https://demtech.oii.ox.ac.uk/wp-content/uploads/sites/12/2021/03/Case-Studies_FINAL.pdf , which yields 2594 observables.

## Environment

Error message in:

1.     Mac OS 14.3
2.     OpenCTI version: 5.11.12
3.     OpenCTI client: frontend
4.     Other environment details: Chrome browser

Hangs in:

1.     Mac OS 12.7.3
2.     OpenCTI version: 5.12.31, demo.opencti.io
3.     OpenCTI client: frontend
4.     Other environment details: Firefox browser

## Reproducible Steps

1. Given the specifications in "Environment" above:
2. Import https://demtech.oii.ox.ac.uk/wp-content/uploads/sites/12/2021/03/Case-Studies_FINAL.pdf , through the "Data import and analyst workbenches" function in the upper right.
3. When it has finished importing, click the report in the "analyst workbenches" pane.
4.  2594 observables should be registered under the observables tab for the report (this may take a moment).
5. Attempt to click that tab.
6. OpenCTI may deliver an error message, or the browser may notify the user that OpenCTI is slowing down performance.

## Expected Output

OpenCTI should be able to handle large numbers of observables gracefully, either presenting them to the user without errors or warning the user that a high number of observables may cause an unwanted drain on OpenCTI and suggest alternate ways of importing a report (breaking it down into pieces, entering observables using a CSV, etc)

## Actual Output
OpenCTI crashes or hangs.

## Additional information

This performance issue might be avoided by making some changes to how aggressively OpenCTI tries to match content in a PDF, or by the [GUI suggested in my other ticket](https://github.com/OpenCTI-Platform/opencti/issues/5968).

**Comment by Jipegien** [comment]
It is linked to the available memory for the browser that is used to display the list. As Analyst Workbenches will soon be replaced by a more complete Draft feature, we won't improve the handling of massive report with analyst workbench.
