### ISSUE TITLE
[Playbooks] Entities linked with inferred relationships missed by "resolve container references" rule

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#5991]
## Description

When I want to retrieve the entities contained in a report using the component "Apply predefined rule : resolve container references", objects contained following the application of an inference rule (e.g. Indicators propagation in reports) are not retrieved.

My guess is that "Apply predefined rule : resolve container references" (and maybe "Apply predefined rule : resolve neighbors relation") doesn't take inferred relationships into account when solving linked objects.

## Environment

OCTI 5.12.31
filigran prod instance

## Reproducible Steps

The playbooks to create:
1. Listener on modification event, with filters "entity:report + label:test"
2. Apply predefined rule : resolve container references
3. Log data in standard output

(nb: you can use the playbook "Bug retrieve inferred entities" on the filigran prod instance)

Steps to create the smallest reproducible scenario:
1. Create the above playbook
2. Find a report with entities contained thanks to inference rule (nb: you can use the report "Debug retrieve inferred entities" on the filigran prod instance) and add the label "test"
3. Look inside the log of the playbook. You will not find the infered entities

**Comment by SamuelHassine** [comment]
Option added: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/ea1cddf1-68d4-4c88-ac2a-ab787306b862)
