### ISSUE TITLE
remove not stix core relationship types in Data>Relationship filter

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#5995]
## Description

Filtering on Sighted in/at is broken, it returns nothing. Dashboards and API are broken as well

```
/dashboard/data/relationships?filters={"filterGroups":[],"filters":[{"id":"a2d8ed3f-c917-4a07-a8fd-dadaa6da9697","key":"relationship_type","values":["stix-sighting-relationship"],"operator":"eq","mode":"or"}],"mode":"or"}&sortBy=created_at&orderAsc=false
```

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.12.29
3. OpenCTI client: Frontend
4. Other environment details: Clustered

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Visit /dashboard/data/relationships?filters={"filterGroups":[],"filters":[{"id":"a2d8ed3f-c917-4a07-a8fd-dadaa6da9697","key":"relationship_type","values":["stix-sighting-relationship"],"operator":"eq","mode":"or"}],"mode":"or"}&sortBy=created_at&orderAsc=false
2. get an empty `edges`

## Expected Output

The Sighted in/at SROs being returned reliably 

## Actual Output

```
{
    "data": {
        "stixCoreRelationships": {
            "edges": [],
            "pageInfo": {
                "endCursor": "",
                "hasNextPage": false,
                "globalCount": 0
            }
        }
    }
}
```

## Additional information

N/A - Was working on 5.12.25 - @SamuelHassine @richard-julien this is a long running trend, any way y'all can implement testing this is a headache to keep hitting these filter bugs every-other release

**Comment by Jipegien** [comment]
All sightings can be retrieved and filtered in events/sightings, as it is not a "normal" SRO. Are you able to retrieve what you want from there @MaxwellDPS?

**Comment by Archidoit** [comment]
Indeed, sightings are not stixCoreRelationships, there are not listed in the Data>Relationship tab.

**Comment by Archidoit** [comment]
--> The relationship types 'contains' and 'sighted at' should not be available in the relationship type filter list.

**Comment by MaxwellDPS** [comment]
This is also broken in the dashboard @Archidoit and is now a change in behavior, sighed at was available in Data>Relationship tab previously

**Comment by Archidoit** [comment]
The filter was available in Data>Relationship, but was useless since sightings are not listed in this tab.

**Comment by MaxwellDPS** [comment]
@Archidoit they most certianly were

**Comment by MaxwellDPS** [comment]
This HAS NOT been addressed, there is no webUI way todo this now -- @SamuelHassine Errm

**Comment by Archidoit** [comment]
@MaxwellDPS  Please be respectful of our code of conduct (https://github.com/OpenCTI-Platform/opencti/blob/master/CODE_OF_CONDUCT.md). We all try to make the platform better, and it's easier to do it with calm and constructive discussions.

Stix core relationships are available in /dashboard/data/relationships, sightings are available in dashboard/events/sightings.
In dashboards the possibility to select the 'sighted in/at' relationship_type in filters will remain available to be able to aggregate on sightings.

For the problem with sighted in/at relationship type filter in dashboards, I opened a new Github issue : https://github.com/OpenCTI-Platform/opencti/issues/6065. I'll resolve this bug.
 
Thanks.

**Comment by MaxwellDPS** [comment]
> Gracefully accepting constructive criticism Focusing on what is best for the community

> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences

There was a breaking change, and my issue was closed without comment to the real change yall induced. I love what this product enables, and I have been here supporting this platform longer than 90% of your team.

But yall have been dismissive of real issues I have posed, and seeing the trend over the last 2 years its concerning from a purely open source and collaborative perspective, which is what makes cyber threat intelligence great. You can only win a game of cat and mouse by being faster.

- There is a legitimate inconsistency between builds. 
- There are things that constantly break that require maintenance 
- There's a data structure issue that ya'll recently acknowledged, but only after  dismissed me for over half a year.

 I have a legitimate gripe here that you aren't prioritizing or even acknowledging sometimes. The legitimate needs of the platform from the open source community are starting to feel like an afterthought.

 I genuinely think there is an amazing platform here, and there's a lot to be done, and we're only scratching the surface at this point.

But to be quite honest, it really sucks that after all these years of collaborating with y'all, this is how you decide to handle this.

 Speaking to yall as a member of your community, we all can benefit from lessons learned; talking about actual problems that have, in fact, been going on, regardless of yalls acknowledgment

While I understand our differing views here, this definitely seemed like an undo reaction, and you promised there would be no further removal of features without advisory @SamuelHassine. In the effort of enlightening the community, please elaborate on the violation of your code of conduct here, as I am curious 


> Our Standards
Examples of behavior that contributes to creating a positive environment include:
Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members
Examples of unacceptable behavior by participants include:
The use of sexualized language or imagery and unwelcome sexual attention or advances
Trolling, insulting/derogatory comments, and personal or political attacks
Public or private harassment
Publishing others' private information, such as a physical or electronic address, without explicit permission
Other conduct which could reasonably be considered inappropriate in a professional

**Comment by SamuelHassine** [comment]
Hello @MaxwellDPS,

We are testing internally 5.12.25 to check if there is any change in the `Data > Relationships` screen (which seems not to be the case in 5.12.25) but I can also confirm that, even if it was the case, the purpose of this screen was to display only STIX Core Relationships and not sightings, available in `Events > Sightings`. Having this fixed and corresponding to the initial intention is therefore not something we noticed nor mentioned as a breaking change. As @Archidoit said, dashboard widgets should be used to mix all abstract types of relationship together in meaningful views.

That being said, our team is doing its best to fix instability related to major and very deep features we have delivered in 5.12.X all over the last weeks, being more than reactive and always transparent, introducing new automated test coverage and not leaving any critical bugs open more than 24 hours without minor release. We take all community and customers feedback very seriously internally, with associated action plans and priorities. 

About the form of your messages, I would like to insist on the @Archidoit's message above. We understand sometimes having some screens not behaving as expected after upgrade can be frustrating, but you have to avoid caps lock messages, direct mentions, references to commitments taken from one minor to another and apostrophize the our teams who work hard to deliver the best possible Open Source product.

This is also true that you have opened a lot of issues recently, and some of them were only related to deployment issues and platform health in general, which lead to huge confusion in our product teams to do proper triage of the tickets you open. We are always available on Slack to help you qualify before opening a bug, and I think it can be truly valuable if we can have an overall discussion to get things right within your environment. I know @richard-julien also proposed multiple times an on-site session to tackle any problem you may have.

Finally, it is maybe worth to remind that deploying more Filigran resources to support our communities and enhance our products is part of the Filigran DNA and that we continue to push very hard to be hyper-reactive for any organization having issues with the platform, whether it is a Filigran customer or not, but that this is made possible by organizations that know and appreciate the added value of our interventions and products. So it makes perfect sense to confirm here that this investment should be done in best effort.

Kind regards,
Samuel
