### ISSUE TITLE
Labels appear fairly broken in 5.12.29

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#6013]
## Description
Sorting Entities on labels is broken, and loading labels is painfully slow and crashes the brower stack

```
http://localhost:8080/dashboard/data/entities?filters={"mode":"and","filters":[{"id":"c1f93381-e619-4afd-a93f-ca39d316687c","key":"objectLabel","values":["39fa543d-7124-4867-8681-9b808c02f412"],"operator":"eq","mode":"or"}],"filterGroups":[]}&sortBy=created_at&orderAsc=false
```

```
self.helper.api.stix_cyber_observable.list(
            filters={
                "mode": 'or',
                "filters": [{
                        "key": "objectLabel", 
                        "values": _labels,
                        "mode": "or"
                }],
                "filterGroups": [],
            },
            getAll=True
        )
```

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 5.12.29
3. OpenCTI client: frontend
4. Other environment details: Cluster

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Visit URL above or filter on label via API
2. get nothing

## Expected Output

Objects that have the label

## Actual Output

Nada

## Additional information
Filters seem forked in 5.12.29

**Comment by MaxwellDPS** [comment]
```
INFO:pycti.entities:Listing Threat-Actors with filters null.
ERROR:pycti.api:{'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/places/in/cyber/space/site-packages/pycti/api/opencti_api_client.py", line 228, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
````

**Comment by MaxwellDPS** [comment]
I am assigning labels to Identities and they are disappearing in 5.12.29 @richard-julien FYSA

**Comment by nino-filigran** [comment]
@MaxwellDPS I can't reproduce your bug on demo. Do you have any other information to provide?

**Comment by MaxwellDPS** [comment]
We have a sync running atm, could try testing when syncing. As for labels, really not sure, memory seems to cap, but hard to tell as it legit crashes chrome

**Comment by nino-filigran** [comment]
Let me know when syncing is over and you when you'll be able to retry again. I also advise to upgrade to latest version in case. Please reach out if the problem persits, I keep this issue opened for now.

**Comment by richard-julien** [comment]
Close for inactivity
