### ISSUE TITLE
[Global Search] missing filter by 'value'

### ISSUE THREAD

**Issue by MalwareCantFly** [LuatixHQ/opencti#6032]
## Use case

Currently, you can filter by 'value' in the Observables screen, but not in the Global Search screen.

## Current Workaround

Go to Observables page to filter based on 'value'.

## Proposed Solution

Add filter by 'value' option in the Global Search screen.

## Additional Information

Current Observables filters:
<img width="221" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/33734448/b2299ce7-2ad3-4b20-adbd-a6535d5fc9fe">

Current Global Search filters:
<img width="221" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/33734448/a4869215-94e5-458d-aa5b-e683d913cde5">

Thanks!

**Comment by Archidoit** [comment]
This feature is developed in #4939

**Comment by Archidoit** [comment]
This feature is developed in #4939
