### ISSUE TITLE
Filter tooltip placement bug when creating a widget

### ISSUE THREAD

**Issue by CelineSebe** [LuatixHQ/opencti#6036]
## Description

The tooltips appear outside of the widget creation box (above or below).

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1- Go to a Dashboard > Create a widget 
2- Horizontal bar > Knowledge Bar
3- Add a filter
4- Click on filter to scroll through all options

## Actual Output

![Bug tooltip arrow](https://github.com/OpenCTI-Platform/opencti/assets/87119259/07a307ea-32db-4bf3-915e-2b8500944dad)

https://github.com/OpenCTI-Platform/opencti/assets/87119259/7fc19edf-1f02-42c8-8956-a9b593ca1085

**Comment by jpkha** [comment]
In my opinion, we cannot fix this bug with the current component we are using.
The structure in the DOM here makes it impossible to manipulate the z-index and overflow; the tooltip element is at the same level as the presentation.
![image](https://github.com/OpenCTI-Platform/opencti/assets/18297909/09ca4148-a023-4c2e-a59c-715f96a438cf)

**Comment by jpkha** [comment]
@nino-filigran @jborozco IMO, the behavior is acceptable. But if you want to fix this, we need to find another tooltip component.

**Comment by nino-filigran** [comment]
After a discussion with @jpkha the ROI to change component is quite low, since its used in lots of places (and therefore we would need to change lots of components before the release). For now, we'll test only the ability to reduce the time during which the tooltip is displayed. IF the test is unsuccessful, then we'll tackle this as proper feature (to update the tooltip component)

cc @Kedae

**Comment by CelineSebe** [comment]
I found a solution with the prop: followCursor on the tooltip component

**Comment by nino-filigran** [comment]
That's great new @CelineSebe ! Could you either show or record a video? And this does not affect other places in the app?

**Comment by CelineSebe** [comment]
https://github.com/OpenCTI-Platform/opencti/assets/87119259/f9c6bb7e-3d85-4b4e-a7ec-7fe1084045bd

**Comment by nino-filigran** [comment]
C'est royal :) merci beaucoup
