### ISSUE TITLE
Entity settings display edit default value input even if attribute has "editDefault" false

### ISSUE THREAD

**Issue by SouadHadjiat** [LuatixHQ/opencti#6037]
## Description

In Settings => customization => Entity types, when selecting an entity type that has an attribute with "mandatory: external" and "editDefault: false", you'll be able to edit the attribute and set a default value.

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: latest master (5.12.32)
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Issue visible locally only

## Expected Output

We shouldn't edit the default value if it's editDefault is set to false.

**Comment by nino-filigran** [comment]
Would potentially worth investigating if all attributes for all entities deserves a default value configurable, for instance, at the moment, indicator has "pattern" as default value configurable.

cc @Jipegien

**Comment by lndrtrbn** [comment]
Taking the initial issue described by Souad. I let the investigation for an other issue.
