### ISSUE TITLE
Filtering by "technical_creator" is not possible on some entities

### ISSUE THREAD

**Issue by rguignard** [LuatixHQ/opencti#6047]
## Description

On some entities, it's not possible to filter by the notion of "technical_creator".
This capability is notably not present on the following entities: Malware, Tools, Artifacts, Organizations...
This capability is usefull when you want to rapidly have a view of entities created by a specific connector/TAXII client.

## Environment

1. OpenCTI version: 5.12.32

**Comment by Archidoit** [comment]
This functionnality is developed in #4939
