### ISSUE TITLE
Default content not working for reports 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6059]
## Description

When setting a default content for reports, the content is empty (and the default value not taken into account).

## Environment

Internal 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in custotimzation
2. Go to report
3. PRovide a default value for content 
4. Click on update
5. Go to report
6. Create a new report 

## Expected Output

The default content is in the report.

## Actual Output

Content is empty

**Comment by Kedae** [comment]
Not a bug, you need to refresh the app in order to get the settings updated
