### ISSUE TITLE
Having Network Traffic observable with a dst ref makes the observable listing crash

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#6070]
## Description

Discovered while working on #6056 
If a Network Traffic observable has a `dst` ref set, the pagination request in the observable list crashes.
=> Update : the bug happens is a network traffic has "dst_port" and we try to sort the observable list by "representative".

## Environment

latest 5.12

## Reproducible Steps

1. create a network traffic observable
2. from its knowledge tab, add a dst ref
3. go to observables list and sort by observable value (dashboard/observations/observables?sortBy=observable_value&orderAsc=true)

## Expected Output

no crash :)

## Actual Output

crash :(

**Comment by labo-flg** [comment]
cc @SouadHadjiat I think you already made the root cause analysis for this one

**Comment by labo-flg** [comment]
"failures":[{"index":"opencti_stix_cyber_observables-000001","node":"Ze8cuEaJT9Gd0Z1ilSybPA","reason":{"caused_by":{"reason":"No field found for [dst_port.keyword] in mapping","type":"illegal_argument_exception"}

`dst_port` is a numeric, so using keyword is an error I guess

**Comment by SouadHadjiat** [comment]
Actually the bug happens only when we sort on "representative" and if we have at least one network traffic with "dst_port", it doesn't have any link to dst_ref
