### ISSUE TITLE
Relationships deleted from a Grouping knowledge graph are not actually deleted from the Grouping or the graph.

### ISSUE THREAD

**Issue by dld-at1** [LuatixHQ/opencti#6071]
## Description

If I try to delete a relationship from a Grouping knowledge graph, the graph will initially look as though the relationship has been removed; the graph will no longer show that relationship.  But if I browse away from the knowledge graph and then browse back, the relationship will once again be in the graph.  So using the graph interface to delete a relationship doesn't acutally delete it from the graph.

A work-around is to actually delete the relationship out of OpenCTI entirely.  This works fine for relationships that you don't want in OpenCTI anyway, like if you created something and later realize it is wrong.  But if you have a relationship in your knowledge graph that you want to remove from the graph but you **still want the relationship to exist in OpenCTI** you have to delete the relationship from OpenCTI and then re-create it and just not add it to your graph this time.  This is an error-prone, manual process which can result in loss of intelligence if the deleted relationship had additional data, like a description, that you failed to copy before deleteing it.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: OpenCTI 5.12.5
3. OpenCTI client: Web front end
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Grouping.
2. In the Knowledge graph tab, add observables to the Grouping.  I had IPv4 addresses and X509 certs.
3. Add relationships between the observables, for example an X509 cert "related-to" an IPv4 address.
4. In the graph, click the relationship you added and click the Delete button in the lower right corner of the graph interface.  The relationship will now appear to have been removed from the graph.
5. Click another tab within the Grouping, like the Content tab.
6. Click back to the Knowledge tab.  The relationship will now be in the graph once again.

## Expected Output

Clicking the Delete button in the graph interface should delete the relationship from the graph and from the Grouping, but leave the relationship to still exist within the OpenCTI platform.

## Actual Output

Clicking the Delete button will initially make it appear the relationship has been deleted from the graph, but browsing away from the graph and browsing back will reveal the relationship is still in the graph.

## Additional information

N/A

## Screenshots (optional)

N/A

**Comment by jborozco** [comment]
I can't reproduce on our demo environment. You may fix this bug by upgrading your version of OpenCTI.

**Comment by dld-at1** [comment]
We'll try this and report back.

**Comment by dld-at1** [comment]
We've verified that the most recent version has indeed corrected this.  Thanks!
