### ISSUE TITLE
Cannot export PDF on Report list

### ISSUE THREAD

**Issue by jpkha** [LuatixHQ/opencti#6072]
Environment:  testing

- Go to report
- Open export panel
- Try to export PDF
- And we can see we cannot export the list in PDF

![image](https://github.com/OpenCTI-Platform/opencti/assets/18297909/68e2b310-cc74-48b4-b8cb-5be35b54e46f)

**Comment by nino-filigran** [comment]
@jpkha seems to work fine in both testing and demo. I close the bug for now.
