### ISSUE TITLE
The way to handle external ref is inconsistent 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6074]
## Description
We had a [bug](https://github.com/OpenCTI-Platform/opencti/issues/5884) to fix the behavior of external references in reports.
As mentioned in [this ](https://github.com/OpenCTI-Platform/opencti/issues/5884#issuecomment-1957280799) comment of the same ticket, the behavior of enforcing reference is bigger. 

## Environment

Demo

## Reproducible Steps

Edit an entity while having external reference 
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference
3. Click on edit 
4. Click on the field external ref
5. You only see the external ref of the report, not the full list of external refs of your platform and cannot select existing ones already created that do not pertains to your entity.

Expected output: 
You should see the list of all the external refs to be able to add another one.

Sharing entity to an org
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference enforced
3. Click on share to org
4. select an org
5. You got an error message because you have not added any external ref 

Expected output: 
It would help if you were prompted the pop up to add an external ref instead of having an error message. 

Remove all external references while enforce external reference is enabled
1. Have external reference enforced for your entity 
2. Click on an entity (ex report) that have an external reference enforced and have some external ref
3. Remove all external ref

Expected output: 
You should not be able to remove all external ref. At least always 1 external ref must remains in the entity.

Adding relations (core ) is sometimes possible without having to add an external ref
1. Have external reference enforced for your entity 
2. Go to your entity and click on add relation 

Expected output: 
You should not be able to add a relation without adding an external ref. The pop up must be pormpted if not in the form.

**Comment by Kedae** [comment]
/!\ All this bug fix MUST be covered by e2e testing
