### ISSUE TITLE
TTP names are replaced by ID in some screens

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6109]
## Description

Attack patterns names are not shown properly and, instead, we get the ID.

## Environment

Testing

## Reproducible Steps

- In dashboards, go check the dashboard called "**TTPs issue 5969**"
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/4472c4bb-d9cd-4306-bbcb-833089b2bcc6)

- In MITRE Matrix: Go to an Intrusion Set's MITRE matrix (Intrusion Set -> Knowledge -> Attack Pattern)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/1fe70f19-a0a0-40a5-a0cf-b288795238f6)

## Expected Output

[T1003.008]/etc/passwd and /etc/shadow

## Actual Output

T1003

**Comment by SarahBocognano** [comment]
Update after meeting with @yassine-ouaamou : There is no problem with the display of the ID but we noticed that on testing the recorded future connector changed the names of TTP. Need to check this issue with the connector team

**Comment by SarahBocognano** [comment]
Update after meeting with connector team : The problem that occured with recorded future connector changing the names of TTP is now obsolete. It has been already taken care of and is stable on the production platform. I am closing this issue.
