### ISSUE TITLE
Matrices tactics order is not right

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6110]
## Description

Matrices columns (tactics) are not properly ordered.
It's the case for all the matrices.

## Environment
Testing

## Reproducible Steps

Go to an Intrusion Set Details -> Knowledge -> Attack patterns

## Expected Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/105ceaad-66ae-4916-8c9c-c9a905756a56)
## Actual Output

![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/3b943fec-ff7f-4952-afb4-a556b54f2e71)

## Additional information

The techniques labels issue that you might notice in the screenshot is adressed in another issue (https://github.com/OpenCTI-Platform/opencti/issues/6109)

**Comment by SarahBocognano** [comment]
After investigation, the order of the matrix columns are fine, we just need to define them in the "Taxonomie" section to configure the order of our choice.
