### ISSUE TITLE
Provide feedback on an entity is difficult when you have a big DB

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6113]
## Description

When trying to provide feedback and selecting the entity to provide feedback for trhough the user profile, feedback, if the DB is full with a lot of information, it is basically impossible to find the entity 
## Environment

Testing and demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on profile
2. select feedback
3. Click on entity
4. Start entering a word: the research will start to die 

## Expected Output

Ability to find my query
## Actual Output

The words are not added at the same rythm I type 
The research does not found my result and eventually close itself

In theory, if we keep the same beahvior, either we should be able to filter on the type of entity maybe or trigger the search manually or simply ensure that the search is sent X seconds after the users stops to add inputs?

## Screenshots (optional)

https://github.com/OpenCTI-Platform/opencti/assets/148041607/34ee25de-3164-46dc-8ab5-d10ded4a1c45

**Comment by SouadHadjiat** [comment]
We have a delay (1.5 seconds, which seems a bit long I think) on some inputs (CreatedBy, Assignees, Status), but not on this field used here for searching entities. Should we add this delay ? @nino-filigran 
I don't know if we shouldn't also check if there are other fields that don't have a delay.

**Comment by nino-filigran** [comment]
If the delay works then we could try it it, yes. We just need to ensure that when the searched is triggered, the app does not become so "buggy", and the delay seems to be a good solution to me.

**Comment by SamuelHassine** [comment]
We just need the "palette" for entity type scoping in the search field.

**Comment by SamuelHassine** [comment]
And also override the results instead of cumulating.
