### ISSUE TITLE
The ImportDocument connector doesn't work when importing document from a "Data" tab

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6121]
## Description

When I import a document into an entity (which is not a container!), a bug occurs. There seems to be a problem in creating a relationship (see the screenshot).

NB:
- I tested in the global import panel or in the Data tab of a container -> no bug
- I tested on Threat actor and Incident -> bug occurs

## Environment

OCTI 5.12.33

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an Incident
2. Navigate to the Data tab of the incident
3. Import a pdf and let the ImportDocument connector do its jobs
-> You will have an error

## Screenshots

![Screenshot 2024-02-26 161027](https://github.com/OpenCTI-Platform/opencti/assets/70956706/9a316503-26e2-49ea-aaba-8c8d8ac0b242)

**Comment by Jipegien** [comment]
Reproduced. And on testing.
https://testing.octi.staging.filigran.io/dashboard/threats/threat_actors_group/a443db74-a96a-4919-8e1a-ccd3b32b4362/files

**Comment by SouadHadjiat** [comment]
Fixed by https://github.com/OpenCTI-Platform/connectors/pull/1865
