### ISSUE TITLE
Allow merging more than 4 entities under Data > Entities

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#6129]
## Description

Allow merging more than 4 entities at once.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 5.12.18
3. OpenCTI client: frontend
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data > Entities
2. Select 5 or more entities
3. Try to merge them

## Expected Output

Allow merging the entities.

## Actual Output

Merge button is not enabled when more than 4 entities are selected.

## Additional information

N/A

## Screenshots (optional)

![imagen](https://github.com/OpenCTI-Platform/opencti/assets/1590496/52359874-7102-428e-8271-dc16d0f28a66)

**Comment by Jipegien** [comment]
The workaround is simple: do the merge in two actions. 
The max of 4 entities to merge is to prevent a merge action of too much entities (or with too many relations) that could break the platform.
I close the ticket (wontfix) but if you have a specific use case you cannot handle with the workaround, feel free to reopen it.

**Comment by febrezo** [comment]
Our use case is related to the ingestion of incidents or entities which are similar but by mistake or misunderstanding where uploaded separatedly. For example, think about a set of hundreds of incidents/alerts reported with similar (but not exact linked data). We only fixed this using an explicit automation to somewhat do the same: automerge and rebuild the relationships,
