### ISSUE TITLE
Top bar elements clump if the screen has not appropriate width

### ISSUE THREAD

**Issue by febrezo** [LuatixHQ/opencti#6134]
## Description

Icons collapse drastically when the screen width is reduced.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 5.12.18
3. OpenCTI client: Frontend
4. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Reduce the screen size

## Expected Output

A prettier way of making elements collapse. Not sure about how, sorry. As a suggestion, maybe a new Menu button where all the options are released with a mouse over event. But not sure.

## Actual Output

Elements in the top bar clumping...

## Additional information

N/A

## Screenshots (optional)

![imagen](https://github.com/OpenCTI-Platform/opencti/assets/1590496/c76efc02-4c24-4299-ab65-b3bd6c5aee5c)

**Comment by Kedae** [comment]
Hello @febrezo ,

We have minimal required width and height for the app (1400px width if my memory is correct)
Below that we do not maintain a consistent screen appearance.

**Comment by SamuelHassine** [comment]
Hello,

And this is solved in 6.0.0.

Kind regards,
Samuel
