### ISSUE TITLE
AbuseIPDB Connector : This update will produce a duplicate

### ISSUE THREAD

**Issue by mayank-joshi-01** [LuatixHQ/opencti#6140]
## Prerequisites

- [ ✔️ ] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [ ✔️ ] I went through old GitHub issues and couldn't find anything relevant
- [ ✔️ ] I googled the issue and didn't find anything relevant

## Description
I used dockercompose of AbuseIPDB from the connectors repo of opencti, I have configured everything correctly but now I am getting the follwing error.

`
{"category":"APP","errors":[{"attributes":{"existingIds":["b06cc4af-51fd-49c6-91fa-4aa2e1352ec3"],"genre":"BUSINESS","http_status":400,"id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","type":"User"},"message":"This update will produce a duplicate","name":"FUNCTIONAL_ERROR","stack":"FUNCTIONAL_ERROR: This update will produce a duplicate\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:89:50)\n    at updateAttributeMetaResolved (/opt/opencti/build/src/database/middleware.js:1816:13)\n    at initAdmin (/opt/opencti/build/src/domain/user.js:1434:5)\n    at initializeAdminUser (/opt/opencti/build/src/config/providers.js:38:5)\n    at platformInit (/opt/opencti/build/src/initialization.js:105:7)\n    at platformStart (/opt/opencti/build/src/boot.js:17:5)"}],"level":"error","message":"This update will produce a duplicate","timestamp":"2024-02-27T12:27:36.221Z","version":"5.12.33"}
`

## Environment

1. OS : Ubuntu 22.04
2. OpenCTI version: 5.12.33
3. OpenCTI client: 5.12.33
4. Abuse IPDB Connector: 5.12.33

**Comment by nino-filigran** [comment]
@Megafredo or @helene-nguyen do you maybe have an idea?

**Comment by helene-nguyen** [comment]
@nino-filigran, I'll take a look

@git-SwitchBlade, could you provide some details about your connector configurations ? And could you confirm to us that it is the enrichment connector and not the feed one ?

**Comment by mayank-joshi-01** [comment]
@helene-nguyen, Thanks for responding
It was an external connector of version 6.0.0 that I picked from opencti [github](https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/abuseipdb-ipblacklist/docker-compose.yml). 

I am using docker compose configuration of opencti and also for connector.

**Comment by helene-nguyen** [comment]
Thanks, this error is raised in 2 different situations:
- when checking if there is an update on an alias lead to entity conflict
- when checking if the update is not resulting to an entity merging

Both cases, it is to warn you about the duplication on update when importing data with AbuseIPDB-Ipblacklist connector and if the entity already exists, it will check in which case you are.

So, I have few more questions for you: 
- Does it stop importing data ? Or the data is well created and you have a duplicate entity?
- Could you give us some steps to reproduce the issue as it is working fine by my side ?

**Comment by mayank-joshi-01** [comment]
I am closing this issue because my opencti has stopped working, I made a new issue for it
