### ISSUE TITLE
[Dashboard] Date displayed in a timeline view is inconsistent with the configuration

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6145]
## Description

The date displayed in a timeline view is inconsistent with the configuration. The date displayed is the date of creation, regardless of the date set.

NB: sorting is done on the date set, the problem is only on the display.

Maybe it's not a bug, but something we don’t handle. I let you decide.

## Environment

OCTI 5.12.33

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create widget with timeline view -> perspective
2. Filters: 

![Screenshot 2024-02-27 171529](https://github.com/OpenCTI-Platform/opencti/assets/70956706/65ad1202-277e-4fe5-b240-7e74b4d5365f)

3. Parameters:

![Screenshot 2024-02-27 171836](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b4f53811-1773-486e-88ae-83896e13c3a3)

4. Create a relation between a campaign and a threat actor matching the filters and with a "start time" set
5. Look in the widget

## Screenshots

![Screenshot 2024-02-27 171542](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b8e84eb6-b84c-4db5-81a3-d15c4f973cff)

![Screenshot 2024-02-27 170507](https://github.com/OpenCTI-Platform/opencti/assets/70956706/85b1a66c-b30d-4752-8f11-0524916e9022)

**Comment by marieflorescontact** [comment]
we're currently doing a lot of refactoring work on widgets, so we'll wait until it's merged before fixing it. @Jipegien
