### ISSUE TITLE
Connector menu is not visible (6.0.0)

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#6166]
I used to be able to see it in the "Data" menu, but in the latest version (6.0.0) I don't see it.

Where can I find that menu?

**(Before)**
![22](https://github.com/OpenCTI-Platform/opencti/assets/19428462/a20dad81-cb53-40a9-b3e8-17aadec53b43)

**(After)**
![11](https://github.com/OpenCTI-Platform/opencti/assets/19428462/85ca9c98-db06-4124-8e01-8c797b14f9fb)

**Comment by ckane** [comment]
It's now under the **Ingestion** section there. Click on Ingestion and then the following will be the choices on the right-hand side of the page:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3454769/bb9656d8-93c9-4a52-bec8-c9cb5a409587)

Caused me a bit of confusion too before I found it
