### ISSUE TITLE
Ability to add indicator generated from the observables of a container in the container

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6171]
## Use case

Currently, in the context of a container, when creating an indicator from an observable, the indicator is not included in the report. We should be able to automatically add it to the report at its creation?

**Comment by Lhorus6** [comment]
NB: The opposite must also be taken into account (observables generated from indicators in a container).

**Comment by nino-filigran** [comment]
This will create a potential breaking change: to be communicated in the release notes.

**Comment by Jipegien** [comment]
Breaking change must be avoid if possible and not shipped in minor, in any case.
