### ISSUE TITLE
Viewing entities not possible (infinite query loop)

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6176]
## Description
When trying to access an organization through the ui, the spinner is shown infinitely. When looking at the network traffic in the browser it can be seen that the requests to the graphql endpoint are infinitely repeated

EDIT: While testing further the problem occurs with multiple entities like individuals, intrusion sets,...
**But strangely some intrusion sets are working normal other have the infinite loop problem**

## Environment

1. OS (where OpenCTI server runs): debian
2. OpenCTI version: 6.0.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to organizations
2. Click on any organization
3. Infinite loading

## Expected Output
The organization

## Actual Output
Spinner

**Comment by ghost** [comment]
When refreshing the site with disabled cache the page loads normal, when going back to the overview and clicking on another entity the problem occurs again.

**Comment by iFrozenPhoenix** [comment]
ok, fixed with 6.0.1

**Comment by ghost** [comment]
ok, fixed with 6.0.1
