### ISSUE TITLE
Select ALL now affect to all Data instead of a Page

### ISSUE THREAD

**Issue by lhviet** [LuatixHQ/opencti#6188]
## Description

The "Select All" checkbox is selecting entities not in the filtered view leading to erroneous modification. In our instance of modifying 35 observables, we noticed that 11.05m observables were being edited by selecting all entities in a container.

* If someone uses the select all and modifies data, its affecting everything in the TIP

![image](https://github.com/OpenCTI-Platform/opencti/assets/5140297/fb06b302-da67-4bbe-938c-89d7885d14cf)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

## Expected Output

No breaking change in UI/UX. We should have another button for Select All Data.

**Comment by labo-flg** [comment]
For the record, it appears that this bug happens on observables view, including the observables tab in containers such as reports.
