### ISSUE TITLE
Some sectors unavailable in 'Add subsector' list, and no search function

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#6190]
I have a government-type sector that is not currently a subsector of Government and administrations, when I try to add it as a subsector, it does not appear on the list. I can't search for it, and I only have an option to create a new sector on 5.12.32:

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/a09ee263-5f29-422f-9861-cc1d46813480)

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/cd5ab47d-0394-4f1e-ac8c-7cee711c5ade)

**Comment by Jipegien** [comment]
Seems fixed with 6.0. Are you able to upgrade your instance to the last version?  (wait for the 6.0.2 though, some important fixes in it) Feel free to reopen the bug if you are still stuck with this.
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/c94d4a29-c895-4b89-9edd-db6be40b3a78)

**Comment by dominictory** [comment]
> Seems fixed with 6.0. Are you able to upgrade your instance to the last version? (wait for the 6.0.2 though, some important fixes in it) Feel free to reopen the bug if you are still stuck with this. ![image](https://private-user-images.githubusercontent.com/104078945/309195067-c94d4a29-c895-4b89-9edd-db6be40b3a78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODM1MDksIm5iZiI6MTcwOTI4MzIwOSwicGF0aCI6Ii8xMDQwNzg5NDUvMzA5MTk1MDY3LWM5NGQ0YTI5LWM4OTUtNGI4OS05ZWRkLWRiNmJlNDBiM2E3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwODUzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDEzNWNkOTNhNWUyNWRiMTE1NTBiN2ViZTkwYzBmOTA3NjFmZTU0M2QyY2JmMDg1ZDBiYzdmZTk2MDYxMjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5BQFOd07qEKlVf78pAfV4LYvwucU7jvZrii5wcqC2Zw)

Thanks, am planning to go to 6.0, just have some work to do first. Will update once there and if fixed
