### ISSUE TITLE
Problems with MISP connector

### ISSUE THREAD

**Issue by mahmut-the-guy** [LuatixHQ/opencti#6193]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

1. I had a MISP connector running for a week, it ended up accumulating 35
   million messages, workers acknowledging almost none, with bundles per second
   nearing zero at all times.

   Yesterday, I purged all messages and reset the connector state. Initially,
   some entities started to be ingested but buildup occurred eventually, now
   sitting at 4m bundles. MISP connector especially seems to be problematic when
   running from scratch.

   For reference, I'm running 4 workers with one platform node. Throwing more
   workers does not seem to help at all in general. (which is odd, interested to
   know the why)

<img width="1563" alt="Screenshot 2024-03-01 at 11 35 45" src="https://github.com/OpenCTI-Platform/opencti/assets/158579334/77bf10cd-5de1-42bb-93f7-60d9dbddd504">

2. In another instance, the platform also suffers from slow ingestion and the
   following error is repeatedly reported via frontend:

    ```json
    {"name": "MISSING_REFERENCE_ERROR", "message": "Element(s) not found"}
    ```

   What does this error mean specifically? How could we fill in these
   *missing references*?

![image](https://github.com/OpenCTI-Platform/opencti/assets/158579334/9906523e-6697-47e4-bc42-00c3126a1d2d)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.2 LTS on Docker Compose
2. OpenCTI version: { e.g. OpenCTI 5.12.24 }

## Reproducible Steps

I believe using the Docker configuration provided by OpenCTI, and enabling MISP connector
will eventually result in this problem i.e., slow and (eventually stalling) data entry.

**Comment by nino-filigran** [comment]
@mahmut-the-guy thanks for your request. I'm not sure to understand what's the question here and what you exactly would expect from Filigran?

**Comment by nino-filigran** [comment]
@mahmut-the-guy given I did not have any answer, I'm closing this ticket. Feel free to re-open it if you want or if you have any other question.
