### ISSUE TITLE
Button askAI in plain text field and HTML field is not well positionned

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6210]
## Use case

Button should be top right and not middle:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/be1d5822-5768-42f4-9d9e-9cd4be55dd92)

Button is in the middle of nowhere:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/1bebaadf-3865-4d04-835a-e2b43218e00c)

**Comment by shawrupesh** [comment]
@SamuelHassine Can I work on this issue?
