### ISSUE TITLE
Merging files must move existing files in S3 and rewrite path in x_opencti_files

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#6258]
## Description

When entities are merged, x_opencti_files are accumulated directly in the target.
However as the x_opencti_files are stored in a path that contains the internal_id of the element, this merging doesnt do the right operations.
Merging process must be improved to:
- Move the files in the S3/Minio to the target entity
- Rewrite the x_opencti_files sources to comply to the new path

### Hints
Metadata of the file in s3 can be discarded are no longer used.

**Comment by jborozco** [comment]
@richard-julien I could not reproduce by uploading a file in an entity and merging the entity with another one. 

Could you detail the steps to reproduce and the expected output?

**Comment by SamuelHassine** [comment]
Hello,

This bug is confirmed, clear the the file is not moved to the new entity.
