### ISSUE TITLE
Mutation icon not always well displayed in Activity

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6261]
Go to Settings > Activity > Events to see the list of activity events.
The icon of some events of type 'mutation' are displayed as '?' :
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/353912af-0db6-4412-804a-9b984c3600f3)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e46bc3be-1eb1-4164-ae52-e79bac31f038)

**Comment by CelineSebe** [comment]
I found a solution by adding the types of missing icons. For example, 'Task-template' didn't exist, which is the origin of the bug in my case. I need the types displayed in the screenshot to resolve all the problems.

**Comment by Archidoit** [comment]
@CelineSebe  maybe you can also add a 'default' icon in case no types is indicated to prevent this bad display for special/missing/future-added types

**Comment by CelineSebe** [comment]
> @CelineSebe maybe you can also add a 'default' icon in case no types is indicated to prevent this bad display for special/missing/future-added types

Yes, you're right. There is already a default icon, HelpOutlined, which has been chosen in case no entity_type or event_scope are indicated. I will discuss this further with JP.
