### ISSUE TITLE
Bulk deletion with the "select all" button deletes entities it shouldn't

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6268]
## Description

When I delete entities in a report using the "select all" button, an unexpected behavior occurs: the selected entities are not deleted, but others are.

## Environment

OCTI 6.0.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Go to the "entities" tab
3. Add a country to it
4. Add incidents
5. Filter on the left to see only incidents
6. Select all 
7. Delete entities
-> Incidents are not deleted, but countries are.

**Comment by Lhorus6** [comment]
It seems that the filter set on the right-hand banner is not taken into account when selecting all, because if you have a City, an Indicator and an Intrusion set and you filter on one of the three to delete it, it deletes everything.

A strange thing is that if you have Incidents, these are never deleted.

**Comment by Archidoit** [comment]
Other bug : in the right bar of Indicators, we can't select more than 1 pattern type or more than 1 observable type
