### ISSUE TITLE
I can't create indicators within a report at once.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#6274]
OpenCTI version: 6.0.4

Clicking on each object individually activates the button to create an indicator,
![11](https://github.com/OpenCTI-Platform/opencti/assets/19428462/6ed85ccc-0d83-4e8b-a48d-17de5067ade5)

If I hold down the "Shift" button and select the objects at once, the button to create an indicator is not activated.
![22](https://github.com/OpenCTI-Platform/opencti/assets/19428462/ab843cee-10e5-4fc7-b46e-017438f64c53)

It is too inconvenient to select many observable objects one by one.

I think it's a bug, but please confirm.

**Comment by Lhorus6** [comment]
May be linked to : https://github.com/OpenCTI-Platform/opencti/issues/6170
