### ISSUE TITLE
Duplicate CSV feed ingesters and mappers

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#6279]
## Use case

Duplicate a CSV feed ingester and mapper for similar feeds so can easily adapt.

## Current Workaround

Create another CSV feed ingester and mapper with different config

## Proposed Solution

Add duplicate option for CSV feed ingester and mapper

**Comment by nino-filigran** [comment]
Closed since done with the https://github.com/OpenCTI-Platform/opencti/issues/7400
