### ISSUE TITLE
Missing "System" objects when trying to update incident author

### ISSUE THREAD

**Issue by HugoCESI** [LuatixHQ/opencti#6282]
## Description

From https://opencti:8080/dashboard/events/incidents, if I try to modify incidents to change the author, they are missing datas : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/33095849/eccec59f-d9d5-417e-9c89-e43e5b1f0b5c)

It should be like in https://opencti:8080/dashboard/events/incidents/[indicent-id] : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/33095849/fdb0e6e5-ebc6-49bf-a4b3-f7c74e76fd0e)

If we are looking to the graphql requests, we can see there is a missing a type value "System" : 
Currently : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/33095849/09eec9c2-25f1-45e7-a0d0-5b14c17dc61f)

Should be : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/33095849/0f2b9a2a-6312-4543-8921-61f1fe45de31)

Edit : it's the same issue with Individals
## Environment

1. OS: Debian (Docker version)
2. OpenCTI version: 6.0.0
3. OpenCTI client: frontend

**Comment by jborozco** [comment]
Can't reproduce on demo environment 
![Capture d'écran 2024-03-07 105316](https://github.com/OpenCTI-Platform/opencti/assets/35300800/98504d1e-6038-49fa-b720-5e6985216f1b)


could you try to update to the latest version of the platform and retry ?

**Comment by Archidoit** [comment]
I have been able to reproduce the issue @jborozco . Individuals and organizations appear in the list, but not systems.

**Comment by HugoCESI** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/33095849/e40e2c40-a7e7-4613-8cab-66e1193ff1e7)
We can see it's missing in the code
