### ISSUE TITLE
Mass selection with the shift key does not work on Incident

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6283]
## Description

On the platform, it is possible to select a set of entities by selecting a first one -> scrolling -> selecting a second one by holding down the shift key -> all entities between the first and second are selected.

However, this mechanism doesn't work with Incidents entities

## Environment

OCTI 6.0.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to Incident
2. In the list, select an Incident (i.e. check the box at the beginning of the line)
3. scroll a bit
4. Maintain shift and check the box of another report
-> only the second incident is selected, not all in between

## Expected Output

Do the repro case on Reports to understand what is expected

**Comment by jborozco** [comment]
This bug might be related to this issue https://github.com/OpenCTI-Platform/opencti/issues/6274

**Comment by Lhorus6** [comment]
I don't think so. However, the issue 6274 may be linked to : https://github.com/OpenCTI-Platform/opencti/issues/6170
