### ISSUE TITLE
 Mass selection with the shift key crash in "Data > Entities"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6284]
## Description

On the platform, it is possible to select a set of entities by selecting a first one -> scrolling -> selecting a second one by holding down the shift key -> all entities between the first and second are selected.

However, this mechanism crash in the panel Data > Entities 

## Environment

OCTI 6.0.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data > Entities
2. In the list, select an object (i.e. check the box at the beginning of the line)
3. scroll a bit
4. Maintain shift and check the box of another entity
-> error occur

NB: The bug only occurs if only one type of entity is selected. If you select a vulnerability first and then a report, for example, the feature works.

**Comment by SarahBocognano** [comment]
Maybe we could we join those two bugs together ? As it's a multiple selection with shift problem for both: https://github.com/OpenCTI-Platform/opencti/issues/6274

**Comment by Lhorus6** [comment]
The issue 6274 isn't linked to the shift IMO

**Comment by JeremyCloarec** [comment]
I wasn't able to reproduce the bug. Does it only occur when a large amount of data is select? I was able to select ~1500 entities by shift selecting without a crash

**Comment by Lhorus6** [comment]
Indeed, this problem is no longer present. We can close the issue
