### ISSUE TITLE
[CSV Mapper] External reference creation

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6287]
## Description

When importing a CSV containing external references, they are not created

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the following mapper:
- Check "My CSV contains headers"
- Indicator (name: A, pattern_type: Default to **stix**, pattern: A main_observable_type: Default IP address)
- External reference: (source name: C)
- Link the external reference to the indicator
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/b43fd118-873c-4846-9f41-3825684effa5)
3. Import the attached CSV using the created mapper

## Expected Output

Correctly imported indicators with embedded external references

## Actual Output

No external references inside the created indicators

## Additional information

[feed_1_mini.csv](https://github.com/OpenCTI-Platform/opencti/files/14525497/feed_1_mini.csv)

The reason behind this is that the URL is mandatory (at least in the creation form) while it's shown as not mandatory in the CSV mapper. When I map a column containing the url to the the attribute, it works fine.
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/4b5c8ee2-d213-4890-86ba-cce046839c83)

**Comment by yassine-ouaamou** [comment]
A mapper called "issue_6287_ext_ref" has been created in Testing and can be used to illustrate the bug.

@Jipegien Should the URL be mandatory in an external reference? I would say no as we can have inputs where the source is just "BreachForums" for example

**Comment by shadyrat** [comment]
@yassine-ouaamou OpenCTI appears to have implemented the UI shown to match STIX 2.1 where the only required field is source name.  Url is explicitly optional.  See section 2.5 here: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_72bcfr3t79jx .

I didn't dig into the code.  I'm just someone evaluating it right now and happen to know STIX pretty well.
