### ISSUE TITLE
Creation of created-by relatiohship is not protected to target only identity

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#6291]
## Description
Creation of created-by relationship is not protected to target only identity.
At creation it will not fail but then the read will fail.

### Steps
1. Get a user id from the platform
2. Create a malware + read
```
mutation createMalware {
  malwareAdd(input: {
    name: "new_malware",
    createdBy: "dc5f1601-e4ff-4d17-9233-ec80ceef207d"
  }) {
    id
    createdBy {
      id
    }
  }
}
```

### Result
Create ok but return read fail.
`"message": "Runtime Object type \"User\" is not a possible type for \"Identity\".",`

### Expected
The creation must fail has USER is not a correct target for createdBy.

**Comment by Jipegien** [comment]
@aHenryJard is the mentionned PR resolving this bug critical? If so, can you link the PR to the issue in the "Development" section? Thank you ! :)
