### ISSUE TITLE
Can't search in Taxonomies > Kill chain phases

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6308]
## Description

Search doesn't work in Kill chain phases customization page

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings > Taxonomies > Kill chain phases
2. Search "collection"

## Expected Output

Attack patterns containg the word "collection"

## Actual Output

No result

**Comment by nino-filigran** [comment]
@yassine-ouaamou I can't reproduce. Have I done something wrong?
Here footage of Demo env: 

https://github.com/OpenCTI-Platform/opencti/assets/148041607/617683aa-b8d2-4787-aef0-619ebc54f9d9

Here footage of Testing 

https://github.com/OpenCTI-Platform/opencti/assets/148041607/481c2bfb-1b3b-4de0-a497-c86c0a17044c

**Comment by nino-filigran** [comment]
Can reproduce, the search is basically broken.

**Comment by nino-filigran** [comment]
We have a similar bug, where we the search on marking definition is broken too: https://github.com/OpenCTI-Platform/opencti/issues/6318
