### ISSUE TITLE
[Playbook] Error when applying label on some types of observables

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6311]
## Description

The goal of this playbook is to apply a label on the observables of reports having that label.
The steps of the playbook are:

1. Listening to reports having a label "217"
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/0e2ecfa3-fb31-4bb4-8353-9b7bed7301ce)
2. Extracting the contained entities of the report
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/f09a35d3-a6bd-4d40-8283-44d61855c8b5)
3. Filtering observables
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/bcc5d889-aa73-4125-8df4-8b005e36592b)
4. Adding the label "217"
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/1cd6d907-095f-4949-abfd-1b3ceba26d26)
5. Send to ingestion

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new empty report with the label "217"
2. Add an Artefact (make sure you are adding one that doesn't have previously the label "217")
3. It works!
4. Add a URL (make sure you are adding one that doesn't have previously the label "217")
5. Error in the playbook

## Expected Output

The label is added to the URL

## Actual Output

No label added + error at the level of "Manipulate knowledge":
`{
  "message": "Cannot set properties of undefined (setting 'labels')",
  "stack": "TypeError: Cannot set properties of undefined (setting 'labels')\n    at Object.add (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:14:16)\n    at applyOperation (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:235:60)\n    at Object.applyPatch (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:280:22)\n    at Object.executor (/opt/opencti/build/src/modules/playbook/playbook-components.ts:573:17)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:135:44)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:202:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:202:9)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:202:9)\n    at playbookStreamHandler (/opt/opencti/build/src/manager/playbookManager.ts:268:13)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:600:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:654:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:671:13)",
  "name": "TypeError"
}`

## Additional information

There is another bug that I showed in the end of video below: When an error happens in a playbook, the whole content (steps, logs and icons) of the previous executions is replaced by the last one. This is why you can see the 4th step of the previous execution change into red.
Seen with @nino-filigran. I can create a new issue for this bug.

## Screenshots (optional)
![playbook_inherit_label](https://github.com/OpenCTI-Platform/opencti/assets/7083405/8c850cb8-c1f3-4ef8-8b5e-4a4207d5c590)

**Comment by lndrtrbn** [comment]
I can reproduce in testing but it is hard to debug because it works locally.

And from my tests on testing, it is not related to observable types because I have also the issue for Artifacts

EDIT:

My take is that there is an issue with the function `computeAttributePath` in `playbook-components.ts` but without the possibility to debug I can't figure it out for now
