### ISSUE TITLE
Unauthorized access to Data > Processing

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6312]
## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a role with the following capabilities:
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/4066ac72-ad69-492d-b24e-d21ce7dc5579)
2. Create a group and give it the previously created role
3. Update or create a user with the previously created group
4. Log in with the user
5. Go to Data > Processing

## Expected Output

? (probably we should not see "Processing" in the menu

## Actual Output

Unauthorized! Redirected to the login page

## Additional information
Other related issues:
- Error when accessing Data > Entities. The result of the GraphQL call includes the following error:
`{
            "message": "Invalid loading of batched element",
            "name": "UNSUPPORTED_ERROR",
            "time_thrown": "2024-03-11T19:48:38.828Z",
            "data": {
                "http_status": 500,
                "genre": "BUSINESS",
                "id": "bf567425-223f-49d6-8462-85a84f3e0963"
            }
        },`
- When accessing Data > Import, the links of the enabled Import connectors should be Idle. They are active and we are redirected to the login screen when clicked.

Sorry for adding these two related issues to the main one. I can create new ones if needed

**Comment by nino-filigran** [comment]
@yassine-ouaamou I'm confused: if your user has the right "manage CSV mappers", then it's normal that the users sees processing. 

What's not normal however is that the user does not have access to processing (and therefore CSV mapper) since the user should be able to modify it.

**Comment by yassine-ouaamou** [comment]
> @yassine-ouaamou I'm confused: if your user has the right "manage CSV mappers", then it's normal that the users sees processing.
> 
> What's not normal however is that the user does not have access to processing (and therefore CSV mapper) since the user should be able to modify it.

Indeed, the user has the right to the CSV mappers page (if accessed directly through the link). The issue is that when we click on Processing, we are directed to Automation which they don't have access to.

**Comment by nino-filigran** [comment]
@SouadHadjiat could these bugs also be linked? Basically the user sees some items in the left navigation menu that should not be visible given to its rights.
https://github.com/OpenCTI-Platform/opencti/issues/6328
https://github.com/OpenCTI-Platform/opencti/issues/6329
