### ISSUE TITLE
When upserting an entity, name should also change

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6315]
## Description

1. Create an entity named "A" confidence = 75
2. Add alias "B" to entity A
3. Try to create the entity named "B" confidence = 75

Current result: Nothing
Expected result: Entity A is now named B and A is put in alias of B

This was the previous behavior and it is critical for data health.

- [ ] Bug fixed
- [ ] Integration test coded

**Comment by jpkha** [comment]
@SamuelHassine The issue come from this code :
https://github.com/OpenCTI-Platform/opencti/blob/beaac8fe6952d9517783a19eb3487e6930c61f05/opencti-platform/opencti-graphql/src/database/middleware.js#L1387C1-L1395C3

It was added by this commit : 
https://github.com/OpenCTI-Platform/opencti/commit/8733303c2763a9ad3ae66d694a3e54fe8d987a08

What would you like to do ?
@SamuelHassine @richard-julien
