### ISSUE TITLE
Marking Definition Search Broken

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#6318]
## Description

Marking Definitions search doesn't return results on TYPE or DEFINITION fields.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: 6.0.5
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to settings/accesses/marking?sortBy=definition&orderAsc=true&searchTerm=
2. Enter TYPE or DEFINITION in the search box

## Expected Output

Results are filter based on search criteria 

## Actual Output

No results are returned

## Additional information

None

## Screenshots (optional)

![Screenshot at 2024-03-12 09-14-38](https://github.com/OpenCTI-Platform/opencti/assets/141024547/2431760d-8481-45cd-a48e-4d7625d72314)

**Comment by nino-filigran** [comment]
Search is broken on this page, I have reproduced the bug.
