### ISSUE TITLE
Some connectors will pause based on queues threshold

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#6325]
## Use case

As a platform admin, I sometimes need to stop connectors to relieve the worker queue. Currently, I am only able to do it by shutting down the entire docker of the connector, that is very cumbersome and cause multiple occasions to make mistakes.

**Comment by jborozco** [comment]
This feature can include this issue https://github.com/OpenCTI-Platform/opencti/issues/6558

**Comment by richard-julien** [comment]
See https://github.com/OpenCTI-Platform/opencti/issues/1161

**Comment by jborozco** [comment]
Will also include https://github.com/OpenCTI-Platform/opencti/issues/7312
