### ISSUE TITLE
Batch Update Observables Available Types Mismatch

### ISSUE THREAD

**Issue by x86NOP** [LuatixHQ/opencti#6326]
## Description

When creating/updating an observable individually, the UI allows setting field `Author` to a user, individual, organization, or system.  However when multi-selecting observables from a list and selecting the `Update` button to do a batch update, only a user, individual, or organization can be set.  A list of systems is not visible in the batch update UI dropdown.

## Environment

1. OS: Docker compose stack on Ubuntu 22.04
2. OpenCTI version: 6.0.5
3. OpenCTI client: Chrome browser
4. Other environment details: New installation, never upgraded from previous version.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create or update an observable individually.  Note that `Author` can be a user, individual, organization, or system.
2. Select two or more observables in a list and click the small `Update` button to "update entities".
3. Select `Action type` of `Replace`
4. Select `Field` of `Author`
5. Note the list of available values _does not_ contain "systems" as expected.

## Expected Output

I would expect UI consistency so that values available to be set on an observable individually exactly match the values available to be set in a batch operation.

## Actual Output

The list of possible values in the batch operation excludes "systems".

## Additional information

![image](https://github.com/OpenCTI-Platform/opencti/assets/135667356/29c899a3-3122-442d-9309-f84bba32b16e)

![image](https://github.com/OpenCTI-Platform/opencti/assets/135667356/3767444c-1e11-4d5d-8ba2-d4e37521e2a9)

![image](https://github.com/OpenCTI-Platform/opencti/assets/135667356/25f3041b-7ede-48ce-9aa1-6043aa6d86e1)

**Comment by nino-filigran** [comment]
Have been able to reproduce: indeed, systems are not found in mass update.

**Comment by Archidoit** [comment]
already resolved in #6282

**Comment by Archidoit** [comment]
Note that only the 10 first author found are displayed in the list:
to find a system, you should write the beginning of its name in the search bar
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/00d2d467-dce2-476d-abd9-efd65dc2ec53)

**Comment by Archidoit** [comment]
@nino-filigran maybe we can update the number of author displayed in the list to 100 (instead of the actual 10) ?

**Comment by nino-filigran** [comment]
Yes, it works for me @Archidoit !

**Comment by x86NOP** [comment]
Impressed by the quick action and detailed responses.  Thanks!
