### ISSUE TITLE
Capabilities settings do not work correctly with the Connectors section

### ISSUE THREAD

**Issue by rattat0r** [LuatixHQ/opencti#6329]
## Description

The user has the "Access connectors" right enabled, but the "Access administration" right is disabled. 
In this case, he cannot get to the "data/ingestion/connectors" section from the sidebar, since the "ingestion" section is not displayed without the "Access administration" right. 
Direct access via the link http://[ip]:8080/dashboard/data/ingestion/connectors gives access to the section with connectors, but it is impossible to get there from the sidebar.

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: OpenCTI 6.0.4
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable the "Access connectors" right and disable the "Access administration" right for the user.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/b8deca92-990e-4a58-87fe-f98f7ce62075)
2. The "Ingestion" section has disappeared from the sidebar. It is impossible to go to the connectors section through the side panel.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/28e6c890-79fe-462c-976d-8ebd18aad595)
3. Direct link access works.
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/1d549c52-992b-468f-9763-28452274690f)

## Expected Output

A section with connectors is available in the sidebar if the "Access connectors" right is enabled.

Is it possible to hide inaccessible sections directly in this area?
![image](https://github.com/OpenCTI-Platform/opencti/assets/122795003/ddbd8347-9bb9-45b0-be46-b8149296170c)

## Actual Output

When the "Access administration" right is disabled, the "Data/Ingestion" section, in which the section with connectors was located, disappears.

**Comment by SouadHadjiat** [comment]
solved with https://github.com/OpenCTI-Platform/opencti/pull/6340
