### ISSUE TITLE
Bulk delete OPs are horrible slow compared to ingestion

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6342]
## Description
Deleting 77k entities takes about 4h for me while ingesting these entities only took about 30 Minutes.
Somehow these bulk delete ops seem not be very efficient.

## Environment

1. OS (where OpenCTI server runs): debian
2. OpenCTI version: 6.0.5
3. OpenCTI client: web
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to entities
2. Filter the entities u want to delete
3. Select all of them
4. Press delete
5. Go to the tasks page and wonder how long it takes

## Expected Output
A much faster deletion process.

## Actual Output
A very slow deletion process

## Additional information
The entities I'm referring to are software observables created with the cpe connector. there were no relations to any other entity (e.g. vulnerability).

**Comment by Jipegien** [comment]
Deletion is longer than creation because impact analysis is performed for every Object deleted. When an object is deleted, we must find if it has any relationships (that will be deleted too). We made some improvement already on this and we will continue to do so.
