### ISSUE TITLE
Files search EE button not aligned

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6346]
in Search > Advanced Search: the EE icon next to 'Files search' is not aligned (too low)
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/7049fc0f-b5fe-4df1-9855-adf162f9f895)

**Comment by SarahBocognano** [comment]
Tooltips are also missing in the "advance search" and "bulk search" in the search bar
