### ISSUE TITLE
Addition of a Product entity

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6351]
## Use case
Currently a software product is only represented in the platform as a software observable.
With the initial release of the cpe connector product data are now widely available for importing on the platform. The purpose of the software observable is to reflect a specific version of a software. But to be able to perform analyzes of vulnerabilities across software products it would be beneficial to have a parent Product entity type.
The relation would be then as follows:
```
              Software Observable > Vulnerability
Product  <
              Hardware Observable > Vulnerability
```
It should be possible to relate the product with an organization (vendor) to represent that a organization manufactures a product.
This would allow to do further analyzes of vulnerabilities per vendor.

For Hardware Observable the related issue is https://github.com/OpenCTI-Platform/opencti/issues/4905

## Proposed Solution
Addition of a Product entity that can be used as a parent of a software observable. The software observable is considered a version of the product. The product should be capable to have a relation to an organization (Proposed type: Vendor of).

**Comment by Jipegien** [comment]
@iFrozenPhoenix We need to think about it, modifying the data model can be very impactful, and something might be done based on the cpe hierarchical identifiers.

Your use cases are the following:
- Ability to identify every software versions impacted by a vulnerability
- Ability to list every vulnerabilities impacting a Software, regardless of the exact versions
- Ability to list every vulnerabilities affecting Organization's product range

correct?

**Comment by ghost** [comment]
That's perfectly correct.

**Comment by Jipegien** [comment]
Thanks. 

We want to address this problem in OpenCTI. We don't know if we will cover these use case by creating a Product Entity and can't give you an ETA at the moment, but we will keep you posted.

**Comment by Jipegien** [comment]
We landed to a coherent approach regarding Vulnerability management enhancement in OpenCTI.
We will leverage CPE identifier and "start with" filter to be able to query Softwares of a same Product range.
We will also implement some dynamic source/target filters in the platform (like ones present in Dashboard) to create more complex lists, streams and trigerring, like "all vuln affecting software that related to an Organization/Infrastructure" or "all vuln affecting my Infra and used by Threat Actor or Intrusion Set targetting my activity Sector. 
On the integration side, we will push to implement Tanium Asset Management and Tenable/Qualys.
