### ISSUE TITLE
[Groupings] Content is not saved

### ISSUE THREAD

**Issue by MalwareCantFly** [LuatixHQ/opencti#6360]
## Description

Groupings -> Content:
Adding content and hiting the save button, doesn't do anything.

## Environment

Demo environement

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to a specific grouping
2. Click the Content tab
3. Edit the content and hit the save button
4. Exit the content tab, and come back to it
5. There is no content

## Expected Output

Content should be saved :)

Thanks!

**Comment by labo-flg** [comment]
Cannot edit the main content + adding files fail too.

**Comment by Kedae** [comment]
Linked to #6379
