### ISSUE TITLE
Wrong sorting of reports when by Publication date 

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6364]
## Description

The sorting is wrong when done by Publication date on reports

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to reports
2. Search "Dark" and sort by publication date

## Actual Output

Wrong sorting

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/e9462746-27eb-47a0-9403-33434cda7c69)

**Comment by Lhorus6** [comment]
First: Maybe I'm wrong, I'm curious to know the answer

My idea:

I don’t think it’s a bug. Search sorts by relevance. If you choose to sort by date, the sorting will be done on reports of the "same" relevance level, but relevance will be the first sorting level.

Here's an example:
Your search is "XXX" and our search engine evaluates the relevance of each report like this:

    Report A -> 5
    Report B -> 3
    Report C -> 3

If you decide to sort by date, Report B and C may change order, but they won't come before Report A.

**Comment by SamuelHassine** [comment]
Yes, this is the expected behaviour.

**Comment by yassine-ouaamou** [comment]
It is still the same problem without any search
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/1874ecc7-9a64-4b8b-a6a7-a260d8c7aab1)

**Comment by SamuelHassine** [comment]
I'm not able to reproduce on my side:

https://github.com/OpenCTI-Platform/opencti/assets/1334279/2934975b-0f4e-47d4-9715-aeb9ef17ac41

Are you sure you press enter after emptying the search field?

**Comment by yassine-ouaamou** [comment]
My bad! You are right @SamuelHassine. I didn't press Enter after emptying the search field
