### ISSUE TITLE
EE button in organization edition is not clickable

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6378]
## Reproductible steps

Disable EE.
Go to Parameters > Settings > Organization.
Go to an organization overview.
Edit it.
The EE button next to the 'granable groups' field is not clikable whereas other EE button in the platform are.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/b7adacbd-963d-42a9-ad0c-2aeb670cef6d)

When we click on the EE button, a pop-up should open, enabling to activate EE.

**Comment by Archidoit** [comment]
In the user edition form, the EE button next to 'Organization admin' is not vertically aligned (it is too low) : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/2b7f76f4-7b97-41d5-ae9b-12dbf9049cc1)

**Comment by nino-filigran** [comment]
@Archidoit I cannot reproduce on Testing. Does it still happen on your side?

**Comment by Archidoit** [comment]
@nino-filigran I still reproduce it on testing

**Comment by nino-filigran** [comment]
My bad, for whatever reason, I guess it did work for a bit. I've also tried again and got same result as you do.
