### ISSUE TITLE
Custom Incident + Incident Response Cases Types

### ISSUE THREAD

**Issue by The-Stuke** [LuatixHQ/opencti#6381]
## Use case

When tracking a case in OpenCTI it would be nice to have custom or more incident response types to help cover a variety of different cases. Currently there is only data-leak and ransomware as case types. Incidents have a larger selection which helps fills gaps, but sometimes we need to utilize feature of incident response that incident does not support.

## Current Workaround

Use current default types and mark it with a specific tag of the actual case type.

## Proposed Solution

Allow the ability to have custom incident response types or a greater selection to cover the variety of case types. Custom would allow organizations to have some flexibility to fit types of cases they have usually.

Suggestions for additional types that are not present: account compromise, phishing, business email compromise (BEC), malware, unauthorized access, insider threat, DDoS.

## Additional Information

Currently incident response cases only let you select data-leak or ransomware.
![image](https://github.com/OpenCTI-Platform/opencti/assets/48042955/a1058118-eb83-468e-9b74-bb6b9d7748a8)

Checking customization for incident response cases only lets you set a default value of data-leak or ransomware.
![image](https://github.com/OpenCTI-Platform/opencti/assets/48042955/c3656280-3be7-4599-b03e-c04c536e52d8)

Incident types have a wider selection of defaults.
![image](https://github.com/OpenCTI-Platform/opencti/assets/48042955/05cafc7b-5634-43c9-9a4f-e8cac777c79a)

## If the feature request is approved, would you be willing to submit a PR?

I can help structure it if needed. Not sure what this would require throughout the whole platform.

**Comment by Jipegien** [comment]
Already possible from Taxonomies/Vocabularies/incident_response_types_ov
