### ISSUE TITLE
System non-responsive (UI nearly unusable) when editing/downloading/saving large HTML files in content editor

### ISSUE THREAD

**Issue by emaes** [LuatixHQ/opencti#6383]
## Description

When editing a large HTML file for an Event, the UI updates super slowly as you type. To the level that the UI is non-responsive and unusable. You type something and it takes several seconds for what you type to populate on the page. Additionally, if you try to download the large HTML file as a PDF, the download never happens or takes a long time to start. Saving also has a very long response time.  This seems to happen with HTML files that are larger than 75k-100k. Plain text files are better, but not great

Navigate to the content tab using **_http://your-opencti-url/dashboard/events/incidents/event-UUID/content_**

*** Our groups workflow depends on the ability to edit/save/download/etc. an HTML file.  So a fix for this is greatly appreciated versus an alternate non-HTML notes option.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Download one of the attached TXT files from this issue and rename it to be a HTML file
2. Open the Events dashboard
3. Create a new Event by pressing the + sign
4. Fill in the Name, Incident Type, Severity, etc..
5. Using the **Select Your File** button, attach the large HTML file (more than 100k that was attached here)
6. Press **Create**

Now to recreate.. 
1. Navigate to the newly created Event
2. Navigate to the content tab by appending **/content** to the URL (as shown above)
3. Try the following:
   -  Try typing in the editor window
   -  Try saving the content (lower left icon)
   -  Try downloading the file as PDF or as is (lower right icon)
4. All seem to take a long time to have any UI response.

## Expected Output

The system should be responsive and allow the user to edit/save/download HTML files

## Actual Output

The UI becomes sluggish and essentially non-functional.  Especially when the files are much larger than 100k

## Additional information

None

## Screenshots (optional)

[100013.txt](https://github.com/OpenCTI-Platform/opencti/files/14640136/100013.txt)

**Comment by emaes** [comment]
Was unable to upload an HTML file.. thats why it's a text file attached...

![image](https://github.com/OpenCTI-Platform/opencti/assets/3697928/cc141843-28d5-497c-8452-5fd85ca4a3bf)

**Comment by emaes** [comment]
Here is a 125k sized TXT file that can be used... make sure to rename it to have HTML extension before attaching it to an event
[125005.txt](https://github.com/OpenCTI-Platform/opencti/files/14640436/125005.txt)

**Comment by nino-filigran** [comment]
@emaes beside the download, which I agree is quite long, I do not encounter any of issues. I've tried it on our demo environment. 

https://github.com/OpenCTI-Platform/opencti/assets/148041607/883cfecf-c140-4756-baa6-7a9f1d2d5c76

**Comment by nino-filigran** [comment]
Additionnally, I've tried it on a report, and the download works (even though my screen is slightly buggy).
Officially speaking, the "content" view is not supported in incidents and many other entities. We are planning to support it in the next release to ensure that we can upload everything correctly on many entity types.

https://github.com/OpenCTI-Platform/opencti/assets/148041607/46c84786-2302-4c79-ae9a-7f20e158f211

Could you maybe share your config? Trying to understand what's happening there.

**Comment by emaes** [comment]
From your video, I see that you are in "text edit" mode vs an HTML editing mode. When I attached the file as a TXT file, it used "text edit" mode when I went to the /content tab... but when I attach the file as an HTML, then it goes into "html edit" mode. That is the mode when it is non-responsive. Not sure if this helps... If you did not already, please rename the file to have an HTML extension and then attach it to the Event.

**Comment by nino-filigran** [comment]
@emaes could you let me know if you're on the most up-to-date version of OpenCTI? And if not, could you please try to upgrade to see if the problem persists? The most recent is 6.0.7

**Comment by nino-filigran** [comment]
@emaes just to ensure, did you see my comment?

**Comment by emaes** [comment]
We recently updated to 6.0.8. I have tested it there and it is also has a slow response when editing at 100k HTML file.  It may be slightly better in responsiveness, but overall very similar behavior.

**Comment by nino-filigran** [comment]
@emaes indeed, issue is still happening.
