### ISSUE TITLE
Getting Yarn Install Error When i try to install OpenCTI manually on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Pascar85** [LuatixHQ/opencti#6385]
## Description

Hi.. i keep getting this error when I'm trying to install OpenCTI manually on ubuntu 20.04 

:/opt/opencti/opencti$ sudo yarn install
/opt/opencti/opencti/.yarn/releases/yarn-4.1.0.cjs:4
(()=>{var Z3e=Object.create;var NR=Object.defineProperty;var $3e=Object.getOwnPropertyDescriptor;var e_e=Object.getOwnPropertyNames;var t_e=Object.getPrototypeOf,r_e=Object.prototype.hasOwnProperty;var ve=(t=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(t,{get:(e,r)=>(typeof require<"u"?require:e)[r]}):t)(function(t){if(typeof require<"u")return require.apply(this,arguments);throw new Error('Dynamic require of "'+t+'" is not supported')});var Et=(t,e)=>()=>(t&&(e=t(t=0)),e);var _=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),Vt=(t,e)=>{for(var r in e)NR(t,r,{get:e[r],enumerable:!0})},n_e=(t,e,r,o)=>{if(e&&typeof e=="object"||typeof e=="function")for(let a of e_e(e))!r_e.call(t,a)&&a!==r&&NR(t,a,{get:()=>e[a],enumerable:!(o=$3e(e,a))||o.enumerable});return t};var $e=(t,e,r)=>(r=t!=null?Z3e(t_e(t)):{},n_e(e||!t||!t.__esModule?NR(r,"default",{value:t,enumerable:!0}):r,t));var vi={};Vt(vi,{SAFE_TIME:()=>x7,S_IFDIR:()=>wD,S_IFLNK:()=>ID,S_IF

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

in the installation manual, when i reach the Start the application section, i have to run the command "yarn install" by default yarn is not installed on ubuntu 20.04 LTS so i had to install it. after that then i run the command yarn install and that were i get the error above, please assist me here i really want to try out OpenCTI. 

## Environment

1. OS: Ubuntu 20.04 LTS
2. OpenCTI version: Version 6.0.7

**Comment by Jipegien** [comment]
Hello @Pascar85! We'll look into it when we get the time. In the mean time, I invite you to ask the community about this on our Slack channel. The community is very active.

**Comment by aHenryJard** [comment]
Hello @Pascar85 , can you please verify version of yarn and node that are used in command line ?
```
yarn --version
node --version
```
Unfortunaltely the binary version installed with `apt-get` or similar linux package manager migth install versions that are too old to run OpenCTI.

Also the discussion on this other issue that looks like similar could help https://github.com/OpenCTI-Platform/opencti/issues/6304

**Comment by symsal** [comment]
I have the same problem yarn version is 1.22.22 

file /home/opencti/.yarn/releases/yarn-4.1.1.cjs

Any update?

**Comment by aHenryJard** [comment]
You need to have yarn 4+. Can you run the migrations steps: `corepack enable` and `yarn set version berry` like in this comment ?

https://github.com/OpenCTI-Platform/opencti/issues/6304#issuecomment-1997665075

**Comment by Pascar85** [comment]
Hi.. @aHenryJard, once i issue the commands above, does that upgrade the Yarn version?

**Comment by symsal** [comment]
> You need to have yarn 4+. Can you run the migrations steps: `corepack enable` and `yarn set version berry` like in this comment ?
> 
> [#6304 (comment)](https://github.com/OpenCTI-Platform/opencti/issues/6304#issuecomment-1997665075)

yarn 4? do you have any guide to follow for migration ? My node version is 12.22.5

**Comment by symsal** [comment]
I resolved
remove nodejs with `apt remove nodejs && apt purge nodejs`
Install nvm following this guide 
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04#option-3-installing-node-using-the-node-version-manager

with nvm install nodejs version > 20
after that go to opencti folder and run
yarn install

**Comment by Pascar85** [comment]
Hi guys.. im still struggling to install. Please guide me. I just did a clean install of ubuntu 20.04 LTS. It doesnt come with yarn by default. Please give me a step by step guide on how you guys got it right.  I tried the steps above but still didnt get it right. 🙏

**Comment by aHenryJard** [comment]
Hello @Pascar85 , the way that a worked for me is:
1. install node with nvm
2. then you can install yarn with `corepack`, corepack is installed along with node so it should be avalaible "out of the box"

So once node is there `corepack enable` should add yarn to your ubuntu.

https://yarnpkg.com/getting-started/install

**Comment by Pascar85** [comment]
Thank you @aHenryJard .. it worked now for me.. thank very much

**Comment by aHenryJard** [comment]
Happy that it's working for you ! I'm closing the issue then.
