### ISSUE TITLE
Error deleting a file from a data tab

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6389]
## Description

When deleting a file from a data tab, an error message appears (but the file is deleted).

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Go in the Data tab
3. Upload a file
4. Remove the file 
-> Error occurs

## Screenshots

![Screenshot 2024-03-19 162121](https://github.com/OpenCTI-Platform/opencti/assets/70956706/20524be1-38a0-4a7f-a83a-5165ddcaf035)

![Screenshot 2024-03-19 162215](https://github.com/OpenCTI-Platform/opencti/assets/70956706/ebad5011-67b9-4982-af2d-372bf0be7581)

**Comment by SouadHadjiat** [comment]
It's quite an issue because the error happens after deleting the file, when trying to update the entity (x_opencti_files), and before we could send a stream event, or log in the history.
