### ISSUE TITLE
Some filters in the entities' "knowledge" tabs don't seem to work.

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6390]
## Description

When I try to filter entities in the timelines of my knowledge tab, nothing changes.

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the intrusion set APT29
2. Go to the knowledge tab
3. Scroll down to see the timeline
4. Try to filter the type of entity displayed with the "target type" filter

## Screenshots

![Screenshot 2024-03-19 162630](https://github.com/OpenCTI-Platform/opencti/assets/70956706/1893a0dd-618c-4c20-aa81-9183784300da)

**Comment by Jipegien** [comment]
seems to be only the "target types" filter.

**Comment by Archidoit** [comment]
In the same screen (Incident > Knowledge): no values in the target entity filter: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f4f26683-3a1c-4cb5-9811-2275614f4ec9)

**Comment by Archidoit** [comment]
other bug resolved in the same PR: fromOrToId filter is not working with not_eq operator
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/58e811e9-28cc-42b4-8aaf-aaa4ad43f5c1)
