### ISSUE TITLE
Several issues in filters of entities' knowledges tab

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6391]
## Description

The filters available in the entity knowledge tabs are strange. For example, we don't have an "entity type" filter, but we do have "event type" filters...

NB: More generally, the filters on the knowledge tab timelines need to be reviewed. Some don't seem to work, some are missing, others we don't really understand why they're there, etc. cf another issue: https://github.com/OpenCTI-Platform/opencti/issues/6390

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the intrusion set APT29
2. Go to the knowledge tab
3. Go to victimology
4. Look into the filters available

## Screenshots

![Screenshot 2024-03-19 162708](https://github.com/OpenCTI-Platform/opencti/assets/70956706/5a8a54dd-8619-459d-9a0d-f4af13872033)

**Comment by Archidoit** [comment]
@Lhorus6  The available filters are the one existing for the entity types displayed in Victimology (system, individual, organization, locations, event etc). Therefore the 'event types' filter (that exists for Events) is available. I can add the 'entity type' filter in the filter list.

**Comment by Lhorus6** [comment]
Oh yes, by "event type" I thought about log events, not entity events. My bad
Entity type can be very useful yes, thank you
