### ISSUE TITLE
Link to relationship object to ObservedData objects in Infrastructure object is wrong

### ISSUE THREAD

**Issue by sweet-mentat** [LuatixHQ/opencti#6400]
## Description

In the GUI, when I view an Infrastructure object and click on the Knowledge tab, I can view my timeline of ObservedData objects that  have imbedded relationships to the Infrastructure object. When I click on any of the ObservedData objects to view the relationship object, it takes me to the wrong link. It takes me to: (Actual Output)
https://<opencti_domain>/dashboard/threats/intrusion_sets/<infrastructure_object_id>/knowledge/relations/<observed_data_id>
I get an error that states "This page is not found on this OpenCTI application."

When I correct the link to this it works: (Expected Output)
https://<opencti_domain>/dashboard/observations/infrastructures/<infrastructure_object_id>/knowledge/relations/<observed_data_id>
The corrected link takes me to the correct page where I can view the relationship object that relates the Infrastructure object and the ObservedData object.

## Environment

1. OpenCTI docker image, opencti/platform:6.0.5
2. OpenCTI version: OpenCTI 6.0.5
3. OpenCTI client: frontend
4. Other environment details:

**Comment by nino-filigran** [comment]
This behavior is reproduced also on my side.
