### ISSUE TITLE
Error not shown in UI

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6404]
## Description

If I try to rename an entity with the same name as another entity, the change is not made. This is normal, however, I don't get any error displayed in the UI to tell me this. In this case, it's hard to understand why the name doesn't change.

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an Organization OrgA
2. Create an Organization OrgB
3. Modify the OrgB to change its name to OrgA
4. Click outside the panel to validate the modification
-> The name doesn't change, and no error/information appears

The error is clearly visible in network traffic (see screenshot)

## Screenshots 

![Screenshot 2024-03-21 121037](https://github.com/OpenCTI-Platform/opencti/assets/70956706/150cd028-04f8-4b0a-b2e0-af1bb6383aad)

**Comment by nino-filigran** [comment]
This seems to happen specifically with orgs (tried with other entities and I could change the name).

**Comment by Lhorus6** [comment]
It depends of the criteria of deduplication. If it's only on the name (like for the Org), this behavior happen. So, try on Event, Malware, etc.

See here : https://docs.opencti.io/latest/usage/deduplication/#entities
