### ISSUE TITLE
[CSV Mapper] Missing "contains" relation in the representation

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6408]
## Description

When I want to map a "contains" representation in my mapper, I can't because it's not available.

My use case is as follows:
I have on each line of my CSV a report title and a set of information (e.g. intrusion set). I want my entities to be contained in my report, but I can't because I can't use the "contains" relationship type in the representation.

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV mapper
2. Add a relationship representation
3. Try to choose "contains" as relation -> you can't

## Screenshots

![Screenshot 2024-03-21 153811](https://github.com/OpenCTI-Platform/opencti/assets/70956706/8eaeef94-8c57-49b0-b3ad-d59aed87b00d)

**Comment by CelineSebe** [comment]
There are no relationships explicitly defined between the Report object and other STIX Objects, other than those defined as common relationships: duplicate-of, derived-from, related-to.
There is no 'contain' relationship in the SRO (STIX Relation Object) sense. It is an object_ref.
I think it's not a bug, but it should be considered as a new feature.

**Comment by Lhorus6** [comment]
Indeed, there is no such thing as a "contains" relationship in the SRO (STIX Relation Object) sense, but OpenCTI has this concept. What we call a "contains" relationship is an object_ref. It seems to me that it was there in the past, but I might be wrong

**Comment by nino-filigran** [comment]
I don't know whether it existed or not honestly. However, the fact of not having it prevents the fact from creating entities contained in report through CSV, which is annoying.
I'm in favor of at least fixing this, and tackling through a proper feature the fact of adding refs (and other custom relations not existing in stix) in the CSV mapper.

**Comment by nino-filigran** [comment]
cc @Jipegien & @jborozco exactly what we discussed this morning

**Comment by lndrtrbn** [comment]
> I don't know whether it existed or not honestly. However, the fact of not having it prevents the fact from creating entities contained in report through CSV, which is annoying.
I'm in favor of at least fixing this, and tackling through a proper feature the fact of adding refs (and other custom relations not existing in stix) in the CSV mapper.

As "contains" is also a ref, I'm not sure you can just "fix" this case without managing all refs in a more generic way. I did not investigate it but it could be a bit of work.

**Comment by nino-filigran** [comment]
@lndrtrbn ok let me know if you think it's too big (and if it makes sense to only tackle one use case) after a short investigation. If it's the case, then let's tackle this as a feature cc @Kedae

**Comment by lndrtrbn** [comment]
In fact, refs are already managed. But they are not in the block "Representations for relationship" because they are not relationships but refs. For example if you create a representation for a Report, you have already a row "contains" inside the representations to do what you want, like for authors, labels, assignees, etc.

Nonetheless it seems that this "contains" row does not work properly, and that indeed seems to be a bug, not a feature.

**Comment by Goumies** [comment]
Based on the different comments, I tried to create a CSV mapper by adding the Intrusion set as a representation entity. Although I created the Intrusion set, it is not listed in the Contains field options. Plus changing the order of the representations of the report and the intrusion set does not impact the list of options. I will look into it more.

[Report title and intrusion set.csv](https://github.com/user-attachments/files/16110038/Report.title.and.intrusion.set.csv)

![Image](https://github.com/OpenCTI-Platform/opencti/assets/13460700/88aeecc2-9dc5-4bd1-9034-bd8d9bc0c85c)

**Comment by Goumies** [comment]
The `contains` field is related to the `objects` property which is considered as a "ref".
Type resolution for ref relationships does not handle parent types.
So when evaluating strict equality between a parent type and a child one, the result is `false`.

For example:
objects refs -> Stix Core Object type
The current codebase evaluate if Intrusion set is equal to Stix Core Object to resolve the compatible options to list.
