### ISSUE TITLE
"Select all" selects the whole platform, not just what's on the screen

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6411]
## Description

When I do a "select all" to delete relations, when I look at my background task, I realize that it contains 160K elements. That's not what I selected at the beginning.

## Environment

OCTI 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Got to a threat actor group
2. Go to knowledge > incidents (if you don't have incident here, add one)
3. Go to the "relation view" 
4. Select all and click on the bin in the bottom right corner to remove the relation.
5. Launch the background task and check the amount of entity that is processed.

**Comment by nino-filigran** [comment]
Confirmed
