### ISSUE TITLE
Home dashboards number metrics loarders are not centered vertically

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6412]
## Description

Home dashboard number metrics loarders are not centered vertically

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/6a6b79d7-9f0c-45d6-99a7-043311a5d123)

**Comment by nino-filigran** [comment]
Is there a way to reproduce this? When I refresh my page, the numbers are always loaded

**Comment by SamuelHassine** [comment]
Yes, just put network throttling. The dev team will now how to reproduce and fix.
