### ISSUE TITLE
Empty knowledge pages

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#6415]
## Description

4 pages are empty (you can try on testing) :
- Observation / infrastructures / select one / knowledge / incidents : https://testing.octi.staging.filigran.io/dashboard/observations/infrastructures/9eea48a1-6b76-436b-bcd1-51c0546b71e6/knowledge/incidents
- Threats / Intrusion sets / select one / knowledge / Observed data : https://testing.octi.staging.filigran.io/dashboard/threats/intrusion_sets/b6b4af6e-bb6f-41da-96a6-3b00c2591df2/knowledge/observed_data
- Techniques / attack pattern / select one / knowledge / sightings : https://testing.octi.staging.filigran.io/dashboard/techniques/attack_patterns/f26180cd-27bc-4d30-a0fa-4fa7bb1fc26d/knowledge/sightings
- Locations / Positions / select one / knowledge / Locations : https://testing.octi.staging.filigran.io/dashboard/locations/positions/9f03db42-47ce-4a45-947e-b11b7cced9d6/knowledge/locations

In Root files, this routes dosn't exist. 

## Expected Output

2 ways :
- remove buttons on right bar if it's an error
- implement routes if we want to make it accessible 

## Actual Output

- empty pages

**Comment by nino-filigran** [comment]
- Therefore for [Observation / infrastructures / select one / knowledge / incidents](https://testing.octi.staging.filigran.io/dashboard/observations/infrastructures/9eea48a1-6b76-436b-bcd1-51c0546b71e6/knowledge/incidents), we should implement routes & allow creation with the values compromises or uses.
   - Relation incident -> infra can be compromises or uses. 
   - Relation infra -> incident can be related to

- There's no specific relation between intrusion set & observed data, in both ways, beside related to. Thereofre, we should remove route for [Threats / Intrusion sets / select one / knowledge / Observed data ](https://testing.octi.staging.filigran.io/dashboard/threats/intrusion_sets/b6b4af6e-bb6f-41da-96a6-3b00c2591df2/knowledge/observed_data). Indeed, related to should be in related entities.

- sighting & attack pattern: can be removed.
- location & location seems to me like a loop. Therefore, we should not implement that route.
