### ISSUE TITLE
Actions not correctly displayed in tasks list

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6417]
## Description

Actions not correctly displayed in tasks list

## Reproducible Steps
Go to the report list. Select some reports via the checkboxes.
Do a background task that modify their labels.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f7b8820b-ba9d-4da3-a3b2-73a07365bdb4)
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/d2e6fe65-333a-4197-a443-b8f59ae68ee2)

Go to the tasks lists.
The 'actions' of the tasks are not correctly displayed: 
- 'object-label' is not translated
- we have the id of the label instead of its name
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/fc95a4a4-3120-430e-840e-38ac57d249ce)

Same for markings, author, etc
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/c457f704-5213-421e-82d6-86e8d5c136f1)
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/fe0fce53-b3ed-4acf-9a9d-6bb2c231c029)

**Comment by nino-filigran** [comment]
It basically happens for any action on any field: only the ID of the value is displayed and not its value.

**Comment by SarahBocognano** [comment]
After speaking with product: We'll keep the display of the ID for refs/rels and maybe open a feature for that in the future. For now I wil just translate the fields.
