### ISSUE TITLE
When consulting a read-only dashboard, the "+" button is still displayed for widgets creation

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6464]
## Description

1. Create a new dashboard
2. Grant read only access to everyone
3. Connect with another user
4. Go to the dashboard
5. The "+" button on the button right is available, creating a widget leads to error (expected) "You are not allowed to do this".

=> The button should be hidden.

**Comment by jborozco** [comment]
I'm adding a link to a dashboard to reproduce issue: https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/fd8f41fe-69a7-479b-aaa9-234fee9ad32a
