### ISSUE TITLE
Redirect to specific vulnerability from a widget does not work

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#6472]
Reproduced on testing environment.

When hovering a CVE in the widget:
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/060cfcfe-7199-490d-8292-30d0125b570f)

Link URL is broken (null inside).

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/44b9b1c2-61e6-4f7d-84c9-f918f3e52ec1)

**Comment by ValentinBouzinFiligran** [comment]
this issue has been fixed in this PR : https://github.com/OpenCTI-Platform/opencti/pull/6512/files
