### ISSUE TITLE
Nested refs are not properly removed in groupings knowledge graph

### ISSUE THREAD

**Issue by JeremyCloarec** [LuatixHQ/opencti#6482]
## Description

When trying to delete a ref from a groupings knowledge graph, the ref is deleted at first, but when switching to an other tab and switching back, the ref is still visible

## Reproducible Steps

1. Create a new grouping
2. Go to the knowledge graph, add a malware and file observable
3. Create a sample ref between the malware and the file
4. Delete the sample ref
5. Switch to an other tab and come back

## Expected Output

The ref being removed from the groupings graph

## Actual Output

The ref still visible in the graph

## Additional information

No graphql query is sent when removing the ref

**Comment by nino-filigran** [comment]
Reproduced on Demo
