### ISSUE TITLE
Labels display doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6494]
## Description

The window that should allow us to see all the labels is stuck on the 25 first labels, i.e. scrolling down doesn't load any other labels.

## Environment

OCTI 6.0.8 (testing and demo)

Firefox 124.0.1 (64-bit)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the window "Settings > Taxonomies > Labels"
2. Scroll down
-> Impossible to see more than 25 labels

**Comment by NiQuintin** [comment]
I think the bug is a little wider in fact...
![Infinite-scroll-down](https://github.com/OpenCTI-Platform/opencti/assets/155080335/ebdffae6-aed1-4273-b23b-65f15ab7620e)
