### ISSUE TITLE
[Generic webhook] Customising notification output

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#6498]
## Description

Considering the below template for the default Teams webhook:

`{
        "type": "message",
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.thumbnail",
                "content": {
                    "subtitle": "Operation : <%=content[0].events[0].operation%>",
                    "text": "<%=(new Date(notification.created)).toLocaleString()%>",
                    "title": "<%=content[0].events[0].message%>",
                    "buttons": [
                        {
                            "type": "openUrl",
                            "title": "See in OpenCTI",
                            "value": "https://10.254.202.12/dashboard/id/<%=content[0].events[0].instance_id%>"
                        }
                    ]
                }
            }
        ]
    }
`

I changed it slightly for my use case, which basically just removed "buttons" as I am just sending this request to Power Automate to generate an email:

`{
    "type": "message",
    "attachments": [
            {
                "contentType": "application/json",
                "content": {
                    "alertSubject": "<%=content[0].events[0].message%>",
                    "alertDatetime": "<%=(new Date(notification.created)).toLocaleString()%>",
	            "alertOperation": "Operation: <%=content[0].events[0].operation%>",
                    "alertUrl": "See threat report in CTI platform: https://10.254.202.12/dashboard/id/<%=content[0].events[0].instance_id%>"
                }
            }
        ]
}`

I would like to be able to customise what information my webhook sends. I want to be able to include information (for a report notification webhook) such as description and external reference. Unfortunately I don't have much webhook/GraphQL knowledge to be able to understand what syntax is needed to add content such as this, and where I would find it.

**Comment by Jipegien** [comment]
@Kedae Can you help on this specific question ?

**Comment by Kedae** [comment]
Hi @dominictory,

We currently don't have specific documentation on how use/access variables in notifiers templates.
In your case you can use the "data" object that is available in the template with something like :

<%=data[0].instance.description%>

For example.
Depending on your endpoint you can also send the whole data object through your webhook to see the format of the element you are getting.

I also suggest that you use a ejs helper online to check the syntax when trying to display value from your entity.

**Comment by dominictory** [comment]
> Hi @dominictory,
> 
> We currently don't have specific documentation on how use/access variables in notifiers templates. In your case you can use the "data" object that is available in the template with something like :
> 
> <%=data[0].instance.description%>
> 
> For example. Depending on your endpoint you can also send the whole data object through your webhook to see the format of the element you are getting.
> 
> I also suggest that you use a ejs helper online to check the syntax when trying to display value from your entity.

Thanks! Unfortunately <%=data[0].instance.description%> didn't seem to produce anything extra in the notification. For the whole object, would I just add <%=data[0]>?

**Comment by dominictory** [comment]
> Hi @dominictory,
> 
> We currently don't have specific documentation on how use/access variables in notifiers templates. In your case you can use the "data" object that is available in the template with something like :
> 
> <%=data[0].instance.description%>
> 
> For example. Depending on your endpoint you can also send the whole data object through your webhook to see the format of the element you are getting.
> 
> I also suggest that you use a ejs helper online to check the syntax when trying to display value from your entity.

Thanks! This worked to add the description. How would I add the external reference URL(s)? Also, if I wanted to send the whole data object, what would be the syntax for this?

**Comment by Kedae** [comment]
I think you can try <%=data%>

**Comment by dominictory** [comment]
> I think you can try <%=data%>

Thanks, I tried this but the output is `[object Object]`. If you could please let me know how I would include the external reference URLs, this should be all I need. Would be nice to see the whole data object though so I know what I can include in future if needed, such as labels and marking.
