### ISSUE TITLE
Incomplete JSON export of reports

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6499]
## Description

When exporting a report from the reports list, if it contains many entities, some of them are not included in the generated bundle

## Environment

Testing (6.0.8)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Include arount 50 entities and a PDF in it
3. Go to the reports list
4. Select the created report and click on the export button
5. Generate an export (JSON, full export, no marking)
6. Download the generated JSON

## Expected Output

The bundle contains the pdf and all the included entities

## Actual Output

Many entities are missing

## Additional information

Here is the report I used to reproduce: https://testing.octi.staging.filigran.io/dashboard/analyses/reports/86ec8fd0-9b66-4971-9348-8828d4ce1c74

**Comment by nino-filigran** [comment]
potentially linked with: https://github.com/OpenCTI-Platform/opencti/issues/5798

**Comment by AlexSanchezN** [comment]
Should that be solved on 6.0.10?
I'm in 6.0.10, and we have reports with many entities as seen on the first image
That only show a few of the objects in knowledge (second image)
And only export a few objects from the Data tab -->
[2024-04-19T14 40 41.122Z_TLP ALL_(ExportFileStix)_Report-Sensor sensor1792.etic.security (Week 16)_full.json](https://github.com/OpenCTI-Platform/opencti/files/15042051/2024-04-19T14.40.41.122Z_TLP.ALL_.ExportFileStix._Report-Sensor.sensor1792.etic.security.Week.16._full.json)



![many](https://github.com/OpenCTI-Platform/opencti/assets/6607235/3fa3a7e0-1fb1-424e-a3d6-d6491ae29a4a)

![imatge](https://github.com/OpenCTI-Platform/opencti/assets/6607235/a2b67259-24a5-4f86-a268-4e2cace0d0dd)

**Comment by SamuelHassine** [comment]
To be qualified.

**Comment by jborozco** [comment]
@AlexSanchezN according to your graph, there might be a filter still active, could you try to clear your local storage and retry ?

**Comment by AlexSanchezN** [comment]
Hi @jborozco , thanks for your help.

It happens in different browsers, different computers and in incognito mode. I've reseted cookies, and cleared data and the problem persists. In fact nothing is shown in the knowledge window in this case.
The images are from a different computer and in incognito mode
I know for sure that the bundle used to create those reports, includes notes, vulnerabilities and relations. But none of those appear either in knowledge. 
Although as it can be seen in the 3rd image below there are 3.600 entities counted but are not shown in the entities list.
Is it possible that Note type is not shown on the entities list?. There should be a lot of notes there with vulnerabilities and its relations to ipv4 observables.

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/e4663b76-d6b7-4e5e-bc55-a80e662463a7)

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/0f92989f-1136-4421-9323-4597c19c010a)

![image](https://github.com/OpenCTI-Platform/opencti/assets/6607235/2e5e01be-c3db-413f-a253-c608b5b61ec3)

**Comment by jborozco** [comment]
Notes should present in entities in theory
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/6c32f9c5-51d6-46c7-a8fe-fe555181a6ca)

@richard-julien @Kedae I can't reproduce, but something seems off, do you have an idea of where the problem could come from ?

**Comment by AlexSanchezN** [comment]
Maybe the attached video explains better the situation with notes inside a report.

https://github.com/OpenCTI-Platform/opencti/assets/6607235/203c7df7-f90b-49ff-8284-7bdcddf4f02a

As you can see, it looks like notes are not shown in lists.
And we see no vulnerabilities either.

**Comment by AlexSanchezN** [comment]
> Notes should present in entities in theory ![image](https://private-user-images.githubusercontent.com/35300800/325889669-6c32f9c5-51d6-46c7-a8fe-fe555181a6ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDM1NTAsIm5iZiI6MTcxNDMwMzI1MCwicGF0aCI6Ii8zNTMwMDgwMC8zMjU4ODk2NjktNmMzMmY5YzUtNTFkNi00NmM3LWE4ZmUtZmU1NTUxODFhNmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDExMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGRmYzk4NzhjOTJiYzBlODM5ODhlODNiOGM5ODIyZmE4OWIzZTBkMDM0YmUzNTQ4M2RkYjA2MzUwNTYwYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IP7LQ0nvWzYypMI2_YKL9VnlFrA65IUnvqEuuKHH6yY)
> 
> @richard-julien @Kedae I can't reproduce, but something seems off, do you have an idea of where the problem could come from ?

By the way. You have two notes in that report, but they are not counted... it says 0 entities in the upper right counter

**Comment by jborozco** [comment]
I just didnt refresh the page after adding entity, when I do I see the right number.

![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/fbd93164-d2f0-4556-8ad1-1d783380f3cd)

**Comment by jborozco** [comment]
The issue seems to be that report can't handle big number of entities

**Comment by AlexSanchezN** [comment]
Glad there is a clue.
It used to work a few versions ago. Provably in version 5.x.x

**Comment by jborozco** [comment]
As discussed with @yassine-ouaamou , I'm creating a new issue here [https://github.com/OpenCTI-Platform/opencti/issues/6839](https://github.com/OpenCTI-Platform/opencti/issues/6839) and closing this one to keep issues separated.
