### ISSUE TITLE
[Merge] Bad management of Author when merging several Organizations

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6507]
## Description

When we merge more than two organizations, the Author field of the entities authored by the Organization merge (the secondary Organization), become empty instead of containing the newly merged entity.

## Environment

OCTI 6.0.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create 3 Org -> OrgA, OrgA bis, OrgA ter
2. Create 3 Malware -> MalA with OrgA as author, MalA bis with OrgA bis as author, etc.
3. Go to Data > Entities and merge the 3 Org
-> Check the field "author" of the 3 malware.

## Additional information

In the lateral panel to choose the main entity (i.e. the entity for which we keep the description and the title):
- if you keep the main organization without changing it manually -> only one of the secondary organizations is well manage in term of author (i.e. the authored entities will have the new value),
- if you change the main organization -> no one is well manage in term of author

### After the merge of 3 System that was the author of 3 Intrusion set

![Screenshot 2024-03-28 102848](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f9ba15df-f835-49c5-ae6f-dac5af440b0a)

**Comment by Jipegien** [comment]
In the screenshot, the org proposed as default in the merge process was "SysA ter"

Other situation: 
in the example, if we choose OrgA bis, the result will be
- IntA->nothing, 
- IntA bis->OrgA bis, 
- IntA ter->nothing.
