### ISSUE TITLE
CSV Feed Creation not possible

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6508]
## Description
Creating a CSV Feed is not possible due to a disabled Create Button.

## Environment

1. OS (where OpenCTI server runs): Debian (k8s)
2. OpenCTI version: 6.0.5
3. OpenCTI client: web
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Data Sharing
2. Click CSV Feed
3. Click +
4. Fill out the form and apply filters

## Expected Output
Possibility to create the feed or information why it is not possible (Missing data, ...)

## Actual Output
None

## Additional information
My User has the capabilities "Bypass all capabilities".

## Screenshots (optional)
![Screenshot from 2024-03-28 11-06-03](https://github.com/OpenCTI-Platform/opencti/assets/36128722/42eaabdb-33f4-4a5b-b1d1-0c51b3cdfa3a)

**Comment by jborozco** [comment]
Hi @iFrozenPhoenix you need to specify how you want to map your feed to be able to create
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/ac414d20-d92f-408b-8fd1-b1fab0caadcd)

**Comment by ghost** [comment]
@jborozco thank you, now it is working :-).
