### ISSUE TITLE
Marking Restriction by User

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#6514]
## Description

When creating a new marking, example TM:RED and attaching that marking to a group and adding roles the user can still see all markings.

## Environment

1. OS: CENTOS7
2. OpenCTI version: 6.0.7
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new marking definition, example: TYPE: statement DEFINITION: TM:RED
2. Create a new user tmred
3. Create role user_TM:RED, add capabilities [Access knowledge, Access exploration, Create/Update exploration]
4. Create group user_TM:RED, add ROLES user_TM:RED, add marking TM:RED, add MEMBERS tmred
5. Login as user
6. The user tmred can still view all markings, happens when adding two markings to an existing threat actor(group). If one marking is used and filtered appropriately via groups user_TM:RED markings the filtering of data works as expected.

## Expected Output

User should only be able to view data with the specified markings per groups/markings assigned

## Actual Output

User can still view all data when multiple marking values are selected.

## Additional information

Recreated from Markings Filtering #5837, closed but not completely resolved.

## Screenshots (optional)

None

**Comment by richard-julien** [comment]
Hi @explorecti i'm not able to reproduce.
Can you check if the user is not part of the group default and have access to more markings than you expect (because of autoassign of default group)?
If not, please do some screenshot of the role config, group config and user config.
And also of the screenshot of the element that the user have access but it should not. Thanks

**Comment by explorecti** [comment]
@richard-julien Ok so it looks that the Default group was assigned by default causing the user to see all markings. Thank you for clearing this up, tested on version 6.0.8.
