### ISSUE TITLE
Icon for polar area widget is the same as radar

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6523]
## Description

Icon for polar area widget is the same as radar => find another icon to keep consistant the screen.

**Comment by nino-filigran** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/91e6fce9-84cd-4583-ac95-16cb5abee952)

**Comment by jborozco** [comment]
Svg suggestion: 

 
![Polar area](https://github.com/OpenCTI-Platform/opencti/assets/35300800/2580622a-9799-4a46-b0ba-a6b4226a091e)


or MUI suggestion https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apie_chart_outline%3A
