### ISSUE TITLE
Region countries are not highlited anymore

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6528]
## Description

Sub-Saharan Africa (but same for all regions, nothing is highlighted) 

Expected output (in blue in standard theme, here in red), version 5.11.X:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/7c8644b9-1419-4a55-97e7-2b74ba37ca44)

Actual output (6.0.X):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/b9f18c49-5896-4b1c-951a-79ea53465ac5)

**Comment by jborozco** [comment]
example here https://demo.octi.filigran.io/dashboard/locations/regions/162211c1-9024-430a-b329-ec2fd7a7efd3
