### ISSUE TITLE
Incomplete error message on Observable StixFile form creation when missing hash

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#6564]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on observable
2. Create a new one that is empty, just set atime and ctime
3. Click on "Create"

## Expected Output

The list of missing fields, it's at least one hash I guess (MD5, SHA1, ...)

## Actual Output
An empty list of missing fields.
![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/8d40513f-2991-42eb-941c-0eec0af2cd06)

**Comment by nino-filigran** [comment]
**Exact same errors for** 
- Artifact
- Files
- X509

**Similar error for the following observables:** 
- Domain (error is slightly different but not explicit either "observable is not correctly formatted")
- Email adress (error is slightly different but not explicit either "observable is not correctly formatted")
- Hostname (error is slightly different but not explicit either "observable is not correctly formatted")
- IPV4 (error is slightly different but not explicit either "observable is not correctly formatted")
- IPV6(error is slightly different but not explicit either "observable is not correctly formatted")
- Mac adress(error is slightly different but not explicit either "observable is not correctly formatted")
- Software(error is slightly different but not explicit either "observable is not correctly formatted")

**Different but still a bug for:** 
- Windows registry key value: can be created without entering any value in any field
- Email - MIME part: can be created without entering any value in any field

**Comment by RomuDeuxfois** [comment]
https://github.com/OpenCTI-Platform/opencti/issues/5454

**Comment by nino-filigran** [comment]
@aHenryJard closing this bug since we have a proper task to handle this. cc @Jipegien for awarness.
