### ISSUE TITLE
Dockers Keep restarting

### ISSUE THREAD

**Issue by vanitasKE** [LuatixHQ/opencti#6567]
Hello, I have problem with OpenCTi it worked yestreday ok but overnight i Had blank white page on Login page.
And noticed dockers keeps restarting:
![image](https://github.com/OpenCTI-Platform/opencti/assets/154703269/123b4cf5-c351-42c8-84d8-3090c979d693)

And here are logs from docker platform: 

Thu, 04 Apr 2024 09:24:53 GMT express-session deprecated req.secret; provide secret option at node:internal/modules/cjs/loader:1376:14
{"category":"APP","dependencyError":{"$fault":"client","$metadata":{"attempts":1,"extendedRequestId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","httpStatusCode":403,"requestId":"17C309781C72818C","totalRetryDelay":0},"BucketName":"opencti-bucket","Code":"InvalidAccessKeyId","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","RequestId":"17C309781C72818C","Resource":"/opencti-bucket/","message":"The Access Key Id you provided does not exist in our records.","name":"InvalidAccessKeyId"},"level":"error","message":"[OPENCTI] System dependencies check failed","timestamp":"2024-04-04T09:24:54.815Z","version":"6.0.8"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"The Access Key Id you provided does not exist in our records.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: The Access Key Id you provided does not exist in our records.\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/opt/opencti/build/src/boot.js:47:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"The Access Key Id you provided does not exist in our records.","name":"InvalidAccessKeyId","stack":"InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n    at throwDefaultError (/opt/opencti/build/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)\n    at throwDefaultError (/opt/opencti/build/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5)\n    at de_CommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18\n    at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22\n    at initializeBucket (/opt/opencti/build/src/database/file-storage.js:78:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:34:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-04-04T09:24:54.819Z","version":"6.0.8"}
Thu, 04 Apr 2024 09:25:05 GMT express-session deprecated req.secret; provide secret option at node:internal/modules/cjs/loader:1376:14
{"category":"APP","dependencyError":{"$fault":"client","$metadata":{"attempts":1,"extendedRequestId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","httpStatusCode":403,"requestId":"17C3097B036EE525","totalRetryDelay":0},"BucketName":"opencti-bucket","Code":"InvalidAccessKeyId","HostId":"dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8","RequestId":"17C3097B036EE525","Resource":"/opencti-bucket/","message":"The Access Key Id you provided does not exist in our records.","name":"InvalidAccessKeyId"},"level":"error","message":"[OPENCTI] System dependencies check failed","timestamp":"2024-04-04T09:25:07.283Z","version":"6.0.8"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"The Access Key Id you provided does not exist in our records.","name":"UNKNOWN_ERROR","stack":"UNKNOWN_ERROR: The Access Key Id you provided does not exist in our records.\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnknownError (/opt/opencti/build/src/config/errors.js:76:47)\n    at Object._logWithError (/opt/opencti/build/src/config/conf.js:331:23)\n    at Object.error (/opt/opencti/build/src/config/conf.js:341:48)\n    at platformStart (/opt/opencti/build/src/boot.js:47:12)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"},{"message":"The Access Key Id you provided does not exist in our records.","name":"InvalidAccessKeyId","stack":"InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n    at throwDefaultError (/opt/opencti/build/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)\n    at throwDefaultError (/opt/opencti/build/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5)\n    at de_CommandError (/opt/opencti/build/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /opt/opencti/build/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:225:18\n    at /opt/opencti/build/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22\n    at initializeBucket (/opt/opencti/build/src/database/file-storage.js:78:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:34:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"}],"level":"error","message":"Platform unmanaged direct error","timestamp":"2024-04-04T09:25:07.288Z","version":"6.0.8"}

Any idea what causing this?

**Comment by vanitasKE** [comment]
Hi, i found issue probably. 
 Did not have .env file set up.
But i can see some dockers restarting.
opencti/connector-import-document:6.0.8   
opencti/connector-export-file-txt:6.0.8 

![image](https://github.com/OpenCTI-Platform/opencti/assets/154703269/7cfa44d7-8fad-4e02-b3d8-f2629b72b5c9)

**Comment by vanitasKE** [comment]
it look all is fixed. only remaining one is. Qradar connector with following error:
{"timestamp": "2024-04-05T08:18:54.961966Z", "level": "ERROR", "name": "OpenCTI QRADAR Connector", "message": "'NoneType' object has no attribute 'group'", "exc_info": "Traceback (most recent call last):\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 175, in consume\n    self._consume()\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 196, in _consume\n    self.qradar_reference.create(id, payload)\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 62, in create\n    f\"{self.collection_url}_{self.get_type(payload)}\",\n                             ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/opencti-connector-qradar/qradar.py\", line 49, in get_type\n    ).group(1)\n      ^^^^^\nAttributeError: 'NoneType' object has no attribute 'group'"}



Can you tell me what it means? or is this issue in your script?

**Comment by vanitasKE** [comment]
@anyone?

**Comment by vanitasKE** [comment]
fixed

**Comment by yagobski** [comment]
how you fixed it?
