### ISSUE TITLE
Opinion are not visible anymore 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6578]
## Description

Navigate to a report, there is no opinions. Adding an opinion creates an error message "There are no opinions. You should create some before." 

## Environment

Testing only (not in demo)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
**No opinions**
1. Go in a report

**Not possible to add an opinion by clicking on CTA**
1. Go in a report
2. Click on the Thumbs

## Expected Output
**No opinions**
There is an opinion 

**Not possible to add an opinion by clicking on CTA**
open the add an opinion window

## Actual Output

**No opinions**
There is no opinion displayed 

**Not possible to add an opinion by clicking on CTA**
Error message described above

**Comment by aHenryJard** [comment]
@nino-filigran I think we should change the error message and say that it's a vocabulary that is missing. The actual message is not explicit enough.

**Comment by nino-filigran** [comment]
Yes that works for me! Something like "The opinions has no value defined in your vocabulary. Please add them first to be able to add opinions"

**Comment by SarahBocognano** [comment]
It's working fine on my side on testing

**Comment by nino-filigran** [comment]
Yes it works @SarahBocognano since we have added back the opinions manually in Testing, therefore the bug does not happen anymore. In essence it's not a bug, but more the fact that the error message is not clear enough to explain to the user that the vocabulary is missing
