### ISSUE TITLE
[Playbook] The drop-down menu doesn't show everything

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6581]
## Description

The drop-down menu in the "manipulate knowledge" component does not display all available statuses, even when using the search function.

## Environment

OCTI 6.0.8

## Reproducible Steps

Before making the repro case, you need to have several status set up on your platform. For example, set 3 - 4 statuses on 5 different entities (otherwise, go directly to the testing platform).

Steps to create the smallest reproducible scenario:
1. Create a playbook and add a "manipulate knowledge" component
2. Try to replace a status -> you won't find all the statuses. Neither by scrolling nor by searching

## Screenshots

![Screenshot 2024-04-04 184323](https://github.com/OpenCTI-Platform/opencti/assets/70956706/4f9c92c6-89d8-487d-a1d6-dcd51200fb3b)

**Comment by marieflorescontact** [comment]
the statuses listed are those used in entities `workflows`. If they exist in the `status template` but are not used, they are not listed. In my opinion, this is not a bug. @jborozco

**Comment by jborozco** [comment]
@marieflorescontact I double checked, actually we don't see all status mapped for exemple in testing, incidents have 4 statuses: 
 
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/ac2a32bb-c72f-4d0d-90c6-ef0381097ccc)

But in the playbook I only see one 
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/b1333fa3-e579-47e1-bbe8-e9943c340606)

**Comment by marieflorescontact** [comment]
you see the status currently in use, not the available statuses. to replace it, it must be in use. The idea is to change the existing status, not to change the mapping.  well I think so...

**Comment by SamuelHassine** [comment]
As we discussed multiple times with @richard-julien, @Jipegien and @Kedae, in the filters / dropdown choices of triggers, dashboard widgets, playbooks, CSV feeds, TAXII collections etc. we should display ALL possible statuses, labels, assignees etc. even if they are not used anywhere in the platform. Users cannot wait for something to be used to be able to set alerting, automation, dashboards or feeds.

If not all statuses are displayed here, this is definitely a bug.

**Comment by lndrtrbn** [comment]
Lhorus6 
> component does not display all available statuses

SamuelHassine
> we should display ALL possible statuses


We need more information to understand what you want. What means "all available statuses" ? All the statuses defined in taxonomies ? All statuses defined in workflows (even if they are not present of any entities for now) ?

The query is already working but we limit the result to 10 items for now. Still there is an other issue that leads to errors. In the dropdown we have multiple times each entities with different statuses. For example if we retake our use case of Incidents @jborozco on testing, first we have:
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/de466891-8a70-44bb-a6e6-8cad581da5a7)
And below in the list we have:
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/fc80e7af-928d-47b4-b48e-fb6869c50f24)

Should we not have all status regrouped in one block for each entities?

**Comment by Jipegien** [comment]
If following status are define for the entityA: new, in progress, closed, blabla -> so "new", "in progress", "closed" and "blabla" must be selectable in filters, regardless of their usage. An automation must be configurable on all possibilities, even if it is not yet used in the platform. Like triggers.

Beware though: there is a subject regarding "users" (used in assignee, participants, author). see @labo-flg about it

**Comment by labo-flg** [comment]
Indeed, as for filters on users, we need to enforce organization segregation : a user should not be able to see users outside of their organization.
I've done some quick changes few months back in `useSearchEntities` so that people can always see themselves (using the `me` object) in these filters, but I've not addressed the whole issue.

**Comment by frapuks** [comment]
@lndrtrbn 
> Should we not have all status regrouped in one block for each entities?

This issue is reported here : #6585 
And this PR fix it : #6707
