### ISSUE TITLE
UI stuck when opening the relationship edition form

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#6601]
## Description

After I open the form to edit a relationship I cannot close it and so cannot interact with the rest of the app. I need to fully refresh the page.

Error in console:
![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/73d75726-6c47-455e-b3fb-07ce693c18e7)

## Environment

1. OS (where OpenCTI server runs): Edge
2. OpenCTI version: 6.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Data > Relationships
2. Click on one to go to its details page
3. Click on the bottom-right button to edit
4. Try to close the panel

## Expected Output

The panel closes

## Actual Output

Stuck with panel opened

**Comment by nino-filigran** [comment]
Cannot reproduce on Demo. Tried both on Edge and Chrome.

**Comment by nino-filigran** [comment]
After testing on Testing, I can reproduce this. Happens on testing (not only on Edge, also on Chrome).

**Comment by JeremyCloarec** [comment]
Same thing is happening when trying to delete the relationship from the edition form: the panel is stuck opened and the relation is not deleted
