### ISSUE TITLE
Change page title when navigating across the platform

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6606]
## Use case

Change page title when navigating across the platform

**Comment by nino-filigran** [comment]
What do you mean by page title? I see the breadcrumbs being updated when navigating a different page so as the URL that reflects the path.

**Comment by SamuelHassine** [comment]
I mean the <title></title> it self, by "OpenCTI - Reports", "OpenCTI - Reports - Name of the entity", etc.

**Comment by ParamConstructor** [comment]
Would it be acceptable to use [react-helmet](https://github.com/nfl/react-helmet) to implement this capability?
