### ISSUE TITLE
Change <html lang="XX"> depending on the selected language

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6607]
## Use case

Change <html lang="XX"> depending on the selected language (currently stuck on lang="en" and hardcoded).

**Comment by nino-filigran** [comment]
What do you mean? Where does this need to be change? In the code? On specific pages or filters?

**Comment by SamuelHassine** [comment]
This is in the HTML code, at the very beginning of the page (currently stuck on lang="en" and hardcoded).

**Comment by ParamConstructor** [comment]
Would it be acceptable to use [react-helmet](https://github.com/nfl/react-helmet) to implement this capability? Seems to support this - example use case - https://stackoverflow.com/questions/64260574/change-language-on-main-index-html-with-reactjs
