### ISSUE TITLE
Identify properly required fields before user starts to input

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6610]
## Use case

Identify properly required fields before user starts to input

**Comment by nino-filigran** [comment]
Duplicate of https://github.com/OpenCTI-Platform/opencti/issues/5454

**Comment by ParamConstructor** [comment]
Implement by/with - Add required fields flagging to majority of platform object types w/ some caveats https://github.com/OpenCTI-Platform/opencti/pull/5877
