### ISSUE TITLE
Using Indicators create Observables can't delete

### ISSUE THREAD

**Issue by L1ulee** [LuatixHQ/opencti#6621]
## Description

when i using Indicators to create Observables.then select all Observables to delete.can't delete Observables.

## Environment

> OS: MacOS Sonama
>
> OpenCTI version: OpenCTI 6.0.9

## Expected Output

**Delete all Observables**

## Actual Output

<img width="1510" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/47224159/8bdccdae-1c4f-4088-9c30-7ad38ee8e9f2">

## Screenshots (optional)
<img width="1510" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/47224159/d7b00655-2573-42bb-a6ab-e440bdb4c0d8">
<img width="1095" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/47224159/9eb8f8e2-e487-46a0-99b6-b8ad29c65711">

**Comment by jborozco** [comment]
Hi @L1ulee I couldn't reproduce your issue, for step 3 and 4, are you still in the context of a workbench ? 

Also to help us reproduce, would it be possible to share with us the file you want to import ?

**Comment by jborozco** [comment]
I'm closing this issue since we can't reproduce it. You can reopen it if you have more information.
