### ISSUE TITLE
Total no of entities incorrect in data//entities

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6623]
## Description
The no of total entities is incorrect in data/entities

## Environment

1. OS (where OpenCTI server runs): debian
2. OpenCTI version: 6.0.5
3. OpenCTI client: web
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Entities, ensure no filter is applied

## Expected Output
The total no of entities is shown in the right top corner

## Actual Output
Not the total amount (lesser)

**Comment by SamuelHassine** [comment]
Hello,

This is very unlikely, in this view, you only have SDOs, so we don't count observables. Can you be more precise?

Kind regards,
Samuel

**Comment by ghost** [comment]
Oh yes, you're right, the observables are not included in the data/entities. Summing data/entites + observables results in the correct no. But it is a bit misleading because if i use a number widget in the dashboard without any filters, the observables are included. 
This is also valid for relations to observables.

**Comment by ghost** [comment]
@SamuelHassine I thought about the relations and double checked it. In data / relations also observables are searchable. But nevertheless it only shows less then the half the amount of relations then in Dashboards (Only relations selected, no filter, no date in dashboard). What could be the cause? References?

**Comment by nino-filigran** [comment]
@iFrozenPhoenix I cannot reproduce any of the behaviors for either entities OR relations. 
To clarify: I've selected in dashboard the widget numbers, selected the perspective knowledge graph (that counts relations) and selected, in the main query, all the relation types. As a result, I end up have 2.28M entities (relations) which exactly corresponds with what I have in data/relationships.

Are you able to find the same result?

This is a screenshot of my dashboard (fitlers are the same in the dash than in data/relationships): 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/a73998ee-fa31-4403-9f2b-b51be840126a)

**Comment by ghost** [comment]
@nino-filigran thank you for your analysis. I've let the query empty, so no relationship type selected. Then I ended with 13.3M in Dashboard and also everything empty in data/relationships I ended with 5.94M.
Rebuilding your query (selecting every possible relationship type I also achieved to get the 5.94M like in data/relationships.
But where is this difference coming from (13.3M to 5.94M)?

**Comment by nino-filigran** [comment]
@iFrozenPhoenix 
Just to ensure I understand your response correctly:
- on a dashboard, selecting the number widget, with a knowledge view representation, selecting the filter "relation type" with all values you get: 5.94M relations
- in data/relations you do have 5.94M relations.
- where is the 13.3M coming from? 
   - Is it a widget number? If so, which representation have you used and which filters have you used?
   - Is it the number that you see in data/relations?
   - Is it the number that you see in data/entities?
   - Is it total of data/entities + Observables?

**Comment by ghost** [comment]
@nino-filigran 
To 1: Correct
To 2: Correct
To 3.1: Yes it is a number widget. I've used the knowledge graph perspective without any filters. You should be able to replicate it if you just remove the filter in your shown query above.
To 3.2: No, I see this number only in the Dashboard with the above query.
To 3.3: No, the number I see in data/entities is 842K
To 3.4: No, obervables count is 1.75M + the 842K would result in 2.59M, which is the number I see in the Dashboard if I select entities in the Dashboard without any filter.

**Comment by nino-filigran** [comment]
@iFrozenPhoenix I hope my answer will not confuse you.
If in a widget number, knowledge view visualisations, no filters selected (your 3.2 query), then it will show: all the stix core + refs. 
While selecting the filter relation type = all relations will only select the stix core.

Therefore, in data/relation, we only display the stix core.

Here a screenshot of the list widget, knwoledge visualisation, no filters selected (your 3.2 query).
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/f640c0e7-8345-4b74-9dc6-4df4e7a76b46)

**Comment by ghost** [comment]
@nino-filigran with refs you mean relations of external references?

**Comment by nino-filigran** [comment]
I mean relations that are not pure SRO, such as [in STIX ](https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070606). For instance you can see in the above screenshot:
- external refs
- labels...

**Comment by nino-filigran** [comment]
@iFrozenPhoenix does this now make sense? If so, are you ok if I close the bug, since it's not a bug, but rather a question of filters? More info on the refs (nested objects) can be found here by the way: https://docs.opencti.io/latest/usage/nested/

Let me know your thoughts.

**Comment by ghost** [comment]
@nino-filigran yes, I understand it now better where the numbers are coming from. Thanks for your explanations.
