### ISSUE TITLE
Names of Attack Patterns and Intrusion Sets are replaced by connectors

### ISSUE THREAD

**Issue by ghost** [LuatixHQ/opencti#6630]
## Description
If a connector creates a entity that already exists it replaces the entities name with the name specified in the connector.
E.g. if I have a Intrusion Set APT28 with Alias Fancy Bear and the connector creates a Intrusion Set Fancy Bear the existing Intrusion Set is used, as expected, but it replaces the Intrusion Sets name and defines the "old name" as an Alias. This leads by the way also to a dataset that is normally not possible to create (Name is equal to one of the aliases).

This problem also occurs e.g. with attack patterns. If I'm correct they are matched by the external ID, not by the name, but if I have an Attack Pattern e.g. Phishing and an Connector has the Number as It's name, the name of the existing Attack Pattern is replaced with the Number and the "old name" is defined as an Alias.

## Environment

1. OS (where OpenCTI server runs): debian
2. OpenCTI version: 6.0.5
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an entity with a name and an alias
2. Create a entity with the alias as the name

## Expected Output
Unchanged name.
I expect that if an entity already exists and the update flag is not set, data are only appended, never replaced.

## Actual Output
Changed name

## Additional information
Connectors have all a lower confidence level then the updated entities.

**Comment by nino-filigran** [comment]
@iFrozenPhoenix thanks for your ticket. Is that the case with any connector or do you have a specific one in mind?

Also, I'm not sure to fully grasp the problem: if entity A exists with alias B, and entity C is created with name B, then the new name of entity A will be C. Therefore, all the knowledge remains on Entity A, regardless of it's "name". Additionally, you can still view the old name in the alias and the search should make it you find the entity.

**Comment by nino-filigran** [comment]
Please see a video capture of the current deduplication process, which behaves exactly like you describe (my original entity changes name, and its old name appears in alias). This 
video (https://github.com/OpenCTI-Platform/opencti/assets/148041607/20151059-cf5b-42e9-b960-52e997a6ff9f)
 has been captured on the demo public environment:

**Comment by ghost** [comment]
@nino-filigran Yes It's exactly like in the video. The Problem is that there are many places in the system where the names are shown and used as the only value to identify a certain entity, e.g. in Attack Pattern where the name is used in the Matrix, see Screenshot below.  The matrix nearly loses it's sense with only the numbers.
Further a specific naming scheme for Threat Actors cannot be enforced anymore. E.g. if I want to use Crowdstrikes naming scheme (Bear, Chomilla, Panda, Spider, ...) and I change all names to this scheme that can still not be enforced due to the fact that the name changes on update. This is especially a problem in the list views and in report (PDFs) exports where the aliases are not shown
![Screenshot from 2024-04-09 09-48-53](https://github.com/OpenCTI-Platform/opencti/assets/36128722/3b4edece-9a16-4d13-9ea4-d1cf2067c0d3)

**Comment by nino-filigran** [comment]
Thanks for the detailed explanation, it helps putting things in perspective.
What I found odd is that if your entity A is already created, with a confidence level at 100, if a connector imports the "same" data (at least with the alias matching the name), it should not update (or as we call it, upsert) the original one.

In my video, I had the same confidence level, therefore, I could upsert. So if everything works as it should do, if you assign a lower confidence level to your connectors, they won't upsert data that have a higher confidence level than them. The only thing that might happen is that some missing data in your original entity might be updated if the new entity from the connector with a lower confidence level has them. But they will not replace existing data.

If you do not see this behavior on your platform (a connector with a lower confidence level should not be able to update an existing entity), then we can consider this ticket as a bug. Otherwise, we'll take it as a feature, since it works as "expected", aiming to help users identifying better their entities, by potentially displaying both fields or choosing a field to display.

**Comment by ghost** [comment]
Which confidence Level is counting for the upsert of the connector? The one I set for the connector as an environment variable, or the one of the connectors account?

**Comment by nino-filigran** [comment]
The one one that you set corresponding to the user of the connector, not the environnement one.

**Comment by x86NOP** [comment]
Worth mentioning, it appears env `CONNECTOR_CONFIDENCE_LEVEL` no longer does anything in the python library according to the link below.  I can't find documentation that mentions this, but it seems they've moved the logic away from the connector and instead rely on the "max" value set in the UI, hence @nino-filigran's response.

https://github.com/OpenCTI-Platform/client-python/blob/61362d218cac3a2509b6c5e1292af5aa8bd9475b/pycti/connector/opencti_connector_helper.py#L724

Side note: I'm writing our first connector and working on documentation I'll submit/propose to be put here: https://docs.opencti.io/6.0.X/development/python/.  Unfortunately, many of the existing connectors and examples use various forms of old/deprecated/incorrect conventions, constructors, and even Python functions so they're not a good source.  Pretty much all of these no longer work in 6.0.x: https://github.com/OpenCTI-Platform/client-python/tree/master/examples but I'll take all of this up in a separate issue to not hijack this one.

**Comment by ghost** [comment]
@nino-filigran, ok I tested it now over night and it seems to be solved by using a user with a lower confidence level.

**Comment by nino-filigran** [comment]
Glad to hear it :)
