### ISSUE TITLE
Missing translations on Profil page

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#6646]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/6dbb888f-f870-40f3-afdf-396d23156b42)

"User experience" and "Unit system" seems not translated

## Environment

1. OS (where OpenCTI server runs): Edge
2. OpenCTI version: 6.0.9
3. OpenCTI client: frontend
4. Other environment details:

**Comment by jborozco** [comment]
@lndrtrbn can you share the link of the page ? I can't find this screen

**Comment by lndrtrbn** [comment]
/dashboard/profile/me
