### ISSUE TITLE
[Workbench] imported observables appear as 'no' in 'already in platform' in the workbench.

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#6652]
## Description

After validating a workbench with certain observables (registry keys), the observables are indeed created and present in the container, but when returning to the workbench they are displayed as 'no' in 'already in platform'.

## Environment

OpenCTI version: 6.0.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Create a workbench with registry keys inside, then validate,
2. Once the container has been created with the observables inside, return to the workbench,
3. The observables are displayed as 'no' in 'already in platform'. 

## Expected Output

The observables are created and appear as existing in the platform when you return to the workbench.

## Actual Output

The observables appear to be absent from the platform, even though they have just been imported.

## Additional information

Repro case in testing: "Nico_test.txt"

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/e89a6841-a090-4f7d-a9d1-ab49d5243ac7)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/bfae6892-0cc9-4583-b872-16df225c719a)

**Comment by nino-filigran** [comment]
Reproduced on demo. Even after having imported the workbench, validated it, ensure that the observables are in the platform, deleting the workbench, re-importing the file to trigger a new upload & workbench generation, when entering in the workbench, these 2 observables are not found even though they exist.
