### ISSUE TITLE
Most used filters are at the end of the list instead of beginning

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6655]
## Description

Most used filters are at the end of the list instead of beginning (at least in French):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/e593fb8e-a7a3-45e0-9785-3405be7c2cca)

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/7e4b6e80-2c02-4496-a259-38a4d56fc5cc)

**Comment by jborozco** [comment]
@SamuelHassine Do you have a list of the most used filters to display ?

**Comment by Archidoit** [comment]
@jborozco The most used filters are the one existing for every entity types of the screen (so they depends on the screen).
Have been able to reproduce (bug is only existing in french)
