### ISSUE TITLE
Autocomplete in filters return odd results

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6656]
## Description

In French:

Go in dashboard => entities perspective => filters.

Start and type "concerne":

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/e1c96947-de14-4529-89ba-88b62a53f0db)

Why all those options are displayed?

**Comment by nino-filigran** [comment]
Reproduced on demo

**Comment by Kedae** [comment]
Still reproduced @nino-filigran ?

**Comment by nino-filigran** [comment]
No we can close!
