### ISSUE TITLE
When having a trigger covering URLs or an Indicator genreated from an URL Observable, URL is clickable in the notification or the description

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6657]
## Description

When having a trigger covering URLs, URL is clickable in the notification

This can be malicious!

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/d450e003-5704-4cfc-990d-ab63e8b37f3e)

=> In the notification content, continue to parse markdown, but put an exception on URL automatic parsing.

**Comment by nino-filigran** [comment]
Even though there's a confirmation pop up that appears when trying to click on the URL, it seems indeed safer to avoid making it clickable and instead let the user copy/pasting the url if the user wishes to navigate to the url.

Pop up: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/4661914e-9b0f-4807-b0be-505f381cc6e0)

**Comment by rguignard** [comment]
Same security issue with "default descriptions" associated to indicators created from the option "Create an indicator from this observable".
Example: Create an observable of type "Domain" with a value like "www.mydomain.com" and select "Create an indicator from this observable". On the newly created indicator, the value of the domain is clickable in the description.

https://github.com/OpenCTI-Platform/opencti/blob/5a85a823b5e616e1fd87226897a5946ab181aca9/opencti-platform/opencti-graphql/src/domain/stixCyberObservable.js#L136

I think it would be better to delete this default description.
