### ISSUE TITLE
Free lasso selection using right mouse button is not working anymore in graphs

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6659]
## Description

1. Go to a report
2. Go to knowledge
3. Press right button and do a free lasso selection

=> Nothing is selected

**Comment by nino-filigran** [comment]
Reproduced on demo

**Comment by Kedae** [comment]
Not sure to get the problem ?

Right click is Relation Selection -> Working on demo
Lasso selection is from the Toolbar -> Working on demo

**Comment by nino-filigran** [comment]
The right click to create a lasso doe not work indeed, but it's not a bug, it has not been implemented. Right click is only used to create relations.
https://github.com/OpenCTI-Platform/opencti/assets/148041607/a8294880-2029-40e1-aa26-f931e68e0c69
