### ISSUE TITLE
Linked RFI is not displayed in Report's entities panel

### ISSUE THREAD

**Issue by debelyoo** [LuatixHQ/opencti#6666]
## Description

I'm linking a report to a request for information case. In the "entities" panel of the RFI I can see the report, but in the "entities" panel of the report I don't see the RFI.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04
2. OpenCTI version: 6.0.9
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Create a RFI case
3. Link the report to the RFI case
4. Check if the report is visible in the "entities" panel of the RFI (OK)
5. Check if the RFI is visible in the "entities" panel of the report (Not OK) 

## Expected Output

RFI visible in the "entities" panel of the report.

## Actual Output

RFI not visible in the "entities" panel of the report.

**Comment by nino-filigran** [comment]
Reproduced on Demo. To link report and RFI, I've been into case/entities and selected the report. When going to the report, the case does not appear, however in the entity tab, the count of entities is equal to 1, as if the case is here but not displayed. The case is also not displayed in the knowledge graph.

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/e74ac0f2-5b6d-4e2f-a075-01ba6839e30f)

**Comment by Archidoit** [comment]
@nino-filigran 
If you add a report in 'entities' of a case RFI, the case RFI contains the report.
But the report does not necessarily contains the case RFI, so no case RFI in 'entities' of a report. Isn't it the number that is incorrect?

**Comment by nino-filigran** [comment]
You are fully right my bad. For the record, I've tried the other way around (create a report, go to entity and linked to a case): the case appears in the list of entities. But If go to the corresponding case, no sign of my report. However, the entity count in the case is also 1 and not 0. 

To conclude: adding a report in case means that the case will contain the report. Contains, unless I'm wrong, is a ref and not a relation. Hence the fact that the case do not appear in the report (and the other way around if doing the opposite action). For me, we should then indeed edit the count to have a 0 when no entity are present in the entity list as you have explained @Archidoit .

@Jipegien for info
