### ISSUE TITLE
ExportReportPDF connector needs to have a list of possible entity types 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6667]
## Use case

At the moment, on every entity you can in theroy download a PDF. But lots of entity types are not supported by the connector. the goal of the feature is to have a list of entities for which we can filter on, in order to display (or not) the download pdf. 

List of supported entities: 
report
case incidents
case RFI
case RFT
Intrusion set
Threat Actor Group
Threat Actor individual 

Any other entities will throw an error currently. Therefore, the option should be disabled only for the other entities. Additionally we need to ensure that we do perform a download on one or more entity at the time. 

cc @ValentinBouzinFiligran

**Comment by SamuelHassine** [comment]
Closing this in favor of https://github.com/OpenCTI-Platform/connectors/issues/775.
