### ISSUE TITLE
ObservedData name not displaying correctly in container list for an object

### ISSUE THREAD

**Issue by sweet-mentat** [LuatixHQ/opencti#6687]
## Description

When I first view the dashboard for an observable that is in one or more ObservedData objects, I can see the list of ObservedData objects in the section labeled "LATEST CONTAINERS ABOUT THE OBJECT." No names are displayed. When I click on one of the ObservedData objects, then click back to go back to the observable dashboard, the ObservedData object's name is now displayed. When I click on another ObservedData object, then click back, then its name is now displayed, but the previous ObservedData object's name that I had clicked on is not displayed. 

## Environment

1. OS (where OpenCTI server runs): Docker image
2. OpenCTI version: OpenCTI 6.0.9
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create two observables
2. create an observedData object that contains the first observable from step one.
3. create another observedData object that contains both observables from step one.
4. view the first observable from step one by going to its dashboard. look at the container list, and you should see both observedData objects with no names.

## Expected Output

Container list should show observedData names.

**Comment by jborozco** [comment]
Reproducible here https://demo.octi.filigran.io/dashboard/observations/observables/a68e70ec-d0ab-452e-b4b0-a02b756567fb

The 2nd observed data name doesn't show up:
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/15b9ea3b-0c7d-4a8b-a945-555ea97a8f90)
