### ISSUE TITLE
Getting MISSING_REFERENCE_ERROR when creating relationships, even if "missing" object is in the same STIX bundle

### ISSUE THREAD

**Issue by sweet-mentat** [LuatixHQ/opencti#6688]
## Description

When I submit a STIX bundle for ingestion, if I have a relationship that references two objects, and both objects are not already in OpenCTI, then I will get a MISSING_REFERENCE_ERROR. This occurs even if the objects are in the same bundle as the relationship. This happens regardless if this is through pyct using functions in pycti/utils/opencti_stix2.py, or using the FileImport connector through the UI, or using CSV mapper. 
When writing connectors, I have been able to work around this by creating multiple bundles, one with objects and another with the relationships/reports/containers that reference those objects. I then stage when I import them, ensuring I import them in the correct order so the objects will be in OpenCTI by the time I import the relationships or other objects that reference other objects. 
This becomes problemsome when importing through the UI, especially when using the CSV Mapper to import relationships. It looks like I will need to import the same file twice - once to import the objects, and another to import the relationships.

I think that I should not get an error if the object is in the same bundle when importing a relationship.

By the way, thank you for fixing the CSV mapper's ability to import relationships! It works great when the objects are already in OpenCTI!

## Environment

1. OS (where OpenCTI server runs): Docker image
2. OpenCTI version: OpenCTI 6.0.9, but this has been around forever.
3. OpenCTI client: frontend and python

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Use CSV mapper to import a csv with relationships between two objects. Make sure those objects are not already in OpenCTI.

Here is an error from trying to import relationships with CSV Mapper:
{
                "category": "APP",
                "errors": [{
                    "attributes": {
                        "genre": "BUSINESS",
                        "http_status": 404,
                        "input": {
                            "confidence": 100,
                            "created": null,
                            "createdBy": null,
                            "description": null,
                            "externalReferences": [],
                            "fromId": "x509-certificate--ea95eea3-4e8a-58fc-xxxx-796468e391d2",
                            "killChainPhases": [],
                            "lang": null,
                            "modified": null,
                            "objectLabel": [],
                            "objectMarking": [],
                            "objectOrganization": null,
                            "relationship_type": "related-to",
                            "revoked": null,
                            "start_time": "2022-11-15T00:00:00.000Z",
                            "stix_id": "relationship--4304d0b5-f82f-45d9-xxxx-9e13f92cf76a",
                            "stop_time": "2024-02-13T00:00:00.000Z",
                            "toId": "ipv4-addr--36b7dac4-e17e-5604-xxxx-8429ea9bf0b3",
                            "update": true
                        },
                        "unresolvedIds": ["x509-certificate--ea95eea3-4e8a-58fc-xxxx-796468e391d2"]
                    },
                    "message": "Element(s) not found",
                    "name": "MISSING_REFERENCE_ERROR",
                    "stack": "MISSING_REFERENCE_ERROR: Element(s) not found\n at error (/opt/opencti/build/src/config/errors.js:8:10)\n at MissingReferenceError (/opt/opencti/build/src/config/errors.js:117:48)\n at inputResolveRefsFn (/opt/opencti/build/src/database/middleware.js:708:13)\n at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2742:25)\n at createRelation (/opt/opencti/build/src/database/middleware.js:2929:16)\n at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:91:19)"
                }],
                "inner_relation_creation": 0,
                "level": "warn",
                "message": "Element(s) not found",
                "operation": "StixCoreRelationshipAdd",
                "operation_query": "mutation StixCoreRelationshipAdd($input:StixCoreRelationshipAddInput!){stixCoreRelationshipAdd(input:$input){id standard_id entity_type parent_types}}",
                "size": 542,
                "time": 8,
                "timestamp": "2024-04-12T16:06:37.100Z",
                "type": "WRITE_ERROR",
                "user": {
                    "applicant_id": "<applicant_id>",
                    "call_retry_number": "3",
                    "group_ids": ["d333248e-2560-42a2-xxxx-5a0c4ecc75e7", "c5b3679e-311c-45f5-xxxx-14d2c3a08333", "efd176e8-bfa6-4ef0-xxxx-0c552c71b683", "f8d5a3b6-93e7-4aa7-xxxx-6ade5edc1c0e"],
                    "ip": "::ffff:10.42.9.115",
                    "organization_ids": ["<org_id>"],
                    "socket": "query",
                    "user_id": "<user_id>",
                    "user_metadata": {}
                },
                "version": "6.0.9"
            }

**Comment by nino-filigran** [comment]
@sweet-mentat maybe I misunderstood your ticket, but I've not been able to reproduce. This is what I did: 
- create a CSV mapper where I listed a malware & and infra
- added a relation in the CSV mapper between malware & infra (targets)
- created a CSV only containing one line: Col A is my malware, Col B is the malware family, Col C is the infra name. None of them exists in my DB.


Did I miss one point? If not, could you maybe share the CSV that you're trying to import so that I can see if I have issues on my side?

**Comment by sweet-mentat** [comment]
Hmmm it looks like it's a different problem than what I thought. The problem is with the X509-Certificate. When I try to import an X509-Certificate with only a SHA-1 hash using the CSV mapper, it fails to find the existing certificate in OpenCTI (the SHA-1 is already associated to an existing certificate) and it fails to create a new X509-Certificate object. Do I need to create a different ticket, since this is not the problem I was trying to describe? I can't seem to reproduce the problem I initially described either. :/

**Comment by nino-filigran** [comment]
Sorry for my late reply. Yes if you don't mind creating a new one it would be great, so that it'll be clear what the problem is and what to solve, with clean comments and so on. I'm closing this one in the menatime so that we can keep track on what needs to be worked on/what does not need.
