### ISSUE TITLE
Empty Content CSV Feed

### ISSUE THREAD

**Issue by argithubtogo** [LuatixHQ/opencti#6689]
## Description

There is no content when I created a CSV sharing feed. I tried to create another sharing feed in TAXII and no issue found. Similar to issue #5301 
## Environment

OS (where OpenCTI server runs): Ubuntu 20.0.4.1 LTS
OpenCTI version: e.g. OpenCTI 6.0.9
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Create CSV feed with main observation - IPv4 address AND Author = AbuseIPDB

## Expected Output
CSV feed

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/d7ae0ef0-7e4b-45ea-a294-f41c68df096d)
![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/16d0f8c8-c74c-4ab6-b6dc-2a22812ac3a6)

![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/38f2afdf-d1e2-456e-9416-7fb53783bea9)

![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/abedc3e2-71d5-4168-afe2-ab1b40aff392)

**Comment by nino-filigran** [comment]
@argithubtogo I have tested on my side and things seems to work properly. To be clear, when creating a CSV feed, it does not read all the existing indicators in the platform, but will fill the feeds with the one being created. Did you try to create one, with the main observable type & authors matching your filters and checked in the CSV feed after?

**Comment by argithubtogo** [comment]
seems it's due to the rolling time instead
![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/42e12869-fdf5-442e-bfbf-f27b2017fc1b)
![image](https://github.com/OpenCTI-Platform/opencti/assets/144109155/a472ea85-41d1-49b0-b916-2a8349052f18)
