### ISSUE TITLE
IP Address Enrichment Doesnt Work (IPInfo) -

### ISSUE THREAD

**Issue by dizzywombat** [LuatixHQ/opencti#6691]
## Description

IPInfo doesnt work enriching IPv4 Observables. Error message after running the IPinfo plugin is consitently "Country not Found , an error occurred ...."

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Observable
2. Click any IPv4 address
3. Click enrichment and select IPInfo

## Expected Output

IPInfo to enrich the IPv4 address

## Actual Output

Clicking enchrichment on an ipv4 observable produces a country not found error.

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/114467742/2abfd26f-ab1d-442f-a0e5-ea691dd98565)

**Comment by nino-filigran** [comment]
@dizzywombat on our demo instance everything seems to work well with the connector. Which version of platform are you on?
Do you have somes logs to share so that we could potentially help you there?

**Comment by dizzywombat** [comment]
No problem, Im running 6.0.9. If its running correctly in the demo instance it must be an issue locally to me. Apologies. I experienced it consistently after moving from 5.x.x.
