### ISSUE TITLE
Loader keeps turning in relationship creation from entity when Reverse relation

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6696]
## Reproducible Steps
- Go to the knowledge graph of a report
- Add a malware and a software
- Select the malware and the software
- Click on 'create a nested relationship' from the toolbar
- Click on 'reverse' in the relationship creation form
- Close the form
- Click on 'create a relationship' from the toolbar
- Click on 'reverse'
- The loading keeps turning

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/2d90565e-6ce1-43c2-82b3-2c220a43b46f)

**Comment by jborozco** [comment]
Reproducible here https://testing.octi.staging.filigran.io/dashboard/analyses/reports/1a4842fc-3a40-4370-afd0-b1310d01234b/knowledge/graph
