### ISSUE TITLE
Impossible to search a user using its email address in Security => Users

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6717]
## Description

1. GO to Security => Users
2. Try to search a user using its email address (partial or full)

=> Nothing is returned

Hint: should be just the field user_email to add in the search attributes on the backend side.

**Comment by jborozco** [comment]
Ex: if you search "fili" in https://testing.octi.staging.filigran.io/dashboard/settings/accesses/users?searchTerm=fili&sortBy=name&orderAsc=true

You should see the list of all users with a filigran email
