### ISSUE TITLE
Update list of TTPs to the latest

### ISSUE THREAD

**Issue by C0nnexor** [LuatixHQ/opencti#6720]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

In the version of OpenCTI I'm running I don't see all the TTPs available. What can I do to "update" the list?

## Environment

1. OS (where OpenCTI server runs): Docker - portainer.io 2.11.1
2. OpenCTI version: 5.11.8
3. OpenCTI client: Python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. browse to Techniques

**Comment by ghost** [comment]
@C0nnexor you must use the mitre connector https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/mitre.
There is a sample docker-config in this dir. Make sure you replace the env vars with your actual values.

**Comment by C0nnexor** [comment]
@iFrozenPhoenix thanks for this. I proceeded by adding a container (I'm using portainer.io) point to the latest Docker image available here: https://hub.docker.com/r/opencti/connector-mitre. However it seems that something more needs to be done because in the logs I see "An URL must be set" but in the `connector.py` file of the repository you linked me I don't see where that error may come from.

What am I missing? I'm really new to OpenCTI


Thank you a lot!

**Comment by ghost** [comment]
@C0nnexor Just adding the image ist Not enough, you must also set the correct environment variables for the container and fill it with your actual values.
In the link mentioned above you see a docker compose example. As far as I know portainer can deploy docker compose files.

**Comment by C0nnexor** [comment]
Thank you, @iFrozenPhoenix , it seems that I successfully created a container to update the MITRE TTPs dataset

![image](https://github.com/OpenCTI-Platform/opencti/assets/153841098/8f55d8bd-00a9-4487-929d-85bd0a600a33)

However I'm still not able to see the imported data in the `Techniques` section of the OpenCTI panel. I'm pretty sure I set the right HTTP endpoint and stuff, since I can see what is provided above. Moreover, I copied these settings from other containers'

How may I proceed?

Thank you so much again

**Comment by ghost** [comment]
@C0nnexor happy to hear this.
Are you logged in as admin into the console?
Have you used the admin token for the connector?
Can you please post a screenshot of the errors of the import process (click the 100).

**Comment by C0nnexor** [comment]
I'm logged in as an administrator on both Portainer and the OpenCTI web client. I'm using the admin token stored in this env var: `${OPENCTI_ADMIN_TOKEN}`. This is also valid for all the other containers.

I see the connector progressing in the window which the screenshot above was taken from. So I guess the two are somehow connected?


Here follow a sample of the 100 errors (they are all almost the same):
![image](https://github.com/OpenCTI-Platform/opencti/assets/153841098/af769729-0f03-4d88-8c5d-d798c7e51b52)

What can I do?

**Comment by ghost** [comment]
@C0nnexor can you confirm that you use the same tag for the platform and the connector?
If not, please use the same tag for both (the upper).

**Comment by C0nnexor** [comment]
@iFrozenPhoenix what do you mean by "tag"? May you explain it to me, please?

Thank you in advance

**Comment by ghost** [comment]
@C0nnexor I mean the tag of the container (version). This is the last part in the compose files image (after the :)

**Comment by C0nnexor** [comment]
@iFrozenPhoenix so I see these two:
- `opencti/platform:5.11.8@sha256:d67946d2a4c3186b28dcf93dae9169f7097690b71456bb5a41e1a906bca080d3`
- `opencti/connector-mitre:6.0.10@sha256:cea41e8aebe7fc132fed506cedb229b952a234a68e9eeb3016bcec550e27746a`

is it really impossible to use opencti 5.11 with the latest version of the connector? I guess I should update opencti to the latest then

**Comment by C0nnexor** [comment]
@iFrozenPhoenix So I updated all the services to 6.0.2, I still cannot see imported TTPs even if the following is provided:

![image](https://github.com/OpenCTI-Platform/opencti/assets/153841098/487ec6d4-89cd-4563-8169-b92d79e9dd4b)


If I browse to Techniques -> Attack patterns, I see a total of 1.53K so there are no difference with a previous situation

What can I do?

Thank you again

**Comment by ghost** [comment]
@C0nnexor what do you mean with you see a total of 1.53k but can't access it? Can you provide a screenshot of what you see when you go to attack patterns?

1.53k is the current total no of attack patterns that I also have, so at least we can assume that the import was successful.

**Comment by C0nnexor** [comment]
Let me elaborate on this.

As far as I understood, I imported 25078 entities, and I understand this by looking at the screenshot reported in the previous message (i.e.: number of operations completed). Now I'm wondering where I'm expected to see all those imported entities. Plus, where can I find all the newly added TTPs?

The current Attack patterns available are the ones that were manually created

**Comment by ghost** [comment]
Well, the 25k are not solely entities but also relations and references.

The mitre connector mainly imports attack patterns, a few intrusion sets and a few campaigns.

So you can use the left sidebar to access these entities.

**Comment by C0nnexor** [comment]
I see, but still I cannot find certain TTPs like [T0074](https://disarmframework.herokuapp.com/technique/68/view)

![image](https://github.com/OpenCTI-Platform/opencti/assets/153841098/9a4bbe32-8f16-4da2-a124-d359c630cec6)

but I can find others, like T0800:

![image](https://github.com/OpenCTI-Platform/opencti/assets/153841098/173c1f2e-93fc-4f3b-b302-211e07c69a9f)

What can I do to have the latest TTPs available?

Thanks a million for your time and availability!!!

**Comment by iFrozenPhoenix** [comment]
Disarm is a whole other thing than mitre attack. You have to look if there is a connector for it. But concerning this I have no idea.

**Comment by iFrozenPhoenix** [comment]
@C0nnexor if you are interested we can talk outside this issue. I think it's more a case of implementation than an issue anymore.

**Comment by C0nnexor** [comment]
@iFrozenPhoenix I do thank you so much, I finally was able to have everything working just right

That's great to have such a community!

I wish you all the best!
