### ISSUE TITLE
Dashboard time filter not properly taken into account depending on view

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6732]
## Description

Some views do not take into account the date set in the widget when filtering on time. Let me explain:

When you set up a widget, the "Date attribute" used by default is "created_at". This parameter defines the date taken into account when displaying the data. However, for certain views (like donuts, for example), the date is not taken into account by the time filter. It seems that the time filter takes the "created_at" into account, whatever the configuration.

## Environment

OCTI 6.0.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create two identical widget but one in list view and the other in donuts view. Here are the parameters:
    - Perspective Knowledge graph
    - Filters : "Source type: Intrusion set" AND " target type: tool"
    - Parameter : Date attribute = "start_time" and Attribute = "entity"
2. Create a relation between an intrusion set and a tool with "start time = [two days ago]"
3. Set your dashboard to "relative time = Last 7 days" (at the top of the dashboard) -> you should see your newly created relationship on both widgets.
4. Now change the relative time to "Last 24 hours" -> you should no longer see your relationships because the "start_time" is more than 24 hours old. On the list widget, the relationship has disappeared, but not on the donuts.

You can find the dashboard "Test issue 6732" in the testing platform with the two widgets already configured.

**Comment by jborozco** [comment]
Link to the dashboard: https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/63ad1dda-aeb5-4a4b-9df3-2691dca9154c
