### ISSUE TITLE
[Playbook] Rename Filter knowledge to Match to reflect his real behavior

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#6739]
## Description

I am trying to create a playbook to automatically add a label to the CVE contained in a report.
While using a Filter knowledge, the following action will be executed on all the entities no matter the filter
Workaround with Reduce knowledge works fine

reviewed with 

## Environment

cloud demo environment

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a new event
2. create a listener
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/5925ce7b-7ccd-4da6-b607-d02250584d0a)
3. apply predefined rule
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/393b3f21-85eb-4366-85b6-abcca6b3bc51)
4. create filter knowledge
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/c3a25796-eecc-43bd-a7c9-4172e2aaa752)
5. Manipulate knowledge
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/90415015-0e9e-4ad7-a525-76d748729319)
6. send for ingestion

Overall playbook:
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/94e12d07-cc60-4ae5-ad29-cc598907de29)

## Expected Output

label applied only to the vulnerabilities

## Actual Output
While creating/editing a report, the label is applied to all the entities (not only the vulnerabilities):
![image](https://github.com/OpenCTI-Platform/connectors/assets/166409476/61492b2d-efc2-494f-a822-707cf6cade81)

**Comment by Jipegien** [comment]
Seems there is a bug on the Filter Knowledge component that does not filter anything.

Repro case in testing: automation TEST_JP_ADD_LABEL_CVE_IN_CONTAINER

**Comment by richard-julien** [comment]
If you want to filter your need to use **Reduce knowledge**

![image](https://github.com/OpenCTI-Platform/opencti/assets/285555/f5368f74-81e0-4afe-9ad5-991b26b9c937)

The filter is in fact currently just a gate to let pass or not if the filter match or not.
I will rename the filter component to "match" and change the description to reflect this.
