### ISSUE TITLE
Be able to filter and sort on Narratives

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6741]
## Use case

We need to be able to filter and sort the list of Narratives to find information efficiently. 

## Proposed Solution

At least add date columns, label column, and filter functionality (basically, do the same as for all other entity lists).

### Currently

![Screenshot 2024-04-18 100010](https://github.com/OpenCTI-Platform/opencti/assets/70956706/09f8153f-0c1e-47b8-95ed-cfcced0daaad)

### What we want

![Screenshot 2024-04-18 100025](https://github.com/OpenCTI-Platform/opencti/assets/70956706/5064ce06-bac1-449d-9d9e-2eb04a4add1a)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by Gwendoline-FAVRE-FELIX** [comment]
Reopening of the issue to add the option of switching to a view with the sub-narratives.
