### ISSUE TITLE
Feedback/attack-pattern simple export issue

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6746]
Go to a feedback overview. Generate a csv simple export (ie only the entity).
You are redirected to (instead of the Data tab) : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/a4bebc57-451e-47ca-b8a8-cb5b19f04439)

And if you go to the Data tab, the generated file contains both the feedback and its related entities : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/a2fa2258-996b-4f41-8f48-4acd389ad13a)
EDIT: same on Report, Notes, Rfi, Rft,...

**Comment by Archidoit** [comment]
redirection problem after export also existing when exporting a task

**Comment by SouadHadjiat** [comment]
what is the status of this issue ?

**Comment by frapuks** [comment]
This PR is already merged : https://github.com/OpenCTI-Platform/opencti/pull/6751#event-12559685317
And fix this bug, right or not ?
