### ISSUE TITLE
CSV feeds screen broken after deleting the CSV mapper

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6757]
## Description

On testing instance: https://testing.octi.staging.filigran.io/dashboard/data/ingestion/csv.

I think, given the errors, is the CSV mapper associated to one of the CSV feed has been deleted.

**Comment by labo-flg** [comment]
Cascade delete seems to be the issue.

What do we want ?

We can prevent and throw an error when trying to delete a mapper that has ingester(s) using it ; meaning the user has to delete or reconfigure all ingesters before being able to delete the mapper.

OR

We cascade delete : when deleting a mapper all ingesters using it are deleted also. IMO this means we should add a confirmation popup when deleting the mapper, warning that "N ingesters are currently using it, are you sure?".

**Comment by nino-filigran** [comment]
The second option would not prevent the error to happen again right? I mean potentially a user could confirm both pop up and we would still be in the same situation, right? If so, I'm more in favor of the first solution.

**Comment by labo-flg** [comment]
The second option would prevent the error because we would delete also all ingesters using this mapper, so the ingestion/feed page would not crash.

**Comment by nino-filigran** [comment]
I think I would still prefer the first option, because if the user has a CSV feed ingester using the specific CSV mapper, the user might delete it which would cause the CSV feed to not work anymore. And I guess we're not letting the user know that something is wrong with a CSV feed.

**Comment by labo-flg** [comment]
Ok, agreed. 
And we note that managing ingesters and managing csv mappers are under different capabilities, which can be tricky in the equation.

Let's throw an error when deleting a mapper used by one or more ingesters. If we need a more complex approach, let's discuss it in time.
