### ISSUE TITLE
[Workbench] Campaign object unrecognized in relationships

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6758]
## Description

In a workbench, when adding relationships with campaign objects, the campaign is not recognized in the relationships(marked "unknown").

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a workbench
2. Add an intrusion set (whether or not it exists in the platform is of no importance, same result)
3. Add a campaign (whether or not it exists in the platform is of no importance, same result)
4. Click on the intrusion set to add "context" (to create relation)
5. In the "attributed to (reversed)" field, add the campaign name that you have in your workbench
6. Select the "campaign" type
7. Then validate

![Screenshot 2024-04-19 104502](https://github.com/OpenCTI-Platform/opencti/assets/70956706/d87f0152-9805-419a-b90d-6042c4c5dc9b)

-> Go to the "relationship" window, you will see "unknown"

![Screenshot 2024-04-19 104513](https://github.com/OpenCTI-Platform/opencti/assets/70956706/c99ea2e2-49e0-43e3-a134-4782aa2fa06e)

## Expected Output

I expect my campaign to be well identified in my relationship

## Additional information

If you don't choose the "campaign" type (step 6 of the repro case), the problem doesn't appear, i.e. the campaign is correctly identified in my relationship.

**Comment by nino-filigran** [comment]
After double checking with Lucas, we could reproduce the case.
