### ISSUE TITLE
'sighting' export from an entity exports all the sightings of the platform

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6761]
## Description

'sighting' export from an entity exports all the sightings of the platform

## Reproducible Steps
Go to an administrative area. Go to the 'sighting' tab.
Add a sighting.
Export the sighting list in csv.
The csv file contains all the sightings of the platform.

## Expected behavior
The csv file should only contains the sightings of the administrative area.

**Comment by jborozco** [comment]
Reproducible here https://testing.octi.staging.filigran.io/dashboard/locations/administrative_areas/906dacd5-d95f-44d1-a3a7-48e6bff0bb3d/sightings
