### ISSUE TITLE
Relationships of observables are not correctly displayed

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6765]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/258f0784-9eef-4582-a096-174b29ed7c18)

Example: https://filigran.octi.filigran.io/dashboard/observations/observables/de0e9396-d173-4c5f-81e9-1aa8643cf021/knowledge/relations/4c4ec39e-fbe4-4a22-be9a-dab6b1bbb99f

**Comment by jborozco** [comment]
@SamuelHassine Just to clarify, should we display these boxes differently or just delete them ?

**Comment by SamuelHassine** [comment]
It was not there before, I think this is side effect of the react router migration. Should be removed, it is in the knowledge part.
