### ISSUE TITLE
Translation in french for light theme is not correct

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6768]
## Description

Translation in french for light theme is not correct: Theme léger (should be: Theme clair).

**Comment by jborozco** [comment]
The wording seems fine in the parameter page 
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/681f522c-969b-48aa-8b8c-d528e79f976d)

And in the profile page
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/a1ac2cf0-e0d6-4753-b84c-752bc77d87a7)

Is there other places that need to be checked ?

**Comment by SamuelHassine** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/a064b2a5-d839-49c8-b664-a855ad655234)

**Comment by SamuelHassine** [comment]
In Settings.
