### ISSUE TITLE
Add a capability to bypass mandatory fields (mostly used for UI input and triggering import errors from connectors)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6775]
## Use case

When putting for instance a description as mandatory for malware, some connectors will have import errors because no description is given. It could be interesting to have a capability allowing to bypass mandatory field that can be applied on the connector role for instance if necessary, or to senior analysts if needed.

**Comment by nino-filigran** [comment]
Will be tackled as part of https://github.com/OpenCTI-Platform/opencti/issues/5550
