### ISSUE TITLE
Widgets handle relation between Role and Capability

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6777]
## Reproductible steps
- Create an horizontal bar widgets with attribute = entity_type
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/35ad2175-7b61-4ba8-b2e5-ad7d16948e4a)

In the graph, there is a line for 'capability' (i.e. the relationship between a role and a capability is taken into account in the graph) : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/38b81029-cb82-46df-add8-096df67693c3)

- Update the widget with attribute = entity and enable 'display the source'.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/6c659f05-da35-45bd-90e9-257f20b0144d)

An error occurs because of the 'role' entity type.
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/821e8b44-0cdd-416d-b990-dd64adfc3d30)

## Comment
If you have lots of relationships, you should 
- add filters (exemple: create a new relation between a role and a capability and filter on the creation date to keep the most recent relationships) 
- or upgrade the number of results

to see the relations between Role and Capability

**Comment by nino-filigran** [comment]
@Archidoit just to be clear, this is a knowledge view perspective right? Could you share (a screenshot is fine) the query you've put in filters so I can easily reproduce if you don't mind?

**Comment by Archidoit** [comment]
@nino-filigran yes, knowledge perspective

for the filters: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/5e8b1770-420c-4d4c-ba78-7e4daa210d78)

**Comment by nino-filigran** [comment]
That's odd: I've tried to reproduced, but did not get the error. Here's the dash I've created (I've granted you admin rights on it), with the 2 visualisations. https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/af728245-70eb-481e-961f-cfbbce01bd52

**Comment by Archidoit** [comment]
@nino-filigran  I updated the 'number of results' to 3000 in your widget and get an error. Here is the config :
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/4730292e-082e-416a-b9cd-09e5aadda9fc)

**Comment by nino-filigran** [comment]
Indeed, I had 30 only and saw the capa but now see the error. Thanks @Archidoit , I remove the label needs more info :)

**Comment by Archidoit** [comment]
@nino-filigran @Jipegien  To be sure: knowledge widgets should only take into account: stix core relationships, stightings and the 'contains' relationship.

**Comment by nino-filigran** [comment]
@Archidoit Yes, for me this sounds right indeed.
