### ISSUE TITLE
[Playbook] Detection field not updated by the playbook

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6796]
## Description

When I try to modify the "detection" field of my Indicators with playbooks, it's not working. The execution logs are correct but the update is not done.

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a playbook with
- Listener : filter on "Entity type: Indicator AND label: test" (create and update event)
- Manipulate : replace - detection - true
- send to ingestion
 
2. Go on an Indicator and apply the label "test"
3. Check the execution log -> everything seem ok
4. Check the indicator -> detection field still false

## Screenshots (optional)

![Screenshot 2024-04-23 222114](https://github.com/OpenCTI-Platform/opencti/assets/70956706/cad778b0-7753-4105-b1cf-0587e84a6bf8)

**Comment by nino-filigran** [comment]
That's odd: my playbook does not get triggered (at least execution traces are empty) even though I've attempted both to create an indicator & to edit an indicator. https://testing.octi.staging.filigran.io/dashboard/data/processing/automation/28ed87c4-0dcb-4e85-a482-a00603f1edb1

Therefore, end result is the same: my indicator does not get updated.

**Comment by Lhorus6** [comment]
Look at this playbook on Demo instance : https://demo.octi.filigran.io/dashboard/data/processing/automation/ebd43fd1-94a1-4d26-ae65-0973ee194cbd

**Comment by nino-filigran** [comment]
Interesting: your automation launches on Demo but the same one does not launch on Testing! 

Therefore, to whoever will work on this: be aware that we might have an additional issue on testing.

**Comment by Lhorus6** [comment]
A little additional information: when I opened the issue yesterday, I had reproduced it on testing, so apparently it's only been there since this morning.
