### ISSUE TITLE
Ability to filter on representatives starting with X in playbook and streams

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#6799]
## Use case

I want to filter my playbook on entity with name/title/value (representative) starting with a defined text value.

Should also be made possible in data sharing streams/feeds.

**Comment by Lhorus6** [comment]
"starting" and "contains if possible

**Comment by Archidoit** [comment]
The scope has been restricted to adding the representative filter for: streams, playbooks, triggers

**Comment by Archidoit** [comment]
Scope reduced to playbooks, streams and triggers.

**Comment by Archidoit** [comment]
Scope reduced to playbooks, streams and triggers.
