### ISSUE TITLE
Several clicks needed to open an entity page displayed on a widget "List Distribution" 

### ISSUE THREAD

**Issue by sancievanneaud** [LuatixHQ/opencti#6804]
## Description

On a widget "List Distribution" - knowledge base - filter on an entity, several clicks is needed to open the entity pages displayed by the graph. 

## Environment
2. OpenCTI version: 6.0.10

## Reproducible Steps
1. Create a new dashboard
2. Create a new Widget,
3. Visualisation, Select  "List Distribution" 
4. Perspective, Select "Knowledge graph"
5. Filters, click on "Add filter" and select "related type" 
6. Select an entity "Intrusion set" 
7. Click on "Validate"
8. Parameters, in "Attribute" select "Entity" 
9. Check the box "Display the source"
10. Click on "create"
11. On the widget just created, click 5 or 6 times on the Intrusion sets displayed to be redirected to the Intrusion set page.

## Expected Output

Click 1 time on the Intrusion set indicated in the widget to be redirected to the Intrusion set page directly. 

## Actual Output

Click 5 or 6 times on the Intrusion sets displayed to be redirected to the Intrusion set page.

**Comment by Jipegien** [comment]
Even more clicks needed when reproducing it.
