### ISSUE TITLE
Global search no indication when files are found

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6820]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/bd2c19c6-0a50-4ef2-bdf4-416baac1a034)

Before, there was a "number" indicating some files available in the tab. This number has disappeared and is not working anymore.

**Comment by nino-filigran** [comment]
@SamuelHassine was the number only on file search or also on knowledge search?

**Comment by SouadHadjiat** [comment]
> @SamuelHassine was the number only on file search or also on knowledge search?

@nino-filigran It was on file search only, but the issue is wider : after searching with a keyword in the search bar, when you click on file search, the keyword is lost and we'll display the whole list of files, same if you click on knowledge search.
