### ISSUE TITLE
CSV Feed Didn't Show Anything 

### ISSUE THREAD

**Issue by 1337Deep** [LuatixHQ/opencti#6830]
## Environment

1. OS ( Ubuntu 20.0.4.1 LTS }
2. OpenCTI version: 6.0.10
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Create CSV feed with main observation - URL 

## Expected Output
CSV feed

## Actual Output
nothing

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/a0a96e24-3eb1-4454-9aab-0e98f0cd5a45)
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/c976d33b-5891-4d27-ad85-6b8e07dc9217)
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/993df85c-20af-474a-b578-cc3490599319)

**Comment by Jipegien** [comment]
"main observable type" is not an attribute of SCO URL, so the filter might return nothing. But still, seems there is a bug as even without the filter, the feed is empty.

**Comment by Jipegien** [comment]
Hello @1337Deep! 
As "main observable type" is not an attribute of the SCO URL, you cannot use it if you select URL as "entity type". The filter will return nothing. 
Plus, the CSV feed will only include added or updated elements in the platform during the defined rolling time. 

Can you check with no filter if newly added URL appears in your feed? Reopen the issue if it is not the case.

**Comment by 1337Deep** [comment]
even with no filter nothing show up 
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/012348f0-88ec-4b7c-a13c-9fad9531ed63)
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/000768d4-dbb0-4af6-afff-25f8deb0e6fa)
