### ISSUE TITLE
Can't unlink a task from a case template

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6834]
- Go to Settings > Taxonomie > Case Templates
- Click on a case template to see the list of its tasks
- Try to unlink a task (3 points at the right of the task > Unlink)
- An error message occurs

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f7abe81b-1857-4d76-9c8c-24bb8be3f132)

**Comment by nino-filigran** [comment]
Reproduced on Demo
