### ISSUE TITLE
Be able to select the default dashboard for home

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#6843]
## Use case

Be able to select the default dashboard for home.

**Comment by SamuelHassine** [comment]
@nino-filigran @Jipegien please prioritize this. This is tiny and very painful, when a default dashboard is selected for a group or an organization, as a user (even admin), you can never come back to the default home. It is my situation on all Filigran instances.

**Comment by Jipegien** [comment]
Proposed solution: When a user open the dialog to configure their home dashboard, it can select "Default Dashboard" in the recommended dashboard section.
![image](https://github.com/OpenCTI-Platform/opencti/assets/104078945/70858ee3-26fe-4cab-b92c-4702e88dcd0d)
