### ISSUE TITLE
user can't view data in a custom dashboard

### ISSUE THREAD

**Issue by KaizenMazzetto** [LuatixHQ/opencti#6852]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I'm trying to view a custom dashboard made for a user of a service to stream on a tv some webpages.
I've created the user and put it in a group called "TV", when i go to manage this role's capabilities i can tick every box but it won't show me data until i tick the "bypass every capabilities" box. I don't want to give all privileges to that group, i want it to just view the dashboard i made.

## Environment

1. OS (where OpenCTI server runs): docker on debian 12
2. OpenCTI version: 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a custom dashboard
2. create a user inside a group with every capability except for the "bypass all capabilities" one
3. assign the custom dashboard to the group
4. log in with the user you just created and see that no data is shown

**Comment by nino-filigran** [comment]
@KaizenMazzetto can you please tell me if you have assigned some markings to your group? This might be the issue.

**Comment by KaizenMazzetto** [comment]
Hi, thanks for replying.
Actually i did not touch anything regarding markings and other things, i only tried with the capabilities of the groups.
So i would define the markings on the group as default.
Let me know if you need a screenshot o something. :)

Regards,
Gabriele

**Comment by nino-filigran** [comment]
@KaizenMazzetto did this solve your issue?

**Comment by nino-filigran** [comment]
Closing the ticket
