### ISSUE TITLE
HTML Heading is broken

### ISSUE THREAD

**Issue by saibamo** [LuatixHQ/opencti#6864]
## Description

The rendering of html headings, when writing a report is broken. Namely is the Heading 2 smaller than Heading 1 (which is what I would expect) but somehow the Heading 3 is as large as Heading 1.

Also confusing is that Heading 1 is `h2` in html, Heading 2 `h3` and Heading 3 `h4`.

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: v6.0.8
3. OpenCTI client: Webfrontend
4. Other environment details:

## Reproducible Steps

Create new html file in a report.
Add three Lines of text.
Mark the first as Heading 1, the second as Heading 2 and the third as Heading 3

You'll see that, Heading 1 is as large as Heading 3.
Also when switching to source mode you'll see, that Heading 1 does not equal `h1`

## Expected Output
Something looking similiar to this.
![image](https://github.com/OpenCTI-Platform/opencti/assets/103260415/1ad40d9c-6671-4c61-8d77-88ecc8ab26ab)

```html
<h1>
    Heading 1
</h1>
<h2>
    Heading 2
</h2>
<h3>
    Heading 3
</h3>
```

## Actual Output
Heading 1 is as large as Heading 3
![image](https://github.com/OpenCTI-Platform/opencti/assets/103260415/a17c0b27-831d-4a6e-bfbd-13854d6e5341)

Also Heading 1 is not `h1` as I would've expected.
```html
<h2>
    Heading 1
</h2>
<h3>
    Heading 2
</h3>
<h4>
    Heading 3
</h4>
```

**Comment by jborozco** [comment]
Hi, thanks for noticing, I'm closing the ticket as a bug but we are currently working on the global hamonization of our platform and on our design system so this will be taken into account for the future iterations.

**Comment by saibamo** [comment]
Hey Guys, 

any update on this, since this issue is close to a year old and still unfixxed.

Would greatly appreciate a fix! @SamuelHassine  @jborozco 

Warm Regards
