### ISSUE TITLE
[Playbook] Generation of indicator after enrichment does not work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6866]
## Description

In my playbook, when I try to generate indicators from observables, i.e. "Promote" component, after enrichment, an error occurs.

The problem seems to come only if I generate them after enrichment, because if I reverse the order of execution (I put the component for generating indicators before the one for enrichment), I don't have the problem.

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a playbook with
- Listener on IPv4 (observable) and label:test
- Enrich with virustotal
- Promote observable (switch on the "Create indicators from all observables in the bundle" toggle)
- Send to ingestion
2. Apply the label "test" on an IPv4
3. Look at the execution logs of the playbook -> an error has occurred on the "Promote" component

## Additional information

If you switch the component 2 and 3 (i.e. "promote" before "enrich", it works (no error).

### Playbook which doesn't work
![Screenshot 2024-05-02 150825](https://github.com/OpenCTI-Platform/opencti/assets/70956706/dadd002c-4e69-4799-8578-1f4b90d42b01)

### Listener config
![Screenshot 2024-05-02 150903](https://github.com/OpenCTI-Platform/opencti/assets/70956706/74346bb0-7c4d-429c-a227-c729f99101c9)

### Promote observable config
![Screenshot 2024-05-02 150851](https://github.com/OpenCTI-Platform/opencti/assets/70956706/0b3f6db3-ee48-4b8e-ae58-4800e3599f4b)

### The error on the "Promote" component
![Screenshot 2024-05-02 150739](https://github.com/OpenCTI-Platform/opencti/assets/70956706/3cd0943b-b52f-4ff8-97b2-ca6a286c8290)

**Comment by nino-filigran** [comment]
Reproduced on Testing
