### ISSUE TITLE
Bulk update allow irrelevant actions

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6870]
## Description

The interface allows to change the score when bulk editing entities, even if this field does not exist on the entity in question.

## Environment

OCTI 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Incident
2. Select several Incidents
3. Click on update (pencil button in the bottom right corner)
4. Action: replace
5. fields: score
-> Score doesn't exist on Incident

## Expected Output

I hope to see only relevant values, i.e. existing fields on the entities I'm modifying.

## Additional information

AFAIK, The field "score" exists only on Observables and Indicators

## Screenshots

![Screenshot 2024-05-02 193153](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f29a761b-2f78-4d9d-95b8-fc8e09f37f8f)

**Comment by nino-filigran** [comment]
Indeed, they do not exist: as a matter of fact, it throws an error in the corresponding task: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/5951595e-5ced-4301-9c26-b36292b61bdd)
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/acd02002-5557-4a47-be49-8d8c2faf76eb)
