### ISSUE TITLE
[technical] incorrect use of stixCoreRelationshipDistribution queries

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#6873]
In Report details, the entities distribution uses widget `EntityStixCoreRelationshipsHorizontalBars` which uses the query `stixCoreRelationshipsDistribution`.

In this case we send `relationship_type: "object"` to this query, but this is a ref relationship not a stix-core-relationship.

With #6872 we now properly check if the provided `relationship_type` is consistent with the query expectations, so sending `object` would throw an error.

We currently disabled the error throwing in the check in stixCoreRelationshipsDistribution to give time to fix the issue frontend side.

We need to properly use other widget such as `StixRelationshipsHorizontalBars` instead of `EntityStixCoreRelationshipsHorizontalBars`, but this means a refactoring (StixRelationshipsHorizontalBars currently won't accept props such as `relationship_type`).

We also need to check throughout the frontend code if there are other places with failing widgets for same reasons.

**Comment by Kedae** [comment]
Part of this is reverted, need to be checked again correctly
