### ISSUE TITLE
Report frontend error in logs and support package

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#6904]
## Use case

In 6.1, we introduced the support package,able to catch any error thrown by the Back End.
However this solution only supports Back End Errors as mentioned: if an error is thrown by the Front only, there will be no trace in the Back and this error will not be present in the support package.

Currently, we present a CTA to copy paste error message in the UI: it copy pastes the error message sent by the back. If there is no error, the CTA to copy/paste is not present. 

## Solution (To be discussed)
- MVP: 
   - For any error that is generated by the Front End only (ex: parsing errors on data sent by the back end), show the copy/paste CTA. The copy/pasting should contain the error generated by the front end. **Bonus:** add a way to add in the error message a link to GitHub to let the user create an issue. 
   -  For any error generated by the Back End only: do not show the copy-paste, and add a CTA to navigate the user to the support package/ask the user to create a support package.

- MMP:
   - Create an API that would catch Front End Errors only and send them so Back End, so that all errors are logged in the Back end and the Support Package becomes the main feature to handle issues.

**Comment by richard-julien** [comment]
MMP information.

![image](https://github.com/OpenCTI-Platform/opencti/assets/285555/92b971f2-9f63-477a-8ac4-828831debbf3)

Example of error you can now find in error.log (standard or support package)

`{"category":"APP","codeStack":"TypeError: Cannot read properties of undefined (reading 'id')\n    at render (http://localhost:3000/js/front.js:1629417:70)\n    at Object.render (http://localhost:3000/js/front.js:66901:24)\n    at ReactRelayQueryRenderer2.render (http://localhost:3000/js/front.js:55554:25)\n    at finishClassComponent (http://localhost:3000/js/front.js:17517:41)\n    at updateClassComponent (http://localhost:3000/js/front.js:17481:34)\n    at beginWork (http://localhost:3000/js/front.js:18784:24)\n    at beginWork$1 (http://localhost:3000/js/front.js:22745:24)\n    at performUnitOfWork (http://localhost:3000/js/front.js:22168:23)\n    at workLoopSync (http://localhost:3000/js/front.js:22104:15)\n    at renderRootSync (http://localhost:3000/js/front.js:22082:17)","componentStack":"\n    at ReactRelayQueryRenderer (http://localhost:3000/js/front.js:55442:36)\n    at QueryRenderer (http://localhost:3000/js/front.js:66887:24)\n    at div\n    at RootChannel (http://localhost:3000/js/front.js:1629358:11)\n    at http://localhost:3000/js/front.js:244243:29\n    at InjectIntl (http://localhost:3000/js/front.js:240201:29)\n    at injectIntl(InjectIntl)\n    at ErrorBoundaryComponent (http://localhost:3000/js/front.js:244398:11)\n    at RenderedRoute (http://localhost:3000/js/front.js:48677:7)\n    at Routes (http://localhost:3000/js/front.js:48974:17)\n    at Suspense\n    at Root (http://localhost:3000/js/front.js:1648479:14)\n    at ErrorBoundaryComponent (http://localhost:3000/js/front.js:244398:11)\n    at RenderedRoute (http://localhost:3000/js/front.js:48677:7)\n    at Routes (http://localhost:3000/js/front.js:48974:17)\n    at Suspense\n    at main\n    at http://localhost:3000/js/front.js:69103:53\n    at Box (http://localhost:3000/js/front.js:72361:47)\n    at div\n    at http://localhost:3000/js/front.js:69103:53\n    at Box (http://localhost:3000/js/front.js:72361:47)\n    at Index (http://localhost:3000/js/front.js:1918849:41)\n    at AnalyticsProvider (http://localhost:3000/js/front.js:864009:19)\n    at LocalizationProvider (http://localhost:3000/js/front.js:95667:23)\n    at IntlProvider (http://localhost:3000/js/front.js:85604:49)\n    at AppIntlProvider (http://localhost:3000/js/front.js:181768:51)\n    at _class (http://localhost:3000/js/front.js:54493:38)\n    at forwardRef (http://localhost:3000/js/front.js:54407:26)\n    at RtlProvider (http://localhost:3000/js/front.js:73459:11)\n    at ThemeProvider (http://localhost:3000/js/front.js:31618:21)\n    at ThemeProvider (http://localhost:3000/js/front.js:73546:21)\n    at ThemeProvider (http://localhost:3000/js/front.js:78163:18)\n    at AppThemeProvider (http://localhost:3000/js/front.js:80646:19)\n    at _class (http://localhost:3000/js/front.js:54493:38)\n    at forwardRef (http://localhost:3000/js/front.js:54407:26)\n    at StyledEngineProvider (http://localhost:3000/js/front.js:70010:11)\n    at RootComponent (http://localhost:3000/js/front.js:1919338:59)\n    at Suspense\n    at Root (http://localhost:3000/js/front.js:1919384:27)\n    at RenderedRoute (http://localhost:3000/js/front.js:48677:7)\n    at Routes (http://localhost:3000/js/front.js:48974:17)\n    at Suspense\n    at RedirectManager (http://localhost:3000/js/front.js:1919424:22)\n    at AuthBoundaryComponent (http://localhost:3000/js/front.js:1919440:7)\n    at http://localhost:3000/js/front.js:244243:29\n    at Router (http://localhost:3000/js/front.js:48917:17)\n    at BrowserRouter (http://localhost:3000/js/front.js:49295:17)\n    at App\n    at Suspense\n    at RelayEnvironmentProvider (http://localhost:3000/js/front.js:45258:31)","level":"error","message":"TypeError: Cannot read properties of undefined (reading 'id')","source":"frontend","timestamp":"2024-05-08T12:00:15.293Z","version":"6.0.10"}`
