### ISSUE TITLE
Observable Nested Object Creation lacks any Relationship Types

### ISSUE THREAD

**Issue by Bonsai8863** [LuatixHQ/opencti#6915]
## Description

When trying to create a nested object relationship on an observable, there are no available relationship types to choose.

## Environment

1. OS (where OpenCTI server runs): Mac OS Sonoma 14.4.1
2. OpenCTI version: 6.0.10
3. OpenCTI client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have system running and at least one observable and another entity to link it to.
2. Navigate to the observable's Knowledge tab.
3. Click the plus icon to the right of "Nested Objects".
4. Check the box of the target entity and hit "Continue".

## Expected Output

Be able to select a relationship type and create the nested object relationship.

## Actual Output

There are no available relationship types in the dropdown, and since this field is required, the relationship cannot be created.

## Additional information

I tried this with various target/source entity types as I wasn't sure if these types of relationships were only available under certain conditions. If so, I'd suggest that target entities that don't satisfy the conditions of this relationship be hidden from the create relationship drawer.

## Screenshots (optional)

<img width="893" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/131906254/cd481903-0193-4f81-9940-d95abeff6876">

**Comment by Bonsai8863** [comment]
Another thing to mention is that the filters for the select entity step of the StixNestedRefRelationshipCreationFromEntity drawer also lack options for many of its filters. e.g. author has no options, same for marking definitions and organization type.
![image](https://github.com/OpenCTI-Platform/opencti/assets/131906254/3494938d-8afc-4957-a81a-c215ba1e2ef9)

**Comment by Jipegien** [comment]
Nested object relationship are very specific relations defined in stix as _ref. There is no "by-default" relationship type for nested object anymore in OpenCTI. So if there is nothing to select, it is because there is no meaning of a relationship between these 2 type of objects defined in stix standard. If you want to create a by-default relationship between 2 entities, you must choose the "related-to" relationship from the usual relations.

**Comment by Jipegien** [comment]
Closing this one and creating a new bug issue for the filter problem

**Comment by Bonsai8863** [comment]
>  if there is nothing to select, it is because there is no meaning of a relationship between these 2 type of objects defined

Then can we hide such target entities from the selection stage? I.e. only show targets with whom we can form a nested object relationship? Or have their selection be disabled?

**Comment by Jipegien** [comment]
hide or disable them will be hard I think. But we could adapt the default filters in the screen to only show "compatible" entity types.
