### ISSUE TITLE
[TAXII Collections] An Unknown Error Occurred

### ISSUE THREAD

**Issue by Belpheg0rsPrime** [LuatixHQ/opencti#6916]
## Description

I cannot access the TAXII Collections that I have created when using the web frontend for OpenCTI. I can still cURL the collections so it appears to me that this is a front end issue only and not an issue with the collections actually existing. This behavior began exhibiting itself while on 5.12.18 a day ago. I updated to 5.12.33, properly prepared for the next upgrade, and then upgraded to 6.0.10. The issue has persisted the entire time. I can also share my docker-compose.yml file but I have not changed anything in it since the TAXII Collections section was working so I am not sure what could have caused this.

## Environment

1. OS (where OpenCTI server runs): Rocky Linux release 9.3 (Blue Onyx)
2. OpenCTI version: 6.0.10
3. OpenCTI client: frontend
4. Other environment details: OpenCTI is being run as a stack inside Portainer 2.19.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Data
2. Click Data Sharing
3. Click TAXII collections

## Expected Output

I expect to see a list of all of the TAXII collections that have been set up for that particular user

## Actual Output
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Additional information

The opencti/platform:6.0.10 container produces the following error when attempting to access the TAXII Collections:
`
ERR [object Object] | category=APP inner_relation_creation=0 operation=TaxiiLinesPaginationQuery operation_query=query TaxiiLinesPaginationQuery($search:String$count:Int!$cursor:ID$orderBy:TaxiiCollectionOrdering$orderMode:OrderingMode){...TaxiiLines_data_2ltyuX}fragment TaxiiLine_node on TaxiiCollection{id name description filters}fragment TaxiiLines_data_2ltyuX on Query{taxiiCollections(search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode){edges{node{...TaxiiLine_node id __typename}cursor}pageInfo{endCursor hasNextPage globalCount}}} size=78 timestamp=2024-05-08T13:51:04.175Z type=READ_ERROR user={"group_ids":["bdc38f4a-d438-47f7-aabc-f61729474448","0d42fdd0-5f06-47db-84c4-b75dd549a135"],"ip":"::ffff:10.0.0.2","organization_ids":[],"referer":"https://opencti.thrivecloud.io/dashboard/data/sharing/taxii?orderAsc=true&searchTerm=&sortBy=undefined","socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}} variables={"count":25,"cursor":null,"orderBy":"undefined","orderMode":"asc","search":""} version=6.0.10
`

## Screenshots (optional)
![TAXII_Collections_Error](https://github.com/OpenCTI-Platform/opencti/assets/15894670/8e051aea-dfe3-478c-bfdc-047954c99fa5)

**Comment by richard-julien** [comment]
Your uri in the logs is a bit strange with a sortBy=undefined
Can you try to force your uri with sortBy=name ?
Thanks

**Comment by Belpheg0rsPrime** [comment]
Hi @richard-julien, I found out that the issue was actually being caused by a connector we had that was on an older version. I am not sure how it was causing it but we got the vendor to update the connector and now everything works as expected. I will close the issue as everything is now working as expected.
