### ISSUE TITLE
Selecting a domain as a nested object of an Ipv4 crashes the front

### ISSUE THREAD

**Issue by Jipegien** [LuatixHQ/opencti#6919]
## Description

When selecting a Domain name Observable to be added as a nested object for an ipv4 address Observable, the front crashes.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the Knowledge tab of an IP v4 observable
2. click on the + button to add a nested object
3. filter on entity type=domain name
4. select a domain name
5. click on continue

## Expected Output

the drawer to create the nested relationship

## Actual Output

A crash
https://testing.octi.staging.filigran.io/dashboard/observations/observables/1e2e805e-ed88-4642-9a86-077d4f1f367c/knowledge

**Comment by SouadHadjiat** [comment]
Adding this bug to be handled with this one : https://github.com/OpenCTI-Platform/opencti/issues/6959 @ValentinBouzinFiligran
