### ISSUE TITLE
user with only access  knowledge capability  can remove entities from reports

### ISSUE THREAD

**Issue by marieflorescontact** [LuatixHQ/opencti#6920]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  create a user  with only  `Access knowledge` capa:

![image](https://github.com/OpenCTI-Platform/opencti/assets/73853856/3bdee2ce-77d5-4928-9b91-eabff34119fa)

3. log with this user
4. go on report
5. try to remove an entity
6. popover shows `remove` option

## Expected Output

no popover (3 dots at the end of the line)

## Actual Output

popover shows `remove` option

![Capture d'écran 2024-05-10 110508](https://github.com/OpenCTI-Platform/opencti/assets/73853856/306ff7fd-2608-4bbd-872e-2821ae36d031)

**Comment by lndrtrbn** [comment]
@marieflorescontact we agree that a user with only `Access knowledge` cannot remove an entities? It's just an UI issue, the user has the button to remove but when trying to do it the backend throw an Unauthorized error right?

Just to be sure I have the right behavior on my local env

**Comment by marieflorescontact** [comment]
> @marieflorescontact we agree that a user with only `Access knowledge` cannot remove an entities? It's just an UI issue, the user has the button to remove but when trying to do it the backend throw an Unauthorized error right?
> 
> Just to be sure I have the right behavior on my local env

yes it is only a UI issue, everything is ok with api. it is just confusing for user to see an action that they are not allowed to do
