### ISSUE TITLE
Malware Source type filter also filter relationship with Malware-Analysis as source type

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#6921]
## Description

Malware Source type filter also filter relationship with Malware-Analysis as source type

### Scenario 1
- Go to the relationship list
- Filter with : source type = Malware
- You also get relationships with source type = Malware Analysis

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/f1bf6c72-286d-47d0-a613-1f55a34b8460)

### Scenario 2
- Create a widget of type donut with the knowledge perspective and filter: source type = Malware
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/26a4b54f-5e07-4763-9d9f-4e3b077f98aa)

- Select 'entity_type' as attribute and display the source
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3463408f-9c72-4f51-a438-90255c726993)

Both relationships with source type = Malware and Malware-Analysis are displayed:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/04ca6e2d-5f21-4b21-8f52-cb08a37b1294)

**Comment by richard-julien** [comment]
Maybe the filter must be applied on the .keyword
