### ISSUE TITLE
Back button no longer works

### ISSUE THREAD

**Issue by misje** [LuatixHQ/opencti#6934]
## Description

Going back to the previous page in OpenCTI no longer works. It worked in 6.0.9.

## Environment

1. Ubuntu 22.04
2. OpenCTI version: 6.0.10
3. OpenCTI client: 6.0.10
4. Other environment details:
  - Firefox 125.0.3
  - Google Chrome 124.0.6367.201

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Log in
2. Navigate to another page
3. Try to go back to any previous page

## Expected Output

The previously accessed URI should be loaded

## Actual Output

Same page is loaded, still creating a new history item.

**Comment by nino-filigran** [comment]
@misje I cannot reproduce your bug. Can you try to clear your cache maybe?

**Comment by misje** [comment]
> @misje I cannot reproduce your bug. Can you try to clear your cache maybe?

I installed chrome for the very purpose of reproducing this in another browser, so there isn't any cache involved there. Perhaps it is somehow affected by the data in my instance. It's just test data, so I'll try again with a fresh install of OpenCTI.

**Comment by SamuelHassine** [comment]
@nino-filigran Indeed it is completely true.


https://github.com/OpenCTI-Platform/opencti/assets/1334279/5551dfa0-fd7a-4d68-91bf-af3d408e3433

**Comment by SamuelHassine** [comment]
Happening when navigating on left menu that have children.

**Comment by misje** [comment]
I tried a fresh install. Same issue. I loaded up 6.0.9 again, and it works fine.

**Comment by nino-filigran** [comment]
Thanks @SamuelHassine : that odd though I still cannot reproduce on the public demo though. @misje I've removed the tag needs tirage so that we can have a look at this.
