### ISSUE TITLE
Error when importing text files or PDFs

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6942]
## Description

When importing a PDF/TXT file, an error occurs in some cases

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report
2. Upload a PDF in the data section (example: https://www.cisa.gov/sites/default/files/2024-05/aa24-131a-joint-csa-stopransomware-black-basta_1.pdf)

## Expected Output

The file should be uploaded then imported

## Actual Output

Error when importing: **list index out of range**

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/29df5483-29c9-4662-bff1-872869475222)

**Comment by yassine-ouaamou** [comment]
The same issue happens with txt files also. I can create a new issue if needed.
Here is an example of a txt file: 
[txt_file.txt](https://github.com/OpenCTI-Platform/opencti/files/15296140/txt_file.txt)

**Comment by jborozco** [comment]
The bug is moved to critical since it impacts majors clients

**Comment by jborozco** [comment]
(bug reproduced here https://demo.octi.filigran.io/dashboard/analyses/reports/aa4385d6-c46b-4120-b0e9-d5c3e9b646ac/files )
