### ISSUE TITLE
[backend] Add family option in Redis to support IPv6 domain connection

### ISSUE THREAD

**Issue by blackpint** [LuatixHQ/opencti#6944]
## Description

Hi! I found an odd bug that It's not possible to make OpenCTI to connect to Redis server hostname if it is resolved in IPv6 address. Surprisingly, everything works fine if server's IP-address specified instead of hostname.

I did some research and noticed that ioredis [by default](https://github.com/redis/ioredis/blob/558497c/lib/redis/RedisOptions.ts#L201) expects the server having IPv4 address. It very likely results in an error `getaddrinfo ENOTFOUND <hostname>` in case Redis server lives on IPv6 address. The problem is despite ioredis allows to specify an expected IP family, it seems for now we do not have options on OpenCTI side to pass this parameter.

I still don't understand why setting an IP instead hostname works as expected. My guess is ioredis might "understand" that IP and not hostname was provided and simply skip some steps that cause this error because of address family mismatch.

## Reproducible Steps

1. Deploy Redis server with IPv6 address
2. Specify it's hostname in OpenCTI configuration
3. Run OpenCTI

## Actual Output

Docker logs part
```
opencti  | {"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500,"provider":"publisher"},"message":"Redis client connection fail","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: Redis client connection fail\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at EventEmitter.<anonymous> (/opt/opencti/build/src/database/redis.ts:154:44)\n    at EventEmitter.emit (node:events:519:28)\n    at EventEmitter.silentEmit (/opt/opencti/build/node_modules/ioredis/built/Redis.js:464:30)\n    at Socket.<anonymous> (/opt/opencti/build/node_modules/ioredis/built/redis/event_handler.js:196:14)\n    at Object.onceWrapper (node:events:634:26)\n    at Socket.emit (node:events:531:35)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"},{"message":"getaddrinfo ENOTFOUND <cut_hostname>","name":"Error","stack":"Error: getaddrinfo ENOTFOUND <cut_hostname>\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)"}],"level":"error","message":"Redis client connection fail","timestamp":"2024-05-13T12:13:04.232Z","version":"6.0.10"}
```

## Additional information

Just as a quick fix, what if we add one extra parameter for setting IP-address family at least in Redis 'single' mode?

I created a pull request with micro fix which helped me with this issue https://github.com/OpenCTI-Platform/opencti/pull/6945

**Comment by richard-julien** [comment]
Hi @beerman17 , thanks for your ticket and your PR.
But I just tested without your PR with no issue.

My config

```
  "redis": {
    "mode": "single",
    "hostname": "fd00::1:aa27:1ae6:9aca:588c"
  },
```

Looks like is working out of the box on my side

**Comment by richard-julien** [comment]
Ok interesting stuff, when using a domain i got the same problem.
Based on your PR code i will do the same code but in a different place to be more generic.
Thanks a lot for you ticket and the base PR
