### ISSUE TITLE
[Live stream] Sending data that already exists in the platform produces an error

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6950]
## Description

When I send data from a live stream (not tried with TAXII if I have the same behavior), if an entity already exists in the receiving platform, an error appears: "Restricted entities already exists"

![Screenshot 2024-05-14 005444](https://github.com/OpenCTI-Platform/opencti/assets/70956706/dbd0964a-1970-4b1e-96a9-591f68e5dca4)

This error appears even though the users used are admin with all possible rights ("bypass all", conf level at 100, all markings, etc.).

## Environment

OCTI 6.1.0

## Reproducible Steps

NB: this repro case doesn't work every time. I had to redo it several times to get the error. Ping me instead of taking too long to get the error.

Steps to create the smallest reproducible scenario:
1. Have a sender platform (hereinafter referred to as “sender”)
2. Having a receiving platform (hereinafter referred to as “receiver”)
3. On both platforms, have an admin user with all possible rights. These users/tokens will be used throughout.
4. On Sender, create a live stream with filter : "label:test" (e.g. "Test bug" https://demo.octi.filigran.io/dashboard/data/sharing/streams?)
5. On Receiver, create an ingester of live stream to consume the Sender's live stream (use the token of the Sender's admin user, and the Receiver's admin user as "user responsible for data creation"), (e.g. "Test bug" https://testing.octi.staging.filigran.io/dashboard/data/ingestion/sync)
6. On Sender, create a report with some entities inside
7. On Receiver, create the same entities that you created on the sender side (not the report)
8. Add the label "test" on the report
9. Look in the Receiver. If your report doesn't contain all entities -> Look in the logs of the platform, you will see the error.

**Comment by Kedae** [comment]
Seems like can't reproduce anymore @Lhorus6

**Comment by Lhorus6** [comment]
It was very hard to reproduce artificially and even the case on the client platform no longer produces the bug (a bug that was reproduced every time before).

Maybe it was a side effect of another bug that had been solved (we've solved bugs on capabilities, haven't we? maybe related).

In short, I think we can close this issue.
