### ISSUE TITLE
[Live stream] Deleting data on the sender's side deletes the data on the receiver's side

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6951]
## Description

When we delete something on the side of the platform sending the data (i.e. with the live stream exposed), the data on the receiving side (i.e. the platform consuming the live stream) is also deleted.

This behavior is intended when the “Take deletions into account” button is on. However, even when this button is off, this deletion behavior occurs.

## Environment

OCTI 6.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Have a sender platform (hereinafter referred to as “sender”)
2. Having a receiving platform (hereinafter referred to as “receiver”)
3. On both platforms, have an admin user with all possible rights. These users/tokens will be used throughout.
4. On Sender, create a live stream with filter : "label:test" (e.g. "Test bug" https://demo.octi.filigran.io/dashboard/data/sharing/streams?)
5. On Receiver, create an ingester of live stream to consume the Sender's live stream (use the token of the Sender's admin user, and the Receiver's admin user as "user responsible for data creation"), (e.g. "Test bug" https://testing.octi.staging.filigran.io/dashboard/data/ingestion/sync) NB: turn off the button **"Take deletions into account"**
6. On Sender, create a report and add the label "test"
7. On Receiver, check that the report has been created
8. On Sender, remove the "test" label on the report
-> On Receiver, the report has been deleted (which should only be the case if the “Take deletions into account” button is enabled)

**Comment by nino-filigran** [comment]
Validated in live with @Lhorus6

**Comment by JeremyCloarec** [comment]
Looking into it, I'm not sure if this was an intended behavior or an oversight @richard-julien. 
Code is in `liveStreamHandler` of `sseMiddleware.js`: we do not check for the **"Take deletions into account"** config flag when receiving an update event making the entity no longer visible (on the case described in the issue, when the label is removed for exemple)

```
if (type === EVENT_TYPE_UPDATE) {
    const { newDocument: previous } = jsonpatch.applyPatch(structuredClone(stix), evenContext.reverse_patch);
    const isPreviouslyVisible = await isStixMatchFilterGroup(context, user, previous, streamFilters);
    if (isPreviouslyVisible && !isCurrentlyVisible) { // No longer visible
      client.sendEvent(eventId, EVENT_TYPE_DELETE, eventData);
      cache.set(stix.id, 'hit');
    }
```
