### ISSUE TITLE
[Dashboard] No available option for "Relationship_type" filter

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6953]
## Description

When I try to create a widget, I don't have a possibility in my filter "relationship_type"

## Environment

OCTI 6.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create new widget with "view: heatmap" and "perspective : knowledge graph"
2. Add a filter "relationship type" and try to find a value

![Screenshot 2024-05-14 042233](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f7ac61f4-b8f4-49df-81bc-11d0cb0bb3f1)

**Comment by Archidoit** [comment]
In widget of perspective 'History', you should only have 'history' and 'activity' in the entity type filter list, not all the stix core objects and relationships types values:
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/6d44a2d4-528d-4406-a02a-329b8a98bc30)

**Comment by dominictory** [comment]
Hi all, unfortunately still seeing this on 6.1.2.

**Comment by Kedae** [comment]
Hi @dominictory, I cannot reproduce on our environment. Can you provide a repro case ? More info ?

**Comment by dominictory** [comment]
> Hi @dominictory, I cannot reproduce on our environment. Can you provide a repro case ? More info ?

Apologies. I've just noticed this is only the case when trying to use the 'In regards of' filter. No relationship types show.

**Comment by Archidoit** [comment]
Indeed, that's a different repro case. I'm going to open another bug for this

**Comment by Archidoit** [comment]
@dominictory Here is the link of the new issue : https://github.com/OpenCTI-Platform/opencti/issues/7153
