### ISSUE TITLE
Report Entities tab - Number of entities not updated when adding or removing entities

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#6961]
## Description

When going to the tab Entities of a Report and adding or removing some entities: the number of entities at the top right of the table is not updated.

![image](https://github.com/OpenCTI-Platform/opencti/assets/33682259/f521bff6-bf4b-410f-8cf4-74ecf9352097)

If changing tab and going back to Entities, the number is updated.

## Environment

1. OS (where OpenCTI server runs): Edge
2. OpenCTI version: 6.1.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to a report
2. Go to Entities tab
3. Click add button (bottom right)
4. Click on some entities
5. Check the number of entities

## Expected Output

The number is updated without the need to refresh the page.

## Actual Output

No update without refresh.

**Comment by CelineSebe** [comment]
Same issue on the report list, grouping list, malware ...

**Comment by lndrtrbn** [comment]
Yep as the component in charge of tab Entities is quite generic to all our data types it should have the issue in any of them.

Could also be worth to check the tab Observables.
