### ISSUE TITLE
[TAXII collection] Not a valid ISO8601-formatted datetime (non-compliant with the TAXII 2.1 spec)

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6973]
## Description

The TAXII implementation is not 100% compliant with the standard
-> the "X-Taxii-Date-Added-First" and "X-Taxii-Date-Added-First" headers can be "undefined" while the documentation specifies "The value of this header MUST be a timestamp".

![requete](https://github.com/OpenCTI-Platform/opencti/assets/70956706/7daceb68-185c-4db8-a118-dc5685d798e5)

![requete](https://github.com/OpenCTI-Platform/opencti/assets/70956706/18637d2a-4aa8-45dd-8849-eab345686606)

This produces client-side errors during ingestion. Notably, EclecticIQ's ingestion of OpenCTI's TAXII collections fails because of this.

## Environment

OCTI 6.1.0

**Comment by richard-julien** [comment]
> The X-TAXII-Date-Added-First header is an extension header. It indicates the date_added timestamp of the first object of the response.

Do you have any result in your call? If not, do we need to put the current date of the query?

**Comment by Lhorus6** [comment]
_Pending - In discussion with the customer_

**Comment by Lhorus6** [comment]
Indeed Julien, you were right, the response is empty.

Moreover, the TAXII documentation makes no reference to the value to be set in these headers if the result is empty. So we're a bit in the dark. I continue talking to the customer and come back.

**Comment by Lhorus6** [comment]
This is the answer that I got:
Based on [the OASIS TAXII 2.1 reference implementation](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foasis-open%2Fcti-taxii-server%2Fblob%2F39e76bf18be5371e9570de7e5f340c3937b69c0d%2Fmedallion%2Fcommon.py%23L202-L211&data=05%7C02%7Cjulien.philippe%40soprasteria.com%7Cfce77831eb534d0ad78f08dc75a390d7%7C8b87af7d86474dc78df45f69a2011bb5%7C0%7C0%7C638514592570802639%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=H0QNnBbBGwuJlJQR%2ByMD0D3sisPEvaKb6UqbPqVZt0Q%3D&reserved=0), if no results from the query, then the TAXII 2.1 server is apparently allowed to just omit the X-TAXII-Date* headers.

So we shouldn't use these headers if no object is contained. What is your opinion on that ? Is it ok for you @richard-julien ?

**Comment by richard-julien** [comment]
Yes perfect
