### ISSUE TITLE
[Playbook] Issue when manipulating an observable

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#6978]
## Description

When creating a playbook that manipulates observables with no score an error is displayed. (perhaps similar to https://github.com/OpenCTI-Platform/opencti/issues/6941)

When manually adding a score or modifying the description the step goes well.

## Environment

1. OpenCTI 6.1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create and start a playbook listening IPV4,
2. Create an IPV4 with no score,
3. The playbook starts but stop early at stage 'manipulate knowledge' displaying an error.

## Expected Output

Knowledge manipulation, such as adding a label or marking definition, should run smoothly.
## Actual Output

If no score is defined, the "manipulate knowledge" step will not work.
## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/155080335/5c5e9f13-6d00-4ece-bd37-7852136fb90c)

**Comment by jborozco** [comment]
Hi @NiQuintin I tested it on both demo and testing without any problem. 

Here is my config, 
https://demo.octi.filigran.io/dashboard/data/processing/automation/e40e476d-5915-4312-ac59-0a449d2b6a0a

and here is the result
https://demo.octi.filigran.io/dashboard/observations/observables/363a1866-d3c8-495d-9693-064377078796

let me know if you have a different config

**Comment by jborozco** [comment]
Actually nevermind, I reproduced the issue on a second try, It s

Entity created here didn't get a label 
 https://demo.octi.filigran.io/dashboard/observations/observables/14347cc9-2315-4eab-b859-15ce7fac7fc4
 
 Error in last execution trace:
![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/b23d48a0-bc53-4e3b-afa4-4096ecf9c239)

![image](https://github.com/OpenCTI-Platform/opencti/assets/35300800/387e3626-1339-4df0-aca5-fffd75de32ed)

> {
>   "message": "Cannot set properties of undefined (setting 'labels')",
>   "stack": "TypeError: Cannot set properties of undefined (setting 'labels')\n    at Object.add (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:14:16)\n    at applyOperation (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:235:60)\n    at Object.applyPatch (/opt/opencti/build/node_modules/fast-json-patch/commonjs/core.js:280:22)\n    at Object.executor (/opt/opencti/build/src/modules/playbook/playbook-components.ts:601:17)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:137:44)\n    at playbookExecutor (/opt/opencti/build/src/manager/playbookManager.ts:205:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at playbookStreamHandler (/opt/opencti/build/src/manager/playbookManager.ts:279:17)\n    at processStreamResult (/opt/opencti/build/src/database/redis.ts:642:3)\n    at processStep (/opt/opencti/build/src/database/redis.ts:696:31)\n    at processingLoop (/opt/opencti/build/src/database/redis.ts:713:13)",
>   "name": "TypeError"
> }
