### ISSUE TITLE
Wrong PDF report generated

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6979]
## Description

When generating a PDF report of a threat actor, the generated report is of another threat actor

## Environment

Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Access this Threat actor: https://demo.octi.filigran.io/dashboard/threats/threat_actors_individual/7edbdfc7-cf62-437c-be0e-8782ad8cdd36
2. Generate a simple PDF report

## Actual Output

The generated report is the one of this [threat actor](https://demo.octi.filigran.io/dashboard/threats/threat_actors_individual/f111b61d-e388-4ee2-9884-82c9d4d9def9)

**Comment by Jipegien** [comment]
also for Intrusion Set. Probably for all entity types managed by the connector

**Comment by Kedae** [comment]
FIxed by 86b6bc852ad792d91a015570ebd17e32c572ca1e

**Comment by yassine-ouaamou** [comment]
> FIxed by [86b6bc8](https://github.com/OpenCTI-Platform/opencti/commit/86b6bc852ad792d91a015570ebd17e32c572ca1e)

Tested on Demo after the release. I don't have the issue anymore.
