### ISSUE TITLE
When sharing a Report with an Organisation (into the platform, organization seggregation) , inferred relationships are not shared 

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6990]
## Description

When sharing with organisation, inferred relationships are not shared 

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make sure organisation segregation is enabled in the platform (main Orga = Filigran)
2. Create a user with Admin rights (no Bypass all)
3. Using your account, share a report containing inferred relationships with the organisation of the created user
4. Log in with the created user
5. Access the report

## Expected Output

The whole graph is shared

## Actual Output

Inferred relationships are missing

## Additional information

I used [this report](https://testing.octi.staging.filigran.io/dashboard/analyses/reports/03187959-c81e-410d-85ed-a340b57cf517). Ping me if you need the credentials of the user I created to do the test.
## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/7083405/8b1a5644-def2-4653-b83f-85b81b18e1c8)

**Comment by Jipegien** [comment]
Is it also the case for other Container types ?

**Comment by Jipegien** [comment]
In order to see the inferred relations, the Organization must be able to access all elements constituing conditions of the inferred rules.

**Comment by frapuks** [comment]
Already fix here : https://github.com/OpenCTI-Platform/opencti/issues/6991
The bug has disappeared locally but is still present on testing.

**Comment by richard-julien** [comment]
We need to discuss about this @Jipegien , @frapuks . Please schedule a sync point

**Comment by Lhorus6** [comment]
What was the conclusion of this issue ?
To see an inferred relationship, a user must have access to all entities that meet the conditions triggering the rule, right?
