### ISSUE TITLE
Once a report is shared with an organisation, added entities are not shared

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#6991]
## Description

Once a report is shared with an organisation, added entities are not visible to the orga with whome the report is shared

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make sure organisation segregation is enabled in the platform (main Orga = Filigran)
2. Create a user with Admin rights (no Bypass all)
3. Using your account, share a report  and then add new entities to the report
4. Log in with the created user 
5. Access the report

## Expected Output

All the entities are visible in the shared report

## Actual Output

Entities added after sharing are not visible

**Comment by nino-filigran** [comment]
IT's indeed really odd: I've followed your steps and shared the reports. Then added 3 incidents. 
When logging in with the platform admin, in the overview I see that the report contains 3 incidents, but in the entity tab, the list is empty 😕 

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/bb1a68bf-ac3e-4a17-838a-388b1444eada)

**Comment by marieflorescontact** [comment]
after many tests it seems like orga sharing is not propagated to the container content when we add or remove items.
for exemple: if a report with a malware X is shared , then malware X is removed from the report, it remains visible to user in the organization even if it disappeared from the report. @nino-filigran critical?

**Comment by nino-filigran** [comment]
Did not test this scenario, but in that case, I'd say yes, given that it's basically a nonworking functionality. I update the tags. (fyi @Jipegien & @Kedae )
