### ISSUE TITLE
[6.1.1] In Dashboards, filtering on Source entity, Target entity, Related entity or Relationship type ends up in a list with "No available options"

### ISSUE THREAD

**Issue by Arcuza** [LuatixHQ/opencti#6994]
## Description

In Dashboards, filtering on Source entity, Target entity, Related entity or Relationship type ends up in a list with "No available options". This more or less makes Dashboard creation and editing not functional since 6.1.0

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. } Ubuntu 22.04
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } OpenCTI 6.1.1
3. OpenCTI client: { e.g. frontend or python } Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Dashboards
2. Create or Edit a widget using Knowledge Graph
3. Try to filter on Source entity, Target entity, Related entity or Relationship type
4. See an empty list showing the text "No available options"

## Expected Output

A list of available options

## Actual Output

"No available options"

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/74782259/19d074a0-9283-4c3e-90b4-f6796662df12)

**Comment by Archidoit** [comment]
This issue has been resolved in https://github.com/OpenCTI-Platform/opencti/pull/6971

The changes will be available in the coming minor release :)

**Comment by Archidoit** [comment]
This issue has been resolved in https://github.com/OpenCTI-Platform/opencti/pull/6971

The changes will be available in the coming minor release :)
