### ISSUE TITLE
[Workbench] Creating or editing Observable File does not work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#6996]
## Description

In a workbench, creating or modifying an Observable File renders the object “corrupt”, i.e. “unknown”.

## Environment

OCTI 6.1.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a workbench
2. Try to create an Observables file:
    - Go to the "Observables" tab
    - Click on "+" and select "File"
    - Add an SHA256 hash (e.g. 25f53e6818589c7d05f4b67ec62d206ea3a416d7db845e70be09a2efbeb0bdc5)
    - Validate (click on "Add")
-> The object is "unknown"

![Screenshot 2024-05-16 162139](https://github.com/OpenCTI-Platform/opencti/assets/70956706/223ade52-de72-42b4-aa13-5f04c5510e4b)

## Additional information

If I import a file (like a .txt) and my import mechanism create a workbench with an Observable File, it works. However, if I modify it (by adding another type of hash that corresponds to the same file), I'm back in the same situation with a “unknown” object.

**Comment by nino-filigran** [comment]
The same happens for any value of the file. However, it's only a "UI" issue, since from a functional point of view, you can still import the Observable and it gets created successfully.

**Comment by lndrtrbn** [comment]
@Lhorus6 what means the column "default values"? What are we supposed to see here?

From what I see in the code, it is the main representative. In this case, should the column be named "Representative"?

**Comment by nino-filigran** [comment]
@lndrtrbn Artifact gives you a good idea: we show the SHA. For file, as long as file name is provided, it seems that we display the FileName. 

So in general, we should have the same behavior as artifact, meaning: 
- if name is provided, default value = file name 
- if file name is provided and any other value is provided, default value = file name
- if only MD5 provided, default value = MD5
- if only SHA1 provided, default value = SHA1
- if only sha 256 provided, default value = SHA256
- if only SHA512 provided, default value = SHA 512
- If x SHAs are provided, default value = the "highest" (the one with the bigger number)
- if MD5 and x SHA are provided, default value = the "highest" (the one with the bigger number)

Does that also make sense for you @Jipegien ?

**Comment by Jipegien** [comment]
Default value displays the representative of the Object. Logic to define what is the representative is already implemented (for example in Observables list, the column "Representation"). I see no need to specifically change this logic.
