### ISSUE TITLE
[ImportDocument] Can't find countries using aliases

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7012]
## Description

When importing a txt document, it seems that the ImportDocument connector doesn't find/idenfy the countries if it's  an alias of the country in the document.

## Environment

OCTI 6.1.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Country with name = "Test", and one alias = "ThisTest"
2. Create a txt file with "ThisTest" inside.
3. Import your file in "Data > Import" and wait that ImportDocument finish
-> Nothing identified by the connector

You can try with "Test" inside your txt, ImportDocument will find the Country

## Additional information

I tried to find malware with aliases, and for malware it worked.

**Comment by nino-filigran** [comment]
I've reproduced this issue using a country called HelloTest and alais testingCountry. Same happens for me: the importDocument does not find the country.
