### ISSUE TITLE
Live Streams sort by description broke the view

### ISSUE THREAD

**Issue by 1337Deep** [LuatixHQ/opencti#7017]
## Description

When i try to create a new live stream i got an error 
## Environment

1. OS (where OpenCTI server runs): { ubuntu }
2. OpenCTI version: {6.1.2}
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click Data Sharing / Live stream 
2. Sort by description
3. Error 

## Hint
Long text are no longer indexed by keyword.
Sorting by description must be removed.

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/149091894/d0225417-827c-487d-b9dc-778e6adad3ce)

**Comment by richard-julien** [comment]
Can you check your sortBy uri parameters?
Thanks

**Comment by 1337Deep** [comment]
by default?  ```sortBy=description&orderAsc=false&searchTerm=```

**Comment by richard-julien** [comment]
Looks like we have an issue with this sorting.
Simple workaround, change your sortBy to sortBy=name

**Comment by 1337Deep** [comment]
It's working, and I got this: ```sortBy=name&orderAsc=false&searchTerm=```
