### ISSUE TITLE
Reindixing fail error when deleting entities in some specific cases

### ISSUE THREAD

**Issue by SouadHadjiat** [LuatixHQ/opencti#7031]
## Description

We encountered a case on testing platform where deleting an entity raised an error:
`Reindexing fail from opencti_stix_domain_objects-000001 to opencti_deleted_objects`

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: 

## Reproducible Steps

Reproduced on this malware on testing be8e0cab-dd32-45ef-8dc7-1a1cf665c49c

**Comment by SamuelHassine** [comment]
Same here : #7015.

**Comment by SouadHadjiat** [comment]
The two issues can be linked, but we are not sure since it's a report orphans delete (with a concurrency issue)
