### ISSUE TITLE
[CSV Import] Failing import with kill chain phases and labels

### ISSUE THREAD

**Issue by Goumies** [LuatixHQ/opencti#7036]
## Description

When importing a CSV containing kill chain phases, no entity is imported. Neither the source entity nor its kill chain phases.

## Environment

Testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the following mapper
- Check "My CSV contains headers"
- Indicator (name: A, pattern_type: Default to stix, pattern: A main_observable_type: Default IP address)
- Kill chain phase (kill chain name: C, phase name: D, order: E)
- Link the kill chain phase to the indicator
![image](https://github.com/OpenCTI-Platform/opencti/assets/13460700/d57d229e-95ee-45b5-a177-25f73881e6af)

2. Import the attached CSV using the created mapper

## Expected Output

Correctly imported indicators with embedded kill chain phases

## Actual Output

No indicator, no kill chain phases

## Additional information

[feed_1_mini - kill chain phases.csv](https://github.com/OpenCTI-Platform/opencti/files/15379793/feed_1_mini.-.kill.chain.phases.csv)
[feed_1_mini - labels.csv](https://github.com/OpenCTI-Platform/opencti/files/15379892/feed_1_mini.-.labels.csv)

To illustrate the bug, 2 CSV mappers were created on testing:
- issue_7036_kill_chain_phases
- issue_7036_labels

## Screenshots (optional)
CSV mapper test succeeds with the expected entities being properly mapped.
![image](https://github.com/OpenCTI-Platform/opencti/assets/13460700/012a8040-338b-48b6-9152-71cac33ac64a)

IP address indicators with 198.168.8.3 & 198.168.8.4 are nowhere to be found.

**Comment by nino-filigran** [comment]
@Goumies don't know if it helps but the IPs are found on public demo: 
![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/3f4ca44d-7f10-46da-967d-1a53663f77fa)

**Comment by Goumies** [comment]
> @Goumies don't know if it helps but the IPs are found on public demo: ![image](https://private-user-images.githubusercontent.com/148041607/332694512-3f4ca44d-7f10-46da-967d-1a53663f77fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjYxNDUsIm5iZiI6MTcyMDE2NTg0NSwicGF0aCI6Ii8xNDgwNDE2MDcvMzMyNjk0NTEyLTNmNGNhNDRkLTdmMTAtNDZkYS05NjdkLTFhNTM2NjNmNzdmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQwNzUwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODdlMTRjMjYwMmJkMjMzODFlMDc0M2U0YWUyMWEwNWU3MTgyMDc4Njc0OWRmNDA5ODk5MzMxM2QwODlmMTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L26s9jtyfC8kyrzQIxy2-DqV471tjskpUVW5RJK2jYM)

@nino-filigran, I opened this issue while resolving a bug related to another embedded property: [the external references were missing](https://github.com/OpenCTI-Platform/opencti/issues/6287). As in the prior case, codebase updates fixed the problem. So I wrote tests to document the expected result. And, spot any regression.
