### ISSUE TITLE
User can merge entities without the full visibility of entities merged

### ISSUE THREAD

**Issue by JeremyCloarec** [LuatixHQ/opencti#7043]
## Description

We now check that the user has access to all relations when deleting following this issue https://github.com/OpenCTI-Platform/opencti/issues/6421.
We may want to add this access check to merge operation also. Adding access check during merging could impact two core processes:

- when data is ingested, the upsert process can sometimes lead to a merge (hard for me to describe the cases where a merge is done during upsert, code can be found in middleware.js createEntityRaw). If connectors are not configured to access all dependencies during a merge, this could lead to some upsert failing and to knowledge data loss
- when a platform is synced, merge events are processed on the target platform by the worker. If worker configuration doesn't have access to all data, this could also lead to some merge events failing

We need to decide if we take the risk of breaking some misconfigured production environment with this change or not

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by nino-filigran** [comment]
We'll take this internally

**Comment by nino-filigran** [comment]
Decision: we will only check for **manual creation** and not any automatic creation (connector or sync). cc @Jipegien & @richard-julien

**Comment by JeremyCloarec** [comment]
After testing multiple merge use cases (merging an entity from where the user doesn't have ACL to access relation, merge an entity from where the user doesn't have ACL to acess target of relation etc..), all scenarios seem to behave correctly.
We no longer see the need to introduce a new capability & change the way merges are done
