### ISSUE TITLE
Missing warning before deletions of entity in container

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7073]
## Description

When I'm in a container, I don't get the warning message when I hover my mouse over the delete icon.

This message is visible in other areas of the platform (e.g. Malware > Knowledge tab > Indicator).

NB: This can lead to accidental deletions. Deletions that may not be understood by users (and therefore not even restored afterwards).

## Environment

OCTI 6.1.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report with entities inside
2. Go to the Entities tab
3. Select multiple entities
4. Hover the delete button
-> No warning

## Expected Output

A warning as we have elsewhere

![Screenshot 2024-05-22 103113](https://github.com/OpenCTI-Platform/opencti/assets/70956706/297277ad-4830-4379-86ba-1b027e5e8c7d)

## Actual Output

No warning
![Screenshot 2024-05-22 103050](https://github.com/OpenCTI-Platform/opencti/assets/70956706/6be3ef66-44bc-4958-a203-26b18404bd47)

**Comment by nino-filigran** [comment]
I agree, but this will not be prioritized compare to any other bugs since we have the trash if you accidentally delete by mistake.

**Comment by lndrtrbn** [comment]
Well, I know it was not prio but I had 15mins free before eat 😁

**Comment by lndrtrbn** [comment]
The PR also:
- adds translations to existing messages that were always displayed in english,
- adds a warning message also on report observables tab
