### ISSUE TITLE
Investigations - add more filter/select options

### ISSUE THREAD

**Issue by sweet-mentat** [LuatixHQ/opencti#7103]
## Use case

Request for additional functionality in Investigations.  In the current version, you can filter/select nodes by entity type.  Unfortunately, there are a lot of different types of data that go into each entity type.  We would like the ability to expand on only a subset of our objects, such as only objects with a particular author, or if the object has a specific label, or if a particular field is populated, for example. It would also be nice to filter/select based on one or more criteria, like entity type and a specific label.  Since some of our investigations have many nodes, individually clicking into each object to see if it is one we want to include is tedious and time consuming. We request either the ability to search in the investigation for specific fields/names, and/or the ability to select based on labels.

## Current Workaround

No workaround

## Proposed Solution

Add filtering/select options on attributes/labels

## If the feature request is approved, would you be willing to submit a PR?

Yes / No (Help can be provided if you need assistance submitting a PR)

**Comment by SamuelHassine** [comment]
Duplicate #7105.
