### ISSUE TITLE
Opinions creation spins forever if you have mandatory marking definitions and you don't have any for the user

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7104]
## Description

Opinions creation spins forever if you have mandatory marking definitions and you don't have it for the user

1. Put marking definition as mandatory for opinion
2. Login with a user that have a group with no default marking definition
3. Try to create an opinion in an entity

=> Spinning for ever (should raise an error)

**Comment by marieflorescontact** [comment]
I can't reproduce on my side, I have the expected error @nino-filigran :

UI:
![image](https://github.com/OpenCTI-Platform/opencti/assets/73853856/4f155c41-ea87-4d6e-8c16-b32c8fc979b2)

Back:
`{
  "errors": [
    {
      "message": "Validation error",
      "name": "VALIDATION_ERROR",
      "time_thrown": "2024-05-27T08:03:44.648Z",
      "data": {
        "http_status": 500,
        "genre": "BUSINESS",
        "field": "objectMarking",
        "message": "This attribute is mandatory",
        "attribute": "objectMarking"
      }
    }
  ],
  "data": {
    "opinionAdd": null
  }
}`

**Comment by nino-filigran** [comment]
Agreed, just retried again on testing and I have the same result, which is the desired behavior. I don't know what changed.
