### ISSUE TITLE
Throwing User effective max confidence level is insufficient to update this element at upsert / ingestion

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7112]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/fa77a0e3-4874-4db8-8976-ce4f09abe358)

I'm very worried about this error. Can someone checked that this error does not prevent upserting the "other STIX IDs" of this element and that we actually continue to cumulate IDs despite of this error?

**Comment by SamuelHassine** [comment]
It is linked to the observable promotion of indicators

**Comment by nino-filigran** [comment]
@SamuelHassine how did you get it ? 
cc @ValentinBouzinFiligran & @Kedae (I think you modified this recently)

**Comment by labo-flg** [comment]
I confirm that when you try to promote an indicator to observable, if you do not have sufficient confidence with respect to the indicator this error is thrown.

This should not be the case, we're just creating an observable and a stix core relationship between the 2.
