### ISSUE TITLE
我配置了opencti 连接器，但是地图热力图无法显示，请帮帮我。

### ISSUE THREAD

**Issue by Reverse-laboratory** [LuatixHQ/opencti#7113]
1，docker-compose.yaml
  connector-opencti:
    image: opencti/connector-opencti:6.1.4
    environment:
      - OPENCTI_URL=http://192.168.10.138:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=1ae312d9-9435-482f-97c1-935ca983ed5e
      - CONNECTOR_NAME='OpenCTI Datasets'
      - CONNECTOR_SCOPE=marking-definition,identity,location
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=error
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_COMPANIES_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/companies.json
      - CONFIG_REMOVE_CREATOR=false
      - CONFIG_INTERVAL=7 # In days
    restart: always

2,
![image](https://github.com/OpenCTI-Platform/opencti/assets/117882938/af40e0b7-2481-4c35-886a-ad86ef8c90f6)
3,
![image](https://github.com/OpenCTI-Platform/opencti/assets/117882938/385a9c89-8c9b-4909-85e2-4dc43acdd65f)

**Comment by Jipegien** [comment]
The OpenCTI datasets connector populates your platform with a library of countries, sectors. The map in your Dashboard is distribution display for relationships between other entities and countries (example: "IntrusionSetA" > targets > "Japan").
So you need to feed your platform (manually or not) with this kind of threat knowledge
