### ISSUE TITLE
CSV Mapper default value for boolean fields are not working

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#7116]
## Environment
Testing 6.1.4

## Reproducible Steps

* Create a new mapper
* add representation for entity type malware
* _name_ in column A
* add a default value for _is family_

## Expected Output

Valus is set to false or true depending on the selection in the default value popup window

## Actual Output

* if you select "false" with the toggle, it does not take false as the default value
* if you select "true"  with the toggle, it does take something as default value apparently, but display is incorrect

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/43e7b95d-cf89-4f6e-9dcc-3a25d4f16c7f)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/248175bd-e750-45e1-97ae-35fadced7b81)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/94525469-3476-408b-a867-13a64a499168)

**Comment by labo-flg** [comment]
probably a simple if clause on the value to check if it's defined, that just `if(value)` or something. We must check for undefined/null only if the `false` value is legit.

**Comment by CelineSebe** [comment]
"is family" attribute is customizable in settings too:
![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/a0d5d11c-f27e-4955-8b52-d97d9094951b)

**Comment by lndrtrbn** [comment]
To have a bit of context: same component is used between default value in CSV mapper and settings customization.

Indeed we should have `false` if off and `true` if on. I think the label of the toggle is misleading as we can understand it as "should we have a default value" instead of "we have a default value, the value is: true/false".

It would be more intuitive (IMO) with something like: `Default value: false <toggle> true` instead of `<toggle> Default value`.
Or even a group off two buttons [true|false] instead of a toggle.

**Comment by lndrtrbn** [comment]
@nino-filigran the bug is not only a UI issue. In fact for now we can set only TRUE as default value for boolean attributes, we cannot set FALSE. To do it we need change how we save the default value in elastic (not a big change).

+ bug also on Settings > Customization (Example: malware/is family)

**Comment by nino-filigran** [comment]
So to recap, If I understand correctly, 
- currently when toggling **on** this CTA it basically means "use TRUE as default value". 
- However, when toggling **off**, it means "do not apply a default value".

If so, I agree that it's misleading.
As a result, we should indeed fix it by applying your suggestion Default value: false <toggle> true

**Comment by lndrtrbn** [comment]
You understand correctly. Agreed on the fix then 😊

**Comment by lndrtrbn** [comment]
There is an other strange behavior on this boolean is_family. It is required but not highlighted in red if nothing is configured for it and the mapper is considered valid by the backend. Nonetheless when trying to import data after, the import fails.

@nino-filigran 

I'm for fixing this issue in the same time

**Comment by nino-filigran** [comment]
Many thanks for your help @lndrtrbn

**Comment by CelineSebe** [comment]
EDIT: issues solved
To precise, it is highlighted in red the first time the field is_family is opened, but it isn't red after it is filled and unfilled.

@nino-filigran 
Another issue:
The default value for the field name seems to be configured in the CSV mapper and customization, but it isn't.

![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/ededc224-31cb-481c-af7c-e66d93336ed3)
![image](https://github.com/OpenCTI-Platform/opencti/assets/87119259/34ce6f2b-bf10-467f-8c95-51aec4a0adef)
 Has a bug already been reported on this issue?

**Comment by lndrtrbn** [comment]
@nino-filigran 

Find an other issue about the management of boolean values:
- I have set a default value for the boolean attribute in Settings > Customization (for example True for malware.is_family),
- I have created a CSV mapper to map malwares without specifying a default value at CSV mapper level,
- I launch an import of a file where the column is_family has missing data for some malwares.

Expected output: import success with the default value set in Customization.
Actual output: import fails.

**Comment by nino-filigran** [comment]
@lndrtrbn Do you want me to open a bug for this, or do you tackle this weird behavior as part of this?

**Comment by lndrtrbn** [comment]
I found the solution yesterday and add it directly in this PR

**Comment by nino-filigran** [comment]
Thanks again for your help
