### ISSUE TITLE
Default trigger for assignment is not generating a meaningful notification

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7127]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/3c618318-1aac-4a62-8af8-fc7a1e24d80d)

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/bd1e564a-bd8a-40a0-8e59-035c85890b4f)

**Comment by nino-filigran** [comment]
@SamuelHassine What's the exact request here? When you're assigned to an entity, to get a notification like: 
- XXX user has modified XXX field for instance?

**Comment by SamuelHassine** [comment]
@nino-filigran I don't know exactly, yes truncate the title of the main element to 120 chars, put an overview etc.

Maybe this screenshot is more meaningful, someone just assigned to me 5 cases, I think the result does not meet our quality standards:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/678eb7ce-9354-409d-a7ae-e70b91bd7e22)

I don't know any tool sending notifications producing this kind of output....

**Comment by nino-filigran** [comment]
At least then, we should do the same as an instance trigger to make more relevant on the short term. This means, we should:
- Replace 1. with the name of the entity, as on all other notifications
- Replace 2 with the name of the entity
- Replace 3 with automatic trigger for participant/Assignee

![image](https://github.com/OpenCTI-Platform/opencti/assets/148041607/b381a721-7028-4e0d-9c32-9b85b4843d81)
