### ISSUE TITLE
OpenCTI / OpenBAS integration does not work

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7144]
## Description

OpenCTI / OpenBAS integration does not work

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/d98d1f73-ce27-4662-8502-a4cb9080d798)

https://testing.octi.staging.filigran.io/dashboard/analyses/reports/0aa073a8-1cda-4c0f-822c-cc488b7422ec

Default parameters.

**Comment by RomuDeuxfois** [comment]
There are still sometimes problems, but it is impossible to reproduce locally.
Sometimes the generation is going well, sometimes not.
Potentially a problem on the platform side @SamuelHassine @sbocahu ?

![image](https://github.com/OpenCTI-Platform/opencti/assets/53513584/ed95150c-d896-4f2e-9065-5089fa2cd161)
