### ISSUE TITLE
Delete might silently crash (timeout) on entities with a large number of relationships

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#7146]
## Description

Happened recently on a prod infrastructure. 
When deleting an object with a large number of relationships (e.g. an intrusion set with 900 ref/relationships), `elDeleteElements` might throw an error.

```json
{
      "message": "Request timed out",
      "name": "TimeoutError",
      "stack": "TimeoutError: Request timed out
    at hdn.request (/opt/opencti/build/node_modules/@elastic/elasticsearch/node_modules/@elastic/transport/src/Transport.ts:602:17)
    at mat.BulkApi [as bulk] (/opt/opencti/build/node_modules/@elastic/elasticsearch/src/api/api/bulk.ts:75:10)\
    at elRemoveRelationConnection (/opt/opencti/build/src/database/engine.js:3175:9)
    at elDeleteElements (/opt/opencti/build/src/database/engine.js:3289:3)
    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3131:7)
    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3153:32)
    at stixDomainObjectDelete (/opt/opencti/build/src/domain/stixDomainObject.js:177:3)"
}
```

This would happen before deleting the relationships and the main element.
The element might thus be in un unpredictable state regarding the rels connections.

## Environment

OCTI 6.1.4

## Reproducible Steps

Sadly it's hard to reproduce. When attempting the same operation twice, it worked the second time.

## Expected Output

Element is deleted, all ref/relationships properly cleaned up.

## Actual Output

Partial deletion ?

## Additional information

When it happens, it might take so much time to actually throw an error that user thinks it went OK and moved on.
The deleted item and all associated relationships are saved in the trash, but when they try to restore it it will throw `Cannot restore entity, duplicate existing entity detected` as the main object was indeed not deleted (but part of the job on rel connections might have completed).

In that case, user is left with little choice, their database is probably in an unpredictable state regarding this entity end its connection rels.

**Comment by labo-flg** [comment]
For the underlying issue (the timeout) I have currently no idea on the subject. We could adapt some elastic configuration, to be more resilient to high volumetry.

By default we do this `elRemoveRelationConnection` operation in bulk of 5k, so I'm starting to reconsider the fact that 900 is "high" volumetry.

As for the error handling we can think of different ideas, for the sake of brainstorming:
* on deletion, if the size of the impacted elements list gets too big, we can force the job to be started as a background task (could be done and explained to user frontend side). This way user gets rapid feedback and can follow the task with proper error handling in the tasks view.
* simplistic solution: have proper feedback in the deletion popout so user knows he has to wait, operation in progress. But it blocks the UI on the popout.
* implementing partial restore could save the situation, as we would smartly restore all rels that were removed and preserve the rest. Note that this is not trivial: partial restore means you either keep the existing data (that might have changed since deletion) or upsert the data from trash on top of it. A new feature to think thoroughly.

**Comment by nino-filigran** [comment]
@richard-julien what's your take on this? Since it can have quite an impact on the platform. 
I'd be in favor of the background task, since I'm afraid that the UI can be blocked for a while. 
cc @Jipegien

**Comment by richard-julien** [comment]
A background task will not solve the issue.
In my opinion its directly the elasticsearch server that send a timeout after 30 seconds of sync execution.
2 solutions i can imagine:
- Limit the size of the bulk
- Increase the timeout time of the bulk to a very large value

**Comment by nino-filigran** [comment]
Given that this issue happened only once & that we need further investigation to understand how it could happen (after many attempts of reproduction without success), for the moment, the decision taken is that we will document a process on how to retrieve your data if this situation occurs. 

The effort needed to fix the problem seems quite huge and would not solve all cases of failure. We'll close the ticket once the process will be documented officially.

**Comment by labo-flg** [comment]
To add some details on the technical side:

We basically fall into the drawbacks of using a non-transactional database like Elastic. Many operations are necessary, in sequence, and if one fails in the middle we cannot rollback on the spot.

We can tweak configuration such as timeouts and bulk size but this will not solve the problem. There is always a set of input + context parameters that would potentially fall into this rare failure case.
Some operations are highly demanding, and there is no magic. For instance, deleting a heavily connected threat actor is not trivial.

Using background task to go full asynchronous would add significant performance cost for a case that happens rarely, and only to improve user feedback (we do not solve the issue, just make the error more visible).

Implementing multiple, specific rollback procedures on failure for every operations would be a naive approach, the cost way too high and in the end, counter productive.

Our design is non-transactional, and that's not changing any time soon.
But we can definitely identify recovery procedures and improve our documentation.

**Comment by nino-filigran** [comment]
@labo-flg Do you know if we've made any progress on this?

**Comment by nino-filigran** [comment]
Given that the sole purpose of this bug being opened was to improve documentation, the follow up action is to work on the above issue.
