### ISSUE TITLE
Even JavaScript is enabled I get a blank page and on page source You need to enable JavaScript to run this app

### ISSUE THREAD

**Issue by aliekberkara** [LuatixHQ/opencti#7147]
Hello all,

Even JavaScript is enabled I get a blank page and on page source You need to enable JavaScript to run this app

<!doctype html> <script>window.BASE_PATH = ""</script> <script defer="defer" src="/static/js/front-22RDRV77.js"></script> <title>OpenCTI - Cyber Threat Intelligence Platform</title> You need to enable JavaScript to run this app.

Thank you very much for your support

**Comment by nino-filigran** [comment]
Hi @aliekberkara can you please specify your question? Which version are you using? Where are you trying to connect: our demo environment? Your own environement?

**Comment by nino-filigran** [comment]
Closing this ticket since no answer.
