### ISSUE TITLE
Trying to manually import a STIX bundle, what I do wrong?

### ISSUE THREAD

**Issue by blackpint** [LuatixHQ/opencti#7152]
## Description

Hi everyone!

I am trying to import some Indicators (~7k) exported from our prod OpenCTI instance to dev instance and frontend just freeze and dies when I open a Workbench.

Sometimes it starts loading the entities but never finishes.  Initially I've tried a bigger bundle (about 70k entities), but it has the same result and I decided that it might be too large for that way of loading entities. But It seems even 7k is too much or I do something wrong.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.4
2. OpenCTI version: OpenCTI 6.1.4
3. Other environment details: 
    Server spec: 
       Kernel Version: 5.4.210-39.1
       Operating System: Ubuntu 22.04.4 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 32
       Total Memory: 58.87GiB

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Upload json file using the cloud icon.
<img width="1232" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/36980924/adee8a14-31ee-446e-a7b8-20e5652427b3">

2. I seen the new Workbench was created.
<img width="1843" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/36980924/b5cda1b8-3ed2-48de-a1cb-08145b86330c">

3. Open Workbench item and... the front just freeze until the browser kill the page :(
<img width="1854" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/36980924/29985bdf-ec2b-492f-a3aa-1982a95e505e">

## Additional information

The file I am trying to upload has about 300k of lines (wc command output)
```sh
285160  552510 11725891 2024-05-28T11_02_47.622Z_TLP_ALL_(ExportFileStix2)_Indicator_simple.json
```

**Comment by Kedae** [comment]
Well, I don't really know how you could review 7k indicators inside a Workbench (there might be some optimization to do as we load the bundle on the front size, but not the main concern here I think).

I suggest you update you import-file-stix configuration to stop validating the bundle before ingestion, that should work better.

**Comment by blackpint** [comment]
Hello @Kedae,

My goal was just to import Indicators and I was not going to review them. Frankly speaking, I didn't know that there is an option to turn validating off. Thank you for pointing this out, I will give it a try.

**Comment by blackpint** [comment]
Yep, now It works exactly I needed. Thank you for your help.

**Comment by Kedae** [comment]
You're welcome :)
