### ISSUE TITLE
When exporting in global search, the search term is not taken into account

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7168]
## Description

In global search, the search term is not taken into account.

---

Mutation sent when exporting from a list of reports (in reports):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/a224eddf-9cff-453f-ad88-89832ad3ab2b)

--- 

Mutation sent when exporting from the global search:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/d1cafbbb-4d02-4be0-a504-a497fdbc305f)

=> search variable is not filled in the global search export mutation

**Comment by Archidoit** [comment]
search term is also not taken into account at observables and relationships exports
