### ISSUE TITLE
Implement the export of lists / search results in PDF

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7176]
## Use case

Implement the export of lists / search results in PDF

**Comment by gkallenborn** [comment]
Hi Samuel. I suppose this feature was implemented in the existing export-report-pdf connector. I tested it on OpenCTI 6.1.10, but unfortunately it did not work. I always got the same error message:

`Connector ready to process the operation, string indices must be integers, not'str'`



![Capture d'écran 2024-06-12 100949](https://github.com/OpenCTI-Platform/opencti/assets/28608796/af9174bb-19fc-4157-a064-4d76b29fac4c)
![Capture d'écran 2024-06-12 101101](https://github.com/OpenCTI-Platform/opencti/assets/28608796/239b38ce-6c87-4ab5-a976-9503ab552f09)
![Capture d'écran 2024-06-12 101207](https://github.com/OpenCTI-Platform/opencti/assets/28608796/36e537c9-ea2b-4c1a-9f74-a1c2ad6c7bdd)
