### ISSUE TITLE
platform - playground not working

### ISSUE THREAD

**Issue by Renizmy** [LuatixHQ/opencti#7181]
Hello,

The graphql playground no longer works since version upgrade (6.0.9 -> 6.1.2)
The demo environement is experiencing the same behavior: https://demo.opencti.io/graphql

Best regards,
Renizmy

![image](https://github.com/OpenCTI-Platform/opencti/assets/62422302/fcf972c1-203a-4852-9f65-e77b7a9dd4f6)

**Comment by SamuelHassine** [comment]
Please use `APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION: "false"`

Demo env has been re-configured and the playground is working.

**Comment by Renizmy** [comment]
It do not looks fixed but the error changed (same issue in our env)

![image](https://github.com/OpenCTI-Platform/opencti/assets/62422302/b7b0f332-b84f-4eee-9b87-8c3065e403a6)
