### ISSUE TITLE
Sightings entity type column doesn't correspond to entity type filter

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7182]
## Description

Sightings entity type column doesn't correspond to entity type filter

## Reproducible Steps
- Go to Event/Sightings
- Filter by entity type
- The entity type filter doesn't correspond with the 'entity type' column (since the real entity type is always 'sighted in/at' for this list

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/354b363f-a058-41d9-bc6a-1be46cd93280)

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e67402d6-806a-4016-8ff1-bc4d61eb78ef)

**Comment by Jipegien** [comment]
Columns "name", "entity type" and "entity" are not explicit enough about what they display.
"Name" is the representative of the source entity of the sighting relationship. It could be named "source entity", "found entity (name)" or "of a (name)" (as in sighting of a ...), etc.
"entity type" is the type of source entity. Could be named "source entity type", "found entity (type)" and so on.
"Entity" is the representative of the target entity of the sighting relationship. Could be named "target entity" or "in (name)" (as in sighting of a ... in ...)
Based on this, filters should be modified to reflect this. 

@nino-filigran what do you think about that?

**Comment by nino-filigran** [comment]
Makes sense, fully agree @Jipegien 
This way we remain consistent with the naming convention of relationships in the platform.
