### ISSUE TITLE
Lifecycle of an indicator is not updated when changing the score from a report "Entities" page

### ISSUE THREAD

**Issue by louispariente** [LuatixHQ/opencti#7191]
## Description

Updating the score of an indicator from a page other than that of the indicator, for example, "entities" page of a report, does not update the lifecycle of the indicator

## Environment

1. OS (where OpenCTI server runs): Ubuntu 
2. OpenCTI version: OpenCTI 6.0.10
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Change the score of an indicator from the "enties" page of a report
2. Check lifecycle of the indicator

## Expected Output

Lifecycle updated with the new score

## Actual Output

The new score is displayed, but the lifecycle is not updated with this new score 

## Screenshots (optional)

When you change the value of "score" from a report page : 
![image1](https://github.com/OpenCTI-Platform/opencti/assets/56361713/d230d623-6c62-40d3-807b-9427fa86ccf6)

When you change from the indicator page, it updates as expected :
![image2](https://github.com/OpenCTI-Platform/opencti/assets/56361713/0dc26ba8-612e-4722-8772-28b8533c13a6)

**Comment by nino-filigran** [comment]
Just to be clear, when you say "Change the score of an indicator from the "enties" page of a report", do you mean:
- clicking on the checkbox next to the indicator 
- the toolbar below opens 
- you click on update 
- as action, you select "update" , as field you select "score" and you set a new score
- even though the task is finished, when you go back to your indicator, the score is not updated?

**Comment by louispariente** [comment]
Yes that's exactly it.

As you can see in screenshot, the score of the indicator has been updated to 75. But in the lifecycle details of the indicator ,it is still the old score that is displayed.

![image](https://github.com/OpenCTI-Platform/opencti/assets/56361713/25538f85-1df7-4f78-9aa2-90010318ded4)
