### ISSUE TITLE
No Open localhost:8080

### ISSUE THREAD

**Issue by meetgyn** [LuatixHQ/opencti#7196]
## Environment

1. OS ubuntu 24.04
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps
"I followed the step-by-step to use it on Docker, but it just doesn't work at all. When I try to access localhost:8080, it just won't open. It's like the image didn't even boot up."
![image](https://github.com/OpenCTI-Platform/opencti/assets/3695608/03cd8802-5e12-4a76-8518-6c16c4012232)

![image](https://github.com/OpenCTI-Platform/opencti/assets/3695608/c1348833-8c23-4508-b768-7e214faf71e8)
![image](https://github.com/OpenCTI-Platform/opencti/assets/3695608/0b67fe44-8b85-402c-b738-5abd84160136)

**Comment by SamuelHassine** [comment]
@meetgyn Can you please share the log of the container opencti-platform?

**Comment by meetgyn** [comment]
Sorry, I don't remember how to generate the logs. I'll search here and get back to you soon.

**Comment by meetgyn** [comment]
root@greenbone:/opt/app/docker# docker container logs -f c8319d7a4ef4
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":1717164856625,"roles":{"data":true,"ingest":true},"status":"dead","url":"http://elasticsearch:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.8.0 (linux 6.2.0-39-generic-x64; Node.js v20.14.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-05-31T14:06:16.626Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:06:16.626Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:76:53)\n    at /opt/opencti/build/src/database/engine.js:215:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:211:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:286:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:31:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"connect ECONNREFUSED 172.20.0.4:9200","name":"ConnectionError","stack":"ConnectionError: connect ECONNREFUSED 172.20.0.4:9200\n    at ClientRequest.onError (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at Socket.socketErrorListener (node:_http_client:500:9)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-05-31T14:06:16.653Z","version":"6.1.6"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":1717164892260,"roles":{"data":true,"ingest":true},"status":"dead","url":"http://elasticsearch:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.8.0 (linux 6.2.0-39-generic-x64; Node.js v20.14.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-05-31T14:06:52.264Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:06:52.264Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:76:53)\n    at /opt/opencti/build/src/database/engine.js:215:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:211:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:286:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:31:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"connect ECONNREFUSED 172.20.0.4:9200","name":"ConnectionError","stack":"ConnectionError: connect ECONNREFUSED 172.20.0.4:9200\n    at ClientRequest.onError (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at Socket.socketErrorListener (node:_http_client:500:9)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-05-31T14:06:52.284Z","version":"6.1.6"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":1717164919303,"roles":{"data":true,"ingest":true},"status":"dead","url":"http://elasticsearch:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.8.0 (linux 6.2.0-39-generic-x64; Node.js v20.14.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-05-31T14:07:19.303Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:07:19.305Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:76:53)\n    at /opt/opencti/build/src/database/engine.js:215:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:211:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:286:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:31:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"connect ECONNREFUSED 172.20.0.4:9200","name":"ConnectionError","stack":"ConnectionError: connect ECONNREFUSED 172.20.0.4:9200\n    at ClientRequest.onError (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at Socket.socketErrorListener (node:_http_client:500:9)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-05-31T14:07:19.321Z","version":"6.1.6"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"http://elasticsearch:9200/","resurrectTimeout":1717164941514,"roles":{"data":true,"ingest":true},"status":"dead","url":"http://elasticsearch:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.8.0 (linux 6.2.0-39-generic-x64; Node.js v20.14.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"CONFIGURATION_ERROR","time_thrown":"2024-05-31T14:07:41.514Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:07:41.523Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"CONFIGURATION_ERROR: Search engine seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at ConfigurationError (/opt/opencti/build/src/config/errors.js:76:53)\n    at /opt/opencti/build/src/database/engine.js:215:15\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at searchEngineVersion (/opt/opencti/build/src/database/engine.js:211:22)\n    at searchEngineInit (/opt/opencti/build/src/database/engine.js:286:27)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:31:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"connect ECONNREFUSED 172.20.0.4:9200","name":"ConnectionError","stack":"ConnectionError: connect ECONNREFUSED 172.20.0.4:9200\n    at ClientRequest.onError (/opt/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at Socket.socketErrorListener (node:_http_client:500:9)\n    at Socket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-05-31T14:07:41.549Z","version":"6.1.6"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"DATABASE_ERROR","time_thrown":"2024-05-31T14:08:02.867Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:08:02.869Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"RabbitMQ seems down","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: RabbitMQ seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/rabbitmq.js:211:13\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:37:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"","name":"Error","stack":"Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"\n    at k (/opt/opencti/build/node_modules/amqplib/lib/connection.js:172:16)\n    at cb (/opt/opencti/build/node_modules/amqplib/lib/connection.js:107:11)\n    at Socket.recv (/opt/opencti/build/node_modules/amqplib/lib/connection.js:456:9)\n    at Object.onceWrapper (node:events:633:28)\n    at Socket.emit (node:events:519:28)\n    at emitReadable_ (node:internal/streams/readable:832:12)\n    at processTicksAndRejections (node:internal/process/task_queues:81:21)"}],"level":"error","message":"RabbitMQ seems down","source":"backend","timestamp":"2024-05-31T14:08:02.881Z","version":"6.1.6"}
{"category":"APP","cause":{"_error":{},"_showLocations":false,"_showPath":false,"data":{"cause":{},"genre":"TECHNICAL","http_status":500},"internalData":{},"name":"DATABASE_ERROR","time_thrown":"2024-05-31T14:08:18.360Z"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-05-31T14:08:18.360Z","version":"6.1.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"RabbitMQ seems down","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: RabbitMQ seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/rabbitmq.js:211:13\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:37:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"","name":"Error","stack":"Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"\n    at k (/opt/opencti/build/node_modules/amqplib/lib/connection.js:172:16)\n    at cb (/opt/opencti/build/node_modules/amqplib/lib/connection.js:107:11)\n    at Socket.recv (/opt/opencti/build/node_modules/amqplib/lib/connection.js:456:9)\n    at Object.onceWrapper (node:events:633:28)\n    at Socket.emit (node:events:519:28)\n    at emitReadable_ (node:internal/streams/readable:832:12)\n    at processTicksAndRejections (node:internal/process/task_queues:81:21)"}],"level":"error","message":"RabbitMQ seems down","source":"backend","timestamp":"2024-05-31T14:08:18.378Z","version":"6.1.6"}

**Comment by fenris** [comment]
+1 for me too

**Comment by niudaii** [comment]
docker-compose.yml 
you can try elasticsearch service add environment **- http.port=9200**


```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      - cluster.name=docker-cluster
      - http.port=9200
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"    
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
```

**Comment by niudaii** [comment]
https://docs.opencti.io/latest/deployment/installation/#using-docker

1.check you have to set vm.max_map_count before running the containers
2.start elasticsearch first and check alive
```
docker compose up elasticsearch -d
```
3.start other services
```
docker compose up -d
```

**Comment by meetgyn** [comment]
Thank you very much. Now with this help I could make it work 100%.
Only a doubt, he rose without any information. This is normal?
![image](https://github.com/OpenCTI-Platform/opencti/assets/3695608/7c226b33-965e-46ab-8691-058d21ccd785)

**Comment by niudaii** [comment]
Yes, you need to add connectors to import data.
https://docs.opencti.io/latest/deployment/connectors/

**Comment by nino-filigran** [comment]
@meetgyn Closing this ticket since it seems that you have found an answer to your question. Feel free to reopen if needs be.
