### ISSUE TITLE
Expansion broken in investigations

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#7205]
## Description

Several expansion options are broken:
- Organization: it expands all the entities instead of the organizations only
- Sector: it expands all the entities instead of the sectors only + wrong number of results displayed 

This bugs don't occur all the time...

## Environment

https://demo.octi.filigran.io/

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open an investigation : https://demo.octi.filigran.io/dashboard/workspaces/investigations/b47af1a8-02de-496e-8683-5ccf5a54ffbf?zoom=%7B%22k%22%3A3.140376851319573%2C%22x%22%3A-0.20189090150155975%2C%22y%22%3A0.7509082937774004%7D&mode3D=false&selectRectangleModeFree=false&selectModeFree=false&selectModeFreeReady=true&modeFixed=false&modeTree=&displayTimeRange=false&selectedTimeRangeInterval=2024-06-01T22%3A00%3A00.000Z%2C2024-06-01T22%3A00%3A00.000Z&stixCoreObjectsTypes=&markedBy=&createdBy=&displayProgress=false&width=null&height=null&zoomed=false&keyword=&prevClick=null&openCreatedRelation=false&isRollBackPreExpandStateDialogOpen=false&openExpandElements=false
2. Expand sectors or organizations of an entity

## Expected Output

expansions of organizations/sectors only + 

## Actual Output

It expands everything

## Screenshots (optional)
Example for sector
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/354dee5e-8d53-4553-8a75-edeb94c5024d)
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/8737c157-ff30-482b-bdc7-485ab320b7c1)
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/ed783de6-fcb7-46a6-b849-4979df3d927d)

Another example:
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/21224df6-417b-4fee-9460-ecde915d1dfb)
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/a768330d-4887-4538-86d6-7a04b83b6f3a)
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/2acc42b4-783d-47cc-b425-5329c15c8eb3)

Another example:
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/2c8cf626-d465-4150-9f42-b01c51352a23)
![image](https://github.com/OpenCTI-Platform/opencti/assets/166409476/0d94ff8d-9463-459e-90f0-0cb8b61763ff)

**Comment by SarahBocognano** [comment]
See: https://github.com/OpenCTI-Platform/opencti/issues/6801
