### ISSUE TITLE
Save filters for various lists (e.g. report list)

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#7206]
## Use case

When researching data in OpenCTI, we use the option of setting filters to see relevant entries. If we switch back and forth between different topics, we have to reset the filters depending on the desired view. It would be nice if every user could save their own filters to be able to list the relevant data (e.g. reports) more quickly.

## Current Workaround

Since filters are also encoded in the URL, it is possible to create browser bookmarks for certain filters.

## Proposed Solution

Add a button `Save filters` next to the filter options. Also add a dropdown field to quickly select and apply saved filters.

## Additional Information

-

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by dominictory** [comment]
+1

Would also love to be able to save filters

**Comment by romain-filigran** [comment]
linked to https://github.com/OpenCTI-Platform/opencti/issues/6044

**Comment by nino-filigran** [comment]
Closing it for the sake of having a single feature to track.
