### ISSUE TITLE
Cannot bulk delete External References when using a filter

### ISSUE THREAD

**Issue by sbjzn** [LuatixHQ/opencti#7210]
## Description

There appears to be a bug with bulk deleting external references when using a filter, the task displays "Targeted entities (0)", even though 100+ are marked.
However, bulk deleting when not using a filter works as expected.

## Environment

1. OS: Ubuntu 22.04 LTS
2. OpenCTI version: 6.1.8
3. OpenCTI client: Frontend/Web
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open the External References view
2. Apply a filter
3. Run a bulk deletion of all entities shown by filter by clicking the top checkbox
4. Look in tasks, it should display "Targeted entities (0)"

## Expected Output

The entities should be deleted

## Actual Output

The entities are not deleted

## Additional information

N/A

## Screenshots (optional)

N/A

**Comment by nino-filigran** [comment]
Reproduced on Testing, happens only with a large amount of entities.
