### ISSUE TITLE
[Bulk search] Sorting on the columns doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7215]
## Description

After searching with bulk search, column sorting does not work with all existing columns.

## Environment

OCTI 6.1.8

## Reproducible Steps

**To do in "testing" platform**

Steps to create the smallest reproducible scenario:
1. Go to the bulk search
2. Look for:
```
93.115.0.49
ns-1156.awsdns-16.org
f9bdeca0e2057b0e334c849ff918bdbe49abd1056a285fed1239c9948040496a
```
3. Try to sort on the "Creators" column (the problem also seems to exist with the column "Analyses"

## Additional information

I haven't tested all columns.

**Comment by nino-filigran** [comment]
After a test, it seems that the non working columns are: 
- authors
- creators
- creation date
- marking
- analyse
