### ISSUE TITLE
Country and Sector's Knowledge UI doesn't load on latest verison

### ISSUE THREAD

**Issue by rach24smith** [LuatixHQ/opencti#7216]
## Description

When upgrading from OpenCTI version 6.0.5 to 6.1.5 and then 6.1.7, we are seeing two pages error out. Both the Sectors > Knowledge, and the Countries > Knowledge pages error out when attempting to load them. When I try to make a support package, we also get an error (See screenshots)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.1.5 as well as 6.1.7
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to Country or Sectors
2. Select any one entity
3. Select Knowledge

Then a secondary issue, when we select the create a support package we get an error. When you open up the support package creation it says status is "IN_ERROR"
## Expected Output

Load the Knowledge UI with information regarding to the sector or country.

## Actual Output

Error as seen in screenshot.

## Screenshots (optional)
<img width="966" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/36097449/092e8536-74b8-4f89-936f-7d43e979b3e6">
![Screenshot 2024-06-03 at 4 11 06 PM](https://github.com/OpenCTI-Platform/opencti/assets/36097449/c398dc48-5841-460a-b3bc-78837f088c91)

**Comment by nino-filigran** [comment]
@rach24smith can you update to latest (6.1.8)? On the public demo, the knowledge tab is accessible. The support package also works.

**Comment by rach24smith** [comment]
Hi @nino-filigran, I have update to 6.1.8 and it appears to now be resolved! Thank you !

**Comment by nino-filigran** [comment]
I'm glad to hear it! I'm closing this ticket
