### ISSUE TITLE
When using Generate Report Document using AI, the first digit in "number of paragraphs" is fixed

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#7240]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: 6.1.8
3. OpenCTI client: Frontend MS Edge on MacOS
4. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a Grouping containing 1-3 reports
2. Click "Generate Report Document" 
3. On the dialogue, select HTML and Tactical
4. On the number of paragraphs, try deleting the default of 10

The number should be deleted

## Actual Output

The first digit (1) is not deleted.
if using the up/down buttons to change it, this works, but this soon goes crazy and number auto-increments continuously without input and cycles.

## Additional information

Video available

**Comment by nino-filigran** [comment]
Reproduced. You can however use the button on the right handside to increase this number but I would expect that you can delete it and type it manually indeed.

**Comment by damians-filigran** [comment]
Yes, but also, the buttons 'go crazy' if clicked more than a few times; see video.


***@***.***?anonymous&ep=bwmEmailSignature>              Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by nino-filigran** [comment]
Yeah, we noticed that too!
