### ISSUE TITLE
[File import] Error when importing files

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7250]
## Description

When importing a file, an error occurs in some cases.

## Environment

OCTI 6.1.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to "Data > Import"
2. Upload a PDF in the data section (example: 
[Operation Crimson Palace_ A Technical Deep Dive – Sophos News.pdf](https://github.com/user-attachments/files/15613726/Operation.Crimson.Palace_.A.Technical.Deep.Dive.Sophos.News.pdf))

## Additional information

Seems to be the same bug as this one : https://github.com/OpenCTI-Platform/opencti/issues/6942

## Screenshots 

![Screenshot 2024-06-06 123348](https://github.com/OpenCTI-Platform/opencti/assets/70956706/58bb0f06-4bad-4822-97ab-82aa4decac1b)

**Comment by nino-filigran** [comment]
Struggle to reproduce. If reproduced, then it would be critical.

**Comment by nino-filigran** [comment]
Could only reproduce on Testing

**Comment by JeremyCloarec** [comment]
Issue has been fixed on impacted platforms, thus the removal of critical tag. 
The point of the opened PR is to have more explicit logs when the error reoccurs
