### ISSUE TITLE
The Count attribute for a Sighting is not useable in Custom Dashboards

### ISSUE THREAD

**Issue by Jermain-N** [LuatixHQ/opencti#7251]
## Description

The Count attribute available in Sightings is useable in that page's search filters, but it is not working as expected in the custom dashboards.

## Environment

1. OS (where OpenCTI server runs): hosted on FIligran cloud
2. OpenCTI version: 6.1.8
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a custom dashboard
2. Create a new widget
3. Select any visualisation
4. Select Knowledge Graph as the perspective
5. Select **Count** from the Add Filter dropmenu
6. Click on the **attribute_count>** filter to enter an operator and a value.

## Expected Output

Expecting the filter to be called **Count** and not **attribute_count**. Expecting the filter's operator dropmenu to allow you to select **Greater than** or **Smaller than** and the number field to allow you to enter any positive integer.

## Actual Output

The filter's operator dropmenui only has the **Equals** option and the number field does not save your number when you type it in and press Enter; instead it shows **No available options**.

## Additional information

It would also be nice to get this Count filter available in the Automation Playbook!

## Screenshots (optional)

![image](https://github.com/OpenCTI-Platform/opencti/assets/155680154/cf843b2e-100c-4b3b-a4a2-0d153ed6681d)

![image](https://github.com/OpenCTI-Platform/opencti/assets/155680154/90e6fc9b-0d73-4146-97cd-da036eb55810)

![image](https://github.com/OpenCTI-Platform/opencti/assets/155680154/f95d3574-6650-4c3c-a394-1c3a557e6252)

**Comment by nino-filigran** [comment]
Ok, it's clear and reproduced. Indeed does not make sense. We should have the operators: 
- greater than
- greater or equal
- equal
- smaller or equal
- smaller than 

Regarding this to be added in playbooks, do you mind opening a ticket for this?

**Comment by Archidoit** [comment]
Adding 'count' filter in automation playbook should be done in another ticket since it requires the handling of a new 'stix' filter in backend
