### ISSUE TITLE
Mandatory fields can block the 'malware analysis' creation

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#7264]
## Description

- For a malware analysis, the update form contains more field than the creation form (i.e. : Configuration Version, Analysis Started)
- In Settings / customization, it's allow to define these fields to 'Mandatory'
- If it's 'Mandatory', you never cann't create a malware analysis because theses fields ane not available in the creation form

## Environment

1. OS (where OpenCTI server runs): Windows 11
2. OpenCTI version: 6.1.8
3. OpenCTI client: frontend 
4. Other environment details: Local & Testing

## Reproducible Steps

1. Go to Settings / Customization / Malware Analysis
2. Update the 'Configuration Version' field
3. Define it 'Mandatory' and save
4. Go to Analyse / Malware Analysis
5. Try to create one
6. Nothing appens

## Expected Output

- To be discussed : May be don't allow to customize these fields (ie : like 'Malware'), or includes these fields in the creation form

## Actual Output

- Nothing appens

## Additional information

- This issue is attached to #6972 

## Screenshots

- Creation form (no 'Configuration Version' field)
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/37332e30-fae8-484e-aa6c-f855927b94db)

- Customization
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/fe19a009-9e3c-43ae-b018-0b175eb9fc46)

**Comment by nino-filigran** [comment]
Given that we'd like to move towards having creation/update forms being driven by the backend, I'm in favor of displaying these fields in the form, rather than limiting users to mark them as mandatory

**Comment by Archidoit** [comment]
The attributes that can be made mandatory but are not in the creation form are: configuration version, analyse started, analyse ended, analyse engine version, analyse definition version, modules, assignees.
