### ISSUE TITLE
[Bulk Update] Revoked field not set after bulk edit of score

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#7265]
## Description
When I have an indicator with a score lower then the revoked score and I want to bulk change the score of few indicators to be > revoked score, then revoked stays "YES" (instead of changing to "NO").

## Environment
OCTI 6.1.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an indicator and set the score lower than the revoked threshold (below 20).
2. Go to the indicator list panel and select (checkbox) the indicator you modified.
3. Click "Update" (bottom right corner) and replace the score to be high than the threshold (>20).
4. Go to the indicator and check the "Revoked" field -> it will be set "YES" (should be set "NO").

## Screenshots (optional)

![Screenshot 2024-06-07 102746](https://github.com/OpenCTI-Platform/opencti/assets/168524367/1ba6017b-9d3a-4636-bcc9-0435c7880ca5)

**Comment by nino-filigran** [comment]
I've reproduced. We should indeed, if the score is revoked and gets above the revokation score again, unrevoke the IOC.
