### ISSUE TITLE
Can't edit status of a relationship

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7267]
## Reproductible steps
- Go to Data > Relationship and click on a relationship
- In the relationship overview, there is a field 'processing status'
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/117bb385-e194-4ee0-959c-cb6273824e60)

 - But this field is not editable in the relationship edition form
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/5122bf53-8822-4797-932d-a30b2fd3f95b)

**Comment by hunxjunedo** [comment]
Hey @Archidoit , can I get assigned ? I'd like to look into this.

**Comment by Kedae** [comment]
Not a bug, the workflow wasn't defined for Relationships
