### ISSUE TITLE
Unecessary error message at sighting edition

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7268]
## Reproductible steps
 - Go to a sighting and open the edition form.
 - Modify a field
 - The 'first seen' and 'last seen' fields appears with errors, than the error disappear and the update of the field is done correctly

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/7771ee59-cd09-44c8-9b7a-4f34f32edd02)

Note: these two fields may be mandatory at edition but not at sighting creation...

**Comment by nino-filigran** [comment]
@Archidoit Not sure to understand the case: where do you put the F? Or what is the field you meant to modify?

Also, it's normal to ask for these fields to be filled, even for update, given that we need them from a business point of view.

**Comment by Archidoit** [comment]
@nino-filigran 
You can modify the description for instance.
The problem is that these fields can be empty...

**Comment by nino-filigran** [comment]
Clear, then we should ensure that these fields can remain empty.
