### ISSUE TITLE
Cannot enrich multiple observables when shift-selecting 

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#7269]
## Environment

Testing (6.1.10)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report and add to it at least 4 domain names
2. Access the report and then go the Observables tab
3. Select the first domain name, press shift and select the last one

## Expected Output

Being able to enrich

## Actual Output

The enrich button is absent. Unable to enrich

**Comment by nino-filigran** [comment]
Reproduced. Additionally, when selecting the "select all" the massive operation does not appear either.
