### ISSUE TITLE
In Threat => Knowledge => Attack patterns: Still old style filters box

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7287]
## Use case

In Threat => Knowledge => Attack patterns: Still old style filters box:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/de6cfd19-5fbe-41ad-a237-64ca215ecfa7)

**Comment by romain-filigran** [comment]
More complete rework of Attack pattern view and filter planned for 6.3

**Comment by Archidoit** [comment]
@romain-filigran  Note: The filters are on the relationship between the threat and the attack patterns. Do we still want the filters to be on the relationships ? or on the attack patterns?
