### ISSUE TITLE
Promote observables to indicators and vice versa in the context of a container should add to container the new entity and the base-on relation

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7294]
## Use case

Promote observables to indicators and vice versa in the context of a container should add to container the new entity and the base-on relation

**Comment by Lhorus6** [comment]
May be a duplicate of this one : https://github.com/OpenCTI-Platform/opencti/issues/6171

**Comment by nino-filigran** [comment]
Yes, it's a duplicate. @SamuelHassine I'm closing this ticket, to only keep one.
