### ISSUE TITLE
In knowledge graph, do not re-apply forces when adding a new entity (working already when adding a new relations)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7298]
## Use case

In knowledge graph, do not re-apply forces when adding a new entity (working already when adding a new relations).

Very frustrating current behaviour:

1. Add dozens of entities
2. Take 10 min to properly position all the nodes and having a very beautiful graphs with manual positionning. 
3. Add 1 new entities

=> Everything you have done is lost....

**Comment by damians-filigran** [comment]
Note this also happens when adjusting the time-selector filter as well

**Comment by damians-filigran** [comment]
It would also be great to preserve and pass-through the current structure (any locked nodes, etc) from an entity KG to the investigation, if one is run

**Comment by nino-filigran** [comment]
@damians-filigran thanks for sharing this, I'll create a specific ticket for the above need. 
Regarding the forces, we're indeed working on it, so that they do mess your graph at least when you've disabled the forces.
