### ISSUE TITLE
When using AI, to generate text, be able to select the language and pre-fill with the user profile lang

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7299]
## Use case

When using AI, to generate text, be able to select the language and pre-fill with the user profile lang

**Comment by damians-filigran** [comment]
Suggest this be extended to "permit entirely customised prompts" in the UI, with editing these as a role capability

**Comment by damians-filigran** [comment]
Note the outcome required from this use case, is for the response from AskAI to be in the user's native language.
