### ISSUE TITLE
Missing number formatter in some dashboard widgets:

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7315]
## Description

Detected in radar charts:
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0cd4c42b-987a-405c-a266-f4af1b06108e)

Canvas charts:
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/e4c059f5-f4da-4bc1-a9e9-b329f3c522f1)

**Comment by nino-filigran** [comment]
On other widgets, when it goes above 1000, we display 1K (and show the hundreds using the decimal, ex 1.23K for 1 230 entities). We need to apply this to: 
- canvas
- radar
- horizontal bars
