### ISSUE TITLE
Be able to use OR operator in playbook filters

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7318]
## Use case

Be able to use OR operator in playbook filters

**Comment by romain-filigran** [comment]
@SamuelHassine : For me it's already covered.

![Capture d'écran 2024-06-19 111233](https://github.com/OpenCTI-Platform/opencti/assets/171329346/505c9b03-f280-4b6a-ba42-1532a0d5cbed)

**Comment by romain-filigran** [comment]
For me it's already covered.
