### ISSUE TITLE
Effect of drawer is not correct in Update dropdown on "latest relationships" widget in the overview of entities

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7329]
## Description

https://filigran.octi.filigran.io/dashboard/observations/observables/1d295c4a-1a91-4dbc-945b-c9bec75c46ac

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/da1c1375-7222-4a39-98d1-58bc341ba9c8)

Drawer open from right but missing the "effect", should be slower.

**Comment by SarahBocognano** [comment]
Is it done ? I see the label "done" here but still open ?

**Comment by CelineSebe** [comment]
I tested it, and the effect was correct for me. I would like to have your opinion.

**Comment by SarahBocognano** [comment]
It was correct for me too. That's why I asked why it's still open
