### ISSUE TITLE
[Export] Exporting a container too large fail

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7332]
## Description

When I try to export a [report containing 8K+ entities](https://testing.octi.staging.filigran.io/dashboard/analyses/reports/3ba859df-b1fd-4bd1-bcf8-8307a31a8dc1/files), I get an error.

I tested it on "testing" instance but also in one of our SaaS instance.

## Environment

OOCTI 6.1.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report (or you can use [this one](https://testing.octi.staging.filigran.io/dashboard/analyses/reports/3ba859df-b1fd-4bd1-bcf8-8307a31a8dc1))
2. Add 8K+ entities inside, tips:
    - Go to "Observations > Observables",
    - Play with the "Platform creation date" filter to obtain 8-9K entities
    - Select all (the checkbox)
    - Add in container (the button in the bottom right corner)
3. Go to the "Data" tab
4. Export the report : JSON + full export

## Screenshots (optional)

![MicrosoftTeams-image (1)](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b8e383da-9e33-4578-b54b-98737c26f422)
![MicrosoftTeams-image](https://github.com/OpenCTI-Platform/opencti/assets/70956706/2cf356da-c287-43a6-a6f5-73d904aab7bf)

**Comment by richard-julien** [comment]
Looks like pre control code generate this error and seems to be a pre control that could be removed.

We can try to remove this part of the code in opencti_stix2.py and check if everything is still well filtered.
```
        # Container
        if "objects" in entity and len(entity["objects"]) > 0:
            object_ids = list(map(lambda e: e["standard_id"], entity["objects"]))
            export_query_filter = self.prepare_id_filters_export(
                id=object_ids, access_filter=access_filter
            )
            filtered_objects = (
                self.opencti.opencti_stix_object_or_stix_relationship.list(
                    filters=export_query_filter, getAll=True
                )
            )
            entity["objects"] = filtered_objects
```
