### ISSUE TITLE
Generating an Indicator from an URL Observable adds the URL clickable in the description

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7340]
## Description

Generating an Indicator from an URL Observable puts the malicious URL in the Indicator description. URL that is clickable.

However, the underlying security problem is less serious, as the platform displays a pop-up “Do you want to browse this external link?"

ps: it's not a bug as such, I'll let you recategorize it if necessary.

## Environment

OCTI 6.1.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an URL Observable.
2. Generate an Indicator based on this URL Observable.
3. Look in the description of the Indicator

## Expected Output

Defang the URL in the description of the Indicator

## Screenshots

![Screenshot 2024-06-10 205904](https://github.com/OpenCTI-Platform/opencti/assets/70956706/9e97348e-d887-4a06-949f-52f4b3aa233e)

**Comment by Jipegien** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/6657
