### ISSUE TITLE
Issue with public dashboard name and case sensitivity

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#7344]
## Description

I'm seeing some strange behaviour on the public dashboard regarding the "Dashboard URI Key" and sensitive/insensitive case which I'll try to describe here.

1. Create a dashboard
2. Share it and give it a public name: ‘TEST001’.
3. Access the dashboard: http:/{opencti}/public/dashboard/TEST001 (normally OK)
4. Delete the sharing (the public dashboard)
5. Recreate a public dashboard but this time with the public name: ‘test001’.
6. Access the Dashboard: http://{opencti}/public/dashboard/test001 (normally OK)
7. Try again to access the old dashboard (http:/{opencti}/public/dashboard/TEST001) and in this case instead of being redirected to the authentication page (because it doesn't exist/no longer exists), I can see the widgets on my dashboard with errors in each widget.

![Capture d'écran 2024-06-10 185834](https://github.com/OpenCTI-Platform/opencti/assets/171329346/259e6e50-ac6d-463f-9770-f4f5a76f2238)

Probably a problem with the case of the generated "Dashboard URI Key". Perhaps it would be better to generate a URI key always in lower case.

## Environment

1. OpenCTI version: 6.1.10

**Comment by SarahBocognano** [comment]
I think it can be linked to : https://github.com/OpenCTI-Platform/opencti/issues/7311
