### ISSUE TITLE
Import Stix Connector SSL Error

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#7349]
## Description

When attempting manual import of stix bundle, the import fails with error "HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /storage/get/import/global/2024-05-09T13_14_56Z_(export-stix-report)_HEADLACE%20(1).json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"

## Environment

1. OS: Ubuntu
2. OpenCTI version: 6.1.10
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to https://yourinstance:8443/dashboard/data/import and manually import stix bundle, make sure instance is running HTTPS

## Expected Output

The import should upload and the user will validate.

## Actual Output

error "HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /storage/get/import/global/2024-05-09T13_14_56Z_(export-stix-report)_HEADLACE%20(1).json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"

## Additional information

This worked on prior versions, all our opencti instances now fail manual stix imports.

## Screenshots (optional)

**Comment by romain-filigran** [comment]
Hello.

It appears that the certificate deployed on your OpenCTI instance is not recognised in the certification chain.

Can you try temporarily disabling SSL verification in the STIX import connector by adding a new Docker environment variable: 
OPENCTI_SSL_VERIFY=false

**Comment by explorecti** [comment]
@romain-filigran , this did not fix the issue and the error still remains. The current certificate has been running on the OPENCTI platform for over a year without an issue until now, something code related has changed that is now causing this issue. Please advise, thank you.

**Comment by explorecti** [comment]
Please provide a status update, currently all instances are unable to ingest manual importation of STIX. Works fine running port 8080, but 8443 fails and no working resolution has been provided. Thanks

**Comment by romain-filigran** [comment]
Hello @explorecti.
Could you share the complete stacktrace of the error mentioned above ? Is this issued by the "import-file-stix" connector ?
By the same way, could you share the configuration file that you used ?

**Comment by explorecti** [comment]
@romain-filigran, Yes this is issued by the "Import-file-stix" connector.

Connector error log:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 349, in _data_handler
    message = self.callback(event_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-import-file-stix/import-file-stix.py", line 31, in _process_message
    file_content = self.helper.api.fetch_opencti_file(file_uri)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 380, in fetch_opencti_file
    r = self.session.get(fetch_uri, headers=self.request_headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /storage/get/import/global/2024-05-09T13_14_56Z_(export-stix-report)_HEADLACE%20(1).json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

DOCKER COMPOSE:

version: '3'
services:
  redis:
    image: redis:7.2.5
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VER}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      # Comment-out the line below for a cluster of multiple nodes
      - discovery.type=single-node
      # Uncomment the line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - thread_pool.search.queue_size=5000
      - logger.org.elasticsearch.discovery="ERROR"
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VER}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - /data/kibana:/data/kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - opencti
  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data
    restart: always
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_NODENAME=rabbit01@localhost
    volumes:
      - amqpdata:/var/lib/rabbitmq
    restart: always
  opencti:
    image: opencti/platform:${octi_ver}
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8443
      - APP__BASE_URL=${OPENCTI_BASE_URLs}
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - APP__HTTPS_CERT__KEY=${HTTPS_CERT_KEY}
      - APP__HTTPS_CERT__CRT=${HTTPS_CERT_CRT}
      - APP__HTTPS_CERT__REJECT_UNAUTHORIZED=false
      - APP__GRAPHQL__PLAYGROUND__ENABLED=true
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - REDIS__PASSWORD=${REDIS_PASSWORD}
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED=false
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "8443:8443"
    volumes:
      - /etc/pki/tls/private:/certs
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-document:
    image: opencti/connector-import-document:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    restart: always
    depends_on:
      - opencti
  connector-alienvault:
    image: opencti/connector-alienvault:${octi_ver}
    environment:
      - OPENCTI_URL=${OPENCTI_URLs}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ALIENVAULT_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_CONFIDENCE_LEVEL=95 
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=error
      - ALIENVAULT_BASE_URL=${ALIENVAULT_URL}
      - ALIENVAULT_API_KEY=${ALIEN_API_KEY}
      - ALIENVAULT_TLP=White
      - ALIENVAULT_CREATE_OBSERVABLES=true
      - ALIENVAULT_CREATE_INDICATORS=true
      - ALIENVAULT_PULSE_START_TIMESTAMP=2024-01-01T00:00:00                  
      - ALIENVAULT_REPORT_TYPE=threat-report
      - ALIENVAULT_REPORT_STATUS=New
      - ALIENVAULT_GUESS_MALWARE=false                                        
      - ALIENVAULT_GUESS_CVE=false                                            
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=FileHash-MD5,FileHash-SHA1  
      - ALIENVAULT_ENABLE_RELATIONSHIPS=true                                  
      - ALIENVAULT_ENABLE_ATTACK_PATTERNS_INDICATES=false                     
      - ALIENVAULT_INTERVAL_SEC=1800
    restart: always

volumes:
  certs:
    driver: local
  esdata:
  s3data:
  redisdata:
  amqpdata:
  kibana:

**Comment by romain-filigran** [comment]
After investigation, it appears that "import-document" and "import-file-stix" theoretically cannot work with invalid or self-signed certificates. Work needs to be done on this. However, we are unable to understand how this has worked in the past. Have your certificates changed recently? Are they still valid?

**Comment by explorecti** [comment]
Yes the currently used certs have been working for over a year running without issue on the OPENCTI platform. They are all still valid. There are a total of six instances of OPENCTI being used and they are all failing except one instance because that one is running port 8080 http.

**Comment by helene-nguyen** [comment]
Willbe fixed with #684
