### ISSUE TITLE
[Dashboard] Multiple filters with the same name

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7350]
## Description

When I want to filter on "Start date", several filters appear without me understanding why. Are these duplicates? Are these different filters but with the same name?

## Environment

OCTI 6.1.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a widget list
2. Use the knowledge perspective
3. Look for "start date" filter in "Dynamic source/target filters"
-> Several appear

## Additional information

By the way, I don't know if it's a bug but I don't have a "stop date" filter

## Screenshots 

![Screenshot 2024-06-11 183539](https://github.com/OpenCTI-Platform/opencti/assets/70956706/401ed61d-66e4-43d9-91d6-dbadc5ce4186)

**Comment by romain-filigran** [comment]
Hello

I admit it's not very practical. We'll see how to propose a response to this behavior.

**Comment by Archidoit** [comment]
There are no 'stop date' because it is called 'end date'.

**Comment by Archidoit** [comment]
The problem is because there is both an attribute with 'start date' label for Event and Network Traffic. We should maybe rename this attribute translations in : 'Event start date', 'Network traffic start date' , etc
