### ISSUE TITLE
External References are not visible in the Data/Entities view

### ISSUE THREAD

**Issue by sbjzn** [LuatixHQ/opencti#7354]
## Description

External References are not visible in the Data/Entities view, it is impossible to filter for external references.

## Environment

1. OS: Ubuntu 22.04 LTS
2. OpenCTI version: 6.1.10
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the Entities view
2. Attempt to filter for External References

## Expected Output

Ability to filter and manage external references in the entities view

## Actual Output

Not able to do this

## Additional information

N/A

**Comment by romain-filigran** [comment]
Hello. 
External references are not actually listed in the Data/Entities view, but you can manage them from the view dedicated to external references: https://{your_opencti_instance}/dashboard/analyses/external_references.

Does this meet your needs?

**Comment by sbjzn** [comment]
Well, I noticed this due to https://github.com/OpenCTI-Platform/opencti/issues/7210.
But the views appear to be similar, I find it weird however that they are not visible in the entities view, as that view has almost every other object in it.

However I assume this might not be a bug, and just a design choice. Which would leave it up to you to determine if they should be visible there or not.

**Comment by romain-filigran** [comment]
This choice was made because external references are not considered to be pure SDO/SCO STIX objects like objects displayed in the Data/Entity view.

**Comment by sbjzn** [comment]
Okay, closing this then. Thanks :+1:
