### ISSUE TITLE
CI improvement: client-python build once and fail fast on test-api

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#7359]
## Description

1. Build the client python once to avoid this flake=>
```
  note: This error originates from a subprocess, and is likely not a problem with pip.145s
503  ERROR: Failed building wheel for pycti145s
504Failed to build pycti145s
505ERROR: Could not build wheels for pycti, which is required to install pyproject.toml-based projects
```
2.  Add the "bail 1" parameter to backend api test to fail as soon as one test is failing (instead of running the remaining one)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by labo-flg** [comment]
Reproduced on my side 2 times (raw server fails to start with this error), restarted the build and it worked.
