### ISSUE TITLE
Adding a child capability does not add the parent capability

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#7370]
## Description

- Adding a child capability does not add the parent capability

## Environment

1. OS (where OpenCTI server runs): Windows 11
2. OpenCTI version: 6.1.10
3. OpenCTI client: backend
4. Other environment details: Local and Testing

## Reproducible Steps

1. Create a new role
2. Update this role
3. Tick a capability that has a parent capability (ie : 'Manage creadentials') without first ticking the parent capability
4. The 2 capabilities are ticked

## Expected Output

- the role contains the 2 capabilities

## Actual Output

- the role only contain the child capabilitie

## Screenshots

- Result after ticking only the child capability (Manage credential)
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/8bddbfa2-043c-414b-9d5f-1c0a85c4bd2a)
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/d787ef7c-8cd7-4146-ba6f-74f2d61270de)

- Result after ticking the two capabilities (Access to admin + Manage credential)
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/a3decdd4-5abf-4527-84ba-16e57bd181fa)
![image](https://github.com/OpenCTI-Platform/opencti/assets/102748848/3a84c790-9df7-4dc8-b80f-a359ebf7a2b2)

**Comment by nino-filigran** [comment]
@frapuks just to be clear, even though it's displayed in UI, the user is not assigned the parent capability? Does it also happen for existing roles?

**Comment by nino-filigran** [comment]
Not a bug, but rather a way that we write things in DB. Will followup internally.
