### ISSUE TITLE
Display modification feature for widgets that has long labels

### ISSUE THREAD

**Issue by cr-KethanPabbi** [LuatixHQ/opencti#7380]
## Use case

No label is cut off so the visualisation is more clear and no additional information is required while communicating with various teams

## Current Workaround

Currently using the graphs as is. The labels are cut is not ideal but when using them in presentations trying to explain it better

## Proposed Solution

Custom margins like other visualisation platforms have. A way to make sure the whole label is displayed even at the cost of reducing the length of the bars in a bar chart for example

## Additional Information

would be awesome if the labels in charts like bar, donut and others can be fully displayed!

![Screenshot 2024-06-14 at 11 20 03](https://github.com/OpenCTI-Platform/opencti/assets/152976980/b916ded3-b83a-4134-ad51-56f956e33cde)
![Screenshot 2024-06-14 at 10 02 42](https://github.com/OpenCTI-Platform/opencti/assets/152976980/a357456c-28ef-4b45-8820-2e792a94dcfa)

## If the feature request is approved, would you be willing to submit a PR?

yes

**Comment by nino-filigran** [comment]
@cr-KethanPabbi It is not something that we would invest time in. I see that you're wiling to create a PR for it though, so feel free to raise it when you want!
