### ISSUE TITLE
Artifact cannot be delete from trash if the referenced file is missing on S3

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#7382]
## Description

When for some reason the uploaded file is not on S3 anymore, it's impossible to delete the artifact from UI.
Created from discussion on https://github.com/OpenCTI-Platform/opencti/issues/7352

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

On a local instance
1. Create Artifact from any file
3. Go on minio ui, inside the bucket > /import/Artifact/ARTIFACT_ID
4. delete the file
5. on opencti web ui: delete the Artifact (tested with the background task)
6. go to trask
7. try to delete permanently the Artifact: it's failing with `Load file from storage fail` error, and the Artifact is still in trash.

## Expected Output

Artifact is deleted

## Actual Output

Artifact stay in trash

## Additional information

Not tested for file that can be attached to other entity than Artifact, please test it too.

## Screenshots (optional)
Delete permanently from background task:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/8c0dd150-d0f0-4562-8c2c-371dd53aab47)

![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/af8f1b3f-20bc-48d3-8bf0-119c11214de0)

Delete permanently directly:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/536420ff-4a92-480a-ac6a-01dc882b0e74)

**Comment by JeremyCloarec** [comment]
I'm not able to reproduce it. Do you still have the same behavior, or was it fixed for you also?

**Comment by aHenryJard** [comment]
Fixed in currrent master version as today.
