### ISSUE TITLE
add support language korean into i18n code

### ISSUE THREAD

**Issue by Fhwang0926** [LuatixHQ/opencti#7385]
## Use case

add support language korean into i18n code
I use this platform in security education, but if there is Korean, I think I can use it more naturally

## Current Workaround

add i18n file

## Proposed Solution

add i18n file

## Additional Information

nothing

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by Jipegien** [comment]
It is something we will not prioritize. So, feel free to propose a PR to do it.
