### ISSUE TITLE
Guidance Needed for Upgrading OpenCTI from Version 5.7.4 to Version 6.1.11 Using Docker

### ISSUE THREAD

**Issue by Security-Team12** [LuatixHQ/opencti#7386]
## Description

Dear Friends,

I am currently planning to upgrade our OpenCTI deployment from Version 5.7.4 to Version 6.1.11 using Docker. Could you please provide guidance or any important recommendations to ensure a smooth upgrade process?
I have missed many major updates. Will it cause any issues if I upgrade directly to version 6.1.11 ? I would appreciate any critical guidance on this matter.

Thank you very much for your assistance.

@richard-julien @SamuelHassine 

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: {OpenCTI 5.7.4 }
3. OpenCTI client: Docker

**Comment by Security-Team12** [comment]
Will it cause any issues if I upgrade directly to version 6.1.11? Should I first upgrade to an intermediate version before moving to the latest version?

**Comment by labo-flg** [comment]
We had a major change to the way confidence levels are handled in the platform.
You might want to have a look at this blog post for more information: https://blog.filigran.io/breaking-change-evolution-of-the-way-connector-streams-and-feeds-import-data-in-opencti-d10d7eb4407e

**Comment by Jipegien** [comment]
Plus:
- do a backup first
- create a pre-prod env from this backup
- try to upgrade the preprod. It will probably need to go through intermediate version.
- If success, apply to your prod.

**Comment by Security-Team12** [comment]
Thanks a lot for your assistance.
@Jipegien @labo-flg
