### ISSUE TITLE
Mandatory External references are still on error when filled on creation form 

### ISSUE THREAD

**Issue by ValentinBouzinFiligran** [LuatixHQ/opencti#7388]
## Description

Mandatory External references are still on error when filled on creation form 

## Reproducible Steps

- On customization form, enable "Enforce references" for malware analysis
- Open the malware analysis creation form
- Complete all mandatory fields
- On create, i have an error on the external references fields

![image](https://github.com/OpenCTI-Platform/opencti/assets/162980256/9096db65-e48c-4468-890d-54a5abcc616a)

**Comment by SarahBocognano** [comment]
Should be fix with this PR: https://github.com/OpenCTI-Platform/opencti/pull/6727/files

**Comment by SarahBocognano** [comment]
After testing, the merge of the PR: https://github.com/OpenCTI-Platform/opencti/pull/6727/files fixed the bug
