### ISSUE TITLE
[CSV Mapper] Not possible to add labels to URL representation

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7419]
## Description

In CSV mapper, it is possible to create representations for labels. Once these representations exist, they can be used in representations of other entities to add the label to them. However, the "URL" representation does not find the existing labels ("no options").

I tried with other entities (e.g. IPv4) and it works. However, I have not tried all possible entities. Maybe there are others in the same state (i.e. with the bug).

## Environment

OCTI 6.1.11 (testing and SaaS platform)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV mapper
2. Create a representation Label
3. Create a representation URL
4. Try to add the label on the URL
-> "no options"

![Screenshot 2024-06-19 083011](https://github.com/OpenCTI-Platform/opencti/assets/70956706/7427dce6-442b-48b5-98bd-6dfd12cd380c)

#### Example with an IPv4 representation in the meme mapper

![Screenshot 2024-06-19 083525](https://github.com/OpenCTI-Platform/opencti/assets/70956706/ab81742d-2a88-4a33-b166-2303ec42184c)

**Comment by Lhorus6** [comment]
The problem seems to exist also with external references, for example

![image-20240624-144502](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b09cb838-013e-4308-8079-9e2ba4ee62ca)

**Comment by CelineSebe** [comment]
@Lhorus6 Yes, the markings and author too.. It concerns all the "RelationsRef" for URL

**Comment by Lhorus6** [comment]
Thanks for the update. 
NB: The problem doesn't only appear on URLs. In my last post for example it's a "User agent".

**Comment by CelineSebe** [comment]
Issue resolved ✅ 
I found 20 new cases with other observables (bank account, credentials, etc.) that I resolved as well.

**Comment by Lhorus6** [comment]
@nino-filigran, @CelineSebe,
We have similar problems elsewhere. For example, with "Kill chain phase" representations in the "Uses" relationship:

<img width="623" alt="image" src="https://github.com/OpenCTI-Platform/opencti/assets/70956706/799d8a23-56f1-4efd-9714-14691bb07b43">

Do I have to create a new issue for this ?

**Comment by nino-filigran** [comment]
We know that we need to improve CSV yes, so if not a ticket, at least the list of things that do not work well/not possible to map currently. But the best remains a ticket.

**Comment by Lhorus6** [comment]
Okay, I made a new issue : https://github.com/OpenCTI-Platform/opencti/issues/7565
This is not an enhancement request, but a bug fix in my opinion (exactly like this issue here)
