### ISSUE TITLE
In Content tab of containers, when selecting "main content", it is displayed "No file selected" on the bottom

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7430]
## Description

In Content tab of containers, when selecting "main content", it is displayed "No file selected" on the bottom

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/9780de68-47ad-4561-ba2f-c98d21ec0128)

**Comment by JeremyCloarec** [comment]
This will be fixed with ongoing PR https://github.com/OpenCTI-Platform/opencti/pull/7262
