### ISSUE TITLE
Bad .docx file upload at artifact creation

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7434]
## Description
If you create an artifact with a .docx file, the file name and extensions are changed, leading to errors.

## Reproducible Steps
- Create an artifact by selecting a .docx file : 
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/3b1a5995-0810-4ddc-8b37-27849d446e28)

- The artifact is created but the file name is incorrect and always 'Content_Types.xml'
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/e5db3e12-6563-4234-a7e0-f05466dcc0a0)

- In the Data tab of the created artifact, the file name and extension are not correct and the import failed
![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/dc2864df-4188-4f4d-967c-b8048c341b84)

**Comment by nino-filigran** [comment]
I think, the real bug is indeed the fact that the file name & extension. An error would happen anyway I guess at the import since only the following types of doc can be imported (using import doc):
PDF file
Text file
HTML file
CSV file
MD file

Therefore, because the doc type is unsupported, it seems normal that we cannot import it.

**Comment by aHenryJard** [comment]
@nino-filigran I'm not sure on what is expected here, is it restrict artifact upload to (pdf/text/html/csv/md) ?

**Comment by aHenryJard** [comment]
I tried in another screen than artefact (report in the screenshot) and the mime type is correctly detected:
![image](https://github.com/OpenCTI-Platform/opencti/assets/3634942/a40d5214-fa94-45c8-9b44-d7a2cf5abba6)

**Comment by nino-filigran** [comment]
I would say the same as your report: allowing it, but not change it to XML. Does that sound correct to you also @romain-filigran ? PS: love the title of your doc 🤣

**Comment by romain-filigran** [comment]
We shouldn't restrict the types of file supported in the "artifact" view, it should be possible to upload any type of file. And mimetype file detection shouldn't be a problem. In this case, the mimetype of the docx file uploaded as an artifact must be "application/vnd.openxmlformats-officedocument.wordprocessingml.document".

Does this answer the question?
