### ISSUE TITLE
Not editable filter in Knowledge tab of an entity

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7445]
## Reproducible Steps
- Go to an entity overview (ex: a threat actor)
- Go to the Knowledge tab
- Go to the 'Indicators' panel

## Actual output
- A filter is automatically set ('contains XX') and is not editable but the cross is present and we can open the panel if we click on 'contains' and add entities in the filter

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/105f92e4-ef19-4931-934f-c5e152a7cd2d)

## Expected output
The cross doesn't appear
We should not be able to open the edition box of the filter

**Comment by nino-filigran** [comment]
Validated! Additionnally, if there's no value in the "contained", the screen returns an error. In that case, we should only have an emty screen, not an error.
