### ISSUE TITLE
Inconsistency in numbers between dashboard and list

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7454]
## Description

When we make dashboards, or look at the numbers displayed in the dashboards of entity "Knowledge" tabs, the values may differ from the lists.

## Environment

OCTI 6.1.12

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a widget "horizontal bar" and "knowledge graph" perspective, with this filter (cf https://testing.octi.staging.filigran.io/dashboard/workspaces/dashboards/d89c9638-fd7c-42a7-a3b0-97c452f36307)

![Screenshot 2024-06-24 160318](https://github.com/OpenCTI-Platform/opencti/assets/70956706/c88213d9-bd48-4eaa-84f5-9ff0e84662f3)

![Screenshot 2024-06-24 160311](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b5968068-4ed3-4b85-b012-ebe329bf2f88)

2. Compare the value with what you can find in the list view "Data > relationships".

![Screenshot 2024-06-24 160331](https://github.com/OpenCTI-Platform/opencti/assets/70956706/81f5a18d-a6f2-4984-9671-ea3b572160a2)

## Expected Output

Obtain the same values.

## Additional information

There are also inconsistencies in the "knowledge" tab. (see this entity for example : https://testing.octi.staging.filigran.io/dashboard/locations/countries/871f5e14-488a-4f21-adb6-733a70565b8b/knowledge/overview)

![Screenshot 2024-06-24 161041](https://github.com/OpenCTI-Platform/opencti/assets/70956706/f1859dac-81e5-4d19-af53-84e28e3673bb)

![Screenshot 2024-06-24 161029](https://github.com/OpenCTI-Platform/opencti/assets/70956706/a10d7339-282b-44ad-9a20-1742a1e9f5e9)

**Comment by Kedae** [comment]
I will check but I think this is the difference between the number of entities and the number of relationships. @nino-filigran a thought ?

**Comment by Lhorus6** [comment]
For the Knowledge tab (what's in the "Additional information" section) I don't know. But for the rest, both (my widget and the list view) are based on relationships, so it shouldn't be different I think.

**Comment by nino-filigran** [comment]
Maybe the inferred relations are not well counted? I guess you're in bypass with all markings right @Lhorus6 ? Could it be relations that are using the relation as source (ex: (entity A targets USA) Targets entity B)?

**Comment by SamuelHassine** [comment]
Taking care of this.
