### ISSUE TITLE
Malware Infrastructure Display Issue

### ISSUE THREAD

**Issue by explorecti** [LuatixHQ/opencti#7479]
## Description

When a relationship of Malware USES Infrastructure exists, Infrastructure is included under Malware/Knowledge Infrastructure, but Malware is not shown under Infrastructure/Knowledge/Malware. In addition Infrastructure/Knowledge/Malware relationships is displayed for relationships Malware CONTROLS Infrastructure.

## Environment

1. OS: RHEL8
2. OpenCTI version: 6.1.11
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to http://opencti:8080/dashboard/arsenal/malware/UUID_from_Malware/knowledge/relations/UUID_from_Infrastructure
2. Now navigate in reverse http://opencti:8080/dashboard/arsenal/malware/UUID_from_Infrastructure/knowledge/relations/UUID_from_Malware

## Expected Output

The UI should show Infrastructure USES Malware

## Actual Output

The Malware is not shown

**Comment by nino-filigran** [comment]
On the top of this, because uses is not displayed, it also means we cannot create create infra USES malware from this same view.

**Comment by lndrtrbn** [comment]
Seems to be more related to the relation `uses` itself as I can also reproduce with "Malware uses Tool"
