### ISSUE TITLE
Different roles and groups see different data in the dashboard.

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#7495]
OpenCTI Version : 6.1.10

In the photo below, **the left side** is the dashboard screen for a user with the Administrator, Default Role and Group,
**on the right** is the dashboard for a user with the External role and Group.
![11](https://github.com/OpenCTI-Platform/opencti/assets/19428462/7bd24097-82d1-4035-818f-0700810d82b8)
.
.
.
The data that exists in the platform is the same, so I don't understand why the two dashboards show different data.

Is this a bug?

Your answer would be greatly appreciated.

**Comment by nino-filigran** [comment]
@misohouse to help you out, can you provide us with: 
- capabilities associated with each role 
- marking associated with each group
- organisation associated with each user (to which organisation they belong)
- if you have set a platform organisation (visible in setting/security/policies)

**Comment by misohouse** [comment]
@nino-filigran 

Here is information about role and group.
.
.
.
[1] Administrator Role
![11](https://github.com/OpenCTI-Platform/opencti/assets/19428462/2fb54841-61c1-45ee-9d4a-b810478d2199)
.
.
[2] Default Role
![22](https://github.com/OpenCTI-Platform/opencti/assets/19428462/7e65dbe7-a19b-4033-bbe7-a15bd5a86a08)
.
.
[3] External Role
![33](https://github.com/OpenCTI-Platform/opencti/assets/19428462/9bab5527-3265-417e-a724-d9583b54d1f7)
.
.
[4] External account information
![44](https://github.com/OpenCTI-Platform/opencti/assets/19428462/ff1465b7-db3f-4e2d-98f0-3cde2e8e5f4f)
.
.
[5] Administrator account information
![55](https://github.com/OpenCTI-Platform/opencti/assets/19428462/1797fb8e-4460-436e-b4f2-10957a525476)
.
.
If you need more information, I'll add it.

**Comment by nino-filigran** [comment]
Yep, I miss the allowed marking for your users (screenshot do not display them)

**Comment by nino-filigran** [comment]
Can you provide the allowed marking fro your groups?

**Comment by misohouse** [comment]
@nino-filigran 
Sure, here it is.
.
.
.
[6] Administrator Groups
![ad](https://github.com/OpenCTI-Platform/opencti/assets/19428462/371f2d58-2648-4b03-aefb-b22a6d2eaad5)
.
.
[7] Default Groups
![de](https://github.com/OpenCTI-Platform/opencti/assets/19428462/24627dd1-59ce-4ccf-8af3-182e5bb0f4c1)
.
.
[8] External Groups
![ex](https://github.com/OpenCTI-Platform/opencti/assets/19428462/33644ef7-4672-4add-8111-2496d3312bbb)

**Comment by nino-filigran** [comment]
To recap my understanding, users of external group (first screenshot on the right in your ticket) see less info than users from default/admin (first screenshot on the left).

Based on your responses and screenshots, the reason is simple: your external group have less marking than your default admin (in the "allowed markings"). They cannot see anything above TLP:AMBER, which is the reason you have some discrepencies.

**Comment by misohouse** [comment]
@nino-filigran

If you're right, shouldn't we rather see less information in the External account?

If you look at the screenshot I posted at the very beginning, it actually shows less information in the Administrator account (the dashboard shows no data).

Note that most data is currently written as TLP:GREEN and TLP:CLEAR.

Am I misunderstanding something?

**Comment by nino-filigran** [comment]
You're completly right, sorry about this, I've mixed up your dashboards and focused on the numbers widgets. I'll keep investigating!

**Comment by nino-filigran** [comment]
@misohouse  sorry for not following up this earlier. Do you still encounter the issue?

**Comment by misohouse** [comment]
@nino-filigran 

Hi, I'm still experiencing the same issue and waiting for a solution.

**(Administrator)**
![11](https://github.com/user-attachments/assets/60b5f10c-3b47-487c-8bbd-bed365ada387)


**(External)**
![22](https://github.com/user-attachments/assets/b85ee2c4-0c08-4e47-84ea-5ed2a3bc5d91)

**Comment by nino-filigran** [comment]
@misohouse we're still trying to understand what could be the issue, however, we struggle with this since we're not able to reproduce at all your situation. I guess since then you've upgraded to most recent version, right? And tried to clear your local storage?

**Comment by Kedae** [comment]
Hi @misohouse when you have empty widget with your administrator do you have any log ? Could you provide a support package after accessing the dashboard with your admin ?

**Comment by misohouse** [comment]
> @misohouse we're still trying to understand what could be the issue, however, we struggle with this since we're not able to reproduce at all your situation. I guess since then you've upgraded to most recent version, right? And tried to clear your local storage?

Yes I am currently using the latest version, and the local storage is not being cleared because it has existing data.

**Comment by nino-filigran** [comment]
We're still having issue on our side to reproduce the issue, making the investigation stuggling for information. Could you please provide a support package as requested above when you have an emtpy widget?

**Comment by misohouse** [comment]
@nino-filigran 

Ah I solved the problem!

I changed the date type to “Technical date” in the settings on the bottom right of the platform and it looks fine :)
![11](https://github.com/user-attachments/assets/64b9854d-ec2c-4eb9-8eb7-a68375f0cc7e)
![22](https://github.com/user-attachments/assets/f3303641-d8b3-408c-ae74-396ed0dcf427)

**Comment by nino-filigran** [comment]
I'm glad to hear it @misohouse  thanks for informing us! I'm closing the bug as a result. Feel free to re-open it if you still have an issue/comment.
