### ISSUE TITLE
Marking definition display issues: text (width) + borders on first element with multiple markings

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7515]
## Use case

Border on AMBER in list (first + multiple):

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/2af8b144-7ae5-43f6-9aa6-eeb781429abc)

Also, marking definition default width should be displayed fully (increase the width).

**Comment by Jipegien** [comment]
Ensure full display in list for most common marking type: TLP.

**Comment by labo-flg** [comment]
not reproducible on every list though.
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/31474ed6-1a32-4f2b-98f1-ac75d1383045)

Which view is it please?

**Comment by labo-flg** [comment]
nevermind, found it.
Strill looks good though 🤔

![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/8e88ef5f-7fe7-4431-a831-f5be64d8c71a)

**Comment by SamuelHassine** [comment]
Also, this is not only the text, but also the border on home which is wired for the first element. Not same amount of pixels in the border bottom.

**Comment by SamuelHassine** [comment]
@labo-flg It is when this is the first element in the list and there are multiple markings.

**Comment by SamuelHassine** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/8fb21b27-b546-483c-8c88-306555b2c69b)

All borders are not correct.

**Comment by lndrtrbn** [comment]
For border issue: this is due to implementation of table itself. Do we want to take time to investigate on this knowing that those datatables has a refacto ongoing ? @Jipegien 

I can still fix the width issue though

**Comment by SamuelHassine** [comment]
@Jipegien @labo-flg @lndrtrbn:

It is happening in all tables: 

![image](https://github.com/user-attachments/assets/c27c532d-19d8-433f-a3d4-0c4e346c7898)

I think we can fix this now and not waiting for new data table please.

**Comment by lndrtrbn** [comment]
Which browser are you using? I cannot reproduce locally or on testing

**Comment by lndrtrbn** [comment]
I think this is outdated now we have new data table component. I can't find any issue locally or testing platform.
@Jipegien @SamuelHassine

**Comment by Jipegien** [comment]
can't reproduce.
