### ISSUE TITLE
[Max confidence level] Error "confidence insufficient" on Observable 

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7520]
## Description

When we run the JoeSandbox connector on an artifact, we get this error message: 

"User max confidence level is insufficient to update this element"

Important information: there is no "confidence level" on Observables (and an Artifact is an Observable)...

However, some information was added on the Artefact. So it looks like the connector worked fine, but there's this error.

## Environment

OCTI 6.2.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open an Artefact,
2. Run the Joe Sandbox connector.

## Screenshots

![Screenshot 2024-06-28 141156](https://github.com/OpenCTI-Platform/opencti/assets/70956706/caea57a4-3ba2-4aae-907e-1252d06e2e0e)

**Comment by helene-nguyen** [comment]
@Lhorus6 Does the `element_id` that the connector is trying to update is an observable ?

**Comment by Lhorus6** [comment]
@nino-filigran From my point of view, it's not a connector problem, but a platform problem. There is no confidence level on Observables, so why do we have this error?

**Comment by labo-flg** [comment]
Yes this is very strange indeed ; I'm investigating on the backend side.

**Comment by labo-flg** [comment]
I can confirm that the code is very clear about this: if the entity type has no confidence attribute in the data model (like Artifact), confidence check is always granted.

**Comment by labo-flg** [comment]
like Helene said, could we verify if the element id in the error corresponds really to an Artifact ?

**Comment by Lhorus6** [comment]
I checked, this is the ID of the Indicator linked to the Artifact on which the connector is run 🤔

**Comment by helene-nguyen** [comment]
@Lhorus6 Ok, so when you enrich the artifact, there are 2 behaviors: you can create new related entities or update the existing one if it already exists. This error show us that it cannot update the related indicator but could you tell us if the artifact has new informations?

**Comment by Lhorus6** [comment]
Yes, apparently he did two actions:
- Replaced the score,
- Add external ref

![Screenshot 2024-07-03 121134](https://github.com/OpenCTI-Platform/opencti/assets/70956706/5231fba4-e59e-4853-a31e-fd663c8da6cc)

**Comment by nino-filigran** [comment]
@Lhorus6 @labo-flg @helene-nguyen is this still an issue?

**Comment by helene-nguyen** [comment]
We talked about it, the artifact is well updated when we enrich but not the Indicator because confidence level of the user don't allow this action. 
@labo-flg I think it is a normal behavior right ?
If yes, we can close the issue :)

**Comment by labo-flg** [comment]
This is likely the explanation, yes.

**Comment by nino-filigran** [comment]
Ok great, thank you both. Closing this issue then.
