### ISSUE TITLE
Incorrect loader / placeholder in knowledge lists

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7523]
## Description

Current:
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/81ca8973-3246-444a-870d-60e26ec78f98)

Should be something like this:
![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/8a3c037e-908c-4d59-98f8-23e1cb487d46)

**Comment by nino-filigran** [comment]
To be clear, it needs to be fixed on following entities 
- Incidents
- All threats (Threat Actor individual, Threat Actor Group, Intrusion Set, Campaign)
- All Arsenal (Malware, Channels, Tools, Vuln)
- Techniques (Attack Patterns, Narratives)
- All Entities (Sectors, Events, Orgs, Systems, Individuals)
- All location (Regions, Countries, Adminsitratives Areas, Cities, Positions)
