### ISSUE TITLE
Placeholder not aligned in the groups loading

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7524]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/1e547f71-36da-44bb-bfb3-64e895dfb74f)

**Comment by nino-filigran** [comment]
Should it be fixed with new tables rollout @Kedae ?

**Comment by nino-filigran** [comment]
Similar to: https://github.com/OpenCTI-Platform/opencti/issues/7526, https://github.com/OpenCTI-Platform/opencti/issues/7528, https://github.com/OpenCTI-Platform/opencti/issues/7527

**Comment by Kedae** [comment]
It might, but it's not coming soon so we might want to fix it sooner.
