### ISSUE TITLE
Incorrect placeholder in Security / Organizations list

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7525]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/6b131d4b-51b6-4701-a418-68f5571175e5)

Should be:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/133338b9-11cf-450c-bbf6-e3c590ebf74c)

**Comment by nino-filigran** [comment]
Similar to: https://github.com/OpenCTI-Platform/opencti/issues/7523, but for the current bug, not in knowledge.
