### ISSUE TITLE
Placeholders not aligned in the roles list

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7526]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0ba174e2-4a07-4d6c-8b36-f45616fdee6c)

**Comment by nino-filigran** [comment]
Similar to: https://github.com/OpenCTI-Platform/opencti/issues/7524, https://github.com/OpenCTI-Platform/opencti/issues/7528, https://github.com/OpenCTI-Platform/opencti/issues/7527
