### ISSUE TITLE
Placeholders not aligned in case templates (taxonomies)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7527]
## Description

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/0f379d78-734f-4478-80ef-d0898617d1ab)

**Comment by nino-filigran** [comment]
Similar to: https://github.com/OpenCTI-Platform/opencti/issues/7524, https://github.com/OpenCTI-Platform/opencti/issues/7528,
