### ISSUE TITLE
Default filters cannot be changed in some cases

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7539]
## Description

Example:

1. Go to a case
2. Click on the "+" in "Origin of the case"
3. Click on entity type filer:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/ff59d63c-baa5-4c21-8188-4451933f2dc3)

Checkboxes cannot be unchecked

**Comment by Archidoit** [comment]
By default, we can't change these values, to indicates the possible entity types in this screen. I suggest a modification to make it possible to filter by entity type by adding a filter as following : 
![Image](https://github.com/user-attachments/assets/1a482b77-9d4f-46ec-b474-dfeb40c159d6)

Would it be okay for you ? @nino-filigran @romain-filigran

**Comment by Archidoit** [comment]
After discussion with @romain-filigran , the chosen solution is:
- We don't display the implicit filter 'entity type = Incient or sighting or report'
- The user can add a filter on the entity type, the possible values for this filter are only: Incident, Sighted in/at, Report
