### ISSUE TITLE
In dashboard list widget, when displaying creators, it is clickable and leads to nowhere

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7541]
## Description

https://filigran.octi.filigran.io/dashboard/workspaces/dashboards/905236b3-33c3-4b6c-8a61-0eeab425d692

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/83ae0bc6-ce49-4d75-a869-ec437ec4348f)

Expected bebhavior:

- If set access permission: go to the user
- If not, not clickable (with proper pointer, etc.)

**Comment by CelineSebe** [comment]
duplicate #7540
