### ISSUE TITLE
Inferred relationships cannot be shared with organization manually

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7543]
## Description

Inferred relationships cannot be shared with organization manually:

https://filigran.octi.filigran.io/dashboard/locations/regions/dd1560f8-2a3a-4cbe-aff6-d074ec8c7609/knowledge/relations/01a05b54-9812-4fb2-af24-0a5ec094ba94

1. The button is not clickable
2. But it is still blue...

=> Based on the last evolution, it should be shareable.

**Comment by Jipegien** [comment]
@SamuelHassine When you say "last evolutuon", you mean that : https://github.com/OpenCTI-Platform/opencti/issues/6990 ?

**Comment by SamuelHassine** [comment]
@Jipegien: yes!
