### ISSUE TITLE
Multiple remaining action buttons in secondary color

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7544]
## Description

Rules are:

1. Action button = primary color
2. Navigation buttons = white / black

Some very special action buttons, in secondary colors.

When adding a relationship, then creating an entity on the fly:

![image](https://github.com/OpenCTI-Platform/opencti/assets/1334279/b76f2bba-dfc9-4133-a2ec-9211d7e0aa84)

**Comment by Jipegien** [comment]
@labo-flg is this screen covered by one of the PR related to floating buttons?

**Comment by labo-flg** [comment]
Yes this button will be ultimately removed by the community contribution on FAB.
If we do not want to wait, we can still do a quickfix as this is not much code change.

**Comment by Jipegien** [comment]
we wait
