### ISSUE TITLE
Duplicate relations in Diamond model

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#7561]
## Description

Diamond model present duplicate relations in victimology part but maybe also in other part.

![Capture d'écran 2024-07-02 091512](https://github.com/OpenCTI-Platform/opencti/assets/171329346/4bbe7067-0ec4-4f22-bf08-038b8b261b91)

## Environment

2. OpenCTI version: 6.2.0

**Comment by nino-filigran** [comment]
Does not happen all the time, but I think I found a repro case: when adding Finance as a victim & then adding the sub sector Banking, then the result in Victimology is: "Finance, Banking, Finance". I guess the we also show the parent sector for each subsectors.
