### ISSUE TITLE
[Marking] Adding markings by default doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7570]
## Description

After configuring the default marking application, it appears that it doesn't work (no marking is added).

## Environment

OCTI 6.2.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Group X with access to all markings and default "TLP:AMBER" marking.
2. Create a User A part of Group X
3. Create a Role Y used by Group X and with the capability to create knowledge
4. Go to "Settings > Customization > Report" and for "Marking" switch on "Activate/Deactivate default values"
5. Create a new report with User A, without adding any marking

## Expected Output

I expect to have the "TLP:AMBER" marking on my report.

## Actual Output

I don't have any marking

**Comment by Jipegien** [comment]
not able to reproduce.
