### ISSUE TITLE
Invisible text in History in reports/users

### ISSUE THREAD

**Issue by dominictory** [LuatixHQ/opencti#7571]
## Description

When on a specific report's page, the text for creators and entities in Most Recent History is white, making it invisible when the platform is set to light theme:

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/01c1aaba-f2c1-4efc-9a3b-2f4b7884bd70)

![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/d3ad0227-e95a-4826-a348-69c5017e0e7a)

## Environment

6.2.0

## Reproducible Steps

Be on version 6.2.0
Set user profile to Light theme
Go to a report's page

## Expected Output

Dark text on white background

## Actual Output

White text on white background

**Comment by dominictory** [comment]
![image](https://github.com/OpenCTI-Platform/opencti/assets/124377454/6282d57a-8c8e-4e75-a70b-2ee0d5eb5b4b)

**Comment by SamuelHassine** [comment]
Fixed in 6.2.1. Duplicate of #7580.
