### ISSUE TITLE
Can't contextually create a malware analysis

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7581]
## Description

Can't create a malware analysis from Knowledge > create relationship > create entity

## Reproducible Steps
- Go to a malware knowledge
- Go to the 'related entities' panel (via the right panel)
- Open the form to create a relationship
- Click on 'add new entity'
- Select entity type = malware analysis
- The entiy type is not supported

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/50d64584-96fe-4152-a3e7-427d759cc3da)

## Expected behavior
A form to create a malware analysis

## Current behavior
see screenshot

**Comment by labo-flg** [comment]
Same for Tasks, unsupported.

We can add the very same fix and make it available. Does it make sense though ?
Maybe not from a malware context, but elsewhere? (like Cases).

**Comment by labo-flg** [comment]
Decision = add Task too for completion
