### ISSUE TITLE
[CSV ingester] credentials not taken into account when Basic auth

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#7586]
## Description

When ingesting a CSV from an authenticated source, the credentials are not taken into account (Basic auth).
The back returns a 403 status

## Environment

Testing (6.2.0)

## Reproducible Steps

Contact me to get more information for this issue

**Comment by romain-filigran** [comment]
Reproduced. Credentials are not transmitted to the backend.
