### ISSUE TITLE
[ExportFileCsv] Unable to choose user access filter for CSV feed when no English language is in use

### ISSUE THREAD

**Issue by alesnav** [LuatixHQ/opencti#7587]
## Description

When English language is in use, everything works fine when trying to set the feed as private for one user. But, when other language is in use (Spanish in my example), it throws the following error when trying to choose those users who must be allowed to access the CSV feed.

![Screenshot_2](https://github.com/OpenCTI-Platform/opencti/assets/1645707/d933dd51-d4b4-45bc-8951-81d1dd61ad7c)

## Environment

1. OS (where OpenCTI server runs): Docker Swarm
2. OpenCTI version: 6.2.1
3. OpenCTI client: Web Frontend
4. Other environment details: Spanish language

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Choose a language different than English (f.i. Spanish)
2. Go to Data > Data sharing > CSV feeds > "+"
3. Fill in the data of the CSV feed and choose a user in the dropdown "Accesible for:"
4. Press CREATE and wait for the error

## Expected Output

CSV feed created.

## Actual Output

Error is shown, CSV feed is not created and both CANCEL and CREATE buttons are disabled. Hence, there's no way to continue and all data must be filled in again from scratch.

## Additional information

N/A

**Comment by nino-filigran** [comment]
@alesnav can you confirm me a few things: 
- you can create it successfuly for one user/group in **English**?
- If so, what's the role of your user?

Indeed, I've tried both with English & Spanish, with users with ByPass capa and I got the same each time.
