### ISSUE TITLE
Blank space on the right for some relationships overviews

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7597]
## Description

Blank space on the right for some relationships overviews

## Reproducible Steps
- Create a relationship between a relationship and a Data Source
- Go to this relationship overview
- There is a blank space on the right

![image](https://github.com/OpenCTI-Platform/opencti/assets/75783086/0d3e11ce-4a0a-4912-b0cf-ebd4d5540857)

## Comment
Same for Data Components and Courses of Action

**Comment by SamuelHassine** [comment]
Can you please use `<>` instead of `<div>`?
