### ISSUE TITLE
Retention Policies don't delete information?

### ISSUE THREAD

**Issue by Pez721** [LuatixHQ/opencti#7598]
## Description

I have implemented two retention policies in OpenCTI:

![image](https://github.com/OpenCTI-Platform/opencti/assets/136246848/a2fc2b9f-09e2-4cc2-81a1-cccc45efa989)

The value of "remaining" is increasing over time and I see no evidence that data is being removed from the platform. 

In the application logs I can see some errors, I see they target early indices in elastic but I am not sure whether they are related to the retention policies:

{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":500,"key":"createdBy","values":[{"_index":"opencti_stix_domain_objects-000001","base_type":"ENTITY","confidence":100,"contact_information":null,"created":"2023-10-17T12:15:41.097Z","created_at":"2023-10-17T12:16:00.380Z","creator_id":["88ec0c6a-13ce-5e39-b486-354fe4a7084f"],"description":null,"entity_type":"Organization","i_aliases_ids":[],"i_group":{"destKey":"createdBy","id":"identity--f29f12ba-3980-5642-9b3e-d11e9b296aed","multiple":false},"id":"6b9e84d4-41b5-44fc-a5d0-308e5c3b0aaa","identity_class":"organization","internal_id":"6b9e84d4-41b5-44fc-a5d0-308e5c3b0aaa","lang":"en","modified":"2024-03-11T14:10:34.900Z","name":"CrowdStrike","parent_types":["Basic-Object","Stix-Object","Stix-Core-Object","Stix-Domain-Object","Identity"],"revoked":false,"roles":null,"sort":[1697544960380],"spec_version":"2.1","standard_id":"identity--f29f12ba-3980-5642-9b3e-d11e9b296aed","updated_at":"2024-03-11T14:10:34.900Z","x_opencti_aliases":null,"x_opencti_organization_type":null,"x_opencti_reliability":null,"x_opencti_stix_ids":[]},{"_index":"opencti_stix_domain_objects-000001","base_type":"ENTITY","confidence":100,"contact_information":null,"created":"2024-04-24T12:23:49.959Z","created_at":"2024-06-24T13:45:10.658Z","creator_id":["88ec0c6a-13ce-5e39-b486-354fe4a7084f"],"description":null,"entity_type":"Organization","i_aliases_ids":[],"i_group":{"destKey":"createdBy","id":"identity--f29f12ba-3980-5642-9b3e-d11e9b296aed","multiple":false},"id":"71a64016-6c5c-41f4-b088-85e318fad60a","identity_class":"organization","internal_id":"71a64016-6c5c-41f4-b088-85e318fad60a","lang":"en","modified":"2024-04-24T12:23:49.959Z","name":"CrowdStrike","parent_types":["Basic-Object","Stix-Object","Stix-Core-Object","Stix-Domain-Object","Identity"],"revoked":false,"roles":null,"sort":[1719236710658],"standard_id":"identity--f29f12ba-3980-5642-9b3e-d11e9b296aed","updated_at":"2024-06-24T13:45:10.658Z","x_opencti_aliases":null,"x_opencti_organization_type":null,"x_opencti_reliability":null,"x_opencti_stix_ids":[],"x_opencti_workflow_id":null}]},"message":"Input resolve refs expect single value","name":"UNSUPPORTED_ERROR","stack":"UNSUPPORTED_ERROR: Input resolve refs expect single value\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at UnsupportedError (/opt/opencti/build/src/config/errors.js:89:51)\n    at /opt/opencti/build/src/database/middleware.js:723:15\n    at Array.map (<anonymous>)\n    at inputResolveRefsFn (/opt/opencti/build/src/database/middleware.js:717:58)\n    at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2650:25)\n    at createRelation (/opt/opencti/build/src/database/middleware.js:2790:16)\n    at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:99:19)"}],"inner_relation_creation":1,"level":"error","message":"Input resolve refs expect single value","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"input","type":"Variable"}]],"name":"stixCoreRelationshipAdd"}]],"size":666,"source":"backend","time":18,"timestamp":"2024-07-04T13:04:13.084Z","type":"WRITE_ERROR","user":{"applicant_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","call_retry_number":"0","group_ids":["5d1ef2c6-62a5-46d2-ba1c-b79e0dba023a"],"ip":"::ffff:<XX.XX.XX.XX>","organization_ids":[],"socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"version":"6.1.10"}

{"category":"APP","errors":[{"attributes":{"genre":"BUSINESS","http_status":404,"unresolvedIds":["indicator--53e410bb-ff68-5191-b799-8ea6f43382b5"]},"message":"Element(s) not found","name":"MISSING_REFERENCE_ERROR","stack":"MISSING_REFERENCE_ERROR: Element(s) not found\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at MissingReferenceError (/opt/opencti/build/src/config/errors.js:123:48)\n    at inputResolveRefsFn (/opt/opencti/build/src/database/middleware.js:731:13)\n    at createRelationRaw (/opt/opencti/build/src/database/middleware.js:2650:25)\n    at createRelation (/opt/opencti/build/src/database/middleware.js:2790:16)\n    at addStixCoreRelationship (/opt/opencti/build/src/domain/stixCoreRelationship.js:99:19)"}],"inner_relation_creation":1,"level":"warn","message":"Element(s) not found","operation":"Unspecified","query_attributes":[[{"arguments":[[{"is_empty":true,"name":"input","type":"Variable"}]],"name":"stixCoreRelationshipAdd"}]],"size":694,"source":"backend","time":41,"timestamp":"2024-07-04T13:04:13.154Z","type":"WRITE_ERROR","user":{"applicant_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","call_retry_number":"3","group_ids":["5d1ef2c6-62a5-46d2-ba1c-b79e0dba023a"],"ip":"::ffff:<XX.XX.XX.XX>","organization_ids":[],"socket":"query","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","user_metadata":{}},"version":"6.1.10"}

Do you have any insight on this?

## Environment

1. OS - Unix
2. OpenCTI version: 6.1.10
3. OpenCTI client: frontend

## Expected Output

Data is deleted in line with retention policy

## Actual Output

Data is not deleted

**Comment by SamuelHassine** [comment]
Hello @Pez721,

The logs you have provided seems to not be related to the retention policies manager.

When starting, retention policies can take time to actually delete the data. 

Can you recheck now if the number of "to deleted entities" has decreased and re-send a screenshot please?

**Comment by Pez721** [comment]
Hi Samuel,

Thanks for the reply. The policies have been in place for about 10 days now and I haven't seen any change in the amount of data in the platform:

![image](https://github.com/OpenCTI-Platform/opencti/assets/136246848/87909d74-7a65-47db-9af6-6c8c24e92de9)

You can even see the first rule has increased significantly!

Thanks

**Comment by Pez721** [comment]
Hi,

Any suggestion how to fix this?

Regards

**Comment by Pez721** [comment]
To update, I can actually see some indicators being deleted. Looking at the speed, I calculate it will delete about 25,000 indicators per day. However we ingest about 40k indicators per day. Is there a way to enable it to delete faster?

**Comment by nino-filigran** [comment]
Hey @Pez721 we're of the limitation you mentioned about the fact that deletion is slow. It's something we're currently working on.

**Comment by richard-julien** [comment]
Closed for https://github.com/OpenCTI-Platform/opencti/issues/4864
