### ISSUE TITLE
AI service is not working

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#7615]
## Description

AI is not reachable or gives random results.

## Environment

* 6.1.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:

* Try any "Ask AI" feature

## Screenshots (optional)
![image](https://github.com/OpenCTI-Platform/opencti/assets/146674147/fe03f7dc-7f94-4b6c-a798-0a9e7fe5d8af)

**Comment by gileri** [comment]
The issue was two-fold :
* The AI system was down
* After restart, an incompatibility rendered the model unusable.

Both issues are now solved durably, I think the issue can be closed.

**Comment by SamuelHassine** [comment]
Closing this, requalifying to questions, as it is related to our cloud services.
