### ISSUE TITLE
[Bulk search] The column ordering doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7623]
## Description

During bulk search, ordering/sorting on marking column doesn't work.

![Screenshot 2024-07-07 121004](https://github.com/OpenCTI-Platform/opencti/assets/70956706/6e2a6080-3e65-4ca0-8d59-10dc62863bc8)

NB: It's possible that other columns don't work either, please check.

## Environment

OCTI 6.2.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make a bulk search with lots of results
2. Play with the different columns to see if the sorting is done correctly

**Comment by romain-filigran** [comment]
Reproduced with markings column
