### ISSUE TITLE
[Export] Error when exporting "all selected" related entities of an entity

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7625]
## Description

When trying to export Tools associated with a specific Intrusion set, the export starts, runs for minutes and then crashes (an error is raised)

![Screenshot 2024-07-07 181942](https://github.com/OpenCTI-Platform/opencti/assets/70956706/b4a58b73-0896-44d7-a9f2-fb07be444661)

## Environment

OCTI 6.2.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to an Intrusion set
2. Go to the Knowledge tab then Tools
3. If no Tools are present, add one or several Tools
4. Click on “select all” then on the button to export them
5. Choose "test/csv" in export format and nothing else
6. Start the export and wait
-> An error appears after several minutes

## Additional information

![Screenshot 2024-07-07 182346](https://github.com/OpenCTI-Platform/opencti/assets/70956706/ef8730c0-72a5-4d81-9612-84accac3701a)

#### Exec info logs:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 349, in _data_handler
    message = self.callback(event_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-export-file-csv/export-file-csv.py", line 277, in _process_message
    entities_list = self.helper.api_impersonate.stix2.export_entities_list(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/utils/opencti_stix2.py", line 2316, in export_entities_list
    return do_list(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_core_object.py", line 1383, in list
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 363, in query
    raise ValueError(value_error)
ValueError: {'name': 'Runtime Object type "User" is not a possible type for "Identity".', 'error_message': 'Runtime Object type "User" is not a possible type for "Identity".'}`

**Comment by romain-filigran** [comment]
Reproduced. I have the feeling that the export doesn't scope on the selected entity but tries to export all related entities.

**Comment by romain-filigran** [comment]
Not specific to tools and CSV.  It's seems to be the case when trying to export "all selected" related entities and for the various export format.

**Comment by Lhorus6** [comment]
Exporting data from the platform is a basic and widely-used feature. So this is true : "the export doesn't scope on the selected entity but tries to export all related entities"

-> maybe we should make it "critical", what do you think?
