### ISSUE TITLE
Cannot search by hashes in knowledge graph

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#7634]
## Description

When, in a report, you have file observables containing a name and hashes, it's impossible to search by hashes.
If the file contains only a hash, then it's possible to search for it

## Environment

Demo (6.2.2)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a new report
2. Add file observables containing hashes and a name
3. Search by hash in the Graph

## Expected Output

File found

## Actual Output

No file found when searching by hash

## Additional information

Example: https://demo.octi.filigran.io/dashboard/analyses/reports/b20daed5-2932-422b-9686-f69ddc28cdae

**Comment by romain-filigran** [comment]
Related to https://github.com/OpenCTI-Platform/opencti/issues/7255
