### ISSUE TITLE
Manipulating organizations in the user edit panel is very slow / triggering errors

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7656]
## Description

Since we know this is heavy process, we should do something at least to not allow manipulating organization unless the first mutation is complete. Disable the button / field in the mean time?

**Comment by Jipegien** [comment]
@SamuelHassine  Can you precise the situation? When I change Organizations in the edition form of the users, I encounter no latencies in list display or selection, only latency in the refresh of the user's overview.

**Comment by nino-filigran** [comment]
Any clarification regarding this @SamuelHassine ?

**Comment by Jipegien** [comment]
not able to reproduce.
