### ISSUE TITLE
[Organization sharing] No button to share certain entities

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7695]
## Description

There is no button to share Techniques (Attack Patterns, Narratives, ...), Entities (Sectors, Individuals, ...), Locations (Countries, Areas, ...) to an Organization.

However, it is technically possible to do so, because if I have a Country in a Report and I share a Report -> The Country is shared.

## Environment

OCTI 6.2.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on an Attack Pattern
2. Search for button -> It doesn't exist

#### Example on an Intrusion set

![Screenshot 2024-07-13 201227](https://github.com/user-attachments/assets/63c706f8-5bdf-463f-8ea5-89b74e4c632f)

#### Example on an Attack pattern

![Screenshot 2024-07-13 201343](https://github.com/user-attachments/assets/239da59c-5307-497a-bd70-8fbe01592be8)

**Comment by SamuelHassine** [comment]
@Lhorus6:

FYI, not normal on attack pattern (I will fix this), but, segregation does not apply on:

- Organization
- Sector
- All locations (Regions, Countries, etc.)

Those entities are always accessible to all organizations.

All other entities should have the button.
