### ISSUE TITLE
When displaying an organization or an individual as "author", right padding is not correct in knowledge

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7717]
## Description

When displaying an organization or an individual as "author", right padding is not correct in knowledge

![image](https://github.com/user-attachments/assets/f8e82852-a84d-46bc-addb-68900fea488a)

**Comment by nino-filigran** [comment]
Repro case for clarity: 
- go to an organization
- switch to author view
- go to knowledge view

If the result is unclear, switch back to the knowledge entity.

The expected result is that the knowledge view should be on full screen and not have the placeholder of the knowledge menu.

**Comment by lndrtrbn** [comment]
We had multiple issues related to this "paddingRight" stuff. Maybe it could be nice to take time to investigate if we can refacto the base layout of the UI to be able to not use this artificial padding depending to the context of the page.
