### ISSUE TITLE
N subscribers is not correctly vertically centered within the button

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7719]
## Description

N subscribers is not correctly vertically centered within the button

![image](https://github.com/user-attachments/assets/966cfafe-ef41-4d51-8f0f-9efcf928cac0)

**Comment by SarahBocognano** [comment]
In which screen ? I couldn't reproduce, seems aligned on several screens

**Comment by nino-filigran** [comment]
Cannot find it either. @SarahBocognano did you get some inputs from @SamuelHassine ?

**Comment by SarahBocognano** [comment]
Not yet no @nino-filigran

**Comment by nino-filigran** [comment]
@SarahBocognano did you get any input? Otherwise, can you confirm taht you see it aligned on all screens? If so, we'll close the bug considering it fixed cc @SamuelHassine

**Comment by SamuelHassine** [comment]
@nino-filigran, @SarahBocognano, not sure to understand why you are not seeing this, it is basically on all screens:

![image](https://github.com/user-attachments/assets/8edc1fdf-a459-45ef-8098-8c1636d9c348)

Reports, threat actors, intrusion sets, etc.

=> https://testing.octi.staging.filigran.io/dashboard/analyses/reports/3962d59b-d02a-4a0c-918e-2a272a94776f
=> https://testing.octi.staging.filigran.io/dashboard/threats/threat_actors_group/3ae09f0e-432e-458c-a5ae-76384fdd36b7

The text is not vertically centered within the button.

**Comment by SarahBocognano** [comment]
I'm so sorry but it seems centered on my screen (took the links provided for the screenshot)
Is it still the case for you ?
![Image](https://github.com/user-attachments/assets/243227d5-1285-469e-a1dd-b50c241e6590)
