### ISSUE TITLE
In Threats => Intrusion sets, when emptying the search it should come back to default sorting

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7726]
## Description

1. Go in intrusion sets list
2. Searching
3. Sorting is automatically set to "Score" (expected)
4. Remove your search keyword and press enter

=> Staying on score, which has no sense and the list is never complete, should come back to the previous sorting of the user

**Comment by Jipegien** [comment]
In the meantime, if not already done, change the "Score" filter in "Relevancy" filter

**Comment by Archidoit** [comment]
Same for all the cards lists + for lines list the order is not reset to the previous one (no column with an arrow)
