### ISSUE TITLE
Add assignee through automation playbook

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#7728]
## Use case

automatically assign report / incident to team members depending on trigger conditions
for report could be the source / author, for incident the severity 

## Current Workaround
Manual assignment

## Proposed Solution
Add the ability to assign a user to a report or case or incident through automation playbook.

**Comment by nino-filigran** [comment]
This will be done as part of this feature: https://github.com/OpenCTI-Platform/opencti/issues/6049
