### ISSUE TITLE
Search not retaining data in GUI

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#7754]
## Description

Basically, what is happening is.. I search for something under an Indicator's sighting, I delete the search string but don't press enter. I go somewhere else in OpenCTI and come back. OpenCTI has the original search in the URL, but the search is blank in the GUI. It would be awesome if you left the page and came back, the search from the URL is populated visually in the search bar. Does any of this make sense? 

Seems to only affect search under Knowledge and Sightings within an Indicator, Analyses seems to work fine as does the main search for Indicators and Observables.

## Environment

OpenCTI version: { 6.1.10 }

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Search for something and press enter.
2. Delete the contents and don't press enter.
3. Go somewhere else in OpenCTI and come back.
4. Search is shown as blank, though in reality a search is still being performed.

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/9a91774d-fda5-4095-b1f8-d1f73b6de5ba)
![image](https://github.com/user-attachments/assets/bfd9dd5d-87ae-48c2-b21d-cdb35bbbb2e1)

**Comment by nino-filigran** [comment]
The fix should be to show the searched text when coming back to the page, as on all other pages.
