### ISSUE TITLE
Unable to embed a "public dashboard" in a web page through an IFrame

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#7756]
## Description

It is not currently possible to integrate a public dashboard into an external web page (e.g. WordPress), which is one of the objectives of public dashboards.
This is not possible due to the presence or absence of certain HTTP Response headers required to allow content to be embedded in Iframe.

I managed to integrate a dashboard in a WordPress page by injecting this HTTP header (through a reverse proxy) in OpenCTI response: 
Content-Security-Policy "frame-ancestors https: http:";

But other HTTP headers returned by OpenCTI should also be reviewed as “X-Frame-Options” for older browsers.

A possible approach would be to be able to adapt these "HTTP headers" only on the dedicated endpoint for public dashboards (to evaluate)

## Environment

OpenCTI version: 6.2.5

**Comment by aHenryJard** [comment]
@romain-filigran do you know oldest browser version fot each browser that should be supported ?
