### ISSUE TITLE
Retention rules may periodically publish error if trying to delete individual coresponding to a user

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7787]
## Description

Retention rules on Individuals may try periodically to delete some individuals even if they are linked to a user --> we have periodically errors in the backend (and in support package files)

## Reproducible Steps
- Create a retention rule on everything (or on Individuals)
- Each time the retention manager re-run the batch of deletion, he tries to delete the individuals linked to a user, and an error is published in the backend : Cannot delete an individual corresponding to a user

## Expected output
Some proposed solutions:
- The retention manager shouldn't try to delete individuals if they correspond to a user
- An error message or a warning should be written somewhere in the app if something can't be deleted by a retention rule 
- The backend error message should be clearer and indicates that the error comes from a retention rule that tries periodically to delete the object

**Comment by nino-filigran** [comment]
@Archidoit I'm not sure it's a bug, since it would also happen if you manually try to delete the individual by hand. I don't know though to what extent the error is unclear in the backend, that might be an improvement point indeed. Would you agree if I trun your ticket into a feature instead?

**Comment by Archidoit** [comment]
@nino-filigran yes you can convert it to a feature. I put it as a bug since you periodically have errors in the backend, polluting the support package, and the error doesn't indicate it comes from a retention rule.

**Comment by SouadHadjiat** [comment]
I think we need to work on this issue, the same we did on organizations, and I think it's a bug. Retention manager shouldn't try to delete individuals associated to users. @nino-filigran

**Comment by SouadHadjiat** [comment]
Also the error is quite clear in the logs, we can see that it comes from RETENTION_MANAGER : 
```
{
  "category": "APP",
  "errors": [
    {
      "attributes": {
        "genre": "BUSINESS",
        "http_status": 400
      },
      "message": "Cannot delete an individual corresponding to a user",
      "name": "FUNCTIONAL_ERROR",
      "stack": "GraphQLError: Cannot delete an individual corresponding to a user\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at FunctionalError (/opt/opencti/build/src/config/errors.js:94:50)\n    at internalDeleteElementById (/opt/opencti/build/src/database/middleware.js:3203:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at deleteElementById (/opt/opencti/build/src/database/middleware.js:3290:32)\n    at deleteElement (/opt/opencti/build/src/manager/retentionManager.ts:42:7)\n    at deleteFn (/opt/opencti/build/src/manager/retentionManager.ts:86:9)"
    }
  ],
  "id": "*****",
  "level": "error",
  "manager": "RETENTION_MANAGER",
  "message": "Cannot delete an individual corresponding to a user",
  "source": "backend",
  "timestamp": "2024-11-18T09:44:09.610Z",
  "version": "6.3.12"
}
```

**Comment by Archidoit** [comment]
I agree with you @SouadHadjiat , we should add the same kind of test as you did for organization.
