### ISSUE TITLE
TAXII Collection pagination not working

### ISSUE THREAD

**Issue by p3nal** [LuatixHQ/opencti#7789]
## Description

The pagination doesn't work in OpenCTI's TAXII Collection. Requesting the next page using the `next` parameter results in the same response, doesn't return the next page even though `more` is `true` in the response.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 23.04
2. OpenCTI version: OpenCTI 6.2.7
3. OpenCTI client: in this case I used curl to supply the URL parameters as well as the browser
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Enable TAXII Collections
2. Do a GET request on TAXII Objects
3. Check if more=true and do the same GET request with the URL parameter next=<previously returned next value>
4. Inspect the response and see that it's the same as in 2.

## Expected Output

Next page

## Actual Output

Same page as without `next` URL parameter

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/9ae6c378-01a0-41b7-9a75-3f9ce651135b)

![image](https://github.com/user-attachments/assets/11023237-28b2-4b01-9c0f-584e00b1dbe4)

**Comment by aHenryJard** [comment]
Hello, the "next" data is a request parameter not a parameter inside body, can you use something like:
```
curl -H 'Accept: application/taxii+json;version=2.1' -H 'Authorization:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 'https://xxxxxxxxxxxxxxx/taxii2/root/collections/$collection/objects/?next=Wz........'
```

**Comment by p3nal** [comment]
Hello,
The thing is it used to not work even when passed as a URL parameter, but for some reason it works now!
Thanks tho
