### ISSUE TITLE
[Workbench] Existing marking definition marked as not in platform

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7795]
## Description
Existing marking definition marked as not in platform in workbench

## Reproducible Steps
- Export some entities with markings in a json file
- Create a workbench from this file
- In the 'entities' tab there is a marking definition marked as 'not in platform'

![image](https://github.com/user-attachments/assets/df247098-7f63-4683-8eae-5f796b603299)

## Expected output
What do we want?
- markings should not be listed in 'entities' since it is not stix domain objects ? 
- OR we should fix the 'no' and display 'yes' if the marking is in the platform --> CHOSEN SOLUTION

**Comment by romain-filigran** [comment]
Reproduced. On the same topic: 
https://github.com/OpenCTI-Platform/opencti/issues/6652
https://github.com/OpenCTI-Platform/opencti/issues/7351
