### ISSUE TITLE
[Workbench] Sightings default value displayed as Unknown

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7797]
## Description
In a workbench, the sightings default values are displayed as unknown -> unknown

## Reproducible Steps
- Export some sightings in json
- In data/import, add the json file and generate a workbench
- Go to the created workbench
- In the Sightings tab, the sightings default value is Unknown -> Unknown

![image](https://github.com/user-attachments/assets/b50b07a7-3681-4f70-a0de-51046401eb49)

## Expected output
Display the correct sighting default value : source -> target

**Comment by SarahBocognano** [comment]
![Image](https://github.com/user-attachments/assets/49b2acde-7b15-48be-a9da-6c9c0fb3f1b6)
Seems to be working well on my side. Maybe it was fix by another issue ?
