### ISSUE TITLE
Inability of Creating or Modifying Entities

### ISSUE THREAD

**Issue by 0xalwageh** [LuatixHQ/opencti#7801]
## Description

I have encountered an issue with the settings/customization tab where I'm unable to create new entity types or rename existing entities like "Malware Analysis." Additionally, I cannot rename groups such as Analyses, Threats, Arsenal, and others.

## Environment

OpenCTI release 6.0.10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on Customization under Settings
2. Navigate to Entity Types

## Expected Output

- An "add" or "create" button for defining new entity types and configuring their attributes.
- The ability to modify names and attributes of existing entities by clicking on them.
- Capability to create and customize entity groups beyond predefined ones like Threats and Arsenal.

**Comment by romain-filigran** [comment]
Unfortunately, it is not possible to create new entities or customize fields within an entity.
Adding a new entity involves a lot of changes within OpenCTI.
