### ISSUE TITLE
Not able to create new `report-type`

### ISSUE THREAD

**Issue by adityav-mox** [LuatixHQ/opencti#7820]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

Hi Team,

While creating Rss Feeds, we notice that the `report-type` feature is locked to default values only ['internal-report, 'threat-report', 'misp-event']. Whereas, we want to label the type as custom example `rss-feed`.
Already tried with admin priv, to put freetext which works for other fields like organisation, but no success for report-type.
<img width="1467" alt="Screenshot 2024-07-26 at 14 49 30" src="https://github.com/user-attachments/assets/a8c1594d-e613-4827-8098-88a55f64b969">

I came across this [Issue](https://github.com/OpenCTI-Platform/opencti/issues/2041), where it says the in `Reports` we can add freetext to create new `report-type`, unfortunately it also did not work.
<img width="961" alt="Screenshot 2024-07-26 at 14 55 28" src="https://github.com/user-attachments/assets/2b30cd48-e368-47fd-bc3b-9384ea379957">

Would request if the team can share if any workaround exists, or is this something we can request as feature?

## Environment

1. OS (where OpenCTI server runs): AMZ Linux, RHEL 7.9
2. OpenCTI version: 6.0.10
3. OpenCTI client: Frontend
4. Other environment details: Runs on EKS 1.28

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by romain-filigran** [comment]
Hello @adityav-mox. You can define new report-type by navigating to : Settings --> Taxonomies --> Vocabularies --> reports_type_ov (https://{opencti_url}/dashboard/settings/vocabularies/fields/report_types_ov)

**Comment by adityav-mox** [comment]
@romain-filigran : Thanks 🚀
