### ISSUE TITLE
Reduce display delay after adding relationships

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7830]
## Description

1. Create an indicator
2. Go to the indicator
3. Go in the knowledge tab
4. Create a relation to a threat

=> Nothing appears, need full refresh

**Comment by romain-filigran** [comment]
Normally covered by https://github.com/OpenCTI-Platform/opencti/issues/7727.
No need to full refresh the page but a latency is observed.
To discuss @ValentinBouzinFiligran

**Comment by romain-filigran** [comment]
Rename "Reduce display delay after adding relationships" for greater clarity

**Comment by delemaf** [comment]
I've noticed the entities table counter also have a delay, I'll include the fix along the refresh
