### ISSUE TITLE
Kill "all" session button is not working anymore in the user overview

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7837]
## Description

Kill "all" session button is not working anymore in the user overview

1. Go to a user with multiple sessions
2. Click on "Kill all sessions"

=> Nothing happens.

**Comment by romain-filigran** [comment]
It's also necessary to completely refresh the page to update the session table when killing session one by one

**Comment by SamuelHassine** [comment]
Indeed!
