### ISSUE TITLE
Default Dashboard is inaccessible

### ISSUE THREAD

**Issue by 0xalwageh** [LuatixHQ/opencti#7839]
## Description

I have set the default dashboard for a specific group, but when I login with a user from this group, I see on the Home page this message: "You do not have any access to the explore part of this OpenCTI instance." Despite configuring the access restriction to "can view," and even trying "can manage," the issue persists.

## Environment

OpenCTI 6.2.7

## Expected Output

View and access the assigned default dashboard.

## Actual Output

An error "You do not have any access to the explore part of this OpenCTI instance"

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/12c25950-a397-4865-9dc4-e471f28e3ccf)

**Comment by nino-filigran** [comment]
@0xalwageh can you please let me know: 
- what are the exact capabilities of the role associated to your group for the user you're trying to log in with?
- does it happen with a user that have "bypass" capability?

**Comment by 0xalwageh** [comment]
Thank you for your assistance. I’ve identified the issue: it appears that new capabilities related to dashboard access have been introduced in the recent updates. Since I was using version 6.0.10, which didn’t include these specific dashboard capabilities.

I had assigned the role "Default" to the group, but it lacked the necessary permissions. I have now updated the role to include the "Access dashboards" capability, and users are able to view the dashboards as expected.

**Comment by nino-filigran** [comment]
Glad to hear this :) 
As I understand, you do not have any issue then. In that case, I'll close this ticket. However, if you still have an issue and feel that I closed it too quick, feel free to re-open it and drop a comment with your question/comment.
