### ISSUE TITLE
Attribute is an Attribute to chose for every entity in CSV mapper

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#7849]
## Description

In all entities, when creating/updating a CSV mapper, there is an attribute called "attribute". This is an internal attribute that should not be exposed.

## Environment

Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
Go to CSV mapper
Create a csv mapper
Chose an entity representation (any)
Look at the fields proposed

## Expected Output

Attribute should not be in the list 
## Actual Output

Attribute should is in in the list 

## Additional information

Fix: 
- remove the "attribute" field from CSV mapper
- hideFromMappers: true (add this param to hide it from the CSV).

![image](https://github.com/user-attachments/assets/cdcc037c-bd48-4736-bb06-7684f7e10ce7)

**Comment by labo-flg** [comment]
mapper builds the form from the schema ; this "attributes" is a technical field `iAttributes` used internally only, but indeed it is present at a high level so appears in all entities.
We need to mark it in the schema so the csv mapper won't display it.
