### ISSUE TITLE
Confidence level: do not replace a field by an empty field even if confidence level is higher

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#7853]
## Use case

If an entity has a field filled, when a new source with a higher confidence level than the original entity upsert the entity, currently, all fields will be upserted, regardless if the fields are empty or not. 
This is problematic because it means that source with higher level of confidence but with emtpy fields can delete knowledge.

The goal of the feature is to update the behavior of the confidence level to: 
- upsert the specific field if: 
   - the effective confidence level is higher than the entity's confidence level AND if the field coming from the new source is not empty
   - the effective confidence level is higher than the entity's confidence level AND if the field coming from the new source is empty AND the field in the original entity is empty 
- do not upsert the specific field if: 
     - The effective confidence level is higher than the entity's confidence level AND the field coming from the new source is empty AND the field in the source entity entity is not empty.

**Comment by SamuelHassine** [comment]
@nino-filigran: We need to discuss this, because empty fields SHOULD be ignored, whatever confidence level of the upsert. If it is not the case, then it is a BUG!

**Comment by labo-flg** [comment]
Just tested but cannot reproduce actually. It works as intented.

**Comment by SamuelHassine** [comment]
After multiple testing / reproductions, the behaviour described here is not accurate / correct of what the platform is doing.

**Comment by SamuelHassine** [comment]
@nino-filigran , with @labo-flg and @richard-julien we close this one. Please reach out if you have a verified repro case.
