### ISSUE TITLE
Massive operation toolbar incorrect icons in trash

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#7870]
## Description

![image](https://github.com/user-attachments/assets/4ba6c331-bdb8-4f20-8afe-8d19c4895efe)

**Comment by romain-filigran** [comment]
Reproduced. Invalid actions appear only when selecting all entities.

**Comment by CelineSebe** [comment]
Those icons must be removed?

**Comment by SamuelHassine** [comment]
Yes, just in the trash.

**Comment by romain-filigran** [comment]
But we need to keep the "trash" and "restore" icon. Just remove icons related to organisation sharing. Agree ?
________________________________
