### ISSUE TITLE
Can't export observables

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7914]
## Description
Error at observable export creation

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps
- Go to the observables list
- Open the export panel
- Click on the Add button to create an export
- An error occurs

![image](https://github.com/user-attachments/assets/6e83b128-ee6a-420a-9716-49c647cdc849)

**Comment by Archidoit** [comment]
linked to https://github.com/OpenCTI-Platform/opencti/issues/7905 @lndrtrbn

**Comment by lndrtrbn** [comment]
Will be fixed with the PR of #7905
