### ISSUE TITLE
Quick Action “Assign to me” button

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#7922]
## Use case

Incident response is a repetitive and time-consuming activity.  Every quick action we can introduce into the platform to facilitate management and reduce the number of clicks contributes to improving the user experience.

## Current Workaround

Edit the container, search me in the assignee list and update the container

## Proposed Solution

Add a quick action button "Assign to me" and "Participe"

**Comment by stefan1anuby** [comment]
Hi, can I work on this issue? I’d love to contribute to the project.

**Comment by romain-filigran** [comment]
Resolved by: https://github.com/OpenCTI-Platform/opencti/issues/4333
