### ISSUE TITLE
Option "auto new marking" in groups not working on max_shareable_markings, could make exports fail

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#7944]
## Description

**[!!! This issue needs proper analysis to be confirmed or not !!!]**

The option "auto new marking" in groups allow to add on the fly any newly added marking to the list of allowed marking in a group.

This automated process does not add the new marking to the max_shareable_markings list.

For instance in a group dedicated to connectors, this would cause export connectors to fail exporting knowledge marked with the new marking.

## Environment

6.2.x

**Comment by nino-filigran** [comment]
After discussion, we will proceed with this. 
The fix should be: whenever a group has the "auto add" option enabled, any new marking should be added in the "max shareable markings" with the value "no restriciton". It would be up the admin to remove this.
