### ISSUE TITLE
Can't create nested relationships

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7967]
## Description
Can't create nested relationships from an observable

## Reproducible Steps
- Go to an observable
- Go to the Knowledge tab
- Click on Add a nested object
- Select a malware
- There are no relationship type available so you can't create a nested relationship

![image](https://github.com/user-attachments/assets/c56212e8-7733-45ad-ac38-03ea86b9aeab)

**Comment by nino-filigran** [comment]
@Archidoit Not sure it's a bug: indeed, we removed the linked to (ref). Therefore, lots of observables do not have a possible nested ref anymore. 
There's indeed a nested ref between file and malware, but it's in the other way around (malware sample file). As a result, I don't think we can consider this as a bug.

**Comment by Archidoit** [comment]
@nino-filigran we can may be restrict the entity types available in this list in the future, or add a filter to know which entities can be added

**Comment by nino-filigran** [comment]
Actually, I'm not really sure it's a bug, the reason being that the entity is often used as a Source entity and not a target entity. Indeed, the nested ref is malware Sample File and not File sample Malware. 

However, I agree that the platform should be intelligent enough to create the proper nested ref. So let's tackle it anyway.
