### ISSUE TITLE
Useless error message at nested relationship start time edition

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#7968]
## Description
When adding a start time to a nested relationship, an error message indicates end time is required whereas it is not

## Reproducible Steps
Go to an observable knowledge tab
Open a nested relationship edition form
Add a start time but no end time
An error appears indicating end time is required (whereas it is not), the start time is correctly updated.

![image](https://github.com/user-attachments/assets/265a2a7e-b100-48d7-98ab-1f6cf38233a6)

**Comment by nino-filigran** [comment]
Agreed. Let's remove this FE validation. Also, given these fields are not visible in UI, it's not really useful.
