### ISSUE TITLE
[Org segregation] Entities created with workbenches are not shared

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#7974]
## Description

When a user who is not a member of the main organization creates an object in the platform, this object is by default shared with his Organization (otherwise he would lose access to it directly).

However, when he creates entities using workbench, it is not shared with him.

## Environment

OCTI 6.2.11

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up the platform like this
    - User A with all capabilities except "bypass all"
    - User A part of Org A
    - Org A is not platform Organization
2. With User A, create a workbench with entities inside (the entities must not already exist in the platform)
3. With User A, validate the workbench

With User A, try to find the entities you've created -> you won't find them.
With User admin, try to find the created entities -> they have been created, but are not shared with Org A.

## Expected Output

Entities created in a workbench by User A must be shared with Org A

## Actual Output

Entities are not shared with Org A and therefore User A no longer has access to them and cannot work on them.

**Comment by JeremyCloarec** [comment]
I wasn't able to reproduce with the same setup. When validating with my User A, the entity is created with User A as the Creator and is shared with my Org A. However, there is a display bug, with the work associated with the workbench that keeps spinning.
![image](https://github.com/user-attachments/assets/de41637c-b72b-4bed-a14e-119f17884104)
Maybe there is more context needed for the bug to be reproduced? Do you have more info on the instance where the bug occured, and more info on the user?
