### ISSUE TITLE
When a user is administrator of an organization, he should be able to manage the users of this organization (enable / disable)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8011]
## Description

1. Promote a user as admin of an organization
2. Login as this user
3. Try to disable a user part of the organization

=> It should be possible, it is not.

**Comment by nino-filigran** [comment]
The behavior happens when: 
- user is org admin only (not settings capa on its role whatesoever)
- user tries to disable a user by changing its account status

**Comment by romain-filigran** [comment]
Reproduced. Exception "Cannot read properties of undefined (reading 'find')" when updating account status.
![Capture d'écran 2024-08-12 092245](https://github.com/user-attachments/assets/488e01fa-7d76-4b59-b10a-ef58da7f2c98)
