### ISSUE TITLE
Option to hide the edit button

### ISSUE THREAD

**Issue by annoyingapt** [LuatixHQ/opencti#8019]
## Use case

Sometimes the edit button can get in the way when creating notes. Could we possibly have the option to auto hide it and only reveal it if we get close to the corner?

## Additional Information

![image](https://github.com/user-attachments/assets/0d3906e0-2604-4478-8878-c86da38c9663)

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by annoyingapt** [comment]
I guess the alternative is to have some sort of buffer at the bottom of the page

**Comment by romain-filigran** [comment]
Hi @annoyingapt: Thank you for your comment. For your information, we plan to remove all these "Speed Dial" and replace them with an "update" CTA button at the top level.
