### ISSUE TITLE
[Taxonomies] Problem adding aliases to open vocab

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8053]
## Description

When I want to add an alias to an open vocabulary value, I get “Add "<my vocab>"” instead of “<my vocab>”.

## Environment

OCTI 6.2.13

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to "Taxonomies > Vocabularies > account_type_ov"
2. Update an attribute
3. Add an alias

![Screenshot 2024-08-16 152202](https://github.com/user-attachments/assets/75c0207f-b3a7-4352-900b-3db64b789d6b)

![image](https://github.com/user-attachments/assets/3429dbf4-db0c-41e1-9046-020ab9c48add)

**Comment by nino-filigran** [comment]
Does not happen on Demo & Testing: 

https://github.com/user-attachments/assets/69766d82-d334-4458-9f4d-4f41a20cea81

**Comment by Lhorus6** [comment]
Hi @nino-filigran,
Yes, the problem is present on demo and testing. You have to **update** an attribute. The problem is not present at the time of creation

**Comment by nino-filigran** [comment]
Ok got it, sorry. So it's really a UI issue, since in the end, only the words between quote is added as alias, which is the expected beahvior. So the fix is about to remove the word "Add" from the modal.
