### ISSUE TITLE
Multiple issues in opinions

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8058]
## Description

Multiple issues in opinions:

1. Hidden title

![image](https://github.com/user-attachments/assets/7f5e9109-1641-44e0-90e3-c218db551d4c)

2. Dialog

When you open the dialog:
![image](https://github.com/user-attachments/assets/abc2a4d3-b465-4a27-9116-15a96bc40e79)

Then clicking on create or update, then it is no longer possible to close it, whether on cancel or clicking elsewhere.

**Comment by SarahBocognano** [comment]
Working well.
