### ISSUE TITLE
Number of entities never comes back to 0 in list

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8086]
## Description

1. Go to observables, put some filters to have a few results
2. Let's say you have 12 observables in the list
3. Select all then delete
4. After a few minute, full resfresh the observable list

![image](https://github.com/user-attachments/assets/1cf4b80d-3a58-45ff-8e32-d8c42e5395f5)

=> Number of top right is never updated (should be 0), for instance above, it remains at 7K.

**Comment by Archidoit** [comment]
The issue is solved with the new data tables
