### ISSUE TITLE
Organization segregation information leakage

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8120]
## Description

1. Enable organization segregation and choose a platform org in settings
2. As a user part of an organization A, quick subscribe (bell) to a sector
3. As an administrator, create a report
4. As an administrator, add the sector to this report
5. As a result, the user part of the organization A will receive a notification on the creation of the report. He can not access it.

=> We don't want this notification.

**Comment by nino-filigran** [comment]
I see this bug is in needs more info and you @richard-julien are on it. Is it the case? Can I remove the need for info?
