### ISSUE TITLE
UI Bug: Limited File Display and Missing Scrollbar in File Upload & Import Interfaces

### ISSUE THREAD

**Issue by ThreatCTI** [LuatixHQ/opencti#8134]
Bug in UI: Only the last 100 uploaded files are displayed in the 'uploaded files' page, and also in the 'import' page, there is no scrollbar to scroll down.
![image](https://github.com/user-attachments/assets/24758f38-6ad3-46a9-a182-d79820cd3a26)
![image](https://github.com/user-attachments/assets/b65dfd4e-4a1b-4c02-8537-863f03d6265d)

 
Additionally, I hope that the feature of multiple selections can be added, as I have many small files, and it takes a lot of time when importing them one by one.

**Comment by nino-filigran** [comment]
Not sure to understand this bug: you can use these arrows to switch pages and see 100 files per page in your case.
![image](https://github.com/user-attachments/assets/1977076b-0e75-4de9-91e2-326e663ed3d7)


Additionnally,  I'm not sure to understand your comment regarding the scrollbar:

https://github.com/user-attachments/assets/7ce03610-7126-4a07-9868-65cd1a2b2540

**Comment by nino-filigran** [comment]
Closing this bug as a result for now.

**Comment by nino-filigran** [comment]
@ThreatCTI I've fre-opened the bug since the component is not 100% finished yet. We'll improve and in the meantime might reuse the old component. Once this component will be fully ready, we'll releas eit. My bad for closing it too early.
