### ISSUE TITLE
Node JS - Memeory leak

### ISSUE THREAD

**Issue by MaxwellDPS** [LuatixHQ/opencti#8144]
## Description

Seeing memory leaks in the node JS processes

Not sure if its related, but large works stall and go into waiting

## Environment

1. OS (where OpenCTI server runs): CentOS Stream 9
2. OpenCTI version: 6.2.6
3. OpenCTI client: frontend
4. Other environment details: Clustered deployment on k8s

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Unknown at this time

## Additional information

Wanna tag in @richard-julien here 🫣
LMK what logs to look for and I get ship them

# Screenshots (optional)

## Node JS
![image](https://github.com/user-attachments/assets/3b4508b2-18f4-4491-a4e7-99c4fdae7c9d)
![image](https://github.com/user-attachments/assets/9324398d-66ca-48b6-bb29-713341d85433)
![image](https://github.com/user-attachments/assets/573bbe42-c34f-41a9-a4e2-217c9d7c0505)

![image](https://github.com/user-attachments/assets/c154433c-9aaa-4cc7-8e3f-1a45f095bab0)
![image](https://github.com/user-attachments/assets/bdb41956-ec1f-4828-ab18-bf79ed1116d1)
![image](https://github.com/user-attachments/assets/e339f97d-f629-474e-a625-d803b1be9447)
![image](https://github.com/user-attachments/assets/0259bac5-5afc-45d6-9deb-b34d685e792e)
![image](https://github.com/user-attachments/assets/9086ff40-3d79-421a-a71a-5e26d4ec0aea)
![image](https://github.com/user-attachments/assets/96cb380f-6c5c-4ef4-a25f-58d7c32cfffc)
![image](https://github.com/user-attachments/assets/0ddf685e-37d4-468e-92a4-2504007f0032)
![image](https://github.com/user-attachments/assets/7c2aa155-bb23-46fd-9793-b0d561c24db3)

**Comment by richard-julien** [comment]
Hi @MaxwellDPS , thanks for the report.
Looks like its more about an accumulation of a lot of queries that fetch a lot of results. The incrementation of the active handlers is generally the effect of a too many calls that cannot succeeded to finished.

I dont know what produce this but if its related to a very very high usage of the elasticsearch, this is more a side effect of a kind of queries flood on the system.

It will be difficult but you have to try to identify the source of this flood by stopping all the external systems and restarting them one by one. As the sync queue is still blocked, can you upgrade in the latest minor first?

Thanks

**Comment by nino-filigran** [comment]
I do not see any movement on this ticket since a while: as a result, I'm closing this ticket for now. Please feel free to re-open if any of you have an issue on that topic.
