### ISSUE TITLE
Backend WRITE_ERROR: Expected non-nullable type \"ID!\" not to be null

### ISSUE THREAD

**Issue by rupivoting** [LuatixHQ/opencti#8171]
## Description

When I open dashboards or reports i have a problem: An unknown error occurred. Please provide a [support package](http://192.168.50.39:8080/dashboard/settings/support) to your administrator or OpenCTI maintainers. I can't figure out the reason for the error and now I can't work with reports. 

## Environment

1. OS (where OpenCTI server runs): docker on ubuntu
2. OpenCTI version: 6.2.14
3. OpenCTI client: frontend
4. Other environment details:

## Additional information

Support package included for next comment

**Comment by Jipegien** [comment]
Hello @rupivoting :) Can you share with us the generated by the support package please? If you are not confortable with sharing it here, you can also send it to us privately through the community Slack.

**Comment by rupivoting** [comment]
Hello @Jipegien 
Add support package and remove logs fro, origin post.
[99d8e47d-d4a3-469e-8a2c-b94067a01e97.zip](https://github.com/user-attachments/files/16758901/99d8e47d-d4a3-469e-8a2c-b94067a01e97.zip)

**Comment by rupivoting** [comment]
update:  I deleted all reports, added from rss feed and platform is alive after that.
