### ISSUE TITLE
Multiple issues in markdown content files

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8174]
## Description

https://filigran.octi.filigran.io/dashboard/cases/rfis/b382a3da-550d-4220-8bd5-1a035173634a/content:

1. Preview mode => no scrolling
2. Download as PDF: raw data instead of having properly formatted content

**Comment by petskratt** [comment]
Point 1 is presumably related to assigned `height` parameter, disabling it results in correct scroll:

![mui-non-scrolling](https://github.com/user-attachments/assets/3e249e8d-318d-402f-b797-d1758c96d8d9)

I would also suggest making the Preview default view for markdown files (and perhaps also "Description & Main content").

**Comment by Jipegien** [comment]
In addition to the fix, put the Preview mode as the default view for files and "Description & Main content" part.

**Comment by romain-filigran** [comment]
related: 
https://github.com/OpenCTI-Platform/opencti/issues/7651
https://github.com/OpenCTI-Platform/opencti/issues/8203

**Comment by Lhorus6** [comment]
Related: https://github.com/OpenCTI-Platform/opencti/issues/8202
