### ISSUE TITLE
Layout issue when loading cases

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8175]
## Description

![image](https://github.com/user-attachments/assets/2a2f12b3-de6d-4077-9418-f5e88d98b977)

=> No skeleton in tasks nor height 100% in the square, leading to bad / wrong layout at loading

**Comment by nino-filigran** [comment]
Hello @SamuelHassine, I've throttled my connection and took a video: I do not see the problem anymore as you can see on this video (at around 7sec). I think the new tables have fixed the issue. 

https://github.com/user-attachments/assets/8d89f4f0-efce-4231-a5fa-c9425fe09cbe



I'm closing this bug, but if you do not agree, please feel free to re-open it.
