### ISSUE TITLE
Entities validated in a report's analyst workbench are not included in the report

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#8178]
## Description

When importing a STIX bundle inside a report and the bundle contains Observed-data or any other container, the content of the analyst workbench is created but not included in the report.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Generate a STIX bundle containing, an IP address, an indicator on this IP address, a relationship between both, an observed data containing the IP address
2. Import the bundle inside a report
3. Validate the analyst workbench

## Expected Output

The entities are created and are embedded in the report
## Actual Output

The entities are created but are not embedded in the report

**Comment by Jipegien** [comment]
waiting some additional test

**Comment by Jipegien** [comment]
To implement: when importing a stix bundle from a Data tab of a ContainerA and the stix bundle describes containers X,Y,Z containing entities, then at the end the ContainerA contains containers X,Y,Z and all their entities. 1 depth level only for now.

**Comment by JeremyCloarec** [comment]
PR has been opened on connector repository: https://github.com/OpenCTI-Platform/connectors/pull/2802
