### ISSUE TITLE
Missing results when searching for observables containing a domain name

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#8179]
## Description

In a report for example, when searching for a domain name, not all the subdomains are shown in the results
https://demo.opencti.io/dashboard/analyses/reports/4319175c-d78d-4332-9924-ca60ddaa12cb

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report containing multiple subdomains of the same domain
2. search by domain name

## Expected Output

All the related subdomains should be displayed

## Actual Output

Only one is displayed

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/ad960a1a-fb5b-4579-8f6a-cde38b94b070)
![image](https://github.com/user-attachments/assets/9374c210-ace3-48bd-999a-68a5f2acbecb)

**Comment by Lhorus6** [comment]
I think there is a problem with research in general, cf:

![image](https://github.com/user-attachments/assets/94f8b743-5c9a-49b9-ad1c-7d069efcb44d)

![Screenshot 2024-08-27 172303](https://github.com/user-attachments/assets/f8f59dc3-5bd0-4f59-8f53-ec04c57f0710)

**Comment by Jipegien** [comment]
Info: works if the searched string is at the beginning of the representative. (in the demo case, search for "dcx")

**Comment by JeremyCloarec** [comment]
I'm not able to reproduce, maybe this has been fixed since then.
@yassine-ouaamou are you still having the issue in some of your searches?
