### ISSUE TITLE
Error is not parsed correctly when creating a public dashboard with an already existing key

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8186]
## Description

![image](https://github.com/user-attachments/assets/0725a983-e64e-4591-b84d-57eb827de674)

**Comment by frapuks** [comment]
it will be fixed by this PR

**Comment by richard-julien** [comment]
Close as duplicate of https://github.com/OpenCTI-Platform/opencti/issues/8923
