### ISSUE TITLE
Unable to scroll in file preview

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8203]
## Description

Unable to scroll in file preview (in a Content tab of a container)

## Environment

OCTI 6.2.16

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Request for information
2. Create a markdown file in "Content" and write things in it (long text with image)
3. Watch the preview and try to scroll down

You can see here : https://filigran.octi.filigran.io/dashboard/cases/rfis/b382a3da-550d-4220-8bd5-1a035173634a/content?currentFileId=import%2FCase-Rfi%2Fb382a3da-550d-4220-8bd5-1a035173634a%2FInvestigation+report.md&contentSelected=false&pdfViewerZoom=1.2&markdownSelectedTab=write&changed=false&isLoading=false&onProgressExportFileName=undefined

## Expected Output

Being able to scroll to see my preview

**Comment by romain-filigran** [comment]
duplicate: https://github.com/OpenCTI-Platform/opencti/issues/7651
