### ISSUE TITLE
app.base_path configuration is not working anymore (default empty works fine)

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#8205]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 6.2.15
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set up a app.base_path that is not empty
2. Run OpenCTI, login, navigate, logout

I tested with version 6.2.11 and app.base_path works correctly.

## Expected Output

everything works fine

## Actual Output

- all call to graphQL are in error, platform UI is all broken, I cannot navigate.

**Comment by V1D1AN** [comment]
I have detroy all my opencti database for this error ... I'm sad .. I think was the compatibility with Elasticsearch 7.x.. Only a bug of graphql..
