### ISSUE TITLE
Search on autonomous system does not work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8210]
## Description

When searching on autonomous systems, you can't search on numbers. If the Observable does not contain “AS”, it is not found. 

#### Example:

In the following screenshot, all these searches will return nothing:

- 112011 (even though there's one called that)
- 1234 (when there is “AS1234”)

What will work is only the full names, starting with “AS”, e.g. “AS1234”.

![image](https://github.com/user-attachments/assets/2f699a83-4e00-4ee5-8a15-86b277edfbe1)

## Environment

OCTI 6.2.16

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on Observations > Observables
2. Filter on "entity type : Autonomous system"
3. Play with the search bar to see what it says in the example above

#### Initial list

![image](https://github.com/user-attachments/assets/047113a4-fe08-4233-b2c7-d49582657781)

#### Don't work

![image](https://github.com/user-attachments/assets/b7bcc190-43d1-4dcc-9dce-6ef0b0236c08)

![image](https://github.com/user-attachments/assets/b92ed3e1-a085-4ff5-a7a7-848eebd82fce)

#### Work

![image](https://github.com/user-attachments/assets/13aa5b6a-cf51-4e09-a7fb-160ed3b291b5)

![image](https://github.com/user-attachments/assets/95e85d6d-9846-4b62-80a1-8f9d7060c720)

**Comment by romain-filigran** [comment]
Only the SA name seems to be used in the search, not the number. More relevant to search on name and number key.

**Comment by SarahBocognano** [comment]
Works on pre release
