### ISSUE TITLE
Retention rule verify : wrong number of elements that will be deleted

### ISSUE THREAD

**Issue by lndrtrbn** [LuatixHQ/opencti#8230]
## Description

When I create, or update, a Retention Rule (Settings/Customization/Retention Policies) I can verify how many elements in my platform will be concerned by the deletion with the button `Verify`.

This verification is not done correctly. The number of elements returned is OK when my rule is set to `days` but in a case of `hours` or `minutes` the number is not correct. No matter the unit chose, the computation is made on `days`.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings/Customization/Retention Policies,
2. Create a new retention rule based on 10 `days`, verify it and look at the number of elements deleted,
3. Modify the unit to 10 `minutes` and verify again, the number is the same.
4. Same for `hours`.

## Expected Output

The number of elements is computed based on the unit.

## Actual Output

The computation is always made based on days.

## Additional information

```js
// domain/retentionRule.js line 18
const before = utcDate().subtract(maxDays, 'days');
```

**Comment by romain-filigran** [comment]
Resolved in https://github.com/OpenCTI-Platform/opencti/issues/8246
Closing this one.
