### ISSUE TITLE
There are 'Exports lists' in another report (OBSERVABLES in report)

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#8241]
OpenCTI version : 6.2.12

There are 'Export lists' generated by other reports, so it's hard to tell which report generated the list.
![image](https://github.com/user-attachments/assets/61a82e17-050f-4474-9518-db4e59293164)

This does not happen on the ENTITIES tab, but only on the OBSERVABLES tab.

Can you please confirm?

**Comment by romain-filigran** [comment]
Reproduced. No "entity_id" is provided in the "exportContext" query param as we do for "entities".

For entities export: 
`"variables":{"count":25,"exportContext":{"entity_id":"e9507545-7213-4f30-9c22-3114cd2e3846","entity_type":"Stix-Domain-Object"}}`

For observables export: 
`"variables": "{count: 25, exportContext: {entity_type: "Stix-Cyber-Observable"}}"`

**Comment by misohouse** [comment]
@romain-filigran 

Thank you for your answer.

I understand what the issue is.

And, you added the keyword 'Bugs backlog', will this issue be fixed in the next update?
