### ISSUE TITLE
Hide some actions in "data" tab when user does not have the capability to create/update knowledge

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8243]
## Description

Hide all action buttons in "Data" tab related to creation or modification of knowledge if the user does not have the capability to create/update knowledge.

![Capture d'écran 2024-09-04 095204](https://github.com/user-attachments/assets/05ea72f6-1bfc-402e-bfa1-fbf588bb6376)

## Environment

2. OpenCTI version: 6.2.18

**Comment by Archidoit** [comment]
other bug : You can create a workbench in an entity even if you don't have the Knowledge update capability

**Comment by Archidoit** [comment]
bilan of the capabilities and associated possible actions : https://www.notion.so/filigran/8243-Actions-in-data-tab-when-user-does-not-have-the-capability-b56b4442045e4d6f99f08311dced882e

**Comment by Archidoit** [comment]
@nino-filigran @romain-filigran do we know what we want?
- to be able to upload a file in Data>entities: capa update knowledge + upload knowledge
- to be able to delete a file in Data>entities: capa import knowledge
- to be able to delete a workbench: capa import knowledge
- to be able to create a workbench: capa import knowledge

(see table in Notion page)

**Comment by nino-filigran** [comment]
To be clear, based on @Archidoit last's comment, we'll use the current capabilities as is to present or not the CTAs. This means: 
- CTA upload & "tt" present only if user has  update knowledge & upload knowledge
- CTA  create worbench present only if  user has import knowledge 
- CTA delete file only if user has import knowledge 

Changing the capabilities might cause lots of unwanted effects.
