### ISSUE TITLE
Retention unit not taken into account in Retention Rule Count Checking

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8246]
## Description

Retention unit is not taken into account when checking the number of entities deleted by a Retention Rule

## Reproducible Steps
- Open the retention rule creation form and fill it with maximum retention = 1 and retention unit = minute
(All the knowledge not updated after 1 minute ago should be concerned).
Click on 'Verify' . The number takes only into account the knowledge not updated a day ago (because retention unit = days by default)
--> The retention unit should be taken into account when verifying a retention rule.

**Comment by romain-filigran** [comment]
Related to: https://github.com/OpenCTI-Platform/opencti/issues/8230.
