### ISSUE TITLE
Bad labels display for user with no edition rights in Entities overview

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8253]
## Description
Labels are not correctly displayed in entities overviews for users with no editon rights

## Reproducible Steps
Log in as a user with only knowledge read rights (the user can't edit knowledge).
Go to an entity overview.
The label is not correctly displayed : 
![image](https://github.com/user-attachments/assets/b2c38b37-d321-4fcc-a684-86878fcb5748)

Whereas it is correctly displayed in the entities list : 
![image](https://github.com/user-attachments/assets/1071495d-42cc-4511-9fad-deab408b5a0d)

**Comment by romain-filigran** [comment]
Duplicate. https://github.com/OpenCTI-Platform/opencti/issues/8193.
Closing this one.
