### ISSUE TITLE
Threat actor top bar right loading is not properly aligned

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8279]
## Description

Threat actor top bar right loading is not properly aligned:

https://github.com/user-attachments/assets/51f18b73-ea25-4d74-9717-4ae5317a0994

In slow 3G:
![image](https://github.com/user-attachments/assets/2fb91ed2-ff3d-4ebb-bce0-88d1b510014f)

**Comment by romain-filigran** [comment]
Seems to be also the case in : 
- incident
- observed data
- indicator
- infrastructure
