### ISSUE TITLE
Useless vertical scrollbar in custom dashboard + hidden by the header

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8282]
## Description

See on the right.

![image](https://github.com/user-attachments/assets/0bc30b31-e725-40b6-93a1-f145b529139a)

1. Scroll bar should not be there, dashboard is not full screen at all
2. If scrollbar is needed, it should be whether "over" the top bar or just in the dashboard container, here it is making no sense as it is "hidden" behind the header.

**Comment by CelineSebe** [comment]
The scrollbar is overlapping the top bar in other containers. 
I opened a PR to fix this scrollbar issue everywhere, including in the dashboard.
