### ISSUE TITLE
The 'entities overview' loader is not the one used in the rest of the application

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8288]
## Description

Loader used in "Entities overview" widget is not the one used in the rest of the application.

![Capture d'écran 2024-09-09 085843](https://github.com/user-attachments/assets/0379c6e7-84f7-47ad-b3a4-01c9f001e003)

**Comment by frapuks** [comment]
@romain-filigran
Do we want to replace all the uses of this “standard” loader ?
![Image](https://github.com/user-attachments/assets/1c3c502e-a4d7-4251-9d6d-ed836582fad8)
