### ISSUE TITLE
OpenCTI failed to validate YARA rules containing "\r" escape sequence in text strings.

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8291]
## Description

OpenCTI failed to validate and import YARA rules containing "\r" escape sequence in text strings.

## Environment

2. OpenCTI version: 6.2.18

## Reproducible Steps

Import a YARA rule containing the "\r" escape sequence in text strings.

**Comment by JeremyCloarec** [comment]
Do you have the bundle that fails ? Are you sure that it is correctly formatted? Shouldn't \n or \r\n be used instead of \r ?
