### ISSUE TITLE
Missing indicator of the number of relationships between threat actors and narratives

### ISSUE THREAD

**Issue by sofiasmargolles** [LuatixHQ/opencti#8295]
## Description
 
Once a relationship between a threat actor group and a narrative has been created, the Narratives tab that appears on the right side of the Knowledge section does not show any number. However, when creating relationships with other objects their respective tabs on the Knowledge section do display the number of relationships. For example, this seems to work on the Threat actor's tab.
 
## Environment
1. OS: Docker
2. OpenCTI version: OpenCTI 6.2.0
3. OpenCTI client:  frontend 
4. Other environment details: none. 
 
## Reproducible Steps
 
Steps to create the smallest reproducible scenario:
1. Go to a threat actor group
2. Create a relationship with narrative
3. Check if the number does not show up
 
## Expected Output
The following should appear next to the word "Narratives": (1)
 

## Actual Output
The number of relationships with narratives does not show up.
 
## Additional information
There seems to be a recurrent issue with the display of the number of relationships on the Knowledge tab, as it may not show up when it should (as described in this issue) or it may show up at places where it should not (as described in #8115 ).
 
## Screenshots (optional)
 
![imagen](https://github.com/user-attachments/assets/b1ff0661-0c7b-4f8e-b14a-4c20d873134c)

**Comment by marieflorescontact** [comment]
The relations number in the right panel is correctly updated after a full refresh. @nino-filigran is it still qualified as a bug?

**Comment by nino-filigran** [comment]
For me it seems good @marieflorescontact
