### ISSUE TITLE
Authorized Members - Default value 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8311]
## Description

Currently, when editing an entity in customization to apply a default value on Authorized members, my user is automatically added to authorized members with the right can manage. This is wrong, user should not be added by default as authorized member.

## Environment

Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in Setting/customization
2. Edit Feedback
3. Click on Authorized members
4. 

## Expected Output

The current user should not be automatically added as an authorized members (and even more, should not be as can manage)

## Actual Output

Current user is added as an authorized member with the capa "can manage".

**Comment by Archidoit** [comment]
@nino-filigran it's not the current user that is added by default with 'can manage' capability... it's the creator : 

![image](https://github.com/user-attachments/assets/fc3e6da4-69fa-4a63-b978-7a12462db9ae)


So we want to remove the creator from authorized members by default ?

**Comment by nino-filigran** [comment]
It's the current user. I'm logged with this user "userwithoutbypass" and when going into customization/feedback, my user is added by default in the list and I cannot remove it! 

![image](https://github.com/user-attachments/assets/0cfb0e84-9ba0-476e-811e-1e5078875036)
