### ISSUE TITLE
Need to refresh to see added markings in Markings edition field

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8313]
## Description
After adding a new marking in the platform, we have to refresh the page to see the added marking in the marking edition field of entities.

## Reproducible Steps
- Create a new marking
- Go to an entity edition form
- Try to add the added marking. It is not in the list.
- If you refresh the page, the marking is in the list.

![image](https://github.com/user-attachments/assets/00a044a8-87d1-4b3c-b470-54eac0e4047d)

## Expected output
Don't need to refresh the page to see the added markings in the markings edition fields.

## Comment
Don't need to refresh to see the new marking in other locations (like in the Group allowed markings edition form).

**Comment by nino-filigran** [comment]
I do not reproduce: when I create a new marking, it gets added to the marking list. Then I go in report, click on a report, select marking, and my marking appears the list, without the need to refresh. Am I doing something wrong @Archidoit ? I4ve used public demo environement.

**Comment by nino-filigran** [comment]
Happens only on Testing

**Comment by Archidoit** [comment]
yes @nino-filigran it happens only on testing and in local

**Comment by SarahBocognano** [comment]
Fix in pre-release
