### ISSUE TITLE
Clickable mouse for Markings and Status in Entity overview

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8314]
## Description
Markings and Status fields are not clickable but the mouse is displayed as clickable in entities overviews.

## Reproducible Steps
- Go to an entity overview
- Put the mouse on the markings or on the statuses. 
- The mouse is clickable whereas nothing happens on click 

![image](https://github.com/user-attachments/assets/97b86974-1ea8-46f8-ae84-6d87c4c7405d)

## Expected output
The mouse should be a classic pointer when we pass it on markings or statuses.

**Comment by nino-filigran** [comment]
On public demo, I do not reproduce this behavior (at least on containers), only on Testing.
