### ISSUE TITLE
Infinite load is broken in container add entity 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8316]
## Description

When going in a container, entity tab, and click on add entity when scrolling, at some point, the drawer is empty. 

## Environment

Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in a report
2. Go in entity
3. Click on add
4. scroll through the list

## Expected Output
The list has infinite scrolling and you can see entities

## Actual Output

The list is empty at some point 

![image](https://github.com/user-attachments/assets/fb7c8619-cea7-4e4c-bdbd-93d775f383d8)

**Comment by labo-flg** [comment]
Maybe linked to #7925, pagination issue with ordering by _score

**Comment by lndrtrbn** [comment]
As 7925 has been solved by fixing python client I suppose it is not linked

**Comment by Kedae** [comment]
Fixed on https://github.com/OpenCTI-Platform/opencti/tree/release/6.4.0 by 52f64d483639a4eac961ae84e7850c5d66f51862
