### ISSUE TITLE
Fail to ingest CSV feed 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8324]
## Description

When trying to ingest this CSV feed: https://urlhaus.abuse.ch/downloads/csv_recent/ we got the following error: 

"Invalid Closing Quote: got \"\r\" at line 50 instead of delimiter, record delimiter, trimable character (if activated) or comment"

## Environment

Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. create a CSV mapper with entity = URL with value = column C, comma separated, skipping the first line
![image](https://github.com/user-attachments/assets/810c48a4-73be-4a3a-a518-100a6181d7b7)

3. Create a CSV feed ingester using the following mapper 

## Expected Output

Ingest happens successfully 
## Actual Output

Ingest fails with the following error  "Invalid Closing Quote: got \"\r\" at line 50 instead of delimiter, record delimiter, trimable character (if activated) or comment"

## Additional information

When trying to ingest a file that correspond to the data in the URL through a simple CSV ingest: 
- it fails when using this file: 
[Classeur1 (1).csv](https://github.com/user-attachments/files/16975416/Classeur1.1.csv)

- it works when using this file: 
[test-jp (1).csv](https://github.com/user-attachments/files/16975418/test-jp.1.csv) (XLSX in a text file renamed as CSV) 

Please note that the file & urls contain a description at the beginning, which can be one the reason of this fail? To be investigated.
![image](https://github.com/user-attachments/assets/ed010888-9039-4a0e-97b3-d5d0d3f20861)

**Comment by CelineSebe** [comment]
In classeur1.1, the only difference I see is that there are more double quotes—one more for each element and an additional pair for each line. I think the origin of issue is this csv format.
![Image](https://github.com/user-attachments/assets/0d264eb4-bdb0-4323-896d-f833103a71ff)

In test-jp, the format is correct:
![Image](https://github.com/user-attachments/assets/29f3da87-84c8-4086-baca-9c2683853d22)

**Comment by CelineSebe** [comment]
One possibility is to escape the extra double quotes before ingesting this file => "\"\"3165254

**Comment by nino-filigran** [comment]
For me, we should be able to deal with double quotes and escape them seems like a good solution.

**Comment by nino-filigran** [comment]
Closing this bug for 2 reasons: 
- the work currently done on CSVs has taken into account CSV files having a comment section like the one in screenshot, fixing the issue
- the classeur 1.1 is not even interpreted as a CSV by Excel: indeed, when trying to use data/import/from CSV, the file is not properly parse, the reason being the one explained by @CelineSebe  above. We have no way to have a character delimiter in this situation.
