### ISSUE TITLE
Entities and report are updated also if the CONNECTOR_UPDATE_EXISTING_DATA variable is set to false

### ISSUE THREAD

**Issue by rgsax** [LuatixHQ/opencti#8325]
## Description

The CONNECTOR_UPDATE_EXISTING_DATA environment variable for several connectors seems not to work. Different entities, included the ones that were manually created, are updated by the connectors.

## Environment

1. OS (where OpenCTI server runs): Docker official OpenCTI image
2. OpenCTI version: OpenCTI 6.2.7
3. OpenCTI client: frontend
4. Other environment details: no particular environment details

## Reproducible Steps

1. From an instance with an existing connector (ours is the AlienVault connector) with CONNECTOR_UPDATE_EXISTING_DATA set to false
2. Edit something that was imported by the connector or create an entity or a report that you expect could be imported by the same connector
3. Check the updates made to the entity that should not be updated

## Expected Output

The entities and reports already presenti in the platform should not be updated by the connector.

## Actual Output

The entities and reports are updated instead, thus removing important informations (often manually added).

In the screenshot below, the AlienVault connector updated the report (in particular a field) that was previously edited by a user, but, since CONNECTOR_UPDATE_EXISTING_DATA was set to false, that behavior was not expected.

## Additional information

No other additional info.

## Screenshots

![image](https://github.com/user-attachments/assets/179e3fa9-5c5c-4a03-972b-247d0f4cf16f)

**Comment by nino-filigran** [comment]
@rgsax it's because we've deprecated the varaible. If you want to avoid having your manual updates upserted, you can reduce the confidence level associated to your user's connector. Does that make sense to you?

**Comment by rgsax** [comment]
Thanks for the clarification. I had missed the CONNECTOR_UPDATE_EXISTING_DATA deprecation and the new confidence level mechanism. Now the reason for my problem is clear.

Thanks for the clarification.

Reducing the confidence of the connector's user should work.

**Comment by nino-filigran** [comment]
No problem, happy to hear that it solves your problem.
Seeing your message, I take note that we need to improve our communication regarding depreciation, that's noted.
