### ISSUE TITLE
[Confidence level] the connector confidence level passed in the configuration file is applied

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8337]
## Description

When I have a confidence level in my connector's configuration file, and I have a different value for the user of my connector on OpenCTI, the confidence level applied is the one in my file.

My understanding was that confidence level in configuration files is deprecated and was no longer taken into account. However, I have the impression that they are still taken into account, but that they also overwrite those set in the platform.

## Environment

The test was carried out on an on-prem instance of a customer (version 6.2.18), with a custom connector. But I guess it doesn't depend on the connector.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a user "my-connector" with confidence level = 50
2. Put in the configuration file of your connector `confidence_level: 3` 
3. Run the connector and wait for data creation.
-> Checks entities newly created by the connector, confidence level should be 3

## Expected Output

The confidence level set in the platform should be the only one taken into account. In my example, my entities should have a confidence level of 50 (and not 3).

## Actual Output

The confidence level of the connector passed in the configuration file is applied rather than that configured on the user.

**Comment by nino-filigran** [comment]
@Lhorus6 does the connector use a direct API call? Is python up to date? cc @Megafredo

**Comment by Lhorus6** [comment]
Is python up to date?

- Everyting is up to date

does the connector use a direct API call?

- You mean instead of classic ingestion queue, i.e. bundle sent to RabbitMQ ? If so, no. The connector does what the others do: it creates works and sends the bundle to the queue.

**Comment by Megafredo** [comment]
I think he meant the client-python ! xD
Because it's only since 6.0 that we've deprecated the confidence level
Just out of curiosity, what is the connector in question? or this behaviour was seen on all connectors ?

**Comment by Lhorus6** [comment]
Ah, you think the python client wasn't up to date! It's possible!

It's a home-made connector to import data from their home-made CRM. It imports a hundred or so organizations with just a few bits of information, nothing too complicated or voluminous.

I think we can close this issue. I'll check with them about the python client and reopen the issue if ever. Thanks for the info guys!

**Comment by nino-filigran** [comment]
Ok, closing now. Sorry for the unclarity of my question!
