### ISSUE TITLE
Can't remove label from entity overview

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8339]
## Description
Can't remove label from entity overview

## Reproducible Steps
Go to an entity overview.
You can't remove labels from there anymore. (Clicking on the cross does nothing)
![image](https://github.com/user-attachments/assets/819e3937-646f-45e6-9633-695bbfadafed)

**Comment by nino-filigran** [comment]
It seems it's a known bug, already in progress (and fixed in branch). Closing it since it's only testing for now
