### ISSUE TITLE
Upgrade passport saml to 5.x

### ISSUE THREAD

**Issue by aHenryJard** [LuatixHQ/opencti#8379]
## Description

Despite green CI upgrade to 0.9.2 is breaking at least SAML authentication. Some code changes are required for upgrade.

see https://github.com/OpenCTI-Platform/opencti/commit/b35c33ca035d17ab812783d06e02470c953002fe

Error message is
```
"errorHandler object is no longer supported, switch to onError!"
```
Passport saml is related see https://github.com/OpenCTI-Platform/opencti/pull/8064

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

SAML Authentication at least.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

**Comment by SamuelHassine** [comment]
@aHenryJard This one can help I think: https://github.com/OpenCTI-Platform/opencti/pull/8064.

**Comment by aHenryJard** [comment]
> @aHenryJard This one can help I think: #8064.

Yes I think that we need to do both at the same time.

**Comment by aHenryJard** [comment]
update: actually updating passport-saml to 5.0.0 is not enough, @nodesaml/nodesaml 5.0.0 is still not compatible with @xmldom/xmldom 0.9.+. Need to stick on 0.8.10 for now.

**Comment by aHenryJard** [comment]
Merged on 6.4 release branch for passport-saml 5, xmldom still must be done be can't in current version of passport-saml

**Comment by nino-filigran** [comment]
@aHenryJard So can we close the ticket?

**Comment by aHenryJard** [comment]
@nino-filigran it's on 6.4 release branch
