### ISSUE TITLE
Bug/Regression - Bulk edition of status not possible

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8393]
## Description

I'd like to change Vulnerability status en masse but I can't do it anymore (i.e. Select several Vulns > Update > Replace > ‘status’ option not available). I am not sure if we could do it in the past on Vulnerability, I imagine we could. One thing's for sure: we were able to at least do it on Reports, but that's no longer possible.

## Environment

OCTI 6.3.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select several Report and click on "update"

![Screenshot 2024-09-18 003814](https://github.com/user-attachments/assets/5f7309cc-7545-413d-9324-a803bd83ad4f)

2. "Replace" then open the drop down menu

![image](https://github.com/user-attachments/assets/52107c9e-c01f-4e1d-b68c-9e487773066d)

We no longer have "status"

**Comment by nino-filigran** [comment]
Ok to be clear the fix should be to be able to update the status on all entities having mass operations.
