### ISSUE TITLE
CTRL-Click is no longer possible on entity tables

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#8394]
## Description

If a user CTRL-clicks (or CMD clicks on Mac), on a report within the Analyses > Reports screen, the web browser will navigate into the details of that report on the current browser tab, rather than opening it in a new browser tab. This is true for all other entity list views, including Indicators, groupings, observables, etc.

## Environment

1. OS (where OpenCTI server runs): SaaS
2. OpenCTI version: 6.3.0}
3. OpenCTI client: Edge on MacOS (current)
4. Other environment details: None

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on Analyses > Reports
2. CMD-Click (Mac) on a report

## Expected Output

The report is opened in a new browser tab in the background

## Actual Output

The report is opened in the current browser tab

## Additional information

This is a regression from 6.2.18 to 6.3. The use case for this, is to be able to open multiple reports at once for review, letting them load in the background,

**Comment by Lhorus6** [comment]
I add here thinking that everything is linked: 
- When I right-click on an entity, I do not have the option to "open in a new tab"
- When I click on the burger button at the end of the line (example: in the list view of the Custom Dashboard, or Investigation), I directly open the object rather than having my usual drop-down menu.

**Comment by guillaumededrie** [comment]
Hi,
The `Mouse middle click` that normally also trigger a new Tab opening, is also not triggering the event on the last version (`6.3.X`). This is normally a default navigator behavior.

If you want to fix it, as you are using `event.preventDefault();` first thing here: https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-front/src/components/dataGrid/components/DataTableLine.tsx#L155

it would require to change the code (I think but not javascript expert here):

```diff
    } else if (navigable) {
-     if (event.ctrlKey) {
+     if (event.ctrlKey or event.button === 1)
        window.open(link, '_blank');
      } else {
        navigate(link);
      }
    }
```

What do you think?

**Comment by yassine-ouaamou** [comment]
Hey @Kedae,
As Guillaume said, the fix will solve only the Ctrl + Click and not the mouse middle click.
Is it possible to handle this case also?

Thanks
