### ISSUE TITLE
User unable to export filtered indicators

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#8407]
## Description

Issue might be related to this issue: https://github.com/OpenCTI-Platform/opencti/issues/8405

This is how the bug originally reported, on a user with the capabilities to Generate Knowledge Export, unable to export in txt/plain or csv/txt and receives an error message. 

## Reproducible Steps

1. Created a user with the capabilities to Generate Knowledge Export: 

![Image](https://github.com/user-attachments/assets/889a2b3c-283d-47ae-9c6e-d8c0bd0aab5d)

![Image](https://github.com/user-attachments/assets/9b3cb5f3-56f4-462c-973d-fa01a6c61781)

2. Go to Indicators, 

Filter on "In regards of" -> Malware -> Lumma

<img width="397" alt="Screenshot 2024-09-18 at 17 18 44" src="https://github.com/user-attachments/assets/b04cb3a1-06f7-43b8-be8f-8f5394088790">

3. Pick a few from the list and check the boxes

4. Click Open Export Panel

5. Click +

To generate the export in plain/txt: 

![image](https://github.com/user-attachments/assets/02b56c4a-96ce-4218-b037-798cb3d79910)

## Expected Output

Generate an export

## Actual Output

Receiving an error :

![image](https://github.com/user-attachments/assets/aa6d866c-e18b-4fb8-9a84-7d2f57b59ba0)

**Comment by nino-filigran** [comment]
At first, I did not reproduced. But then after syncing with @EinatAR I reproduced. It's important to note that Allowed markings for the repro cases are TLP:AMBER, TLP:AMBER+STRICT, TLP:GREEN, TLP:CLEAR and Maximum Shareable marking TLP = no restriction 
 Import is only on TLP:clear entities (IOCs). 

However, it's important to note that: 

- if my user has TLP:RED and: 
   - max shareable marking = TLP: RED & I create an export of the file **without** specifying a marking, it works. 
   - max shareable marking = TLP:RED & I create an export of the file **with** a specific TLP markingon the file, it works
    - max shareable marking = no restriction & I create an export of the file **without** specifying a marking, it works. 
   - max shareable marking = no restriction & I create an export of the file **with** a specific TLP markingon the file, it works
- If my user has all TLP except TLP RED and : 
   - max shareable marking = TLP: AMBER & I create an export of the file **without** specifying a marking, it fails. 
   - max shareable marking = TLP:AMBER & I create an export of the file **with** a specific TLP markingon the file, it fails
    - max shareable marking = no restriction & I create an export of the file **without** specifying a marking, it fails. 
   - max shareable marking = no restriction & I create an export of the file **with** a specific TLP markingon the file, it fails

**Comment by Kedae** [comment]
![image](https://github.com/user-attachments/assets/dd1a3a8f-b588-4e4e-85f4-1298f16ad92d)

**Comment by Kedae** [comment]
We should also try to fix : the export button is available even if you do not have the capability

**Comment by nino-filigran** [comment]
@JeremyCloarec  Important to note that it seems to happen only on testing for me

**Comment by JeremyCloarec** [comment]
The bug comes from the fact that the indicators have an Author that is not accessible by the user, and the connector trying to access the standard_id of the Author. The bug can be reproduced using this query with the user not having access to TLP:RED :
`query indicator {
  indicators {
    edges{
      node{
        id
        entity_type
        name
        createdBy {
          id
          name
          standard_id
        }
      }
    }
  }
}`

I'm not entirely sure how to fix it for now though

**Comment by richard-julien** [comment]
As the logic for now of the export do not use the stix generation from the API, i think we need to modify the export connector code to ignore the error when the creator is not accessible, and so export the indicator without his organization
