### ISSUE TITLE
[AI] "Summaries file"on all files does not always work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8413]
## Description

When I launch the AI ​​to summarize the associated files, if the file comes from an External Reference, it is not found when running on all files. Let me explain:

When you launch the feature, you can choose which file you want to summarize. If you do not select any file, by default, the AI ​​summarizes them all. The problem occurs when:

- You do not select any file, and therefore want the AI ​​to summarize them all,
- The attached file comes from an External Reference.

![image](https://github.com/user-attachments/assets/3197e0e8-1127-4d59-ab45-93bb4defa8c6)

In these conditions the AI ​​tells us "Unable to summarize files as no file is associated to this entity."

![image](https://github.com/user-attachments/assets/2ee2af58-36ac-44e4-82ea-f3e983cf6bda)

However, if I decide to select my file, it appears fine. And if I select it, it works.

![image](https://github.com/user-attachments/assets/9dcf3c38-c7e5-4ba0-a1ad-c6213b748b1b)

If I attach a file manually by uploading a pdf, I do not have this bug.

## Environment

OCTI 6.3.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a Report
2. Create an External Ref attach to it with this URL : https://thehackernews.com/2024/09/wordpress-mandates-two-factor.html
3. Run the enrichment connector ImportExternalReference to import the page in pdf format.
4. Once the pdf has been generated, click on the button "Ask AI", then "Summarize associated files"
5. Click on "generate" without changing any option.

**Comment by romain-filigran** [comment]
@frapuks : Could you look into this issue, as you're working on this subject ?
