### ISSUE TITLE
[Activity log - Filter] Missing value in Activity log filters

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8414]
## Description

When I want to filter on "event scope", I don't have the value "unauthorized" available

## Environment

OCTI 6.3.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings > Activity
2. Try the filter

![Screenshot 2024-09-18 214443](https://github.com/user-attachments/assets/c0c96fc4-4ba1-4b6c-81b8-5f7eebcc9a32)

![Screenshot 2024-09-18 214745](https://github.com/user-attachments/assets/aa443b94-8ba6-49ce-b4b1-072ef1c26747)

**Comment by romain-filigran** [comment]
Add "unauthorized" in the options of "Event scope" filter
