### ISSUE TITLE
Worker Validation Error on STIX/TAXII Import

### ISSUE THREAD

**Issue by ddgeyedcybersec** [LuatixHQ/opencti#8416]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
    Ubuntu 22.4.1
3. OpenCTI version: { e.g. OpenCTI 1.0.2 }
    6.3.1
5. OpenCTI client: { e.g. frontend or python }
    frontend
7. Other environment details:
     dockerized setup

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add a STIX/TAXII Feed from Rapid 7 (Docs available here: https://docs.rapid7.com/threat-command/pull-iocs-from-the-intsights-taxii-server/)
2. Activate the Feed

## Expected Output

STIX Objects created on OpenCTI

## Actual Output

Workers show a validation error on every STIX Object with the following message:

## Additional information

Worker log:

`{"timestamp": "2024-09-19T07:17:03.621824Z", "level": "ERROR", "name": "worker", "message": "Error executing import", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 2417, in import_item\n    self.import_sighting(item, from_id, to_id, update)\n  File \"/usr/local/lib/python3.12/site-packages/pycti/utils/opencti_stix2.py\", line 1330, in import_sighting\n    stix_sighting_result = self.opencti.stix_sighting_relationship.create(\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/entities/opencti_stix_sighting_relationship.py\", line 522, in create\n    result = self.opencti.query(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py\", line 365, in query\n    raise ValueError(value_error)\nValueError: {'name': 'VALIDATION_ERROR', 'error_message': 'Variable \"$input\" got invalid value \"2024-08-06T11:25:28.536000\" at \"input.created\"; DateTime cannot represent an invalid date-time-string 2024-08-06T11:25:28.536000.'}", "taskName": null, "attributes": {"count": 0, "reason": "{'name': 'VALIDATION_ERROR', 'error_message': 'Variable \"$input\" got invalid value \"2024-08-06T11:25:28.536000\" at \"input.created\"; DateTime cannot represent an invalid date-time-string 2024-08-06T11:25:28.536000.'}"}}`

Here's one of the STIX objects from the feed:

`{"type":"indicator","spec_version":"2.1","id":"indicator--140f7a52-b45a-54ca-ae24-e0deb8618e4e","created":"2024-08-06T11:25:28.265000","modified":"2024-08-06T11:25:28.265000","name":"IOC 218.78.46.81 from feed Blocklist.de","description":"{\"IOC\": \"218.78.46.81\", \"ReportingFeeds\": [\"Blocklist.de\"], \"SystemTags\": [], \"UserTags\": [], \"FirstSeen\": \"2019-10-08T05:00:39.520000\", \"LastSeen\": \"2024-09-19T00:28:17.070000\", \"Severity\": \"Medium\", \"ThreatActors\": [], \"Campaigns\": [], \"Malwares\": [], \"RelatedAlert\": \"\", \"Status\": \"active\"}","pattern":"[ipv4-addr:value = '218.78.46.81']","pattern_type":"stix","pattern_version":"2.1","valid_from":"2024-09-19T02:25:32.622000","revoked":false,"confidence":50}`

**Comment by romain-filigran** [comment]
Hello @ddgeyedcybersec : I have the feeling that dates coming from Rapid7 are not correctly formatted. In regard of the STIX 2.1 specification, dates must be formatted as : "YYYY-MM-DDTHH:mm:ss[.s+]Z". Moreover, dates must be expressed in UTC format with the "Z" designation to indicate this.
https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_ksbm2nost85y

**Comment by ddgeyedcybersec** [comment]
You are right, this is an issue on Rapid7s end, not with OpenCTI, sorry for the inconvenience and thanks for the help
