### ISSUE TITLE
[Dashboards] Can't modify dashboards settings even in admin (bypass all cap)

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#8433]
## Description

When trying to modify dashboard settings (date reference) from the home page with an admin account (capa bypass all) a message "you're not allowed to do this" is displayed and no modifications are made. 

Did the test on a dashboard I created myself and with the right to manage it.

## Environment

OpenCTI 6.3.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:

GIF attached

## Expected Output

With my administrator account, I expect to be able to change the reference date.

## Actual Output

Can't modify the date reference setting from the home page.

## Screenshots (optional)
![Can't modify dashboards](https://github.com/user-attachments/assets/9e126153-e06a-457a-8991-f00478a43440)

**Comment by nino-filigran** [comment]
Reproduced, but the problem is on changing the dashboard, not the date.
