### ISSUE TITLE
Can't bulk enrich observables with select all

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8438]
## Description
The 'Enrichment button' is not visible in the toolbar in the Observables list in certain cases.

## Reproducible Steps
- Go to the observables list
- Add a filter on a specific observable type (exemple: entity type = IPV4 adress)
- Do a select all via the checkbox
- The enrichment button of the toolbar is disabled
![image](https://github.com/user-attachments/assets/02b8ff2a-2d4f-44fc-ab2e-13f5c76772c0)

- You need to select the IPV4 adresses one by one to have the button visible.
![image](https://github.com/user-attachments/assets/ea1083e6-a4a3-4f4d-a036-e780bb391919)

## Comment
Issue raised by a community member

**Comment by nino-filigran** [comment]
A feature is already opened
