### ISSUE TITLE
Opening a stream gives a 410 response 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8439]
## Description

Some streams when opened are giving a 410 response: 

## Environment

Testing & public demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in   datasharing/ live stream (started)
2. create a new stream 
3. filter on a given entity type & mark this stream as public
4. click on create
5. once it appears in the list of stream, click on it 
## Expected Output

The page of the stream opens

## Actual Output

error 410
## Screenshots (optional)
![image](https://github.com/user-attachments/assets/64a43ff1-21c8-420e-af21-37796a3ad398)

**Comment by richard-julien** [comment]
have you started the stream?

**Comment by nino-filigran** [comment]
Yes, hence the opening of the ticket.

**Comment by richard-julien** [comment]
410 is the error when the stream is not started.
Has a start modification invalidate the cache for the stream manager, it could take some seconds for that.
Can you retry and wait a couple of seconds before trying to open the stream after the start?

**Comment by nino-filigran** [comment]
@NiQuintin I created this issue because you had it. Could you please try the above action on your side?

**Comment by NiQuintin** [comment]
Indeed it works after waiting some seconds

**Comment by nino-filigran** [comment]
Ok, since we don't have the behavior anymore (or at least it's explained and work as expected), closing this bug for now.
