### ISSUE TITLE
Can't remove latitude and longitude of locations in UI

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8440]
## Description
Can't remove latitude/longitude of locations via the UI

## Reproducible Steps
- Go to a position that has a latitude
- Open the edition panel
- Remove the latitude
- The latitude is not removed

Same for longitude.

**Comment by nino-filigran** [comment]
I cannot reproduce @Archidoit on any of our environments.

**Comment by nino-filigran** [comment]
My bad, it's reproduced.
