### ISSUE TITLE
Reverse proxy certificate issue

### ISSUE THREAD

**Issue by plygrnd** [LuatixHQ/opencti#8460]
## Description

An incorrect certificate is presented to users when running OpenCTI behind a reverse proxy.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 24.04.1 LTS
3. OpenCTI version: OpenCTI 6.3.1
4. OpenCTI client: Frontend
5. Other environment details: Running in pure Docker via `docker-compose`. Fronted by Caddy reverse proxy

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Provision Caddy reverse proxy configuration (see below)
2. Ensure that OpenCTI is listening on tcp/8080
3. Start Caddy
4. Attempt to access frontend

## Expected Output

OpenCTI frontend loads without any SSL warnings

## Actual Output

I receive a cert validation error. The CN of the cert presented to the viewer is `TRAEFIK DEFAULT CERT`.

### Caddyfile

```caddy
{
	email xxxx
}

xxx {
	log {
		output file /var/log/caddy/access.log
	}
	reverse_proxy / http://localhost:8080 {
		header_up Host {host}
		header_up Upgrade {http.request.header.Upgrade}
		header_up Connection {http.request.header.Connection}
		flush_interval -1
	}
}

**Comment by plygrnd** [comment]
![Screenshot 2024-09-23 at 14 33 04](https://github.com/user-attachments/assets/1a9f171b-4790-4bf1-a9fb-eb8b65c4c91f)

**Comment by seanthegeek** [comment]
The certificate is managed by your reverse proxy, not OpenCTI.

**Comment by nino-filigran** [comment]
Thanks for your response @seanthegeek, closing the bug as a result for now.
