### ISSUE TITLE
Sightings tabs in observables are broken

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8483]
## Description

Sightings tabs in the Observables are broken:

- Sightings are not displayed
- It is not possible to create new Sightings

## Environment

OCTI 6.3.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on a Country and in the "Sightings" tab
2. Create a new sightings with an IPv4 Observable
3. Go on the IPv4 and in the "Sightings" tab
-> You can't see the newly created sightings and you can't create new sightings

**Comment by nino-filigran** [comment]
I canto fully reproduced sicne, in demo for whatever reason, you cannot select the list of observable you want: 
![image](https://github.com/user-attachments/assets/0f9d1641-5832-492b-9e2a-4430eaedb2f2)

I've created a sighting from a country, selecting an artifact.
Sighting was created & visible in the artifact's sgihting tab. But when navigating to the artifact's sighting tab, I could not created a new sighting indeed.

Therefore the fix should be: 
- allow the selection of any observable in the list when creating a sighting
- ensure that we can add a sighting from the sghting tab of an observable after having created one.

**Comment by nino-filigran** [comment]
Linked to this: https://github.com/OpenCTI-Platform/opencti/issues/8398

**Comment by nino-filigran** [comment]
Contrary to wht has been said above, the fix should be to: 
- redirect to the observable overview only.

The reason is that the sighting is only visible in the "target" (observable sighted at country/system...) and not in the origin of the sighting. & the current URL only exist for entities/knowledge and not observables.
