### ISSUE TITLE
Making opinion properties mandatory may prevent the creation of new ones

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#8494]
## Description

- In Settings/Customization/Opinions page, you can set `Markings`, `Author` and `Content` as mandatory
- Or, the form don't allow the user to set these field.
- If an admin set one of these properties as mandatory, no user can create an Opinion.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set `Content` (or `Author`, or `Marking`) as Mandatory
2. Go to a report
3. Try to create an Opinion

## Expected Output

To discuss because an Opinion is a Container, and that's why Opinions have these properties.

## Actual Output

Impossible to create an Opinion for any users

## Screenshots (optional)

- Form in a report :
![image](https://github.com/user-attachments/assets/8e4ecd50-18cd-43a5-92b2-4655dcec1f36)

- Settings/customization/Opinion page (with issue properties set as mandatory)
![image](https://github.com/user-attachments/assets/59b07d70-8520-4ae5-871e-b9618ae41726)

- You can access to an update form in data/entities page => click on an Opinion => update, and in this form you can change `Athor` and `Markings`, but not `Content`
![image](https://github.com/user-attachments/assets/744bea0b-0307-4abb-9ad4-34c827e87e7d)

**Comment by nino-filigran** [comment]
I think we discussed this already a while ago @frapuks ! 
At least, we should: 
- remove content from mandatory attributes & from the entity in itself
- add author in the form to create an opinion 
- add marking in the form to create a opinion 

Would you agree @romain-filigran ? cc @Jipegien

**Comment by nino-filigran** [comment]
This has been validated ☝️

**Comment by SarahBocognano** [comment]
The bug seems to not be here anymore. Seen with @nino-filigran
