### ISSUE TITLE
Not possible to CTRL+click directly on the left menu (first level)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8501]
## Description

Not possible to CTRL+click directly on the left menu (first level)

**Comment by Lhorus6** [comment]
#### Here is the status of the "feature" allowing to open pages in a new tab:

On left menu items:

- Mouse-click on left menu items opens a new tab ✅ 
- Right-click > "open new tab" on left menu items opens a new tab ✅ 
- Ctrl-click does the same ✅ 

On list view of particular menu (e.g. Report list):

- Mouse-click on drop-down list items does not work ❌ 
- Right-click > "open new tab" does not work ❌ 
- Ctrl-click on a drop-down list item works ✅

**Comment by SarahBocognano** [comment]
- Right-click > "open new tab" works ✅

**Comment by nino-filigran** [comment]
After testing it on testing, it is fixed.
