### ISSUE TITLE
open a new tab from listing

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#8506]
Hello, with the new listing we cannot open in new tab anymore.
 
![image](https://github.com/user-attachments/assets/672335a0-ad77-499c-a3b1-69a2fb859859)

Is that expected? that's a frustrating if you need to do investigations on multiple objects

**Comment by Lhorus6** [comment]
Normally it'll be fixed with this PR : https://github.com/OpenCTI-Platform/opencti/pull/8464

**Comment by nino-filigran** [comment]
Linked to https://github.com/OpenCTI-Platform/opencti/issues/8501
