### ISSUE TITLE
History of entity is not visible (no history)

### ISSUE THREAD

**Issue by axelfahy** [LuatixHQ/opencti#8510]
## Description

Sometimes, the history of modificationd for an entity is not visible.

## Environment

1. OS (where OpenCTI server runs): docker, MacOS
2. OpenCTI version: 3.3.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an entity (e.g. a report)
2. Do some modifications

## Expected Output

I expect to see the history of the operations done on the report, for example:

![image](https://github.com/user-attachments/assets/4662e450-ef90-4228-a9a1-f3f30ed875c7)

## Actual Output

Sometimes, I don't have any history: 

![image](https://github.com/user-attachments/assets/5d9df493-2509-4f05-8395-e4a37a3aecf4)

## Additional information

I don't have a consistent way to reproduce this.

**Comment by nino-filigran** [comment]
Hey @axelfahy Do you have more info regarding: 
- your user (which role & capability)?
- your platform set up: have you enabled a platform organization in settings/securities/policy? If so does it happen with a user that  pertains to this organization? Or with a user does not pertain to this organization (and the organization has been shared to your user)?

I could not reproduce so far.

**Comment by axelfahy** [comment]
I don't have a consistent way to reproduced, it might have been an issue with my redis instance. Closing for now, will reopen if this occurs again.
