### ISSUE TITLE
[RSS feed] Author set in ingester not applied 

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8515]
## Description

The reports created by RSS feeds no longer include the Author configured in my ingester. Example:

### My ingester : 

![Screenshot 2024-09-26 152502](https://github.com/user-attachments/assets/4c32a59c-6e3b-4706-956e-99f1b7810edf)

### My newly ingested reports : 

![Screenshot 2024-09-26 152715](https://github.com/user-attachments/assets/af6cffbb-4d45-4427-b880-c294d57dbffe)

**NB: I haven't tried with the other feeds (e.g. TAXII), maybe we have the same bug.**

## Environment

OCTI 6.3.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an RSS feed as shown in my screenshot (set an Author)
2. Wait for the import and check the “Author” field -> it's empty

**Comment by Kedae** [comment]
Not reproduced on prerelease :(

**Comment by richard-julien** [comment]
Will be handled by https://github.com/OpenCTI-Platform/client-python/issues/741
