### ISSUE TITLE
Create entities in bulk: front end when creating entities in bulk from a Knwoeldge view blocked even though entities have been created

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8522]
## Description

When using the CTA to create in Bulk, entities are creared by the Front End. However the progress bar does not update & does not close automatically even though the entities have been created. 
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
**Scenario1: in a knoweldge tab**
1. Go in an entity (ex malware)
2. Go in tit knowledge tab (ex observable)
3. Click on the + to create a new relation 
4. The drawer opens with the list of observable
5. Click on the + to create a new observable 
6. Select a type compatible with bulk creation of entities (ex url)
7. On the URL creation from, clcik on create in bulk
8. Add all the entities you want to create 
9. Click on validate
10. Click on create
11. The loading appears

**Scenario2: in the bulk relation screen**
1. Add not existing entities in your bulk entitiy screen (compatible with the relation. For instance, for malware, create a bulk relation "communicates with" and add some IPs & URLs)
2. Click on create missing entities
3. The progress bar is stuck & does not progress
4. Close the progress bar
5. Click again on create missing entities 
6. entities entities are making progress and are being created.

## Expected Output

Once the entities have been create, to have the success message appearing 
![image](https://github.com/user-attachments/assets/b51c4b96-d800-49b0-9860-59400388e185)

## Actual Output

The loader is blocked 

## Screenshots (optional)

**scenario 1**
https://github.com/user-attachments/assets/2ca4fc31-26b5-4d1d-8cc7-dcea3f6c1f32

**scenario 2**

https://github.com/user-attachments/assets/cb45736e-9059-49b6-bc3a-ec6f1762a6d2

**Comment by labo-flg** [comment]
I confirm it happened also to me on demo platform. It's not a consistent behavior though, I cannot reproduce locally.

**Comment by nino-filigran** [comment]
Actually found a new repro case, I added a second scenario. Since I guess the root cause is the same, I have not created a new ticket.

**Comment by delemaf** [comment]
I tried to reproduce both scenarios locally but couldn't achieve to reproduce the bug 🤔

**Comment by Archidoit** [comment]
The bug has been solved, we can close the issue :)
