### ISSUE TITLE
Narrative list wrong icon + alignment issue

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8533]
## Description

1. The list icon is different in narrative from the rest of the platform:

Everywhere:

![image](https://github.com/user-attachments/assets/e0c08a63-a9e6-485e-9377-893f26d93dad)

In narratives:

![image](https://github.com/user-attachments/assets/50f8e306-78ca-4355-bf3e-2f2cc15747de)

2. When switching, everything is moving (bad top margin on the nested view, datatable seems correct):

https://github.com/user-attachments/assets/33deed67-9a39-437c-9772-d5dd9f5cc94e

**Comment by romain-filigran** [comment]
Moreover, icons are not well aligned on the "list view"
![Capture d'écran 2024-09-29 190856](https://github.com/user-attachments/assets/130e059e-8d6c-4393-bc6b-2610f24ffaaf)
