### ISSUE TITLE
Replace empty author with playbook

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#8538]
Hello,
When I try to replace an author to an indicator with empty author, the playbook is executed but author is not added:
 
![image](https://github.com/user-attachments/assets/17095384-001f-4780-aa38-696c936fd662)
![image](https://github.com/user-attachments/assets/7650a1ad-ff89-49eb-9db2-7b30850dfdf0)

 author still empty
![image](https://github.com/user-attachments/assets/8e4a6584-ae76-41eb-b973-157a76a51112)

**Comment by SamuelHassine** [comment]
@marckto-filigran it seems to be fixed in 6.3.4. Please ping me if you still have the issue.

**Comment by SamuelHassine** [comment]
Related to #8512.
