### ISSUE TITLE
Replace action in playbook doesn't replace but update

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#8539]
In testing environment, replace action is broken
<img width="550" alt="image" src="https://github.com/user-attachments/assets/aa03ed16-61a1-4a6d-aa64-3da2784688be">
<img width="763" alt="image" src="https://github.com/user-attachments/assets/1461f081-9647-4af6-9217-a9d80cc34f2d">

**Comment by nino-filigran** [comment]
Hey @marckto-filigran could you be slightly more explicit?
I cannot reproduce.When I click on replace the component changes. 

https://github.com/user-attachments/assets/12c89964-08b7-4333-97de-3ca6396b3a72

**Comment by marckto-filigran** [comment]
It replace window didn't show up 1hour ago but it does now. Let's not waste time on it.
