### ISSUE TITLE
Internal document identifier are case sensitive

### ISSUE THREAD

**Issue by richard-julien** [LuatixHQ/opencti#8547]
## Description

Internal document identifier are case sensitive

<img width="1442" alt="image" src="https://github.com/user-attachments/assets/5df97751-a29f-492c-8114-6d6c7f857be2">

This situation leads to GraphQLError: Id loading expect only one response

We need to:
- Lower case the id
- Create a migration to remove the duplicate

**Comment by JeremyCloarec** [comment]
When working on this, I realized that MinIO is also case sensitive:
![image](https://github.com/user-attachments/assets/1ae30c8e-757d-4395-bfbc-74b568539028)
Should we still fix this by making the id case insensitive? Isn't there a risk that we will lose access to some files on minio that have the same name but with different cases ?

**Comment by richard-julien** [comment]
Yes, I still want to handle file name as case insensitive.
