### ISSUE TITLE
Re-order entries in ingestion queue to have Connectors first

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#8558]
## Use case

When opening the ingestion UI, I am usually going there to check the status of a connector. However, since this is the bottom option, this usually requires extra 'mouse mileage' and a click to view this.

It is proposed that Connectors be the default option viewed when opening Data > Ingestion.

## Current Workaround

Click connectors manually

## Proposed Solution

Have Connectors as the top option, and selected by default

**Comment by romain-filigran** [comment]
I completely agree with this, and given that the connector view is the only one to contain ingestion metrics, it makes more sense to have it as the default view.
