### ISSUE TITLE
Not allowed to update default dashboard

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#8559]
## Description

- Not allowed to update default dashboard

## Reproducible Steps

1. Go to Home page : https://testing.octi.staging.filigran.io/dashboard/
2. click on the settings button (in right bottom corner)
3. Change the `default dashboard` value (ex : Platform dashboard)

## Expected Output

Allow to update your default dashboard

## Actual Output

Get an error : You are not allowed to do this

## Additional information

In Domain/User, we don't have `defaut_dashboard`, only `default_dashboards` in the list :
![image](https://github.com/user-attachments/assets/35e2f1ea-e67b-4516-81e5-32b71ece17b4)

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/bc298a86-ec07-430e-9c83-94de842625d6)

**Comment by nino-filigran** [comment]
Bug already been logged: https://github.com/OpenCTI-Platform/opencti/issues/8433
