### ISSUE TITLE
[CSV mappers] External references can't be selected in relationships

### ISSUE THREAD

**Issue by sofiasmargolles** [LuatixHQ/opencti#8561]
## Description

When creating a CSV mapper the platform allows for an external reference to be chosen in an object such as a threat actor, but it does not allow for it to be selected in relationships such as uses. 

## Environment

1. OS (where OpenCTI server runs): Docker
OpenCTI version: OpenCTI 6.2.0
OpenCTI client: frontend
Other environment details: none.

## Reproducible Steps

1. Create a new csv mapper
2. Introduce a external reference and map all the required fields with your csv
3. Introduce a threat actor and an attack pattern, and map them accordingly
4. Create a "uses" relationship between the threat actor and the attack pattern
5. Try to choose the external reference as a reference in said relationship

## Expected Output

The platform allows you to choose your external reference (# 3 External reference in the provided screenshot) as an external reference for the "uses" relationship.

## Actual Output

The platform does not you to choose your external reference (# 3 External reference in the provided screenshot) as an external reference for the "uses" relationship, displaying a "No options" message. However, it does allow to choose it as a reference for the threat actor and the attack pattern. 

## Additional information

No.

## Screenshots (optional)
![imagen](https://github.com/user-attachments/assets/8a70a8e0-09fc-40a5-9019-6e043f3be480)
![imagen](https://github.com/user-attachments/assets/0eacea7b-b560-4437-94e8-7c13b97c37d5)

**Comment by nino-filigran** [comment]
Hey @sofiasmargolles I see that you're not on the latest version. 

Could you please try to upgrade and see if the problem happens?
As you can see on my screen I did manage it
![image](https://github.com/user-attachments/assets/bf4f21c0-47df-4ce2-9a75-339d50432a58)

**Comment by nino-filigran** [comment]
@sofiasmargolles Closing this bug since I did not get any response so far. Feel free to reopen if needed.
