### ISSUE TITLE
Regression in massive operations on data tables

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8571]
## Description

1. Go to Data => Entities
2. Search for something
3. Select one element with a checkbox
4. Change the keyword and search for something else
5. Select another element

=> Previous behaviour: 2 elements selected

=> Current behaviour: onlye the last element is selected, 1 selected element

This regression is preventing users to correctly merge entities after multiple search / filters.

**Comment by nino-filigran** [comment]
More info regarding how to display it.

**Comment by nino-filigran** [comment]
After dicussion: 
- fix is to keep the selection even though the search/filter is trigggered (back to previous behavior)
- indication in the "selected" the amount of selected elements to make the user understand this behavior (enhancement)

We're going to prioritze this bug.

**Comment by lndrtrbn** [comment]
What I can see is that elements are still selected but the selection is not displayed on the table.
![image](https://github.com/user-attachments/assets/ae3349e8-8ecc-4b56-ac26-72d2883d6cf7)
![image](https://github.com/user-attachments/assets/c88fe675-2c18-4352-b6d5-fa120d28f41a)

**Comment by nino-filigran** [comment]
I don't have this behavior on demo.octi @lndrtrbn 

https://github.com/user-attachments/assets/05c3897f-e4b9-4660-aa89-41d92a3b2613

**Comment by lndrtrbn** [comment]
Indeed, it seems we have multiple issues here. Try using the search, not filters
