### ISSUE TITLE
time out on Simulate report with IA and Email for OpenBas

### ISSUE THREAD

**Issue by frapuks** [LuatixHQ/opencti#8585]
## Description

- Time out after 1 min when you simulate with IA and Email for OpenBas

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an Report
2. Go to this report
3. Click on Simulate (open a drawer)
4. Select `Use AI`
5. Select `Simulated (emails)`
6. Click on Generate

## Expected Output

Works

## Actual Output

Time out after 1 min!

## Additional information

- With this configuration, we generate multiple email with AI prompt. At each loop, we have 4 prompt (1 for email content, 1 for email subject, and the same for a second email). The 2 prompts for email subjects are fast, but the 2 prompts for email contents are very slow. The multiple generation are slow, more than 1 minute, and it's over the maximum delay authorized for a query.
- Current delay : approximatly 1m30s
- If you update prompts to generate only 1 paragraph (in place of 3) of 3 lines, we can reduce at : approximatly 1m (not enough)
- On local it works, but the limit is on deploy platforms.
- Issue OpenBas : https://github.com/OpenBAS-Platform/openbas/issues/1321
- Branch OpenCTI with console.log to test : https://github.com/OpenCTI-Platform/opencti/compare/master...issue/simulate-for-obas
- Maybe improve prompt ?
- Maybe have a timeout after 2 min ?

**Comment by nino-filigran** [comment]
For me it works fine: which version are you on?
![image](https://github.com/user-attachments/assets/345a85f3-8ac4-462d-9faa-a04fee974e2d)

**Comment by nino-filigran** [comment]
@frapuks up just in case :)

**Comment by frapuks** [comment]
I think, if you try with a report and have a positiv result after some seconds, it is because you have already simulate it in openBas. Try to create a new report, and simulate this new report.

**Comment by nino-filigran** [comment]
Ok, now I have the error, thanks for explaining :) 

![image](https://github.com/user-attachments/assets/d4e62bdb-92b7-42bf-9df7-ca04714671ca)
