### ISSUE TITLE
[Dashboard] Entities perspective displays the “relationship” message

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8597]
## Description

In a widget defined with "Perspective = Entities", I can read "Number of relationships" (see below), which is not normal as we are not focusing/counting relationships (contrary to the knowledge perspective)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a widget:
2. Visualization horizontal bar
3. Perspective entities
4. Filters: "entity type = malware"
5. Parameter: "Attribute=Creator"
6. Validate
7. Put you mouse on a bar:
-> You can read "Number of relationships". We are in "entities" perspective here, so we are not focusing/counting relation

![image](https://github.com/user-attachments/assets/b292b13f-d7a0-4dac-9254-325bf5b660ed)

## Additional information

I don't know if it's just the text, or the whole mechanism that's wrong.

**Comment by romain-filigran** [comment]
We need to see if we can adapt the content of this tooltip to suit the perspective.
