### ISSUE TITLE
Playground not autocompleting as expected

### ISSUE THREAD

**Issue by seanthegeek** [LuatixHQ/opencti#8600]
## Description

The playground is not showing a list of types in the autocomplete list as expected

## Environment

1. OS (where OpenCTI server runs): Debian 12
2. OpenCTI version: 6.3.4
3. OpenCTI client: Frontend
4. Other environment details:

## Reproducible Steps

1. Navigate to the GraphQL Playground with the configuration environment variable called `APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION` to `false`
2.  Type `query In`

## Expected Output

Autocomplete options should be listed, as shown in [the documentation](https://docs.opencti.io/latest/development/api-usage/#interactive-querying).

![playground-interactive-query](https://github.com/user-attachments/assets/c85867b8-3094-4907-a849-264e7e2c2e4e)

## Actual Output

The auto complete list is empty.

![2024-10-03_12-40-44](https://github.com/user-attachments/assets/c6ecaae8-0df5-463d-838d-631d5bfa429c)

**Comment by richard-julien** [comment]
In your quick gif its normal to not have any autocompletion.
What comes after the query word is the name you want to have for your query, so its a user choice.
For info this playground is now deprecated and will be replace in https://github.com/OpenCTI-Platform/opencti/issues/7363
