### ISSUE TITLE
Queries for sectors do not account for aliases

### ISSUE THREAD

**Issue by seanthegeek** [LuatixHQ/opencti#8601]
## Description

When running a query for a `Sector` named `Healthcare` when using the OpenCTI dataset, the `Healthcare technology` subsector is returned instead of the parent sector, `Health`, even though the `Health` sector created by the openCTI dataset has the alias `Healthcare`. This causes connectors like `ransomwarelive` to misattribute all attacked Healthcare organizations to `Healthcare technology`

The query that the `ransomwarelive` connector uses to find a sector is included below.

```python
self.helper.api.identity.read(
                filters={
                    "mode": "and",
                    "filters": [
                        {"key": "entity_type", "values": ["Sector"], "operator": "eq"},
                        {
                            "key": "name",
                            "values": sector,
                            "mode": "or",
                            "operator": "search",
                        },
                    ],
                    "filterGroups": [],
                },
            )
```

## Environment

1. OS (where OpenCTI server runs): Debian 12
2. OpenCTI version: 6.3.4
3. OpenCTI client: Python

**Comment by nino-filigran** [comment]
@seanthegeek I've talked internally about it & the reason is because we do not match aliases when searching for name in filters. Therefore, in your case, searching for "health" should be the best approach. Does that make sense to you?

**Comment by seanthegeek** [comment]
That's what I suspected. That is a problem a problem, because other sources may use different names for the same thing, In my example above, ransomware.live uses the word Healthcare as a sector and the connector builds a filter based on that name. Code could be added to the connector to search for Health if the sector is Healthcare, but that is a really bad solution that only covers one case. It would be much better to include all aliases in all name filters.

Consider another example: Intel reports come describing an Intrusion Set but using one of its many aliases. Because the name filter does not currently match aliases, no results would be returned, and a connector would treat that Intrusion Set as new, even though it actually is an existing intrusion set.

**Comment by ckane** [comment]
I _think_ that the solution to this is to update the above search so that it is performing the `"search"` operation against both the `"name"` field and the `"x_opencti_aliases"` field in the objects.

**Comment by seanthegeek** [comment]
Got it. Thanks.
