### ISSUE TITLE
Bulk search is not working properly anymore

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8624]
## Description

Bulk search is not working properly anymore

Search for (https://testing.octi.staging.filigran.io/dashboard/search_bulk)

89.1.2.45 (does not exist)
8.8.8.8
APT28

=> Just displaying 8.8.8.8

Search for:

89.1.2.45

=> Just displaying 89.1.2.45

APT28 is never found.

Expected result:

1. Everything is displayed, what is existing and what is not
2. Search in name / aliases / value etc. so all entities are found

**Comment by nino-filigran** [comment]
Does not happen (yet) on public demo

**Comment by SamuelHassine** [comment]
Totally happening in prod.

**Comment by SamuelHassine** [comment]
![image](https://github.com/user-attachments/assets/00d10216-6a93-4417-b2f9-ae8aa9a3729e)
