### ISSUE TITLE
Add Attack Patterns to a report by clicking on ATT&CK Matrix items

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#8640]
## Use case

For faster mapping of attack patterns, it would be nice to be able to click attack patterns in the matrix view of a report to add these attack patterns to the report. This should be no more than one click.

## Current Workaround

none

## Proposed Solution

In the matrix view of a report, make attack patterns clickable. Each click should toggle whether or not the attack pattern is added to the report. Currently added attack patterns should be highlighted.

## Additional Information

-

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by nino-filigran** [comment]
I agree, and we have this feature already planned for 6.6 https://github.com/OpenCTI-Platform/opencti/issues/6373.
I'm closing the ticket to avoid having duplicates !
