### ISSUE TITLE
[Kill chain phase ordering] We can't modify the order

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8641]
## Description

When I try to modify the order of the Kill chain phase, I can't. The field in the side editing window is like "lock"

## Environment

OCTI 6.3.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Settings > Taxonomies > Kill chain phases
2. Update an object in the list
3. Try to change its order
-> You can't

**Comment by nino-filigran** [comment]
Side note: when clicking on a kill chain, we're redirected to an empty page (ex: https://demo.opencti.io/dashboard/settings/vocabularies/kill_chain_phases/null/7b7b237e-8de9-4b86-8f2d-f71433f3ce68 )

We should not be able click on it if we do not display any information.

The global fix for the bug should be to change the order & to have no action when clicking on the page)

**Comment by SarahBocognano** [comment]
Same in Labels. Impossible to edit components using DataTable in taxonomies
