### ISSUE TITLE
Long title on dashboards can mess with UI 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8646]
## Description

When having a too long title, CTAs on the right can have a weird look & feel 

## Environment

Demo 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a dashboard
2. Give it a sufficient long name so that the CTAs on the right start to move one line below 
3. Observe the result 

## Expected Output

All CTA should be aligned and not crossing each other

## Actual Output

It's a mess
## Additional information

![image](https://github.com/user-attachments/assets/c529c583-5899-4feb-bed7-e3792bc74d5d)

**Comment by SarahBocognano** [comment]
Are we ok to add "..." with a tooltip when dashboard's name are too long to keep the UI not as a mess ?

**Comment by nino-filigran** [comment]
Yes @SarahBocognano
