### ISSUE TITLE
Editing some objects titles from the view list is broken - edition drawer is not responsive

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8647]
## Description

When clicking on edit, the drawer opens but nothing happens when trying to edit (not able to type in) 
## Environment

Demo 
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. go in <object> list
2. click on edit a <object> from the list 
3. try to type in in the title or the description 
4. nothing happens 

**Objects**
- dashboards
- taxonomies (labels only)
- investigation 

## Expected Output

You can edit title or description 
## Actual Output

Nothing happens

**Comment by nino-filigran** [comment]
Potentially same root cause as this one https://github.com/OpenCTI-Platform/opencti/issues/8649

**Comment by Kedae** [comment]
Workaround : click on the title of the field seems to be working. Still looking into it

**Comment by SarahBocognano** [comment]
Related to : https://github.com/OpenCTI-Platform/opencti/issues/8641 as well
