### ISSUE TITLE
cannot create a public dashboard from the dashboard list 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8649]
## Description

In dashboard list, when clicking on the 3 dots at the end to create a public dashboard from a dashboard, the drawer opens, but you cannot type in. As a result, you cannot create a public dashboard since the name is mandatory 
## Environment

Demo 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in a list of dashboard
2. Click on the 3 dots
3. Select the option "create a public dashboard"
4. The drawer opens 
5. select a marking 
6. Name is marked as mandatory
7. Try to type in the name field: you cannot 

## Expected Output

Ability to insert a name & type in the drawer 
## Actual Output

Cannot write in the drawer 
## Additional information

https://github.com/user-attachments/assets/633e7323-efe1-42c0-8b1e-f5cbf6083468

**Comment by SarahBocognano** [comment]
Solved by : https://github.com/OpenCTI-Platform/opencti/issues/8647
