### ISSUE TITLE
[Column resize] Increasing the size of a column makes the bulk action button disappear

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8660]
## Description

Increasing the size of a column makes the bulk action button disappear

## Environment

OCTI 6.3.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to Events > Incidents
2. Increasing the size of the "name" column
3. Select two Incidents
4. Look at the bulk action button

![Screenshot 2024-10-14 154629](https://github.com/user-attachments/assets/c92ffadb-3c8d-48b2-8752-c53d016daab2)

## Expected Output

![image](https://github.com/user-attachments/assets/19eb8447-7999-4b14-94b3-ea2eed7594e3)

**Comment by nino-filigran** [comment]
After discussion with @Lhorus6 it's not a bug: there's a scrollbar to navigate to the right of the table, allowing you to see the full list of actions.
