### ISSUE TITLE
Add an option in TAXII feed ingestion to map confidence on x_opencti_score on Indicators and Observables

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#8680]
## Use case

Add an option in TAXII feed ingestion to map confidence on x_opencti_score on Indicators and Observables

**Comment by aleksapetakovic2** [comment]
Are there any plans to get the mirror feature for shared TAXII collections, i.e. confidence score = x_opencti_score?

**Comment by SamuelHassine** [comment]
This is a good idea @aleksapetakovic2, I will implement both.
