### ISSUE TITLE
Not possible to view the list of reports authored by an organization

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8681]
## Description

It is not possible to view the list of reports authored by an organization when you are in the Analyses tab with the correct view (i.e. “display as Author”).

## Environment

OCTI 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an Organization
2. Create a Report and put this Org as Author
3. Go on the Org and the "knowledge" tab
4. Switch to "display as Author" (next to the name of the Org)
5. You will se one report

![image](https://github.com/user-attachments/assets/eaaf8d56-6717-47ff-b67f-1d439ab5bbfc)

6. Go to the Analyses view
7. Switch to "display as Author" (next to the name of the Org)
-> No report displayed

![image](https://github.com/user-attachments/assets/29bf9194-db1f-41f3-97b5-91ad560c7322)

**Comment by nino-filigran** [comment]
So the fix is:  have analysis filled with report when in author mode

**Comment by Archidoit** [comment]
@nino-filigran So in the Analysis tab of an Organization, we should have :
- for display as Author : the containers that have the organization has author (and not the containers that contain the organization)
- for display as Knowledge : only the containers that contain the organization

**Comment by nino-filigran** [comment]
Yes, you're right @Archidoit
