### ISSUE TITLE
Reset of the "display as" settings

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8682]
## Description

On an Organization, System, and other, every time I change tabs, the “display as” settings switch back to “Knowledge entity”.

I categorized it as a bug since it was not like this in the past.

## Environment

OCTI 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on the Org and switch to "display as Author" (next to the name of the Org)
2. Move to the "Knowledge" tab
-> Check the "display as", it switched back to “Knowledge entity”.

## Expected Output

Stick with what I've set up

**Comment by nino-filigran** [comment]
Cannot say whether or not it was like this before, but yeah, I agree it needs to be fixed.

**Comment by SarahBocognano** [comment]
Already fix on release 6.4.0
