### ISSUE TITLE
Container: in Source mode, you need to click twice on Source mode to quit the source mode 

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#8688]
## Description

When in an HTML in source mode you need to click twoce on source to revert back to UI mode 
## Environment

Demo octi 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go in a report
2. add some content
3. switch to source mode
4. click on source again 

## Expected Output

On the second click I should be in UI mode 
## Actual Output

I'm still on source mode 

## Screenshots (optional)

https://github.com/user-attachments/assets/d774b558-d25b-479f-97ef-7021135ee0df

**Comment by Archidoit** [comment]
@nino-filigran I don't reproduce anymore. It seems solved by the ck editor migration isn't it?

**Comment by nino-filigran** [comment]
You're right @Archidoit, not reproduced anymore
