### ISSUE TITLE
Update of the confidence level on an entity break the entity update/sync when ingested through an OCTI stream Feed

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8711]
## Description

When ingested a Feed exposed through a remote OCTI stream, it would appears that when the confidence level of an entity is updated in the remote OCTI instance (server instance) this prevent the OCTI client to apply new updates on the entity

## Environment

2. OpenCTI version: 6.3.5

## Reproducible Steps

1. Configure an OpenCTI data sharing stream in platform A
2. Configure an OpenCTI stream client in platform B that consume the feed exposed by platform A
3. Create an entity (ex: a malware) in platform A and check that the entity is correctly created in platform B
4. Update the entity in platform A,  update the confidence level of the entity and add a label
5. In platform B, the entity confidence level is not updated and the label is not added
6. Since this moment, no more updates will be applied to the entity in the platform B

It seems that the problem is on the client side, given that the stream is correctly updated.

**Comment by JeremyCloarec** [comment]
@romain-filigran did you set your platform B stream as a perfect sync? ![Image](https://github.com/user-attachments/assets/89feee57-309e-4771-b141-0bf723e0f5ee)
I didn't try to reproduce your scenario exactly, but I noticed that when trying to upsert an entity with a lower confidence manually, the same thing happens: the labels are not added to the existing entity if the confidence of the duplicate entity you are creating is lower than the existing entity confidence. So it looks like the behavior you describe from your scenario is working as expected?
If you set the sync to a perfect sync though, it should update the entity correctly

**Comment by romain-filigran** [comment]
Closing because this is normal behavior if we're not in perfect synchronization.
