### ISSUE TITLE
[Playbooks] unable to filter on "Platform Creation Date" on "Query knowledge on regular basis"

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#8721]
## Description

Error messaged received when trying to create a Playbook that "Query knowledge on regular basis" with a "Platform Creation Date" filter -> receives an Error (see below)

## Environment

OpenCTI version: 6.3.6

## Reproducible Steps

1. Go to Data > Processing > Create a new playbook
2. Click the rectangle to create the first step of the playbook and choose ""Query knowledge on regular basis"
3. Fill in the info and add the filter "Platform creation date" with a date

Example: 

<img width="752" alt="Screenshot 2024-10-21 at 14 12 32" src="https://github.com/user-attachments/assets/0a0f2765-5291-46c7-b1df-f4c79f109e36">

## Expected Output

Should filter results from the date noted in the filter

## Actual Output

Error message: 

<img width="632" alt="Screenshot 2024-10-21 at 14 12 12" src="https://github.com/user-attachments/assets/6166a582-05a3-48f6-a0cf-5bc358bff007">

**Comment by nino-filigran** [comment]
@EinatAR I've reproduced but be aware that this playbook might be difficult to maintain while we do not have any dynamic filtering (given that we'll fetch a max of 5000 entities). The more time past, the more entities will be re-fetched. Therefore, you would need to update the date manually if you want to ensure that data is always fetched as expected. Ping me if you need more information :)
