### ISSUE TITLE
Manual Installation: Elasticsearch on seperate serves

### ISSUE THREAD

**Issue by khoavan001** [LuatixHQ/opencti#8729]
## Description

i tried to manual install OpenCTI with ElasticSearch cluster on seperate servers. i got erro when try to connect to elasticsearch

## Environment

1. OS:      Ubuntu 22.04
2. OpenCTI version: OpenCTI 6.3.6
3. OpenCTI client: python
4. Other environment details:
Elasticsearch cluster: 8.15
node: 4
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  yarn install
2.  yarn build
3.  yarn serv

## Expected Output

openCTI is up and running

## Actual Output

root@openCTI:/home/sysadmin/opencti# yarn build
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(node:135882) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
b Parse Configuration
b Generate outputs

  build/back.js                        23.5mb b -8
  build/script-clean-relations.js      21.2mb b -8
  build/nodecallspython-UO3QPWIP.node   1.2mb b -8
  build/back.js.map                    23.9mb
  build/script-clean-relations.js.map  21.6mb

b! Done in 2048ms
root@openCTI:/home/sysadmin/opencti# yarn serv
{"category":"APP","environment":"production","level":"info","message":"[OPENCTI] Starting platform","source":"backend","timestamp":"2024-10-22T07:42:25.426Z","version":"6.3.6"}
{"category":"APP","level":"info","message":"[FEATURE-FLAG] Deactivated features still in development: FAB_REPLACEMENT,NEW_IMPORT_SCREENS,FILIGRAN_LOADER,CONTAINERS_AUTHORIZED_MEMBERS,TELEMETRY_COUNT_ACTIVE_USERS,PROTECT_SENSITIVE_CHANGES","source":"backend","timestamp":"2024-10-22T07:42:25.428Z","version":"6.3.6"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","source":"backend","timestamp":"2024-10-22T07:42:25.428Z","version":"6.3.6"}
{"category":"APP","level":"info","message":"[CHECK] checking if Search engine is alive","source":"backend","timestamp":"2024-10-22T07:42:25.428Z","version":"6.3.6"}
(node:136024) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"category":"APP","level":"info","message":"[SEARCH] Engine client not specified, trying to discover it with opensearch client","source":"backend","timestamp":"2024-10-22T07:42:25.436Z","version":"6.3.6"}
{"category":"APP","cause":{"extensions":{"code":"CONFIGURATION_ERROR","data":{"cause":{"meta":{"body":null,"headers":null,"meta":{"aborted":false,"attempts":3,"connection":{"_openRequests":0,"deadCount":4,"headers":{},"id":"https://10.255.2.91:9200/","resurrectTimeout":1729583425546,"roles":{"data":true,"ingest":true},"status":"dead","url":"https://10.255.2.91:9200/"},"context":null,"name":"opensearch-js","request":{"id":1,"options":{},"params":{"body":null,"headers":{"user-agent":"opensearch-js/2.12.0 (linux 5.15.0-124-generic-x64; Node.js v22.9.0)"},"method":"GET","path":"/","querystring":"","timeout":30000}}},"statusCode":null},"name":"ConnectionError"},"genre":"TECHNICAL","http_status":500}},"message":"Search engine seems down"},"level":"error","message":"[OPENCTI] System dependencies check failed","source":"backend","timestamp":"2024-10-22T07:42:25.546Z","version":"6.3.6"}
{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"Search engine seems down","name":"CONFIGURATION_ERROR","stack":"GraphQLError: Search engine seems down\n    at error (/home/sysadmin/opencti/build/src/config/errors.js:7:10)\n    at ConfigurationError (/home/sysadmin/opencti/build/src/config/errors.js:75:53)\n    at /home/sysadmin/opencti/build/src/database/engine.js:241:15\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at searchEngineVersion (/home/sysadmin/opencti/build/src/database/engine.js:237:22)\n    at searchEngineInit (/home/sysadmin/opencti/build/src/database/engine.js:323:27)\n    at checkSystemDependencies (/home/sysadmin/opencti/build/src/initialization.js:38:3)\n    at platformStart (/home/sysadmin/opencti/build/src/boot.js:15:7)"},{"message":"self-signed certificate in certificate chain","name":"ConnectionError","stack":"ConnectionError: self-signed certificate in certificate chain\n    at ClientRequest.onError (/home/sysadmin/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:103:11)\n    at TLSSocket.socketErrorListener (node:_http_client:506:5)\n    at TLSSocket.emit (node:events:519:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at processTicksAndRejections (node:internal/process/task_queues:90:21)"}],"level":"error","message":"Search engine seems down","source":"backend","timestamp":"2024-10-22T07:42:25.548Z","version":"6.3.6"}

**Comment by Kedae** [comment]
Hi,

Can you confirm that you can access https://10.255.2.91:9200/ to get your elastic ?

**Comment by khoavan001** [comment]
yes i can access elasticsearch using both curl -u user:password or using kibana (i already installed to make sure elasticsearch cluster is running)

**Comment by gileri** [comment]
Hi @khoavan001,

A bit hidden in the logs you provided is the following error :

> {"message":"self-signed certificate in certificate chain","name":"ConnectionError","stack":"ConnectionError: self-signed certificate in certificate chain\n at ClientRequest.onError (/home/sysadmin/opencti/build/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16 [...]

This message indicates that OpenCTI encounters a self-signed "HTTPS" certificate when connecting to Elasticsearch.

To solve that, you can either generate a proper certificate for your Elasticsearch, with a local certificate authority. Or more easily, you can tell OpenCTI to ignore errors like this with the following [environment variable or configuration item](https://docs.opencti.io/latest/deployment/configuration/?h=introspection#elasticsearch) :

`ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED=false`

**Comment by khoavan001** [comment]
@gileri I am aware problem is self-signed certificate and tried to install in trusted ca store of server but still failed. i have noted ELASTICSEARCH__SSL__REJECT_UNAUTHORIZED=false in docs but dont understand what it means.
i have opencti running, finally.
thank you. you are my life saver.

**Comment by gileri** [comment]
No problem ! Yes it can be tedious to manage CA certificates, glad it could save it for you.
