### ISSUE TITLE
[Filter] No more filters on Sectors

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8730]
## Description

When I am in my sector list, the filters are no longer present.

## Environment
OCTI 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on Entities > Sectors

## Expected Output

![image](https://github.com/user-attachments/assets/b6f09a00-92c3-45c6-8940-65adc6417c37)

## Actual Output

![image](https://github.com/user-attachments/assets/eb579427-fe0c-431c-89f2-94fc9dccb3d0)

**Comment by romain-filigran** [comment]
@Lhorus6 : Are you sure this view contained a filtering capability? Given that it's an indented list, it's possible that it was never possible to filter on it.

**Comment by nino-filigran** [comment]
For now we we'll close it, because it never existed. Also it's a bit unclear on what we could filter beside "is parent" or "is subsector". We do not plan to add filters anytime soon after a discussion internally.
