### ISSUE TITLE
Starting opencti

### ISSUE THREAD

**Issue by AlexForensic** [LuatixHQ/opencti#8755]
Hello, 

version : 6.3.6 on debian 12.
I have this error when i m starting opencti : 
![image](https://github.com/user-attachments/assets/36918fff-99c7-4dbe-84e4-54e5b88d662a)

What can i do ?

**Comment by Kedae** [comment]
Hi @AlexForensic,

Can you provide more explanation on your installation ? What you have done ? How is your redis configured ?
Have you correctly configured you env ?

**Comment by AlexForensic** [comment]
Hello, 
I followed the manual installation of the product. I modified the tokens in the production.json file and the id for the connexion.
I didn't make any particular modification to Redis.

**Comment by AlexForensic** [comment]
@Kedae  
Now i have this message : 
![image](https://github.com/user-attachments/assets/7e2283a2-ba84-4ae1-a727-9e2fdcd758f2)

**Comment by Kedae** [comment]
Hi,

You still have a connection error, you need to check your production.json to see if your hostnames/urls/.. are ok.

**Comment by AlexForensic** [comment]
Hi @Kedae, 
I'm doing a new installation. But each time I install a new file with the "yarn install" command, I get this error message: 
![image](https://github.com/user-attachments/assets/266d75af-c83b-4482-a657-c14e0f3737e8)

**Comment by Kedae** [comment]
Can you try cleaning your yarn cache and trying again ?

**Comment by AlexForensic** [comment]
@Kedae I've already done it and it's always the same mistakes. So I install the webpack from npm.
Then I no longer get this error and I build.
