### ISSUE TITLE
"Marking definitions" issues between different “Groups” within the same “Roles”

### ISSUE THREAD

**Issue by misohouse** [LuatixHQ/opencti#8759]
OpenCTI version : 6.3.6

I want to show data separately between different groups that exist within the same role.

To accomplish what I wanted, I set up roles, groups, accounts, and marking definitions as shown in the photo below.

![role](https://github.com/user-attachments/assets/57cd5bf8-c5b1-4721-8d10-d2e40224c614)
![role2](https://github.com/user-attachments/assets/bfef4506-e618-4eeb-b0b5-cb914283a869)
![group](https://github.com/user-attachments/assets/c3b6bdf8-439c-4d57-aa60-87772570d6e2)
![account](https://github.com/user-attachments/assets/24593722-528c-43fc-b1a7-dc0cf2215f47)
![44](https://github.com/user-attachments/assets/acc87315-e8fa-424b-9fd9-b6a54edaf1e2)
![55](https://github.com/user-attachments/assets/ea91099e-6fa1-48ed-9ae5-88dafb29c1ae)

The problem is that when I log in as the test account and check, I see data with a marking definitions(Test_B) that I didn't specify in the settings.
<img width="1286" alt="66" src="https://github.com/user-attachments/assets/64cb0186-11ec-454a-a049-dedf58369b23">

The group assigned to the test account is Test_A, and only Test_A has been assigned a marking definition, so I think it is normal that data with a Test_B marking definition should not be visible.

Or is it because I set the order value to 0 when I set the marking definition?

I ask because I see data from other marking groups even when I don't specify roles when setting up groups.

I would appreciate your response to this issue.

**Comment by nino-filigran** [comment]
It does not sound right @misohouse , I'll try to reproduce, but in the meantime, could you let me know 3 things?
- did you create your marking **after** you created you group "external"?
- could you verify what marking "external" has access to?
- could you verify, when you go to external, edit this group, whether this group has the toggle "
Automatically authorize this group to new marking definition" enabled ?

**Comment by misohouse** [comment]
@nino-filigran 

Q1. did you create your marking after you created you group "external"?
A1. 
That's right. The External role is the role you created previously.

Then I created the Test_A group and added only the Test_A group to the External role.

Finally, I created the Test_A marking definition, and added the Test_A marking definition to the Test_A group
.
.
.
.
.
.
Q2. could you verify what marking "external" has access to?
A2.
The Marking definitions accessible to the External group are shown in the figure below.
![111](https://github.com/user-attachments/assets/c136de63-79aa-4ec3-adfe-b3724cd2b84e)
.
.
.
.
.
.
Q3. could you verify, when you go to external, edit this group, whether this group has the toggle "Automatically authorize this group to new marking definition" enabled ?
A3.
I think the screen below might answer your question.
![112](https://github.com/user-attachments/assets/598aad7d-b0e1-4778-aa28-3d8a83447ac1)

**Comment by nino-filigran** [comment]
Ok thanks for your quick answer. At least I can already evacuate this option. I'll keep you posted about reproduction and any questions/information I might need.

**Comment by nino-filigran** [comment]
I can't manage to reproduce so far, will keep investigating. Could you perform the same check than above but for the 2 groups TEST_A & TEST_B ( just to be sure)?

**Comment by nino-filigran** [comment]
Could you share also also a screenshot of your marking definition page?

**Comment by nino-filigran** [comment]
And last question from my side: what is the process you have followed when creating your marking & users? 
Did you create all your users & groups first? And/Or your markings? & Did you assign all markings to your groups in one go, or did you create one marking, assigned it to a group, then created another marking & assigned it to a group?

**Comment by misohouse** [comment]
@nino-filigran 

**A screenshot of "Marking definition page"**
![md page](https://github.com/user-attachments/assets/e15816b7-7294-407d-892f-e392f0eed24e)

**Q1. what is the process you have followed when creating your marking & users?**
A1.
Users were created in the “Settings/Security/Users” menu.

After that, marking definitions were created in the “Settings/Security/Marking definitions” menu (TLP:AMBER+A, TLP:AMBER+B)

After creating the markings, I realized that I could assign markings by group, I created the groups Test_A and Test_B and put the above marking definitions in “Allowed markings”.

After that, I added the Test_A and Test_B groups to “Groups using this role” in External Roles.
.
.
.
.
.
**Q2. Did you create all your users & groups first? And/Or your markings?**
A2.
The user is a test account, so I created it when I first built the platform.

Groups and markings were created following the procedure outlined in the first question.
.
.
.
.
.

**Q3. Did you assign all markings to your groups in one go, or did you create one marking, assigned it to a group, then created another marking & assigned it to a group?**
A3.
I created two marking definitions first, then creating two groups.

And I assigned a marking definition to each group.
(Please refer to Answer 1).

**Comment by misohouse** [comment]
@nino-filigran 

Hi, I'd appreciate it if you could let me know the progress on this issue.

**Comment by nino-filigran** [comment]
Hey @misohouse sorry for not having followed this up. 
So indeed, the problem **comes form the order** (which is the same) assigned to each markings.

Basically, we would expect if 2 markings are different (different meaning/scope) that they would not belong to the same type: in your case, this would mean a specific type for group owning UserA & a specific type for group owning UserB. 

This would solve your issue. Is that a solution that could work for you?

**Comment by misohouse** [comment]
@nino-filigran 

Um... I didn't understand your answer exactly.

Based on the photo I uploaded before, can you tell me clearly in which settings I need to change the values (or the order of the marking definitions?? I'm not sure)?

**Comment by misohouse** [comment]
@nino-filigran 

As you said, it was the order's problem.

When I changed the orders of two markings to different, it was worked what I wanted.

I think that the problem is solved.

Thank you for replying :)
