### ISSUE TITLE
TAXII collection not accessible which is created by user on the demo website.

### ISSUE THREAD

**Issue by NeerajGulia** [LuatixHQ/opencti#8761]
## Description

TAXII collection is not accessible which is created by the user on the demo website. Same I am able to replicate to my local instance of OpenCTI

## Environment

1. OS: Ubuntu 22.04 
2. OpenCTI version: 6.3.6
3. OpenCTI client: frontend and python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login to the demo website - https://demo.opencti.io/
2. Go to Data -> Data Sharing
3. Create TAXII Collection
4. Disable "public collection"
5. Do not enter anything in "Accessible for" (I even tried adding group and organization to which user belongs, but still did not work)
6. Create collection
7. From the UI click on the collection
8. It will land user to collection objects - https://demo.opencti.io/taxii2/root/collections/d8c28de9-1a9d-4fbf-a88d-dd16a53af7c4/objects
9. gives error - {"title":"You are not allowed to do this.","error_code":"GraphQLError","http_status":500}
10. Gives same error if try to access the collection using python TAXII client library - taxii2client

## Expected Output

Logged in user should be able to access the TAXII collection for non public collections. 

## Actual Output

Authentication fails and user not able to access the taxii collection.
The collection is accessible only if I use admin credentials, or if I enable "public taxii collection" while creating the taxii collection.

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/4a9a45dd-e016-4a56-9a17-ce61a81e7eac)
![image](https://github.com/user-attachments/assets/380ea298-16e8-4c39-bda7-437ff19d337f)

**Comment by aHenryJard** [comment]
Hello @NeerajGulia have you set your own user in "Accessible for" ? It should work that way.

**Comment by NeerajGulia** [comment]
> Hello @NeerajGulia have you set your own user in "Accessible for" ? It should work that way.

Hello @aHenryJard I verified and added own user in "Accessible for", but its not working. I even tried adding groups, organizations etc as well.

**Comment by nino-filigran** [comment]
I've reproduced this issue. Only way to access the TAXII is by making it public, which is not desired.

**Comment by NeerajGulia** [comment]
A new update. I created a new user and given "Access data sharing" capability to the role assigned to user. Now I am able to access the TAXII collection using the new user. However, only admin can add the capability to the given role.

**Comment by nino-filigran** [comment]
I'm not sure to unerstand your exact issue here: the fact that only an admin (manage users) can proivde the capability is normal. So you're tested it again, with a user having the capability "access data sharing" and was able to access the taxii collection even though you were not in the "accessible for"?

**Comment by NeerajGulia** [comment]
> I'm not sure to unerstand your exact issue here: the fact that only an admin (manage users) can proivde the capability is normal. So you're tested it again, with a user having the capability "access data sharing" and was able to access the taxii collection even though you were not in the "accessible for"?

Yes. In a nutshell we need to add the "access data sharing" capability to the user role. Just adding the user to the "Accessible For" will not enable the user to access the TAXII feed.
Adding user to the "Accessible For" will restrict access to TAXII feed to other users (Even if the capability is enabled for them).
If we keep the "Accessible For" as empty then all users who have "access data sharing" capability will be able to access the TAXII feed.

**Comment by nino-filigran** [comment]
Thanks for the clarification !
