### ISSUE TITLE
Switch from "opt-out dev features" to "opt-in feature flags"

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#8764]
## description 
Today, we can define in the [app configuration file](https://github.com/OpenCTI-Platform/opencti/blob/e17b1ed7b3f65435eaeeab4320482b18c7f5aa9f/opencti-platform/opencti-graphql/config/default.json#L9) a list of dev feature flags to disable (opt-out).
This served well in a purely dev context, allowing to easily see in the config file the existing flags, switch them, etc.

However, this approach is counter intuitive in many aspects of our daily operations.
Deploying new platforms with feature flags enabled will be much more clear to everyone, for config, debugging, etc.

## solution
Turn config into : 

```json
  enabled_feature_flags: [
    FEATURE_FLAG_1,
    FEATURE_FLAG_2
  ],
```

And rework the utility code that checks these flags, backend and frontend side.

**Comment by sweet-mentat** [comment]
Is there a place where I can see available feature flags?

**Comment by labo-flg** [comment]
Hi @sweet-mentat
We do not maintain a documentation page for the feature flags, I'm afraid.
This is because we usually do not open features in development to beta testing. These features are still in development, half baked stuff that could make your platform really unstable. 

Now if you're curious, just have a look in the codebase ; search for use of `isFeatureEnabled()` in both frontend and backend.

Please keep in mind that we do not support things under feature flags and won't help in settings things up or understanding how it works. Obviously, I suggest you use a dedicated test platform for that purpose, do not enable feature flags in production.

**Comment by sweet-mentat** [comment]
Thank you for the help!
