### ISSUE TITLE
Having a large number of Organizations slows down the playbooks

### ISSUE THREAD

**Issue by labo-flg** [LuatixHQ/opencti#8767]
## Description

When the platform ingests many many organizations, for instance through a feed like ransomware.live, it slows down the platform performances.

It might be due to the way we handle organizations in the platform, according to organization sharing (caching, playbooks on orga sharing).

## Environment

OCTI 6.3.6

**Comment by khalidelborai** [comment]
When should we have a timeline for this bug? and if we can offer any help once you share/find any further details.

**Comment by labo-flg** [comment]
I'm splitting this issue, creating specific bugs to track resolution of specific issues.
