### ISSUE TITLE
Creators not accumulated when setting "do not accumulate" is off

### ISSUE THREAD

**Issue by petskratt** [LuatixHQ/opencti#8792]
## Description

Editing an object (ex: report) does not accumulate users as shown in https://docs.opencti.io/latest/usage/exploring-entities/#visualizing-knowledge-associated-with-a-sector - this could be regression bug related to https://github.com/OpenCTI-Platform/opencti/issues/7290 e.g "Do not accumulate creators for the users of this group" implementation.

## Environment

1. Local Docker setup, based on https://github.com/OpenCTI-Platform/docker
2. OpenCTI 6.3.6, clean install for testing

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Fresh OpenCTI 6.3.6 install, setting "Do not accumulate creators for the users of this group" for Deafult group is off
2. Create users A and B in Default group
3. Log in as user A, create report X
4. Log in as user B, edit report X (ex description / content, add observable)

## Expected Output

Both users are listed as creators.

## Actual Output

User A remains the sole creator

## Additional information

Asked this question in https://filigran-community.slack.com/archives/C06CETVDJ5R/p1729167123623639, no response so presuming this is bug.

**Comment by SouadHadjiat** [comment]
This is not a bug, creators are not accumulated when editing an object, only when creating the same object (upsert logic). Could you confirm @nino-filigran ?

**Comment by Jipegien** [comment]
I confirm. Creators accumulate only when upsert is performed. @petskratt If you need a different implementation, you can reopen the issue. FYI, you can see which users perform modification in the history of the entity.
