### ISSUE TITLE
Finding report duplicates does not work properly

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#8800]
## Description

We noticed that analysts sometimes produced duplicate reports in OpenCTI for OSINT reports. After some testing, we noticed that the detection of potential duplicates is not triggered when a report title is pasted into the text field.

## Environment

2. OpenCTI version: 6.3.1

## Reproducible Steps

1. Create a report with name `Reporty McReportface` (or something else :) )
2. Copy the report title
3. Open the dialog to create another report and paste the title
4. You should now see a hint that a potential duplicate was found, but instead, it is shown that there is no potential duplicate

## Expected Output

You should now see a hint that a potential duplicate was found, but instead ...

## Actual Output

... it is shown that there is no potential duplicate.

## Additional information

none

**Comment by romain-filigran** [comment]
Hi @ups1decyber :The duplication notification is correctly displayed if you manually enter the report name but in fact it is not triggered when you copy/paste the name. We'll see if we can improve this behavior

**Comment by CelineSebe** [comment]
Already fix with #8180 I think
