### ISSUE TITLE
Bulk actions invisible in the tool bar for some screens resolution

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#8808]
## Description
No actions available in the toolbar for some screens resolution (actions are too on the right)

## Reproducible Steps
- Go to the reports list and select some reports
- The tool bar is empty : no action can be done, need to change screen resolution
![image](https://github.com/user-attachments/assets/15ac524b-6e74-433f-8551-7c71b236210f)

![image](https://github.com/user-attachments/assets/db48a32e-e374-4a0e-9b15-ffab8e648dd6)

**Comment by labo-flg** [comment]
This happens if you move the window around onto another screen that has another resolution. Recomputation of the table width is not done.

You can click on the table actions, and click on Reset Table to remake this computation and fix the problem.

**Comment by Archidoit** [comment]
Maybe linked issue as we talked about @lndrtrbn https://github.com/OpenCTI-Platform/opencti/issues/9138

**Comment by lndrtrbn** [comment]
> Maybe linked issue as we talked about [@lndrtrbn](https://github.com/lndrtrbn) [#9138](https://github.com/OpenCTI-Platform/opencti/issues/9138)

After some investigations, my rework does not fix this, and I think it's two independent topics.
