### ISSUE TITLE
[Workbench] Relationships not created

### ISSUE THREAD

**Issue by NiQuintin** [LuatixHQ/opencti#8818]
## Description

By importing a list of IPs in a .txt file linked to an incident at the panel data level of an incident entity, the observables and the relationships between these observables and the incident are identified in the workbench. 
Once the workbench has been validated, the observables are created, but not the relationships. This means that the relationships have to be created manually, which is a constraint with a large volume of observables.

## Environment

OpenCTI version 6.3.6

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. From an incident entity, importing observables,
2. Checking the workbench to see the observables and relationships,
3. Validating the workbench,
4. Check for the elements created, relationships aren't added.

## Expected Output

Having the relationships created 

## Actual Output

Only the observables, not the relationships 

## Additional information

Reproduced on testing.

## Screenshots (optional)
![IP_Incident](https://github.com/user-attachments/assets/48e3abf5-baf6-455c-949e-0432bdda1438)

**Comment by JeremyCloarec** [comment]
Fix push on connector repo https://github.com/OpenCTI-Platform/connectors/pull/2915
