### ISSUE TITLE
Bug may lead to deletion of all entities in OpenCTI

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#8837]
## Description

Hi all,

a bug in the search result list may lead to deletion of all entities. This caused quite some trouble when we noticed this, but I was able to reproduce the issue in a test instance.

## Environment

1. OS (where OpenCTI server runs): For reproducing the issue, the example docker-compose setup can be used
2. OpenCTI version: 6.3.1 (where we first noticed the bug) / 6.3.7 (where we could also reproduce the bug)
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

1. Set up a fresh OpenCTI instance, e.g. by using the [example docker setup](https://github.com/OpenCTI-Platform/docker).
2. Add some reports, observables and so on. Doesn't really matter what you add.
3. For one report, add an opinion (I used `neutral` to reproduce the issue, but it doesn't really matter)
4. In the platform search bar, search for `neutral`. You should now see exactly one result.
5. Select the checkbox above the single result (the checkbox that is used to select all items of a list)

![image](https://github.com/user-attachments/assets/06c07867-c380-4677-9bc0-23c75069c745)

6. The action bar should show "1 selected". Click "Delete" and confirm.
7. Watch how a background tasks deletes all entities.

## Expected Output

I would expect that OpenCTI deletes only entities that match the given search term. However, it seems that when using the "Select all" checkbox, all items that match a given filter are deleted. Since I did not specify any filters, a background task that deletes all items was queued and executed.

## Actual Output

A background task deleted all items instead only those that match my search terms.

**Comment by nino-filigran** [comment]
Even easier use case: 
- go on platform (like testing)
- search trhough global search
- select an amount of item to delete trhough the select all
- clcik on delete and notice the amount that should be deleted
- go in task
- the amount is not the same.

**Comment by labo-flg** [comment]
Bug limited to global search, fixed with #8845
