### ISSUE TITLE
Show opinion comments in the report overview

### ISSUE THREAD

**Issue by ups1decyber** [LuatixHQ/opencti#8842]
## Use case

We use the opinion feature in reports to allow users of OpenCTI to provide feedback to our CTI analysts. Unfortunately, it seems that it's not so easy to read the optional comments that users can provide when submitting an opinion.

We would like to have the opinion comments somewhere on the report overview page or in another tab of the report, so that report authors can easily find and read them.

## Current Workaround

It is possible to find opinion entities through the search or through data > entities. But that's a quite user-unfriendly way to find opinions on a specific report.

## Proposed Solution

Add an option to show opinions (specifically associated comments) on a specific report somewhere in the report overview or in a separate tab.

## Additional Information

none

## If the feature request is approved, would you be willing to submit a PR?

No

**Comment by labo-flg** [comment]
This has been tackled in 6.4.0.
To easily access all opinions in the report, just click on the radar distribution widget in the report details.
It open a dialog with all opinions including comments.

![Image](https://github.com/user-attachments/assets/866e4523-9177-4d53-893a-7a3c2d9b9488)
