### ISSUE TITLE
Permissions from External Auth Server Not Mapped to OpenCTI Platform Groups When Logging in via loginFromProvider

### ISSUE THREAD

**Issue by savannah030** [LuatixHQ/opencti#8867]
## Description

When logging in through the loginFromProvider method, permissions assigned by the external authentication server are not properly mapped to the corresponding OpenCTI platform groups. As a result, users do not receive the correct group-level permissions within OpenCTI.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. The original permissions, as shown in the first screenshot, were set by the external authentication server and later changed to those in the second screenshot (**with OPENCTI_TEST_B removed**).

![스크린샷 2024-11-01 105018](https://github.com/user-attachments/assets/6b20df02-a048-4631-b822-08367b07361e)
![image](https://github.com/user-attachments/assets/a21727af-3174-43ce-8476-b00a4ebeda58)

2. The user accesses the opencti platform.

## Expected Output
In the OpenCTI platform, **I expect the user's group to exclude Test_B.**

## Actual Output
In the OpenCTI platform, the user's group Test_B is not being removed as expected.

![스크린샷 2024-11-01 105638](https://github.com/user-attachments/assets/76349cbf-be3a-4423-ba8d-1553398867c6)

**Comment by richard-julien** [comment]
Thanks for the report and thanks for the PR!
PR is merged, closing the ticket.
