### ISSUE TITLE
Public dashboard erros on some widgets when not configuring any time range

### ISSUE THREAD

**Issue by JeremyCloarec** [LuatixHQ/opencti#8901]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a dashboard
2. Add an entities vertical bar widget, with any filters and Week as interval
3. Click on 'None' in the dropdown of Relative time
4. Create a public dashboard from this dashboard

## Expected Output

The public dashboard with data in widget

## Actual Output

The public dashboard with an error in widget

## Additional information

This error is due to the startDate and endDate being sent as null in the public dashboard widget request.
They are set to null in usePublicDashboardWidgets.tsx: 
```
 const startDate = config?.relativeDate ? computerRelativeDate(config.relativeDate) : config?.startDate;
  const endDate = config?.relativeDate ? formatDate(dayStartDate(null, false)) : config?.endDate;
```

**Comment by romain-filigran** [comment]
Reproduced on version 6.3.9
