### ISSUE TITLE
Investigation: cannot expand observables of type File

### ISSUE THREAD

**Issue by marckto-filigran** [LuatixHQ/opencti#8908]
If you try to expand files from an investigation, the page will load indefinitely.
<img width="661" alt="image" src="https://github.com/user-attachments/assets/da353539-a3af-475d-bf13-7faa2b0987a0">

**Comment by SarahBocognano** [comment]
Probably linked to those changes: https://github.com/OpenCTI-Platform/opencti/issues/7255

**Comment by marieflorescontact** [comment]
Fixed by : https://github.com/OpenCTI-Platform/opencti/pull/8933

**Comment by marieflorescontact** [comment]
Fixed by : https://github.com/OpenCTI-Platform/opencti/pull/8933
