### ISSUE TITLE
Export / Import for Automation Playbooks

### ISSUE THREAD

**Issue by atluxity** [LuatixHQ/opencti#8915]
## Use case

As a sysadmin for OpenCTI I want a way to export and import the automation playbooks I have defined.

## Current Workaround

I made a python script that queries the API to export a json version of the playbooks I have created. I have not made an import workaround. I mostly wanted it for my own documentation.

## Proposed Solution

I have no idea about this. 

## Additional Information

N/A

## If the feature request is approved, would you be willing to submit a PR?

No, I am not a dev

**Comment by richard-julien** [comment]
Closed as duplication of https://github.com/OpenCTI-Platform/opencti/issues/4523
