### ISSUE TITLE
Domain observable with hyphen/dash is incorrectly rejected 

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#8927]
## Description

A domain name can contains a dash or hyphen in it's value.
Same for subdomain

Example: 

- test-test.com
- test-test.mydomain.com

## Environment

2. OpenCTI version: 6.3.10

**Comment by aHenryJard** [comment]
**Reopening**: This feature has been reverted du to performance issues, we need to add a test coverage on regeprx performance issue (relates to https://github.com/OpenCTI-Platform/opencti/issues/8942)
