### ISSUE TITLE
[Workbench] Validation is allowed even without the capability "Create / Update knowledge"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#8962]
## Description

The "Import knowledge" capability allows access to the workbench.
The "Create / Update knowledge" allow ingest the data, i.e. to validate the workbench and write the data into the database.

If you only have "Import knowledge", you can still validate the workbench, but nothing will happen (the data will not be created). Moreover, a validation message is displayed, despite the fact that it will not work, which is very confusing:

![Image](https://github.com/user-attachments/assets/18657aea-6066-4d98-b43b-df8bc72333d0)

## Environment

OCTI 6.3.11

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. With an admin user, create a report A, import a pdf in the report A's Data tab, and generate a workbench (if it has not been generated automatically).
2. Create a User B with all marking allowed and only "Access knowledge" and "Import knowledge" capabilities
3. Log in with user B
4. Go on the report A's Data tab.
5. Click on the workbench.
6. Validate the workbench.
7. Check that entities in the workbench that did not exist in the platform are still non-existent

## Expected Output

The validation button should be grayed out, or an error message should be displayed after clicking the button if you don't have the "Create / Update knowledge" capability.

**Comment by nino-filigran** [comment]
Got spot @Lhorus6 , user without validate knowledge should not be able to validate a workbench at all!
