### ISSUE TITLE
CSV mappers: default value for authors does not show that a default value is set

### ISSUE THREAD

**Issue by nino-filigran** [LuatixHQ/opencti#9007]
## Description

When setting a default value for author, there's no green icon idnciating that a default value for author has been set.
## Environment

1. demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a CSV mapper
2. Add an entity represnetation that have the author field 
3. set a default value for author

## Expected Output

A little green icon on the top of the wheel should be present

## Actual Output

The icon is not present

**Comment by CelineSebe** [comment]
Issue already solved with the last release
