### ISSUE TITLE
Entity type filter values are not restricted in Relationship creation form list

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#9073]
## Description
Entity type filter in Relationship creation form list from Knowledge tab of an entity should only propose possible values

## Reproducible Steps
- Go to a malware Knowledge tab
- Go under 'Threat actors'
- in the list, only threat acotr individuals and threat actor groups are displayed 
- Add a filter on 'entity type'
- All the entity types are proposed in the filter list, whereas we should only have the possible ones (Threat Actor Group and Threat Actor Individual in this case)

![Image](https://github.com/user-attachments/assets/b9b10951-b6ff-4514-bd56-3650eca508aa)

Same for other screens of Knowledge

**Comment by Jipegien** [comment]
limit the option to Threat Actor (Group) and Threat Actor (Individual)
