### ISSUE TITLE
Need to refresh when deleting a marking definition

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#9081]
## Description
Updater error when deleting a marking definition

## Reproducible Steps
- Go to Settings > Security > Marking definition
- delete a marking definition
- The pop up doesn't close 
![Image](https://github.com/user-attachments/assets/9072aa3b-1b3b-43e8-8c11-9d3ce266e09f)

- if we refresh the page, the marking is correctly deleted.

**Comment by SamuelHassine** [comment]
Duplicate of #9049.
