### ISSUE TITLE
Error when exporting a list of entities in PDF format

### ISSUE THREAD

**Issue by gkallenborn** [LuatixHQ/opencti#9082]
## Description

After making a search on the knowledge graph, I wanted to export a list of selected entities in PDF format. The connector launched, but the process ended with the following error: 

`string indices must be integers, not ‘str’` 

## Environment

1. OS (where OpenCTI server runs): Debian GNU/Linux 10 (buster)
2. OpenCTI version: 6.4.0
3. OpenCTI client: Chrome
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Make a search, for example "ransomware"
2. Select some items in the search result
3. Trigger an export in PDF format

## Expected Output

A PDF document 

## Actual Output

An error message 

## Additional information

![Image](https://github.com/user-attachments/assets/4bc8e91c-a25c-4239-984d-40b1b75aabea)

**Comment by nino-filigran** [comment]
We have never supported the export of malware through PDF. As a result, I cannot categorize this as a bug but rather a feature if we would need to export it as a pdf.

**Comment by gkallenborn** [comment]
Hi. I think there is a misunderstanding. This feature should have been implemented as part of a projet with one of our client. The user story was about "exporting in PDF any search result". @SamuelHassine assured us that is was implemented, but is is not. What can we do now?

**Comment by SamuelHassine** [comment]
I confirm this is a but @nino-filigran. Check the error message of the connector. This feature is supported by the connector.

Can we please prioritize this as it was part of the project deliverables? Thanks!

**Comment by nino-filigran** [comment]
Ok we checked with @romain-filigran and missed this then. We'll push for this bug to be fixed then (since I4ve been able to reproduce)

**Comment by nino-filigran** [comment]
After testing, the confusion came that we had another error. We are able to reproduce and get the same error only when specifying a file marking.
