### ISSUE TITLE
[Bulk enrich] Available connectors are not displayed if "select all"

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#9126]
## Description

When I select the entities to enrich with a select all, I no longer have a connector listed

## Environment

OCTI 6.4.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go on Observations > Observables
2. Add a filter "entity_type=IPv4"
3. Select several IP
4. Open the enrichment panel -> you have several connector available

![Image](https://github.com/user-attachments/assets/40aca212-1d76-466c-8432-b9d7189278c2)

5. Now click on select all
6. Open the enrichment panel -> you have no more connectors

![Image](https://github.com/user-attachments/assets/2842900d-fec5-4ded-b891-1b21f8d3a7fc)

**Comment by romain-filigran** [comment]
Related to this: https://github.com/OpenCTI-Platform/opencti/issues/5582
@Gwendoline-FAVRE-FELIX : Could you have a look please ?
