### ISSUE TITLE
Bulk enrichment of observables in a container does not offer any enrichments when compared to an individual observable

### ISSUE THREAD

**Issue by damians-filigran** [LuatixHQ/opencti#9127]
## Description

In OpenCTI 6.4.1, it is possible to select multiple observables in a report and enrich them. However, this does not work in the cases tested.

## Environment

1. OS (where OpenCTI server runs): SaaS demo.octi, testing.octi
2. OpenCTI version: 6.4.1
3. OpenCTI client: Edge on MacOS
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a report. eg. [here](https://demo.octi.filigran.io/dashboard/analyses/reports/89e4dc6b-20ee-44c4-a903-a21099cb25c7/observables?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%2213637f39-0312-4a24-bee8-c81e1cae61f6%22%2C%22key%22%3A%22entity_type%22%2C%22values%22%3A%5B%22IPv4-Addr%22%5D%2C%22operator%22%3A%22eq%22%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&searchTerm=&sortBy=created_at&orderAsc=false)
2. Click an IP. eg. [here](https://demo.octi.filigran.io/dashboard/observations/observables/e8ba4202-e565-45e9-bbf4-e1aea9631196)
3. Click enrich to be offered AbuseIPDB, IPInfo, Shodan, etc.
4. Go back up to the [list of Observables](https://demo.octi.filigran.io/dashboard/analyses/reports/89e4dc6b-20ee-44c4-a903-a21099cb25c7/observables?filters=%7B%22mode%22%3A%22and%22%2C%22filters%22%3A%5B%7B%22id%22%3A%2213637f39-0312-4a24-bee8-c81e1cae61f6%22%2C%22key%22%3A%22entity_type%22%2C%22values%22%3A%5B%22IPv4-Addr%22%5D%2C%22operator%22%3A%22eq%22%2C%22mode%22%3A%22or%22%7D%5D%2C%22filterGroups%22%3A%5B%5D%7D&searchTerm=&sortBy=created_at&orderAsc=false)
5. Select any 3 IPv4 addresses
6. Click .... > Enrich
7. No enrichments are offered

## Expected Output

The same enrichment options should be offered

## Actual Output

No appropriate enrichments are found

## Additional information

Apologies if I'm missing something. I read 6.4 notes, and this option should apparently be possible; the quickest way to validate+report is via a GH issue

**Comment by nino-filigran** [comment]
@damians-filigran I do not reproduced on the links you gave.
- Here is the list I see when enriching only a single IP (from it's overview)
![Image](https://github.com/user-attachments/assets/03b5ca5f-b206-4847-9288-fec8f4c2c507)

- Here is the list I see when enriching from the observable list: 
![Image](https://github.com/user-attachments/assets/ce4c8f82-f96d-4035-ab96-16228d5cb666)

As a result, I'm closing this bug, but if it happens again, please re-open this one.

FYI I don't have a MAC so I tested on Chrome on PC

**Comment by damians-filigran** [comment]
ACk - works for me too now; thanks Nino.


***@***.***?anonymous&ep=signature>              Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
