### ISSUE TITLE
Colors of connectors list is not correct

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#9129]
## Description

![Image](https://github.com/user-attachments/assets/7cc51b5b-d59d-4ce5-8029-b3057b4a4497)

**Comment by SarahBocognano** [comment]
Has been resolved with : https://github.com/OpenCTI-Platform/opencti/commit/1261d0e4930bd6ddf1d6a9e4e8dc59e2ced9db5a

Back to normal on testing
