### ISSUE TITLE
[RSS] Brackets escaped in RSS feed

### ISSUE THREAD

**Issue by christiaanvaken** [LuatixHQ/opencti#9133]
When having a bracket inside a title of an article in a RSS feed, the brackets are escaped with backslashes.

Example:
Name \[1232\] - Description

Any idea if this can be solved?

**Comment by romain-filigran** [comment]
Hi @christiaanvaken. Thanks. I think it's a bug that we have to investigate.

For Filigran team: 

I have the same behavior when ingested RSS item with title containing bracket. Example with redpacketsecurity RSS Feed:

**Original RSS item**
![Image](https://github.com/user-attachments/assets/f54a5958-e91f-44c2-8d24-1e35b1c677ff)

**RSS Item in OpenCTI**
![Image](https://github.com/user-attachments/assets/fa2ccf3b-377f-4ac5-ae04-940771843b7e)
