### ISSUE TITLE
[Playbook] Adding assignee with playbook is not possible

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#9134]
## Description

New bulk editable field in 6.4 (e.g. assignee, participant, creator), are not available in playbooks.

NB: I don't know if this is a bug or a new feature, I'll let you decide.

## Environment

OCTI 6.4.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to the report list
2. Select two report
3. Update them : Add > Assignee 
-> Working well

![Image](https://github.com/user-attachments/assets/bd0612b1-7532-440b-8e9b-596a11598efa)

4. Now, create a playbook
5. Add a "Manipulate knowledge" component: Add > No "Assignee" available

![Image](https://github.com/user-attachments/assets/a132d629-aab7-4f1e-89bd-6e61c52d8156)

## Expected Output

Be able to add assignee with playbook

**Comment by romain-filigran** [comment]
duplicate of https://github.com/OpenCTI-Platform/opencti/issues/7728
