### ISSUE TITLE
ImportDoc connector Will not Automatically Create a Workbench When Uploading a PDF on the Data page of an Observable and Artifact

### ISSUE THREAD

**Issue by nhuber0724** [LuatixHQ/opencti#9136]
## Description

When uploading a PDF via the data tab on an observable or artifact page, the importdoc doc connectors will not automatically create a workbench. 

## Environment

OpenCTI v6.4.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Navigate to the data tab on an observable or artifact;
2. Upload a PDF;
3. the ImportDoc connector connector will automatically create a workbench
4. Check the data ingestion page for both connectors - they are set to automatic. 

## Expected Output

When uploading a PDF the connectors should automatically create a workbench

## Actual Output

No workbench is created. 

## Screenshots (optional)
![Image](https://github.com/user-attachments/assets/1c3d2dde-4e0f-4aeb-a009-e66605ba2aa4)

**Comment by nino-filigran** [comment]
Actually, workbench is created, but in the data/import section. The fix is to ensure that the workbench is created within the observable.

**Comment by nhuber0724** [comment]
@nino-filigran that's correct. When you import via the data tab on an observable or artifact, the workbench is not created.

**Comment by nino-filigran** [comment]
I've tested on demo and the workbench IS created, but is not created within the OBSERVABLE. It is only present in the DATA/Import

**Comment by nhuber0724** [comment]
@nino-filigran yes we'd like to see it in the actual observable and artifact.

**Comment by SouadHadjiat** [comment]
This issue is not a regression, it only worked for stix domain objects, it was not implemented at first for stix cyber observables.

**Comment by nino-filigran** [comment]
Thanks for your investigation @SouadHadjiat

**Comment by SouadHadjiat** [comment]
Fixed with PR https://github.com/OpenCTI-Platform/connectors/pull/3058
