### ISSUE TITLE
Feature Request: Restrict users to specific identities when updating entities

### ISSUE THREAD

**Issue by samczsun** [LuatixHQ/opencti#9161]
## Use case

I would like a way to ensure that a given user can only create entities with certain author identities. This is so that when my instance is sharing data with another instance, I can assure that the data (which only contains the author, and not the creator) is correctly attributed such that a compromised or malicious user can't create data and forge the author as someone else. This then allows recipients of the data to confidently use the data they receive from my instance depending on which user created it.

## Current Workaround

I could write a microservice to monitor for new intel and assert that the author field, if set, is an approved identity. However, native support would be preferred.

## Proposed Solution

Similar to how a user can be members of an organization, allow admins to select from all existing identities a subset of authorized identities that a user can use.

## If the feature request is approved, would you be willing to submit a PR?

I can try, but I'm not very familiar with this codebase and would not have much time to iterate on feedback

**Comment by Jipegien** [comment]
Hi @samczsun! Thanks a lot for your request!

Even if we understand your concern, we won't do this development as we consider the audit log feature and current RBAC/confidence system enough to ensure limitation and tracking of malicious behavior.
