### ISSUE TITLE
Unable to delete some relationships - mapping set to strict, dynamic introduction of [i_stop_time_year] within [_doc] is not allowed

### ISSUE THREAD

**Issue by yassine-ouaamou** [LuatixHQ/opencti#9173]
## Description

On an on-prem instance we are having the following error when trying to delete a Core relationship:

## Environment

6.2.8

## Reproducible Steps

Delete a relationship from Data > Relationships

## Actual Output

`"cause":{
                                 "type":"strict_dynamic_mapping_exception",
                                 "reason":"[1:88] mapping set to strict, dynamic introduction of [i_stop_time_year] within [_doc] is not allowed"
                              },`

## Additional information

In another instance with the same version, we are having a similar error but for a different field. Here is the error:
`mapping set to strict, dynamic introduction of [rel_has-reference] within [_doc] is not allowed`

**Comment by nino-filigran** [comment]
@yassine-ouaamou do you have more info regarding reproduction case?

**Comment by SouadHadjiat** [comment]
I have now all the information in an internal ticket @nino-filigran
