### ISSUE TITLE
Tasks becomes unknown after adding a task in Related entities of another task

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#9191]
## Reproducible Steps
- Go to a task overview
- Click on add a related entity
![Image](https://github.com/user-attachments/assets/612c3adc-646d-4b02-8f46-820bec1f12a4)

- Add a task
![Image](https://github.com/user-attachments/assets/e5808752-b53f-4e5f-b7c4-a818e91621b5)

The task is correctly added
![Image](https://github.com/user-attachments/assets/3632bf86-0b28-4729-9263-4e09092f0bdd)

- Reload the page, all the tasks names are 'unknown'
![Image](https://github.com/user-attachments/assets/e37b8215-42ad-42d6-90a0-2be3f262baa3)

**Comment by Lhorus6** [comment]
I don't know if it's related, but FYI: https://github.com/OpenCTI-Platform/opencti/issues/9521
