### ISSUE TITLE
[Playbook] Label application on Observable doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [LuatixHQ/opencti#9226]
## Description

Playbooks don't add labels if the **entity already contains one**. This effect seems to occur **only on Observable** objects.

## Environment

OCTI 6.4.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create two label "LabelA" and "LabelB"
2. Create an Observable Text and apply the LabelA on it
3. Create the following playbook
    - Listener on "update" event and "Entity type = Text"
    - Manipulate knowledge: Add -> Label -> LabelB
    - Send for ingestion
    - (start the playbook)

4. Go to the Observable Text and modify it (add a description for example)
5. Wait for the playbook to execute
-> No label added despite the correct execution of the playbook according to the execution traces

You can redo the same experiment without having a label on the observable at the beginning (so without adding "LabelA" at the start) -> you will see that it works

## Expected Output

I expect to have both labels, i.e. to have my old label LabelA, as well as my new label LabelB

## Actual Output

The new label is not added (the entity remains unchanged)

**Comment by romain-filigran** [comment]
Reproduced with Text observable. The label seems not correctly modelize in the stix bundle.
![Image](https://github.com/user-attachments/assets/571f41e1-ca7d-4eaf-996f-8aebf0f838a4)
