### ISSUE TITLE
In global search, header is blinking 2 times (2 re-renders)

### ISSUE THREAD

**Issue by SamuelHassine** [LuatixHQ/opencti#9227]
## Description

https://github.com/user-attachments/assets/42eaf744-788e-4f1f-9dac-9c2ea19aef44

**Comment by nino-filigran** [comment]
Reproduced on testing but not demo public.

**Comment by SamuelHassine** [comment]
My test was on the Filigran prod instance.

**Comment by SamuelHassine** [comment]
This is happening only the first time you search, so you have to full reload and then search.
