### ISSUE TITLE
Note & Opinion displayed as unknown in relationship creation form

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#9245]
## Description
Note displayed as unknown in relationship creation form

## Reproducible Steps
- Go to a malware
- Go to the knowledge tab
- Click on 'related entities' and 'create'
- in the list, select a note
![Image](https://github.com/user-attachments/assets/f33debce-e945-465a-94f0-ba12385736c3)

- In the form, the note is displayed as unknown
![Image](https://github.com/user-attachments/assets/7bcc68fa-f267-4421-a295-8d5a667ba8b1)

## Comment
Same for opinions

**Comment by nino-filigran** [comment]
Reproduced. Additionnally, I don't know if it's linked, but if you want to add it directly from the overview, you get an error (update indexing fail): 
- go in malware overview
- click on the + to add a note directly from the mawlare overview
- the drawer opens
- select a given note 
- you get an error message


https://github.com/user-attachments/assets/dbce24a6-7c17-46b3-b932-682e98fe6413
