### ISSUE TITLE
Error in 'Knowledge from container view' of Knowledge Observables

### ISSUE THREAD

**Issue by Archidoit** [LuatixHQ/opencti#9247]
## Description
The 'Knowledge from container view' is broken in Knowledge > Observables

## Reproducible Steps
- Go to a malware
- Go under the Knowledge view
- Select the 'observable' tab
- Click on the 'Knowledge from container view' button
![Image](https://github.com/user-attachments/assets/5c3467f1-b9df-41de-9cbc-8f78f363ec27)

- An error occurs

![Image](https://github.com/user-attachments/assets/5ed5aaa1-7ebc-470a-a348-b6b19907fcdf)

## Comment
Not reproduced for all the malwares

**Comment by Archidoit** [comment]
reproduced for PIVY Variant (08709f35581e0958d1ca4e50b7d86dba)

**Comment by nino-filigran** [comment]
I don't know if it's linked but on public demo, with malware "CQ KL, I can access the knowledge view of observable without problem (no observable linked.  But when I try to create a relation with an observable (tried with multiple types), I get a timeout.

**Comment by Archidoit** [comment]
@nino-filigran It's not linked :)

**Comment by Archidoit** [comment]
The error occurs when there are no containers in the 'Analyses' tab of the malware.
