### ISSUE TITLE
The default "Latest Reports" dashboard widget does not list recent reports

### ISSUE THREAD

**Issue by romain-filigran** [LuatixHQ/opencti#9264]
## Description

On the default/main platform dashboard, the “Latest reports” widget no longer seems to display the latest recent reports, but old reports.

Screenshot from demo public instance

![Image](https://github.com/user-attachments/assets/54ea88bd-f874-4158-8909-f469693b3444)

## Environment

2. OpenCTI version: 6.4.3

**Comment by ckane** [comment]
I'm seeing this behavior too, doing browser inspection, looks like the list is sorted by "asc" instead of descending order:
![Image](https://github.com/user-attachments/assets/b644c3f5-1162-40b9-8390-9c3a1f16244d)
