### ISSUE TITLE
Public dashboards for relationships distribution doesn't show any data

### ISSUE THREAD

**Issue by marieflorescontact** [LuatixHQ/opencti#9278]
## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. OpenCTI client: { e.g. frontend or python }
5. Other environment details:
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  Create custom dashboard with relationships distribution such as Donut and HorizontalBars (knowledge perspective).
2. Create a publicDashboard from the custom dashboard
3. Copy paste the publicdashboard link and open it in private session
4. No data displayed
## Actual Output

![Image](https://github.com/user-attachments/assets/ce30fcb5-94c6-46df-950d-5a0429e43800)

**Comment by nino-filigran** [comment]
@marieflorescontact  I do not reproduce: here's a link of public dashboard (done on Demo): https://demo.opencti.io/public/dashboard/publicdashboard
