### ISSUE TITLE
"Update indexing fails" error message when activating the "In carousel" button in a picture update / threat actor page

### ISSUE THREAD

**Issue by sancievanneaud** [LuatixHQ/opencti#9285]
## Description
In a threat actor page, when uploading a picture no matter the format (JPEG or PNG) and the marking definition, then activating the "In carousel" button the error message "Update indexing fails" appears and the update is not taken into account. So the picture doesn't display in the overview tab of the Threat actor. 

## Environment

2. OpenCTI version: 6.4.3

## Reproducible Steps
1. Go to a threat actor page
2. Upload a picture no matter the format (JPEG or PNG)
3. The picture appears in the Picture management section and then click on the picture
4. In the window that opens, check "In carousel" and then update
5. The error message appears "Update indexing fails"and the update is not taken into account. 

## Expected Output

Update confirmed, In carousel indicates "YES" and the picture appears in the overview tab of the Threat actor. 

## Actual Output

Update unconfirmed, In carousel indicates "NO" and the picture doesn't appear in the overview tab of the Threat actor. 

## Additional information
After running some tests, We succeeded in uploading to a specific threat actor page but not to another, even after changing the marking definition. We have not managed to find out why.
- Threat actor where the update doesn't work: https://testing.octi.staging.filigran.io/dashboard/threats/threat_actors_group/3ae09f0e-432e-458c-a5ae-76384fdd36b7/files

- Threat actor where the update works: https://testing.octi.staging.filigran.io/dashboard/threats/threat_actors_group/5746b00d-7646-453d-92b5-f91dc287debe

**Comment by nino-filigran** [comment]
Indeed, I struggle to reproduce on Demo. I'll get help with a dev.

**Comment by JeremyCloarec** [comment]
Bug is confirmed. It happens everytime a picture with a marking applied has been uploaded. Everytime we try to edit it in picture management afterwards, the error occurs.
