### ISSUE TITLE
Error when I try to access the report (OCTI OBAS)

### ISSUE THREAD

**Issue by savacano28** [LuatixHQ/opencti#9311]
## Description

When I try to acces to report https://testing.octi.staging.filigran.io/dashboard/analyses/reports/2bb71397-e3e2-4243-94b0-54a1e2b6d058, I get:
![Image](https://github.com/user-attachments/assets/e8aae1e9-480d-4aab-b4ac-03cf636a62d0)

I have the same error on demo: https://demo.octi.filigran.io/dashboard/analyses/reports/7582d2ba-afeb-4422-84be-10afc3ec6784

## Environment

1. OCTI Staging
2. OCTI Demo

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Filter reports: Report attack tests
2. Click on report

## Expected Output

I can see my report without error

## Actual Output

Error

## Additional information
Staging: https://testing.octi.staging.filigran.io/dashboard/analyses/reports/2bb71397-e3e2-4243-94b0-54a1e2b6d058
DEMO: https://demo.octi.filigran.io/dashboard/analyses/reports/7582d2ba-afeb-4422-84be-10afc3ec6784

- Probably, 'EmptyResult' is not extracted correctly. If I pass the following directly to extractExerciseResultByType: { unknown: 1, success: 0, failure: 0 }, I don't get any error.

## Screenshots (optional)

![Image](https://github.com/user-attachments/assets/c53ec1f5-7fda-4a61-a22e-ff6281a5effb)
![Image](https://github.com/user-attachments/assets/99473ae7-55d0-410c-a7f1-0d8f1f1d216b)

**Comment by nino-filigran** [comment]
FYI this bug is related to an OBAS test: a simulation has been launched on OBAS and @savacano28 was trying to access the the report to see the result of the scenario. But it's not accessible anymore.
