### ISSUE TITLE
Email Received from OpenCTI contains always a link to localhost

### ISSUE THREAD

**Issue by igniter07** [LuatixHQ/opencti#9343]
## Prerequisites

- [x] I read the [Deployment and Setup](https://docs.opencti.io/latest/deployment/overview) section of the OpenCTI documentation as well as the [Troubleshooting](https://docs.opencti.io/latest/deployment/troubleshooting) page and didn't find anything relevant to my problem.
- [x] I went through old GitHub issues and couldn't find anything relevant
- [x] I googled the issue and didn't find anything relevant

## Description

I am currently using OpenCTI, and I've noticed that the emails sent by the system always contain a URL that points to localhost. I would like to know how I can change this URL to point to my actual server address instead.

Could you please provide guidance on where to make this configuration change? Any help would be greatly appreciated!

## Environment

1. OS (where OpenCTI server runs): Debian 12
2. OpenCTI version: OpenCTI 6.4.3
3. OpenCTI client: frontend 

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install OpenCTI v6.4.3
2. Add the SMTP configuration to make opencti able to send emails.
3. Create an RFI case for example and check that the email is received
4. Check the link in the email (it will be localhost normally (127.0.0.1))

**Comment by Kedae** [comment]
Hi @igniter07,

Can you confirm that your base_url is correctly configured ?

**Comment by igniter07** [comment]
Hello @Kedae ,

Yes, my base_url is configured correctly and it looks ike this : 
https://192.168.1.7

**Comment by igniter07** [comment]
Any updates ?

the link appears like this:
![Image](https://github.com/user-attachments/assets/7b035916-d91b-467c-b13d-95502a3fc43b)

**Comment by Kedae** [comment]
Hi @igniter07,

Can you show the part of configuration where you set the base_url ?
Additionnaly, are you able to perform a GraphQL query on the playground and send the result ?

```
{
  settings {
    platform_url
  }
}

```

**Comment by igniter07** [comment]
@Kedae ,
I've set the base url in the .env file like this:

`OPENCTI_ADMIN_EMAIL=admin@opencti.io

OPENCTI_ADMIN_PASSWORD=<PASSWORD-MASKED>

OPENCTI_ADMIN_TOKEN=<TOKEN_MASKED>

OPENCTI_BASE_URL=https://192.168.56.155

OPENCTI_VERSION=6.4.3

MINIO_ROOT_USER=

...`


For the GraphQL query, here is the result (an error):


`{
  "errors": [
    {
      "message": "Fail to execute engine pagination",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "settings"
      ],
      "extensions": {
        "code": "DATABASE_ERROR",
        "data": {
          "http_status": 500,
          "genre": "TECHNICAL",
          "cause": {
            "options": {
              "redaction": {
                "type": "replace",
                "additionalKeys": []
              }
            },
            "name": "ConnectionError",
            "meta": {
              "statusCode": 0,
              "headers": {},
              "meta": {
                "context": null,
                "request": {
                  "params": {
                    "method": "POST",
                    "path": "/opencti_inferred_entities*%2Copencti_internal_objects*/_search",
                    "body": "{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"should\":[{\"bool\":{\"should\":[{\"multi_match\":{\"fields\":[\"entity_type.keyword\",\"parent_types.keyword\"],\"query\":\"Settings\"}}],\"minimum_should_match\":1}}],\"minimum_should_match\":1}}],\"must_not\":[]}},\"size\":500,\"sort\":[{\"standard_id.keyword\":\"asc\"}],\"track_total_hits\":true,\"_source\":true}",
                    "querystring": "",
                    "headers": {
                      "user-agent": "elasticsearch-js/8.15.0 (linux 6.1.0-26-amd64-x64; Node.js 20.18.0; Transport 8.9.1)",
                      "x-elastic-client-meta": "es=8.15.0,js=20.18.0,t=8.9.1,hc=20.18.0",
                      "content-type": "application/vnd.elasticsearch+json; compatible-with=8",
                      "accept": "application/vnd.elasticsearch+json; compatible-with=8",
                      "content-length": "319"
                    }
                  },
                  "options": {
                    "signal": {}
                  },
                  "id": 601159
                },
                "name": "elasticsearch-js",
                "connection": {
                  "url": "http://elasticsearch:9200/",
                  "tls": {
                    "ca": null,
                    "rejectUnauthorized": true
                  },
                  "id": "http://elasticsearch:9200/",
                  "timeout": 30000,
                  "headers": {
                    "user-agent": "elasticsearch-js/8.15.0 (linux 6.1.0-26-amd64-x64; Node.js 20.18.0; Transport 8.9.1)",
                    "x-elastic-client-meta": "es=8.15.0,js=20.18.0,t=8.9.1,hc=20.18.0"
                  },
                  "deadCount": 0,
                  "resurrectTimeout": 0,
                  "_openRequests": 0,
                  "weight": 1000,
                  "maxEventListeners": 100,
                  "pool": {
                    "_events": {},
                    "_eventsCount": 0
                  }
                },
                "attempts": 3,
                "aborted": false
              },
              "warnings": null
            }
          },
          "query": {
            "index": "opencti_inferred_entities*,opencti_internal_objects*",
            "track_total_hits": true,
            "_source": true,
            "body": {
              "query": {
                "bool": {
                  "must": [
                    {
                      "bool": {
                        "should": [
                          {
                            "bool": {
                              "should": [
                                {
                                  "multi_match": {
                                    "fields": [
                                      "entity_type.keyword",
                                      "parent_types.keyword"
                                    ],
                                    "query": "Settings"
                                  }
                                }
                              ],
                              "minimum_should_match": 1
                            }
                          }
                        ],
                        "minimum_should_match": 1
                      }
                    }
                  ],
                  "must_not": []
                }
              },
              "size": 500,
              "sort": [
                {
                  "standard_id.keyword": "asc"
                }
              ]
            }
          }
        }
      },
      "name": "DATABASE_ERROR"
    }
  ],
  "data": null
}`

**Comment by igniter07** [comment]
Hello, 
I confirm that the problem is resolved after getting a proper response from this query: 

`{
  settings {
    platform_url
  }
}
`

Thanks @Kedae  for your help.
