### ISSUE TITLE
[Dashboard] Latest Reports widget - main dashboard

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#9425]
## Description

Observed that for some customers the widget "Latest Report" on the main dashboard doesn't update on new reports (stuck on one date).

## Environment

OpenCTI version: 6.4.4

## Reproducible Steps

Open your instance on main dashboard

## Expected Output

See latest reports in the platform

## Actual Output

Stuck on an old date of reports

## Additional information

Working properly on "Testing" environment

## Screenshots

You can contact @EinatAR to see an example.

**Comment by romain-filigran** [comment]
@EinatAR : This issue is fixed in 6.4.5: https://github.com/OpenCTI-Platform/opencti/issues/9264
