### ISSUE TITLE
Advanced Search not loading with empty search term

### ISSUE THREAD

**Issue by EinatAR** [LuatixHQ/opencti#9452]
## Description

Advanced search option doesn't load when clicking it

## Environment

OpenCTI version: 6.4.4

## Reproducible Steps

1. Click the advanced search icon

## Expected Output

Window for advanced search and filters should open

## Actual Output

The platform loads but nothing happen (stuck on loading page)

## Screenshots (optional)

![Image](https://github.com/user-attachments/assets/198a7a6b-721e-4707-81da-2c1be6271e6c)

**Comment by romain-filigran** [comment]
Reproduced in version 6.4.5

**Comment by labo-flg** [comment]
Actually related to having no search terms. If you have a search term in the URL it works.
